### ISSUE TITLE
 List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout) yara.Error: internal error: 34

### ISSUE THREAD

**Issue by HughLu** [MobSF/Mobile-Security-Framework-MobSF#1014]
[ERROR] 23/Jul/2019 06:12:49 - Error Performing Static Analysis
Traceback (most recent call last):
  File "./Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "./Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 23/Jul/2019 06:12:49 - internal error: 34
[ERROR] 23/Jul/2019 06:12:49 - Internal Server Error: /StaticAnalyzer/
[ERROR] 23/Jul/2019 06:12:49 - "GET /StaticAnalyzer/?

## ENVIRONMENT

```
OS and Version: MaxOS Majave 10.14.5
Python Version:3.7
MobSF Version: Master branch
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```
1、 upload the apk

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```
[ERROR] 23/Jul/2019 06:12:49 - Error Performing Static Analysis
Traceback (most recent call last):
  File "./MobSF-Master/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "./Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 23/Jul/2019 06:12:49 - internal error: 34
[ERROR] 23/Jul/2019 06:12:49 - Internal Server Error: /StaticAnalyzer/
[ERROR] 23/Jul/2019 06:12:49 - "GET /StaticAnalyzer/?name=Cruzr_v1.37_201907121436_guonei_signed.apk&type=apk&checksum=c4f9a8a4e69117d55b90d00d013ff270 HTTP/1.1" 500 4796
[INFO] 23/Jul/2019 06:12:49 - "GET /static/css/font-awesome.min.css HTTP/1.1" 200 26711
[INFO] 23/Jul/2019 06:12:49 - "GET /static/css/ionicons.min.css HTTP/1.1" 200 51284
[INFO] 23/Jul/2019 06:12:49 - "GET /static/dash/css/skins/_all-skins.min.css HTTP/1.1" 200 41878
[INFO] 23/Jul/2019 06:12:49 - "GET /static/dash/css/AdminLTE.min.css HTTP/1.1" 200 89483
[INFO] 23/Jul/2019 06:12:49 - "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 122540
[INFO] 23/Jul/2019 06:12:49 - "GET /static/plugins/jQuery/jQuery-2.1.4.min.js HTTP/1.1" 200 84345
[DEBUG] 23/Jul/2019 06:12:49 - File /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py first seen with mtime 1545637506.0
[DEBUG] 23/Jul/2019 06:12:49 - File /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yara.cpython-37m-darwin.so first seen with mtime 1563849500.0
[DEBUG] 23/Jul/2019 06:12:49 - File /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/apkid.py first seen with mtime 1563848490.929075
[DEBUG] 23/Jul/2019 06:12:49 - File /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/rules.py first seen with mtime 1563848490.929663
[DEBUG] 23/Jul/2019 06:12:49 - File /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/output.py first seen with mtime 1563848490.929466
[DEBUG] 23/Jul/2019 06:12:49 - File /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/__init__.py first seen with mtime 1563848490.928748
[INFO] 23/Jul/2019 06:12:49 - "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 35951
[INFO] 23/Jul/2019 06:12:50 - "GET /static/plugins/fastclick/fastclick.min.js HTTP/1.1" 200 8776
[INFO] 23/Jul/2019 06:12:50 - "GET /static/css/style.css HTTP/1.1" 200 3541
[INFO] 23/Jul/2019 06:12:50 - "GET /static/js/jquery.bootstrap-growl.min.js HTTP/1.1" 200 1260
[INFO] 23/Jul/2019 06:12:50 - "GET /static/plugins/slimScroll/jquery.slimscroll.min.js HTTP/1.1" 200 6230
[INFO] 23/Jul/2019 06:12:50 - "GET /static/js/docs.js HTTP/1.1" 200 1581

**Comment by superpoussin22** [comment]
did you run setup.sh ?

**Comment by superpoussin22** [comment]
if yes did you have the headers install (Mojave no more install headers by default  ?
if not : 
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

setup.sh`

**Comment by HughLu** [comment]
> did you run setup.sh ?

Yes, install by setup.sh

**Comment by superpoussin22** [comment]
see my previous comment

**Comment by HughLu** [comment]
> see my previous comment

OK . I try it

**Comment by HughLu** [comment]
> see my previous comment

Hi, I reinstall the macOS_SDK_headers_for_macOS_10.14.pkg, and do setup.sh
run the MobSF,and upload the apk
have the same error :
File "./MobSF-Master/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 188, in static_analyzer
'app_dir'], app_dic['app_path'], app_dic['app_name'])
File "./Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
res = scanner.scan_file(apk_file)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/apkid.py", line 120, in scan_file
matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34

**Comment by superpoussin22** [comment]
do you have error during setup.sh ?

**Comment by HughLu** [comment]
> do you have error during setup.sh ?

no error.just have one warning : [WARNING] 23/Jul/2019 07:49:23 - Could not find VirtualBox path

**Comment by HughLu** [comment]
> do you have error during setup.sh ?

The V1.0.3 I used before is no this error. But V1.0.3 can not correct  check the apk sign version.

**Comment by superpoussin22** [comment]
can you rebbot ? and try setup again ?

**Comment by HughLu** [comment]
> can you rebbot ? and try setup again ?

OK .

**Comment by HughLu** [comment]
> can you rebbot ? and try setup again ?

It still run the same error.

**Comment by superpoussin22** [comment]
works fine for me on 10.14.5 can you post your full setup.sh output ?

**Comment by HughLu** [comment]
> works fine for me on 10.14.5 can you post your full setup.sh output ?

#!/bin/bash
if ! [ -x "$(command -v python3)" ]; then
  echo '[ERROR] python3 is not installed.' >&2
  exit 1
fi
echo '[INSTALL] Found Python3'

command
status=$?
cmd='python3 -m pip -V'
$cmd
status=$?
if [ $status -eq 0 ]; then
  echo '[INSTALL] Found pip'
  python3 -m pip install --upgrade pip
else
  echo "[ERROR] The command ($cmd) failed. python3-pip not installed"
  exit 1
fi

echo '[INSTALL] Installing virtualenv'
python3 -m pip install virtualenv
python3 -m virtualenv venv -p python3
source venv/bin/activate

unamestr=$(uname)
if [[ "$unamestr" == 'Darwin' ]]; then
  export ARCHFLAGS='-arch x86_64'
  export LDFLAGS='-L/usr/local/opt/openssl/lib'
  export CFLAGS='-I/usr/local/opt/openssl/include'  
fi

echo '[INSTALL] Installing APKiD requirements - yara-python'
pip install wheel
pip wheel --wheel-dir=/tmp/yara-python --build-option='build' --build-option='--enable-dex' git+https://github.com/VirusTotal/yara-python.git@v3.10.0
pip install --no-index --find-links=/tmp/yara-python yara-python

echo '[INSTALL] Installing Requirements'
pip install -r requirements.txt

echo '[INSTALL] Clean Up'
bash scripts/clean.sh y

echo '[INSTALL] Migrating Database'
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate
echo 'Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html'
echo '[INSTALL] Installation Complete'

**Comment by HughLu** [comment]
the setup result log:
`[INSTALL] Found Python3
pip 19.2 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
[INSTALL] Found pip
Requirement already up-to-date: pip in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (19.2)
[INSTALL] Installing virtualenv
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (16.2.0)
Requirement already satisfied: setuptools>=18.0.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv) (40.6.2)
Already using interpreter /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.7'
New python executable in ./Mobile-Security-Framework-MobSF/venv/bin/python3
Not overwriting existing python script ./Mobile-Security-Framework-MobSF/venv/bin/python (you must use ./Mobile-Security-Framework-MobSF/venv/bin/python3)
Installing setuptools, pip, wheel...
done.
[INSTALL] Installing APKiD requirements - yara-python
Requirement already satisfied: wheel in ./venv/lib/python3.7/site-packages (0.33.4)
Collecting git+https://github.com/VirusTotal/yara-python.git@v3.10.0
  Cloning https://github.com/VirusTotal/yara-python.git (to revision v3.10.0) to /private/tmp/pip-req-build-_vbkf_eu
Building wheels for collected packages: yara-python
  Building wheel for yara-python (setup.py): started
  Building wheel for yara-python (setup.py): finished with status 'done'
  Created wheel for yara-python: filename=yara_python-3.10.0-cp37-cp37m-macosx_10_9_x86_64.whl size=166904 sha256=ba7a301758ee475066bc90fe719d01a4f28a8c982e3343e0405108b075c13d14
  Stored in directory: /private/tmp/yara-python
Successfully built yara-python
Looking in links: /tmp/yara-python
Requirement already satisfied: yara-python in ./venv/lib/python3.7/site-packages (3.10.0)
[INSTALL] Installing Requirements
Requirement already satisfied: cryptography==2.6.1 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.6.1)
Requirement already satisfied: Django==2.2.3 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: pdfkit==0.6.1 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: androguard==3.3.5 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (3.3.5)
Requirement already satisfied: lxml==4.3.3 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (4.3.3)
Requirement already satisfied: rsa==4.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (4.0)
Requirement already satisfied: biplist==1.0.3 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.0.3)
Requirement already satisfied: requests==2.22.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.22.0)
Requirement already satisfied: bs4==0.0.1 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (0.0.1)
Requirement already satisfied: colorlog==4.0.2 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (4.0.2)
Requirement already satisfied: macholib==1.11 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.11)
Requirement already satisfied: play-scraper==0.5.5 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (0.5.5)
Requirement already satisfied: whitenoise==4.1.3 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (4.1.3)
Requirement already satisfied: click==6.7 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (6.7)
Requirement already satisfied: pyparsing==2.2.2 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (2.2.2)
Requirement already satisfied: capfuzz==0.0.1 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (0.0.1)
Requirement already satisfied: waitress==1.3.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (1.3.0)
Requirement already satisfied: gunicorn==19.9.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (19.9.0)
Requirement already satisfied: apkid==2.0.3 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (2.0.3)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python3.7/site-packages (from cryptography==2.6.1->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in ./venv/lib/python3.7/site-packages (from cryptography==2.6.1->-r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./venv/lib/python3.7/site-packages (from cryptography==2.6.1->-r requirements.txt (line 1)) (1.12.3)
Requirement already satisfied: pytz in ./venv/lib/python3.7/site-packages (from Django==2.2.3->-r requirements.txt (line 2)) (2019.1)
Requirement already satisfied: sqlparse in ./venv/lib/python3.7/site-packages (from Django==2.2.3->-r requirements.txt (line 2)) (0.3.0)
Requirement already satisfied: future in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (0.17.1)
Requirement already satisfied: ipython>=5.0.0 in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (7.6.1)
Requirement already satisfied: colorama in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: pydot>=1.4.1 in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (1.4.1)
Requirement already satisfied: matplotlib in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (3.1.1)
Requirement already satisfied: pygments in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (2.4.2)
Requirement already satisfied: networkx>=1.11 in ./venv/lib/python3.7/site-packages (from androguard==3.3.5->-r requirements.txt (line 4)) (2.3)
Requirement already satisfied: pyasn1>=0.1.3 in ./venv/lib/python3.7/site-packages (from rsa==4.0->-r requirements.txt (line 6)) (0.4.5)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests==2.22.0->-r requirements.txt (line 8)) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests==2.22.0->-r requirements.txt (line 8)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./venv/lib/python3.7/site-packages (from requests==2.22.0->-r requirements.txt (line 8)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests==2.22.0->-r requirements.txt (line 8)) (1.25.3)
Requirement already satisfied: beautifulsoup4 in ./venv/lib/python3.7/site-packages (from bs4==0.0.1->-r requirements.txt (line 9)) (4.8.0)
Requirement already satisfied: altgraph>=0.15 in ./venv/lib/python3.7/site-packages (from macholib==1.11->-r requirements.txt (line 11)) (0.16.1)
Requirement already satisfied: requests-futures>=0.9.7 in ./venv/lib/python3.7/site-packages (from play-scraper==0.5.5->-r requirements.txt (line 12)) (1.0.0)
Requirement already satisfied: mitmproxy==3.0.2 in ./venv/lib/python3.7/site-packages (from capfuzz==0.0.1->-r requirements.txt (line 16)) (3.0.2)
Requirement already satisfied: argparse in ./venv/lib/python3.7/site-packages (from apkid==2.0.3->-r requirements.txt (line 19)) (1.4.0)
Requirement already satisfied: yara-python==3.10.0 in ./venv/lib/python3.7/site-packages (from apkid==2.0.3->-r requirements.txt (line 19)) (3.10.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.6.1->-r requirements.txt (line 1)) (2.19)
Requirement already satisfied: decorator in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (4.4.0)
Requirement already satisfied: traitlets>=4.2 in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (4.3.2)
Requirement already satisfied: backcall in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (4.7.0)
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (41.0.1)
Requirement already satisfied: jedi>=0.10 in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.14.1)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (2.0.9)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.1.0)
Requirement already satisfied: pickleshare in ./venv/lib/python3.7/site-packages (from ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.7.5)
Requirement already satisfied: python-dateutil>=2.1 in ./venv/lib/python3.7/site-packages (from matplotlib->androguard==3.3.5->-r requirements.txt (line 4)) (2.8.0)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.7/site-packages (from matplotlib->androguard==3.3.5->-r requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: numpy>=1.11 in ./venv/lib/python3.7/site-packages (from matplotlib->androguard==3.3.5->-r requirements.txt (line 4)) (1.16.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.7/site-packages (from matplotlib->androguard==3.3.5->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: soupsieve>=1.2 in ./venv/lib/python3.7/site-packages (from beautifulsoup4->bs4==0.0.1->-r requirements.txt (line 9)) (1.9.2)
Requirement already satisfied: hyperframe<6,>=5.1.0 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (5.2.0)
Requirement already satisfied: passlib<1.8,>=1.6.5 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.7.1)
Requirement already satisfied: h11<0.8,>=0.7.0 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.7.0)
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.8)
Requirement already satisfied: h2<4,>=3.0.1 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (3.1.0)
Requirement already satisfied: sortedcontainers<1.6,>=1.5.4 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.5.10)
Requirement already satisfied: urwid<2.1,>=2.0.1 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (2.0.1)
Requirement already satisfied: pyperclip<1.7,>=1.5.22 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.6.5)
Requirement already satisfied: ldap3<2.5,>=2.4 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (2.4.1)
Requirement already satisfied: wsproto<0.12.0,>=0.11.0 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.11.0)
Requirement already satisfied: blinker<1.5,>=1.4 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (1.4)
Requirement already satisfied: brotlipy<0.8,>=0.7.0 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.7.0)
Requirement already satisfied: pyOpenSSL<17.6,>=17.5 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (17.5.0)
Requirement already satisfied: tornado<4.6,>=4.3 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (4.5.3)
Requirement already satisfied: ruamel.yaml<0.16,>=0.13.2 in ./venv/lib/python3.7/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (0.15.100)
Requirement already satisfied: ipython-genutils in ./venv/lib/python3.7/site-packages (from traitlets>=4.2->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.6.0)
Requirement already satisfied: parso>=0.5.0 in ./venv/lib/python3.7/site-packages (from jedi>=0.10->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.5.1)
Requirement already satisfied: wcwidth in ./venv/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=5.0.0->androguard==3.3.5->-r requirements.txt (line 4)) (0.1.7)
Requirement already satisfied: hpack<4,>=2.3 in ./venv/lib/python3.7/site-packages (from h2<4,>=3.0.1->mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 16)) (3.0.0)
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting python byte code files
Deleting temp and log files
Deleting DB
Deleting Secret File
Done
[INSTALL] Migrating Database
No changes detected
Migrations for 'StaticAnalyzer':
  StaticAnalyzer/migrations/0001_initial.py
    - Create model RecentScansDB
    - Create model StaticAnalyzerAndroid
    - Create model StaticAnalyzerIOSZIP
    - Create model StaticAnalyzerIPA
    - Create model StaticAnalyzerWindows
Operations to perform:
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  Applying StaticAnalyzer.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK
Operations to perform:
  Synchronize unmigrated apps: DynamicAnalyzer, MalwareAnalyzer, MobSF, messages, staticfiles
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
No changes detected
No changes detected in app 'StaticAnalyzer'
Operations to perform:
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete
`

**Comment by superpoussin22** [comment]
can you proviide the output of 

pip list | grep yara

**Comment by HughLu** [comment]
> pip list | grep yara

yara-python       3.10.0

**Comment by superpoussin22** [comment]
you launch mobsf using the run.sh right ?

**Comment by superpoussin22** [comment]
can you try 
source venv/bin/activate
pip uninstall yara-python
pip install upgrade wheel
pip wheel --wheel-dir=/tmp/yara-python --build-option='build' --build-option='--enable-dex' git+https://github.com/VirusTotal/yara-python.git@v3.10.0
pip install --no-index --find-links=/tmp/yara-python yara-python

**Comment by HughLu** [comment]
> can you try
> source venv/bin/activate
> pip uninstall yara-python
> pip uninstall apkid
> pip install upgrade wheel
> pip wheel --wheel-dir=/tmp/yara-python --build-option='build' --build-option='--enable-dex' git+https://github.com/VirusTotal/yara-python.git@v3.10.0
> pip install --no-index --find-links=/tmp/yara-python yara-python
> pip install -r requirements.txt

Thank you your help。 the MobSF run success。
I close it。but I found another bug in the master branch。
