### ISSUE TITLE
Error Geneating Dynamic Analysis Report

### ISSUE THREAD

**Issue by iceboym2m** [MobSF/Mobile-Security-Framework-MobSF#1015]
environment: MobSF on actual physical Kali; and use a Real Device(6.0.1) for testing APKs.
it works as a static analyzer correctly, but i have error in generating Dynamic report:
![Screenshot from 2019-07-23 12-18-07](https://user-images.githubusercontent.com/52599405/61693499-eaca0400-ad44-11e9-8dda-234c02d11f82.png)

**Comment by ajinabraham** [comment]
Please read how to report issues and do accordingly
