### ISSUE TITLE
[FEATURE] Migrate from virtualenv to venv

### ISSUE THREAD

**Issue by FranklinYu** [MobSF/Mobile-Security-Framework-MobSF#1017]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Use venv instead of virtualenv in `setup.sh` and `run.sh`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by superpoussin22** [comment]
why ?

**Comment by FranklinYu** [comment]
Because I don't want to install any package in my Python 3. venv is pre-installed. I installed Python 3 with MacPorts, so I need `sudo` for `pip`. More reasons to switch to venv is available in https://www.reddit.com/r/learnpython/comments/4hsudz/pyvenv_vs_virtualenv/

I thought it's widely accepted in Python community to prefer venv over virtualenv when both works.

**Comment by ajinabraham** [comment]
Addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1026
