### ISSUE TITLE
Signer Certificate Cannot check APK Verified using scheme version V1 or V2 or V1+V2

### ISSUE THREAD

**Issue by HughLu** [MobSF/Mobile-Security-Framework-MobSF#1020]
if I use the apksigner check the apk.
the result is :
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): false
Number of signers: 1

but the MobSF cannot provide the result

## ENVIRONMENT

```
OS and Version: imac 10.14
Python Version:
MobSF Version:
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

How can I do it for check the apk signer

**Comment by superpoussin22** [comment]
see PR #1036
