### ISSUE TITLE
[FEATURE]add  jadx support 

### ISSUE THREAD

**Issue by qtfreet00** [MobSF/Mobile-Security-Framework-MobSF#1022]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

jadx can easily transform apk to java_source,but use dex2jar ,you should first transform unzip apk,then convert dex to jar ,last use cfr to transform jar to java_source.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
                    ```
                    tracker_res = tracker.get_trackers()
                    apk_2_java(app_dic['app_path'], app_dic[
                              'app_dir'], app_dic['tools_dir'])
                    dex_2_smali(app_dic['app_dir'], app_dic['tools_dir'])
                   ```
```
def apk_2_java(app_path, app_dir, tools_dir):
    """Run jadx."""
    try:
        logger.info('APK -> JAVA')
        working_dir = None
        args = []
        output = os.path.join(app_dir, 'java_source/')
        logger.info('Using Apk converter - jadx')
        if (len(settings.JADX_BINARY) > 0
                and is_file_exists(settings.JADX_BINARY)):
            jadx = settings.JADX_BINARY
        else:
            if platform.system() == 'Windows':
                dex_2_jar(app_path,app_dir,tools_dir)
                jar_2_java(app_dir,tools_dir)
            else:
                jadx = os.path.join(tools_dir, 'jadx/bin/jadx')
                os.chmod(jadx, 0o777)
            args = [
                jadx,
                '-ds',
                output,
                '-r',
                '--show-bad-code',
                app_path,
            ]
            subprocess.call(args)
    except Exception:
        logger.exception('Converting APK to JAVA')
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by qtfreet00** [comment]
I haven't dealt with the environment on Windows yet, but it's a minor problem.

**Comment by superpoussin22** [comment]
@qtfreet00 
can you submit a PR ?
your code must be in converter.py  for the function 
think 744 should be enough for chmod 
need a jadx.txt file in LICENCES 

is it possible to safely remove gui part ? , we don't need it in mobsf

**Comment by qtfreet00** [comment]
ok,I will submit a PR later

**Comment by superpoussin22** [comment]
@qtfreet00  is '--show-bad-code' usuable ? It will put a lot of things in console but it won't be in the gui 
what about adding --deobf  ?

**Comment by superpoussin22** [comment]
working on it

**Comment by qtfreet00** [comment]
--deobf Only helpful when reversing an apk,this command will help us rename class and method name such as a,b,c to C100a,C101b and so on

this is the result when adding --deobf 

```
com/alipay/android/phone/mrpc/core/C1009q.java 
com/p017a/p018a/p019a/C0771e.java 
com/p017a/p018a/p019a/C0773g.java 
com/p017a/p018a/p019a/p020a/C0765b.java 
com/p017a/p018a/p021b/p022a/C0775b.java 
com/p017a/p018a/p021b/p022a/C0774a.java 
```

and it makes us diffcult to Locate the code problem

**Comment by superpoussin22** [comment]
@qtfreet00  yep I know .
Ther'e a branch jadx you can test . It doesn't install jadx but let you et it up in settings.py ( need to be setup twice) 
test it if you have time

**Comment by qtfreet00** [comment]
I have tested the jadx branch,works well

**Comment by superpoussin22** [comment]
in #1030
