### ISSUE TITLE
add documentation to the readme

### ISSUE THREAD

**Issue by Kunseok** [MobSF/Mobile-Security-Framework-MobSF#1023]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Currently there is no documentation to see what the out of box tests this tool does and I have to read through the tool's source code to determine how or what this checks for.

**Describe the solution you'd like**
Update/add to the readme with details about the standard features/tests being run.

Edit: Shortened for clarity.

**Comment by superpoussin22** [comment]
For me MobSF is a solution to HELP you to investigate and can point you in the right direction. But if someone is a real pentester, he shouldn't stop his work with an analysis done by a tool.
Explaining what MobsF is doing won't help, 
Static analysis is not an end on itself.

If a tool was able to do everything an replace the intelligence of a real pentester, all the pentester would  be forced to find another job 

This is My opinion ( And I'm sepaking only for me )

**Comment by ajinabraham** [comment]
MobSF helps in assisting finding issues and requires a person with Mobile Security knowledge to make the best use of it. It's up to the pentester to validate a finding before reporting. A static analysis tool works based on signatures and it's known to have false positives.

**Comment by oxr463** [comment]
I still think it is important to document the functionality of the tool.

**Comment by ajinabraham** [comment]
The functionality is Static and Dynamic Analysis. Output of all the checks are in the report generated with decent description. When you upload a binary, the console shows what MobSF is trying to do step by step.

Then again It's and open source tool. If you feel like there should be more information, feel free to send a PR to https://github.com/MobSF/docs

**Comment by oxr463** [comment]
> Then again It's and open source tool. If you feel like there should be more information, feel free to send a PR to https://github.com/MobSF/docs

Ah! So there is a place for documentation. This is helpful!
