### ISSUE TITLE
在启动MobSF时，一直报JDK 8+ is not available的问题，但我的JAVA环境已经正常安装。

### ISSUE THREAD

**Issue by cuiyuqi** [MobSF/Mobile-Security-Framework-MobSF#1024]
错误信息为：JDK 8+ is not available.Set JAVA_HOME  environment variable orJAVA_HOME in MobSF/settings.py
我本机的JAVA环境为JDK_1.8.0_201,安装路径为：C:\Program Files\Java\jdk1.8.0_201
求教各位大神

**Comment by ajinabraham** [comment]
Please use english for communication. 
You need to set `JAVA_DIRECTORY` in https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L302

In your case it will be 

`JAVA_DIRECTORY = C:/Program Files/Java/jdk1.8.0_201/bin/`

Also do not post support tickets in Github, join the slack channel.
GitHub issues are strictly for bugs only!

**Comment by ajinabraham** [comment]
We also made a hot fix for a java path issue in Windows. Update to the latest master branch
