### ISSUE TITLE
'NoneType' object is not subscriptable ?

### ISSUE THREAD

**Issue by kishore-kt** [MobSF/Mobile-Security-Framework-MobSF#1025]
In Browser

Don't Play Around. An Error just popped in!
Inappropriate argument type.

**'NoneType' object is not subscriptable**

in command prompt
==============

[ERROR] 29/Jul/2019 18:11:01 - Performing Code Analysis
Traceback (most recent call last):
  File "F:\Downloads\Chrome Downloads\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\code_analysis.py", line 63, in **code_analysis**
    errors='ignore',

**FileNotFoundError: [Errno 2] No such file or directory:** 

[ERROR] 29/Jul/2019 18:11:01 - Error Performing Static Analysis
Traceback (most recent call last):
  File "F:\Downloads\Chrome Downloads\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\static_analyzer.py", line 207, in static_analyzer
    code_an_dic['urls_list'].extend(

**TypeError: 'NoneType' object is not subscriptable**
[ERROR] 29/Jul/2019 18:11:01 - 'NoneType' object is not subscriptable
[ERROR] 29/Jul/2019 18:11:02 - Internal Server Error: /StaticAnalyzer/
[ERROR] 29/Jul/2019 18:11:02 - "GET /StaticAnalyzer/?name=app-release.apk&type=apk&checksum=f02324114c87cc372d674dee9e6ebf9e HTTP/1.1" 500 4848

## ENVIRONMENT
python 3.7
django 2.2.1
Mobile Security Framework v1.1.3

1. Installed and ran some sample APK's they ran without any issues ( such as whatsapp,facebook)
2. My APK throws this issue as well as (Instagram APK too)

**Comment by ajinabraham** [comment]
Incomplete information.

**Comment by kishore-kt** [comment]
Now Check brother

**Comment by ajinabraham** [comment]
Please share the problamatic APK for troubleshooting.

**Comment by kishore-kt** [comment]
Sorry Brother this is Office APK... having problem in share.. check Instagram APK... same issue Nonetype error in that too

**Comment by ajinabraham** [comment]
Try using the latest master. Instagram APK works for me. If you still see issues, share the exact APK.

**Comment by kishore-kt** [comment]
Thanks brother... after using uninstalling and installing the latest Mobsf.. this works fine without error...
