### ISSUE TITLE
[Version compatibility prompt question]MobSF has incorrect information for incompatible jdk version

### ISSUE THREAD

**Issue by snowlotusfly** [MobSF/Mobile-Security-Framework-MobSF#1027]
OS and Version:Win10
Python Version:Python 3.6.4
MobSF Version:Lastest
```

## EXPLANATION OF THE ISSUE

```
I hope this problem can be solved according to the prompts.
```


## STEPS TO REPRODUCE THE ISSUE

```
1. MobSF has installed
2.Jdk system environment variables are also configured
3.JAVA_DIRECTORY in MobSF/settings.py are also configured
```


## LOG FILE

```
[INFO] 30/Jul/2019 11:27:30 - MobSF Basic Environment Check
[ERROR] 30/Jul/2019 11:27:30 - JDK 8+ is not available. Set JAVA_HOME environment variable or JAVA_HOME in MobSF/settings.py
[INFO] 30/Jul/2019 11:27:30 - Current Configuration: JAVA_DIRECTORY=D:/Program Files/Java/jdk1.8.0_181/bin/
[INFO] 30/Jul/2019 11:27:30 - Example Configuration:
JAVA_DIRECTORY = "C:/Program Files/Java/jdk1.7.0_17/bin/"
```

<!--
BEFORE POSTING YOUR ISSUE/BUG
- These comments won't show up when you submit the issue.
- GitHub issues ARE NOT FOR FEATURE REQUESTS, SUPPORT, DISCUSSIONS AND QUESTIONS! 
- If you have questions, use our slack channel. Request invitation here https://goo.gl/6cYU5a.
- Reproduce issue in the latest master and try to add as much detail as possible.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.
- Once you open a bug, you should also provide additional information if requested. 
- Failure to do so in 25 days will result in closure of the bug without further communication.
-->

**Comment by snowlotusfly** [comment]
Maybe I should try Python35-32

**Comment by snowlotusfly** [comment]
Python 3.5.0 also has the same  problem,I also tried jdk1.7.0_02

**Comment by ajinabraham** [comment]
Please use the latest master. We did a hot fix for a path bug in Windows

**Comment by ajinabraham** [comment]
Feel free to comment if the issue exists

**Comment by snowlotusfly** [comment]
Haha, thank you for the speed of solving the problem.I want to wait for the startup to succeed and then close the problem.The network speed is too bad

**Comment by snowlotusfly** [comment]
yes,It works well,thanks a lot.  After this ,also experienced several problems like "internal error: 34" "invalid syntax (apkid.py, line 38)" ...
