### ISSUE TITLE
Is it Possible to dynamic testing in Docker?

### ISSUE THREAD

**Issue by kishore-kt** [MobSF/Mobile-Security-Framework-MobSF#1038]
If you need Dynamic Analysis do not setup MobSF inside a VM or use **Docker,** set it up in your Host OS.

**Comment by superpoussin22** [comment]
Not possible to use Docker for Dynamic testing.

Do you ask us to update documentation ?

If you have question please use the slack channel .

For discussions use our Slack Channel: https://mobsf.slack.com/ , Get Invitation: https://goo.gl/6cYU5a
