### ISSUE TITLE
update available notification but not updating.

### ISSUE THREAD

**Issue by bhavikp43** [MobSF/Mobile-Security-Framework-MobSF#1039]
[INFO] 06/Aug/2019 12:36:03 - 
  __  __       _    ____  _____           _   _   
 |  \/  | ___ | |__/ ___||  ___| __   __ / | / |
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | |
 | |  | | (_) | |_) |__) |  _|    \ V /  | |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/   |_(_)_|

[INFO] 06/Aug/2019 12:36:03 - Mobile Security Framework v1.1.4 Beta
REST API Key: 43fcde1a8bc1766a461c36d1329b8835902f88307e86fa3ec11b013775d13bd8
[INFO] 06/Aug/2019 12:36:03 - OS: Linux
[INFO] 06/Aug/2019 12:36:03 - Platform: Linux-4.19.0-kali5-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[INFO] 06/Aug/2019 12:36:03 - Dist: ('Kali', 'kali-rolling', 'kali-rolling')
[WARNING] 06/Aug/2019 12:36:03 - Could not find VirtualBox path
[INFO] 06/Aug/2019 12:36:03 - MobSF Basic Environment Check
[INFO] 06/Aug/2019 12:36:03 - Checking for Update.
Operations to perform:
  Synchronize unmigrated apps: DynamicAnalyzer, MalwareAnalyzer, MobSF, messages, staticfiles
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
[WARNING] 06/Aug/2019 12:36:03 - A new version of MobSF is available, Please update from master branch or check for new releases.

root@ABC:/tools/security/Mobile-Security-Framework-MobSF# git fetch
root@ABC:/tools/security/Mobile-Security-Framework-MobSF# git remote add origin https://github.com/MobSF/Mobile-Security-Framework-MobSF
fatal: remote origin already exists.
root@ABC:/tools/security/Mobile-Security-Framework-MobSF# git fetch
root@ABC:/tools/security/Mobile-Security-Framework-MobSF# git merge origin/master
Already up to date.

how to resolve?

**Comment by superpoussin22** [comment]
@bhavikp43 this is an error on our side will fix it today  PR #1040
