### ISSUE TITLE
[FEATURE] Customizable Report

### ISSUE THREAD

**Issue by Jnchi** [MobSF/Mobile-Security-Framework-MobSF#1041]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I would like to be able to remove the strings from the report, (See: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/347#issuecomment-281622455).

**Describe the solution you'd like**

Report generation takes a long time, and I don't typically see anything useful in the strings anyways.

If the report can be configured to only output certain sections, then it will allow for more flexibility.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by HughLu** [comment]
you can change the path pdf/*.html, delete content you don't care about  annotation them

**Comment by Jnchi** [comment]
Can you provide an example?

I'm running from the latest commit built the docker image from git.

In the web interface, after uploading and analyzing an ipa, if you right-click the Download Report button, and select Copy Link Location, <http://127.0.0.1:8000/PDF/?md5=7ddf32e17a6ac5ce04a8ecbf782ca509&type=IPA>.

Where would I go to generate an HTML report?

**Comment by ajinabraham** [comment]
You will have to create a fork of MobSF and remove string section from PDF templates here:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/tree/master/templates/pdf
For example: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/templates/pdf/android_binary_analysis.pdf.html#L854

And build the docker image locally if you need it dockerized.
We don't plan to support selective reporting at the moment.

**Comment by Jnchi** [comment]
Oh, that looks simple enough. Thanks!

**Comment by royalsniffer** [comment]
Hi Ajin, 

I have generated the Dynamic report, but the information are not much clear and explained. Please advise how to  customise the report as per OWASP top 10 vulnerability. 

Mart
