### ISSUE TITLE
Java hash code static analyzer rule

### ISSUE THREAD

**Issue by peja** [MobSF/Mobile-Security-Framework-MobSF#1048]
## EXPLANATION OF THE ISSUE

Android static analyzer has a rule to check if **hashCode()** method is being used in the code.

That method is integral part of Java (part of the **Object** class itself) and it's primarily used in types that are used as HashMap or HashSet keys. It is also generally recommended to override **hashCode()** method in every class that overrides **equals()**.

On the other hand, it's also used implicitly by Java compiler; for example, a very common use of strings inside of switch statements: 

```java
switch(s) {
    case "ONE": ... break;
    case "TWO": ... break;
}
```

Uses **hashCode()** method internally and would be decompiled and picked up by the static analyzer as:

```java
switch(s.hashCode()) {
    case 0x13246:
        if (s.equals("ONE")) {
            ...
        }
    break;
    case 0x1462c:
        if (s.equals("TWO")) {
            ...
        }
}
```

I think this static check should either be removed or have its _cvss_ score reduced to zero, because it triggers a lot of false positives.

**Comment by ajinabraham** [comment]
The reason why it's considered an issue is due to insecure implementations using it as a hash function. https://security.stackexchange.com/questions/52877/how-secure-is-javas-hashcode?answertab=votes#tab-top

Since it's a common thing in the java world. I will reduce the cvss score

**Comment by ajinabraham** [comment]
Hotfixed to master
