### ISSUE TITLE
Don't Play Around. An Error just popped in! None  internal error: 34

### ISSUE THREAD

**Issue by Kelds** [MobSF/Mobile-Security-Framework-MobSF#1063]
I'm the below error message when trying to scan Android apk files. I can scan iOS IPA files successfully without any error message.

[ERROR] 12/Aug/2019 09:07:56 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/me/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 186, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/Users/me/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 12/Aug/2019 09:07:56 - internal error: 34
[ERROR] 12/Aug/2019 09:07:56 - Internal Server Error: /StaticAnalyzer/

Your help will be well appreciated.
Thanks

**Comment by superpoussin22** [comment]
@Kelds which OS ?

**Comment by Kelds** [comment]
@superpoussin22 
Yes, I saw the below:

Please install macOS headers.
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

Pls help, am a beginner. How do I set the target to install it? 

Thank you.

**Comment by Kelds** [comment]
I get this:

installer: Error - the package path specified was invalid: '/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg'.

**Comment by superpoussin22** [comment]
please install command line utility as decribed in documentation 1st 

` xcode-select --install`
then 
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
then in mobsf 
`./setup.sh`

**Comment by Kelds** [comment]
Hi @superpoussin22  I have installed the header successfully following the instructions. 

now both apk and ipa gives error. the error for ipa files is below:

[ERROR] 12/Aug/2019 12:23:41 - Saving to DB
Traceback (most recent call last):
  File "/Users/me/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 163, in create_db_entry_ipa
    BIN_ANAL=bin_dict['bin_res'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 12/Aug/2019 12:23:41 - Rendering to Template
Traceback (most recent call last):
  File "/Users/me/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 34, in get_context_from_analysis_ipa
    'bin_anal': bin_dict['bin_res'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 12/Aug/2019 12:23:41 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/Users/me/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 181, in static_analyzer_ios
    context['VT_RESULT'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 12/Aug/2019 12:23:41 - 'NoneType' object does not support item assignment
[ERROR] 12/Aug/2019 12:23:41 - Internal Server Error: /StaticAnalyzer_iOS/

**Comment by superpoussin22** [comment]
ok so try this , to update the database:

`python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate`

**Comment by Kelds** [comment]
@superpoussin22 done.

same error message.

**Comment by superpoussin22** [comment]
so start with a clean database:  
` cat ./scripts/clean.sh`

**Comment by Kelds** [comment]
@superpoussin22 

It now works. it didn't work after running ./scripts/clean.sh. I had to delete everything and installed afresh. 

Thank you so much.

**Comment by ajinabraham** [comment]
Running setup.sh will essentially reinstall everything
