### ISSUE TITLE
[FEATURE]General Report. When the pdf page loads,How Can I an additional JS file is executed

### ISSUE THREAD

**Issue by HughLu** [MobSF/Mobile-Security-Framework-MobSF#1065]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.
I need count the number of  all the high-level bugs in the pdf report.
Through js calculation the high-level and pass value to tag id.
I found the pdf report is not load the js.
How can I do

**Comment by HughLu** [comment]
How can I change the wkhtmltopdf default setting. --run-sript can make after page loads to addition js。

**Comment by ajinabraham** [comment]
We won't be doing that at the moment in official repo since we are working on a major UI and PDF report revamp.
You can modify the settings if it's supported in here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/shared_func.py#L261

**Comment by HughLu** [comment]
> We won't be doing that at the moment in official repo since we are working on a major UI and PDF report revamp.
> You can modify the settings if it's supported in here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/shared_func.py#L261

Thanks so much
