### ISSUE TITLE
file path error in windows env

### ISSUE THREAD

**Issue by FallenGavin** [MobSF/Mobile-Security-Framework-MobSF#1066]
How can I dear with this error, 

"""
[INFO] 14/Aug/2019 11:10:22 - Mobile Security Framework v1.1.6 Beta
[INFO] 14/Aug/2019 11:10:22 - OS: Windows
[INFO] 14/Aug/2019 11:10:22 - Platform: Windows-10-10.0.17134-SP0
[INFO] 14/Aug/2019 11:10:22 - MobSF Basic Environment Check
[INFO] 14/Aug/2019 11:10:22 - Checking for Update.
[INFO] 14/Aug/2019 11:10:23 - No updates available.
[ERROR] 14/Aug/2019 11:10:29 - [WinError 3] 系统找不到指定的路径。: 'D:\\tools\\mobsf\\Mobile-Security-Framework-MobSF\\uploads/a1ae528ee6aa36e67237df5c73b6c691\\java_source\\kotlin\\coroutines\\experimental\\intrinsics\\IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnchecked$$inlined$buildContinuationByInvokeCall$IntrinsicsKt__IntrinsicsJvmK.java'
[ERROR] 14/Aug/2019 11:10:29 - Internal Server Error: /delete_scan/
[INFO] 14/Aug/2019 11:11:01 - MIME Type: application/vnd.android.package-archive FILE: mier_im_debug.apk
[INFO] 14/Aug/2019 11:11:01 - Performing Static Analysis of Android APK
[INFO] 14/Aug/2019 11:11:01 - Starting Analysis on : mier_im_debug.apk
[INFO] 14/Aug/2019 11:11:01 - Generating Hashes
[INFO] 14/Aug/2019 11:11:01 - Unzipping
[INFO] 14/Aug/2019 11:11:04 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Aug/2019 11:11:04 - APK Extracted
[INFO] 14/Aug/2019 11:11:04 - Converting AXML to XML
[INFO] 14/Aug/2019 11:11:16 - Reading Android Manifest
[INFO] 14/Aug/2019 11:11:16 - Parsing AndroidManifest.xml
[INFO] 14/Aug/2019 11:11:17 - Fetching icon path
[INFO] 14/Aug/2019 11:11:18 - Extracting Manifest Data
[INFO] 14/Aug/2019 11:11:18 - Fetching Details from Play Store: com.mi.oa.mierim.test
[WARNING] 14/Aug/2019 11:11:18 - Unable to get app details.
[INFO] 14/Aug/2019 11:11:18 - Manifest Analysis Started
[INFO] 14/Aug/2019 11:11:18 - Static Android Binary Analysis Started
[INFO] 14/Aug/2019 11:11:18 - Static Android Resource Analysis Started
[INFO] 14/Aug/2019 11:11:18 - Reading Code Signing Certificate
[INFO] 14/Aug/2019 11:11:18 - Running APKiD 2.0.3
[INFO] 14/Aug/2019 11:11:27 - Trackers Database is up-to-date
[INFO] 14/Aug/2019 11:11:27 - Detecting Trackers
[INFO] 14/Aug/2019 11:11:31 - APK -> JAVA
[INFO] 14/Aug/2019 11:11:31 - Decompiling to Java with jadx
[ERROR] 14/Aug/2019 11:11:31 - Decompiling to JAVA
Traceback (most recent call last):
  File "D:\tools\mobsf\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\converter.py", line 63, in apk_2_java
    shutil.rmtree(output)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\tools\\mobsf\\Mobile-Security-Framework-MobSF\\uploads/a1ae528ee6aa36e67237df5c73b6c691/java_source/kotlin\\coroutines\\experimental\\intrinsics\\IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnchecked$$inlined$buildContinuationByInvokeCall$IntrinsicsKt__IntrinsicsJvmK.java'
[INFO] 14/Aug/2019 11:11:31 - DEX -> SMALI
[INFO] 14/Aug/2019 11:11:31 - Converting classes.dex to Smali Code
[INFO] 14/Aug/2019 11:11:34 - Converting classes2.dex to Smali Code
[INFO] 14/Aug/2019 11:11:44 - Converting classes3.dex to Smali Code
[INFO] 14/Aug/2019 11:11:58 - Converting classes4.dex to Smali Code
[INFO] 14/Aug/2019 11:12:09 - Static Android Code Analysis Started
[INFO] 14/Aug/2019 11:12:09 - Code Analysis Started on - java_source
[INFO] 14/Aug/2019 11:12:11 - Finished Code Analysis, Email and URL Extraction
[INFO] 14/Aug/2019 11:12:11 - Extracting Strings from APK
[INFO] 14/Aug/2019 11:12:14 - Detecting Firebase URL(s)
[INFO] 14/Aug/2019 11:12:14 - Performing Malware Check on extracted Domains
[INFO] 14/Aug/2019 11:12:20 - Malware Database is up-to-date
[INFO] 14/Aug/2019 11:12:20 - Generating Java and Smali Downloads
[INFO] 14/Aug/2019 11:12:20 - Generating Downloads
[INFO] 14/Aug/2019 11:12:20 - Zipping
[ERROR] 14/Aug/2019 11:12:20 - Zipping
Traceback (most recent call last):
  File "D:\tools\mobsf\Mobile-Security-Framework-MobSF\MobSF\utils.py", line 445, in zipdir
    zip_file.write(f_path)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1713, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 506, in from_file
    st = os.stat(filename)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\tools\\mobsf\\Mobile-Security-Framework-MobSF\\uploads/a1ae528ee6aa36e67237df5c73b6c691/java_source/kotlin\\coroutines\\experimental\\intrinsics\\IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnchecked$$inlined$buildContinuationByInvokeCall$IntrinsicsKt__IntrinsicsJvmK.java'
[INFO] 14/Aug/2019 11:12:20 - Zipping
[ERROR] 14/Aug/2019 11:12:35 - Zipping
Traceback (most recent call last):
  File "D:\tools\mobsf\Mobile-Security-Framework-MobSF\MobSF\utils.py", line 445, in zipdir
    zip_file.write(f_path)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1713, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "C:\Users\guanyu\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 506, in from_file
    st = os.stat(filename)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\tools\\mobsf\\Mobile-Security-Framework-MobSF\\uploads/a1ae528ee6aa36e67237df5c73b6c691/smali_source/kotlin\\coroutines\\experimental\\intrinsics\\IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnchecked$$inlined$buildContinuationByInvokeCall$IntrinsicsKt__IntrinsicsJvmKt$1.smali'
[INFO] 14/Aug/2019 11:12:35 - Connecting to Database
[INFO] 14/Aug/2019 11:12:35 - Saving to Database
"""

**Comment by superpoussin22** [comment]
did you run setup.bat ?

**Comment by FallenGavin** [comment]
> did you run setup.bat ?

Yes ,and i check all of them ,but the log show that  path was wrong.  I think the 
problem is  the file path  has   "\ " and "\\"  .   

![image](https://user-images.githubusercontent.com/23303142/63002307-3a18d580-bea8-11e9-8c2e-98ad343fd362.png)

Is it a problem with path stitching ?

**Comment by FallenGavin** [comment]
> did you run setup.bat ?
Github  has escaped the double slash and backslash, so I still take a screenshot

**Comment by superpoussin22** [comment]
strange all our build pass the test :( 
can you run setup.bat again ?

**Comment by FallenGavin** [comment]
> strange all our build pass the test :(
> can you run setup.bat again ?

OK,I will try it again.

**Comment by ajinabraham** [comment]
@FallenGavin please share the problamatic APK for troubleshooting. The path slashes shouldn't really matter. The exception says file not found. It might be something else.

**Comment by ajinabraham** [comment]
Closing due to no response
