### ISSUE TITLE
Don't Play Around. An Error just popped in! internal error: 34

### ISSUE THREAD

**Issue by JROUT53** [MobSF/Mobile-Security-Framework-MobSF#1068]
## ENVIRONMENT
Android

```
OS and Version: Windows 10 v10.0 Build 17763 _(Version 10.0.17763.678)_
Python Version:  v3.6.4:d48eceb
MobSF Version: Mobile Security Framework v1.1.6 Beta
```
## EXPLANATION OF THE ISSUE
I am unable to see the report as Error 34 appears after uploading the build.

## STEPS TO REPRODUCE THE ISSUE

```
1. Installed MobSF from git
2. Opened Localhost and dragged the apk file.
3. App uploaded 100% but the error appears 

'Don't Play Around. An Error just popped in!
None
internal error: 34'

The following appears in the CMD screen.
```
[ERROR] 19/Aug/2019 16:16:35 - Error Performing Static Analysis
Traceback (most recent call last):
  File "D:\X\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\static_analyzer.py", line 186, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "D:\X\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views\apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "d:\X\mobile-security-framework-mobsf-master\venv\lib\site-packages\apkid\apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 19/Aug/2019 16:16:35 - internal error: 34
[ERROR] 19/Aug/2019 16:16:35 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/
```

Paste the contents of logs/debug.log here or attach the log file.
```
![image](https://user-images.githubusercontent.com/50312301/63260447-9ca21500-c29e-11e9-9f87-836738efdbb7.png)

**Comment by superpoussin22** [comment]
did you run setup.bat ?

**Comment by JROUT53** [comment]
This is happening every time. I have run setup.bat twice.

**Comment by JROUT53** [comment]
I also tried the steps in https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1063
no result

**Comment by superpoussin22** [comment]
you have no error on setup ?

**Comment by ajinabraham** [comment]
Error 34 is due to APKiD install failure. Make sure APKiD is installed correctly. This is not a bug. For any discussions, use slack channel
