### ISSUE TITLE
[FEATURE] Improve security scoring of apps

### ISSUE THREAD

**Issue by peja** [MobSF/Mobile-Security-Framework-MobSF#1069]
Currently, app score is calculated as:

```python
avg_cvss = round(sum(cvss_scores) / len(cvss_scores), 1)
app_score = int((10 - avg_cvss) * 10)
```

Since average CVSS score is used, it could happen that if an app has one major issue and multiple minor ones, it would score better than if it only had a major issue.

For example, if an issue is introduced to an app that already has higher average cvss than that issue, app would actually have higher score than before even though it now has more issues.

This could be a problem for CI workflow because it will not catch regression in that case.

I suggest using a different scoring scheme that would calculate scores as 100 - percentage of maximum CVSS for a particular platform, or any other scheme that would avoid using averages.

**Comment by ajinabraham** [comment]
I see your point. Will look into alternative scoring mechanisms.

**Comment by ajinabraham** [comment]
@peja Yes, I got your point. Calculating security score from CVSS is not a good idea. I am going to look into alternate scoring mechanisms.

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1110

**Comment by god0fcode** [comment]
Hi Ajin,

i am scanning the app but in spite of various high and dangerous my app security score is 100

**Comment by god0fcode** [comment]
Is there any way to do changes in app scoring

**Comment by ajinabraham** [comment]
What version of MobSF are you using?

**Comment by god0fcode** [comment]
I am using the latest version 
I tried to make changes in sharedfunction  file
It takes only the value defined initially app score which is 100. Though the findings included various dangerous and high vulnerability. 
I have written a code in my cicd which stop the release of build based on the scoring so I need scoring to be perfect

**Comment by ajinabraham** [comment]
Generate a PDF report and see how the score is calculated. It's documented at the bottom

**Comment by god0fcode** [comment]
The problem is App score is not calculated based on the formula. Intially CVSS is 0 and appscore is 100, PDF report doesnt generate the report based on the formula, it takes the static value

**Comment by god0fcode** [comment]
def score(findings):
    # Score Apps based on AVG CVSS Score
    cvss_scores = []
    avg_cvss = 0
    app_score = 100
only these values are returned

**Comment by ajinabraham** [comment]
What version of MobSF are you?
The latest version have changes in how App Security score is calculated. it's based on code analysis findings and not cvss

**Comment by ajinabraham** [comment]
![screenshot_2020-02-20_at_6 05 28_pm](https://user-images.githubusercontent.com/4301109/75094295-d9a1d980-5557-11ea-8cbe-30955930d18a.png)

**Comment by god0fcode** [comment]
Got your point, But how can we edit the source code analysis finding risk scoring as for now scoring is calculated based on the code analysis result, which is not giving fair result at all

**Comment by ajinabraham** [comment]
I dont understand why it's not fair. This is the scoring mechanism we flow. if you are seeing issues, please share the APKs for troubleshooting

**Comment by god0fcode** [comment]
APK i am using is internal to project. but if you could guide me to edit the scoring of code analysis it would be great. i can manually adjust the scoring.

**Comment by ajinabraham** [comment]
All the logic for scoring is here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/shared_func.py#L557-L590

**Comment by ajinabraham** [comment]
And in case of android the `level` considered for scoring is available here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/android_rules.py

**Comment by god0fcode** [comment]
Let me try once more

**Comment by god0fcode** [comment]
Hi Ajin,

I have made certain changes and scanned almost 10 diffrent APK. The problem remain the same. Average CVSS and Secure Score comes as 0 and 100 which we have set initially. If i change these value to say 10 and 70 the score in PDF comes as 10 and 70. I dont know why?

**Comment by ajinabraham** [comment]
I can't help without a sample APK to replicate the issue. I see no such issues at my end.

**Comment by god0fcode** [comment]
https://play.google.com/store/apps/details?id=com.petstationa1&hl=en&pli=1

**Comment by god0fcode** [comment]
Please check and confirm

**Comment by god0fcode** [comment]
Any updates

**Comment by ajinabraham** [comment]
Works fine for me.
[pets.pdf](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4245971/pets.pdf)

Use slack channel for further discussions.
