### ISSUE TITLE
Mobsf Root CA error & ADB not installing apk on virtual box vm

### ISSUE THREAD

**Issue by specters312** [MobSF/Mobile-Security-Framework-MobSF#1070]
Hello hope your day is going well, I was trying to setup your tool which has been really fun so far :D I cant seem to work my way around this issue and the dynamic analysis issue. 

**BACKGROUND**
I compiled from source on MAC 10.14.5 and am using the Oracle virtual box version 5.2 and I am using the VM supplied in the documentation.

**ISSUE**
It seems after the mitmproxy connects it disconnects possibly causing the APK not to install on the device. Also when it seems the root ca is never pushed to the device.

**log**

> [INFO] 20/Aug/2019 17:04:58 - VM Starting
> [ERROR]` 20/Aug/2019 17:04:58 - Error Downloading File screen/screen.png
> [ERROR] 20/Aug/2019 17:04:58 - Internal Server Error: /download/screen/screen.png
> [INFO] 20/Aug/2019 17:05:01 - Setting up Dynamic Analysis Environment
> [INFO] 20/Aug/2019 17:05:01 - Connecting to VM/Device
> daemon not running; starting now at tcp:5037
> Capture Module Loaded
> Proxy server listening at http://*:1337
> daemon started successfully
> [INFO] 20/Aug/2019 17:05:04 - ADB Started
> [INFO] 20/Aug/2019 17:05:04 - Waiting for 5 seconds...
> 192.168.56.101:44319: clientconnect --> What I think the Issue is
> 192.168.56.101:44319: clientdisconnect 
> 192.168.56.101:40228: clientconnect
> 192.168.56.101:40228: clientdisconnect --> Proxy disconnects before installing apk
> [INFO] 20/Aug/2019 17:05:09 - Connecting to VM/Device
> [INFO] 20/Aug/2019 17:05:09 - Mounting
> [INFO] 20/Aug/2019 17:05:09 - Starting App for Dynamic Analysis
> [INFO] 20/Aug/2019 17:05:09 - Installing APK
> [INFO] 20/Aug/2019 17:05:12 - Launching APK Main Activity
> [INFO] 20/Aug/2019 17:05:12 - Testing Environment is Ready!
> [INFO] 20/Aug/2019 17:05:12 - Getting Screen Resolution
> [INFO] 20/Aug/2019 17:05:12 - Installing MobSF RootCA
> [INFO] 20/Aug/2019 17:05:12 - Starting Clipboard Dump Service in VM/Device
> 192.168.56.101:50328: clientconnect
> 192.168.56.101:50328: clientdisconnect

**Root CA Issue**
> [ERROR]` 20/Aug/2019 17:05:51 - MobSF RootCA Handler
> Traceback (most recent call last):
>   File "/Users/nrivera/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py", line 371, in mobsf_ca
>     ca_file], True)
> UnboundLocalError: local variable 'ca_file' referenced before assignment
> [ERROR] 20/Aug/2019 17:05:51 - Error in RootCA Handler

**End log**

**My Troubleshooting**
Assuming its a dependency issue I ran `rm -rf venv/` and `pip uninstall mitmproxy`. 
This resulted in the same issue so then I tried `rm -rf Mobile-Security-Framework-MobSF/`and pip uninstalled all the requirements as well as mitmproxy. 
still did not work 😞

**Comment by specters312** [comment]
Please let me know if there is anything I can supply to help troubleshoot :D

**Comment by specters312** [comment]
Looks like the issue might just be the apk, trying a couple other apks

**Comment by ajinabraham** [comment]
@specters312 

We are making a lot of changes to dynamic analysis at the moment. Please do not use the current dynamic analyzer. If you are adventurous enough, you can try our new Work in Progress branch `geny`. Would also help us as well to make sure things are working well before we officially release it.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1067
Before running dynamic analysis, you need to run a Genymotion Android VM version 4.1 to 4.4

1. In settings.py, 
* Configure adb path with the one used by Genymotion
`ADB_BINARY = '/Applications/Genymotion.app/Contents/MacOS/tools/adb'`
* Set `ANALYZER_IDENTIFIER = '192.168.56.113:5555'` to the IP of your Genymotion VM
2. Configure Proxy IP inside Genymotion VM WiFi settings for intercepting web traffic, which may be 192.168.56.1:1337 in your case.
3. Once Xposed is installed, reboot, enable all the modules and reboot VM before analysis.

Also some APKs won't respect the proxy. You need to use the xposed module ssl unpinning to force them. 

If you need any help or assistance use our slack channel. Github issues is strictly for bugs.

**Comment by specters312** [comment]
Thank you :D Ill play around with it and update here!
