### ISSUE TITLE
Error in Running Dynamic Analysis using genymotion

### ISSUE THREAD

**Issue by kishore-kt** [MobSF/Mobile-Security-Framework-MobSF#1072]
[INFO] 22/Aug/2019 18:19:40 - Setting up Dynamic Analysis Environment
[INFO] 22/Aug/2019 18:19:40 - Connecting to VM/Device
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Capture Module Loaded
Proxy server listening at http://*:1337
[INFO] 22/Aug/2019 18:19:44 - ADB Started
[INFO] 22/Aug/2019 18:19:44 - Waiting for 5 seconds...
[INFO] 22/Aug/2019 18:19:49 - Connecting to VM/Device
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Only one usage of each socket address (protocol/network address/port) is normally permitted. (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

**Comment by ajinabraham** [comment]
Genymotion is not supported by master. If you want to run Genymotion. use the branch `geny`. It is a work in progress.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1067

Before running dynamic analysis, you need to run a Genymotion Android VM version 4.1 to 4.4

1. In settings.py, 
* Configure adb path with the one used by Genymotion
`ADB_BINARY = '/Applications/Genymotion.app/Contents/MacOS/tools/adb'`
* Set `ANALYZER_IDENTIFIER = '192.168.56.113:5555'` to the IP of your Genymotion VM
2. Configure Proxy IP inside Genymotion VM WiFi settings for intercepting web traffic, which may be `192.168.56.1:1337.
3. Once Xposed is installed, reboot, enable all the modules and reboot VM before analysis.

Also some APKs won't respect the proxy. You need to use the xposed module ssl unpinning to force them. 

If you need any help or assistance use our slack channel. Github issues is strictly for bugs.
