### ISSUE TITLE
Docker booting worker with pid taking a very long time to run

### ISSUE THREAD

**Issue by AkashBhagat174** [MobSF/Mobile-Security-Framework-MobSF#1076]
## ENVIRONMENT

```
OS and Version:Windows 7
Python Version:3.7.4
MobSF Version:latest
```

## EXPLANATION OF THE ISSUE

Docker booting worker with pid taking a very long time to run.This is first time run on the system .

## STEPS TO REPRODUCE THE ISSUE
Following the steps as per documentation to install mobsf

## LOG FILE

```
 docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
2019-08-28 10:24:21 +0000] [1] [INFO] Starting gunicorn 19.9.0               
2019-08-28 10:24:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)   
2019-08-28 10:24:21 +0000] [1] [INFO] Using worker: threads                   
2019-08-28 10:24:21 +0000] [8] [INFO] Booting worker with pid: 8              
```

**Comment by superpoussin22** [comment]
how many time ?

**Comment by AkashBhagat174** [comment]
This is the first time I am running mobsf. 
after the command:- docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
mobsf hasn't run even a single time. I kept the system running for entire night and still it hasn't run.

Also checked 0.0.0.0:8000 and localhost:8000. Unable to connect there

**Comment by superpoussin22** [comment]
can you run it without it ?

exemple :
docker run -d --name mobsf -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

then if you want to access shell do

docker exec -it mobsf /bin/bash

**Comment by AkashBhagat174** [comment]
I can access the shell after command docker exec -it mobsf /bin/bash as:-

$ docker exec -it mobsf /bin/bash
root@f849131b2e32:~/Mobile-Security-Framework-MobSF#

However after the logs command this is the output:-

C:\Users\Akash Bhagat>docker logs -f --tail 100 mobsf
[2019-08-29 06:55:25 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-08-29 06:55:25 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-08-29 06:55:25 +0000] [1] [INFO] Using worker: threads
[2019-08-29 06:55:25 +0000] [8] [INFO] Booting worker with pid: 8

**Comment by superpoussin22** [comment]
did http://localhost:8000 work ? 
can you check you don't have a proxy configured ?

**Comment by AkashBhagat174** [comment]
No.localhost and 0.0.0.0 don't work. Have no proxy configured

**Comment by superpoussin22** [comment]
can you try with another browser and I think move to slack channel more easy to help

**Comment by ajinabraham** [comment]
There is no bug in docker image. I just checked that. Please join our slack channel for further troubleshooting.

**Comment by alexandrevvo** [comment]
Mobsf hang because there was no internet connection from inside docker..

Removing the docker0 interface and restarting it resolved. https://stackoverflow.com/questions/39828185/no-internet-connection-inside-docker-containers
