### ISSUE TITLE
need information about MobSF performance improvement

### ISSUE THREAD

**Issue by sampa2410** [MobSF/Mobile-Security-Framework-MobSF#1078]
Please help understanding the parameter "--threads=4" in run.bat. Could it be possible to improve performance by optimizing this parameter value? Or any other way to improve the performance of analysis.

**Comment by ajinabraham** [comment]
Github is strictly for bug reports. Use Slack channel for discussions.

**Comment by sampa2410** [comment]
Hi, Could you please help me with the particular channel link where I can post this query.
