### ISSUE TITLE
Jadx within MobSF tentative out of memory issue

### ISSUE THREAD

**Issue by artikrh** [MobSF/Mobile-Security-Framework-MobSF#1079]
## ENVIRONMENT

```
OS and Version: Kali GNU/Linux Rolling 2019.3 (Linux 5.2.0-kali2-amd64)
Python Version: 3.7.4
MobSF Version: 1.1.6 Beta
```

## EXPLANATION OF THE ISSUE

Large application files (APKs) - typically over 70mb - get stuck during static analysis at the java decompling phase. Before analyzing the APK with MobSF, I initially tried to decompile the referenced app with [`dex2jar`](https://github.com/pxb1988/dex2jar/) and I had the same problems with `java.lang.OutOfMemoryError: Java heap space`, however, I manually typed the `java` command and increased the Java memory allocation to 3gb; and it worked.  

Since MobSF uses `jadx`, I do not have much control over the decompiler in terms of modifying the number of thread usage and memory allocation. Correct me if I am wrong, but the default setup of MobSF uses 4gb of memory (which is more than enough I think), however, something queer is happening with the number of threads.  

In the `jadx` repository, you can reduce the number of threads using the `-j` switch, but the problem is that I was unsuccessful in finding where the `jadx` command is issued so I can add a `-j 1` option; in other words, use a single thread.

The `java` processes get stuck and CPU usage does not go down as seen in the following picture:

![image](https://user-images.githubusercontent.com/38540757/64176042-e40ed080-ce5c-11e9-8167-700a8e01e553.png)

Monitoring `/uploads` indicates no I/O activity after the thread hang (typically after 70 seconds of static analysis) - therefore, the process cannot go on even if I wait for longer times - which is what I would expect.

## STEPS TO REPRODUCE THE ISSUE

```
1. Launch MobSF
2. Upload the APK sample at the web interface
3. Monitor `htop` and notice the massive RAM usage; after more than a minute, the decompiling process hangs but CPU and RAM usage do not go down (I have to manually `pkill -9 java`).
```

## LOG FILE

```
  __  __       _    ____  _____           _   _
 |  \/  | ___ | |__/ ___||  ___| __   __ / | / |
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | |
 | |  | | (_) | |_) |__) |  _|    \ V /  | |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/   |_(_)_|


[INFO] 03/Sep/2019 09:09:11 - Mobile Security Framework v1.1.6 Beta
[INFO] 03/Sep/2019 09:09:11 - OS: Linux
[INFO] 03/Sep/2019 09:09:11 - Platform: Linux-5.2.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[INFO] 03/Sep/2019 09:09:11 - Dist: ('Kali', 'kali-rolling', 'kali-rolling')
[INFO] 03/Sep/2019 09:09:11 - MobSF Basic Environment Check
[INFO] 03/Sep/2019 09:09:11 - Checking for Update.
[INFO] 03/Sep/2019 09:09:12 - No updates available.
[INFO] 03/Sep/2019 09:09:12 - MIME Type: application/vnd.android.package-archive FILE: base.apk
[INFO] 03/Sep/2019 09:09:13 - Performing Static Analysis of Android APK
[INFO] 03/Sep/2019 09:09:13 - Starting Analysis on : base.apk
[INFO] 03/Sep/2019 09:09:13 - Generating Hashes
[INFO] 03/Sep/2019 09:09:14 - Unzipping
[INFO] 03/Sep/2019 09:09:16 - Getting Hardcoded Certificates/Keystores
[INFO] 03/Sep/2019 09:09:16 - APK Extracted
[INFO] 03/Sep/2019 09:09:16 - Reading Android Manifest
[INFO] 03/Sep/2019 09:09:16 - Parsing AndroidManifest.xml
[INFO] 03/Sep/2019 09:09:23 - Fetching icon path
[INFO] 03/Sep/2019 09:09:30 - Extracting Manifest Data
[INFO] 03/Sep/2019 09:09:30 - Fetching Details from Play Store: com.xiaomi.hm.health
[INFO] 03/Sep/2019 09:09:31 - Manifest Analysis Started
[INFO] 03/Sep/2019 09:09:31 - Static Android Binary Analysis Started
[INFO] 03/Sep/2019 09:09:31 - Static Android Resource Analysis Started
[INFO] 03/Sep/2019 09:09:31 - Reading Code Signing Certificate
[INFO] 03/Sep/2019 09:09:31 - Running APKiD 2.0.3
[INFO] 03/Sep/2019 09:09:39 - Trackers Database is up-to-date
[INFO] 03/Sep/2019 09:09:39 - Detecting Trackers
[INFO] 03/Sep/2019 09:09:43 - APK -> JAVA
[INFO] 03/Sep/2019 09:09:43 - Decompiling to Java with jadx
[INFO] 03/Sep/2019 10:42:07 -
```

**Comment by superpoussin22** [comment]
by default jadx is launched with those parameters

`DEFAULT_JVM_OPTS="\"-Xms128M\" \"-Xmx4g\" \"-XX:+UseG1GC\"`

**Comment by superpoussin22** [comment]
go in ./StaticAnalyser/tools/jadx/bin/ and edit jadx script if you want make tests

**Comment by artikrh** [comment]
> go in ./StaticAnalyser/tools/jadx/bin/ and edit jadx script if you want make tests

Alright, after playing around a bit I finally resolved the issue. Since I am on Linux, I noticed the `jadx` shell script for UNIX systems and noticed these two lines:  

```
# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $JADX_OPTS -classpath "\"$CLASSPATH\"" jadx.cli.JadxCLI "$APP_ARGS"
```

Nonetheless, there was no `$JADX_OPTS` declared so I manually added it after `$DEFAULT_JVM_OPTS`:

```
JADX_GUI_OPTS='"-j 1"'
```  

Now the MobSF process was much easier on the CPU, therefore, the decompile process took a bit longer but it successfully ran. Thank you @superpoussin22 for the heads up!
