### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AndrewR777** [MobSF/Mobile-Security-Framework-MobSF#1081]
Don't Play Around. An Error just popped in!
Inappropriate argument type.

'NoneType' object is not subscriptable
================================

I get this error scanning "DIVA Android" application, available here: https://github.com/tjunxiang92/Android-Vulnerabilities/raw/master/diva-beta.apk

The Mobile framework version is MobSF v1.1.6 Beta.
This is a docker build - it runs on the smallest Digital Ocean droplet. I can provide root access to the droplet, if it helps.

**Comment by ajinabraham** [comment]
Incomplete logs

**Comment by AndrewR777** [comment]
Hi,
What logs do you need? I can provide any file or full access to the system.

**Comment by AndrewR777** [comment]
Sorry for not providing the logs from the \Docker!
Here it is:

[INFO] 10/Sep/2019 19:15:14 - Starting Analysis on : diva-beta.apk
[INFO] 10/Sep/2019 19:15:14 - Generating Hashes
[INFO] 10/Sep/2019 19:15:14 - Unzipping
[INFO] 10/Sep/2019 19:15:14 - Getting Hardcoded Certificates/Keystores
[INFO] 10/Sep/2019 19:15:14 - APK Extracted
[INFO] 10/Sep/2019 19:15:14 - Reading Android Manifest
[INFO] 10/Sep/2019 19:15:14 - Parsing AndroidManifest.xml
[INFO] 10/Sep/2019 19:15:14 - Fetching icon path
[INFO] 10/Sep/2019 19:15:14 - Extracting Manifest Data
[INFO] 10/Sep/2019 19:15:14 - Fetching Details from Play Store: jakhar.aseem.diva
[WARNING] 10/Sep/2019 19:15:14 - Unable to get app details.
[INFO] 10/Sep/2019 19:15:14 - Manifest Analysis Started
[INFO] 10/Sep/2019 19:15:14 - Static Android Binary Analysis Started
[INFO] 10/Sep/2019 19:15:14 - Static Android Resource Analysis Started
[INFO] 10/Sep/2019 19:15:14 - Reading Code Signing Certificate
[ERROR] 10/Sep/2019 19:15:14 - Reading Code Signing Certificate
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py", line 68, in cert_info
    cert_path) if os.path.isfile(os.path.join(cert_path, f))]
FileNotFoundError: [Errno 2] No such file or directory: '/root/.MobSF/uploads/77a9be5009f7ca26534b58fe57f8d712/META-INF/'
[INFO] 10/Sep/2019 19:15:14 - Running APKiD 2.0.3
[INFO] 10/Sep/2019 19:15:15 - Trackers Database is up-to-date
[INFO] 10/Sep/2019 19:15:15 - Detecting Trackers
[INFO] 10/Sep/2019 19:15:16 - APK -> JAVA
[INFO] 10/Sep/2019 19:15:16 - Decompiling to Java with jadx
[INFO] 10/Sep/2019 19:15:20 - DEX -> SMALI
[INFO] 10/Sep/2019 19:15:20 - Converting classes.dex to Smali Code
[INFO] 10/Sep/2019 19:15:24 - Static Android Code Analysis Started
[INFO] 10/Sep/2019 19:15:24 - Code Analysis Started on - java_source
[INFO] 10/Sep/2019 19:15:24 - Finished Code Analysis, Email and URL Extraction
[INFO] 10/Sep/2019 19:15:24 - Extracting Strings from APK
[INFO] 10/Sep/2019 19:15:25 - Detecting Firebase URL(s)
[INFO] 10/Sep/2019 19:15:25 - Performing Malware Check on extracted Domains
[INFO] 10/Sep/2019 19:15:25 - Malware Database is up-to-date
[INFO] 10/Sep/2019 19:15:25 - Generating Java and Smali Downloads
[INFO] 10/Sep/2019 19:15:25 - Generating Downloads
[INFO] 10/Sep/2019 19:15:25 - Zipping
[INFO] 10/Sep/2019 19:15:25 - Zipping
[INFO] 10/Sep/2019 19:15:26 - Connecting to Database
[INFO] 10/Sep/2019 19:15:26 - Saving to Database
[ERROR] 10/Sep/2019 19:15:26 - Saving to DB
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 255, in create_db_entry
    CERT_INFO=cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:15:26 - Rendering to Template
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 120, in get_context_from_analysis
    'certinfo': cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:15:26 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 269, in static_analyzer
    'security_score'] = score(context['findings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:15:26 - 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:15:26 - Internal Server Error: /api/v1/scan
[INFO] 10/Sep/2019 19:22:28 - MIME Type: application/vnd.android.package-archive FILE: diva-beta.apk
[INFO] 10/Sep/2019 19:22:28 - Performing Static Analysis of Android APK
[INFO] 10/Sep/2019 19:22:28 - Starting Analysis on : diva-beta.apk
[INFO] 10/Sep/2019 19:22:28 - Generating Hashes
[INFO] 10/Sep/2019 19:22:28 - Unzipping
[INFO] 10/Sep/2019 19:22:28 - Getting Hardcoded Certificates/Keystores
[INFO] 10/Sep/2019 19:22:28 - APK Extracted
[INFO] 10/Sep/2019 19:22:28 - Reading Android Manifest
[INFO] 10/Sep/2019 19:22:28 - Parsing AndroidManifest.xml
[INFO] 10/Sep/2019 19:22:28 - Fetching icon path
[INFO] 10/Sep/2019 19:22:28 - Extracting Manifest Data
[INFO] 10/Sep/2019 19:22:28 - Fetching Details from Play Store: jakhar.aseem.diva
[WARNING] 10/Sep/2019 19:22:28 - Unable to get app details.
[INFO] 10/Sep/2019 19:22:28 - Manifest Analysis Started
[INFO] 10/Sep/2019 19:22:28 - Static Android Binary Analysis Started
[INFO] 10/Sep/2019 19:22:28 - Static Android Resource Analysis Started
[INFO] 10/Sep/2019 19:22:28 - Reading Code Signing Certificate
[ERROR] 10/Sep/2019 19:22:28 - Reading Code Signing Certificate
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py", line 68, in cert_info
    cert_path) if os.path.isfile(os.path.join(cert_path, f))]
FileNotFoundError: [Errno 2] No such file or directory: '/root/.MobSF/uploads/77a9be5009f7ca26534b58fe57f8d712/META-INF/'
[INFO] 10/Sep/2019 19:22:28 - Running APKiD 2.0.3
[INFO] 10/Sep/2019 19:22:29 - Trackers Database is up-to-date
[INFO] 10/Sep/2019 19:22:29 - Detecting Trackers
[INFO] 10/Sep/2019 19:22:30 - APK -> JAVA
[INFO] 10/Sep/2019 19:22:30 - Decompiling to Java with jadx
[INFO] 10/Sep/2019 19:22:34 - DEX -> SMALI
[INFO] 10/Sep/2019 19:22:34 - Converting classes.dex to Smali Code
[INFO] 10/Sep/2019 19:22:38 - Static Android Code Analysis Started
[INFO] 10/Sep/2019 19:22:38 - Code Analysis Started on - java_source
[INFO] 10/Sep/2019 19:22:38 - Finished Code Analysis, Email and URL Extraction
[INFO] 10/Sep/2019 19:22:38 - Extracting Strings from APK
[INFO] 10/Sep/2019 19:22:38 - Detecting Firebase URL(s)
[INFO] 10/Sep/2019 19:22:38 - Performing Malware Check on extracted Domains
[INFO] 10/Sep/2019 19:22:39 - Malware Database is up-to-date
[INFO] 10/Sep/2019 19:22:39 - Generating Java and Smali Downloads
[INFO] 10/Sep/2019 19:22:39 - Generating Downloads
[INFO] 10/Sep/2019 19:22:39 - Zipping
[INFO] 10/Sep/2019 19:22:39 - Zipping
[INFO] 10/Sep/2019 19:22:39 - Connecting to Database
[INFO] 10/Sep/2019 19:22:39 - Saving to Database
[ERROR] 10/Sep/2019 19:22:39 - Saving to DB
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 255, in create_db_entry
    CERT_INFO=cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:22:39 - Rendering to Template
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 120, in get_context_from_analysis
    'certinfo': cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:22:39 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 269, in static_analyzer
    'security_score'] = score(context['findings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:22:39 - 'NoneType' object is not subscriptable
[ERROR] 10/Sep/2019 19:22:39 - Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
@AndrewR777 That APK doesn't have signer certificate info
Use the APK from http://web.archive.org/web/20160616232157/http://www.payatu.com/wp-content/uploads/2016/01/diva-beta.tar.gz

**Comment by AndrewR777** [comment]
Hi ajinabraham,

working with a non-singed build is a norm (at list for us).
Should't the Framework scan the build anyway? It is completely possible!

**Comment by ajinabraham** [comment]
What do you mean? Are you referring to `debug` mode?
If that is the case we do support that since it is signed by Android debug cert.

**Comment by ajinabraham** [comment]
@AndrewR777 To clarify that is not even a valid APK. You cannot install that to an android device as it's mandatory to have a code signing cert (release/debug) IIRC.

```
$  adb install /Users/ajinabraham/Downloads/boo.apk
Performing Push Install
boo.apk: 1 file pushed. 80.1 MB/s (1475989 bytes in 0.018s)
	pkg: /data/local/tmp/boo.apk
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]
```

**Comment by AndrewR777** [comment]
The scan should not stop - it just fails with exception because the Framework does not find a certificate.

At least **it would be nice to return a meaningful error**.
Please, consider it - I do hope it will make this application better!

...Thank you for your efforts.

**Comment by ajinabraham** [comment]
We can't just scan a file that is not a valid and working APK. Certificate Analysis is a major thing. (To identify accidental release of debug mode apks or modified malware infected apks) We don't proceed if it fails.

Also we don't stop the scan process if one component fail as you can see from the logs. This is a major error and it triggered other errors. Looking at `[ERROR]` in logs will tell you *detailed and meaningful error*. There is no single error that can be displayed since there is a chain of errors triggered by the first major exception.

But we are working on a similar thing to handle it gracefully since we see a lot of `HACKED_META` dirs added packers, obfuscators etc.
