### ISSUE TITLE
[FEATURE]I want to scan multiple apps at once

### ISSUE THREAD

**Issue by bay0max** [MobSF/Mobile-Security-Framework-MobSF#1082]
I can drag several apps into the dropzone,but it just analysis one app at once,if I want to see result of another app in recent scans,it will do analysis after I click view button.if there is a task queue for analysis,it will be convenient to do analysis for all apps .

**Comment by superpoussin22** [comment]
you can use the mass_static_analysis.py script :)

**Comment by bay0max** [comment]
> you can use the mass_static_analysis.py script :)

I run this python script with command 
`python3 mass_static_analysis.py -d /apks -s 127.0.0.1:8000 -r 0  -k 0`
 but the termination just print
 `performing upload XXX.apk`
and end without doing analysis.Is there something wrong with my arguments? in fact I don't know the meaning of "-k" argument

**Comment by superpoussin22** [comment]
-k must be followed by your api key which can be found if you click on API doc link on MobSF interface

**Comment by superpoussin22** [comment]
please go to slack fo rmore questions
