### ISSUE TITLE
Decompiling error on the Docker image

### ISSUE THREAD

**Issue by r3pek** [MobSF/Mobile-Security-Framework-MobSF#1083]
## ENVIRONMENT

```
OS and Version: Official Docker Image from DockerHub (opensecurity/mobile-security-framework-mobsf)
```

## EXPLANATION OF THE ISSUE

While decompiling a project, this error is logged on the console:
```
[ERROR] 20/Sep/2019 07:38:27 - Decompiling to JAVA
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/converter.py", line 64, in apk_2_java
    if (len(settings.JADX_BINARY) > 0
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'JADX_BINARY'
```

**Comment by superpoussin22** [comment]
Does it appear after upgrading the docker image or from a fresh install ?

**Comment by r3pek** [comment]
@superpoussin22 i think it was an upgrade from 1.0.x 

This is my docker-compose.yml:
```
version: '3.4'

services:
    app:
        image: opensecurity/mobile-security-framework-mobsf
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        volumes:
            - data:/root/.MobSF
        networks:
            - traefik_net

volumes:
    data:
        driver: n0r1skcom/docker-volume-cephfs
        driver_opts:
            <snip>
```

**Comment by r3pek** [comment]
btw, I have a few of this on the logs:
django.db.utils.OperationalError: table StaticAnalyzer_staticanalyzerandroid has no column named REAL_NAME

I'll can try with a clean DB and report back

**Comment by r3pek** [comment]
OK, I'll close it since the clean database makes it work again normally. Might have something to do with the upgrade itself (but can't confirm right now)

**Comment by superpoussin22** [comment]
yes in your volume you have a config.py  which reflect the settings.py with some custom parameters ste at startup, this file is for the moment not updated so the problem come from this point
