### ISSUE TITLE
Venv requirement does not shecking while installing

### ISSUE THREAD

**Issue by berkayyildi** [MobSF/Mobile-Security-Framework-MobSF#1085]
In kali linux when python3 and pip3 installed but  python3-venv is not installed it does not works.
So it needs `apt-get install python3-venv`
Setup.py script can check it..

**Comment by ajinabraham** [comment]
This is clearly mentioned in the Documentation: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#requirements
