### ISSUE TITLE
[FEATURE] Export Application Permissions as XLSX

### ISSUE THREAD

**Issue by AresS31** [MobSF/Mobile-Security-Framework-MobSF#1089]
For technical reporting purposes, it could be nice to have a feature to export the "Application Requested Permissions" as an Excel spreadsheet. Additionally, it would be interesting to export all the different sections from the static analysis as Excel spreadsheets too (and not be restricted to the PDF version).

**Comment by ajinabraham** [comment]
We currently support PDF and JSON response. Other formats of low priority, but open to pull requests. Enhancements are tracked separately.

**Comment by ajinabraham** [comment]
Duplicate of #248
