### ISSUE TITLE
[FEATURE] Sortable Tables

### ISSUE THREAD

**Issue by AresS31** [MobSF/Mobile-Security-Framework-MobSF#1090]
MobSF display findings in Tables which is a good approach but to further improve this approach I suggest to make the Table sortable.

**Comment by ajinabraham** [comment]
Could you please elaborate?
Tracked separately

**Comment by aress31** [comment]
When I say sortable table, what I mean is for example being able to sort the permission table by severity level in the web interface, or by permission name...

**Comment by aress31** [comment]
Why has this issue been closed and marked as lacking of info? The title is self explanatory and I provided additional information. The goal of this ticket is to request for sortable table feature, e.g. 

![image](https://user-images.githubusercontent.com/11601622/128425424-377cb9b2-dc10-481c-bee8-ecbd8809ec88.png)

**Comment by ajinabraham** [comment]
We do support sorting tables.
<img width="1252" alt="Screen Shot 2021-08-05 at 3 43 16 PM" src="https://user-images.githubusercontent.com/4301109/128430778-3c37e02e-933e-4aa9-a8ba-e89f0f865a57.png">
