### ISSUE TITLE
PERMISSION DANGEROUS

### ISSUE THREAD

**Issue by abdymm** [MobSF/Mobile-Security-Framework-MobSF#1098]
Hi, I just got an output from APK Static Analysis from MobSF, and I got some permission dangerous status, like INTERNET, CAMERA, EXTERNAL STORAGE and etc, what is that means? 
I mean in general, we need that permission in android, what should i do so I can get a normal status?

**Comment by ajinabraham** [comment]
Permission Analysis is more.focused on the Malware Analysis side, where you analyze a third party APK to identify it's capabilities. It is a permission that can be abused if it's misused. For example a calculator apk doesn't need the Internet permission.

**Comment by abdymm** [comment]
@ajinabraham but my apps need internet permission and the others permission, how?

**Comment by abdymm** [comment]
how @ajinabraham ? can you give us a solution, please

**Comment by ajinabraham** [comment]
If it's a needed permission , you can ignore the finding. Having a severity Dangerous doesn't mean the permission is dangerous. It is a permission that can be abused by a malicious app. Like I said this is only useful when analysing malicious third party apps.

**Comment by abdymm** [comment]
oh, ok i miss the "this is only useful when analyzing malicious third-party apps" words, so if thas my own apps, it can be ignored?

**Comment by abdymm** [comment]
but it will included into CVSS Score and App Security score, isn't it?

**Comment by ajinabraham** [comment]
Yes, if you are sure that the permission is needed by your app.

**Comment by abdymm** [comment]
but it will included into CVSS Score and App Security score, isn't it?

**Comment by ajinabraham** [comment]
GitHub issues are only for bug reports, please use our slack channel for discussions

**Comment by abdymm** [comment]
ok sorry man @ajinabraham
