### ISSUE TITLE
[FEATURE] Add button to redownload APK from MobSF

### ISSUE THREAD

**Issue by baharkhalid** [MobSF/Mobile-Security-Framework-MobSF#1101]
Request to add another button to download the APK from MobSF database. 

I setup a machine with MobSF and share it with my team. Sometime my team interested and want to access the APK which the team or me have uploaded to the MobSF machine. So they don't have to request from the team or me but access directly from the MobSF machine itself. Currently we are using SFTP to download the APK from MobSF machine for further analysis but need to search the hash folder to identify where the APK located.

**Comment by ajinabraham** [comment]
Available when this PR is merged: https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1163
