### ISSUE TITLE
Migrate reports

### ISSUE THREAD

**Issue by itsecforu** [MobSF/Mobile-Security-Framework-MobSF#1103]
Hey! 

Env: Centos 7 + Docker

I deployed a new version ( 2.0)

Can i migrate my last reports from older ver. for new MobSF's version?

I tryed to copy /downolads and /uploads directories,but its doesnt work :-(

**Comment by superpoussin22** [comment]
if you are using docker you should mount a volume if you want to have persistent report 

https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/7.-Docker-Container-for-MobSF-Static-Analysis

> For persistence

docker run -it --name mobsf -p 8000:8000 -v <your_local_dir>:/root/.MobSF opensecurity/mobile-security-framework-mobsf:latest

**Comment by superpoussin22** [comment]
but you can integrate all the previuos report by doing a new scan using the mass_static_analysis script 

https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/4.-Mass-Static-Analysis

**Comment by itsecforu** [comment]
> if you are using docker you should mount a volume if you want to have persistent report

i did it from portainer with Docker Swarn

**Comment by superpoussin22** [comment]
in portainer you can add volume  :)  and  limit the container to one specific swarm client :)

**Comment by itsecforu** [comment]
So Do I need to to update the stack with old volumes and same devices?

**Comment by itsecforu** [comment]
So it works man, thx u for help!
