### ISSUE TITLE
Integrate with SonarQube 

### ISSUE THREAD

**Issue by itsecforu** [MobSF/Mobile-Security-Framework-MobSF#1104]
Hello !

Did you think about integrate MobSF with Sonarqube via plugin ( for example as Dependencies check or Owasp 10 ) for check apks and ipas in CI/CD pipeline?

It would be very cool and modern.

**Comment by ajinabraham** [comment]
You can make use of MobSF REST APIs for any 3rd party integrations. We don't explicitly tag findings under OWASP Top 10 at the moment. But you can expect tagging for OWASP Mobile Top 10 in the next major release.

**Comment by Natgho** [comment]
Hi, Any updates about this issue?

**Comment by marwagad** [comment]
Any updates regarding this issue please? can we integrate the results of MobSF within the sonarqube?

**Comment by ajinabraham** [comment]
@marwagad You might want to look into https://github.com/MobSF/mobsfscan
