### ISSUE TITLE
Command errored out with exit status 1

### ISSUE THREAD

**Issue by fabro777** [MobSF/Mobile-Security-Framework-MobSF#1107]
OS and Version: Mac OS Mojaven
Python Version: Python 3.7
MobSF Version: 2.0.0.Beta

the bug is presented when installing

ERROR: Command errored out with exit status 1:
     command: /Users/usuario/Desktop/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-install-cejfkahc/frida/setup.py'"'"'; __file__='"'"'/private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-install-cejfkahc/frida/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-record-05s3kp1k/install-record.txt --single-version-externally-managed --compile --install-headers /Users/usuario/Desktop/Mobile-Security-Framework-MobSF/venv/include/site/python3.7/frida
         cwd: /private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-install-cejfkahc/frida/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/usuario/frida-12.7.5-py3.7-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/usuario/Desktop/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-install-cejfkahc/frida/setup.py'"'"'; __file__='"'"'/private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-install-cejfkahc/frida/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0q/868_71090k5330q3gtqrmqb40000gn/T/pip-record-05s3kp1k/install-record.txt --single-version-externally-managed --compile --install-headers /Users/usuario/Desktop/Mobile-Security-Framework-MobSF/venv/include/site/python3.7/frida Check the logs for full command output.

**Comment by ajinabraham** [comment]
This looks like a setup error. it's a Frida installation error and you need to check with with Frida developers.

**Comment by prem3010** [comment]
If your Python version is 3.6 and above please follow the below steps. It has cleared my error

pip install certifi

Then Goto Application Folder And expand Python
In that Double click and run the **Install Certificates.command**
