### ISSUE TITLE
False Positive on IP Address Disclosure

### ISSUE THREAD

**Issue by rlvilla** [MobSF/Mobile-Security-Framework-MobSF#1109]
## ENVIRONMENT

```
OS and Version: Manjaro 2018.1, Kernel 4.19
Python Version: 3.7.4
MobSF Version: 2.0.0 beta
```

## EXPLANATION OF THE ISSUE

In latest release, when analyzing some apps, some paths to java classes are reported as IP Address Disclosure. For example, in SqliteDB, in DANG column:
{'IP Address disclosure': {'path': ['com/cootek/smartinputv5/language/oem/latvian/BuildConfig.java'], 'level': 'warning', 'cvss': 4.3, 'cwe': 'CWE-200'}}
while this is just a .java file inside the Apk.

## STEPS TO REPRODUCE THE ISSUE

1. For example, in my case, I was analyzing language packs for TouchPal for OPPO
2. Check when finished in DB o MobSF in DANG column

## SCREENSHOT

![image](https://user-images.githubusercontent.com/16118866/66194160-34639300-e694-11e9-9e35-fad557d73d68.png)

**Comment by superpoussin22** [comment]
can you share the APK ?

**Comment by ajinabraham** [comment]
Or you can share just the file buildconfig.java. there might be a match for ip address in that file.

**Comment by superpoussin22** [comment]
@rlvilla can you share the file buildconfig.java or the apk ?

**Comment by ajinabraham** [comment]
No response
