### ISSUE TITLE
[FEATURE] Add check for usesCleartextTraffic

### ISSUE THREAD

**Issue by ethicalhack3r** [MobSF/Mobile-Security-Framework-MobSF#1116]
The `usesCleartextTraffic` configuration within the manifest file, if set to `true`, will allow unencrypted communications such as HTTP and FTP.

https://developer.android.com/guide/topics/manifest/application-element.html#usesCleartextTraffic

It would be great if MobSF implemented a check and warn if `usesCleartextTraffic` is set to `true`.

This is what it looks like in the `AndroidManifest.xml` file of the app I'm currently testing:

```
<application android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:name="host.exp.exponent.MainApplication" android:allowBackup="true" android:largeHeap="true" android:supportsRtl="true" android:usesCleartextTraffic="true" android:appComponentFactory="android.support.v4.app.CoreComponentFactory">
```

Sometimes the `usesCleartextTraffic` configuration can also be found within the `res/xml/network_security_config.xml` file.

**Comment by ajinabraham** [comment]
Sure, we can do that. Thanks for pointing out.

**Comment by ajinabraham** [comment]
Feature added in PR https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1200
![Screenshot 2019-12-10 at 11 50 52 AM](https://user-images.githubusercontent.com/4301109/70550364-a13b5380-1b43-11ea-8834-d5a3954451b8.png)
