### ISSUE TITLE
Unable to connect to internet after HTTPS interception proxy

### ISSUE THREAD

**Issue by drakewader** [MobSF/Mobile-Security-Framework-MobSF#1117]
## ENVIRONMENT

```
OS and Version: Windows 10 Enterprise build 17134
Python Version: 3.7.4
MobSF Version: Latest build
```

## EXPLANATION OF THE ISSUE

After setting up HTTPS interception proxy, Genymotion VM unable to connect to internet.

I have tried changing the ports but the problem still persists. 

## STEPS TO REPRODUCE THE ISSUE

Running MobSF in windows 10 environment with Genymotion VM having Android Nougat 7.0

## Other Information

1. MobSF running in default configuration.
2. Commenting the line
         `env.set_global_proxy(version)`
    has fixed the issue temporarily. of course HTTPS interceptor won't work.
3. Windows firewall is active.(Default configuration)

## LOG FILE

[debug.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3708509/debug.log)

**Comment by ajinabraham** [comment]
`After setting up HTTPS interception proxy`- What do you mean, MobSF does that automatically and redirects all traffic through the proxy. If the app is having SSL certificate checks or pinning, you need to instrument it with Frida for android >4.4 to get internet connectivity.

**Comment by drakewader** [comment]
So in order to access the internet, I need to manually bypass SSL pinning ?

Is there a way to disable HTTPS interception ? I just need to monitor APIs

**Comment by JeffKitson** [comment]
This also seems to happen if you have MobSF target a physical device for dynamic testing; at least in my case. It seems the proxy settings are set [HERE](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android/environment.py#L110) and never get deleted/unset.  

For me to unset the proxy and allow normal traffic I had to use the commands described [in this post](https://stackoverflow.com/questions/31807559/undo-setting-proxy-via-settings-global-in-android)
```
adb shell settings delete global http_proxy
adb shell settings delete global global_http_proxy_host
adb shell settings delete global global_http_proxy_port
```

**Comment by drakewader** [comment]
> 
> 
> This also seems to happen if you have MobSF target a physical device for dynamic testing; at least in my case. It seems the proxy settings are set [HERE](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android/environment.py#L110) and never get deleted/unset.
> 
> For me to unset the proxy and allow normal traffic I had to use the commands described [in this post](https://stackoverflow.com/questions/31807559/undo-setting-proxy-via-settings-global-in-android)
> 
> ```
> adb shell settings delete global http_proxy
> adb shell settings delete global global_http_proxy_host
> adb shell settings delete global global_http_proxy_port
> ```

Yep, I had removed the global proxy with same commands. Thanks for the comment though, it would help others having similar problem, it took me a while. For me, using MobSF on physical device causes ADB command errors as executing a ADB command in emulator is little different than physical device considering we use stock ROMs. I have used Samsung J7 Prime with stock ROM (rooted).

For instance in my device, all ADB commands that require root privileges require the input `su -c`  after adb shell so the command looks like `adb shell su -c [command]`

**Comment by ajinabraham** [comment]
@drakewader depends on your app, for most apps you need to bypass certificate checks so that it can talk to internet. We don't have an option to disable traffic interception. But I will add a task to unset proxy after analysis.

We only support Genymotion VMs at the moment. There is a lot of unknowns in real devices and we don't support them.

**Comment by ajinabraham** [comment]
Closing this a feature request to track this is added here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1118
