### ISSUE TITLE
Wkhtmltox other languages export pdf error

### ISSUE THREAD

**Issue by ldbfpiaoran** [MobSF/Mobile-Security-Framework-MobSF#1120]
Wkhtmltox other languages export pdf error under ubuntu eg Bengali Korean
![image](https://user-images.githubusercontent.com/19885418/66618929-a9dbe000-ec0d-11e9-94c0-ff9de9eac6c6.png)

![image](https://user-images.githubusercontent.com/19885418/66618922-a3e5ff00-ec0d-11e9-9102-b11bcda43762.png)

## ENVIRONMENT

```
OS and Version: ubuntu
Python Version: python3.7 
MobSF Version:
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by ajinabraham** [comment]
Out of scope to this project. You might want to report that here: https://github.com/wkhtmltopdf/wkhtmltopdf
