### ISSUE TITLE
 Failed to MobSFy Android Instance

### ISSUE THREAD

**Issue by maverickNerd** [MobSF/Mobile-Security-Framework-MobSF#1121]
## ENVIRONMENT
```
OS and Version: Ubuntu16.x
Python Version: python3.6
MobSF Version:  Mobile Security Framework v2.0.2 Beta

```

## EXPLANATION OF THE ISSUE

```
On running Dynamic analysis on the app, getting "Failed to MobSFy Android Instance"
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Dragged an app on Mobsf running webserver, static analysis is working fine.\
2. On starting dynamic analysis, getting errors.

```

## LOG FILE

[INFO] 11/Oct/2019 07:17:18 - ADB Restarted
[INFO] 11/Oct/2019 07:17:18 - Waiting for 2 seconds...
[INFO] 11/Oct/2019 07:17:20 - Connecting to Android 192.168.56.101:5555
[INFO] 11/Oct/2019 07:17:20 - Remounting /system
[INFO] 11/Oct/2019 07:17:20 - Android Version identified as 9.0
[INFO] 11/Oct/2019 07:17:20 - Environment MobSFyed Check
cat: /system/.mobsf-f: No such file or directory
[WARNING] 11/Oct/2019 07:17:20 - This Android instance is not MobSfyed.
MobSFying the android runtime environment
[INFO] 11/Oct/2019 07:17:20 - Android Version identified as 9.0
[INFO] 11/Oct/2019 07:17:20 - Android instance architecture identified as x86
[INFO] 11/Oct/2019 07:17:20 - Copying frida server
[INFO] 11/Oct/2019 07:17:20 - Installing MobSF RootCA
[ERROR] 11/Oct/2019 07:17:20 - Failed to MobSFy Android Instance
Traceback (most recent call last):
  File "/local/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 285, in mobsfy_init
    self.mobsf_agents_setup('frida')
  File "/local/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 295, in mobsf_agents_setup
    self.install_mobsf_ca('install')
  File "/local/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 102, in install_mobsf_ca
    self.adb_command(['push', get_ca_dir(), ca_file])
  File "/local/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/webproxy.py", line 67, in get_ca_dir
    from mitmproxy import ctx
  File "/local/Mobile-Security-Framework-MobSF/venv/lib/python3.5/site-packages/mitmproxy/ctx.py", line 6
    log: mitmproxy.log.Log = None
       ^
SyntaxError: invalid syntax
[ERROR] 11/Oct/2019 07:17:20 - Failed to MobSFy the instance
[ERROR] 11/Oct/2019 07:17:20 - Internal Server Error: /android_dynamic/

**Comment by joeBENTIL** [comment]
Hello maverickNerd
How did you install mitmproxy and can you help me with links to how to do it  .
Am also facing the same issues but i have installed python3.6

**Comment by Piuliss** [comment]
I have install python  3.6.15 and it solved my issue. Maybe it can help you too.
