### ISSUE TITLE
Android Dynamic analysis

### ISSUE THREAD

**Issue by mahchiahui** [MobSF/Mobile-Security-Framework-MobSF#1123]
When trying to run mobsf dynamic analysis, it gave the following error.
[INFO] 14/Oct/2019 13:41:12 - Android instance architecture identified as armeabi-v7a
[ERROR] 14/Oct/2019 13:41:12 - Make sure a Genymotion Android x86instance is running

It is stated in the wiki to use genymotion, but all genymotion vms are in armeabi-v7a. Is there an alternative that would be recommended?

**Comment by matandobr** [comment]
Why are you saying that they are arm? Genymotion are all x86 from my knowledge

**Comment by mahchiahui** [comment]
Oops i had 1 device and 1 vm conencted. yes u are right, genymotion are all x86, which really puzzled me when i got armeabi-v7a. Thanks
