### ISSUE TITLE
Recent scans issue

### ISSUE THREAD

**Issue by mahchiahui** [MobSF/Mobile-Security-Framework-MobSF#1124]
When clicking on recent scans, I would get the following error. Everything else works, except for this.

SuspiciousFileOperation at /recent_scans/
The joined path (C:\static\staticfiles.json) is located outside of the base path component (C:\static\)

**Comment by ajinabraham** [comment]
Which version of MobSF? What OS version? Logfile? Please report issues properly with enough information
