### ISSUE TITLE
Get 'Type None error' when upload a file that name begin with '#'

### ISSUE THREAD

**Issue by xxzzddxzd** [MobSF/Mobile-Security-Framework-MobSF#1125]
## ENVIRONMENT

```
OS and Version: OS X 10.14
Python Version:3.7
MobSF Version:2.0.0beta
```

## STEPS TO REPRODUCE THE ISSUE

1. Drag file like '#test.ipa' into Mobsf
2. The return page show :
Error
None

'type'

## LOG FILE

[ERROR] 15/Oct/2019 08:17:08 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Documents/workspace/mobsf_osx/StaticAnalyzer/views/ios/static_analyzer.py", line 105, in static_analyzer_ios
    file_type = request.GET['type']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'type'
[ERROR] 15/Oct/2019 08:17:08 - 'type'
[ERROR] 15/Oct/2019 08:17:08 - Internal Server Error: /StaticAnalyzer_iOS/
[ERROR] 15/Oct/2019 08:17:08 - "GET /StaticAnalyzer_iOS/?name= HTTP/1.1" 500 4874

**Comment by superpoussin22** [comment]
can you share the apk ?

**Comment by xxzzddxzd** [comment]
sorry I can't share it.
but if I change file name, like '#test.ipa' to 'test.ipa', will not get error.

**Comment by ajinabraham** [comment]
I am guessing it's because browser won't send anything after # from the URL to MobSF server and the request that reaches the backed is broken.
