### ISSUE TITLE
Unable to scan IPA file 

### ISSUE THREAD

**Issue by RanjithMahadevan** [MobSF/Mobile-Security-Framework-MobSF#1126]
Hi Team,

facing issues while scanning IPA file using MOBSF.

Below log FYR.

[INFO] 15/Oct/2019 04:40:41 - MIME Type: application/octet-stream FILE: e4-1.7.ipa
[INFO] 15/Oct/2019 04:40:42 - Performing Static Analysis of iOS IPA
[INFO] 15/Oct/2019 04:40:42 - iOS Static Analysis Started
[INFO] 15/Oct/2019 04:40:42 - iOS Binary (IPA) Analysis Started
[INFO] 15/Oct/2019 04:40:42 - Generating Hashes
[INFO] 15/Oct/2019 04:40:42 - Extracting IPA
[INFO] 15/Oct/2019 04:40:42 - Unzipping
[ERROR] 15/Oct/2019 04:40:42 - Unzipping Error
Traceback (most recent call last):
  File "/opt/mobsf/mobsf/StaticAnalyzer/views/shared_func.py", line 81, in unzip
    with zipfile.ZipFile(app_path, 'r') as zipptr:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[INFO] 15/Oct/2019 04:40:42 - Using the Default OS Unzip Utility.
[/opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa or
        /opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa.zip, and cannot find /opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa.ZIP, period.
[/opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa or
        /opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa.zip, and cannot find /opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa.ZIP, period.
[ERROR] 15/Oct/2019 04:40:42 - Unzipping Error
Traceback (most recent call last):
  File "/opt/mobsf/mobsf/StaticAnalyzer/views/shared_func.py", line 81, in unzip
    with zipfile.ZipFile(app_path, 'r') as zipptr:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mobsf/mobsf/StaticAnalyzer/views/shared_func.py", line 100, in unzip
    dat = subprocess.check_output([unzip_b, '-qq', '-l', app_path])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/unzip', '-qq', '-l', '/opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/9b9ee199ebc28dd40ea094dd3d16ac14.ipa']' returned non-zero exit status 9.
[INFO] 15/Oct/2019 04:40:42 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 15/Oct/2019 04:40:42 - iOS Info.plist Analysis Started
[INFO] 15/Oct/2019 04:40:42 - Finding Info.plist in iOS Binary
[ERROR] 15/Oct/2019 04:40:42 - Reading from Info.plist
Traceback (most recent call last):
  File "/opt/mobsf/mobsf/StaticAnalyzer/views/ios/plist_analysis.py", line 185, in plist_analysis
    dirs = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mobsf/mobsf/uploads/9b9ee199ebc28dd40ea094dd3d16ac14/Payload/'
[ERROR] 15/Oct/2019 04:40:42 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/opt/mobsf/mobsf/StaticAnalyzer/views/ios/static_analyzer.py", line 149, in static_analyzer_ios
    app_dict['appstore'] = app_search(infoplist_dict.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 15/Oct/2019 04:40:42 - 'NoneType' object has no attribute 'get'
[ERROR] 15/Oct/2019 04:40:42 - Internal Server Error: /StaticAnalyzer_iOS/

**Comment by ajinabraham** [comment]
Read through the exception. It's an invalid file `zipfile.BadZipFile: File is not a zip file`

**Comment by RanjithMahadevan** [comment]
nope, i  ran scan against ipa file **"[INFO] 15/Oct/2019 04:40:41 - MIME Type: application/octet-stream FILE: e4-1.7.ipa"**

**Comment by ajinabraham** [comment]
Please share the IPA. A valid IPA is a zip archive. The error is caused due to invalid zip file format.

**Comment by RanjithMahadevan** [comment]
> Please share the IPA. A valid IPA is a zip archive. The error is caused due to invalid zip file format.

unfortunately i couldn't share the IPA  due to some security reason , can you confirm if the scan can be run against .ipa file ?

**Comment by ajinabraham** [comment]
Can't debug without reproducing the issue with the IPA. We do unit test with ipa before pushing to master branch. We support scanning valid IPA files.

**Comment by RanjithMahadevan** [comment]
![image](https://user-images.githubusercontent.com/50738041/66865002-498eca80-ef8e-11e9-8b9b-2c9dc93050a9.png)

**Comment by flamecopper** [comment]
Just ensure the file directory is Payload and the file compressed is zip type, it will work .
