### ISSUE TITLE
Dynamic Analysis Failed

### ISSUE THREAD

**Issue by LeoMiaBinw** [MobSF/Mobile-Security-Framework-MobSF#1127]
This is the error log below.The second one can't use the httptools as a command

ERROR No.1:

[INFO] 6/Oct/09 06 - Installing MobSF Clipboard Dumper
[ERROR] 6/Oct/09 06 - Error Running ADB Command
Traceback (most recent call last)
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/lib/python.6/subprocess.py", line 56, in check_output
    **kwargs).stdout
  File "/usr/lib/python.6/subprocess.py", line 8, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError Command '['/usr/lib/android-sdk/platform-tools/adb', '-s', '9.68.59.05555', 'push', '/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/tools/onDevice/mobsf_agents/.mobsf-f', '/system/.mobsf-f']' returned non-zero exit status .

[INFO] 6/Oct/09 06 - MobSFying Completed!
[INFO] 6/Oct/09 06 - Starting HTTPs Proxy on 7

ERROR No.2:

[ERROR] 6/Oct/09 06 - Dynamic Analyzer
Traceback (most recent call last)
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/dynamic_analyzer.py", line , in dynamic_analyzer
    env.configure_proxy(package)
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 9, in configure_proxy
    start_proxy(proxy_port, project)
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/tools/webproxy.py", line , in start_proxy
    subprocess.Popen(argz, stdout=fnull, stderr=subprocess.STDOUT)
  File "/usr/lib/python.6/subprocess.py", line 79, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python.6/subprocess.py", line 6, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError [Errno ] No such file or directory 'httptools' 'httptools'
[ERROR] 6/Oct/09 06 - Dynamic Analysis Failed.
[ERROR] 6/Oct/09 06 - Internal Server Error /android_dynamic/

**Comment by ajinabraham** [comment]
Not enough deatails about environment, Android version, Genymotion version etc.
httptools is a part of requirements and you need it install it before using Dynamic Analyzer. Make sure all modules inside requirements.txt is installed properly to the venv.

**Comment by ajinabraham** [comment]
Also the path to adb looks strange. Normally it should be using the one shipped with Genymotion. Don't run Android studio emulator.

**Comment by LeoMiaBinw** [comment]
> Not enough deatails about environment, Android version, Genymotion version etc.
> httptools is a part of requirements and you need it install it before using Dynamic Analyzer. Make sure all modules inside requirements.txt is installed properly to the venv.

I have installed the http-tools and the httptools by pip3.I saw that the 'httptools' is used by subprocess.Popen in the webproxy.py and I think the 'httptools' doesn't work as a command.
![Snipaste_2019-10-16_16-29-17](https://user-images.githubusercontent.com/40820775/66903678-7f3abe80-f035-11e9-8aa1-719322b91008.png)
![Snipaste_2019-10-16_16-53-15](https://user-images.githubusercontent.com/40820775/66903680-7f3abe80-f035-11e9-912d-a04108b14979.png)

**Comment by LeoMiaBinw** [comment]
> > Not enough deatails about environment, Android version, Genymotion version etc.
> > httptools is a part of requirements and you need it install it before using Dynamic Analyzer. Make sure all modules inside requirements.txt is installed properly to the venv.
> 
> I have installed the http-tools and the httptools by pip3.I saw that the 'httptools' is used by subprocess.Popen in the webproxy.py and I think the 'httptools' doesn't work as a command.
> ![Snipaste_2019-10-16_16-29-17](https://user-images.githubusercontent.com/40820775/66903678-7f3abe80-f035-11e9-8aa1-719322b91008.png)
> ![Snipaste_2019-10-16_16-53-15](https://user-images.githubusercontent.com/40820775/66903680-7f3abe80-f035-11e9-912d-a04108b14979.png)



> Not enough details about environment, Android version, Genymotion version etc.
> httptools is a part of requirements and you need it install it before using Dynamic Analyzer. Make sure all modules inside requirements.txt is installed properly to the venv.

I didn't use the Android Studio emulator and I used the VMware Workstation to run an Android 8.1 VM

**Comment by ajinabraham** [comment]
Won't work. We support only Genymotion. Please read documentation and strictly follow that. The required httptools will be installed while you run setup.sh

**Comment by LeoMiaBinw** [comment]
I'm soory man,I used the Genymotion and the 'adb' error disappeared,but the 'httptools' error still be there.I have tried to run the setup.sh for many times and reinstall but it didn't work.

`[INFO] 17/Oct/2019 06:17:26 - "GET /dynamic_analysis/ HTTP/1.1" 200 15835
[INFO] 17/Oct/2019 06:17:26 - "GET /download/58b7b74bb0937d5faa82f77d366a6f6a-icon.png HTTP/1.1" 200 2829
[INFO] 17/Oct/2019 06:17:29 - Creating Dynamic Analysis Environment
* daemon not running; starting now at tcp:5037
* daemon started successfully
[INFO] 17/Oct/2019 06:17:32 - ADB Restarted
[INFO] 17/Oct/2019 06:17:32 - Waiting for 2 seconds...
[INFO] 17/Oct/2019 06:17:34 - Connecting to Android 192.168.58.102:5555
[INFO] 17/Oct/2019 06:17:34 - Remounting /system
[INFO] 17/Oct/2019 06:17:34 - Android Version identified as 8.0
[INFO] 17/Oct/2019 06:17:34 - Environment MobSFyed Check
[INFO] 17/Oct/2019 06:17:34 - Starting HTTPs Proxy on 1337
[ERROR] 17/Oct/2019 06:17:34 - Dynamic Analyzer
Traceback (most recent call last):
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/dynamic_analyzer.py", line 111, in dynamic_analyzer
    env.configure_proxy(package)
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 94, in configure_proxy
    start_proxy(proxy_port, project)
  File "/MobSF/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/tools/webproxy.py", line 44, in start_proxy
    subprocess.Popen(argz, stdout=fnull, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'httptools': 'httptools'
[ERROR] 17/Oct/2019 06:17:34 - Dynamic Analysis Failed.
[ERROR] 17/Oct/2019 06:17:34 - Internal Server Error: /android_dynamic/
[ERROR] 17/Oct/2019 06:17:34 - "GET /android_dynamic/?hash=58b7b74bb0937d5faa82f77d366a6f6a&package=com.brightoilonline.c2b_phone HTTP/1.1" 500 4891`

**Comment by ajinabraham** [comment]
Activate MobSF venv and install http-tools

```
source venv/bin/activate
pip install  http-tools==1.0.1
```
Make sure it's installed sucessfully.

**Comment by LeoMiaBinw** [comment]
Sir,sorry for bothering you again,now I get this error.The APK can be installed in the Genymotion VM.It seems like that the App can't support the Intel CPU.So,can I use a real Android phone to build a dynamic analysis environment?

[INFO] 18/Oct/2019 06:29:15 - Getting screen resolution
[INFO] 18/Oct/2019 06:29:15 - Installing APK
[INFO] 18/Oct/2019 06:29:21 - Installing MobSF RootCA
[INFO] 18/Oct/2019 06:29:21 - Installing MobSF Clipboard Dumper
[INFO] 18/Oct/2019 06:29:23 - MobSFying Completed!
[INFO] 18/Oct/2019 06:29:23 - Starting HTTPs Proxy on 1337
[INFO] 18/Oct/2019 06:29:23 - Killing httptools UI
[INFO] 18/Oct/2019 06:29:23 - Enabling ADB Reverse TCP on 1337
[ERROR] 18/Oct/2019 06:29:23 - error: more than one device/emulator
[INFO] 18/Oct/2019 06:29:23 - Setting Global Proxy for Android VM
[INFO] 18/Oct/2019 06:29:23 - Starting Clipboard Monitor
[INFO] 18/Oct/2019 06:29:23 - Getting screen resolution
[INFO] 18/Oct/2019 06:29:23 - Installing APK
adb: failed to install /MobSF/Mobile-Security-Framework-MobSF-master/uploads/d1962f89f9bd7eacd55c1f551c2ae835/d1962f89f9bd7eacd55c1f551c2ae835.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
[INFO] 18/Oct/2019 06:29:32 - Testing Environment is Ready!
[INFO] 18/Oct/2019 06:29:32 - "GET /android_dynamic/?hash=d1962f89f9bd7eacd55c1f551c2ae835&package=com.brightoilonline.c2b_phone HTTP/1.1" 200 29758

**Comment by ajinabraham** [comment]
At this point, we only support x86 Android via Genymotion. You will need tk use a suitable apk. We do not support real android device

**Comment by ibediaz2014** [comment]
Hello, when I try to do a dynamic analysis, the following error appears in MobSF:

[INFO] 02/Aug/2020 17:56:56 - OS: Windows
[INFO] 02/Aug/2020 17:56:56 - Platform: Windows-10-10.0.19041-SP0
[INFO] 02/Aug/2020 17:56:56 - Dist:
[INFO] 02/Aug/2020 17:56:56 - MobSF Basic Environment Check
[INFO] 02/Aug/2020 17:56:56 - Checking for Update.
[INFO] 02/Aug/2020 17:56:56 - No updates available.
[INFO] 02/Aug/2020 17:57:08 - Starting Analysis on : 311 Panamá_v3.1.6_apkpure.com.apk
[INFO] 02/Aug/2020 17:57:08 - Analysis is already Done. Fetching data from the DB...
[INFO] 02/Aug/2020 17:57:11 - Creating Dynamic Analysis Environment
* daemon not running; starting now at tcp:5037
* daemon started successfully
[INFO] 02/Aug/2020 17:57:14 - ADB Restarted
[INFO] 02/Aug/2020 17:57:14 - Waiting for 2 seconds...
[INFO] 02/Aug/2020 17:57:16 - Connecting to Android emulator-5554
[INFO] 02/Aug/2020 17:57:22 - Waiting for 2 seconds...
[INFO] 02/Aug/2020 17:57:24 - Restarting ADB Daemon as root
[INFO] 02/Aug/2020 17:57:24 - Waiting for 2 seconds...
[INFO] 02/Aug/2020 17:57:26 - Reconnecting to Android Device
[INFO] 02/Aug/2020 17:57:29 - Waiting for 2 seconds...
C:\Users\Michel\AppData\Local\Android\Sdk\platform-tools[INFO] 02/Aug/2020 17:57:31 - Found Android Studio Emulator
[INFO] 02/Aug/2020 17:57:31 - Remounting
[INFO] 02/Aug/2020 17:57:31 - Performing System check
[INFO] 02/Aug/2020 17:57:31 - Android API Level identified as 27
[ERROR] 02/Aug/2020 17:57:31 - VM's /system is not writable. This VM cannot be used for Dynamic Analysis.
[ERROR] 02/Aug/2020 17:57:31 - Please start the AVD as per MobSF documentation!
[ERROR] 02/Aug/2020 17:57:31 - Cannot Connect to emulator-5554
[ERROR] 02/Aug/2020 17:57:31 - Internal Server Error: /android_dynamic/
ERROR:django.request:Internal Server Error: /android_dynamic/

I have already started android studio, but it still appears to me, in the Static reports it does NOT present problems.

**Comment by ajinabraham** [comment]
Please use slack channel for support
