### ISSUE TITLE
[FEATURE] REST API to mobsf

### ISSUE THREAD

**Issue by siewer** [MobSF/Mobile-Security-Framework-MobSF#1131]
Are there any plans on setting rest api to static analyzer to allow remote scan execution as well as report donwload?

**Is your feature request related to a problem? Please describe.**
I would like to be able to run static scan for mobile application from CI via API

**Describe the solution you'd like**
I would like to have three endpoints for example
PUT /api/scan with attachement of apk or ipa
GET /api/status  to see if scan is still running
GET /api/results with finding result in Json

**Describe alternatives you've considered**
no alternatives found for remote static analysis of mobile apps

**Additional context**
nothing more to add

**Comment by superpoussin22** [comment]
Did you check thaht : https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/10.-MobSF-CI-CD ?

also 
https://your_mobsf_api:8000/api_docs

> api/v1/upload - Upload a File
api/v1/scan - Scan a File
api/v1/scans - Display Recent Scans
api/v1/delete_scan - Delete a Scan
api/v1/download_pdf - Download PDF Report
api/v1/report_json - Generate JSON Report
api/v1/view_source - View Source Files
