### ISSUE TITLE
How to upgrade MobSF from v1.1.1 Beta to latest version

### ISSUE THREAD

**Issue by nick2root** [MobSF/Mobile-Security-Framework-MobSF#1132]
i didnt find any document upgrading from old releases to latest release safely. please share your instructions about this situtation.
thanks

**Comment by superpoussin22** [comment]
can you provide more details ?
using Docker, on a linux system, on windows, on macOS ?

did you take a look on : https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation ?

**Comment by nick2root** [comment]
Hi,
I have installed MobSF v1.1.1 beta version on Kali Linux. I need new dynamic analysis option on MobSF. i curios about that Should i remove this version completely and then install latest version or is it any option to available to upgrade?

**Comment by superpoussin22** [comment]
pull the new version 
go in your venv
update the requirements 
then do (always in the venv ):
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate

**Comment by nick2root** [comment]
ok bro. thanks for your quick help but i hope there is a documentation for upgrading issue. Because all of information is documented except upgrading.

**Comment by superpoussin22** [comment]
upgrading is explained in doc but not with all this details , will look at this

**Comment by nick2root** [comment]
thanks bro.

**Comment by Vasun111** [comment]
[2020-06-03 13:06:49]
[ERROR] Cannot Check for updates. (C:\MobSF\MobSF\utils.py, LINE 36 "response = urllib2.urlopen(github_url)"): <urlopen error [Errno 11001] getaddrinfo failed>
System check identified no issues (0 silenced).
June 03, 2020 - 13:06:49
Django version 1.10b1, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

unable to launch http://127.0.0.1:8000/ for static Analysis

**Comment by ajinabraham** [comment]
Follow official docs:https://mobsf.github.io/docs/#/
