### ISSUE TITLE
Endless static analysis

### ISSUE THREAD

**Issue by MRazian** [MobSF/Mobile-Security-Framework-MobSF#1134]
## ENVIRONMENT

```
OS and Version: Ubuntu 16.04
Python Version: 3.5
MobSF Version: 2.0
```

## EXPLANATION OF THE ISSUE

It seems the _static analysis_ goes to an endless state for some apk files. The program waits for the below function in the StaticAnalyzer/views/android/converter.py
```
subprocess.call(args,
                            stdout=fnull,
                            stderr=subprocess.STDOUT)
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Start  the static analysis
2. Upload [Nextcloud](https://f-droid.org/en/packages/com.nextcloud.client/) mobile app
3. It passes all steps except the **Decompiling to Java with jadx**. It seems it cannot decompile the file.

```

## LOG FILE

```

[INFO] 22/Oct/2019 14:38:26 - Manifest Analysis Started
[INFO] 22/Oct/2019 14:38:26 - Static Android Binary Analysis Started
[INFO] 22/Oct/2019 14:38:26 - Static Android Resource Analysis Started
[INFO] 22/Oct/2019 14:38:26 - Reading Code Signing Certificate
[INFO] 22/Oct/2019 14:38:28 - Trackers Database is up-to-date
[INFO] 22/Oct/2019 14:38:28 - Detecting Trackers
[INFO] 22/Oct/2019 14:38:30 - APK -> JAVA
[INFO] 22/Oct/2019 14:38:30 - Decompiling to Java with jadx
```

**Comment by superpoussin22** [comment]
can you share the apk ?

**Comment by superpoussin22** [comment]
it works on my Docker container which is based on ubuntu 18.04 but with python 3.6 and openjdk1

**Comment by MRazian** [comment]
I checked the following well known app
https://f-droid.org/repo/com.nextcloud.client_30080190.apk

**Comment by MRazian** [comment]
Thanks for your follow up,
I tested the following well known app


https://f-droid.org/repo/com.nextcloud.client_30080190.apk

**Comment by superpoussin22** [comment]
will try this apk

**Comment by superpoussin22** [comment]
I open a ticket on jadx site

**Comment by superpoussin22** [comment]
this is corrected by last unstabel build of jadx : https://bintray.com/skylot/jadx/unstable/v1.0.0-b1157-f228a721#files

you can use it but we will only include a  stable build in MobSF

**Comment by MRazian** [comment]
Perfect...It works for me.
I just replaced jadx-1.0.0-b1157-f228a721with the current jadx (Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/StaticAnalyzer/tools).

tnx @superpoussin22
