### ISSUE TITLE
Installation failures on Mac 10.15

### ISSUE THREAD

**Issue by alonf1983** [MobSF/Mobile-Security-Framework-MobSF#1136]
Hi
once we try to execute:

sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

we have the error:
Error - the package path specified was invalid.

under the:
/Library/Developer/CommandLineTools/ we have only:

Library
SDKs
usr

without this the installation failed

please help

**Comment by superpoussin22** [comment]
did you install the command line utility ?

**Comment by superpoussin22** [comment]
can you also verifiy you have the last version of MobSF ?

**Comment by superpoussin22** [comment]
move to slack channel this is the place for help on installation :)

**Comment by alonf1983** [comment]
hi.
yes - I have installed the lasted MobSF and the command line utility
yes- it's Catalina

any ideas hot to solve it?

**Comment by alonf1983** [comment]
was my mistake.... worked....

**Comment by aashya** [comment]
Hi @alonf1983 

what was the mistake you had made, I'm facing the same error
