### ISSUE TITLE
[FEATURE] Optimize the directory structure of downloaded ZIP files

### ISSUE THREAD

**Issue by Lazza** [MobSF/Mobile-Security-Framework-MobSF#1142]
**Is your feature request related to a problem? Please describe.**

When I download a ZIP file from MobSF, the source code is buried inside a hidden directory:

    root/.MobSF/uploads/[... hash ...]/java_source

This is inconvenient, especially on macOS but also on Linux, as I need to enable hidden files and folders in the file manager.

**Describe the solution you'd like**

Ideally, MobSF should ZIP the `java_source` directory directly.

**Describe alternatives you've considered**

I did consider manually enabling and disabling hidden files in my file manager every time. It is a bit cumbersome.

**Additional context**

—

**Comment by ajinabraham** [comment]
Fixed when this PR is merged: https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1163

**Comment by Lazza** [comment]
It works very well, thank you. 😄
