### ISSUE TITLE
Pls Help！ An error found at the time of running setup

### ISSUE THREAD

**Issue by lxy2343** [MobSF/Mobile-Security-Framework-MobSF#1148]
I am working with win 10, Python38.  When running setup.bat, below error occur. Pls let me know how to fix it.  thanks a lot.

Collecting google-play-scraper==0.0.1.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/3b/44/c5aa28b23ddb81177fec531a543a9dc9ed4066aa74c400dc2cc677d6a0eb/google-play-scraper-0.0.1.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'd:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXX\\AppData\\Local\\Temp\\pip-install-51rj4tu7\\google-play-scraper\\setup.py'"'"'; __file__='"'"'C:\\Users\\XXX\\AppData\\Local\\Temp\\pip-install-51rj4tu7\\google-play-scraper\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\XXX\AppData\Local\Temp\pip-install-51rj4tu7\google-play-scraper\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXX\AppData\Local\Temp\pip-install-51rj4tu7\google-play-scraper\setup.py", line 18, in <module>
        long_description=open("README.md").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1908: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lxy2343** [comment]
problem fixed by using below command
pip install git+https://github.com/ETOCheney/google-play-scraper.git

**Comment by lxy2343** [comment]
I reinstalled python with version 37. However when running setup.bat.  This error continues happan.
By the way, my computer also intalled python 2.7.  Does python version cause this error.
Thinks a lot!

**Comment by ajinabraham** [comment]
Use slack channel. GitHub issues are for bug reports only
