### ISSUE TITLE
MobSF unable to set execute permission to jadx

### ISSUE THREAD

**Issue by noraj** [MobSF/Mobile-Security-Framework-MobSF#1151]
## ENVIRONMENT

```
OS and Version: ArchLinux
Python Version: 3.7.4
MobSF Version: Mobile Security Framework v2.0.2 Beta
```

## EXPLANATION OF THE ISSUE

When using `USE_HOME = True` Decompiling to Java with jadx fails.

```
[ERROR] 30/Oct/2019 21:23:11 - Decompiling to JAVA
Traceback (most recent call last):
  File "/usr/share/mobsf/StaticAnalyzer/views/android/converter.py", line 75, in apk_2_java
    os.chmod(jadx, 0o744)
PermissionError: [Errno 1] Operation not permitted: '/usr/share/mobsf/StaticAnalyzer/tools/jadx/bin/jadx'
```

MobSF is installed in `/usr/share/mobsf/`, its a write-protected directory.

I think the decompilation step try to write here instead of in the user home.

## STEPS TO REPRODUCE THE ISSUE

1. `blackman -i mobsf` (from blackarch [PKGBUILD](https://github.com/BlackArch/blackarch/tree/master/packages/mobsf))
2. Modify `MobSF/settings.py` to change `USE_HOME = False` to `USE_HOME = True`
3. Launch MobSF as a user

## LOG FILE

`~/.MobSF/logs/debug.log`

```
...

[INFO] 30/Oct/2019 21:27:44 - Decompiling to Java with jadx
[ERROR] 30/Oct/2019 21:27:44 - Decompiling to JAVA
Traceback (most recent call last):
  File "/usr/share/mobsf/StaticAnalyzer/views/android/converter.py", line 75, in apk_2_java
    os.chmod(jadx, 0o744)
PermissionError: [Errno 1] Operation not permitted: '/usr/share/mobsf/StaticAnalyzer/tools/jadx/bin/jadx'
[INFO] 30/Oct/2019 21:27:44 - DEX -> SMALI

...
```

**Comment by ajinabraham** [comment]
Also could you replace the code with  `os.chmod(jadx, 0o555)` or `os.chmod(jadx, 0o544)` and see if the exceptions are going away?

**Comment by noraj** [comment]
On a new install there is also this happening in addition to jadx:

```
[INFO] 31/Oct/2019 20:11:10 - Updating Trackers Database....
[ERROR] 31/Oct/2019 20:11:10 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "/usr/share/mobsf/MalwareAnalyzer/views/Trackers.py", line 57, in _update_tracker_db
    with open(self.tracker_db, 'wb') as wfp:
PermissionError: [Errno 13] Permission denied: '/usr/share/mobsf/MalwareAnalyzer/trackersdb/exodus_trackers'
```

jadx is already 755

```
$ ls -l /usr/share/mobsf/StaticAnalyzer/tools/jadx/bin/jadx
-rwxr-xr-x 1 root root 6295 oct.  25 22:12 /usr/share/mobsf/StaticAnalyzer/tools/jadx/bin/jadx
```

So before trying to do a `os.chmod(jadx, 0o744)` MobSF should check if the permission is the binary is already executable. Why trying to do a chmod if the permission is already good.

**Comment by ajinabraham** [comment]
`mobsf/MalwareAnalyzer/trackersdb/exodus_trackers` might be an issue since tracker db and malware domain db are relative to MobSF directory and doesn't respect home directories. They are shipped with MobSF and are updated at runtime and is not user data.
We could do preemptive checks on the binary permissions, but we are not doing that at the moment. Will consider it as an enhancement.
@superpoussin22  ^

**Comment by noraj** [comment]
@ajinabraham I made a PR #1152 for this issue, I'll create another issue to track `exodus_trackers` one

**Comment by ajinabraham** [comment]
There is malware db https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MalwareAnalyzer/malwaredb/malwaredomainlist
and trackers db, both of which are dynamic
