### ISSUE TITLE
Allow for CSV export of findings[FEATURE]

### ISSUE THREAD

**Issue by Maleus** [MobSF/Mobile-Security-Framework-MobSF#1155]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
I use this tool for FedRAMP penetration testing against Federal companies. As such, there are very strict documentation standards. Allowing export of a CSV file would greatly streamline my reporting as currently I am having to copy/paste from PDFs unless I want to work on the report instantly.

**Describe the solution you'd like**
I would like a function added that could either export as CSV or even XML that could be converted to CSV through scripting in Python. Anything but a PDF that cannot be properly parsed.

**Describe alternatives you've considered**
I am currently working on attempting to pull the HTML down and use Beautiful soup to perform the parsing, however I feel that if I am needing this functionality, multiple other people may be wanting it as well.

**Additional context**
No additional however I do want to take a moment to thank you for making this tool. It is an amazing addition to the community.

**Comment by ajinabraham** [comment]
MobSF has REST APIs for exporting Static Analysis result as JSON. You should be able to do scripting on that. We already have an enhancement to track XML/CSV output. But that won't happen soon.

**Comment by qurbat** [comment]
I needed this for a report I was working on. I came across: https://github.com/jakubd/apkreport
