### ISSUE TITLE
Dynamic Analysis Failed

### ISSUE THREAD

**Issue by SagarKashyap479** [MobSF/Mobile-Security-Framework-MobSF#1160]
Dynamic analysis failed  - How can we set ADB path, can someone please help

![Mobsf_Dynamic_Scan](https://user-images.githubusercontent.com/56971460/68402527-76a35700-01a1-11ea-9171-de2a40403600.png)
![Mobsf_Dynamic_Scan_Web](https://user-images.githubusercontent.com/56971460/68402530-773bed80-01a1-11ea-8929-55fecb8fd1ee.png)

**Comment by ajinabraham** [comment]
Github issues are not for help. Use slack channel. You need to run Genymotion inside Kali before attempting dynamic analysis

**Comment by crisleicon** [comment]
Hello,
How can I see the resolution for this issue? I'm facing the same problem and not sure how to proceed.
thanks
