### ISSUE TITLE
Python error while installlation

### ISSUE THREAD

**Issue by Rollingsmoke** [MobSF/Mobile-Security-Framework-MobSF#1162]
[INSTALL] Migrating Database
/Users/******/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecRandomDefault' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
UserWarning: Global variable 'kCFTypeDictionaryValueCallBacks' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')

./setup.sh: line 64:  6753 Abort trap: 6           python manage.py migrate

## ENVIRONMENT

```
OS and Version:Mac 10.15.1
Python Version:python 3.7
MobSF Version:2.0
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
We are aware of this issue due to catalina last update

**Comment by Rollingsmoke** [comment]
so , what now ? do i need to wait for the bug to be fixed ?

**Comment by Rollingsmoke** [comment]
any work around mate ?

**Comment by ajinabraham** [comment]
These are warnings. You can suppress them by adding
```
import warnings

warnings.filterwarnings("ignore", category=UserWarning, module='cffi')
```

to MobSF/wsgi.py

As for `./setup.sh: line 64: 6753 Abort trap: 6 python manage.py migrate`
There is something else that is not broken. Look into the setup logs after hiding the warning

**Comment by ajinabraham** [comment]
Try the latest from master version `2.0.5` after this PR https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1163 gets merged

There is something else causing `./setup.sh: line 64: 6753 Abort trap: 6 python manage.py migrate`

**Comment by Rollingsmoke** [comment]
[INSTALL] Migrating Database
./setup.sh: line 62:  7357 Abort trap: 6           python manage.py makemigrations
./setup.sh: line 63:  7379 Abort trap: 6           python manage.py makemigrations StaticAnalyzer
./setup.sh: line 64:  7382 Abort trap: 6           python manage.py migrate
./setup.sh: line 65: wkhtmltopdf: command not found

**Comment by ajinabraham** [comment]
This looks like a lot of errors coming from Native code.
Please share full setup log.

**Comment by ajinabraham** [comment]
Also this looks like your python is not happy about something. You might wanna reinstall Python 3.7 from brew or Python.org. 
The latest Mac update breaks a lot of stuff.

**Comment by Rollingsmoke** [comment]
about the reinstall i have already tried a couple of times deleting /usr/local files .. reinstalling brew and python 
but i will give it a try again

**Comment by Rollingsmoke** [comment]
[INSTALL] Found Python3
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
[INSTALL] Found pip
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.3.1)
xcode-select version 2370.
[INSTALL] Using python virtualenv
[INSTALL] Activating virtualenv
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1
[INSTALL] Installing Requirements
Collecting Django==2.2.7
  Downloading https://files.pythonhosted.org/packages/a0/36/463632a2e9161a7e713488d719a280e8cb0c7e3a66ed32a32e801891caae/Django-2.2.7-py3-none-any.whl (7.5MB)
     |████████████████████████████████| 7.5MB 693kB/s 
Collecting pdfkit==0.6.1
  Downloading https://files.pythonhosted.org/packages/57/da/48fdd627794cde49f4ee7854d219f3a65714069b722b8d0e3599cd066185/pdfkit-0.6.1-py3-none-any.whl
Collecting androguard==3.3.5
  Downloading https://files.pythonhosted.org/packages/43/ca/09deda747e28903e742768918480083682799abbe31c5e1ba5dbe7eeaf4b/androguard-3.3.5-py3-none-any.whl (922kB)
     |████████████████████████████████| 931kB 811kB/s 
Collecting lxml==4.4.1
  Downloading https://files.pythonhosted.org/packages/bd/9f/6cda4672d3ad1aa4cf818ab8401a763787efba751c88aaf4b38fc8f923bb/lxml-4.4.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.9MB)
     |████████████████████████████████| 8.9MB 1.0MB/s 
Collecting rsa==4.0
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting biplist==1.0.3
  Downloading https://files.pythonhosted.org/packages/3e/56/2db170a498c9c6545cda16e93c2f2ef9302da44802787b45a8a520d01bdb/biplist-1.0.3.tar.gz
Collecting requests==2.22.0
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 1.2MB/s 
Collecting bs4==0.0.1
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting colorlog==4.0.2
  Downloading https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl
Collecting macholib==1.11
  Downloading https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Collecting google-play-scraper==0.0.1.1
  Downloading https://files.pythonhosted.org/packages/3b/44/c5aa28b23ddb81177fec531a543a9dc9ed4066aa74c400dc2cc677d6a0eb/google-play-scraper-0.0.1.1.tar.gz
Collecting whitenoise==4.1.4
  Downloading https://files.pythonhosted.org/packages/a6/b4/72f2218c91cef12fc434c163881067be482a917c4067834cdbced90133df/whitenoise-4.1.4-py2.py3-none-any.whl
Collecting waitress==1.3.1
  Downloading https://files.pythonhosted.org/packages/2d/0b/84a7da7fd12ee556dd193c24b635a11b840d314bc580771dd2a3151450c9/waitress-1.3.1-py2.py3-none-any.whl (144kB)
     |████████████████████████████████| 153kB 875kB/s 
Collecting gunicorn==20.0.0
  Downloading https://files.pythonhosted.org/packages/60/0d/3dbda0324f5bf007f3274e5ea09f0f3bcbf0ca01a75b80ff4f1ff9f8ecfd/gunicorn-20.0.0-py2.py3-none-any.whl (77kB)
     |████████████████████████████████| 81kB 1.2MB/s 
Collecting frida==12.7.20
  Downloading https://files.pythonhosted.org/packages/41/44/3e073828d4dcb76c712716d4073b7bf7cb5679a040a97089c206e42b46fc/frida-12.7.20.tar.gz
Collecting psutil==5.6.5
  Downloading https://files.pythonhosted.org/packages/03/9a/95c4b3d0424426e5fd94b5302ff74cea44d5d4f53466e1228ac8e73e14b4/psutil-5.6.5.tar.gz (447kB)
     |████████████████████████████████| 450kB 1.3MB/s 
Collecting shelljob==0.5.6
  Downloading https://files.pythonhosted.org/packages/7f/c4/3f1393d9960dd11b85e96a640a7587ce5bf65d75773fec82a744ba52add7/shelljob-0.5.6.tar.gz (228kB)
     |████████████████████████████████| 235kB 1.5MB/s 
Collecting asn1crypto==1.2.0
  Downloading https://files.pythonhosted.org/packages/6b/8c/ff300484eca90b397d919408619fae479965bdd8a1df3d6d08d58e491da5/asn1crypto-1.2.0-py2.py3-none-any.whl (103kB)
     |████████████████████████████████| 112kB 1.4MB/s 
Collecting oscrypto==1.1.0
  Downloading https://files.pythonhosted.org/packages/b4/b7/ebe2571e26f70d2c52eccbbe7499c1aeb89fbf2c22a8fed9ec237797113b/oscrypto-1.1.0-py2.py3-none-any.whl (191kB)
     |████████████████████████████████| 194kB 1.3MB/s 
Collecting distro==1.4.0
  Downloading https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl
Collecting pyparsing<2.3
  Downloading https://files.pythonhosted.org/packages/2b/4a/f06b45ab9690d4c37641ec776f7ad691974f4cf6943a73267475b05cbfca/pyparsing-2.2.2-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 3.5MB/s 
Collecting click<7
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
     |████████████████████████████████| 71kB 1.1MB/s 
Collecting http-tools==1.0.1
  Downloading https://files.pythonhosted.org/packages/56/ce/d912b8e4da2dc9ac9e3b69c38d7e13c74eb11b53f6f74a9fb1970fe19106/http_tools-1.0.1-py3-none-any.whl (573kB)
     |████████████████████████████████| 583kB 1.2MB/s 
Collecting pytz
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
     |████████████████████████████████| 512kB 1.5MB/s 
Collecting sqlparse
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting ipython>=5.0.0
  Downloading https://files.pythonhosted.org/packages/81/2e/59cdacea6476a4c21b7c090a91250ffbcd085900f5eb9f4e4d68dd2ee4e3/ipython-7.9.0-py3-none-any.whl (775kB)
     |████████████████████████████████| 778kB 1.4MB/s 
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/c3/8b/af9e0984f5c0df06d3fab0bf396eb09cbf05f8452de4e9502b182f59c33b/matplotlib-3.1.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.4MB)
     |████████████████████████████████| 14.4MB 475kB/s 
Collecting future
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
     |████████████████████████████████| 829kB 764kB/s 
Collecting pygments
  Downloading https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl (883kB)
     |████████████████████████████████| 890kB 1.4MB/s 
Collecting pydot>=1.4.1
  Downloading https://files.pythonhosted.org/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Collecting colorama
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting networkx>=1.11
  Downloading https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 953kB/s 
Collecting pyasn1>=0.1.3
  Downloading https://files.pythonhosted.org/packages/a1/71/8f0d444e3a74e5640a3d5d967c1c6b015da9c655f35b2d308a55d907a517/pyasn1-0.4.7-py2.py3-none-any.whl (76kB)
     |████████████████████████████████| 81kB 2.6MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl (125kB)
     |████████████████████████████████| 133kB 1.3MB/s 
Collecting idna<2.9,>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 2.2MB/s 
Collecting chardet<3.1.0,>=3.0.2
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 1.4MB/s 
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
     |████████████████████████████████| 163kB 1.5MB/s 
Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/3b/c8/a55eb6ea11cd7e5ac4bacdf92bac4693b90d3ba79268be16527555e186f0/beautifulsoup4-4.8.1-py3-none-any.whl (101kB)
     |████████████████████████████████| 102kB 886kB/s 
Collecting altgraph>=0.15
  Downloading https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=3.0 in ./venv/lib/python3.7/site-packages (from gunicorn==20.0.0->-r requirements.txt (line 14)) (41.2.0)
Collecting mitmproxy==4.0.4
  Downloading https://files.pythonhosted.org/packages/e5/6c/fe3f4b4cbef7f703b1199d5443963c4c56c2182223375bdaf0930e1ad052/mitmproxy-4.0.4-py3-none-any.whl (1.3MB)
     |████████████████████████████████| 1.3MB 938kB/s 
Collecting decorator
  Downloading https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting traitlets>=4.2
  Downloading https://files.pythonhosted.org/packages/ca/ab/872a23e29cec3cf2594af7e857f18b687ad21039c1f9b922fac5b9b142d5/traitlets-4.3.3-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 2.1MB/s 
Collecting jedi>=0.10
  Downloading https://files.pythonhosted.org/packages/55/54/da994f359e4e7da4776a200e76dbc85ba5fc319eefc22e33d55296d95a1d/jedi-0.15.1-py2.py3-none-any.whl (1.0MB)
     |████████████████████████████████| 1.0MB 545kB/s 
Collecting backcall
  Downloading https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
Collecting pexpect; sys_platform != "win32"
  Downloading https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 1.0MB/s 
Collecting appnope; sys_platform == "darwin"
  Downloading https://files.pythonhosted.org/packages/87/a9/7985e6a53402f294c8f0e8eff3151a83f1fb901fa92909bb3ff29b4d22af/appnope-0.1.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.1.0,>=2.0.0
  Downloading https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl (340kB)
     |████████████████████████████████| 348kB 801kB/s 
Collecting pickleshare
  Downloading https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting python-dateutil>=2.1
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
     |████████████████████████████████| 235kB 647kB/s 
Collecting cycler>=0.10
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting numpy>=1.11
  Downloading https://files.pythonhosted.org/packages/60/9a/a6b3168f2194fb468dcc4cf54c8344d1f514935006c3347ede198e968cb0/numpy-1.17.4-cp37-cp37m-macosx_10_9_x86_64.whl (15.1MB)
     |████████████████████████████████| 15.1MB 1.6MB/s 
Collecting kiwisolver>=1.0.1
  Downloading https://files.pythonhosted.org/packages/df/93/8bc9b52a8846be2b9572aa0a7c881930939b06e4abe1162da6a0430b794f/kiwisolver-1.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (113kB)
     |████████████████████████████████| 122kB 2.2MB/s 
Collecting soupsieve>=1.2
  Downloading https://files.pythonhosted.org/packages/81/94/03c0f04471fc245d08d0a99f7946ac228ca98da4fa75796c507f61e688c2/soupsieve-1.9.5-py2.py3-none-any.whl
Collecting urwid<2.1,>=2.0.1
  Downloading https://files.pythonhosted.org/packages/c7/90/415728875c230fafd13d118512bde3184d810d7bf798a631abc05fac09d0/urwid-2.0.1.tar.gz (604kB)
     |████████████████████████████████| 614kB 1.7MB/s 
Collecting hyperframe<6,>=5.1.0
  Downloading https://files.pythonhosted.org/packages/19/0c/bf88182bcb5dce3094e2f3e4fe20db28a9928cb7bd5b08024030e4b140db/hyperframe-5.2.0-py2.py3-none-any.whl
Collecting cryptography<2.4,>=2.1.4
  Downloading https://files.pythonhosted.org/packages/98/0b/a6f293e5f10095dd8657a1b125c1ba6995c59d39cd8e20355475c8f760d0/cryptography-2.3.1-cp34-abi3-macosx_10_6_intel.whl (1.5MB)
     |████████████████████████████████| 1.5MB 637kB/s 
Collecting ldap3<2.6,>=2.5
  Downloading https://files.pythonhosted.org/packages/54/93/55d4de43abf3af1b60befa648811538b49701237e5cbda456608384b25ac/ldap3-2.5.2-py2.py3-none-any.whl (393kB)
     |████████████████████████████████| 399kB 1.5MB/s 
Collecting kaitaistruct<0.9,>=0.7
  Downloading https://files.pythonhosted.org/packages/23/71/8577ca06e81c1dc0ba03a39ae32e315175ba2d9df51befa3a45f47950056/kaitaistruct-0.8.tar.gz
Collecting pyperclip<1.7,>=1.6.0
  Downloading https://files.pythonhosted.org/packages/80/a4/7c65c8fb16787d74f720dfb1dee4227a65058f268e91014e24fd76b18f8b/pyperclip-1.6.5.tar.gz
Collecting sortedcontainers<2.1,>=1.5.4
  Downloading https://files.pythonhosted.org/packages/be/e3/a065de5fdd5849450a8a16a52a96c8db5f498f245e7eda06cc6725d04b80/sortedcontainers-2.0.5-py2.py3-none-any.whl
Collecting passlib<1.8,>=1.6.5
  Downloading https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl (498kB)
     |████████████████████████████████| 501kB 976kB/s 
Collecting brotlipy<0.8,>=0.7.0
  Downloading https://files.pythonhosted.org/packages/5f/d3/dbc8aafa09565a4946f788d8524e53772036f8f6ab280672775985b0f9d2/brotlipy-0.7.0-cp37-cp37m-macosx_10_14_x86_64.whl (389kB)
     |████████████████████████████████| 399kB 1.1MB/s 
Collecting tornado<5.2,>=4.3
  Downloading https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz (516kB)
     |████████████████████████████████| 522kB 896kB/s 
Collecting h2<4,>=3.0.1
  Downloading https://files.pythonhosted.org/packages/fb/e3/823a574b33aac578c3a171b1a2225ee8e1ad0c3842f3871bdc34e270f352/h2-3.1.1-py2.py3-none-any.whl (64kB)
     |████████████████████████████████| 71kB 3.1MB/s 
Collecting wsproto<0.12.0,>=0.11.0
  Downloading https://files.pythonhosted.org/packages/1f/bf/a4136bd7950c49f18a7d643f962e307cbed93ca115e0634656d88e02c333/wsproto-0.11.0-py2.py3-none-any.whl
Collecting ruamel.yaml<0.16,>=0.13.2
  Downloading https://files.pythonhosted.org/packages/a6/e0/e65db3b59ad417113b50040bd083e489309343f7653f4ce75ec52518ad56/ruamel.yaml-0.15.100-cp37-cp37m-macosx_10_9_x86_64.whl (254kB)
     |████████████████████████████████| 256kB 1.3MB/s 
Collecting pyOpenSSL<18.1,>=17.5
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
     |████████████████████████████████| 61kB 707kB/s 
Collecting blinker<1.5,>=1.4
  Downloading https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111kB)
     |████████████████████████████████| 112kB 911kB/s 
Collecting ipython-genutils
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting six
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting parso>=0.5.0
  Downloading https://files.pythonhosted.org/packages/a3/bd/bf4e5bd01d79906e5b945a7af033154da49fd2b0d5b5c705a21330323305/parso-0.5.1-py2.py3-none-any.whl (95kB)
     |████████████████████████████████| 102kB 1.4MB/s 
Collecting ptyprocess>=0.5
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting wcwidth
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7
  Downloading https://files.pythonhosted.org/packages/d5/61/32b1aa5ef1bf60be4ef679c4aae082a7ceef98517e0e0fde68072c6ef8b6/cffi-1.13.2-cp37-cp37m-macosx_10_6_intel.whl (258kB)
     |████████████████████████████████| 266kB 782kB/s 
Collecting hpack<4,>=2.3
  Downloading https://files.pythonhosted.org/packages/8a/cc/e53517f4a1e13f74776ca93271caef378dadec14d71c61c949d759d3db69/hpack-3.0.0-py2.py3-none-any.whl
Collecting h11~=0.7.0
  Downloading https://files.pythonhosted.org/packages/97/57/c0734cec5a9344d1feab295046011edbc6ba8e877ce1b822373257acdb61/h11-0.7.0-py2.py3-none-any.whl (53kB)
     |████████████████████████████████| 61kB 3.3MB/s 
Collecting pycparser
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
     |████████████████████████████████| 163kB 812kB/s 
Installing collected packages: pytz, sqlparse, Django, pdfkit, decorator, ipython-genutils, six, traitlets, pygments, parso, jedi, backcall, ptyprocess, pexpect, appnope, wcwidth, prompt-toolkit, pickleshare, ipython, lxml, python-dateutil, cycler, numpy, kiwisolver, pyparsing, matplotlib, future, pydot, click, asn1crypto, colorama, networkx, androguard, pyasn1, rsa, biplist, urllib3, idna, chardet, certifi, requests, soupsieve, beautifulsoup4, bs4, colorlog, altgraph, macholib, google-play-scraper, whitenoise, waitress, gunicorn, frida, psutil, shelljob, oscrypto, distro, urwid, hyperframe, pycparser, cffi, cryptography, ldap3, kaitaistruct, pyperclip, sortedcontainers, passlib, brotlipy, tornado, hpack, h2, h11, wsproto, ruamel.yaml, pyOpenSSL, blinker, mitmproxy, http-tools
    Running setup.py install for backcall ... done
    Running setup.py install for future ... done
    Running setup.py install for biplist ... done
    Running setup.py install for bs4 ... done
    Running setup.py install for google-play-scraper ... done
    Running setup.py install for frida ... done
    Running setup.py install for psutil ... done
    Running setup.py install for shelljob ... done
    Running setup.py install for urwid ... done
    Running setup.py install for pycparser ... done
    Running setup.py install for kaitaistruct ... done
    Running setup.py install for pyperclip ... done
    Running setup.py install for tornado ... done
    Running setup.py install for blinker ... done
Successfully installed Django-2.2.7 altgraph-0.16.1 androguard-3.3.5 appnope-0.1.0 asn1crypto-1.2.0 backcall-0.1.0 beautifulsoup4-4.8.1 biplist-1.0.3 blinker-1.4 brotlipy-0.7.0 bs4-0.0.1 certifi-2019.9.11 cffi-1.13.2 chardet-3.0.4 click-6.7 colorama-0.4.1 colorlog-4.0.2 cryptography-2.3.1 cycler-0.10.0 decorator-4.4.1 distro-1.4.0 frida-12.7.20 future-0.18.2 google-play-scraper-0.0.1.1 gunicorn-20.0.0 h11-0.7.0 h2-3.1.1 hpack-3.0.0 http-tools-1.0.1 hyperframe-5.2.0 idna-2.8 ipython-7.9.0 ipython-genutils-0.2.0 jedi-0.15.1 kaitaistruct-0.8 kiwisolver-1.1.0 ldap3-2.5.2 lxml-4.4.1 macholib-1.11 matplotlib-3.1.1 mitmproxy-4.0.4 networkx-2.4 numpy-1.17.4 oscrypto-1.1.0 parso-0.5.1 passlib-1.7.1 pdfkit-0.6.1 pexpect-4.7.0 pickleshare-0.7.5 prompt-toolkit-2.0.10 psutil-5.6.5 ptyprocess-0.6.0 pyOpenSSL-18.0.0 pyasn1-0.4.7 pycparser-2.19 pydot-1.4.1 pygments-2.4.2 pyparsing-2.2.2 pyperclip-1.6.5 python-dateutil-2.8.1 pytz-2019.3 requests-2.22.0 rsa-4.0 ruamel.yaml-0.15.100 shelljob-0.5.6 six-1.13.0 sortedcontainers-2.0.5 soupsieve-1.9.5 sqlparse-0.3.0 tornado-5.1.1 traitlets-4.3.3 urllib3-1.25.6 urwid-2.0.1 waitress-1.3.1 wcwidth-0.1.7 whitenoise-4.1.4 wsproto-0.11.0
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting python byte code files
Deleting temp and log files
Deleting DB
Deleting Secret File
Done
[INSTALL] Migrating Database
./setup.sh: line 62:  7357 Abort trap: 6           python manage.py makemigrations
./setup.sh: line 63:  7379 Abort trap: 6           python manage.py makemigrations StaticAnalyzer
./setup.sh: line 64:  7382 Abort trap: 6           python manage.py migrate
./setup.sh: line 65: wkhtmltopdf: command not found
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete

**Comment by Rollingsmoke** [comment]
attaching bug report 


Process:               Python [24922]
Path:                  /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.7.5 (3.7.5)
Code Type:             X86-64 (Native)
Parent Process:        Python [24918]
Responsible:           Terminal [496]
User ID:               ****

Date/Time:             2019-11-11 12:23:15.990 +0530
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Bridge OS Version:     4.1 (17P1081)
Anonymous UUID:        **********************************************

Sleep/Wake UUID:      *******************************************

Time Awake Since Boot: 6300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/usr/lib/libcrypto.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.

**Comment by ajinabraham** [comment]
Your Python3 or environment is screwed up. 
See:  https://stackoverflow.com/questions/58272830/python-crashing-on-macos-10-15-beta-19a582a-with-usr-lib-libcrypto-dylib

This is not a MobSF issue. hence closing.

**Comment by ITmustang** [comment]
@Rollingsmoke Catalina doesn't allow un-versioned dylibs to be called. follow the commands on this site and it'll fix it. worked for me. https://dbaontap.com/2019/11/11/python-abort-trap-6-fix-after-catalina-update/
