### ISSUE TITLE
MobSF APK installation fails on genymotion

### ISSUE THREAD

**Issue by Rollingsmoke** [MobSF/Mobile-Security-Framework-MobSF#1171]
[INFO] 13/Nov/2019 12:10:12 - ADB Restarted
[INFO] 13/Nov/2019 12:10:12 - Waiting for 2 seconds...
[INFO] 13/Nov/2019 12:10:14 - Connecting to Android 192.168.56.114:5555
[INFO] 13/Nov/2019 12:10:14 - Remounting /system
[INFO] 13/Nov/2019 12:10:14 - Android Version identified as 8.0
[INFO] 13/Nov/2019 12:10:14 - Environment MobSFyed Check
[INFO] 13/Nov/2019 12:10:14 - Starting HTTPs Proxy on 1337
[INFO] 13/Nov/2019 12:10:14 - Killing httptools UI
[INFO] 13/Nov/2019 12:10:14 - Enabling ADB Reverse TCP on 1337
[INFO] 13/Nov/2019 12:10:14 - Setting Global Proxy for Android VM
[INFO] 13/Nov/2019 12:10:14 - Starting Clipboard Monitor
[INFO] 13/Nov/2019 12:10:14 - Getting screen resolution
[INFO] 13/Nov/2019 12:10:14 - Installing APK
adb: failed to install /Users/*********/Desktop/Mobile-Security-Framework-MobSF/uploads/1eca983ec973dfd7675ea5b9ac8ad7cf/1eca983ec973dfd7675ea5b9ac8ad7cf.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

## ENVIRONMENT

```
OS and Version:Catalina
Python Version:3.7
MobSF Version:2.0.5
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by dokkillo** [comment]
Hi, 
I got the same problem, just do this:
* Go to Superuser app in the genimotion mobile
* Select settings
* Select Automattic response and the Allow

![genymotion](https://user-images.githubusercontent.com/920841/68770443-6f0f0280-0626-11ea-9cb3-229e94bad18f.png)

* Then return to load the app and it will work

**Comment by ajinabraham** [comment]
`Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`
The APK is not x86 compatible, so it failed to install.
