### ISSUE TITLE
mobsfying android runtime 'None type' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Kevintroll** [MobSF/Mobile-Security-Framework-MobSF#1175]
## ENVIRONMENT

```
OS and Version: Kali Linux
Python Version:
MobSF Version:
```

## EXPLANATION OF THE ISSUE

```
mobsfying android runtime 'None typr' object has no attribute 'decode' but if i check in adb connect <ip:port> my device is connected to the maching
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
Please don't put everything in title of the request
 please put a simple explicit title and fill the template

**Comment by Kevintroll** [comment]
mobsfying android runtime 'None typr' object has no attribute 'decode' 

![image](https://user-images.githubusercontent.com/53478733/69239695-0c52c500-0b58-11ea-921d-161f76ecc220.png)
![Screenshot from 2019-11-20 05-35-58](https://user-images.githubusercontent.com/53478733/69239734-25f40c80-0b58-11ea-8088-5e75aa3ed217.png)

**Comment by ajinabraham** [comment]
Is MobSF installed inside a VM?
I don't see Genymotion running inside Kali.

**Comment by Kevintroll** [comment]
I am connecting external Mobile device using TCPIP.

**Comment by Kevintroll** [comment]
> Is MobSF installed inside a VM?
> I don't see Genymotion running inside Kali.

Yes MobSF is installed in VM over Kali linux.
connecting Physical Android Smart Phone.

root@kali:~/TCPIP# adb devices
List of devices attached
192.168.0.32:5555	device


Still Issue is arising:
[INFO] 21/Nov/2019 06:27:42 - MobSFying Android instance
* daemon not running; starting now at tcp:5037
* daemon started successfully
[INFO] 21/Nov/2019 06:27:45 - ADB Restarted
[INFO] 21/Nov/2019 06:27:45 - Waiting for 2 seconds...
[INFO] 21/Nov/2019 06:27:47 - Connecting to Android 192.168.0.32:5555
[INFO] 21/Nov/2019 06:27:47 - Remounting /system
error: device offline
[ERROR] 21/Nov/2019 06:27:47 - Error Running ADB Command
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/android-sdk/platform-tools/adb', '-s', '192.168.0.32:5555', 'shell', 'mount', '-o', 'rw,remount', '/system']' returned non-zero exit status 1.
error: device offline
[ERROR] 21/Nov/2019 06:27:47 - Error Running ADB Command
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/android-sdk/platform-tools/adb', '-s', '192.168.0.32:5555', 'shell', 'getprop', 'ro.build.version.release']' returned non-zero exit status 1.
[ERROR] 21/Nov/2019 06:27:47 - MobSFying Android instance failed
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/operations.py", line 90, in mobsfy
    version = create_env.mobsfy_init()
  File "/root/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 296, in mobsfy_init
    version = self.get_android_version()
  File "/root/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/environment.py", line 247, in get_android_version
    and_version = out.decode('utf-8').rstrip()
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by Kevintroll** [comment]
> Please don't put everything in title of the request
> please put a simple explicit title and fill the template

Thank you for your suggestions, this very first time I am raining any issue in Git, will take care in future.

**Comment by ajinabraham** [comment]
This is not supported. Read the documentation clearly.

**Comment by Kevintroll** [comment]
How your application giving ratings. 7.4 High, 0 also High, 7.5 is info.
Please Explain the Procedure for making a report

Example

  ﻿
Code Analysis
ISSUE SEVERITY CVSS CWE OWASP FILES
Files may contain hardcoded sensitive informations like usernames,
passwords, keys etc. high *7.4* *CWE-312* *M9: Reverse Engineering*
com/secneo/apkwrapper/Helper.java
<http://0.0.0.0:8000/ViewSource/?file=com/secneo/apkwrapper/Helper.java&md5=1717ab3d9cceea4ed83f6a60b19b56f0&type=apk>
This App may request root (Super User) privileges. high *0* *CWE-250*
com/secneo/apkwrapper/a.java
<http://0.0.0.0:8000/ViewSource/?file=com/secneo/apkwrapper/a.java&md5=1717ab3d9cceea4ed83f6a60b19b56f0&type=apk>
The App logs information. Sensitive information should never be logged. info
*7.5* *CWE-532* com/alibaba/android/arouter/utils/DefaultLogger.java
<http://0.0.0.0:8000/ViewSource/?file=com/alibaba/android/arouter/utils/DefaultLogger.java&md5=1717ab3d9cceea4ed83f6a60b19b56f0&type=apk>
com/alibaba/android/arouter/utils/ClassUtils.java
<http://0.0.0.0:8000/ViewSource/?file=com/alibaba/android/arouter/utils/ClassUtils.java&md5=1717ab3d9cceea4ed83f6a60b19b56f0&type=apk>
com/alibaba/android/arouter/launcher/_ARouter.java
<http://0.0.0.0:8000/ViewSource/?file=com/alibaba/android/arouter/launcher/_ARouter.java&md5=1717ab3d9cceea4ed83f6a60b19b56f0&type=apk>
