### ISSUE TITLE
Run with doecker, nginx does reverse proxy, static Not Found

### ISSUE THREAD

**Issue by Pa55w0rd** [MobSF/Mobile-Security-Framework-MobSF#1178]
Run with doecker, nginx does reverse proxy, static Not Found
![image](https://user-images.githubusercontent.com/16274549/69516296-3b1fcf80-0f8c-11ea-9beb-8b277ec9aa1f.png)

**Comment by Pa55w0rd** [comment]
location /mobsf/ {
            proxy_pass http://0.0.0.0:39000/;
            index index.html index.htm;
        }

**Comment by superpoussin22** [comment]
take a look here : 
https://github.com/MobSF/RP4MobSF/blob/master/conf/conf.d/auth.conf
