### ISSUE TITLE
APKiD - Could not import APKiD

### ISSUE THREAD

**Issue by Takaeda4413** [MobSF/Mobile-Security-Framework-MobSF#1180]
## ENVIRONMENT

```
OS and Version: Kali GNU/Linux Rolling 2019.2
Python Version: 3.7
MobSF Version: 2.0
```

## EXPLANATION OF THE ISSUE

```
Im getting an error while running mobsf, says "APKiD - Could not import APKiD" I also set the APKID_ENABLED to True but it is still giving the same error.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step: run mobsf like normal
2. This is the second step: drag and drop or upload a normal apk
3. Further steps, etc. in the terminal it will say "could not import apk id"
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```
[INFO] 27/Nov/2019 03:17:38 - Mobile Security Framework v2.0.2 Beta
REST API Key: ***********************************
[INFO] 27/Nov/2019 03:17:38 - OS: Linux
[INFO] 27/Nov/2019 03:17:38 - Platform: Linux-4.19.0-kali4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[INFO] 27/Nov/2019 03:17:38 - Dist: ('Kali', 'kali-rolling', 'kali-rolling')
[INFO] 27/Nov/2019 03:17:38 - MobSF Basic Environment Check
[INFO] 27/Nov/2019 03:17:38 - Checking for Update.
[WARNING] 27/Nov/2019 03:17:38 - A new version of MobSF is available, Please update to v2.0.7 Beta from master branch.
[INFO] 27/Nov/2019 03:17:48 - MIME Type: application/vnd.android.package-archive FILE: ************************************
[INFO] 27/Nov/2019 03:17:48 - Performing Static Analysis of Android APK
[INFO] 27/Nov/2019 03:17:48 - Starting Analysis on : **************************
[INFO] 27/Nov/2019 03:17:48 - Generating Hashes
[INFO] 27/Nov/2019 03:17:48 - Unzipping
[INFO] 27/Nov/2019 03:17:48 - Getting Hardcoded Certificates/Keystores
[INFO] 27/Nov/2019 03:17:48 - APK Extracted
[INFO] 27/Nov/2019 03:17:48 - Converting AXML to XML
[INFO] 27/Nov/2019 03:17:51 - Reading Android Manifest
[INFO] 27/Nov/2019 03:17:51 - Parsing AndroidManifest.xml
[INFO] 27/Nov/2019 03:17:51 - Fetching icon path
[INFO] 27/Nov/2019 03:17:51 - Extracting Manifest Data
[INFO] 27/Nov/2019 03:17:51 - Fetching Details from Play Store: ************************
[WARNING] 27/Nov/2019 03:17:52 - Unable to get app details.
[INFO] 27/Nov/2019 03:17:52 - Manifest Analysis Started
[INFO] 27/Nov/2019 03:17:52 - Static Android Binary Analysis Started
[INFO] 27/Nov/2019 03:17:52 - Static Android Resource Analysis Started
[INFO] 27/Nov/2019 03:17:52 - Reading Code Signing Certificate
[ERROR] 27/Nov/2019 03:17:52 - APKiD - Could not import APKiD
[INFO] 27/Nov/2019 03:17:56 - Trackers Database is up-to-date
[INFO] 27/Nov/2019 03:17:56 - Detecting Trackers
[INFO] 27/Nov/2019 03:17:56 - APK -> JAVA
[INFO] 27/Nov/2019 03:17:56 - Decompiling to Java with jadx
[INFO] 27/Nov/2019 03:18:00 - DEX -> SMALI
[INFO] 27/Nov/2019 03:18:00 - Converting classes.dex to Smali Code
[INFO] 27/Nov/2019 03:18:00 - Static Android Code Analysis Started
[INFO] 27/Nov/2019 03:18:00 - Code Analysis Started on - java_source
[INFO] 27/Nov/2019 03:18:00 - Finished Code Analysis, Email and URL Extraction
[INFO] 27/Nov/2019 03:18:00 - Extracting Strings from APK
[INFO] 27/Nov/2019 03:18:00 - Detecting Firebase URL(s)
[INFO] 27/Nov/2019 03:18:00 - Performing Malware Check on extracted Domains
[INFO] 27/Nov/2019 03:18:04 - Malware Database is up-to-date
[INFO] 27/Nov/2019 03:18:04 - Generating Java and Smali Downloads
[INFO] 27/Nov/2019 03:18:04 - Generating Downloads
[INFO] 27/Nov/2019 03:18:04 - Zipping
[INFO] 27/Nov/2019 03:18:04 - Zipping
[INFO] 27/Nov/2019 03:18:04 - Connecting to Database
[INFO] 27/Nov/2019 03:18:04 - Saving to Database

**Comment by ajinabraham** [comment]
Use the latest version of MobSF and run setup.sh once.
