### ISSUE TITLE
Marking vulnerability as false positive

### ISSUE THREAD

**Issue by shounakitraj** [MobSF/Mobile-Security-Framework-MobSF#1189]
Hi,

Thank you for writing this tool which helps to perform static security analysis of apk files. I would like to know, is it possible to mark any vulnerability/security issue as False positive in current implementation? If not, is it possible to add the functionality?

This way it will be easier to maintain the history of the application.

**Comment by superpoussin22** [comment]
@phoenixadb time for a sonar connector ?

**Comment by superpoussin22** [comment]
Plugin is in progress and could arrive end of January

**Comment by ajinabraham** [comment]
enhancements are tracked separately

**Comment by kaczalapa** [comment]
Hello,
I want to refresh that issue and ask you when this feature can be implemented in your tool? I see it on TODO list on https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/264 but on the other hand you wrote that it is in progress half year ago. What is the status of this feature?

**Comment by ajinabraham** [comment]
This is something we plan to do after we change the our SAST core and that will take some time. We don't have a timeline for this yet.
