### ISSUE TITLE
No such file or directory - exodus_trackers

### ISSUE THREAD

**Issue by B4RD4k** [MobSF/Mobile-Security-Framework-MobSF#1190]
while uploading new APK into the system i got this error;

![image](https://user-images.githubusercontent.com/7777720/70234675-d58cc980-1769-11ea-82b1-f6a22df66bdd.png)

[Errno 2] No such file or directory: '/root/.MobSF/signatures/exodus_trackers'

**Comment by superpoussin22** [comment]
can you share the logs ?

**Comment by B4RD4k** [comment]
find out that my docker host date wasn't updated.
sorry

**Comment by Sandb0xED** [comment]
How did you change your docker host date? I tried the date +%T -s <date> 
However the operation wasn't permitted, even though I am root.

**Comment by Sandb0xED** [comment]
How did you change your docker host date? I tried the date +%T -s <date> 
However the operation wasn't permitted, even though I am root.
