### ISSUE TITLE
None type while trying to iterate Trackers

### ISSUE THREAD

**Issue by punkcoder** [MobSF/Mobile-Security-Framework-MobSF#1191]
## ENVIRONMENT

```
OS and Version: Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic
Python Version:
MobSF Version: v2.0.7
```

## EXPLANATION OF THE ISSUE

After uploading the APK, process begins processing the APK then crashes out while trying to iterate the trackers.

## STEPS TO REPRODUCE THE ISSUE

```
1. Follow directions for pulling docker image
2. Run docker image on port 8005:8000
3. Upload APK Via drag and drop
```

## LOG FILE

[2019-12-05 18:52:01 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2019-12-05 18:52:01 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-12-05 18:52:01 +0000] [1] [INFO] Using worker: threads
[2019-12-05 18:52:01 +0000] [8] [INFO] Booting worker with pid: 8
[INFO] 05/Dec/2019 18:52:17 - 
  __  __       _    ____  _____         ____    ___  
 |  \/  | ___ | |__/ ___||  ___| __   _|___ \  / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / __) || | | |
 | |  | | (_) | |_) |__) |  _|    \ V / / __/ | |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_____(_)___/ 

[INFO] 05/Dec/2019 18:52:17 - Mobile Security Framework v2.0.7 Beta
REST API Key: 987585ce34263e54452d100eab5280cce64f5a3df8c341dbc26577c8ac6941da
[INFO] 05/Dec/2019 18:52:17 - OS: Linux
[INFO] 05/Dec/2019 18:52:17 - Platform: Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 05/Dec/2019 18:52:17 - Dist: ubuntu 18.04 bionic
[INFO] 05/Dec/2019 18:52:17 - MobSF Basic Environment Check
[INFO] 05/Dec/2019 18:52:17 - Checking for Update.
[INFO] 05/Dec/2019 18:52:17 - No updates available.
[INFO] 05/Dec/2019 18:53:01 - MIME Type: application/vnd.android.package-archive FILE: bluetooth.apk
[INFO] 05/Dec/2019 18:53:01 - Performing Static Analysis of Android APK
[INFO] 05/Dec/2019 18:53:01 - Starting Analysis on : Bluetooth.apk
[INFO] 05/Dec/2019 18:53:01 - Generating Hashes
[INFO] 05/Dec/2019 18:53:01 - Unzipping
[INFO] 05/Dec/2019 18:53:01 - Getting Hardcoded Certificates/Keystores
[INFO] 05/Dec/2019 18:53:01 - APK Extracted
[INFO] 05/Dec/2019 18:53:01 - Converting AXML to XML
[INFO] 05/Dec/2019 18:53:08 - Reading Android Manifest
[INFO] 05/Dec/2019 18:53:08 - Parsing AndroidManifest.xml
[INFO] 05/Dec/2019 18:53:08 - Fetching icon path
[INFO] 05/Dec/2019 18:53:08 - Extracting Manifest Data
[INFO] 05/Dec/2019 18:53:08 - Fetching Details from Play Store: com.android.bluetooth
[INFO] 05/Dec/2019 18:53:08 - Manifest Analysis Started
[INFO] 05/Dec/2019 18:53:08 - Static Android Binary Analysis Started
[INFO] 05/Dec/2019 18:53:08 - Static Android Resource Analysis Started
[INFO] 05/Dec/2019 18:53:08 - Reading Code Signing Certificate
[INFO] 05/Dec/2019 18:53:09 - Running APKiD 2.0.3
[INFO] 05/Dec/2019 18:53:11 - Updating Trackers Database....
[INFO] 05/Dec/2019 18:53:11 - Detecting Trackers
[ERROR] 05/Dec/2019 18:53:11 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 189, in static_analyzer
    tracker_res = tracker.get_trackers()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 169, in get_trackers
    trackers = self.detect_trackers()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 164, in detect_trackers
    return self.detect_trackers_in_list(self.get_embedded_classes())
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 148, in detect_trackers_in_list
    for res in itertools.starmap(_detect_tracker, args):
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 138, in _detect_tracker
    for clazz in class_list:
TypeError: 'NoneType' object is not iterable
[ERROR] 05/Dec/2019 18:53:11 - 'NoneType' object is not iterable
[ERROR] 05/Dec/2019 18:53:11 - Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
Are you seeing the issue with all the APKs or just one?

**Comment by punkcoder** [comment]
I'm going to go ahead and close this, I don't think this is on your side... Originally, I thought it was with mobsf, but the more that I'm looking at the APKs I'm thinking I've got some malformed packages.

**Comment by punkcoder** [comment]
Thanks for the fantastic work, sorry to break your workflow.
