### ISSUE TITLE
cannot find the READ_SETTINGS permission

### ISSUE THREAD

**Issue by sfsgtc** [MobSF/Mobile-Security-Framework-MobSF#1201]
dvm_permissions.py  cannot find the READ_SETTINGS permission

**Comment by superpoussin22** [comment]
please provide more logs

**Comment by sfsgtc** [comment]
![11](https://user-images.githubusercontent.com/58774019/70762993-94aa3b80-1d8d-11ea-8316-73b5d101e16f.png)
@superpoussin22
