### ISSUE TITLE
Unable to view Java files after static apk scan

### ISSUE THREAD

**Issue by Chan9390** [MobSF/Mobile-Security-Framework-MobSF#1202]
## ENVIRONMENT 

Running it as a docker container.

```
docker pull opensecurity/mobile-security-framework-mobsf:latest
docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
```
(Image ID: 75192e58ae45)

## EXPLANATION OF THE ISSUE

Decompiled Java files of an apk are not available.

## STEPS TO REPRODUCE THE ISSUE

1. Upload the apk and start the static scan
2. Scroll down to `Decompiled Code` and click `View Java`. The java files section will be empty.

## LOG FILE

![image](https://user-images.githubusercontent.com/12944530/70686634-efcb2800-1cd2-11ea-933c-a854be1d7586.png)

**Comment by superpoussin22** [comment]
can you share the apk ?

**Comment by ajinabraham** [comment]
This is probably due to an issue with a particular APK. Need the apk for debugging.

**Comment by Chan9390** [comment]
I cannot share the apk as it is proprietary. Thanks for the response.
