### ISSUE TITLE
Getting error after uploading apk

### ISSUE THREAD

**Issue by Et0hacker** [MobSF/Mobile-Security-Framework-MobSF#1204]
GUI -Error ( Just after compliting analyze )
Error

Raised when run() is called with check=True and the process returns a non-zero exit status. Attributes: cmd, returncode, stdout, stderr, output

Command '['java', '-jar', '/root/Mobile-Security-Framework-MobSF1/StaticAnalyzer/tools/baksmali-2.3.4.jar', 'list', 'classes', '/root/Mobile-Security-Framework-MobSF1/uploads/97c032d2864990b1ea9d65263b9428a0/classes.dex']' returned non-zero exit status 1.

How can i fix this?

**Comment by ajinabraham** [comment]
Follow documentation properly!
Set JAVA_HOME env variable or set java path in MobSF/settings.py

**Comment by dileep7007** [comment]
I am also facing same issue, as you suggested  "Set JAVA_HOME env variable or set java path in MobSF/settings.py" i did the same, then also i am facing the issue

How can i fix this?
![still](https://user-images.githubusercontent.com/69950531/90783142-594d0d00-e31d-11ea-80fe-4f3f5a549e99.png)
