### ISSUE TITLE
Unable to parse folder from binskin nuget installation

### ISSUE THREAD

**Issue by JosephOswaldo98** [MobSF/Mobile-Security-Framework-MobSF#1205]
Tengo este problema después de instalar python y los certificados ejecuto el archivo setup.py que recomiendan en las instrucciones pero responde con el siguiente error

![MobSF](https://user-images.githubusercontent.com/31598269/71046564-adf11600-2106-11ea-855f-e9834f4e0cae.JPG)

SO: Windows 7

**Comment by superpoussin22** [comment]
please go to slack channel to discuss this :)
did you install all the required tools 

> Install Git
Install Python 3.7
Install JDK 8+
Install Microsoft Visual C++ Build Tools
Install OpenSSL
Download & Install wkhtmltopdf as per the wiki instructions
Add the folder that contains wkhtmltopdf binary to environment variable PATH.

**Comment by ajinabraham** [comment]
You do not have to run setup.py inside Windows. Run setup.bat instead. Please follow the documentation properly
