### ISSUE TITLE
can use android studio x86 emulator for dynamic analyzer[FEATURE]

### ISSUE THREAD

**Issue by mousavi007** [MobSF/Mobile-Security-Framework-MobSF#1207]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajinabraham** [comment]
Genymotion is x86 emulator and we support it already.
