### ISSUE TITLE
Black background  PDF Report is generated.

### ISSUE THREAD

**Issue by balramrexwal** [MobSF/Mobile-Security-Framework-MobSF#1209]
PDF report generated by mobsf is black background.Can't find the issue 
![Screenshot_2019-12-26_05-02-18](https://user-images.githubusercontent.com/19252923/71473958-42164980-27a7-11ea-9578-16d218f6d482.png)

When i execute ,normal pdf is genrated without black background

`wkhtmltopdf http://google.com google.pdf`

Logs of the mobsf given below
:
`[INFO] 26/Dec/2019 10:07:16 - Starting Analysis on : Firefox Lite — Fast Browser Games Deals and News_v2.0.5(17500)_apkpure.com.apk
[INFO] 26/Dec/2019 10:07:16 - Analysis is already Done. Fetching data from the DB...
[INFO] 26/Dec/2019 10:07:16 - VirusTotal: Check for existing report
[INFO] 26/Dec/2019 10:07:22 - VirusTotal: Scan finished, information embedded
[INFO] 26/Dec/2019 10:07:37 - Fetching data from DB for PDF Report Generation (Android)
[INFO] 26/Dec/2019 10:07:37 - Analysis is already Done. Fetching data from the DB...
[INFO] 26/Dec/2019 10:07:37 - VirusTotal: Check for existing report
[INFO] 26/Dec/2019 10:07:43 - VirusTotal: Scan finished, information embedded
[DEBUG] 26/Dec/2019 10:07:43 - Exception while resolving variable 'packagename' in template 'pdf/android_binary_analysis.pdf.html'.
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/root/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'packagename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'Context' has no attribute 'packagename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'packagename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/template/base.py", line 849, `

and long html code which i think not to post it here,then
`[WARNING] 26/Dec/2019 10:07:44 - Not Found: /favicon.ico`

**Comment by superpoussin22** [comment]
no problem on ubuntu .
Did you run setup.sh without eror ?

can you move to Slack channel  for discussion cause sounds like this is not a bug

**Comment by paddhole** [comment]
I am having the similar problem , how did you fix it ??? i am using kali linux with the latest version

**Comment by artikrh** [comment]
This issue persists when you are using dark theme of the OS that you are using (such as Kali Linux). Switch to light theme and you may read the report properly (it seems that `wkhtmltopdf` uses system-wide settings).

**Comment by daihoujai** [comment]
Yo! Finally found a way out! As the default html background is transparent, the report generated looks dark.  I tried to edit the pdf templates (under templates/pdf) and add bgcolor="FFFFFF" to body tag. It works! The PDF reports generated with white background finally! :D

**Comment by ajinabraham** [comment]
Mind sending a PR?
