### ISSUE TITLE
[FEATURE] Add authentication method

### ISSUE THREAD

**Issue by iabdulla** [MobSF/Mobile-Security-Framework-MobSF#1211]
First of all, thank you for your effort you put it in sech as great tools like this, I am suggested to add an authentication method on your tools for login to the portal. Also add some categorization of the users such as (admin, analyst, etc.).

Also, it will be better for using MobSF in enterprise environment if it will support several authentication methods like: 

- Active Directory
- LDAP
- OAuth 2
- Local authentication

**Comment by superpoussin22** [comment]
why don't you use a Reverse Proxy like nginx ? theres an example with basic authent 
https://github.com/MobSF/RP4MobSF

**Comment by iabdulla** [comment]
thank you for that, i will try it, but i have one question, do i need to install the MobSF as docker image or the normal installation ? because i am install it in Linux ?

**Comment by superpoussin22** [comment]
You can have MobSF installed as a regular application and use a RP as docker or as a regular application too

**Comment by iabdulla** [comment]
thank you for that information, I will try it out and let you know about my experience.

**Comment by ajinabraham** [comment]
We now support password  and SSO authentication from MobSF v4.0
