### ISSUE TITLE
[ERROR] 01/Jan/2020 13:09:24 - invalid syntax (apkid.py, line 38)

### ISSUE THREAD

**Issue by nocomp** [MobSF/Mobile-Security-Framework-MobSF#1213]
hi
finally succeed install msf on ubuntu 16.04 but when i do an analysis i get this error, any tips for a fix?
thxx for your help

nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$ ./run.sh 
[2020-01-01 14:08:49 +0100] [10351] [INFO] Starting gunicorn 20.0.4
[2020-01-01 14:08:49 +0100] [10351] [INFO] Listening at: http://0.0.0.0:8000 (10351)
[2020-01-01 14:08:49 +0100] [10351] [INFO] Using worker: threads
[2020-01-01 14:08:49 +0100] [10354] [INFO] Booting worker with pid: 10354
[INFO] 01/Jan/2020 13:08:50 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 01/Jan/2020 13:08:50 - Mobile Security Framework v3.0.0 Beta
REST API Key: b3356d878ca6a8ff77d6a157fa6bcdbdb7014568150bfb951789377da73796ae
[INFO] 01/Jan/2020 13:08:50 - OS: Linux
[INFO] 01/Jan/2020 13:08:50 - Platform: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[INFO] 01/Jan/2020 13:08:50 - Dist: ubuntu 16.04 xenial
[INFO] 01/Jan/2020 13:08:50 - MobSF Basic Environment Check
[INFO] 01/Jan/2020 13:08:50 - Checking for Update.
No changes detected
[INFO] 01/Jan/2020 13:08:51 - No updates available.
[INFO] 01/Jan/2020 13:08:51 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 01/Jan/2020 13:08:51 - Mobile Security Framework v3.0.0 Beta
REST API Key: b3356d878ca6a8ff77d6a157fa6bcdbdb7014568150bfb951789377da73796ae
[INFO] 01/Jan/2020 13:08:51 - OS: Linux
[INFO] 01/Jan/2020 13:08:51 - Platform: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[INFO] 01/Jan/2020 13:08:52 - Dist: ubuntu 16.04 xenial
[INFO] 01/Jan/2020 13:08:52 - MobSF Basic Environment Check
[INFO] 01/Jan/2020 13:08:52 - Checking for Update.
Migrations for 'StaticAnalyzer':
  StaticAnalyzer/migrations/0001_initial.py
    - Create model RecentScansDB
    - Create model StaticAnalyzerAndroid
    - Create model StaticAnalyzerIOS
    - Create model StaticAnalyzerWindows
[INFO] 01/Jan/2020 13:08:52 - No updates available.
[INFO] 01/Jan/2020 13:08:53 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 01/Jan/2020 13:08:53 - Mobile Security Framework v3.0.0 Beta
REST API Key: b3356d878ca6a8ff77d6a157fa6bcdbdb7014568150bfb951789377da73796ae
[INFO] 01/Jan/2020 13:08:53 - OS: Linux
[INFO] 01/Jan/2020 13:08:53 - Platform: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[INFO] 01/Jan/2020 13:08:53 - Dist: ubuntu 16.04 xenial
[INFO] 01/Jan/2020 13:08:53 - MobSF Basic Environment Check
[INFO] 01/Jan/2020 13:08:53 - Checking for Update.
Operations to perform:
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  Applying StaticAnalyzer.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
[INFO] 01/Jan/2020 13:08:53 - No updates available.
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK
[INFO] 01/Jan/2020 13:08:54 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 01/Jan/2020 13:08:54 - Mobile Security Framework v3.0.0 Beta
REST API Key: b3356d878ca6a8ff77d6a157fa6bcdbdb7014568150bfb951789377da73796ae
[INFO] 01/Jan/2020 13:08:54 - OS: Linux
[INFO] 01/Jan/2020 13:08:54 - Platform: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[INFO] 01/Jan/2020 13:08:54 - Dist: ubuntu 16.04 xenial
[INFO] 01/Jan/2020 13:08:54 - MobSF Basic Environment Check
[INFO] 01/Jan/2020 13:08:54 - Checking for Update.
Operations to perform:
  Synchronize unmigrated apps: DynamicAnalyzer, MalwareAnalyzer, MobSF, messages, staticfiles
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
[INFO] 01/Jan/2020 13:08:55 - No updates available.
[INFO] 01/Jan/2020 13:09:06 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 01/Jan/2020 13:09:06 - Mobile Security Framework v3.0.0 Beta
REST API Key: b3356d878ca6a8ff77d6a157fa6bcdbdb7014568150bfb951789377da73796ae
[INFO] 01/Jan/2020 13:09:06 - OS: Linux
[INFO] 01/Jan/2020 13:09:06 - Platform: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[INFO] 01/Jan/2020 13:09:06 - Dist: ubuntu 16.04 xenial
[INFO] 01/Jan/2020 13:09:06 - MobSF Basic Environment Check
[INFO] 01/Jan/2020 13:09:06 - Checking for Update.
[INFO] 01/Jan/2020 13:09:06 - No updates available.
[INFO] 01/Jan/2020 13:09:15 - MIME Type: application/vnd.android.package-archive FILE: jet.apk
[INFO] 01/Jan/2020 13:09:15 - Performing Static Analysis of Android APK
[INFO] 01/Jan/2020 13:09:15 - Starting Analysis on : jet.apk
[INFO] 01/Jan/2020 13:09:15 - Generating Hashes
[INFO] 01/Jan/2020 13:09:15 - Unzipping
[INFO] 01/Jan/2020 13:09:16 - Getting Hardcoded Certificates/Keystores
[INFO] 01/Jan/2020 13:09:16 - APK Extracted
[INFO] 01/Jan/2020 13:09:16 - Converting AXML to XML
[INFO] 01/Jan/2020 13:09:22 - Reading Android Manifest
[INFO] 01/Jan/2020 13:09:22 - Parsing AndroidManifest.xml
[INFO] 01/Jan/2020 13:09:22 - Fetching icon path
[INFO] 01/Jan/2020 13:09:23 - Extracting Manifest Data
[INFO] 01/Jan/2020 13:09:23 - Fetching Details from Play Store: com.jet.jet.app
[INFO] 01/Jan/2020 13:09:24 - Manifest Analysis Started
[INFO] 01/Jan/2020 13:09:24 - Static Android Binary Analysis Started
[INFO] 01/Jan/2020 13:09:24 - Static Android Resource Analysis Started
[INFO] 01/Jan/2020 13:09:24 - Reading Code Signing Certificate
[ERROR] 01/Jan/2020 13:09:24 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/nocomp/tools/android/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 185, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/home/nocomp/tools/android/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 24, in apkid_analysis
    from apkid.apkid import Scanner, Options
  File "/usr/local/lib/python3.5/dist-packages/apkid/apkid.py", line 38
    SCANNABLE_FILE_MAGICS: Dict[str, Set[bytes]] = {
                         ^
SyntaxError: invalid syntax
[ERROR] 01/Jan/2020 13:09:24 - invalid syntax (apkid.py, line 38)
[ERROR] 01/Jan/2020 13:09:24 - Internal Server Error: /StaticAnalyzer/

**Comment by nocomp** [comment]
after some search, it seems cause it need pyton3.6
so i ve installed python3.6-venv then i ve python3.6 -m venv venv but i still have 3.5.2 :/
(venv) nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$ python --version
Python 3.5.2
(venv) nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$ 


what did i do wrong???
thxx for your help

**Comment by ajinabraham** [comment]
I am sorry I can't help with that. You need to install the required version of Python.

**Comment by nocomp** [comment]
hi @ajinabraham 
i ve been looking some closed topics and as you said it s a python-venv issue.
i ve fixed it
(venv) nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$ python --version
Python 3.6.10
(venv) nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$ 


but now when i launch run.sh i get this error
 File "/home/nocomp/tools/android/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 21, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
[2020-01-01 16:55:09 +0100] [20346] [INFO] Worker exiting (pid: 20346)
[2020-01-01 16:55:09 +0100] [20343] [INFO] Shutting down: Master
[2020-01-01 16:55:09 +0100] [20343] [INFO] Reason: Worker failed to boot.
nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$ 


so i ve re run config.sh
and i  get this error:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-RCiuZN/google-play-scraper/setup.py'"'"'; __file__='"'"'/tmp/pip-install-RCiuZN/google-play-scraper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-RCiuZN/google-play-scraper/pip-egg-info
         cwd: /tmp/pip-install-RCiuZN/google-play-scraper/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RCiuZN/google-play-scraper/setup.py", line 3, in <module>
        from google_play_scraper import __version__
      File "google_play_scraper/__init__.py", line 2, in <module>
        from urllib.error import HTTPError
    ImportError: No module named error
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

any idea what is happening?
thxx for your help
