### ISSUE TITLE
ModuleNotFoundError: No module named 'distro'

### ISSUE THREAD

**Issue by nocomp** [MobSF/Mobile-Security-Framework-MobSF#1214]
hi
since i ve installed python-venv i can t run run.sh, i get this error:

File "/home/nocomp/tools/android/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 21, in
import distro
ModuleNotFoundError: No module named 'distro'
[2020-01-01 16:55:09 +0100] [20346] [INFO] Worker exiting (pid: 20346)
[2020-01-01 16:55:09 +0100] [20343] [INFO] Shutting down: Master
[2020-01-01 16:55:09 +0100] [20343] [INFO] Reason: Worker failed to boot.
nocomp@P0wNB0X:~/tools/android/Mobile-Security-Framework-MobSF$

so i ve redo the pip install -r requirements.txt
then run config.sh
and get this error:

ERROR: Command errored out with exit status 1:
command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-RCiuZN/google-play-scraper/setup.py'"'"'; file='"'"'/tmp/pip-install-RCiuZN/google-play-scraper/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-RCiuZN/google-play-scraper/pip-egg-info
cwd: /tmp/pip-install-RCiuZN/google-play-scraper/
Complete output (7 lines):
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-RCiuZN/google-play-scraper/setup.py", line 3, in
from google_play_scraper import version
File "google_play_scraper/init.py", line 2, in
from urllib.error import HTTPError
ImportError: No module named error
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

and of course there are no module named error i can pip install

any idea about how to solve this?
thxx for your time @ajinabraham

**Comment by ajinabraham** [comment]
Sorry I can't help on non MobSF issues. Besides this is a GitHub issue tracker for MobSF bugs.
