### ISSUE TITLE
Window10 use pycharm local debug can not load static web resources

### ISSUE THREAD

**Issue by LeoonZHANG** [MobSF/Mobile-Security-Framework-MobSF#1220]
Environment: win10 +pycharm
 
bug description :
When we use pycharm debug, haven this erro: 
![image](https://user-images.githubusercontent.com/12006000/72306466-186b8680-36b2-11ea-852e-399c6c94c9a3.png)

Then we open 127.0.0.1:8000:
![image](https://user-images.githubusercontent.com/12006000/72306499-3f29bd00-36b2-11ea-907d-bb901fc1f4ae.png)

Infect version: V3.0.0 beta

Solutions:
open MobSF.settings , Problems in line 205
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
comment this line ,and then add
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'static')]

I don't know if this erro happened to anyone else , hope can help someone.

**Comment by ajinabraham** [comment]
How are you running MobSF?

**Comment by LeoonZHANG** [comment]
> How are you running MobSF?

running Mobsf in pycharm ,this is the Configurations
![image](https://user-images.githubusercontent.com/12006000/72310417-acdae680-36bc-11ea-8fb4-fc8cbf7966b6.png)

then click [Run] button

**Comment by ajinabraham** [comment]
The production configuration uses Gunicorn. See run.sh. We do not support any other means of running MobSF
