### ISSUE TITLE
While scanning IPA, there is a error while Reading from Info.plist

### ISSUE THREAD

**Issue by prtk19** [MobSF/Mobile-Security-Framework-MobSF#1222]
I am using MobSF v3.0.0 beta
in docker 

**Please find log below**

[INFO] 16/Jan/2020 09:35:54 - OS: Linux
[INFO] 16/Jan/2020 09:35:54 - Platform: Linux-4.14.154-boot2docker-x86_64-with-Ubuntu-18.04-bionic
[INFO] 16/Jan/2020 09:35:54 - Dist: ubuntu 18.04 bionic
[INFO] 16/Jan/2020 09:35:54 - MobSF Basic Environment Check
[INFO] 16/Jan/2020 09:35:54 - Checking for Update.
[INFO] 16/Jan/2020 09:35:57 - No updates available.
[INFO] 16/Jan/2020 09:36:15 - MIME Type: application/octet-stream FILE: *************01.00.25.ipa
[INFO] 16/Jan/2020 09:36:16 - Performing Static Analysis of iOS IPA
[INFO] 16/Jan/2020 09:36:16 - iOS Static Analysis Started
[INFO] 16/Jan/2020 09:36:16 - iOS Binary (IPA) Analysis Started
[INFO] 16/Jan/2020 09:36:16 - Generating Hashes
[INFO] 16/Jan/2020 09:36:16 - Extracting IPA
[INFO] 16/Jan/2020 09:36:16 - Unzipping
[INFO] 16/Jan/2020 09:36:16 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 16/Jan/2020 09:36:16 - iOS Info.plist Analysis Started
[INFO] 16/Jan/2020 09:36:16 - Finding Info.plist in iOS Binary
[INFO] 16/Jan/2020 09:36:16 - Checking Permissions
[INFO] 16/Jan/2020 09:36:16 - Checking for Insecure Connections
[ERROR] 16/Jan/2020 09:36:16 - Reading from Info.plist
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/plist_analysis.py", line 99, in plist_analysis
    plist_info['inseccon'] = check_transport_security(plist_obj)
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/app_transport_security.py", line 52, in check_transport_security
    if config.get('NSTemporaryExceptionAllowsInsecureHTTPLoads'): AttributeError: 'str' object has no attribute 'get'
[ERROR] 16/Jan/2020 09:36:16 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 89, in static_analyzer_ios
    app_dict['appstore'] = app_search(infoplist_dict.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 16/Jan/2020 09:36:16 - 'NoneType' object has no attribute 'get'
[ERROR] 16/Jan/2020 09:36:16 - Internal Server Error: /StaticAnalyzer_iOS/

**Comment by superpoussin22** [comment]
can you share the ipa ?

**Comment by prtk19** [comment]
Hi @superpoussin22, sorry,  i am cannot.
The app is utilizing swift library, could this be causing issue? I am not sure where to look into, any lead would be helpful.

Thanks.

**Comment by ajinabraham** [comment]
Cannot troubleshoot without the binary

**Comment by prtk19** [comment]
hi Ajin, i have mailed you the ipa

**Comment by prtk19** [comment]
reopening bug

**Comment by ajinabraham** [comment]
@prtk19 Where did you send the IPA? I haven't received it yet.

**Comment by prtk19** [comment]
hi Ajin, i had mailed you at ajin25@gmail.com in 21st, re sending it again. i had mentioned bug id on subject line

**Comment by ajinabraham** [comment]
Gmail thinks it's harmful and send the mail to my spam box

**Comment by ajinabraham** [comment]
The IPA works fine on docker for me. I am using the latest docker image. There was a debug message issue with template. That's hot fixed in latest master.

**Comment by prtk19** [comment]
@ajinabraham thanks , issue resolved and able to scan app now
