### ISSUE TITLE
Found elf built without Position Independent Executable (PIE) flag	

### ISSUE THREAD

**Issue by sugip0304** [MobSF/Mobile-Security-Framework-MobSF#1223]
Hi,

i got this error 

Found elf built without Position Independent Executable (PIE) flag

FILES
lib/mips64/libmodft2.so lib/mips64/libmodpng.so lib/mips64/libc++_shared.so lib/mips64/libjniPdfium.so lib/mips64/libmodpdfium.so

is this bugs or something

**Comment by ajinabraham** [comment]
it's a report finding. verify manually
