### ISSUE TITLE
[FEATURE] Make get_app_name search in localizations.xml if app_name isn't found in strings.xml

### ISSUE THREAD

**Issue by Nicoolai** [MobSF/Mobile-Security-Framework-MobSF#1224]
Our android project keeps `app_name` in `app/src/main/res/values/localizations.xml` instead of `app/src/main/res/values/strings.xml`.

I am a bit unsure how common this is. Perhaps no-one else structures their localization strings like this, if that is the case, maybe this is not something that should be made?

So, I am kind of looking for some input as to wether or not this is something that would make sense adding?

**Is your feature request related to a problem? Please describe.**
Scan crashes after android .zip files has been uploaded, as it cannot locate `app_name` in `app/src/main/res/values/strings.xml`

**Describe the solution you'd like**
If it cannot find it in `strings.xml` I would like it to look in `localizations.xml` instead.

**Describe alternatives you've considered**
Could also simply set an "unknown" value (or similar) if it cannot find `app_name` in `strings.xml`. Possibly a better solution. Definitely better than crashing :)

**Additional context**
Not really.

**Comment by Nicoolai** [comment]
So, this is for android and zip file upload. Not sure if I can add labels myself?

**Comment by ajinabraham** [comment]
Can you share the sample format of localisations.xml

**Comment by Nicoolai** [comment]
It's the exact same as strings.xml. 
I just talked to one of our android devs, and it sounds like you can name your file whatever you want, and it will still work, as long as it's in the values folder.

Perhaps, if it doesn't find app_name in strings, it could look at whatever other xml files exists, in the folder?

If still no app_name found, just set it to blank (or "unknown", if blank wont work).

**Comment by ajinabraham** [comment]
The fix should happen here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/static_analyzer.py#L535

1. Search for all xml files under `app/src/main/res/values/` if app_name is not found in `strings.xml`
2. Handle both android studio and legacy eclipse source structure.
3. This line https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/static_analyzer.py#L553 has to be changed to check `None` on `app_name_match`

PRs are always welcome.

**Comment by Nicoolai** [comment]
I guess we can close this?
