### ISSUE TITLE
Use of Genymotion in combination with docker deployment

### ISSUE THREAD

**Issue by mr-gosh** [MobSF/Mobile-Security-Framework-MobSF#1225]
**Is your feature request related to a problem? Please describe.**
Even if we use docker for the MobSF deployment it should be possible to use genymotion on antoher machine to trigger the dynamic analysis. In the documentation is clearly written that this is not possible - can this be changed to make it possible through some manual effort?

**Describe the solution you'd like**
If we configure Genymotion on another machine and make the genymotion port accessable through exposing the port in the internal network - i would like to be able to let MobSF connect to the remote IP through some config.

**Comment by ajinabraham** [comment]
We have a PR in work that will address this.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1193

**Comment by ajinabraham** [comment]
As a hack it works except for the web proxy on master.  We did some testing and it seems there are some connection issues with adb from docker to a remote host.
