### ISSUE TITLE
Django debug mode enabled

### ISSUE THREAD

**Issue by V1dhun** [MobSF/Mobile-Security-Framework-MobSF#1227]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/ea9d47e3d4571175e02c33354448856654e09d5a/MobSF/settings.py#L150

refers : https://www.acunetix.com/vulnerabilities/web/django-debug-mode-enabled/

**Comment by ajinabraham** [comment]
We will be running in debug mode until we move out of beta. This helps our users to provided detailed stack traces and exceptions when bugs occurs. Also unlike a traditional application, MobSF is deployed at your own host.
