### ISSUE TITLE
[FEATURE] Return ZIP type in REST API

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#1229]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Currently for zipped source files, the upload api doesn't return what type of zip it is. This needs to be explicitly set or scan should be able to happen without specifying the type of zip, ie `andzip or ioszip` .

**Describe the solution you'd like**
Need investigation to find out which is easier to make changes at upload api or other apis.

**Describe alternatives you've considered**
N/A

**Additional context**
A person using REST api has no way to identify the type of the zip file. He has to explicitly mention zip type in multiple cases, but none of the initial API call tells that.

**Comment by Nicoolai** [comment]
The scan api endpoint `/api/v1/scan` only asks you to specify `zip`, not `andzip` or `ioszip`.  
It's only when you ask for reports (json/pdf) you need to provide this.  

It would be pretty sweet if you didn't have to provide scan_type at all, when asking for a report.  
It already did the scan, right? Shouldn't it be enough to just provide the hash?

**Comment by Nicoolai** [comment]
I would be happy to look into this.

**Comment by ajinabraham** [comment]
Addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1234
