### ISSUE TITLE
[FEATURE] Docker tag versioning

### ISSUE THREAD

**Issue by oxr463** [MobSF/Mobile-Security-Framework-MobSF#1237]
The only available tag is [latest](https://hub.docker.com/r/opensecurity/mobile-security-framework-mobsf/tags); it would be helpful to have each tagged release built and uploaded to Docker Hub.

**Comment by superpoussin22** [comment]
agree with this :) it was in my backlog .
we need to discuss this internaly to define the tag structure

**Comment by ajinabraham** [comment]
Configured tagged builds in Dockerhub, you will see version tags in future for all releases.

**Comment by jcavar** [comment]
I am not sure if this is still working as expected. There is no 3.0.5 tag anymore, only 3.1.1 which is latest.

**Comment by ajinabraham** [comment]
This was configured a long time back but never worked. I think it started to work with an updated regex recently. Hopefully, it will start working from now on.
![Screenshot 2020-08-12 at 12 12 10 PM](https://user-images.githubusercontent.com/4301109/90039890-42f7df00-dc95-11ea-9f25-675424637126.png)
