### ISSUE TITLE
Mass Static Analysis documentation out of date

### ISSUE THREAD

**Issue by oxr463** [MobSF/Mobile-Security-Framework-MobSF#1238]
The example command provided just returns the script usage instructions:

```sh
python mass_static_analysis.py -s 127.0.0.1:8000 -d /home/files/
```
Source: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/4.-Mass-Static-Analysis

**Comment by ajinabraham** [comment]
Thanks for pointing out. It's updated.
