### ISSUE TITLE
No internet connection for dynamic analysis

### ISSUE THREAD

**Issue by liyakhatalisheikh** [MobSF/Mobile-Security-Framework-MobSF#1239]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.8
MobSF Version: 3.0
```

## EXPLANATION OF THE ISSUE

```
Got the internet when started the genymotion android emulator, But when started dynamic analysis using MobSF it's showing no internet connection 
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Start genymotion android emulator and search for anything in google, Search results came
2. Start Dynamic analysis and search for the same thing in google, No internet connection
```

**Comment by ajinabraham** [comment]
MobSF Dynamic Analysis will only bypass SSL for the app you are testing and not the entire OS.

**Comment by liyakhatalisheikh** [comment]
@ajinabraham I didn't get what you're saying, Can you please elaborate the solution

**Comment by ajinabraham** [comment]
This is probably because 
1. App uses a custom SSL pinning library or code. You will need to find that and bypass it
2. The device has networking issue and doesn't have internet. Verify that device has internet by stopping dynamic analysis (This will remove global proxy settings from the device) and running the device standalone from Genymotion.

**Comment by liyakhatalisheikh** [comment]
@ajinabraham Thank you for your reply,
We are checking the first case i.e., SSL bypass, In second case we are getting the internet when we start gennymotion emulator but once dynamic analysis has started we are not getting the internet.

**Comment by trapp3rhat** [comment]
Hello bro,

Here I am also getting same kind of issue in my genymotion (Android 7.1) and android mobile phone with android 4.4.4 version.

Here I have ran the dynamic analysis then I can't able access the internet through the device.

But here I don't know how to stop the dynamic analysis from the MOBSF.

Thanks

**Comment by trapp3rhat** [comment]
Hello,

That issue has been fixed after run this below command

adb shell settings put global http_proxy :0

Dynamic analyzer uses the global proxy settings which is not displayed in the wifi settings in phone that is the issue which can be fixed by running this command 

Thanks

**Comment by ajinabraham** [comment]
MobSF will remove proxy global proxy when you generate report after dynamic analysis
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android/environment.py#L164

**Comment by trapp3rhat** [comment]
Thanks for the response bro.

Here I need to specify the proxy IP and port  on the above mentioned environment.py file before starting the dynamic analyzer then the traffic will be captured by the proxy during the dynamic analysis right ??

Thanks

**Comment by ajinabraham** [comment]
Nope. MobSF will detect everything automatically

**Comment by Gunkkk** [comment]
> Hello,
> 
> That issue has been fixed after run this below command
> 
> adb shell settings put global http_proxy :0
> 
> Dynamic analyzer uses the global proxy settings which is not displayed in the wifi settings in phone that is the issue which can be fixed by running this command
> 
> Thanks

it works!
