### ISSUE TITLE
[FEATURE] Better handling of info.plist files in IOS Source

### ISSUE THREAD

**Issue by Nicoolai** [MobSF/Mobile-Security-Framework-MobSF#1241]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
When working with large IOS projects, it is not uncommon, at least in our org, that projects are structured into modules.  
Each module has their own info.plist. This causes some problems with mobSF as it appears to simply pick the first info.plist if finds (when scanning IOS Source, it is not an issue in binary as all the plist's are combined into one), which could easily be a sub-module instead of the actual app.

Furthermore, you are free to name the info.plist file as you please. It does not have to be called info.plist.

I would like to hear some opinions on how to solve this and if it even should be solved. Maybe we're the only ones with this issue?

**Describe the solution you'd like**
Perhaps we could have an optional parameter, in the scan api call, with the name of the configuration that gets built. That way, it could check the project.pbxproj file, and find that configuration.   
In the configuration, in the project file, it shows the path the info.plist file and also values that you might replace, in it, using variable placeholders.  
Combining these two things could potentially give you the proper info.plist content.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Nicoolai** [comment]
I haven't really been able to come up with any good solutions for this, so I am giving up.  
Instead, I will change our process and include the binary in the source and simply extract the final info.plist from binary and do the rest of the analysis on src.

**Comment by ajinabraham** [comment]
Tracked separately
