### ISSUE TITLE
Kubernetes chart!

### ISSUE THREAD

**Issue by itsecforu** [MobSF/Mobile-Security-Framework-MobSF#1249]
Hey guys! Have u got a kubernetes chart or yaml configs? Thx

**Comment by itsecforu** [comment]
i tryied to install via kubectl run , but cant open Web GUI (

**Comment by ajinabraham** [comment]
MobSF is self contained. You only need to run MobSF docker image with kubectl. We don't have plans for making charts.

**Comment by itsecforu** [comment]
I did it with postgre and nginx. I can share this settings if i will fix this [issue](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1169)
