### ISSUE TITLE
Getting Error while run Frida Live API

### ISSUE THREAD

**Issue by hemangdk** [MobSF/Mobile-Security-Framework-MobSF#1258]
I am getting error message popping while running Frida Live API for Real Unrooted Device - Google Pixel 3a

DataTables warning: table id=autotbl - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

Can you please tell me what can be the issue ?

**Comment by superpoussin22** [comment]
MobSF works only with Genymotion and not with real devices

**Comment by hemangdk** [comment]
Thank you for quick response.
Is MobSF planning to run on real device ?

**Comment by ajinabraham** [comment]
MobSF can support it out of the box. But we do not officially support it.

**Comment by sidahmed-malaoui** [comment]
I'm still having this issue, even though I'm using a genymotion device.

Any advice ?
