### ISSUE TITLE
Various problems when performing dynamic analysis

### ISSUE THREAD

**Issue by JorgeTebruski** [MobSF/Mobile-Security-Framework-MobSF#1261]
**Environment**
```
OS and Version: Windows 10 1909
Python Version: 3.7.4
MobSF Version: 3.0.4
```
**Issue**

When dynamically analyzing the app, there is an error in the "Live API Monitor".

![Erro DataTables](https://user-images.githubusercontent.com/38569298/74410734-8b366180-4e18-11ea-92b0-21e121b6b210.jpg)

When you select "Start Activity Test" you start to show several errors causing Genymotion to restart, and consequently causing it to restart without an internet connection. Just returning to normal when resetting the VM.

![Bug](https://user-images.githubusercontent.com/38569298/74410767-a43f1280-4e18-11ea-8154-1f71f3fe929a.gif)

**Steps to reproduce the issue**
```
1. Start dynamic analysis
2. Click in Live API Monitor
3. Click in Start Activity Test
```

**Log file**
[INFO] 13/Feb/2020 03:03:15 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 13/Feb/2020 03:03:15 - Mobile Security Framework v3.0.4 Beta
[INFO] 13/Feb/2020 03:03:15 - OS: Windows
[INFO] 13/Feb/2020 03:03:15 - Platform: Windows-10-10.0.18362-SP0
[INFO] 13/Feb/2020 03:03:16 - Dist:   
[INFO] 13/Feb/2020 03:03:16 - MobSF Basic Environment Check
[INFO] 13/Feb/2020 03:03:16 - Checking for Update.
[INFO] 13/Feb/2020 03:03:17 - No updates available.
[INFO] 13/Feb/2020 03:03:29 - MIME Type: application/vnd.android.package-archive FILE: id estudantil_v1.2.1_apkpure.com.apk
[INFO] 13/Feb/2020 03:03:29 - Performing Static Analysis of Android APK
[INFO] 13/Feb/2020 03:03:29 - Starting Analysis on : ID Estudantil_v1.2.1_apkpure.com.apk
[INFO] 13/Feb/2020 03:03:29 - Analysis is already Done. Fetching data from the DB...
[INFO] 13/Feb/2020 03:03:29 - VirusTotal: Check for existing report
[INFO] 13/Feb/2020 03:03:31 - VirusTotal: Scan finished, information embedded
[INFO] 13/Feb/2020 03:03:50 - Creating Dynamic Analysis Environment
[INFO] 13/Feb/2020 03:03:56 - ADB Restarted
[INFO] 13/Feb/2020 03:03:56 - Waiting for 2 seconds...
[INFO] 13/Feb/2020 03:03:58 - Connecting to Android 192.168.115.101:5555
[INFO] 13/Feb/2020 03:03:58 - Waiting for 2 seconds...
[INFO] 13/Feb/2020 03:04:00 - Restarting ADB Daemon as root
[INFO] 13/Feb/2020 03:04:00 - Waiting for 2 seconds...
[INFO] 13/Feb/2020 03:04:02 - Reconnect to Android Device
[INFO] 13/Feb/2020 03:04:02 - Waiting for 2 seconds...
[INFO] 13/Feb/2020 03:04:04 - Remounting /system
[INFO] 13/Feb/2020 03:04:04 - Android Version identified as 9.0
[INFO] 13/Feb/2020 03:04:04 - Environment MobSFyed Check
[WARNING] 13/Feb/2020 03:04:04 - This Android instance is not MobSfyed.
MobSFying the android runtime environment
[INFO] 13/Feb/2020 03:04:04 - Android Version identified as 9.0
[INFO] 13/Feb/2020 03:04:04 - Android instance architecture identified as x86
[INFO] 13/Feb/2020 03:04:04 - Copying frida server
[INFO] 13/Feb/2020 03:04:06 - Installing MobSF RootCA
[INFO] 13/Feb/2020 03:04:07 - Installing MobSF Clipboard Dumper
[INFO] 13/Feb/2020 03:04:08 - MobSFying Completed!
[INFO] 13/Feb/2020 03:04:08 - Starting HTTPs Proxy on 1337
[INFO] 13/Feb/2020 03:04:13 - Enabling ADB Reverse TCP on 1337
[INFO] 13/Feb/2020 03:04:13 - Setting Global Proxy for Android VM
[INFO] 13/Feb/2020 03:04:13 - Starting Clipboard Monitor
[INFO] 13/Feb/2020 03:04:13 - Getting screen resolution
[INFO] 13/Feb/2020 03:04:13 - Installing APK
[INFO] 13/Feb/2020 03:04:17 - Testing Environment is Ready!
[INFO] 13/Feb/2020 03:04:47 - Starting Instrumentation
[INFO] 13/Feb/2020 03:04:47 - Starting Frida Server
[INFO] 13/Feb/2020 03:04:47 - Waiting for 2 seconds...
[INFO] 13/Feb/2020 03:04:48 - Frida Logs live streaming
[INFO] 13/Feb/2020 03:04:49 - Frida Logs live streaming
[INFO] 13/Feb/2020 03:04:50 - Spawning br.gov.mec.idestudantil
[DEBUG] 13/Feb/2020 03:04:53 - [Frida] Loaded Frida Script - api_monitor
[DEBUG] 13/Feb/2020 03:04:53 - [Frida] Loaded Frida Script - debugger_check_bypass
[DEBUG] 13/Feb/2020 03:04:53 - [Frida] Loaded Frida Script - root_bypass
[DEBUG] 13/Feb/2020 03:04:53 - [Frida] Loaded Frida Script - ssl_pinning_bypass
[DEBUG] 13/Feb/2020 03:04:53 - [Frida] [API Monitor] Cannot find android.os.Process.start
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [API Monitor] Cannot find org.apache.http.impl.client.AbstractHttpClient.execute
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [API Monitor] Cannot find com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] TrustManagerImpl.checkTrustedRecursive() not found
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] TrustManagerImpl.verifyChain() not found
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] okhttp CertificatePinner not found
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] DataTheorem trustkit not found
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] Appcelerator PinningTrustManager not found
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] Apache Cordova SSLCertificateChecker not found
[DEBUG] 13/Feb/2020 03:04:54 - [Frida] [SSL Pinning Bypass] Wultra CertStore.validateFingerprint not found
[INFO] 13/Feb/2020 03:06:12 - Starting API monitor streaming
[INFO] 13/Feb/2020 03:06:12 - Starting API monitor streaming
[INFO] 13/Feb/2020 03:09:53 - Starting API monitor streaming
[INFO] 13/Feb/2020 03:10:16 - Starting Instrumentation
[INFO] 13/Feb/2020 03:10:16 - Frida Server is already running
[INFO] 13/Feb/2020 03:10:17 - Spawning br.gov.mec.idestudantil
[DEBUG] 13/Feb/2020 03:10:20 - [Frida] Loaded Frida Script - api_monitor
[DEBUG] 13/Feb/2020 03:10:20 - [Frida] Loaded Frida Script - debugger_check_bypass
[DEBUG] 13/Feb/2020 03:10:20 - [Frida] Loaded Frida Script - root_bypass
[DEBUG] 13/Feb/2020 03:10:20 - [Frida] Loaded Frida Script - ssl_pinning_bypass
[DEBUG] 13/Feb/2020 03:10:20 - [Frida] [API Monitor] Cannot find android.os.Process.start
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [API Monitor] Cannot find org.apache.http.impl.client.AbstractHttpClient.execute
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [API Monitor] Cannot find com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] TrustManagerImpl.checkTrustedRecursive() not found
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] TrustManagerImpl.verifyChain() not found
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] okhttp CertificatePinner not found
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] DataTheorem trustkit not found
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] Appcelerator PinningTrustManager not found
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] Apache Cordova SSLCertificateChecker not found
[DEBUG] 13/Feb/2020 03:10:21 - [Frida] [SSL Pinning Bypass] Wultra CertStore.validateFingerprint not found
[INFO] 13/Feb/2020 03:11:32 - Starting API monitor streaming
[INFO] 13/Feb/2020 03:11:32 - Starting API monitor streaming
[INFO] 13/Feb/2020 03:11:37 - Starting Logcat streaming
[INFO] 13/Feb/2020 03:11:38 - Starting Logcat streaming
[WARNING] 13/Feb/2020 03:11:38 - Not Found: /favicon.ico
[INFO] 13/Feb/2020 03:21:08 - Activity tester
[INFO] 13/Feb/2020 03:21:09 - Fetching activities for br.gov.mec.idestudantil
[INFO] 13/Feb/2020 03:21:09 - Starting Activity Tester...
[INFO] 13/Feb/2020 03:21:09 - 15 Activities Identified
[INFO] 13/Feb/2020 03:21:09 - Launching Activity - 1. br.gov.mec.idestudantil.activity.OnboardActivity
[INFO] 13/Feb/2020 03:21:09 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:21:13 - Activity screenshot captured
[INFO] 13/Feb/2020 03:21:13 - Stopping app
[INFO] 13/Feb/2020 03:21:13 - Launching Activity - 2. br.gov.mec.idestudantil.activity.BaixarDependenteActivity
[INFO] 13/Feb/2020 03:21:14 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:21:19 - Activity screenshot captured
[INFO] 13/Feb/2020 03:21:19 - Stopping app
[INFO] 13/Feb/2020 03:21:19 - Launching Activity - 3. br.gov.mec.idestudantil.activity.VinculoActivity
[INFO] 13/Feb/2020 03:21:20 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:21:26 - Activity screenshot captured
[INFO] 13/Feb/2020 03:21:26 - Stopping app
[INFO] 13/Feb/2020 03:21:27 - Launching Activity - 4. br.gov.mec.idestudantil.activity.QrCodeActivity
[INFO] 13/Feb/2020 03:21:28 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:21:34 - Activity screenshot captured
[INFO] 13/Feb/2020 03:21:34 - Stopping app
[INFO] 13/Feb/2020 03:21:35 - Launching Activity - 5. br.gov.mec.idestudantil.activity.AddDependenteIdActivity
[INFO] 13/Feb/2020 03:21:35 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:21:42 - Activity screenshot captured
[INFO] 13/Feb/2020 03:21:42 - Stopping app
[INFO] 13/Feb/2020 03:21:42 - Launching Activity - 6. br.gov.mec.idestudantil.activity.AddMyIdActivity
[INFO] 13/Feb/2020 03:21:43 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:21:49 - Activity screenshot captured
[INFO] 13/Feb/2020 03:21:49 - Stopping app
[INFO] 13/Feb/2020 03:21:50 - Launching Activity - 7. br.gov.mec.idestudantil.activity.DetalheActivity
[INFO] 13/Feb/2020 03:21:52 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:22:00 - Activity screenshot captured
[INFO] 13/Feb/2020 03:22:00 - Stopping app
[INFO] 13/Feb/2020 03:22:06 - Launching Activity - 8. br.gov.mec.idestudantil.activity.AddIdActivity
[INFO] 13/Feb/2020 03:22:06 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:22:15 - Activity screenshot captured
[INFO] 13/Feb/2020 03:22:15 - Stopping app
[INFO] 13/Feb/2020 03:22:17 - Launching Activity - 9. br.gov.mec.idestudantil.activity.HomeActivity
[INFO] 13/Feb/2020 03:22:20 - Waiting for 3 seconds...
[ERROR] 13/Feb/2020 03:22:24 - Error Running ADB Command
Traceback (most recent call last):
  File "C:\Users\Tebruski\Desktop\ENGENHARIA REVERSA\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 92, in adb_command
    result = subprocess.check_output(args)
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Genymobile\\Genymotion\\tools\\adb.exe', '-s', '192.168.115.101:5555', 'shell', 'screencap', '-p', '/data/local/stream.png']' returned non-zero exit status 1.
[ERROR] 13/Feb/2020 03:22:24 - Error Running ADB Command
Traceback (most recent call last):
  File "C:\Users\Tebruski\Desktop\ENGENHARIA REVERSA\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 92, in adb_command
    result = subprocess.check_output(args)
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Genymobile\\Genymotion\\tools\\adb.exe', '-s', '192.168.115.101:5555', 'shell', 'screencap', '-p', '/data/local/stream.png']' returned non-zero exit status 1.
[ERROR] 13/Feb/2020 03:22:24 - Error Running ADB Command
Traceback (most recent call last):
  File "C:\Users\Tebruski\Desktop\ENGENHARIA REVERSA\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 92, in adb_command
    result = subprocess.check_output(args)
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Genymobile\\Genymotion\\tools\\adb.exe', '-s', '192.168.115.101:5555', 'shell', 'screencap', '-p', '/data/local/stream.png']' returned non-zero exit status 1.
[INFO] 13/Feb/2020 03:22:40 - Activity screenshot captured
[INFO] 13/Feb/2020 03:22:40 - Stopping app
[INFO] 13/Feb/2020 03:22:40 - Launching Activity - 10. br.gov.mec.idestudantil.activity.SplashScreen
[INFO] 13/Feb/2020 03:22:40 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:23:05 - Activity screenshot captured
[INFO] 13/Feb/2020 03:23:05 - Stopping app
[INFO] 13/Feb/2020 03:23:06 - Launching Activity - 11. br.gov.mec.idestudantil.activity.LoginActivity
[INFO] 13/Feb/2020 03:23:07 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:23:44 - Activity screenshot captured
[INFO] 13/Feb/2020 03:23:44 - Stopping app
[INFO] 13/Feb/2020 03:23:45 - Launching Activity - 12. br.gov.mec.idestudantil.activity.WebLoginActivity
[INFO] 13/Feb/2020 03:23:59 - Waiting for 3 seconds...
[ERROR] 13/Feb/2020 03:24:04 - Error Running ADB Command
Traceback (most recent call last):
  File "C:\Users\Tebruski\Desktop\ENGENHARIA REVERSA\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 92, in adb_command
    result = subprocess.check_output(args)
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\Tebruski\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Genymobile\\Genymotion\\tools\\adb.exe', '-s', '192.168.115.101:5555', 'pull', '/data/local/stream.png', 'C:\\Users\\Tebruski\\Desktop\\ENGENHARIA REVERSA\\Mobile-Security-Framework-MobSF-master\\downloads/screen/screen.png']' returned non-zero exit status 1.
[INFO] 13/Feb/2020 03:24:08 - Activity screenshot captured
[INFO] 13/Feb/2020 03:24:08 - Stopping app
[INFO] 13/Feb/2020 03:24:09 - Launching Activity - 13. br.gov.serpro.pvlibrary.MainActivity
[INFO] 13/Feb/2020 03:24:09 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:24:19 - Activity screenshot captured
[INFO] 13/Feb/2020 03:24:19 - Stopping app
[INFO] 13/Feb/2020 03:24:19 - Launching Activity - 14. br.gov.serpro.mobile.fotodocumento.FotoDocumentoActivity
[INFO] 13/Feb/2020 03:24:22 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:24:29 - Activity screenshot captured
[INFO] 13/Feb/2020 03:24:29 - Stopping app
[INFO] 13/Feb/2020 03:24:29 - Launching Activity - 15. com.google.android.gms.common.api.GoogleApiActivity
[INFO] 13/Feb/2020 03:24:30 - Waiting for 3 seconds...
[INFO] 13/Feb/2020 03:24:34 - Activity screenshot captured
[INFO] 13/Feb/2020 03:24:34 - Stopping app

PS: I tested some apps and this was the only one that happens.

**Comment by ajinabraham** [comment]
When dynamically analyzing the app, there is an error in the "Live API Monitor".
-- This is expected. The table will be populated only if the app is instrumented successfully. If the app crashes, that means the instrumentation has failed and you won't see anything there.


When you select "Start Activity Test" you start to show several errors causing Genymotion to restart, and consequently causing it to restart without an internet connection. Just returning to normal when resetting the VM.
-- Need to talk with genymotion support for that
