### ISSUE TITLE
ERROR Reading from Info.plist

### ISSUE THREAD

**Issue by lscsg** [MobSF/Mobile-Security-Framework-MobSF#1263]
[ERROR] 14/Feb/2020 01:28:19 - Reading from Info.plist
Traceback (most recent call last):
  File "/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/plist_analysis.py", line 62, in plist_analysis
    dirs = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/Mobile-Security-Framework-MobSF/uploads/0a5ad326a750b28a4eddb92683b705a3/Payload/'
[ERROR] 14/Feb/2020 01:28:19 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 99, in static_analyzer_ios
    app_dict['appstore'] = app_search(infoplist_dict.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 14/Feb/2020 01:28:19 - 'NoneType' object has no attribute 'get'
[ERROR] 14/Feb/2020 01:28:19 - Internal Server Error: /StaticAnalyzer_iOS/

Getting this error when trying to perform static analysis on IPA file. I checked the plist and it looked okay.

**Comment by ajinabraham** [comment]
Is that a valid IPA with `Payload` directory? Please share the IPA for debugging.

**Comment by lscsg** [comment]
Can I send it to you directly?

**Comment by ajinabraham** [comment]
email: ajin25 ATgmail

**Comment by ajinabraham** [comment]
As per the conversation over email, the IPA is Invalid. MobSF expects it to have Payload directory.
