### ISSUE TITLE
[FEATURE] Properly Handle Multi-Part-apk Files (apx)

### ISSUE THREAD

**Issue by mr-gosh** [MobSF/Mobile-Security-Framework-MobSF#1267]
**Is your feature request related to a problem? Please describe.**
If I want to analyse mutli part apk file using apps its not supported to upload multiple files for one analysis

**Describe the solution you'd like**
either there should be a way to add multiple files to one dedicated analysis, or there should be a possibility to add mutliple .obb and/or .apk files into one zip file to get an overall result

**Describe alternatives you've considered**
as mentioned above there could be an .api endpoint to add files to an existing analysis that could than be merged or chained, OR a specified way to add multiple files to one archive for propper handling

**Additional context**
An App to get an Idea about the format of these Apps could be [Netflix](https://play.google.com/store/apps/details?id=com.netflix.mediaclient&hl=en)
[Aurora](https://f-droid.org/en/packages/com.aurora.store/) is for example able to download apps like these.

**Comment by ajinabraham** [comment]
Right now you can scan them if you unzip the APK and scan them individually. But I will track this as a feature.

**Comment by schniggie** [comment]
I think this is a really needed feature, because dynamic analysis does not work for this bundled apps.
