### ISSUE TITLE
Assets.car parser

### ISSUE THREAD

**Issue by blshkv** [MobSF/Mobile-Security-Framework-MobSF#1271]
Hi, thanks a lot for working on this tool.

During a recent .IPA file review, I discovered multiple Assets.car files with BOMStore header.
After a quick google, I found the following article:
https://blog.timac.org/2018/1112-quicklook-plugin-to-visualize-car-files/

He released few tools (with source code), however they are all for OSX sources.

I was wondering if you can find/write a cross-platform alternative and include this parser into MobSF

Thanks!

**Comment by ajinabraham** [comment]
I would be happy to support this is a python version of the parser is available. At this point we have other enhancements with higher priority so this will be tracked separately.
