### ISSUE TITLE
Save as HTML

### ISSUE THREAD

**Issue by blshkv** [MobSF/Mobile-Security-Framework-MobSF#1272]
Hi, I noticed that the current PDF report requires a huge binaries to be installed.
First, pdfkit is required, which depends on wkhtmltopdf, which in turn depends on absolute qtwebkit package (must be replaced with qtwebengine).

Could you make an option to save as HTML please? That should simplify the whole process.

Please also a note that each section in the report has <previous> and <next> buttons. The report should include all data.

**Comment by ajinabraham** [comment]
You could use the browser function to save as html.

**Comment by ajinabraham** [comment]
For any custom output, you will have to generate them from the JSON API

**Comment by blshkv** [comment]
Sorry, i wasn't clear. Saving using browser doesn't save the whole report if there are multiple pages (under next / previous buttons in report sections

**Comment by ajinabraham** [comment]
Well we have to use pagination to support large reports that otherwise will make browsers unresponsive on rendering. so if you need a different output format, you have to create that from the JSON output. we will not support that way of printing with the current architecture.

**Comment by blshkv** [comment]
Well, yeah. That pagination kills the report. That's the reason of this report. 

Can you create a page without a pagination, and let users to download it perhaps instead if opening in a browser ?

**Comment by ajinabraham** [comment]
We won't be doing it since it doesn't meet any actual purpose. But you could disable paging by changing https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/templates/static_analysis/android_binary_analysis.html#L1617 to `false`

**Comment by blshkv** [comment]
Ок, that will do it. Thanks!
