### ISSUE TITLE
After uploading apk file, not able to click upload and analyse button. Nothing is dispalying

### ISSUE THREAD

**Issue by testing98** [MobSF/Mobile-Security-Framework-MobSF#1274]
[

## ENVIRONMENT

```
OS and Version: Windows 7 
Python Version:3.7.6
MobSF Version:3.0.4 beta
```

## STEPS TO REPRODUCE THE ISSUE
1. Open the web brwoser 127.0.0.1:8000
2. Selected apk file

[Screen Capture](https://user-images.githubusercontent.com/9430789/74911686-1e583400-53e3-11ea-973f-93a67090873c.png)

```


1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
can you provide details please ? when you open an issue you must fill the form not only the title

**Comment by ajinabraham** [comment]
Incomplete bug reports will be closed.
