### ISSUE TITLE
[FEATURE] Check if isCleartextTrafficPermitted is set to true in network_security_config file

### ISSUE THREAD

**Issue by rajuraju14** [MobSF/Mobile-Security-Framework-MobSF#1277]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
isCleartextTrafficPermitted returns whether cleartext network traffic (e.g. HTTP, FTP, XMPP, IMAP, SMTP -- without TLS or STARTTLS) is permitted for communicating with a specific hostname for this process.

**Describe the solution you'd like**
Create a check that checks for this setting when it's set to true and report it along with the domains associated

**Describe alternatives you've considered**
N/A

**Additional context**

https://developer.android.com/reference/android/security/NetworkSecurityPolicy.html#isCleartextTrafficPermitted()

https://developer.android.com/training/articles/security-config

**Comment by ajinabraham** [comment]
Added in 3.1.1

**Comment by rajuraju14** [comment]
@ajinabraham where in the source code was this feature added? Thanks!

**Comment by ajinabraham** [comment]
PR not pushed yet, will happen today.
