### ISSUE TITLE
(tcp_error: A communication error occurred: "") view resul report analysis APK

### ISSUE THREAD

**Issue by trongky** [MobSF/Mobile-Security-Framework-MobSF#1278]
## ENVIRONMENT

```
OS and Version: Ubuntu 18.04
Python Version: Python 3.7
MobSF Version: last version
```

## EXPLANATION OF THE ISSUE

```
When I upload the apk file and see the result, the indicator shows the result "tcp_error: A communication error occurred:". I checked on the server there was no error returned.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
tcp_error: A communication error occurred: ""

```

**Comment by superpoussin22** [comment]
sounds like i is a pure network issue do you have a FW or a proooxy/RP in the path ?
did you try with another browser ?
can you move to slack to discuss this ?

**Comment by trongky** [comment]
Hi support team,

I check issues network no problem.
You can visit site view :
http://45.32.1.52:8000/recent_scans/

Thank ./.

**Comment by superpoussin22** [comment]
just upload an apk and it works

**Comment by trongky** [comment]
But I don't view result scan ☹
You can help me ☹

**Comment by superpoussin22** [comment]
did you try from outside or from your network , from outside I can get the report and the result for the apk I push to your mobsf
