### ISSUE TITLE
App Score is not working 

### ISSUE THREAD

**Issue by god0fcode** [MobSF/Mobile-Security-Framework-MobSF#1279]
While the scan gets completed. score is calculated based on the initail value defined in:

avg_cvss = 0
    app_score = 100

the formula is not working to calculate the score in shared func

**Comment by ajinabraham** [comment]
Not enough information. 
please report issues with all requested information.
MobSF version, host is is missing and we need a sample app that demonstrate the said issue

**Comment by god0fcode** [comment]
I am using the latest mob sf version.

If we scan any app, app score is always 100.

**Comment by ajinabraham** [comment]
Specify version no also share the apk

**Comment by ajinabraham** [comment]
Cannot troubleshoot further without reproducing the issue. Hence closing the issue.

**Comment by ajinabraham** [comment]
Ref conversation: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1069#issuecomment-589969524
