### ISSUE TITLE
Shows "Google Firebase Analytics" even after disabling. 

### ISSUE THREAD

**Issue by karthik-dusk** [MobSF/Mobile-Security-Framework-MobSF#1294]
## ENVIRONMENT

```
OS and Version: Android 4+
Python Version: 3.7
MobSF Version: MobSF v3.0.4 Beta
```

## EXPLANATION OF THE ISSUE
MobSF shows "Google Firebase Analytics" tracker in the tracker even after disabling it as mentioned by the google in their documentation here  
https://firebase.google.com/docs/analytics/configure-data-collection?platform=android

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Create a new Android App 
2. Add FCM support (FireBase Cloud Messaging)
3. Follow the procedure to disable analytics/trackers
4. Upload the generated apk to MobSF
5. One will see the "Google Firebase Analytics" tracker listed in trackers
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by ajinabraham** [comment]
This might be because you still have the firebase related Code/SDK in the APK. Tracker Detection works by looking into libraries or sdks that comes with the binary. Reopen if you still think there is a bug.

**Comment by karthik-dusk** [comment]
Even though there is a library used for Push Notifications, I am disabling "Google Firebase Analytics", as mentioned by Google. 
In this case, MobSF should not show this tracker detection. 
There is certainly a flaw in the tracker detection logic. So, reopening it.

**Comment by karthik-dusk** [comment]
Please reopen, no option to reopen this issue.

**Comment by ajinabraham** [comment]
MobSF will detect it if it sees Firebase related classes in code. It doesn't matter if you programmatically disable it or not. That's how tracker logic work. If you are sure that the SDK is not included the binary, please share a sample binary for troubleshooting.

**Comment by karthik-dusk** [comment]
Let me share the binary asap.

> MobSF will detect if it sees Firebase related classes in code. It doesn't matter if you programmatically disable it or not.

This is giving a wrong info to the user.

**Comment by ajinabraham** [comment]
Please do.
There is no reason to have firebase sdk code in the binary if it's not enabled.

**Comment by karthik-dusk** [comment]
Firebase sdk is used for pushnotifications also, here in this context, we are just disabling "Firebase Analytics", we are not disabling push-notifications. 
When we disable analytics, MobSF blindly should not show the tracker, just by seeing if the Firebase sdk is present or not.

**Comment by ajinabraham** [comment]
We use rules from https://reports.exodus-privacy.eu.org/en/trackers/49/
Based on that we look for `com.google.firebase.analytics. | com.google.android.gms.measurement.` in code. If you think this is an issue, you could reach-out to them.
