### ISSUE TITLE
iOS: NSFaceIDUsageDescription 

### ISSUE THREAD

**Issue by martin-1337** [MobSF/Mobile-Security-Framework-MobSF#1298]
## IMPORTANT

The permission NSFaceIDUsageDescription of an iOS-App could not be identified and will not be shown in the section APPLICATION PERMISSIONS

<img width="285" alt="Bildschirmfoto 2020-03-05 um 01 57 42" src="https://user-images.githubusercontent.com/61656179/75937390-01147280-5e85-11ea-8551-0017243009e2.png">

## ENVIRONMENT

OS and Version: Debian GNU/Linux 10 (buster)
Python Version: 2.7.16
MobSF Version: 3.0.0 beta

**Comment by ajinabraham** [comment]
Please share the Info.plist file contents or the IPA for troubleshooting this issue.

**Comment by martin-1337** [comment]
Hi Abraham,

 

as requested from you side, please find the attached info.plist
 

Kind regard

martin-1337

 
 

Gesendet: Donnerstag, 05. März 2020 um 17:01 Uhr
Von: "Ajin Abraham" <notifications@github.com>
An: MobSF/Mobile-Security-Framework-MobSF <Mobile-Security-Framework-MobSF@noreply.github.com>
Cc: martin-1337 <mschuermeyer@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [MobSF/Mobile-Security-Framework-MobSF] iOS: NSFaceIDUsageDescription (#1298)


Please share the Info.plist file contents or the IPA for troubleshooting this issue.

**Comment by ajinabraham** [comment]
@martin-1337 You will have to upload it here in the github issues page. Github is not showing attachments that came in via email reply.

**Comment by martin-1337** [comment]
Added the file info.plist, see issue

**Comment by karolpiateknet** [comment]
I believe this case is missing in the https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/ios/permission_analysis.py

**Comment by karolpiateknet** [comment]
PR: https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1303

**Comment by ajinabraham** [comment]
Should be fixed in lated master. Thanks @karolpiateknet
