### ISSUE TITLE
IP address disclosure issue

### ISSUE THREAD

**Issue by frida12345** [MobSF/Mobile-Security-Framework-MobSF#1299]
In static analysis :code analysis, the issue " IP address disclosure is not showing the correct file location. It is been tested on various apks. Those file location it shows where  a dot (.) is coming between any numeric value in the code. It seems considering such values as IP. However it is observed that it cannot be an IP. tested on apps l from google playstore like, Bhim adhaar UBI, KVB UPay, U-Mobile, bob, maha_UPI, SBI yono and many more.

![image](https://user-images.githubusercontent.com/58165424/75951052-edfba580-5e78-11ea-9529-5deafccd2362.png)

![image](https://user-images.githubusercontent.com/58165424/75951005-cefd1380-5e78-11ea-97f2-c8bb036c9dd6.png)
![image](https://user-images.githubusercontent.com/58165424/75951084-023fa280-5e79-11ea-820e-52bac45fa9b8.png)

![image](https://user-images.githubusercontent.com/58165424/75951112-16839f80-5e79-11ea-8703-94b95eaa5236.png)

**Comment by ajinabraham** [comment]
This is a false positive. Our IP address regex is very forgiving to capture most of the IP address or look alike format. There is a room for improvement. I will track this as an enhancement.
