### ISSUE TITLE
Droidmon

### ISSUE THREAD

**Issue by DimitriBurve** [MobSF/Mobile-Security-Framework-MobSF#1301]
Hello,

I use the latest MobSF version. I tested in an avd in android 8.1. But i can't because Droidmon make me bug. I found the error.log location changed in `/data/user_de/0/de.robv.android.xposed.installer/log/error.log`. And droidmon don't write in this document and we can't open the application to test or other no system app like jackpal terminal. 
In the github of @idanr1986 a people as the same problem but no one answered (https://github.com/idanr1986/droidmon/issues/13).
 Do you have a similar issue.
How to resolv this ?

Regard,

**Comment by ajinabraham** [comment]
We do not support AVD in latest MobSF. Also Droidmon uses Xposed and we support Xposed only for Android <5. You should be using Genymotion Android VM < 5 if you need Xposed and Droidmon support. Please see the latest docs: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation

**Comment by DimitriBurve** [comment]
I use also Genymotion (in android 8.0). I tried to run a dynamic analysis on wikipedia. When I start live API monitor there was the error with id. When the activity tester has finished I generated the report but nothing appeared. I didn't install Droidmon. How to have a report for dynamic analysis for android 8.0 ?
