### ISSUE TITLE
How To Change Directory Installation

### ISSUE THREAD

**Issue by its4win** [MobSF/Mobile-Security-Framework-MobSF#1313]
Hi, 
I try to change the directory of Mobile-Security-Framework-MobSF,
From drive V: to drive P: by copying all files 
but i got this error when i run it
![image](https://user-images.githubusercontent.com/58930060/76189041-3a920880-620c-11ea-8d24-7baa79dbd68e.png)

and i try to reinstall it, but i got another error on yara-python when i build it,
![image](https://user-images.githubusercontent.com/58930060/76189123-79c05980-620c-11ea-8e98-eea9181fa517.png)

It was no problem when i run in path before i change it (drive V:)

So, 
how can i change the directory / path of MobSF?

Thanks.

FYI,
Operating System: Windows 10 Enterprise x64

**Comment by superpoussin22** [comment]
can you start from a fresh git clone note a copy ?

**Comment by its4win** [comment]
I was try many times to do that,
I clone from github and build it again,
but i got same error on yara-python as picture above

**Comment by ajinabraham** [comment]
Please use Slack channel for support
