### ISSUE TITLE
class-dump/class-dump-swift failed on this binary - MACOS

### ISSUE THREAD

**Issue by KirubakaranK17** [MobSF/Mobile-Security-Framework-MobSF#1323]
@ajinabraham Please help on this below issue, I have pulled the latest code from MOBSF master while running on .ipa file below error getting displayed. So that Malware Analysis is not getting displayed

Select an architecture setting the ARCH= environment variable

[INFO] 11/Mar/2020 08:56:04 - Running jtool against the binary for dumping classes
[ERROR] 11/Mar/2020 08:56:09 - class-dump/class-dump-swift failed on this binary
[INFO] 11/Mar/2020 08:56:09 - Running strings against the Binary

Using : MACOS

**Comment by ajinabraham** [comment]
@KirubakaranK17 Are you sure it's the latest master. We have added a fix for jtool two days back. If you are on the latest, Can you share the IPA.

Also provide all the requested information like logs, OS version, Python version etc. Please provide enough information.

**Comment by ajinabraham** [comment]
We have a possible fix for this. Will be available once this branch is merged to master.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1302

**Comment by ajinabraham** [comment]
Use latest master, v3.0.5. Please comment if you still see the issue.
