### ISSUE TITLE
Frida error during dynamic analysis : cannot read property '_o' of null.

### ISSUE THREAD

**Issue by RLee063** [MobSF/Mobile-Security-Framework-MobSF#1337]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 2.7.5
MobSF Version: v3.0 beta
Frida version: 12.8.14
```
## EXPLANATION OF THE ISSUE

When I use the dynamic analysis of Mobsf, I always got an error `cannot read property '_o' of null`, then I decided to implement an API Monitor myself. After use frida only with the script `api_monitor.js`, I found two possible problems:

### 1. hasOwnProperty('argumentTypes') always return false.
In my experiment, the condition `impl.hasOwnProperty('argumentTypes')` never met, even though I can use `impl.argumentTypes` to get the value directly. 

So `get_implementations` always return `imp_args` as `[]`.
```javascript
// DynamicAnalyzer\tools\frida_scripts\default\api_monitor.js
// line 500
// Get All Method Implementations

function get_implementations(toHook) {
    var imp_args = []
    toHook.overloads.forEach(function (impl, _) {
        if (impl.hasOwnProperty('argumentTypes')) {
            var args = [];
            var argTypes = impl.argumentTypes
            argTypes.forEach(function (arg_type, __) {
                args.push(arg_type.className)
            });
            imp_args.push(args);
        }
    });
    return imp_args;
}
```
### 2. apply(null, args) cause an error due to parameter `null`

Function `apply` replaces pointer  `this`  with `null` : 

```javascript
// DynamicAnalyzer\tools\frida_scripts\default\api_monitor.js
// line 535
toHook.overload.apply(null, args).implementation = function () {
    // ...
};
```
While `overload` is defined as:
```javascript
// frida-java-bridge\lib\class-factory.js
// line 1213
  overload: {
    value (...args) {
      const overloads = this._o;
      const numArgs = args.length;
      const signature = args.join(':');
      //...
```
So `this._o` will cause `TypeError: cannot read property '_o' of null`

**Comment by RLee063** [comment]
After fixing these two problems, my `API monitor` works.

**Comment by ajinabraham** [comment]
@RLee063 Thanks for digging deep. This is caused by some changes in frida introduced recently. 

How did you manage to fix the issue corresponding to `toHook.overload.apply(null, args).implementation = function () {` ? Changing `null` to `this` doesn't seems to help.

**Comment by ajinabraham** [comment]
Fixed this by looping overloads
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1336/commits/23c6eac7d98587bea88460d5cb50095bbc52d5a1#diff-90e713ef0671772b2f8de24ed324f0faR533-R535

**Comment by RLee063** [comment]
> @RLee063 Thanks for digging deep. This is caused by some changes in frida introduced recently.
> 
> How did you manage to fix the issue corresponding to
> `toHook.overload.apply(null, args).implementation = function () {` ?
> 
> Changing `null` to `this` doesn't seems to help.

Sorry for the late reply, I see you've solved this problem. I fixed it by changing `null` to `toHook` : )
