### ISSUE TITLE
Change Frida Server binary to latest 12.8.20 in code

### ISSUE THREAD

**Issue by surajpkhetani** [MobSF/Mobile-Security-Framework-MobSF#1346]
When MobSFYing during dynamic analysis, the frida binary that is called is an older version (12.8.19) that does not exist in the /DynamicAnalyzer/tools/onDevice/frida directory.
Kindly change the frida binary to 12.8.20 in the code.

**Comment by ajinabraham** [comment]
Thanks for pointing this out.

**Comment by ajinabraham** [comment]
Fixed!
