### ISSUE TITLE
PATH - venv/bin/activate Error Installation - URGENT

### ISSUE THREAD

**Issue by ims1337** [MobSF/Mobile-Security-Framework-MobSF#1347]
I am in mid of a test. During installation i run 

sudo ./setup.sh it download all required but at end it shown up this 

> ````Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.  `

What does it mean? as i am unable to run it, upon running it says 

```
> 
> root@kali:~/Desktop/Mobile-Security-Framework-MobSF-master# ./run.sh
> ./run.sh: line 5: venv/bin/activate: No such file or directory
> 
> 
```
Main Error

> Installing collected packages: asgiref, Django, pdfkit, lxml, asn1crypto, networkx, androguard, rsa, biplist, requests, bs4, colorlog, altgraph, macholib, google-play-scraper, whitenoise, waitress, gunicorn, frida, psutil, shelljob, oscrypto, distro, IP2Location, yara-python, argparse, apkid, pycparser, cffi, cryptography, zstandard, publicsuffix2, ldap3, ruamel.yaml.clib, ruamel.yaml, wsproto, mitmproxy, http-tools
>   WARNING: The script django-admin is installed in '/root/.local/bin' which is not on PATH.                                                           
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The script androguard is installed in '/root/.local/bin' which is not on PATH.                                                             
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/root/.local/bin' which is not on PATH.                                                         
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The scripts macho_dump, macho_find and macho_standalone are installed in '/root/.local/bin' which is not on PATH.                          
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The script waitress-serve is installed in '/root/.local/bin' which is not on PATH.                                                         
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The script gunicorn is installed in '/root/.local/bin' which is not on PATH.                                                               
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The script distro is installed in '/root/.local/bin' which is not on PATH.                                                                 
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The script apkid is installed in '/root/.local/bin' which is not on PATH.                                                                  
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The scripts mitmdump, mitmproxy, mitmweb, pathoc and pathod are installed in '/root/.local/bin' which is not on PATH.                      
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
>   WARNING: The script httptools is installed in '/root/.local/bin' which is not on PATH.                                                              
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                   
> Successfully installed Django-3.0.5 IP2Location-8.4.1 altgraph-0.17 androguard-3.3.5 apkid-2.1.0 argparse-1.4.0 asgiref-3.2.7 asn1crypto-1.3.0 biplist-1.0.3 bs4-0.0.1 cffi-1.14.0 colorlog-4.1.0 cryptography-2.4.2 distro-1.5.0 frida-12.8.20 google-play-scraper-0.0.2.2 gunicorn-20.0.4 http-tools-1.1.0 ldap3-2.6.1 lxml-4.5.0 macholib-1.14 mitmproxy-5.0.1 networkx-2.4 oscrypto-1.1.0 pdfkit-0.6.1 psutil-5.7.0 publicsuffix2-2.20191221 pycparser-2.20 requests-2.23.0 rsa-4.0 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 shelljob-0.5.6 waitress-1.4.3 whitenoise-5.0.1 wsproto-0.14.1 yara-python-3.11.0 zstandard-0.12.0
> 
```

**Comment by ims1337** [comment]
Here it get stuck at gunicorn even installed it manually again and it shows it already installed. Please help out @ajinabraham 

root@kali:~/Desktop/Mobile-Security-Framework-MobSF-master# sudo ./run.sh
./run.sh: line 5: gunicorn: command not found

root@kali:~/Desktop/Mobile-Security-Framework-MobSF-master# cat run.sh
#!/bin/bash
# Dev Server
#. venv/bin/activate && python manage.py runserver
# Prod Server
. venv/bin/activate && gunicorn -b 0.0.0.0:8000 MobSF.wsgi:application --workers=1 --threads=10 --timeout=1800

**Comment by ims1337** [comment]
> Here it get stuck at gunicorn even installed it manually again and it shows it already installed. Please help out @ajinabraham
> 
> root@kali:~/Desktop/Mobile-Security-Framework-MobSF-master# sudo ./run.sh
> ./run.sh: line 5: gunicorn: command not found
> 
> root@kali:~/Desktop/Mobile-Security-Framework-MobSF-master# cat run.sh
> #!/bin/bash
> # Dev Server
> 
> #. venv/bin/activate && python manage.py runserver
> # Prod Server
> 
> . venv/bin/activate && gunicorn -b 0.0.0.0:8000 MobSF.wsgi:application --workers=1 --threads=10 --timeout=1800

Here i got a solution, as we into python3 and requirement install normal guncorn so we need python3 one.

> `sudo apt install gunicorn3`

Let me know if anyone stucked

**Comment by ajinabraham** [comment]
Incomplete setup. `sudo` in not used to fix issues. Use slack channel for discussions

**Comment by DustinTheGreat** [comment]
Was this actually resolved?

**Comment by ims1337** [comment]
no but it was solved through slack channel. please go there and share error
log plus screenshot they are very active there and help
