### ISSUE TITLE
[Feature] Add "Submit" button in VirusTotal section

### ISSUE THREAD

**Issue by baharkhalid** [MobSF/Mobile-Security-Framework-MobSF#1349]
Our investigation on mobile app sometime dealing with application in development and we have to disable auto submit to VirusTotal. But sometime deal with malware or app store application which is available publicly. Adding "Submit" button in VirusTotal section will be helpful if we need to submit the application to VirusTotal manually. Thank you.

**Comment by ajinabraham** [comment]
Low Priority
Tracked Separately
