### ISSUE TITLE
[FEATURE] Continue analysis on APKiD failiure

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#1351]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Lot of people does not know how to follow the docs and install requirements

**Describe the solution you'd like**
When APKiD fails do bail and continue analysis

**Additional context**
People cannot follow documentation :-/

**Comment by aph3rson** [comment]
Related: #1335

For what it's worth, we definitely can follow instructions. The issues installing the customized version of `yara-python` are buried install the initial run of `setup.bat`. There's no catch process for if this process fails - it's not often that users are expected to build their own wheel, so many might not have the environment needed to do so.

In this particular case (and, I suspect #1335's reporter), it's a broken install of the C++ build tools - but, again, the error isn't immediately apparent, and the install script doesn't fail-fast if the build process fails.

**Comment by ajinabraham** [comment]
Well, there are about 49 invalid issues related to this https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues?q=is%3Aissue+internal+error%3A+34+is%3Aclosed

The requirements section in docs(https://mobsf.github.io/docs/#/requirements)  clearly mentions to install the requirements for each operating systems before running setup.

But you are right about the setup script that it needs to fail fast rather than proceeding with the rest of the instructions. The exceptions can go unnoticed.

**Comment by ajinabraham** [comment]
Fail fast is implemented. https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/setup.bat#L41-L54
