### ISSUE TITLE
Scan not executed properly/incomplete when triggered via REST API

### ISSUE THREAD

**Issue by klmmr** [MobSF/Mobile-Security-Framework-MobSF#1355]
## ENVIRONMENT

```
OS and Python: from prebuild Docker Image (133f25036b647b27bd2e3301bf28fc56d5b15f0d62abaa7ee0ea5250089ff7da)
MobSF Version: v3.0.7 Beta
```

## EXPLANATION OF THE ISSUE

**TL;DR:** It seems that the REST API does not allow to perform a proper static analysis of an app (APK in my case) or at least it is incomplete. Complete scan is only performed via the browser.

_Wrong behavior:_
I can upload and scan the APK using the REST API but after that I cannot retrieve a JSON/PDF report (`"report": "Report not Found"`) via the API. However, accessing MobSF with my browser I see in "Recent Scans" that the scan is not completed. When I click on "Static Report" (in my browser) it seems that the scan is now executed properly/complete and all results are shown after analysis finished. Now I can get the results as JSON/PDF via the REST API as I expected

_Expected behavior:_
After upload and scan via REST API the scan should be completed and I can retrieve the report as JSON/PDF (also via REST API).

## STEPS TO REPRODUCE THE ISSUE

1. Upload APK using `api/v1/upload`. (This is successful, returning Status 200. And APK shows up in the list of recent scans as not completed.)
2.  Then I request to scan the APK via REST-API `api/v1/scan`. (The app is still shown as "scan not completed" in the list of recent scans in browser, but now with its icon. The scan is also listed in `api/v1/scan`.)
3. I try to request a report as JSON or PDF via `api/v1/report_json` or `api/v1/download_pdf`. But I get `{"report": "Report not Found"}` back from the API.
4. After that I go with my browser to the site with the Static Analysis report. This seems to cause another scan. After some time I get the results and in the list of recent scans the "scan not completed" badge is gone.
5. When trying again to get JSON or PDF report (as in step 3) everything works fine. I get the report as JSON and PDF.

## LOG FILE

```
[INFO] 14/Apr/2020 13:20:04 - MIME Type: application/octet-stream FILE: 1491928811_com.starfinanz.smob.android.sfinanzstatus_41206_04-11-2017.apk
[INFO] 14/Apr/2020 13:20:04 - Performing Static Analysis of Android APK
[INFO] 14/Apr/2020 13:21:49 - Starting Analysis on : 1491928811_com.starfinanz.smob.android.sfinanzstatus_41206_04-11-2017.apk
[INFO] 14/Apr/2020 13:21:49 - Generating Hashes
[INFO] 14/Apr/2020 13:21:49 - Unzipping
[INFO] 14/Apr/2020 13:21:50 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Apr/2020 13:21:50 - APK Extracted
[INFO] 14/Apr/2020 13:21:50 - Converting AXML to XML
[INFO] 14/Apr/2020 13:21:56 - Reading Android Manifest
[INFO] 14/Apr/2020 13:21:56 - Parsing AndroidManifest.xml
[INFO] 14/Apr/2020 13:21:58 - Fetching icon path
[INFO] 14/Apr/2020 13:22:01 - Extracting Manifest Data
[INFO] 14/Apr/2020 13:22:01 - Fetching Details from Play Store: com.starfinanz.smob.android.sfinanzstatus
[INFO] 14/Apr/2020 13:22:01 - Manifest Analysis Started
[INFO] 14/Apr/2020 13:22:01 - Static Android Binary Analysis Started
[INFO] 14/Apr/2020 13:22:01 - Static Android Resource Analysis Started
[INFO] 14/Apr/2020 13:22:01 - Reading Code Signing Certificate
[INFO] 14/Apr/2020 13:22:01 - Running APKiD 2.1.0
[INFO] 14/Apr/2020 13:22:05 - Updating Trackers Database....
[INFO] 14/Apr/2020 13:22:05 - Detecting Trackers
[INFO] 14/Apr/2020 13:22:07 - APK -> JAVA
[INFO] 14/Apr/2020 13:22:07 - Decompiling to Java with jadx
[INFO] 14/Apr/2020 13:22:27 - DEX -> SMALI
[INFO] 14/Apr/2020 13:22:27 - Converting classes.dex to Smali Code
[INFO] 14/Apr/2020 13:22:27 - Converting classes2.dex to Smali Code
[INFO] 14/Apr/2020 13:22:27 - Static Android Code Analysis Started
[INFO] 14/Apr/2020 13:22:27 - Code Analysis Started on - java_source
[INFO] 14/Apr/2020 13:22:40 - Finished Code Analysis, Email and URL Extraction
[INFO] 14/Apr/2020 13:22:40 - Extracting Strings from APK
[INFO] 14/Apr/2020 13:22:43 - Detecting Firebase URL(s)
[INFO] 14/Apr/2020 13:22:43 - Performing Malware Check on extracted Domains
[INFO] 14/Apr/2020 13:22:44 - Updating Malware Database....
[INFO] 14/Apr/2020 13:22:46 - Connecting to Database
[WARNING] 14/Apr/2020 13:28:06 - Not Found: /api/v1/download_pdf
[INFO] 14/Apr/2020 13:31:36 - Starting Analysis on : 1491928811_com.starfinanz.smob.android.sfinanzstatus_41206_04-11-2017.apk
[INFO] 14/Apr/2020 13:31:36 - Generating Hashes
[INFO] 14/Apr/2020 13:31:36 - Unzipping
[INFO] 14/Apr/2020 13:31:37 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Apr/2020 13:31:37 - APK Extracted
[INFO] 14/Apr/2020 13:31:37 - Reading Android Manifest
[INFO] 14/Apr/2020 13:31:37 - Parsing AndroidManifest.xml
[INFO] 14/Apr/2020 13:31:39 - Fetching icon path
[INFO] 14/Apr/2020 13:31:41 - Extracting Manifest Data
[INFO] 14/Apr/2020 13:31:41 - Fetching Details from Play Store: com.starfinanz.smob.android.sfinanzstatus
[INFO] 14/Apr/2020 13:31:41 - Manifest Analysis Started
[INFO] 14/Apr/2020 13:31:41 - Static Android Binary Analysis Started
[INFO] 14/Apr/2020 13:31:41 - Static Android Resource Analysis Started
[INFO] 14/Apr/2020 13:31:41 - Reading Code Signing Certificate
[INFO] 14/Apr/2020 13:31:41 - Running APKiD 2.1.0
[INFO] 14/Apr/2020 13:31:44 - Trackers Database is up-to-date
[INFO] 14/Apr/2020 13:31:44 - Detecting Trackers
[INFO] 14/Apr/2020 13:31:46 - APK -> JAVA
[INFO] 14/Apr/2020 13:31:46 - Decompiling to Java with jadx
[INFO] 14/Apr/2020 13:32:05 - DEX -> SMALI
[INFO] 14/Apr/2020 13:32:05 - Converting classes.dex to Smali Code
[INFO] 14/Apr/2020 13:32:05 - Converting classes2.dex to Smali Code
[INFO] 14/Apr/2020 13:32:05 - Static Android Code Analysis Started
[INFO] 14/Apr/2020 13:32:05 - Code Analysis Started on - java_source
[INFO] 14/Apr/2020 13:32:19 - Finished Code Analysis, Email and URL Extraction
[INFO] 14/Apr/2020 13:32:19 - Extracting Strings from APK
[INFO] 14/Apr/2020 13:32:21 - Detecting Firebase URL(s)
[INFO] 14/Apr/2020 13:32:21 - Performing Malware Check on extracted Domains
[INFO] 14/Apr/2020 13:32:22 - Malware Database is up-to-date
[INFO] 14/Apr/2020 13:32:23 - Connecting to Database
[INFO] 14/Apr/2020 13:32:23 - Saving to Database
[INFO] 14/Apr/2020 13:33:27 - Fetching data from DB for PDF Report Generation (Android)
[INFO] 14/Apr/2020 13:33:27 - Analysis is already Done. Fetching data from the DB...
[INFO] 14/Apr/2020 13:33:27 - Generating PDF report for android apk
```

**Comment by ajinabraham** [comment]
May be your API calls are incorrect or you are requesting PDF before the scan is completed? Works fine for me. This is not a bug, please move the conversation to our slack channel.

```
curl -F 'file=@/Users/xxx/diva-beta.apk' http://localhost:8000/api/v1/upload -H "Authorization:xxx"

{"scan_type": "apk", "hash": "82ab8b2193b3cfb1c737e3a786be363a", "file_name": "diva-beta.apk"}

curl -X POST --url http://localhost:8000/api/v1/scan --data "scan_type=apk&file_name=diva-beta.apk&hash=82ab8b2193b3cfb1c737e3a786be363a" -H "Authorization:xxx"

...."playstore_details": {"error": true}, "average_cvss": 6.1, "security_score": 55, "dynamic_analysis_done": false, "virus_total": null

curl -X POST --url http://localhost:8000/api/v1/download_pdf --data "hash=82ab8b2193b3cfb1c737e3a786be363a" -H "Authorization:xxx" > x.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 83395    0 83358  100    37  22923     10  0:00:03  0:00:03 --:--:-- 22919

**Comment by AnixPasBesoin** [comment]
@klmmr I am having the exact same issue. Did you manage to figure it out?

**Comment by flubshi** [comment]
The same happend for me :(

**Comment by AnixPasBesoin** [comment]
@flubshi if you're looking for a quick and dirty solution (hack), you can use this (basically wrapping a curl sys call):

        template = 'curl --silent -X POST --url {url} --data "scan_type={scan_type}&file_name={apk_filename}&hash={hash}" -H "Authorization:{api_key}"'
        curl_scan = template.format(
            url=f'{self.__server}/api/v1/scan',
            scan_type=scantype,
            apk_filename=filename,
            hash=scanhash,
            api_key=self.__apikey,
        )
        output = subprocess.getoutput(curl_scan)
        resp = json.loads(output)

**Comment by flubshi** [comment]
Thanks @AnixPasBesoin ! Usually, I use https://github.com/klmmr/mobsfpy for interacting with MobSF. Your workaround is working for me. 

What is the difference? The `requests` implementation looks similar to me. :thinking:

**Comment by AnixPasBesoin** [comment]
@flubshi I didn't really dig deeper, but I'd say (on the top of my head) this could be due to the implementation of python's `requests` library. You could replace it with some other alternative web clients (`urllib2`, `httplib`) and check my hypothesis. Best luck!
