### ISSUE TITLE
[FEATURE] Specify versions of data sets used

### ISSUE THREAD

**Issue by mkshr31** [MobSF/Mobile-Security-Framework-MobSF#1357]
Some analysis results are time-dependent; specifically, reported ratings may change with each scan. This applies at least to:

1. all app metadata retrieved from AppStores
2. the certificate status of the signer certificate (Android)
3. domain malware checks (IP address, IP geolocation, status)
4. VirusTotal results

In order to make test results verifiable and possible differences between two scans comprehensible, a consistent versioning if the data sets used is necessary.

Currently, only the scan date is specified when using the VirusTotal API.

I suggest to add the following information to JSON Report API:
* time at which an analysis started
* time at which an analysis was completed (since not all analysis steps are executed in the very beginning and all at once)
* the version string (if available) and the time at which a data set was successfully updated the last time (for example, the Malware Analysis or IP Geolocation data sets may be cached)

**Comment by ajinabraham** [comment]
Tracked Separately
