### ISSUE TITLE
[FEATURE] Update search expressions that are used to match Android APIs

### ISSUE THREAD

**Issue by mkshr31** [MobSF/Mobile-Security-Framework-MobSF#1361]
According to the official Android developer reference, some of the search expressions that are used to match APIs are out of date. These should be updated.
On the other hand, there are accesses to sensitive data, which are currently not taken into account. Suitable search expressions should be added for this.

**Examples:**
* the test for potential access of Device ID, IMEI, MEID/ESN, etc. is currently done by `'match': ['telephony.TelephonyManager', 'getDeviceId']`; however, `getDeviceId` is deprecated since API Level 26 and should be supplemented by `getImei` and `getMeid` (for compatibility) - cf. https://developer.android.com/reference/android/telephony/TelephonyManager#getDeviceId()
* data such as
  - telephone number,
  - WLAN SSID, 
  - local IP address,
  - MAC addresses,
  - list of installed apps,
  - Android Advertising ID,
  - etc.

  are worth protecting. A potential access by using the API functions, should be reported

**Comment by ajinabraham** [comment]
addressed in 3.0.9
