### ISSUE TITLE
[FEATURE] Koodous API integration for vote and upload

### ISSUE THREAD

**Issue by cepok** [MobSF/Mobile-Security-Framework-MobSF#1367]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

Koodous API function (upload, vote)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like my samples to be checked in Koodous. if they don't exist, they should be uploaded.
I would like to be able to vote in Koodous from MobSF

**Describe alternatives you've considered**
Manually or my python scripts

**Additional context**
When I analyze sample on MobSF, later i vote and comment this app on Koodous with my analysis verdict.
Sometimes my samples not exist on Koodous and I mus upload this manually. 
I suggest that the samples upload through the API, just like in the case of VirusTotal API

**Comment by superpoussin22** [comment]
@cepok feel free to submit a PR

**Comment by ajinabraham** [comment]
Tracked Separately
