### ISSUE TITLE
Can not generate json and pdf report for android (apk)

### ISSUE THREAD

**Issue by nongpoo** [MobSF/Mobile-Security-Framework-MobSF#1368]
Hi all,

I build android app with gradle 3.6.2 then upload to MobSF then I try to generate json and pdf report
but MobSF have error log like i attached. And when I build the same app with gradle 3.5.3, it is working.
Please  suggest me.
Thank you.

[logforgradle_3.6.2.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4513722/logforgradle_3.6.2.txt)

**Comment by ajinabraham** [comment]
This is not an error log.

**Comment by nongpoo** [comment]
Sorry I already updated.

**Comment by ajinabraham** [comment]
This looks like a bug that we have fixed. A new android build format breaks certificate parser. But we handle this in latest version of MobSF. please update to latest master.

**Comment by nongpoo** [comment]
Fixed bug is included in latest version of MobSF docker or not ?

**Comment by ajinabraham** [comment]
Yes the docker image is always the latest master. You can pull the docker image to get latest.

**Comment by nongpoo** [comment]
Ok Thank you  i will try

**Comment by nongpoo** [comment]
Thank you @ajinabraham  i can fix my problem
