### ISSUE TITLE
[FEATURE] Integrate something similar to pidcat to see the logs during Dynamic analysis

### ISSUE THREAD

**Issue by carlospolop** [MobSF/Mobile-Security-Framework-MobSF#1376]
First of all, thank you for this tool, it's just amazing.
Also, thank you for the certifications, they were really helpful.

I was playing with dynamic analysis, and I just realised how amazing it was. 
However, when I saw the logs I was a little bit disappointed. MobSF if showing all the logs of the device and that makes very difficult to search the logs that you really care about when analysing an application: The logs of the application.
Indeed, I wasn't even able to find any log of the application (and I know it's logging things).
Therefore, I would like to suggest you some improvements for the log view:
- Maybe you could add some kind of grep to just show the logs being created by the analysed application
- Maybe you could somehow integrate [pidcat](https://github.com/JakeWharton/pidcat) to see the logs of the application and the colors (which are very helpful)

Please, let me know if any of this features already exist and I don't know about it.

**Comment by ajinabraham** [comment]
Tracked separately
