### ISSUE TITLE
[FEATURE] Add App Compare method to REST API

### ISSUE THREAD

**Issue by benbadio** [MobSF/Mobile-Security-Framework-MobSF#1378]
Add a REST API method to output an app comparison report in JSON given two app hashes. The generic_compare() method in comparer.py is already set up to be used for this purpose, but there is no REST API method that uses it.

**Comment by ajinabraham** [comment]
@matandobr a good feature to consider once we improve diffing and add support for iOS diffing.

**Comment by ajinabraham** [comment]
Added in 3.1.1
