### ISSUE TITLE
Path with $ causing issues in Windows

### ISSUE THREAD

**Issue by CristiVlad25** [MobSF/Mobile-Security-Framework-MobSF#1397]
I'm using the latest mobsf and the app is olx.ro (ro.mercador)

In browser:

"Error
Inappropriate argument type.

'NoneType' object is not subscriptable"

In CMD:

"[INFO] 20/May/2020 10:28:03 - Decompiling to Java with jadx
[ERROR] 20/May/2020 10:28:05 - Decompiling to JAVA
Traceback (most recent call last):
  File "E:\androidpen\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\converter.py", line 70, in apk_2_java
    shutil.rmtree(output)
  File "C:\Python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 3 more times]
  File "C:\Python37\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\androidpen\\Mobile-Security-Framework-MobSF\\uploads/0660e0a18625fbf6a054a2b319820d8f/java_source/com\\olxgroup\\olx\\monetization\\data\\entity\\PricingListResponse$PricingResponse$ProvidersResponse$ProviderResponse$ProviderPricingResponse$BundleResponse$$serializer.java'
[INFO] 20/May/2020 10:28:05 - DEX -> SMALI
[INFO] 20/May/2020 10:28:05 - Converting classes.dex to Smali Code
[INFO] 20/May/2020 10:28:05 - Converting classes2.dex to Smali Code
[INFO] 20/May/2020 10:28:05 - Converting classes3.dex to Smali Code
[INFO] 20/May/2020 10:28:05 - Converting classes4.dex to Smali Code
[INFO] 20/May/2020 10:28:05 - Static Android Code Analysis Started
[INFO] 20/May/2020 10:28:05 - Code Analysis Started on - java_source
[ERROR] 20/May/2020 10:28:05 - Performing Code Analysis
Traceback (most recent call last):
  File "E:\androidpen\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\code_analysis.py", line 75, in code_analysis
    errors='ignore',
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\androidpen\\Mobile-Security-Framework-MobSF\\uploads/0660e0a18625fbf6a054a2b319820d8f/java_source/com\\olxgroup\\olx\\monetization\\data\\entity\\PricingListResponse$PricingResponse$ProvidersResponse$ProviderResponse$ProviderPricingResponse$BundleResponse$$serializer.java'
[INFO] 20/May/2020 10:28:05 - Extracting Strings from APK
Picked up _JAVA_OPTIONS: -Xms512m -Xmx3000m
Picked up _JAVA_OPTIONS: -Xms512m -Xmx3000m
Picked up _JAVA_OPTIONS: -Xms512m -Xmx3000m
Picked up _JAVA_OPTIONS: -Xms512m -Xmx3000m
[ERROR] 20/May/2020 10:28:09 - Error Performing Static Analysis
Traceback (most recent call last):
  File "E:\androidpen\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 205, in static_analyzer
    code_an_dic['urls_list'].extend(
TypeError: 'NoneType' object is not subscriptable
[ERROR] 20/May/2020 10:28:09 - 'NoneType' object is not subscriptable
[ERROR] 20/May/2020 10:28:09 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/"

**Comment by ajinabraham** [comment]
This is mostly a path problem in windows. `E:\androidpen\Mobile-Security-Framework-MobSF\uploads/0660e0a18625fbf6a054a2b319820d8f/java_source/com\olxgroup\olx\monetization\data\entity\PricingListResponse$PricingResponse$ProvidersResponse$ProviderResponse$ProviderPricingResponse$BundleResponse$$serializer.java`

Paths with `$` might cause issue in windows.

You might want to use a Linux host OS or docker for scanning the APK. Can you share the exact APK?

**Comment by CristiVlad25** [comment]
Yes, here it is. 
[ro.mercador.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4658829/ro.mercador.zip)

**Comment by ajinabraham** [comment]
Works fine for me on Mac.
[download.pdf](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4664584/download.pdf)

I don't think we can do anything about this on Windows. These paths are invalid in Windows. 
For binaries with special path, you might want to use dockerized version of MobSF on windows.

**Comment by ajinabraham** [comment]
I will test this on windows and see if something can be done about this.

**Comment by ajinabraham** [comment]
This is fixed with internal replacement using pathlib on Windows. The fix is available on #1486
