### ISSUE TITLE
'waitress-serve' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nyxs** [MobSF/Mobile-Security-Framework-MobSF#1398]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version:  3.7.3
MobSF Version:  v3.0.9 Beta
```

## EXPLANATION OF THE ISSUE

After finishing installing MobSF, I tried to run the run.bat file, and I got this error:
```
'waitress-serve' is not recognized as an internal or external command,
operable program or batch file.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Finish installing MobSF
2. Run the run.bat file
```

## LOG FILE

```
No log file
```

**Comment by superpoussin22** [comment]
did you run setup.bat  1st ?

please use slack channel  to dicuss

**Comment by nyxs** [comment]
@superpoussin22 yeah, I finished installing first, using the setup.bat and then run.bat

**Comment by ajinabraham** [comment]
This sounds like incomplete or failed setup. Please move the conversation to slack channel.

**Comment by mrsh3z4n** [comment]
Me also facing this issue.....
waitress-serve' is not recognized as an internal or external command, operable program or batch file.

how to fix it

**Comment by serrovsky** [comment]
I'm having the same problem guys. Using Windows 10 and Python 3.9, Any update @ajinabraham

**Comment by serrovsky** [comment]
@mrsh3z4n I found the problem. Check the script run.bat. The last command is trying to run waitress-serve, but it's not defined in your path. Define it or you can change run.bat script, to something like this:

`.\venv\Scripts\activate && C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\waitress-serve --listen=%conf% --threads=10 --channel-timeout=3600 mobsf.MobSF.wsgi:application
`

**Comment by alexander474** [comment]
@serrovsky I does not seem to work for me

**Comment by mrsh3z4n** [comment]
@serrovsky here me can't understand....can u tell me it in brief,, how actually fix it🙄

**Comment by abidlf** [comment]
> @mrsh3z4n I found the problem. Check the script run.bat. The last command is trying to run waitress-serve, but it's not defined in your path. Define it or you can change run.bat script, to something like this:
> 
> `.\venv\Scripts\activate && C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\waitress-serve --listen=%conf% --threads=10 --channel-timeout=3600 mobsf.MobSF.wsgi:application `

I've changed it, but it appears like this `The system cannot find the path specified` . I checked `C:\Users\USERNAME\AppData\Local\Packages\` there is no `PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\waitress-serve`. I'm using Python 3.9.4

**Comment by ajinabraham** [comment]
Try pulling the latest master and run setup again.  The above instructions will not work as the packages are installed inside virtual environment and not your local python install location. For support, please join MobSF slack channel. Github issues are for bugs and feature requests only.
