### ISSUE TITLE
Insecure Default Bind to 0.0.0.0

### ISSUE THREAD

**Issue by ThunderSon** [MobSF/Mobile-Security-Framework-MobSF#1400]
After analyzing the idea behind why `0.0.0.0` is being used, I still didn't understand why a person that didn't read the docs closely will have to expose their MobSF to the world because it's an insecure default.

Yes, if they're running a container, that could be a case. That's the only case.

If someone is running it on a server, the application should still be secure and make the admin update it.
I know I can update it in the configuration file, I am just asking for the `default insecure` option on a security tool.

**Comment by ajinabraham** [comment]
Fare enough, will change to localhost on run scripts.
