### ISSUE TITLE
MobSF not loading correctly in windows 10

### ISSUE THREAD

**Issue by aktjkt** [MobSF/Mobile-Security-Framework-MobSF#1407]
## ENVIRONMENT

```
OS and Version: windows 10
Python Version: 3.8.2 
MobSF Version: 3.0
```

## EXPLANATION OF THE ISSUE

when I Run the following command -- **python manage.py runserver**
its not loading correctly I am attaching the screen short for the reference 
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```
<!-- If you see errors while running setup/run scripts, join MobSF Slack channel: http://tiny.cc/mobsf to get limited support. -->

## STEPS TO REPRODUCE THE ISSUE


```
1. Run : python manage.py runserver it showing it started running on 127.0.0.1:8000 when I open the same thing in the browser its not loading properly 
![mobsf](https://user-images.githubusercontent.com/19797443/82757460-400bf180-9dfe-11ea-9ed0-d8e9d710468d.PNG)
[debug.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4673791/debug.log)

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
1) Python 3.8 is not supported
2) you did not launch MobSF corectly 

Please read the doc :)
