### ISSUE TITLE
Getting [WARNING] 404 for reading static files, NOT WORKING

### ISSUE THREAD

**Issue by gptshubham595** [MobSF/Mobile-Security-Framework-MobSF#1408]
I did this:
ran setup.bat

Now ran python manage.py runserver 
Got this WARNING

![image](https://user-images.githubusercontent.com/24877361/82949152-b8baab80-9fc0-11ea-93a0-01be9a14e026.png)

**Comment by ajinabraham** [comment]
Run `run.bat` after setup. Please follow official docs: https://mobsf.github.io/docs/#/
