### ISSUE TITLE
Installing http_tools module error

### ISSUE THREAD

**Issue by iii235** [MobSF/Mobile-Security-Framework-MobSF#1410]
When I try to install http_tools on kali linux, this is the error log I get:
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpfqpxdvn4 build_wheel /tmp/tmpbkux2c3m   
       cwd: /tmp/pip-install-hiwxdevo/cryptography                           
  Complete output (137 lines):                                               
  running bdist_wheel                                                        
  running build                                                              
  running build_py                                                           
  creating build                                                             
  creating build/lib.linux-i686-3.8                                          
  creating build/lib.linux-i686-3.8/cryptography                             
  copying src/cryptography/__about__.py -> build/lib.linux-i686-3.8/cryptography                                                                          
  copying src/cryptography/fernet.py -> build/lib.linux-i686-3.8/cryptography
  copying src/cryptography/exceptions.py -> build/lib.linux-i686-3.8/cryptography                                                                         
  copying src/cryptography/utils.py -> build/lib.linux-i686-3.8/cryptography 
  copying src/cryptography/__init__.py -> build/lib.linux-i686-3.8/cryptography                                                                           
  creating build/lib.linux-i686-3.8/cryptography/x509                        
  copying src/cryptography/x509/extensions.py -> build/lib.linux-i686-3.8/cryptography/x509                                                               
  copying src/cryptography/x509/name.py -> build/lib.linux-i686-3.8/cryptography/x509                                                                     
  copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-i686-3.8/cryptography/x509                                                 
  copying src/cryptography/x509/base.py -> build/lib.linux-i686-3.8/cryptography/x509                                                                     
  copying src/cryptography/x509/ocsp.py -> build/lib.linux-i686-3.8/cryptography/x509                                                                     
  copying src/cryptography/x509/__init__.py -> build/lib.linux-i686-3.8/cryptography/x509                                                                 
  copying src/cryptography/x509/general_name.py -> build/lib.linux-i686-3.8/cryptography/x509                                                             
  copying src/cryptography/x509/oid.py -> build/lib.linux-i686-3.8/cryptography/x509                                                                      
  creating build/lib.linux-i686-3.8/cryptography/hazmat                      
  copying src/cryptography/hazmat/_der.py -> build/lib.linux-i686-3.8/cryptography/hazmat                                                                 
  copying src/cryptography/hazmat/_oid.py -> build/lib.linux-i686-3.8/cryptography/hazmat                                                                 
  copying src/cryptography/hazmat/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat                                                             
  creating build/lib.linux-i686-3.8/cryptography/hazmat/backends             
  copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends                                         
  copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends                                           
  creating build/lib.linux-i686-3.8/cryptography/hazmat/bindings             
  copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/bindings                                           
  creating build/lib.linux-i686-3.8/cryptography/hazmat/primitives           
  copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                  
  copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                        
  copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                         
  copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                           
  copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                       
  copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                        
  copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                       
  copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives                                           
  creating build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl     
  copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                        
  copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                                 
  copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                            
  copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                               
  copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                              
  copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                             
  copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                                
  copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                               
  copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                        
  copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                                 
  copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                             
  copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                                
  copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                              
  copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                               
  copying src/cryptography/hazmat/backends/openssl/ocsp.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                               
  copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                           
  copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                           
  copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                            
  copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                               
  copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                            
  copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-i686-3.8/cryptography/hazmat/backends/openssl                               
  creating build/lib.linux-i686-3.8/cryptography/hazmat/bindings/openssl     
  copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-i686-3.8/cryptography/hazmat/bindings/openssl                       
  copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/bindings/openssl                           
  copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-i686-3.8/cryptography/hazmat/bindings/openssl                            
  creating build/lib.linux-i686-3.8/cryptography/hazmat/primitives/serialization                                                                          
  copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/serialization                
  copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/serialization               
  copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/serialization           
  copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/serialization             
  creating build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                       
  copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                     
  copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                    
  copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                   
  copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                      
  copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                       
  copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                  
  copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                      
  copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                    
  copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                 
  copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/asymmetric                  
  creating build/lib.linux-i686-3.8/cryptography/hazmat/primitives/ciphers   
  copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/ciphers                     
  copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/ciphers                           
  copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/ciphers                           
  copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/ciphers                       
  copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/ciphers                          
  creating build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf       
  copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                              
  copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                                  
  copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                                   
  copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                               
  copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                                 
  copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                                 
  copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/kdf                                
  creating build/lib.linux-i686-3.8/cryptography/hazmat/primitives/twofactor 
  copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/twofactor                      
  copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/twofactor                       
  copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/twofactor                   
  copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-i686-3.8/cryptography/hazmat/primitives/twofactor                       
  running egg_info                                                           
  writing src/cryptography.egg-info/PKG-INFO                                 
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt 
  writing requirements to src/cryptography.egg-info/requires.txt             
  writing top-level names to src/cryptography.egg-info/top_level.txt         
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'              
  reading manifest template 'MANIFEST.in'                                    
  no previously-included directories found matching 'docs/_build'            
  warning: no previously-included files found matching 'vectors'             
  warning: no previously-included files matching '*' found under directory 'vectors'                                                                      
  warning: no previously-included files found matching 'azure-pipelines.yml' 
  warning: no previously-included files found matching '.azure-pipelines'    
  warning: no previously-included files found matching '.travis.yml'         
  warning: no previously-included files found matching '.travis'             
  warning: no previously-included files matching '*' found under directory '.azure-pipelines'                                                             
  warning: no previously-included files matching '*' found under directory '.travis'                                                                      
  warning: no previously-included files found matching 'release.py'          
  warning: no previously-included files found matching '.coveragerc'         
  warning: no previously-included files found matching 'codecov.yml'         
  warning: no previously-included files found matching 'dev-requirements.txt'
  warning: no previously-included files found matching 'rtd-requirements.txt'
  warning: no previously-included files found matching 'tox.ini'             
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'              
  running build_ext                                                          
  generating cffi module 'build/temp.linux-i686-3.8/_padding.c'              
  creating build/temp.linux-i686-3.8                                         
  generating cffi module 'build/temp.linux-i686-3.8/_constant_time.c'        
  generating cffi module 'build/temp.linux-i686-3.8/_openssl.c'              
  building '_openssl' extension                                              
  creating build/temp.linux-i686-3.8/build                                   
  creating build/temp.linux-i686-3.8/build/temp.linux-i686-3.8               
  i686-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c build/temp.linux-i686-3.8/_openssl.c -o build/temp.linux-i686-3.8/build/temp.linux-i686-3.8/_openssl.o -Wconversion -Wno-error=sign-conversion                       
  build/temp.linux-i686-3.8/_openssl.c:546:10: fatal error: openssl/opensslv.h: No such file or directory                                                 
    546 | #include <openssl/opensslv.h>                                      
        |          ^~~~~~~~~~~~~~~~~~~~                                      
  compilation terminated.                                                    
  error: command 'i686-linux-gnu-gcc' failed with exit status 1              
  ----------------------------------------                                   
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
I even have cryptography already installed on my box: 
python3 -m pip install cryptography
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (2.6.1)

**Comment by iii235** [comment]
Oh come on!

**Comment by ajinabraham** [comment]
Github issues are strictly for bug reports, use slack channel for support.

**Comment by iii235** [comment]
What slack channel?

**Comment by iii235** [comment]
Just help me out here

**Comment by ajinabraham** [comment]
1. Follow Official Docs to setup MobSF: https://mobsf.github.io/docs/#/

2. Issues are ONLY for reporting BUGS. For support, feature requests, questions, queries, and discussions use our slack channel for limited support. Join MobSF Slack channel: http://tiny.cc/mobsf
