### ISSUE TITLE
I have some error, on Window7

### ISSUE THREAD

**Issue by caoxiaoyan163** [MobSF/Mobile-Security-Framework-MobSF#1411]
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Python37\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /MobSF/Mobile-Security-Framework-MobSF/master/MobSF/settings.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000000172D3550>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

when I run the MobSF, get some issue

**Comment by ajinabraham** [comment]
This looks like is a network issue at your end. Please use slack channel for support

**Comment by caoxiaoyan163** [comment]
> This looks like is a network issue at your end. Please use slack channel for support

thanks
