### ISSUE TITLE
[FEATURE]there is no API 28 support (Android Studio Emulator)Dynamic Analyzer 

### ISSUE THREAD

**Issue by caoxiaoyan163** [MobSF/Mobile-Security-Framework-MobSF#1427]
I have a question： my app only can install on ARM side. but Android Studio Emulator only support api level to 25. how to fix then. X86 side MobSF Dynamic Analyzer performs good.but my app just run on Arm 

thanks

**Comment by ajinabraham** [comment]
Android studio arm emulator only supports till API 25. If it's an ARM only app and targeted for API above 25, you might need a real rooted device. We do not support it official, but you can achieve it with some hacks and efforts.

**Comment by ajinabraham** [comment]
For support and help, please use our slack channel.
