### ISSUE TITLE
Error in install on Windows 10

### ISSUE THREAD

**Issue by jimmyleeeeee** [MobSF/Mobile-Security-Framework-MobSF#1429]
When click setup.bat in windows 10, it shows error:
[ERROR] OpenSSL executable not found in [C:\\Program Files\\OpenSSL-Win64\\bin\\openssl.exe]
[INFO] Install OpenSSL - https://slproweb.com/download/Win64OpenSSL-1_1_1d.exe

when visit https://slproweb.com/download/Win64OpenSSL-1_1_1d.exe, the page is not existing.

Should it be https://slproweb.com/download/Win64OpenSSL-1_1_1g.exe ?

**Comment by ajinabraham** [comment]
Yes that link is updated now.
