### ISSUE TITLE
No Results in Code Analysis for any apk in MobSF v3

### ISSUE THREAD

**Issue by pentest499** [MobSF/Mobile-Security-Framework-MobSF#1438]
I have installed latest mobsf v3.0 in windows 10 machine. There were no installation errors. But while scanning any apk, the code analysis part, SHARED LIBRARY BINARY ANALYSIS, JAVA API and FILE ANALYSIS are showing empty results (No data available in table). 

Command prompt result:-(No errors)

[INFO] 18/Jun/2020 14:36:30 - Reading Android Manifest
[INFO] 18/Jun/2020 14:36:30 - Parsing AndroidManifest.xml
[INFO] 18/Jun/2020 14:36:30 - Fetching icon path
[INFO] 18/Jun/2020 14:36:30 - Extracting Manifest Data
[INFO] 18/Jun/2020 14:36:30 - Fetching Details from Play Store: com.android.insecurebankv2
[INFO] 18/Jun/2020 14:36:31 - Manifest Analysis Started
[INFO] 18/Jun/2020 14:36:31 - Static Android Binary Analysis Started
[INFO] 18/Jun/2020 14:36:31 - Static Android Resource Analysis Started
[INFO] 18/Jun/2020 14:36:31 - Reading Code Signing Certificate
[INFO] 18/Jun/2020 14:36:31 - Running APKiD 2.1.0
[INFO] 18/Jun/2020 14:36:34 - Trackers Database is up-to-date
[INFO] 18/Jun/2020 14:36:34 - Detecting Trackers
[INFO] 18/Jun/2020 14:36:35 - APK -> JAVA
[INFO] 18/Jun/2020 14:36:35 - Decompiling to Java with jadx
[INFO] 18/Jun/2020 14:36:35 - DEX -> SMALI
[INFO] 18/Jun/2020 14:36:35 - Converting classes.dex to Smali Code
[INFO] 18/Jun/2020 14:36:35 - Static Android Code Analysis Started
[INFO] 18/Jun/2020 14:36:35 - Code Analysis Started on - java_source
[INFO] 18/Jun/2020 14:36:35 - Finished Code Analysis, Email and URL Extraction
[INFO] 18/Jun/2020 14:36:35 - Extracting Strings from APK
[INFO] 18/Jun/2020 14:36:35 - Detecting Firebase URL(s)
[INFO] 18/Jun/2020 14:36:35 - Performing Malware Check on extracted Domains
[INFO] 18/Jun/2020 14:36:38 - Malware Database is up-to-date
[INFO] 18/Jun/2020 14:36:38 - Connecting to Database
[INFO] 18/Jun/2020 14:36:38 - Saving to Database

## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: required python
MobSF Version: latest (Mobsfv3.0)
```

**Comment by ajinabraham** [comment]
MobSF skip analyzing default classes. https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L239

Insecure Bank uses one of these as package name.

**Comment by pentest499** [comment]
I just kept here Insecure Bank logs. But what ever android app I scanned, it didn't show.

**Comment by ajinabraham** [comment]
Please share an APK that reporduce this issue, along with console log.

**Comment by ajinabraham** [comment]
Passed 25 days response timeline. Closing.
