### ISSUE TITLE
[FEATURE] Android Signer Certificate Status: v1-scheme-only should not be marked as "good"

### ISSUE THREAD

**Issue by mkshr31** [MobSF/Mobile-Security-Framework-MobSF#1444]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
According to [New Android vulnerability allows attackers to modify apps without affecting their signatures](https://www.guardsquare.com/en/blog/new-android-vulnerability-allows-attackers-modify-apps-without-affecting-their-signatures), it is highly recommended to "[...] at least always apply signature scheme v2.".
Unfortunately, the current version of MobSF does not distinguish qualitatively between [the four different signing versions](https://source.android.com/security/apksigning).

**Describe the solution you'd like**
MobSF should not use "good" as status for the Android Signer Certificate if a APK was signed using the v1 scheme only.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ajinabraham** [comment]
Thanks for opening the enhancement request. Will be addressed in next release.

**Comment by ajinabraham** [comment]
Added in #1486
