### ISSUE TITLE
I run setup.sh in ubuntu,  occur error

### ISSUE THREAD

**Issue by ESP-ME** [MobSF/Mobile-Security-Framework-MobSF#1447]
setup.sh: 36: setup.sh: Syntax error: "else" unexpected (expecting "then")

**Comment by ajinabraham** [comment]
Please provide more information like ubuntu version, shell in use etc.

**Comment by ESP-ME** [comment]
My ubuntu installed in win 10 Microsoft store.  I not modify setup file.

$ uname -a
Linux DESKTOP-II5M1QA 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ajinabraham** [comment]
We don't test or support Ubuntu on Windows. In Windows you can run setup.bat to run MobSF on Windows

**Comment by ESP-ME** [comment]
run MobSF on Windows also can not work.

D:\embedded\resource-code-repository\reverse\androidbook_code\chapter6\Mobile-Security-Framework-MobSF>setup.bat
此时不应有 \Microsoft。

**Comment by ajinabraham** [comment]
Please use our slack channel for support. Github issues are only for bug reports and you should provide all the requested information.
