### ISSUE TITLE
Thanks to help me.My PDF file cannot be displayed in Chinese.IOS Scan.

### ISSUE THREAD

**Issue by guxiaonian** [MobSF/Mobile-Security-Framework-MobSF#1456]
I build the dockerfile in my mac.When I run it ,my app icon is not show,like no-icon.image.also , My PDF file cannot be displayed in Chinese.it shows like [] [] [] [].

**Comment by ajinabraham** [comment]
Please use slack channel. Github issues are only for bugs and we require all the requested relevant information regarding a any bug report.
