### ISSUE TITLE
Error Running ADB Command

### ISSUE THREAD

**Issue by hujingzheng** [MobSF/Mobile-Security-Framework-MobSF#1460]
I have a problem using the dynamic analyzer. The version used is v3.0.9
![wen](https://user-images.githubusercontent.com/26641791/86323788-0a192300-bc70-11ea-830e-014f7e931d47.jpg)
![wen2](https://user-images.githubusercontent.com/26641791/86323831-1dc48980-bc70-11ea-9da6-6f8e30c742ef.jpg)

**Comment by superpoussin22** [comment]
can you switch to slack channel and provide more information like do you use Genymotion, Android emulator .... ?

**Comment by hujingzheng** [comment]
Sorry, I forgot to say it. I used genymotion. Now the dynamic analysis can run successfully, but I don't know how to use Frida scripts. Thank you again. I hope this project can be done more and more
![asdf1](https://user-images.githubusercontent.com/26641791/86344963-840bd500-bc8d-11ea-8a6f-f012e37af97a.jpg)
