### ISSUE TITLE
add some restApi interface

### ISSUE THREAD

**Issue by hujingzheng** [MobSF/Mobile-Security-Framework-MobSF#1462]
Can the restapi interface of "start activity tester" be added and the restapi interface for obtaining dynamic analysis report be added? You know, in Linux with this framework, you want to directly drop the command to get dynamic analysis results

**Comment by ajinabraham** [comment]
@hujingzheng Most of the Dynamic Analyzer APIs are RESTful, you could inspect the network connection to see the API details. It is just that we do not document them because a lot of things under Dynamic Analyzer is being changed and actively developed.
