### ISSUE TITLE
unable to run the tool

### ISSUE THREAD

**Issue by mohsin2928** [MobSF/Mobile-Security-Framework-MobSF#1467]
Hi there, could you please help me with this

root@kali:~/Downloads/Mobile-Security-Framework-MobSF# ./run.sh
Traceback (most recent call last):
  File "/root/Downloads/Mobile-Security-Framework-MobSF/venv/bin/gunicorn", line 6, in <module>
    from gunicorn.app.wsgiapp import run
ModuleNotFoundError: No module named 'gunicorn'
root@kali:~/Downloads/Mobile-Security-Framework-MobSF# pip3 install gunicorn
Requirement already satisfied: gunicorn in /usr/local/lib/python3.8/dist-packages (20.0.4)
Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn) (46.1.3)
root@kali:~/Downloads/Mobile-Security-Framework-MobSF# ./run.sh
Traceback (most recent call last):
  File "/root/Downloads/Mobile-Security-Framework-MobSF/venv/bin/gunicorn", line 6, in <module>
    from gunicorn.app.wsgiapp import run
ModuleNotFoundError: No module named 'gunicorn'
root@kali:~/Downloads/Mobile-Security-Framework-MobSF#

**Comment by mohsin2928** [comment]
![error](https://user-images.githubusercontent.com/44868349/87246254-df3f8380-c454-11ea-8228-bdc3562da932.JPG)

**Comment by ajinabraham** [comment]
Please join slack channel for support: https://mobsf.slack.com/join/shared_invite/enQtNzM2NTAyNzA1MjgxLTdjMzkzNDc3ZjdiMjkwZTZhMmFhNDlkZmMwZDhjNDNmYTAzYWE5NGZlMDIzYzliNTdiMDQ2MTRlYjU1MjkyNGM
Github Issues are only for bugs.

**Comment by houtengzhi** [comment]
I have also met this issue, has it been resolved?
