### ISSUE TITLE
`OutputFormatter` has no method called  _build_json_output

### ISSUE THREAD

**Issue by xandfury** [MobSF/Mobile-Security-Framework-MobSF#1468]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/36c1440b807a65f0c5dcedefe7aad77e72c59948/MalwareAnalyzer/views/apkid.py#L45

There exists one called `build_json_output`

**Comment by ajinabraham** [comment]
Yes, that method was there in APKiD <=2.0.3 (https://github.com/rednaga/APKiD/blob/v2.0.0/apkid/output.py#L107). Hence it was added for backward compatibility for users who haven't updated MobSF dependencies.

**Comment by ajinabraham** [comment]
Closing this. Feel free to comment if you have any thoughts.

**Comment by xandfury** [comment]
Actually it crashed on my local setup. Which is why I opened a ticket :slightly_smiling_face:

**Comment by ajinabraham** [comment]
I think you have a stale version of APKID installed globally. You might need to remove it. This didn't happen to us on our tests. See if you can reporduce this on a fresh setup.
