### ISSUE TITLE
VM's /system is not writable. This VM cannot be used for Dynamic Analysis

### ISSUE THREAD

**Issue by hujingzheng** [MobSF/Mobile-Security-Framework-MobSF#1469]
I use the Android stuido method to configure dynamic analysis, but I found that it is no problem to start dynamic analysis after starting the simulator with "Android virtual device manager". However, as long as I don't operate for a long time and use dynamic analysis again, mobsf will disconnect the link with the simulator and only restart the simulator can it be connected. Otherwise, the following error will be reported

![image](https://user-images.githubusercontent.com/26641791/87513262-07282480-c6ab-11ea-8fe5-92f7294b24ba.png)

**Comment by ajinabraham** [comment]
You are not using a non-production emulator. Join slack for support. Github issues are for bugs only.

**Comment by Laci0088** [comment]
>

**Comment by Laci0088** [comment]
``
