### ISSUE TITLE
Unzipping Error right after uploading apk

### ISSUE THREAD

**Issue by wadim-al** [MobSF/Mobile-Security-Framework-MobSF#1470]
## ENVIRONMENT

```
OS and Version: Windows 10 x64 2004
Python Version: 3.7.8 x32
MobSF Version: 3.0.9 b
```

## EXPLANATION OF THE ISSUE

```
Unzipping Error is shown in console after uploading a particular apk. APK file is invalid or corrupt message is shown in web UI.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Start mobsf 3.0.9 b
2. Upload apk (I can't disclose the apk in question so do not ask to provide it).
```

## LOG FILE

```
[log.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4923710/log.txt)
```

**Comment by ajinabraham** [comment]
This looks like a malformed APK. We can't troubleshoot without the APK, hence closing this issue.

**Comment by wadim-al** [comment]
Could you provide steps for logs gathering instead of closing the issue? I will clean out any sensitive info and provide more information.

**Comment by ajinabraham** [comment]
I went through the logs that you shared. As per the logs the APK appears to be malformed or the files are locked by some other process. The issue is triggered by the APK file, so we need the file to troubleshoot anything further.

**Comment by wadim-al** [comment]
Is there any additional more verbose debug logging mode in mobsf?

**Comment by ajinabraham** [comment]
Nope, none that I am aware of.
