### ISSUE TITLE
Add numbers for reference for the static analysis PDF report

### ISSUE THREAD

**Issue by harri35** [MobSF/Mobile-Security-Framework-MobSF#1481]
Please add numbers for reference for the static analysis PDF report. It will make it easier to refer to the items in the Manifest Analysis and Code Analysis parts of the report from any accompanying explanation/addition document users of the software may want to write. Currently, it is hard to refer to items, the only meaningful way is via the text under the ISSUE column. 

My case: for each release, I have to provide the MObSF report along with a companion document addressing each "high" and "warning" level items. It is hard to refer from the companion document to the report.

**Comment by ajinabraham** [comment]
Added in #1486
