### ISSUE TITLE
This APK cannot be installed. Is this APK compatible the Android VM/Emulator?

### ISSUE THREAD

**Issue by dubey-amit** [MobSF/Mobile-Security-Framework-MobSF#1502]
```
OS and Version: win 10
Python Version: 3.8
MobSF Version: 3.1.1 beta
```

**This APK cannot be installed. Is this APK compatible the Android VM/Emulator?**

```
The Dynamic analysis was working fine till I updated to 3.1.1 beta

## STEPS TO REPRODUCE THE ISSUE

```
1. Upload APK
2. Start dynamic analysis
3. Error : This APK cannot be installed. Is this APK compatible the Android VM/Emulator?
```


## LOG FILE

```
[WARNING] 06/Aug/2020 20:39:29 - Using Fake XML to continue the Analysis
[INFO] 06/Aug/2020 20:39:30 - Fetching icon path
[INFO] 06/Aug/2020 20:39:31 - Extracting Manifest Data
[INFO] 06/Aug/2020 20:39:31 - Fetching Details from Play Store: Failed
[INFO] 06/Aug/2020 20:39:31 - Manifest Analysis Started
[INFO] 06/Aug/2020 20:39:31 - Static Android Binary Analysis Started
[INFO] 06/Aug/2020 20:39:31 - Static Android Resource Analysis Started
[INFO] 06/Aug/2020 20:39:31 - Reading Code Signing Certificate
[INFO] 06/Aug/2020 20:39:31 - Running APKiD 2.1.0
[INFO] 06/Aug/2020 20:39:34 - Trackers Database is up-to-date
[INFO] 06/Aug/2020 20:39:34 - Detecting Trackers
[INFO] 06/Aug/2020 20:39:36 - APK -> JAVA
[INFO] 06/Aug/2020 20:39:36 - Decompiling to Java with jadx
[INFO] 06/Aug/2020 20:40:05 - DEX -> SMALI
[INFO] 06/Aug/2020 20:40:05 - Converting classes.dex to Smali Code
[INFO] 06/Aug/2020 20:40:05 - Converting classes2.dex to Smali Code
[INFO] 06/Aug/2020 20:40:05 - Static Android Code Analysis Started
[INFO] 06/Aug/2020 20:40:05 - Code Analysis Started on - java_source
[INFO] 06/Aug/2020 20:40:41 - Finished Code Analysis, Email and URL Extraction
[INFO] 06/Aug/2020 20:40:41 - Extracting Strings from APK
[INFO] 06/Aug/2020 20:40:42 - Detecting Firebase URL(s)
[INFO] 06/Aug/2020 20:40:44 - Performing Malware Check on extracted Domains
[INFO] 06/Aug/2020 20:40:50 - Malware Database is up-to-date
[INFO] 06/Aug/2020 20:40:51 - Connecting to Database
[INFO] 06/Aug/2020 20:40:51 - Saving to Database
[INFO] 06/Aug/2020 20:41:40 - Creating Dynamic Analysis Environment
[INFO] 06/Aug/2020 20:41:45 - ADB Restarted
[INFO] 06/Aug/2020 20:41:45 - Waiting for 2 seconds...
[INFO] 06/Aug/2020 20:41:47 - Connecting to Android 192.168.199.101:5555
[INFO] 06/Aug/2020 20:41:48 - Waiting for 2 seconds...
[INFO] 06/Aug/2020 20:41:50 - Restarting ADB Daemon as root
[INFO] 06/Aug/2020 20:41:50 - Waiting for 2 seconds...
[INFO] 06/Aug/2020 20:41:52 - Reconnecting to Android Device
[INFO] 06/Aug/2020 20:41:52 - Waiting for 2 seconds...
[INFO] 06/Aug/2020 20:41:54 - Found Genymotion x86 VM
[INFO] 06/Aug/2020 20:41:54 - Remounting /system
[INFO] 06/Aug/2020 20:41:54 - Performing System check
[INFO] 06/Aug/2020 20:41:54 - Android API Level identified as 25
[INFO] 06/Aug/2020 20:41:54 - Android Version identified as 7.1
[INFO] 06/Aug/2020 20:41:54 - Environment MobSFyed Check
[INFO] 06/Aug/2020 20:41:54 - Installing MobSF RootCA
[INFO] 06/Aug/2020 20:41:54 - Starting HTTPs Proxy on 1337
[INFO] 06/Aug/2020 20:41:54 - Killing httptools UI
[INFO] 06/Aug/2020 20:41:54 - Enabling ADB Reverse TCP on 1337
[INFO] 06/Aug/2020 20:41:54 - Setting Global Proxy for Android VM
[INFO] 06/Aug/2020 20:41:55 - Starting Clipboard Monitor
[INFO] 06/Aug/2020 20:41:55 - Getting screen resolution
[INFO] 06/Aug/2020 20:41:55 - Installing APK
[INFO] 06/Aug/2020 20:41:57 - Removing Global Proxy for Android VM
[ERROR] 06/Aug/2020 20:41:59 - This APK cannot be installed. Is this APK compatible the Android VM/Emulator?
[ERROR] 06/Aug/2020 20:41:59 - Internal Server Error: /android_dynamic/```

**Comment by ajinabraham** [comment]
Please join slack channel for support. The APK is either not compatible with x86 architecture or missing dependencies.

**Comment by dubey-amit** [comment]
APK is working properly when installed without mobsf

**Comment by YzaSoLong** [comment]
> APK is working properly when installed without mobsf

i am facing  the same situation，so how solve the problem？ i am using  Android 9 API 28

**Comment by 1UC1F3R616** [comment]
@YzaSoLong have u found the solution?

**Comment by ajinabraham** [comment]
See https://mobsf.github.io/docs/#/faq?id=dynamic-analysis-apk-failed-to-install

**Comment by 1UC1F3R616** [comment]
> > APK is working properly when installed without mobsf
> 
> i am facing the same situation，so how solve the problem？ i am using Android 9 API 28

you are able to install using `adb install app.apk` ? 
what are u getting with this command --> `adb devices`
