### ISSUE TITLE
xapk packages not supported

### ISSUE THREAD

**Issue by javixeneize** [MobSF/Mobile-Security-Framework-MobSF#1510]
Hi

Im trying to analyse an XAPK file, and it is not supported by the framework. It would be a nice addition to it :)

**Comment by ajinabraham** [comment]
As of now it is not supported. But you could extrack the XAPK and scan the bundled APK's individually.

**Comment by javixeneize** [comment]
Yeah, if you rename it as a zip and extract it, it has the .apk inside, so should not be difficult to implement. I dont have much time, but if i find some, i can do a PR with this

**Comment by ajinabraham** [comment]
Tracked Separately
