### ISSUE TITLE
IPA Binary Analysis issue when archiving Distribution and Development Provisiong profile it throws unrelated error

### ISSUE THREAD

**Issue by delmarz** [MobSF/Mobile-Security-Framework-MobSF#1516]
> We have a partial fix for this is 3.1.1. I don't think we can fix this completely as from binary analysis, it's difficult to get into a precise conclusion.

@ajinabraham
I tried to re-investigate this issue it seems there something wrong while compiling the binary to development/distribution profile since it has symbols stripped.

It could be 100% false positive for both _(SSP & ARC) and Insecure Apis error_

Hence it throws an unrelated error:

**Archiving to Distribution Profile** - _No insecure apis error etc_,  **But it throws (SSP and ARC) error**

**Archiving to Development Profile** - _No error for (SSP and ARC)_, **But it throws insecure apis error etc**

This is tested with the latest Swift 5.2.x 
Ref: you quoted last time which is related on this issue. https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/681#issuecomment-412803911

_Originally posted by @delmarz in https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/372#issuecomment-674363738_

**Comment by ajinabraham** [comment]
This could be a false positive. I don't think we have a reliable way to fix this.

**Comment by ajinabraham** [comment]
Waiting for files to reproduce this issue.

**Comment by delmarz** [comment]
DisAndDev.zip
<https://drive.google.com/file/d/17ZqwsAgH0miVEWNNHI8Coh3PBCQIYG5a/view?usp=drive_web>


I attached the development and distribution ipa. please let me know

**Comment by delmarz** [comment]
I just sent the file through your gmail account. Thanks Ajin!

**Comment by ajinabraham** [comment]
Stripped binaries now show a warning
<img width="1202" alt="Screen Shot 2020-10-07 at 9 54 52 AM" src="https://user-images.githubusercontent.com/4301109/95340464-32be4380-0883-11eb-85c7-c5db7fa5dcdf.png">
This is fixed in #1558 
Thanks for the patience @delmarz

**Comment by delmarz** [comment]
Is this fixed available now in master?

**Comment by ajinabraham** [comment]
@delmarz Not yet #1558  will be merged to master soon after peer review

**Comment by ajinabraham** [comment]
Now available in master!

**Comment by delmarz** [comment]
thanks do you have any idea on this? When I run the './run.sh 127.0.0.1:8000'

I get some error logs in terminal, 

- Shutting down: Master
- Reason: Worker failed to boot.

@ajinabraham

**Comment by ajinabraham** [comment]
MobSF 3.1.7 has has database model changes new dependencies. To update see: https://mobsf.github.io/docs/#/updating
