### ISSUE TITLE
Support for Android App Bundles

### ISSUE THREAD

**Issue by ChuckMN** [MobSF/Mobile-Security-Framework-MobSF#1517]
Starting in the fall of 2021 Google will no longer be supporting APK files for new applications and will be requiring for developers to leverage Android App Bundles. The information on this can be found at the below Google Announcement URL.

https://android-developers.googleblog.com/2020/08/recent-android-app-bundle-improvements.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+blogspot%2FhsDu+%28Android+Developers+Blog%29

More information can also be found on the Android App Bundle page at the below Android Developer URL.

https://developer.android.com/platform/technology/app-bundle

It would be great if this tool supported Android App Bundles as a supported file type even though the structure and compilation is very different from that of a typical APK file.

The interactivity with the system is great through the GUI and API so no changes needed there, but would be great for Bundles to be supported prior to the Google Play Store requirement for new applications.

The current version of the tool returns the below API response.

`{"error": "File format not Supported!"}`

Thank you in advance for continuing to support this great tool!

**Comment by superpoussin22** [comment]
see #1510

**Comment by ajinabraham** [comment]
@superpoussin22 I think we will reopen this and close the other one since this has more useful info.

**Comment by ajinabraham** [comment]
Addressed in 3.2.2
