### ISSUE TITLE
MobSF i am getting error

### ISSUE THREAD

**Issue by dileep7007** [MobSF/Mobile-Security-Framework-MobSF#1518]
After upload APK file i am getting this error

Error
Raised when run() is called with check=True and the process returns a non-zero exit status. Attributes: cmd, returncode, stdout, stderr, output

Command '['C:/Program Files/Java/jdk1.7.0_79/bin/java.exe', '-jar', 'E:/HART/MobSF/New folder/Mobile-Security-Framework-MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools\\baksmali-2.4.0.jar', 'list', 'classes', 'E:/HART/MobSF/New folder/Mobile-Security-Framework-MobSF/Mobile-Security-Framework-MobSF/uploads/0b88410c55a36d5489987eca2112454f\\classes.dex']' returned non-zero exit status 1.

1. As you suggested change, in  set java path in MobSF/settings.py,  i have did this then also i am getting above error
2. In cmd prompt also i am getting error, screen shot is attached

How can i fix this issue?
![Java](https://user-images.githubusercontent.com/69950531/90724775-b379ae00-e2dc-11ea-946a-3d29024c170b.png)

**Comment by superpoussin22** [comment]
Please use slack channel to discuss installation issue 
also please reduce installation path length

**Comment by dileep7007** [comment]
After reducing installation path, still i am facing the issue could you please help this issue
