### ISSUE TITLE
Change required installation packages for libjpeg8-dev

### ISSUE THREAD

**Issue by R3dF0x-cyber** [MobSF/Mobile-Security-Framework-MobSF#1523]
I tried installing MobSF for the first time according to the instructions here: https://mobsf.github.io/docs/#/requirements

According to that requirements page, it is required to install libjpeg8-dev 

However, in Debian linux, if you "sudo apt-get install libjpeg8-dev", you receive the following error:

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libjpeg8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev

E: Package 'libjpeg8-dev' has no installation candidate
`
If you do as the error suggests and install libjpeg62-turbo-dev as suggested, MobSF appears to run correctly as intended

This bug report is to change the install documentation to require the installation of libjpeg62-turbo-dev instead of libjpeg8-dev

**Comment by superpoussin22** [comment]
the installation documentation was tested on Ubuntu not Debian 
Perhaps we could add this info for debian @ajinabraham  ?

**Comment by ajinabraham** [comment]
@superpoussin22 Yes we could do that.

**Comment by ajinabraham** [comment]
Please open this issue here: https://github.com/MobSF/docs
