### ISSUE TITLE
Astrings [FEATURE]

### ISSUE THREAD

**Issue by ipk1** [MobSF/Mobile-Security-Framework-MobSF#1524]
the tool shows a list of stings it could parse from the apk, under Astrings, however is it possible to have the location of the file where it found the string, in my case it was a google api, i have searched
<img width="640" alt="smali" src="https://user-images.githubusercontent.com/32953048/91168494-596d5400-e6f3-11ea-8270-9240cb70e622.png">
 the entire smali and java code but could not locate it.

thanks

**Comment by ajinabraham** [comment]
These strings are not from Code, but from Android Resource XML called `strings.xml` https://developer.android.com/guide/topics/resources/string-resource
