### ISSUE TITLE
MobSF stucks when analysis starts

### ISSUE THREAD

**Issue by JuanchoParedes** [MobSF/Mobile-Security-Framework-MobSF#1525]
Hello, I've installed all tools as the documentation says, I've analyzed a couple of test apk files and works well, however I tried an apk file that weights around 189 MB, but it gets stucked when the analysis starts. No errors are in the log. here is last part of the Log :
`
[INFO] 25/Aug/2020 09:05:45 - Static Android Code Analysis Started
[INFO] 25/Aug/2020 09:05:46 - Code Analysis Started on - java_source`

It stucks here, nothing happens.
I'm on Windows 10 by the way. Thanks in advance.

**Comment by ajinabraham** [comment]
There was a bug in libsast that was fixed recently. You need to update libsast within the venv.

Navigate to MobSF root directory from command prompt
```
.\venv\Scripts\activate
pip install libsast==1.1.8
```
If you still see any issues, please join our Slack channel for support.

**Comment by pavel-pi** [comment]
Had the same issue on Kali. The solution above worked for me:

```
source ./venv/bin/activate
pip install libsast==1.1.8
```
