### ISSUE TITLE
Recent scan page [FEATURE]

### ISSUE THREAD

**Issue by thisguy23** [MobSF/Mobile-Security-Framework-MobSF#1526]
It would be great to see things like the appscores  CVSS/security score/trackers detection on the recent scan page.
sort-able would be amazing but being able to just view it on the page would be great. for overview and metrics.
![image](https://user-images.githubusercontent.com/5863477/91603216-9e36fc00-e93a-11ea-85da-1573e77ead28.png)
![image](https://user-images.githubusercontent.com/5863477/91603248-abec8180-e93a-11ea-97d0-c7b32b7edfa4.png)

Thanks,

**Comment by ajinabraham** [comment]
de scoping since scores are not implemented for windows yet. Tracked separately.
