### ISSUE TITLE
MobSFy Android Runtime Connection failed

### ISSUE THREAD

**Issue by rageshS** [MobSF/Mobile-Security-Framework-MobSF#1534]
Hi All,

I am a newbie in using MobSF, I already download this repository and perform a static analysis, Now i try to setuping the dynamic analysis.

I am working in Windows 10 OS, and I already installed the Android Studio and created an emulator too. Please see my configuration below.

Python version - 3.6.8

Android Emulator name - Nexus_5X_API_26  (API version 26), 

in the dynamic analysis page it shows a message like the below image.

![image](https://user-images.githubusercontent.com/6523618/92687524-514f1e80-f359-11ea-98d9-e672c94a3f56.png)

**Comment by rageshS** [comment]
(venv) (base) C:\Projects\py\MobSF>run.bat
Serving on http://zc-ws-153.office.in:8000
[INFO] 10/Sep/2020 11:51:07 -
  __  __       _    ____  _____       _____  _
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / |
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) || |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)_|

[INFO] 10/Sep/2020 11:51:07 - Mobile Security Framework v3.1.4 Beta
REST API Key: feabfc173d13afd2b878eb42546318b8366e8394d9d03bc7800c8f4c1895fe66
[INFO] 10/Sep/2020 11:51:07 - OS: Windows
[INFO] 10/Sep/2020 11:51:07 - Platform: Windows-10-10.0.18362-SP0
[INFO] 10/Sep/2020 11:51:07 - Dist:
[INFO] 10/Sep/2020 11:51:07 - MobSF Basic Environment Check
[INFO] 10/Sep/2020 11:51:07 - Checking for Update.
[INFO] 10/Sep/2020 11:51:07 - No updates available.
[INFO] 10/Sep/2020 11:51:14 - MobSFying Android instance
* daemon not running; starting now at tcp:5037
* daemon started successfully
[INFO] 10/Sep/2020 11:51:19 - ADB Restarted
[INFO] 10/Sep/2020 11:51:19 - Waiting for 2 seconds...
[INFO] 10/Sep/2020 11:51:21 - Connecting to Android Nexus_5X_API_26
[INFO] 10/Sep/2020 11:51:34 - Waiting for 2 seconds...
[ERROR] 10/Sep/2020 11:51:36 - failed to connect to Nexus_5X_API_26:5555

![image](https://user-images.githubusercontent.com/6523618/92689242-4f3a8f00-f35c-11ea-8600-d37ae6a82012.png)

**Comment by ajinabraham** [comment]
Please use slack channel for support. GitHub Issues are only for bugs
