### ISSUE TITLE
MobSF: After Uploading zip Source code i am getting this error

### ISSUE THREAD

**Issue by dileep7007** [MobSF/Mobile-Security-Framework-MobSF#1535]
![Source code issue](https://user-images.githubusercontent.com/69950531/92723267-79a14200-f386-11ea-8daf-1330daa721c6.png)
MobSF tool: After Uploading zip Source code i am getting this error, we are writing code Visual studio
Can you please help to fix this issue

**Error:**
Zipped Source Code Instruction
Mobile Security Framework supports iOS and Android (eclipse and Android Studio) project files.

Eclipse Project: The file AndroidManifest.xml and the directory 'src' must exist in the root directory of ZIPPED Source files for eclipse projects.

Android Studio Project: AndroidManifest.xml must be located at 'app/src/main/AndroidManifest.xml' and the directory 'app/src/main/java/' must exist for Android Studio projects.

iOS Project: For iOS projects, the .xcodeproj file must exist in the root directory of the ZIPPED Source files.

**Comment by ajinabraham** [comment]
Please use slack for suppt
