### ISSUE TITLE
[Feature] Android: Static Analysis: Improve search for URLs

### ISSUE THREAD

**Issue by mkshr31** [MobSF/Mobile-Security-Framework-MobSF#1536]
The attached APK file contains the URL `https://issuetracker.google.com/issues/116541301`:

```
$ unzip com.microsoft.teams_2020596013.apk -d exam_room
$ grep -r https://issuetracker.google.com --binary-files=text exam_room
[...] exam_room/classes.dex: [...] See  https://issuetracker.google.com/issues/116541301 for details [...]
```

On the other hand, MobSF v3.1.1 does not show it in the generated JSON report. This behavior should be corrected and the potentially accessed URL should be shown as such in the report.

Link to APK: https://easyupload.io/szsx3q

**Comment by ajinabraham** [comment]
I couldn't reproduce this 

```
root@90e77c0e4212:/tmp# uname -a
Linux 90e77c0e4212 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
root@90e77c0e4212:/tmp# ls
com.microsoft.teams_2020596013.apk
root@90e77c0e4212:/tmp# grep -r https://issuetracker.google.com --binary-files=text .
root@90e77c0e4212:/tmp#
```

Since you give `.` and `-r` it might from a different file?

**Comment by mkshr31** [comment]
I've updated the instructions for proving that the URL is included. Basically the APK must be unzipped first. Sorry for the incomplete information.

**Comment by ajinabraham** [comment]
So this URL is from a file that is skipped for analysis by MobSF.

```bash
$ grep -r https://issuetracker.google.com --binary-files=text java_source/
java_source//androidx/databinding/ViewDataBinding.java:        throw new IllegalArgumentException("The provided bindingComponent parameter must be an instance of DataBindingComponent. See  https://issuetracker.google.com/issues/116541301 for details of why this parameter is not defined as DataBindingComponent");
```

The path name `androidx/databinding/ViewDataBinding.java` is skipped by default, see https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L238-L239

If you need to include that URL, you can remove `androidx` from `SKIP_CLASS_PATH` and do a rescan.
