### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by k1dp** [MobSF/Mobile-Security-Framework-MobSF#1539]
Hi team,
I am facing this issue, I have seen some previews issue as "Error Inappropriate argument type. 'NoneType' object is not subscriptable"
but not helpful, sharing logs.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/55620313/93056658-59c19500-f68a-11ea-8e70-3c1fa04d3254.png)
[INFO] 14/Sep/2020 12:12:36 -
  __  __       _    ____  _____       _____  _
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / |
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) || |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)_|

[INFO] 14/Sep/2020 12:12:36 - Mobile Security Framework v3.1.4 Beta
REST API Key: 7cf0d02684988f148d2e827bd7814792d9ad1f8bd1df1bf8c53271424fcc1f7c
[INFO] 14/Sep/2020 12:12:36 - OS: Windows
[INFO] 14/Sep/2020 12:12:36 - Platform: Windows-10-10.0.18362-SP0
[INFO] 14/Sep/2020 12:12:36 - Dist:
[INFO] 14/Sep/2020 12:12:36 - MobSF Basic Environment Check
[WARNING] 14/Sep/2020 12:12:36 - Dynamic Analysis related functions will not work.
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 14/Sep/2020 12:12:36 - Checking for Update.
[INFO] 14/Sep/2020 12:12:37 - No updates available.
[INFO] 14/Sep/2020 12:13:03 - MIME Type: application/vnd.android.package-archive FILE: applenative5.6.0release.apk
[INFO] 14/Sep/2020 12:13:03 - Performing Static Analysis of Android APK
[INFO] 14/Sep/2020 12:13:03 - Starting Analysis on : appleNative5.6.0release.apk
[INFO] 14/Sep/2020 12:13:03 - Generating Hashes
[INFO] 14/Sep/2020 12:13:04 - Unzipping
[INFO] 14/Sep/2020 12:13:09 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Sep/2020 12:13:09 - APK Extracted
[INFO] 14/Sep/2020 12:13:09 - Converting AXML to XML
[INFO] 14/Sep/2020 12:13:44 - Reading Android Manifest
[INFO] 14/Sep/2020 12:13:44 - Parsing AndroidManifest.xml
[INFO] 14/Sep/2020 12:13:45 - Fetching icon path
[INFO] 14/Sep/2020 12:13:45 - Extracting Manifest Data
[INFO] 14/Sep/2020 12:13:45 - Fetching Details from Play Store: com.applemobile.appleofflineplay
[INFO] 14/Sep/2020 12:13:46 - Manifest Analysis Started
[INFO] 14/Sep/2020 12:13:46 - Static Android Binary Analysis Started
[INFO] 14/Sep/2020 12:13:46 - Static Android Resource Analysis Started
[INFO] 14/Sep/2020 12:13:46 - Reading Code Signing Certificate
[INFO] 14/Sep/2020 12:13:47 - Running APKiD 2.1.0
[INFO] 14/Sep/2020 12:13:51 - Trackers Database is outdated!
[INFO] 14/Sep/2020 12:13:51 - Updating Trackers Database....
[INFO] 14/Sep/2020 12:13:51 - Detecting Trackers
[INFO] 14/Sep/2020 12:13:54 - APK -> JAVA
[INFO] 14/Sep/2020 12:13:54 - Decompiling to Java with jadx
[INFO] 14/Sep/2020 12:14:32 - DEX -> SMALI
[INFO] 14/Sep/2020 12:14:32 - Converting classes.dex to Smali Code
[INFO] 14/Sep/2020 12:14:32 - Converting classes2.dex to Smali Code
[INFO] 14/Sep/2020 12:14:32 - Static Android Code Analysis Started
[INFO] 14/Sep/2020 12:14:32 - Code Analysis Started on - java_source
[ERROR] 14/Sep/2020 12:15:43 - Performing Code Analysis
Traceback (most recent call last):
  File "C:\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\code_analysis.py", line 67, in code_analysis
    pfile.read_text('utf-8', 'ignore'), relative_java_path)
  File "C:\Users\kuldeeps\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1206, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\kuldeeps\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1193, in open
    opener=self._opener)
  File "C:\Users\kuldeeps\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1046, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Mobile-Security-Framework-MobSF-master\\Mobile-Security-Framework-MobSF\\uploads\\40276384ebb0664f0445f629b9cf4127\\java_source\\com\\applemobile\\appleofflineplay\\orange_demo\\model\\botNext\\chat\\response\\RelationshipStrategy\\BotRelationshipStrategyResponse.java'
[INFO] 14/Sep/2020 12:29:58 - Extracting Strings from APK
[ERROR] 14/Sep/2020 12:29:59 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 206, in static_analyzer
    code_an_dic['urls_list'].extend(
TypeError: 'NoneType' object is not subscriptable
[ERROR] 14/Sep/2020 12:29:59 - 'NoneType' object is not subscriptable
[ERROR] 14/Sep/2020 12:29:59 - Internal Server Error: /StaticAnalyzer/

**Comment by superpoussin22** [comment]
can you reduce the path and use MobSf instead of Mobile-Security-Framework-MobSF-master ?
can you also use slack to exchange on your problem ?
