### ISSUE TITLE
External Storage issue in code analysis

### ISSUE THREAD

**Issue by gmamobileapp** [MobSF/Mobile-Security-Framework-MobSF#1545]
Hello There.

As per the MobSF report of our Android app, there are errors saying _"App can read/write to External Storage. Any App can read data written to External Storage"_. 
There is certain functionality in our app which needs external storage permission but the MobSF tool is marking it as HIGH severity error. Finally, it is lowering down the CVSS score. 
Please suggest what to do for this as it is reducing the overall score and it is needed in the app too. 

<img width="349" alt="1" src="https://user-images.githubusercontent.com/71687399/93850133-1b9c2500-fccb-11ea-97a0-6b02a848d192.png">

Thanks in advance.
GMA Mobile App

**Comment by ajinabraham** [comment]
please use slack channel for discussions

**Comment by gauravpatil1989** [comment]
Hi,
can i get the solution for above thing?
I am unable to find channel on slack

**Comment by ajinabraham** [comment]
MobSF slack channel https://tiny.cc/mobsf
