### ISSUE TITLE
Invalid json format of iOS reports

### ISSUE THREAD

**Issue by kalyaganov** [MobSF/Mobile-Security-Framework-MobSF#1546]
## STEPS TO REPRODUCE THE ISSUE

1. Upload facebook ipa file. Can be downloaded [here](https://iosninja.io/ipa-library/download-facebook-plus-ipa-ios)
2. Download json report from MobSF like this: 
```
echo "Downloading JSON report"
json_response=$(curl -X POST --url http://localhost:8000/api/v1/report_json --data "hash=$hash" -H "Authorization:$auth")
echo "$json_response" >> report.json
```
3. Json report is invalid. Trying to verify it here https://jsonformatter.curiousconcept.com/# and get this `INVALID (RFC 8259)`

## LOG FILE

```
This is the json report that i get.
```
https://gist.github.com/kalyaganov/c048e34ede1d22c812c551f72420bdb3

## SYSTEM

```
OS and Version: MacOS (mobsf docker image)
Python Version: 3.7.6
MobSF Version: 3.1.1 beta and 3.0.9
```

**Comment by ajinabraham** [comment]
Works fine on latest version for me. Please use slack for support. Also share the IPA that causes the issue.
The gist you shared looks it is formatted by something that might be the reason for invalid json.
The API response is guaranteed to be JSON https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/views/api/rest_api.py#L26

**Comment by kalyaganov** [comment]
>Also share the IPA that causes the issue.

You can download it here. https://iosninja.io/ipa-library/download-facebook-plus-ipa-ios

>Please use slack for support. 

Ok, thank you!

**Comment by kalyaganov** [comment]
It seems that my download script automatically removes all escape characters from `info_plist`. That was a problem. 

Thank you for support
