### ISSUE TITLE
MobSF Dynamic analyzer issue with android 6.0.0 in Genymotion 

### ISSUE THREAD

**Issue by Nisaryousafzai** [MobSF/Mobile-Security-Framework-MobSF#1547]
Android 6.0.0
MobSF V3.1 
Genymotion V2.12.1 
Windows 7

Followed complete guidelines as per documentation but facing an issue which couldn't be resolved yet!

[INFO] 23/Sep/2020 18:16:11 - Mobile Security Framework v3.1.5 Beta
REST API Key: fb7e1a7facaa7401feb4a2d4f4bb2af463f0d0cba78fb71c92003de0fcf0a483
[INFO] 23/Sep/2020 18:16:11 - OS: Windows
[INFO] 23/Sep/2020 18:16:11 - Platform: Windows-7-6.1.7601-SP1
[INFO] 23/Sep/2020 18:16:11 - Dist:
[INFO] 23/Sep/2020 18:16:11 - MobSF Basic Environment Check
[INFO] 23/Sep/2020 18:16:11 - Checking for Update.
[WARNING] 23/Sep/2020 18:16:12 - A new version of MobSF is available, Please upd
ate to v3.1.6 Beta from master branch.
[INFO] 23/Sep/2020 18:16:24 - MIME Type: application/vnd.android.package-archive
 FILE: sieve_base.apk
[INFO] 23/Sep/2020 18:16:24 - Performing Static Analysis of Android APK
[INFO] 23/Sep/2020 18:16:24 - Starting Analysis on : Sieve_base.apk
[INFO] 23/Sep/2020 18:16:24 - Analysis is already Done. Fetching data from the D
B...
[INFO] 23/Sep/2020 18:16:28 - Creating Dynamic Analysis Environment
[INFO] 23/Sep/2020 18:16:32 - ADB Restarted
[INFO] 23/Sep/2020 18:16:32 - Waiting for 2 seconds...
[INFO] 23/Sep/2020 18:16:34 - Connecting to Android x.x.x.x:y
[INFO] 23/Sep/2020 18:16:34 - Waiting for 2 seconds...
[INFO] 23/Sep/2020 18:16:36 - Restarting ADB Daemon as root
[INFO] 23/Sep/2020 18:16:36 - Waiting for 2 seconds...
[INFO] 23/Sep/2020 18:16:38 - Reconnecting to Android Device
[INFO] 23/Sep/2020 18:16:38 - Waiting for 2 seconds...
[INFO] 23/Sep/2020 18:16:40 - Found Genymotion x86 Android VM
[INFO] 23/Sep/2020 18:16:40 - Remounting
[INFO] 23/Sep/2020 18:16:40 - Performing System check
[INFO] 23/Sep/2020 18:16:40 - Android API Level identified as 23
[INFO] 23/Sep/2020 18:16:40 - Android Version identified as 6.0
[INFO] 23/Sep/2020 18:16:40 - Environment MobSFyed Check
[INFO] 23/Sep/2020 18:16:41 - Installing MobSF RootCA
[INFO] 23/Sep/2020 18:16:41 - Starting HTTPs Proxy on 1337
[INFO] 23/Sep/2020 18:16:43 - Enabling ADB Reverse TCP on 1337
[INFO] 23/Sep/2020 18:16:43 - Setting Global Proxy for Android VM
[INFO] 23/Sep/2020 18:16:44 - Starting Clipboard Monitor
[INFO] 23/Sep/2020 18:16:44 - Getting screen resolution
[INFO] 23/Sep/2020 18:16:45 - Installing APK
[INFO] 23/Sep/2020 18:16:46 - Removing Global Proxy for Android VM
[ERROR] 23/Sep/2020 18:16:48 - T**his APK cannot be installed. Is this APK compati
ble the Android VM/Emulator?**
[ERROR] 23/Sep/2020 18:16:48 - Internal Server Error: /android_dynamic/
ERROR:django.request:Internal Server Error: /android_dynamic/

adb path has been set from Genymotion also set in setting.py file of MobSF but still adb.exe stop working error pops up. Thought it might be a bug in android 6.0.0...

**Comment by ajinabraham** [comment]
Please use slack for support
