### ISSUE TITLE
This APK cannot be installed. Is this APK compatible the Android VM/Emulator?

### ISSUE THREAD

**Issue by CreVase** [MobSF/Mobile-Security-Framework-MobSF#1549]
Hi!

a lot of VPNs which I tries to research throws this error : 
"This APK cannot be installed. Is this APK compatible the Android VM/Emulator?"

What is the problem ? How can I solved it using MobSF ?

**Comment by ajinabraham** [comment]
Please use slack channel for support.

**Comment by CreVase** [comment]
What do you mean by slack channel?

בתאריך יום ה׳, 24 בספט׳ 2020, 14:08, מאת Ajin Abraham ‏<
notifications@github.com>:

**Comment by ajinabraham** [comment]
@CreVase Here is the invite to MobSF slack
https://mobsf.slack.com/join/shared_invite/enQtNzM2NTAyNzA1MjgxLTdjMzkzNDc3ZjdiMjkwZTZhMmFhNDlkZmMwZDhjNDNmYTAzYWE5NGZlMDIzYzliNTdiMDQ2MTRlYjU1MjkyNGM
