### ISSUE TITLE
[FEATURE] Problem with android permission

### ISSUE THREAD

**Issue by Doudnox** [MobSF/Mobile-Security-Framework-MobSF#1556]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**

When i have the permission : com.oppo.launcher.permission.WRITE_SETTINGS in my manifest it give me the permission description of  : android.permission.WRITE_SETTINGS so "Allows an application to modify the system's settings data. Malicious applications can corrupt your system's configuration." but it should have as description "Unknown permission from android reference"

**Describe the solution you'd like**
In manifest_analysis.py line 146 in the for loop don't rfind the last word but take all the permission name .
And in dvm_permissions.py write the full name permission

**Describe alternatives you've considered**
if the permission doesn't have android.permission in it tag as unknown

**Additional context**
If tomorrow i create a malware with a custom permission like : com.mymalware.SET_ALARM it will be tag as a normal permissions and not a dangerous one.

**Comment by ajinabraham** [comment]
Can you share the APK to reproduce this issue?

**Comment by Doudnox** [comment]
No problem it's : com.tumblr.apk . The tumblr app from the google play store ( https://play.google.com/store/apps/details?id=com.tumblr )
