### ISSUE TITLE
[FEATURE] Update NIAP verification to latest requirements

### ISSUE THREAD

**Issue by jarv-git** [MobSF/Mobile-Security-Framework-MobSF#1563]
Hi! Checking the NIAP testing functionality, I've realized that you are using https://www.niap-ccevs.org/MMO/PP/394.R/pp_app_v1.2_table-reqs.htm. However, this has been succeeded by https://www.niap-ccevs.org/MMO/PP/-429-M-/pp_app_v1.3_table-reqs.htm. Are you planning to update the NIAP verification to the latest requirements?

**Comment by ajinabraham** [comment]
Thanks for pointing this out. We will add this in a future major release.

**Comment by jarv-git** [comment]
Thanks! Sounds great.
