### ISSUE TITLE
Support Running in Physical Android Device NFC Pen Testing

### ISSUE THREAD

**Issue by hanoisteve** [MobSF/Mobile-Security-Framework-MobSF#1567]
NFC cannot be easily tested in an emulator so its necessary to run tests in a physical device. This is true of a number of other sensors as well.

**Is your feature request related to a problem? Please describe.**
Cannot run NFC tests on an emulator

**Describe the solution you'd like**
Support running mobSF on at least newer Android Devices with NFC

**Describe alternatives you've considered**
Try to find an emulator to handle NFC to an actual card
**Additional context**
Everyone who is using latests sensors and NFC needs this

**Comment by hanoisteve** [comment]
If there is a way to do it now lets document this and which device it works for. Thanks

**Comment by ajinabraham** [comment]
MobSF should work on real device if you have a rooted device and all the requirements are installed. You might need to fix any exceptions that might occur. We do not support this officially as we don't have the bandwidth to support any issues arising with real device.
