### ISSUE TITLE
Web UI elements overlap or spread afar on Mobile & big screen

### ISSUE THREAD

**Issue by elig0n** [MobSF/Mobile-Security-Framework-MobSF#1569]
## ENVIRONMENT

```
MobSF Version: 3.1.7 beta
OS and Version: Windows 10 Chrome , Android 9 Chrome
```

## EXPLANATION OF THE ISSUE

When accessing the web interface via Chrome on Windows 10 or Chrome on Android the layout get "messy" with elements overlapping each other or, when zooming out, spread far from each other. 

While on PC there is more freedom to resize a window and zoom-out, on Android 9 (~6 Inch screen) elements from table columns like images or buttons in the static analysis page or the search button on the main page overlap and cover other elements. 
Here's an example on both Android & PC:

_Chrome on PC (small window) at 100% zoom:_
![chrome_windows](https://user-images.githubusercontent.com/31196036/97226404-9aa9df00-17dc-11eb-970b-8e665909b490.png)

_Chrome on Android:_
![chrome_android](https://user-images.githubusercontent.com/31196036/97227897-cb8b1380-17de-11eb-8f59-66a91a46d649.jpg)

**Comment by ajinabraham** [comment]
Tracked Separately
