### ISSUE TITLE
API not support type of file but I can upload by web

### ISSUE THREAD

**Issue by IngeniaSeguridadInnovacion** [MobSF/Mobile-Security-Framework-MobSF#1570]
Hi,

I have downloaded and installed this framework and I'm working with API to integrate it with others frameworks. The problem is when I upload files by API because I get this error message:

![image](https://user-images.githubusercontent.com/67693293/97294845-d087ab80-184e-11eb-961a-a9254f840769.png)

On the other hand, If I upload the same file using web interface I can upload it, get static report and dynamic report.

![image](https://user-images.githubusercontent.com/67693293/97295179-40963180-184f-11eb-8b8f-e84ad8f461fa.png)
![image](https://user-images.githubusercontent.com/67693293/97295253-586db580-184f-11eb-8b5e-2d41a0022459.png)
![image](https://user-images.githubusercontent.com/67693293/97295380-7b986500-184f-11eb-8395-4f1d8dd318f1.png)

**Comment by ajinabraham** [comment]
This is mostly due to invalid API headers or file type. Please join MobSF slack channel for support and discussions.

**Comment by IngeniaSeguridadInnovacion** [comment]
The problem is resolved. In MobSF/views/home.py, when you extract in line 122 a content_type of file, the value is empty. This occur because in my python client I use requests library and its necesary to send content_type, usually "application/octet-stream". 
I never use this parameter, Its first time that I need use content_type in a client, but in this case its require.
