### ISSUE TITLE
[FEATURE] New API method to search dynamic analysis or static analysis by hash

### ISSUE THREAD

**Issue by IngeniaSeguridadInnovacion** [MobSF/Mobile-Security-Framework-MobSF#1571]
Hi,

I think that it will be good practice to project to create a new API method which allow us get a general information about a file like a analysis URL. It will require only one parameter (hash) because over time we forget other parameters such as relative file path or file type (View Source Files API). 
It will be good feature to integrate MobSF in a analysis malware environment

**Comment by ajinabraham** [comment]
Could you please elaborate? I did not clearly understand your enhancement request.

**Comment by ajinabraham** [comment]
Did you mean, the ability to view source without specifying  `type | apk/ipa/studio/eclipse/ios`?

**Comment by ajinabraham** [comment]
This should be possible. I can address this in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1572 where we guess the source directory locations.

**Comment by IngeniaSeguridadInnovacion** [comment]
Yes I can elaborate my idea. I would like to have an API method that allows me to send only a hash as a parameter. If that hash is in database, let it return url of analysis in web interface. If hash not exists, return a specific message. 
For example, Imagine that files continually arrive to me, and I automatically want to know if I already have that file in MobSF or I need to send it to analyze it. For this, I need to know through some API method if it is or not.

**Comment by ajinabraham** [comment]
`/api/v1/report_json` takes a hash and returns you the output. if it does not return anything then the file is not scanned.
`/api/v1/scans` gives you a list of hashes of files scanned by MobSF.

**Comment by IngeniaSeguridadInnovacion** [comment]
ok, thank you, this methods can help me, this will require more work in a API client, but resolve my problem. 
I appreciate your fast answer
