### ISSUE TITLE
Use extension to get file type

### ISSUE THREAD

**Issue by IngeniaSeguridadInnovacion** [MobSF/Mobile-Security-Framework-MobSF#1573]
I review API code and I found a error when extract a file type. 
This is a error, because you check if file has a specific extension to get a file type. I can change a extension and file is still same type. In malware, It is usually get this situation.

Its necesary check a magic number of file, It is usually in firsts bytes of file. 

- https://en.wikipedia.org/wiki/List_of_file_signatures

This error is locate in MobSF/views/helpers.py lines 27 to 41

**Comment by doroniz** [comment]
Someone is going to take care of it?

**Comment by doroniz** [comment]
Is there any update? Raz?

**Comment by ajinabraham** [comment]
Addressed.
