### ISSUE TITLE
[FEATURE] Dynamic Analysis on Prebuilt Docker Image

### ISSUE THREAD

**Issue by mike14u** [MobSF/Mobile-Security-Framework-MobSF#1577]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
There is no problem, I just would want to use the Static / Dynamic Analysis feature on the prebuilt Docker Image that we can pull

**Describe the solution you'd like**
Once the docker image has been pulled, it would contain both static / dynamic analysis

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ajinabraham** [comment]
We do not support Dynamic Analysis with docker officially. However it is possible and we made the docker image in such a way that it work out of the box.
https://dreher.in/posts/2020/may/28/mobsify-docker/
