### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by lfputnam** [MobSF/Mobile-Security-Framework-MobSF#1578]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masumiaban96** [comment]
This is Screenshot of my phone

**Comment by masumiaban96** [comment]
I can not update Android
 software
