### ISSUE TITLE
Daily/Weekly/Monthly Auto-remove uploaded APK's [FEATURE]

### ISSUE THREAD

**Issue by Natgho** [MobSF/Mobile-Security-Framework-MobSF#1580]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajinabraham** [comment]
Please use REST API to achieve this. We will not remove APK since some of our users need to perform dynamic analysis or rescan with a new version of MobSF etc. You will need the APK for that.

**Comment by masumiaban96** [comment]
http://localhost/?error=invalid_request&error_description=The%20provided%20request%20must%20include%20a%20%27response_type%27%20input%20parameter.

**Comment by masumiaban96** [comment]
This is my localhost address can you find hacker?

**Comment by masumiaban96** [comment]
Your Feedback: 



========================== 
Network Cell Info Lite (v.5.0.23)

Device: HUAWEI KSA-LX9 - Mt6761
Radio: MOLY.LR12A.R2.TC3.UNI.PR3.SP.V1.P29,MOLY.LR12A.R2.TC3.UNI.PR3.SP.V1.P29
Android: 9 (API 28) - KSA-L29 9.1.0.278(C185E2R5P1)
RAM total: 1.75 GB
RAM available/threshold/low: 504 MB / 144 MB / false
Screen size type: normal
Screen Real Size: 720x1520(px), 360 x 760(dp)
Screen Size: 720x1372(px), 360 x 686(dp)
Screen Size: 5.7"
DPI: 320 (xhdpi)
Density: 2.0, Scaled density: 2.0
Navigation keys: false
Soft keys ON: true

==========================

The following cell/signal/android information may help us improve further the response of the app for your device (if there are any issues).

Location access : true / enabled : true
Phone State access : true
Write access : true
WiFi State access : true
API : - |R true, true

Agree to save Map state : false
Agree to allow saving Logs : true
Agree to connect to DB : true
Show dialog again : false

Current Phone Type 1: GSM (1)
Current Phone Type 2: GSM (1)
World phone : false
Telephony: Yes
Voice call capable : true
Video call available : false
VoLTE available : false
WiFi calling available : false

Airplane Mode : false
Network : true-true / Type = 15 (HSPA+) |R 15 (HSPA+)
Data : Mobile

Cell (API 1) : false
-- getCellLocation = [33611,40146357,-1]
-- GSM - [33611,40146357,-1], loc: [33611,40146357,-1]
-- N size: null

Cell2 (API 1)
-- GSM - [33611,40146357,-1], loc: [33611,40146357,-1]

Cell (API 17) : 3 :: null
Neighbor dBm: RSSI (is RSCP: false:true-false)
CellList old change: false, false
CellList new change: true, false

-------------- API17 cell list ( 3 :: null ) --------------

YES,UMTS(1),43211,33611,40146357,334,3053,-105
NO,UMTS(1),43211,33611,40146357,334,3053,-105
NO,UMTS(1),43211,33611,40146354,334,3028,-107

O>

>CellInfoWcdma:{mRegistered=YES mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=1 CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=4 ber=19}
>CellInfoWcdma:{mRegistered=NO mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=0 CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=4 ber=19}

-------------- new cell list 1 [-2] (3) --------------
CellInfoWcdma:{mRegistered=YES mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=1 CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=4 ber=19}
CellInfoWcdma:{mRegistered=NO mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=0 CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=4 ber=19}
CellInfoWcdma:{mRegistered=NO mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=0 CellIdentityWcdma:{ mPsc=334 mUarfcn=3028 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=3 ber=13}

-------------- new cell list 2 [1] (3) --------------
CellInfoWcdma:{mRegistered=YES mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=1 CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=4 ber=19}
CellInfoWcdma:{mRegistered=NO mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=0 CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=4 ber=19}
CellInfoWcdma:{mRegistered=NO mTimeStampType=unknown mTimeStamp=0ns mCellConnectionStatus=0 CellIdentityWcdma:{ mPsc=334 mUarfcn=3028 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} CellSignalStrengthWcdma: ss=3 ber=13}

--------------1---------------
SIM1 ok : false
SIM1 state : 1 (Absent)
SIM1 service state : 0 (In-Service)

cellInfoList : 0 / 3
cellInfoListS = null

nNeighbors : 0
nNeighbors same : 0
nNeighbors data : -
isCDMA : false
isLTECDMA : false

--------------2---------------
noNetwork = false
Operator : IR-MCI
operatorID : 43211
SIM2 ok : true
SIM2 state : 5 (Ready)
SIM2 service state : 0 (In-Service)

cellInfoList : 3 / 3

nNeighbors2 : 2
nNeighbors same2 : 2
nNeighbors data2 : 1
isCDMA2 : false
isLTECDMA : false

S (1: 0: 0) - sim:1 (max:0) Ccase:2 O:1 - UARFCN = 3053 / BAND = 8(0) | Unknown/UMTS (0): 1 1 4 -105 -1000 | 102 0 -1 -1000 -1000 | 103 1 4 -105 -1000 | Cell: 432_11 / 40146357 / 334 | CellSignalStrengthWcdma: ss=4 ber=19 | orig. type 4a Unknown -> UMTS (UMTS) || CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} || [ Wcdma : 43211, 33611, 40146357, 334 ] ||
isRegistered: true | orig. type 5 UMTS -> HSPA+ (UMTS)

N (1: 1: #1) - sim:1 (max:1) Ccase:13 O:1 - UARFCN = 3053 / BAND = 8(0) | Unknown/UMTS (1): 1 1 4 -105 -1000 | Cell: 432_11 / 40146357 / 334 | CellSignalStrengthWcdma: ss=4 ber=19 || CellIdentityWcdma:{ mPsc=334 mUarfcn=3053 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} || [ Wcdma : 43211, 33611, 40146357, 334 ] ||
isRegistered: false

N (1: 2: #2) - sim:1 (max:1) Ccase:13 O:1 - UARFCN = 3028 / BAND = 8(0) | Unknown/UMTS (2): 1 1 3 -107 -1000 | Cell: 432_11 / 40146354 / 334 | CellSignalStrengthWcdma: ss=3 ber=13 || CellIdentityWcdma:{ mPsc=334 mUarfcn=3028 mMcc=432 mMnc=11 mAlphaLong=IR-TCI mAlphaShort=IR-TCI} || [ Wcdma : 43211, 33611, 40146354, 334 ] ||
isRegistered: false

--------------- sim(s) ----------------

HUAWEI KSA-LX9, en/en, API 28, tmMTK: null
Cell (API 17) : 3 :: null, SIs : 1 (1-2, 1-1, -21), (1)
Operator IDs: 43211, 

A: nSIMS(23) = 2, F: 2 >> SIM: false/true
B: nSIMS(23) = 2, F: 2 >> SIM: false/true
isMultiSimEnabled = true (function: true)
numServingCells(List) = 1 (-1 + 1)

Dual SIM Android: true
Use Dual SIM Mode: true
--show SIM: #2
Use WiFi Mode: false

SIM(tm): IR-MCI, 43211, networkType: 15 (HSPA+)
SIM state : 5 (Ready) -- Absent-Ready
SIM roaming : false
SIM data state : 2 (Data CONNECTED)
Notification (ON): HSPA+: 33611-40146357-334 :: B8 -- null

SIM1 state : 1 (Absent)
SIM1 service state : 0 (In-Service) | (R) : 0
SIM1 roaming : false
SIM1 active : false
SIM1 (0, -2): SignalStrength: -1 99 -1 -255 -1 255 255 99 2147483647 2147483647 2147483647 -1 0 2147483647 0 120 -97 -14 gsm|lte use_rsrp_and_rssnr_for_lte_level rscp [-128, -118, -108, -98] [-115, -105, -95, -85] 1 0 0 0 0 0
SIM1 VU: null
CellLocation1: [33611,40146357,-1]
GsmCellLocation1(p): (432/11) 33611, 40146357, -1 -- [33611,40146357,-1]
CellLocation1(N): [33611,40146357,-1] / NW: HSPA+
SIM1(r): empty list
SIM1(p): IR-MCI [IR-MCI], 43211 (MCC/MNC: 432/11), NW: 15 (HSPA+), Voice: 3 (UMTS), Data: 15 (HSPA+), LTE CA: --
SIM1(n): -, - (MCC/MNC: -1/-1), -, NW: 0 (Unknown), sigstr: Unknown
SIM1(f): -, - (MCC/MNC: -1/-1), -
*SubInfo SIM1: null
ServS: IR-MCI, 43211 (432,11), roaming: false, serv state: 0 -- [{mVoiceRegState=0(IN_SERVICE), mDataRegState=0(IN_SERVICE), mChannelNumber=2147483647, duplexMode()=0, mCellBandwidths=[], mVoiceRoamingType=home, mDataRoamingType=home, mVoiceOperatorAlphaLong=IR-MCI, mVoiceOperatorAlphaShort=IR-MCI, mDataOperatorAlphaLong=IR-MCI, mDataOperatorAlphaShort=IR-MCI, isManualNetworkSelection=false(automatic), mRilVoiceRadioTechnology=3(UMTS), mRilDataRadioTechnology=15(HSPAP), mCssIndicator=unsupported, mNetworkId=-1, mSystemId=-1, mCdmaRoamingIndicator=-1, mCdmaDefaultRoamingIndicator=-1, mIsEmergencyOnly=false, mIsDataRoamingFromRegistration=false, mIsUsingCarrierAggregation=false, mLteEarfcnRsrpBoost=0, mNetworkRegistrationStates=[NetworkRegistrationState{transportType=1 domain=PS regState=HOME accessNetworkTechnology=HSPA reasonForDenial=0 emergencyEnabled=false supportedServices=[I@4b55aed cellIdentity=CellIdentityWcdma:{ mPsc=-1 mUarfcn=2147483647 mMcc=432 mMnc=11 mAlphaLong=IR-MCI mAlphaShort=IR-MCI} voiceSpecificStates=null dataSpecificStates=DataSpecificRegistrationStates { mMaxDataCalls=1} nsaState=0}, NetworkRegistrationState{transportType=1 domain=CS regState=HOME accessNet

**Comment by masumiaban96** [comment]
Dear this text about feedback of nfc check

**Comment by masumiaban96** [comment]
If is possible for you send me some note for police because my information is senssetive
Best regards
