### ISSUE TITLE
[FEATURE] Dynamic analysis apk install error - disable verification of the APK during adb install

### ISSUE THREAD

**Issue by naebo** [MobSF/Mobile-Security-Framework-MobSF#1587]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
When trying to run dynamic analysis (using genymotion 10.0 - API29) - getting the error `[ERROR] 11/Nov/2020 09:17:35 - This APK cannot be installed. Is this APK compatible the Android VM/Emulator? adb install failed`

**Describe the solution you'd like**
Add extra set up instructions to docs/ or possibly a line that mobsf could run in setup script:

When trying to run dynamic analysis (using genymotion 10.0 - API29) I was getting the error 
`[ERROR] 11/Nov/2020 09:17:35 - This APK cannot be installed. Is this APK compatible the Android VM/Emulator? adb install failed `
which was odd because I could install and run the app from playstore.

To troubleshoot I tried to install directly with adb which failed with 
`❯ adb: failed to install base.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]`

Googled and turns out you need to disable verification of the APK during adb install, you can do this by running 
`adb shell settings put global verifier_verify_adb_installs 0`

**Comment by ajinabraham** [comment]
Fixed in latest master
