### ISSUE TITLE
Failure in building wheel for lief

### ISSUE THREAD

**Issue by mwanza-k** [MobSF/Mobile-Security-Framework-MobSF#1589]
ERROR: Command errored out with exit status 1:
   command: 'c:\users\kmmwanza\desktop\mobile-security-framework-mobsf\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kmmwanza\\AppData\\Local\\Temp\\pip-install-jz8bvd02\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\kmmwanza\\AppData\\Local\\Temp\\pip-install-jz8bvd02\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kmmwanza\AppData\Local\Temp\pip-wheel-5ieitza9'
       cwd: C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief\
  Complete output (86 lines):
  0.10.1
  running bdist_wheel
  running build
  running build_ext
  cmake C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief\build\temp.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\users\kmmwanza\desktop\mobile-security-framework-mobsf\venv\scripts\python.exe -DLIEF_PYTHON_API=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief\build\temp.win-amd64-3.9 -DLIEF_USE_CRT_RELEASE=MT -A x64
  -- Building for: Visual Studio 16 2019
  -- LIEF_CRT: /MT
  -- Using Release VC++ CRT: MT
  -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
  -- The C compiler identification is MSVC 19.28.29333.0
  -- The CXX compiler identification is MSVC 19.28.29333.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- LIEF 0.10.0
  -- ccache: ON
  -- Enable JSON support
  -- Enable Frozen (C++14 support)
  -- Number of parallel compiler jobs set to /MP
  -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
  -- Configuration Types: Debug;Release;MinSizeRel;RelWithDebInfo
  -- Build Types: Release
  -- Found PythonInterp: C:/Users/kmmwanza/Desktop/Mobile-Security-Framework-MobSF/venv/Scripts/python.exe (found suitable version "3.9", minimum required is "3.5")
  -- Found PythonLibs: C:/Program Files/Python39/libs/Python39.lib
  -- Python version: 3.5
  -- Python lib:     C:/Program Files/Python39/libs/Python39.lib
  -- Python include: C:/Program Files/Python39/include
  -- Python interpreter: C:/Users/kmmwanza/Desktop/Mobile-Security-Framework-MobSF/venv/Scripts/python.exe
  -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED
  -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED - Failed
  -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED
  -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED - Failed
  -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS
  -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Failed
  -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS
  -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Failed
  -- Performing Test HAS_ANSI
  -- Performing Test HAS_ANSI - Failed
  CMake Error at CMakeLists.txt:541 (add_subdirectory):
    add_subdirectory given source
    "C:/Users/kmmwanza/AppData/Local/Temp/pip-install-jz8bvd02/lief/package"
    which is not an existing directory.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/kmmwanza/AppData/Local/Temp/pip-install-jz8bvd02/lief/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/kmmwanza/AppData/Local/Temp/pip-install-jz8bvd02/lief/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief\setup.py", line 363, in <module>
      setup(
    File "c:\users\kmmwanza\desktop\mobile-security-framework-mobsf\venv\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\Python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files\Python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\kmmwanza\desktop\mobile-security-framework-mobsf\venv\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Program Files\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\Python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Program Files\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief\setup.py", line 78, in run
      self.build_extension(ext)
    File "C:\Users\kmmwanza\AppData\Local\Temp\pip-install-jz8bvd02\lief\setup.py", line 202, in build_extension
      subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
    File "C:\Program Files\Python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\kmmwanza\\AppData\\Local\\Temp\\pip-install-jz8bvd02\\lief', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\kmmwanza\\AppData\\Local\\Temp\\pip-install-jz8bvd02\\lief\\build\\temp.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\users\\kmmwanza\\desktop\\mobile-security-framework-mobsf\\venv\\scripts\\python.exe', '-DLIEF_PYTHON_API=on', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\kmmwanza\\AppData\\Local\\Temp\\pip-install-jz8bvd02\\lief\\build\\temp.win-amd64-3.9', '-DLIEF_USE_CRT_RELEASE=MT', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for lief

**Comment by ajinabraham** [comment]
Please use Python 3.7 as recommended in documentation

**Comment by ttimasdf** [comment]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1586#issuecomment-761566206
