### ISSUE TITLE
Lack of ability to View Source in browser in some cases until upstream EnlighterJS bug is fixed

### ISSUE THREAD

**Issue by nuschpl** [MobSF/Mobile-Security-Framework-MobSF#1603]
https://github.com/EnlighterJS/EnlighterJS/issues/144

**Comment by ajinabraham** [comment]
Waiting for upstream to cut a release. Tracked separately.

**Comment by nuschpl** [comment]
I doubt it's 'enhancment' I would call it regression as this used to work and now you can't use basic functionality due to fact syntax is colored. Can't we just revert this to work as before untill upstream fix ?

**Comment by ajinabraham** [comment]
This is out of our control, we switched to this library for the support of line numbers which the previous library has no support for. As it stands the maintainer of EnlighterJS has to release a fix or we are open to PR that could fix the issues while still providing all the existing features.

**Comment by anantshri** [comment]
faced this today.
mid way could be if enlighterjs error is detected then text is presented without the highlight. so usual smaller files work as is. any large file atleast gets listed minus all the funky bits. but i can understand in case @ajinabraham would like to wait for the upstream to fix it as it would probably only affect a small number of people.
