### ISSUE TITLE
Use multiple devices for dynamic testing

### ISSUE THREAD

**Issue by janzand** [MobSF/Mobile-Security-Framework-MobSF#1605]
Because too many people use it, sometimes the execution of dynamic tests will be slow or error will occur,  I want to extend this function to use multiple real mobile devices for dynamic testing

I have encountered some problems when using multiple devices for dynamic testing，adb always fails when multiple devices are running at the same time，such as：

subprocess.CalledProcessError: Command '['adb', '-s', '**LDYF00016423**', 'shell', 'tar', '-cvf', '/data/local/com.scope.myapplication1.tar', '/data/data/com.scope.myapplication1/']' returned non-zero exit status 1.

subprocess.CalledProcessError: Command '['adb', '-s', '**LDYF00016424**', 'shell', 'tar', '-cvf', '/data/local/com.scope.myapplication1.tar', '/data/data/com.scope.myapplication1/']' returned non-zero exit status 1.

If I only use one device, it's okay.Is this problem caused by adb or other reasons?

**Comment by ajinabraham** [comment]
We do not support multiple devices at a time for Dynamic Analysis in current  architecture. But we are open to pull requests.
