### ISSUE TITLE
IP Address disclosure 

### ISSUE THREAD

**Issue by XalfiE** [MobSF/Mobile-Security-Framework-MobSF#1606]
## ENVIRONMENT

```
OS and Version: Kali
Python Version: 2.7.18
MobSF Version: 3.1
```

## EXPLANATION OF THE ISSUE

```
Something seems to change on the IP Address disclosure scripts. On MobSF 3.0, I got more IPs detected under IP Address disclosure; on upgrading to 3.1 I got less IPs 
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Run static analysis on MobSF 3.0
2. Run Static Analysis on MobSF 3.1
3. Check differences under IP Address disclosure 

I could provide the APK on request.
```

**Comment by ajinabraham** [comment]
We have improved the detection regex to avoid some false positives and a redos vulnerability. That's might be the reson for this. If you could share an example of an IP that is not detected, I can take a look.

**Comment by XalfiE** [comment]
Thanks. I have sent APK to your e-mail

**Comment by ajinabraham** [comment]
Haven't got the APK yet

**Comment by ajinabraham** [comment]
Thanks for the APK.

**Comment by ajinabraham** [comment]
Closing as per comments on Slack

**Comment by XalfiE** [comment]
We could reopen as we seek solution?

**Comment by ajinabraham** [comment]
as per discussion over slack this looks like an issue

**Comment by ajinabraham** [comment]
Fixed in latest master
