### ISSUE TITLE
[Contributing] Integration of Library Detection & Analysis into MobSF

### ISSUE THREAD

**Issue by VainlyStrain** [MobSF/Mobile-Security-Framework-MobSF#1614]
Hi!

As we approach the final semester of our bachelor at Saarland University, a friend of mine and me are doing a project this semester. We have been assigned to integrate Android library detection & anaylsis techniques into a popular mobile security analysis tool.

We have chosen MobSF as framework, and will be integrating [LibScout](https://people.svv.lu/derr/publications/pdfs/derr_ccs16.pdf), as well as [LibID](https://github.com/ucam-cl-dtg/LibID) into the static analysis routine of MobSF.

As I like contributing to open source, I wanted to ask if you'd be interested in a pull request once work is finished.

Greetings!

**Comment by ajinabraham** [comment]
@VainlyStrain This sounds like a nice and useful feature addition and few people were requesting this in our support channel. If you would like to discuss, requires some support, pointers in integrating. Join the MobSF slack channel: https://mobsf.slack.com/join/shared_invite/enQtNzM2NTAyNzA1MjgxLTdjMzkzNDc3ZjdiMjkwZTZhMmFhNDlkZmMwZDhjNDNmYTAzYWE5NGZlMDIzYzliNTdiMDQ2MTRlYjU1MjkyNGM

Also please take a look at the contribution guidelines: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/.github/CONTRIBUTING.md

**Comment by ajinabraham** [comment]
closing this as it is a third party enchancement. Will be tracked separately.

**Comment by ajinabraham** [comment]
Related: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/303

**Comment by srikanthlogic** [comment]
Just noting here that a more recent / actively maintained project that is an alternative is 

https://github.com/zhaobozhen/LibChecker
