### ISSUE TITLE
MobSF labels custom android permissions and unknown permissions as "dangerous"

### ISSUE THREAD

**Issue by ajakka** [MobSF/Mobile-Security-Framework-MobSF#1617]
I have noticed in the static analysis report that mobsf treats custom permissions and unknown permissions as dangerous. This could be alarming to anyone looking at the report. 
I'd suggest that custom permissions have their own label "custom" as well as unknown be named "unknown".

Thank you.

**Comment by ajinabraham** [comment]
Fixed
