### ISSUE TITLE
Live API Monitor doesn't work

### ISSUE THREAD

**Issue by peter527** [MobSF/Mobile-Security-Framework-MobSF#1620]
## ENVIRONMENT

OS and Version: Ubuntu 16.04
Python Version: 3.8
MobSF Version: 3.1.8

## EXPLANATION OF THE ISSUE

No Response

![1](https://user-images.githubusercontent.com/10228410/101566339-c8a05700-3a09-11eb-8902-77b3b9f4a498.png)

![3](https://user-images.githubusercontent.com/10228410/101566347-cccc7480-3a09-11eb-866d-65c5eff775a9.png)

## STEPS TO REPRODUCE THE ISSUE

1. Start dynamic analysis
2. Start Instrumenttation
3. Click in Live API Monitor
4. Click APP like use it in a Phone

## LOG FILE

![2](https://user-images.githubusercontent.com/10228410/101566275-af97a600-3a09-11eb-82ac-b8bf13690bd3.png)

**Comment by ajinabraham** [comment]
Adddressed in slack.
