### ISSUE TITLE
Implement SARIF format for report export

### ISSUE THREAD

**Issue by damiencarol** [MobSF/Mobile-Security-Framework-MobSF#1624]
Our security collection tool has problems to load current JSON reports.

**Is your feature request related to a problem? Please describe.**
We want that MobSF provide a feature to generate report in SARIF format instead of custm JSON.
SARIF is a standard supported by OASIS. It's backed by Microsoft and a lot of tools from OWASP.

https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif
https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html#_Toc16012605

**Describe the solution you'd like**
A way to export reports in SARIF format instead of JSON.

**Describe alternatives you've considered**
Use current JSON reports but due to recent changes, some "import" features of our collection tool is broken.

**Additional context**
Having SARIF format export will make it easy to load it in GitHub as GitHub load this format natively (actions, etc...) 

**Usefull tools**

[Tools to validate reports](http://sarifweb.azurewebsites.net/Validation)
[Tool to view how the report render](https://microsoft.github.io/sarif-web-component/)

**Comment by ajinabraham** [comment]
I am familiar with SARIF, recently added it to one of the tool I maintain, njsscan.

The problem with MobSF Static Analysis  is that, it is more than a SAST in terms of the output it generates.  A lot of it cannot be represented using SARIF or not suitable in a typical SARIF output. So I don't think this will get added to MobSF anytime soon. But we are open to PRs.

**Comment by damiencarol** [comment]
@ajinabraham I'm pushing this kind of standard because we have some problems with the JSON format that we import in [DefectDojo](https://github.com/DefectDojo/django-DefectDojo).
It seems that they had some modifications that break the import code.
See:

-  [DefectDojo#3479 ](https://github.com/DefectDojo/django-DefectDojo/issues/3479)
-  [DefectDojo#3134](https://github.com/DefectDojo/django-DefectDojo/issues/3134)

**Comment by ajinabraham** [comment]
I can probably add a code analysis only SARIF export REST API, what is the info DefectDojo is looking for?
Would an output similar to `njsscan` (https://github.com/ajinabraham/njsscan ) with `--sarif` be sufficient for DefectDojo?

**Comment by damiencarol** [comment]
> Would an output similar to njsscan (https://github.com/ajinabraham/njsscan ) with --sarif be sufficient for DefectDojo?
Yes, I think.
I'm supporting the SARIF format for DefectDojo so, I will be able to provide you feedback and test+unit tests.
Also, I added URLs of useful tools like validator and viewer in the issue description.

**Comment by ajinabraham** [comment]
This is now available via mobsfscan https://github.com/marketplace/actions/mobsfscan

**Comment by damiencarol** [comment]
@ajinabraham took a look at `mobsfscan`, it awesome! Do you have some documentation about what is the differences between MobSF and mobsfscan?

**Comment by ajinabraham** [comment]
It focuses on the code aspect than binary.  Currently only supports Java/Kotlin/Objective C/Swift code, but will soon support manifest and property files.
