### ISSUE TITLE
How Can I build Docker Image for rpi4 ?

### ISSUE THREAD

**Issue by Malvik298** [MobSF/Mobile-Security-Framework-MobSF#1625]
I am trying to install normally using the setup.sh script with python 3.8 in kali 2020.4 but always stuck on lief error in rpi4. Installed successfully on kali2020.4-amd64 using same method. So I am now trying it with docker.
I already tried docker build with --platform argument but throws error at the end.
Do I need to change the Base Image ?

**Comment by ajinabraham** [comment]
@Malvik298 Assuming `rpi4` stands for Raspberry Pie. It uses ARM architecture and I am not sure if LIEF is targeted for ARM. You will have to reach out to that project to resolve this. This is out of our control.
