### ISSUE TITLE
PWD no longer works

### ISSUE THREAD

**Issue by ObscenityIB** [MobSF/Mobile-Security-Framework-MobSF#1631]
The PWD button to deploy the container says it doesn't have permission to mount something.
Manually opening port 8000 doesn't work since nothing is running.

**Comment by ajinabraham** [comment]
PWD is unstable these days due to heavy load. This is out of our control. Please reach out to PWD.

**Comment by ObscenityIB** [comment]
well PWD is the only option
since MobSF will not install on windows or linux

yara-python doesnt exist on windows or linux
linux has an error that python 3.9 is too new
bypassing the check says its missing a dependency for SOCKS support

the only thing that works was PWD until recently

**Comment by ObscenityIB** [comment]
libjpeg8-dev also doesnt exist, it is replaced by libjpeg62-turbo-dev

**Comment by ajinabraham** [comment]
You can take a look at our runners https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions/runs/451956471
on Ubuntu, Windows and Mac, on python <= 3.7 & < 3.9

**Comment by ObscenityIB** [comment]
so looking at this, looks like i have to install an old version of ubuntu, with an old version of python

ill try installing it and see if it works with the outdated software

**Comment by ajinabraham** [comment]
Where did you see an old version of Ubuntu? We are on the latest LTS version of Ubuntu (in GitHub actions)

You could install on the latest versions of Python, provided you can configure and install all the build dependencies of the project.

MobSF requires Python3 and can run on the latest. But some of the dependencies will not build gracefully by default. So you can choose to use a stable and supported version of Python like 3.8 for which you have prebuilt wheels available for most dependencies or use 3.9 and figure out issues with building dependencies.

**Comment by ajinabraham** [comment]
Or similar to PWD pull and run the latest docker image https://hub.docker.com/u/opensecurity and save time.

**Comment by ObscenityIB** [comment]
> Where did you see an old version of Ubuntu? We are on the latest LTS version of Ubuntu

Yes, LTS is the long term support release.

The latest stable release is 20.10
The version I use is 21.04
