### ISSUE TITLE
[FEATURE]When will Android API 30 be supported

### ISSUE THREAD

**Issue by lxzh** [MobSF/Mobile-Security-Framework-MobSF#1637]
WARNING:androguard.core.api_specific_resources:Requested API level 30 is larger than maximum we have, returning API level 28 instead.

**Comment by ajinabraham** [comment]
You might want to report this to androguard project. We use the latest version of androguard with MobSF.

**Comment by lxzh** [comment]
[androguard/issues#852](https://github.com/androguard/androguard/issues/852)
