### ISSUE TITLE
Frida dependency fails

### ISSUE THREAD

**Issue by javixeneize** [MobSF/Mobile-Security-Framework-MobSF#1638]
Hi

When installing frida as part of the setup process, it fails

    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

Apparently this is a common issue, that has a workaround - https://github.com/frida/frida/issues/1051 but maybe frida can come already packaged in the application?

**Comment by ajinabraham** [comment]
This is an issue at your end. You need to install the certificates for Python. See Requirements in Docs: https://mobsf.github.io/docs/#/requirements

Please use slack for support. Github issues are only for bug reports.
