### ISSUE TITLE
Create non root docker image [FEATURE]

### ISSUE THREAD

**Issue by javixeneize** [MobSF/Mobile-Security-Framework-MobSF#1639]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

It is not a good practise to run a docker image as root. It would be a good improvement to build this image with a lower privilege user, MobSF

**Comment by ajinabraham** [comment]
Some of the things we have in the container might complain about that. Feel free to send a PR otherwise, I will close this and track it as a low priority enhancement.
