### ISSUE TITLE
Need Update for support Python 3.9

### ISSUE THREAD

**Issue by zfirered** [MobSF/Mobile-Security-Framework-MobSF#1642]
so i can't install this mobsf because the update python 3.9

run the setup.sh and then asked me to install python3-venv <- this command automatically install python 3.9

already switch back to 3.8 but cannot run the setup.sh 

![image](https://user-images.githubusercontent.com/17750324/104269846-cd08d580-54c9-11eb-94f2-b4788955869e.png)

**Comment by ajinabraham** [comment]
Pluse use slack channel for support. You need to point `python3` to a version less than python 3.9.

**Comment by ajinabraham** [comment]
It's recommended to use pyenv to create isolated versions of python.
