### ISSUE TITLE
Error while running run.bat file

### ISSUE THREAD

**Issue by Ulpa-Makwana** [MobSF/Mobile-Security-Framework-MobSF#1655]
I completed the setup of the mobile security framework, but while running the run.bat file it shows me the error "The system cannot find the path specified." 

![image](https://user-images.githubusercontent.com/70023780/105449362-452b8400-5c9e-11eb-96ce-1a45bef738ab.png)

I added the path of mobsf into environmental variables too.

**Comment by ajinabraham** [comment]
Please make sure that you are on latest master, we fixed a bug recently.  Try running setup on latest master

**Comment by ajinabraham** [comment]
With that fix this issue is resolved. Feel free to comment otherwise.
