### ISSUE TITLE
Add a section in MobSF that clearly indicates SSL Pinning detection: Yes/No

### ISSUE THREAD

**Issue by aryanguenthner** [MobSF/Mobile-Security-Framework-MobSF#1659]
If you're requesting a new **feature**/enhancement, explain why you'd like it to be added and it's importance.

**Describe the solution you'd like**
The Static Report does not clearly call out the APP is using SSL Pinning.
Add a section in MobSF that clearly indicates SSL Pinning detection: Yes/No

**Additional context**
Thank you so much!!!!! This will help everyone and MobSF!

**Comment by ajinabraham** [comment]
We already have a rule for this. https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/9b059a39a7bcfb1b009c4c962d1309ff1d452a8b/mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml#L280
