### ISSUE TITLE
httptools UI URL is hardcoded to localhost

### ISSUE THREAD

**Issue by nelenkov** [MobSF/Mobile-Security-Framework-MobSF#1667]
## ENVIRONMENT

```
OS and Version: all
Python Version: all
MobSF Version: 3.3.0 Beta
```

## EXPLANATION OF THE ISSUE

```
httptools UI URL is hardcoded to `http://localhost:1337`, which obviously doesn't work if MobSF is deployed on a server, behind nginx, etc. LB.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py#L192

Suggest to at least make hostname configurable. 

Alternatively support deployment with docker-compose, include a proxy (Envoy, etc.) in the config and route appropriately.  
```
Relevant code:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py#L192

## STEPS TO REPRODUCE THE ISSUE

```
1. Open a dynamic analysis report
2. Click 'Start HTTPTools'
3. You get redirected to `http://localhost:1337/dashboard/<package name>`
Should be accessible via the public hostname/IP address.
```

**Comment by nelenkov** [comment]
Thanks for the fix. 

However this is not ideal, because it requires to expose the proxy port (1337) publicly. 

https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/18f4a483d361e704a795bea416f5eb968860b068#diff-0ae2698d1d487d67756a87835a45c4349158c5d9461cc89922a0101b453b1974R549

As it's not a standard port, it may be blocked or otherwise unavailable. Also it doesn't really work if MobSF is behind a load balancer or reverse proxy with authentication, etc. Backend scheme might be http://, but frontend https://, etc.

In my case the new code also ends up returning

```
https://127.0.0.1:1337/dashboard
```

It's not easy to provide for all uses case, but maybe introduce a config parameter and if not set use the default host/port?
Something like:

```
if config.http_tools_url is not None:
   return config.http_tools_url
else:
  
```

**Comment by ajinabraham** [comment]
The httptools webUI takes host name from request.get_host() and is supposed to be taking the same host ip as what MobSF is running on. Did your load balancer strip the real ip? httptools in proxy mode infact listens on `0.0.0.0:<port in settings.py>`.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/18f4a483d361e704a795bea416f5eb968860b068/mobsf/DynamicAnalyzer/tools/webproxy.py#L39

You could change that here https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/18f4a483d361e704a795bea416f5eb968860b068/mobsf/MobSF/settings.py#L319

**Comment by nelenkov** [comment]
You can't rely on the IP really, there might be multiple proxies before the request gets to MobSF.

It seems Django kind of provides a way to handle this by using the `HTTP_X_FORWARDED_HOST` setting.

Cf. https://docs.djangoproject.com/en/3.1/ref/request-response/#methods

But even that doesn't completely solve the problem, as the current code appends the httptools port, which we don't really want to make public. 

I am trying to see if this can be solved with some creative use of nginx config, but in any case it seems two 
separate URLs might be needed internally:

* one to start/stop http tools (fine to use localhost, as starting httptools on different host is not really supported)
* one to use as the redirect httptools dashboard

**Comment by nelenkov** [comment]
Something like this works with the following setup:

* nginx as reverse proxy, MobSF, httpproxy URL mapped accordingly (see below)
* `USE_X_FORWARDED_HOST = True` in `mobsf/MobSF/settings.py`

* dynamic_analyzer.py:
```
--- a/mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
+++ b/mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
@@ -191,7 +191,22 @@ def httptools_start(request):
             project = request.GET['project']
         else:
             project = ''
-        url = f'{httptools_url}/dashboard/{project}'
+
+        scheme = request.scheme
+        url = f'{scheme}://{httptools_url}/dashboard/{project}'
+
+        if 'X-Forwarded-For' in request.headers:
+            xff = request.headers['X-Forwarded-For']
+            if len(xff.split(',')) > 1:
+                # behind one or more reverse proxies
+                host = request.get_host()
+                redirect_host = request.get_host().split(':')[0]
+                url = f'{scheme}://{redirect_host}/dashboard/{project}'
+
          return HttpResponseRedirect(url)  # lgtm [py/reflective-xss]
```

* no changes to `/mobsf/MobSF/utils.py`

Other issues:
* there is no real pattern for mobsf/httptools URLs, some are similar/same, which makes it difficult to map in the reverse proxy. Something like this works:
```
location / {
                proxy_pass http://mobsf;
                proxy_read_timeout                  900;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host  $host:$server_port;
                proxy_redirect      off;
        }
        location /static/adminlte/ {
                proxy_pass http://mobsf;
                proxy_read_timeout                  900;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host  $host:$server_port;
                proxy_redirect      off;
        }
        location (/static/css/|/static/js/|/static/fonts/|/flow_meta){
                proxy_pass http://httptools;
                proxy_read_timeout                  900;
                proxy_redirect      off;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host  $host:$server_port;
        }
        location (^/dashboard/|^/repeat/|^/kill) {
                proxy_pass http://httptools;
                proxy_read_timeout                  900;
                proxy_redirect      off;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host  $host:$server_port;
        }
```
* killing and starting httptools each time is not very efficient, especially, when the same data is loaded. Maybe add a `/load?project=<...>` to httptools and don't reload if same as currently loaded project
* having httptools save captures in files makes it hard (and slow) to load, run in containers, etc. Should relatively simple to add DB storage as an option.

**Comment by ajinabraham** [comment]
Let me see what can be done here.

**Comment by nelenkov** [comment]
Having another look at this, the following might be better, as setting `USE_X_FORWARDED_HOST` affects the whole application and doesn't play well with the current httpproxy code:

```
--- a/mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
+++ b/mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
@@ -191,7 +191,23 @@ def httptools_start(request):
             project = request.GET['project']
         else:
             project = ''
-        url = f'{httptools_url}/dashboard/{project}'
+
+        scheme = request.scheme
+        url = f'{scheme}://{httptools_url}/dashboard/{project}'
+
+        if 'X-Forwarded-For' in request.headers:
+            xff = request.headers['X-Forwarded-For']
+            if len(xff.split(',')) > 1:
+                # behind one or more reverse proxies
+                host = request.headers['X-Forwarded-Host']
+                redirect_host = host.split(':')[0]
+                url = f'{scheme}://{redirect_host}/dashboard/{project}'
```

**Comment by nelenkov** [comment]
One more place where URL is hardcoded to 127.0.0.1. The port doesn't mach, and the exception is not handled, so this probably always fails:

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/DynamicAnalyzer/tools/webproxy.py#L27

**Comment by nelenkov** [comment]
After playing with this some more, it seems that most of this can be solved by:

* using `url = f'http://{settings.PROXY_IP}:{str(settings.PROXY_PORT)}'` for all proxy stop requests
* using X-Forwarded-Host for the redirect (as above)

If that makes sense I could submit a pull request + another one with working nginx config and systemd unit file.

**Comment by ajinabraham** [comment]
I am going to take a look again and come back with my observations.

**Comment by 720-462-9960** [comment]
![image](https://user-images.githubusercontent.com/86526799/123518137-c332f300-d661-11eb-98d9-46780f1ccb8c.png)

**Comment by ajinabraham** [comment]
Tracked separately.
