### ISSUE TITLE
Android Emulator [FEATURE]

### ISSUE THREAD

**Issue by Anu-bhav** [MobSF/Mobile-Security-Framework-MobSF#1668]
Hi @ajinabraham 

I modified the ```run.bat``` file so that it starts avd automatically.
I am also using anaconda environment.

```run.bat```:
```batch
@echo off
cmd /c D:\ProgramData\Anaconda3\Scripts\activate.bat MobSF
start "Android Emulator" /min cmd /k call "android_emulator.bat"

if [%1]==[] goto usage
SET conf=%1
goto :run
:usage
SET conf="0.0.0.0:8000"
:run
.\venv\Scripts\activate && waitress-serve --listen=%conf% --threads=10 --channel-timeout=3600 mobsf.MobSF.wsgi:application
```

```android_emulator.bat```:
```batch
@echo off
D:\Documents\Development\Android-AVD\Sdk\platform-tools\adb.exe start-server
set ANDROID_AVD_HOME=D:\Documents\Development\Android-AVD\.android\avd\
@REM D:\Documents\Development\Android-AVD\Sdk\emulator\emulator.exe -avd Pixel_XL_API_28 -port 5037 -writable-system -no-snapshot
D:\Documents\Development\Android-AVD\Sdk\emulator\emulator.exe -avd Pixel_XL_API_28 -writable-system -no-snapshot -dns-server 8.8.8.8 -netdelay none -netspeed full -wipe-data
```
The additional flags are to enable internet connection as I was having net issues with the avd.

**Comment by ajinabraham** [comment]
We let our users choose between Android Studio and Genymotion Emulators. There are a lot of variables here 
like `D:\Documents\Development\Android-AVD\Sdk\platform-tools\` or the name of the emulator `Pixel_XL_API_28`. So we do not want to ship anything from our side. The users can make scripts like this to simplify the process.
