### ISSUE TITLE
[FEATURE] Add Quark Engine as one of the static analyzers

### ISSUE THREAD

**Issue by 18z** [MobSF/Mobile-Security-Framework-MobSF#1674]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
I think it would nice to provide high risk activities detected in the malware analysis section.

**Describe the solution you'd like**
I propose to use [Quark Engine](https://github.com/quark-engine/quark-engine) as an overview of those high risk activities. We have experiences ([ghidraquark](https://github.com/quark-engine/ghidraquark), [APKLab](https://github.com/APKLab/APKLab)) developing a feature that when users click on one of the activity, the corresponding smali source codes are highlighted for manual verification. This boost up the speed for malware analyst.

**Describe alternatives you've considered**
So far, I haven't come up with other alternatives.

**Additional context**
Belows are features and reports released recently.
![ghidraquark](https://i.imgur.com/rfkOCSI.png")
![FB_IMG_1607307398565](https://user-images.githubusercontent.com/593954/101302495-b346f380-3876-11eb-8e9a-8f32b2ccccb1.jpg)
![FB_IMG_1607307385159](https://user-images.githubusercontent.com/593954/101302513-bfcb4c00-3876-11eb-987d-ec8b0f288f0b.jpg)

**Comment by ajinabraham** [comment]
Do you have a sample integration or docs for quark engine available?

**Comment by 18z** [comment]
hi @ajinabraham 

We'll be working on a sample integration for the next couple of weeks. 😸 

Yes, we do have docs but they are quite outdated though.
https://quark-engine.readthedocs.io/en/latest/

BTW, we'll be presenting quark engine at Blackhat Asia arsenal 2021 this May. 
Super excited about it !

**Comment by ajinabraham** [comment]
That will be really useful. 
Congrats and all the best for your BlackHat talk.

**Comment by ajinabraham** [comment]
Closing this for now. Will reopen once sample integration is available.

**Comment by notKnownn** [comment]
Is this finally added? I've seen they added a Quark analysis button to the tool but in mobSF.live it's not there
