### ISSUE TITLE
Possible Irregularities in Binary Scanning 

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#1680]
## ENVIRONMENT

```
OS and Version: Ubuntu Focal
Python Version: 3.9
MobSF Version: 3.3.1
```

## EXPLANATION OF THE ISSUE

IPA Symbols: https://mobsf.slack.com/archives/C0QMLNKMF/p1612370258071300
IPA Unrestricted segments: https://mobsf.slack.com/archives/C0QMLNKMF/p1612398771077200

Investigate binary analysis rules

## LOG FILE

```
Paste the contents of mobsf/debug.log here or attach the log file.
```

**Comment by akokare** [comment]
Hi @ajinabraham do we have any update on the validity of this finding/issue? Please let me know if I can answer any questions.

**Comment by ajinabraham** [comment]
@akokare Thanks for looking into this.

Regarding symbols, the recommendation is taken from OWASP MSTG: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06i-Testing-Code-Quality-and-Build-Settings.md#static-analysis-1

> Make sure that debugging symbols are stripped when the application is being built for production. Stripping debugging symbols will reduce the size of the binary and increase the difficulty of reverse engineering. To strip debugging symbols, set Strip Debug Symbols During Copy to YES via the project's build settings.

But it looks like `DEPLOYMENT_POSTPROCESSING` is relevant. The latest MobSF (3.3.3) will recommend that and `Strip Linked Product` as well.

Regarding `restricted segments`, you are right it looks like iOS apps need it. The category is removed.
