### ISSUE TITLE
Unable to upload Android source code zipped on a Mac

### ISSUE THREAD

**Issue by timtraversy** [MobSF/Mobile-Security-Framework-MobSF#1682]
## ENVIRONMENT

```
OS and Version: macOS 11.2.1
Python Version: Using latest docker image 
MobSF Version: v3.2.9 Beta
```

## EXPLANATION OF THE ISSUE

I'm unable to upload Android source code when I zip it on my Mac. You can reproduce this using your own test files (see below).

Macs seems to use a different compression program that is incompatible with what MobSF is expecting.

## STEPS TO REPRODUCE THE ISSUE

1. Run MobSF on a Mac.
2. Download the Android source test file: https://github.com/MobSF/test_files/blob/master/android_src.zip
3. Uncompress the file and then re-compress it.
4. Try uploading this new zip file - you get the. error `This ZIP Format is not supported`
5. Try uploading the original zip file - it works fine.

## LOG FILE

```
[INFO] 24/Feb/2021 19:37:12 - MIME Type: application/zip FILE: android_src 2.zip
[INFO] 24/Feb/2021 19:37:13 - Performing Static Analysis of Android/iOS Source Code
[INFO] 24/Feb/2021 19:37:13 - Starting Analysis on : android_src 2.zip
[INFO] 24/Feb/2021 19:37:13 - Extracting ZIP
[INFO] 24/Feb/2021 19:37:13 - Unzipping
[INFO] 24/Feb/2021 19:37:14 - Checking for ZIP Validity and Mode
[INFO] 24/Feb/2021 19:37:14 - Getting Hardcoded Certificates/Keystores
[INFO] 24/Feb/2021 19:37:14 - ZIP Type - 
[ERROR] 24/Feb/2021 19:37:14 - This ZIP Format is not supported
```

**Comment by ajinabraham** [comment]
This works fine for me on macOS Catalina. You are probably not generating the zip from within the root directory.
Please use MobSF slack channel for support.

**Comment by ajinabraham** [comment]
Also tested on BigSur 11.2.1

**Comment by timtraversy** [comment]
You don't see this?
Uploading Invalid ZIP.mov…

**Comment by timtraversy** [comment]
You don't see this?

https://user-images.githubusercontent.com/21370530/109068271-9bd11700-76bd-11eb-9a33-0ceb72ed9529.mov

**Comment by ajinabraham** [comment]
You are doing it incorrectly, MobSF needs the zip to be created from inside the root directory.

* Open the directory
* Select all files
* Create a Zip

**Comment by timtraversy** [comment]
Ohhh - thanks for the advice, I didn't think of that.
