### ISSUE TITLE
Error Installing with linux 

### ISSUE THREAD

**Issue by MahmoudMabrok** [MobSF/Mobile-Security-Framework-MobSF#1691]
![Screenshot from 2021-03-09 18-04-24](https://user-images.githubusercontent.com/13488900/110504563-f464d300-8105-11eb-8a21-ef3febe024d3.png)
i got this 
```
ERROR: Could not find a version that satisfies the requirement mitmproxy>=6.0.0<=6.0.2 (from http-tools)
ERROR: No matching distribution found for mitmproxy>=6.0.0<=6.0.2
![Screenshot from 2021-03-09 18-04-24](https://user-images.githubusercontent.com/13488900/110500488-eb720280-8101-11eb-96e6-1de7d30c2b97.png)

```

**Comment by MahmoudMabrok** [comment]
@ajinabraham  why it is closed? 
could i ask at another place or need more data ?

**Comment by ajinabraham** [comment]
Please use MobSF slack channel for support

**Comment by MahmoudMabrok** [comment]
ok

**Comment by hwangjr** [comment]
I fix this issue by:
1. update mitm proxy to 6.0.2

**Comment by MahmoudMabrok** [comment]
@hwangjr  how to do this update of mitm

**Comment by hwangjr** [comment]
@MahmoudMabrok  I use mac os, so just use brew:
```
brew upgrade mitmproxy
```
for linux, this doc may help you:
```
https://docs.mitmproxy.org/stable/overview-installation/#linux
```
