### ISSUE TITLE
[UX] Sticky horizontal scrollbar in code/xml views

### ISSUE THREAD

**Issue by serkonda7** [MobSF/Mobile-Security-Framework-MobSF#1693]
**Is your feature request related to a problem? Please describe.**
When some lines exceed the viewport width inside the source and smali code views or the Manifest XML view, a horizontal scrollbar is shown.
The problem is, it's all at the bottom of the view which forces the user to scroll all way down to adjust the horizontal scroll.
This interrupts the workflow and is distracting because you have to guess what width is needed to view a specific part of the line.

**Describe the solution you'd like**
The horizontal scrollbar might be set to stick at the page bottom if it would be outside the viewport otherwise.

**Comment by ajinabraham** [comment]
Can you share a GIF or Video to explain the issue?

**Comment by ajinabraham** [comment]
Tracked Separately

**Comment by serkonda7** [comment]
![no_scrollbar](https://user-images.githubusercontent.com/40118727/110915910-86dcc080-8318-11eb-8d85-59cfc3ac7da8.gif)
