### ISSUE TITLE
Static Analyzer/Android: PIE check is incorrect

### ISSUE THREAD

**Issue by mkshr31** [MobSF/Mobile-Security-Framework-MobSF#1694]
## ENVIRONMENT

From v3.3.3 Dockerfile
```
OS and Version: Ubuntu 20.04
Python Version: 3.8
MobSF Version: v3.3.3
```

## EXPLANATION OF THE ISSUE

MobSF uses LIEF to do the ELF analysis of Android Shared Objects (i.e. libs/*.so). LIEF's method is_pie() is used and checks for file type ET_DYN (which is correct) and the existence of a segment type PT_INTERP (which is reserved for executables and not used for shared objects): https://github.com/lief-project/LIEF/blob/master/src/ELF/Binary.cpp#L1161

This causes all shared objects to be marked with a PIE = False flag.

## STEPS TO REPRODUCE THE ISSUE

Take any APK that contains some lib/\*/\*.so (e.g. https://m.apkpure.com/de/flutter-gallery/io.flutter.demo.gallery) und run against MobSF.
All shared objects are marked as PIE = False.

**Comment by ajinabraham** [comment]
This is already tracked here https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1676
