### ISSUE TITLE
Wrong version in the changelog

### ISSUE THREAD

**Issue by saikat056** [MobSF/Mobile-Security-Framework-MobSF#1695]
@ajinabraham: I was looking into the latest MobSF [version](https://github.com/MobSF/Mobile-Security-Framework-MobSF/releases/tag/v3.3.3). Looks like the version specified in the changelog is not correct. Please correct me if I am wrong.

<img width="589" alt="Screen Shot 2021-03-11 at 11 49 22 AM" src="https://user-images.githubusercontent.com/1566651/110839063-694c2000-8260-11eb-9741-2f57945ff8a7.png">

**Comment by ajinabraham** [comment]
Thanks for pointing out.I just fixed this.
