### ISSUE TITLE
Dynamic analysis fails if there are two scan for same binary

### ISSUE THREAD

**Issue by nelenkov** [MobSF/Mobile-Security-Framework-MobSF#1700]
## ENVIRONMENT

```
OS and Version: Linux 
Python Version: 3.9
MobSF Version: v3.3.4 Beta
```

## EXPLANATION OF THE ISSUE

```
When there is more than one scan with the same MD5 (same APK scanned twice, etc.), 
trying to start dynamic analysis fails with the undescriptive `Invalid parameters` message. 
The cause seems to be this code to get the package name from MD5. Django OR throws a 
`MultipleObjectsReturned` exception which is being silently swallowed.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/DynamicAnalyzer/views/android/operations.py#L31-L38
```

Suggested fix:

1. Don't use the MD5, but the DB ID to refer to scans.
2. (quick fix) Change `get_package_name()` to return package name even if more than one matching record (should be the same for equal package hashes)

## STEPS TO REPRODUCE THE ISSUE

```
1. Scan the same APK twice
2. Try to start dynamic analysis from static analysis page
```

## LOG FILE

```
Paste the contents of mobsf/debug.log here or attach the log file.
```

**Comment by ajinabraham** [comment]
A scan result is always tied to a single MD5 hash. You can't have more than one scan result with the same MD5 in DB.
How are you seeing more than one occurrence?

**Comment by nelenkov** [comment]
This has happened quite a few times, so definitely possible. Could have something to do with scans timing out and the same scan being recreated as a new record.

**Comment by ajinabraham** [comment]
I haven't seen this before with the default setup we have. The db entry is created once and updated if rescan parameter is provided. So the logic is always to have one MD5 associated with a single scan.

 Do you have multiple workers running or something that might be causing a race condition?
if you can share steps to reproduce, it will be useful. Also can you share the output of scans API showing multiple results for same MD5?

**Comment by nelenkov** [comment]
I think it may be because the request times out at the LB, sending the same requests, triggers the same scan. 
I'll try to reproduce and post some logs.

In any case, might be good to decouple the scan from the Web request with a job queue or something.

**Comment by nelenkov** [comment]
Here it is:

```mobsf=> select id,"MD5" from "StaticAnalyzer_staticanalyzerandroid" where "MD5"='85ef4553994b3594bd9f29f7b0285057';
 id |               MD5                
----+----------------------------------
 59 | 85ef4553994b3594bd9f29f7b0285057
 60 | 85ef4553994b3594bd9f29f7b0285057
 61 | 85ef4553994b3594bd9f29f7b0285057
 62 | 85ef4553994b3594bd9f29f7b0285057
(4 rows)

mobsf=> select id,"MD5" from "StaticAnalyzer_recentscansdb" where "MD5"='85ef4553994b3594bd9f29f7b0285057';
 id |               MD5                
----+----------------------------------
 55 | 85ef4553994b3594bd9f29f7b0285057
(1 row)
```

How to reproduce:

1. Start analysis
2. Request times out
3. Press refresh
4. (alternatively) Go to recent scans, press 'Static report' which trigger scan.

Could probably also happen if another user uploads the same file while a scan is under way.

To have full multi-user support, will probably need to rename directories also (probably needs a new ticket), but maybe we can fix this issue in the mean time.

**Comment by nelenkov** [comment]
Here's the trace if you try to start dynamic analysis (added some logging):

```
[INFO] 16/Mar/2021 12:23:55 - Creating Dynamic Analysis Environment
[DEBUG] 16/Mar/2021 12:23:55 - checksum: 85ef4553994b3594bd9f29f7b0285057
[DEBUG] 16/Mar/2021 12:23:55 - all scans: <QuerySet [<StaticAnalyzerAndroid: StaticAnalyzerAndroid object (59)>, <StaticAnalyzerAndroid: StaticAnalyzerAndroid object (60)>, <StaticAnalyzerAndroid: StaticAnalyzerAndroid object (61)>, <StaticAnalyzerAndroid: StaticAnalyzerAndroid object (62)>]>
[WARNING] 16/Mar/2021 12:23:55 - get() returned more than one StaticAnalyzerAndroid -- it returned 4!
[DEBUG] 16/Mar/2021 12:23:55 - None
[ERROR] 16/Mar/2021 12:23:55 - Invalid Parameters
[ERROR] 16/Mar/2021 12:23:55 - Internal Server Error: /android_dynamic/85ef4553994b3594bd9f29f7b0285057
```[INFO] 16/Mar/2021 12:23:55 - Creating Dynamic Analysis Environment
[DEBUG] 16/Mar/2021 12:23:55 - checksum: 85ef4553994b3594bd9f29f7b0285057
[DEBUG] 16/Mar/2021 12:23:55 - all scans: <QuerySet [<StaticAnalyzerAndroid: StaticAnalyzerAndroid object (59)>, <StaticAnalyzerAndroid: StaticAnalyzerAndroid object (60)>, <StaticAnalyzerAndroid: StaticAnalyzerAndroid object (61)>, <StaticAnalyzerAndroid: StaticAnalyzerAndroid object (62)>]>
[WARNING] 16/Mar/2021 12:23:55 - get() returned more than one StaticAnalyzerAndroid -- it returned 4!
[DEBUG] 16/Mar/2021 12:23:55 - None
[ERROR] 16/Mar/2021 12:23:55 - Invalid Parameters
[ERROR] 16/Mar/2021 12:23:55 - Internal Server Error: /android_dynamic/85ef4553994b3594bd9f29f7b0285057

**Comment by ajinabraham** [comment]
I couldn't reproduce this on a non-load balancer setup, however, I have added a guard rail code to prevent multiple occurrences of the same scan hash in the latest master. (3.3.5)

**Comment by nelenkov** [comment]
Thanks!. I'll try it out and report back if it reoccurs.
