### ISSUE TITLE
[FEATURE] Ability to provide false positive list to remove/mark them in the report.

### ISSUE THREAD

**Issue by alexiscaruana** [MobSF/Mobile-Security-Framework-MobSF#1704]
We use MobSF to analyze Android and IOS applications.

Currently, we are facing a lot of false positive issues and only few true positive issues.

At the end, the report score and content make less sense to be analyzed with all the false positives.

We expect to have a way to determine automatically the false positive from a provided input list.
With this information, the report should be able to mark as false positive or hide these issues.

**Comment by alexiscaruana** [comment]
@neerajnigam-se

**Comment by ajinabraham** [comment]
Duplicate of #1189

**Comment by ajinabraham** [comment]
Low priority enhancements are tracked here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/264
