### ISSUE TITLE
[FEATURE] What is the maximum size of an APK file that can be uploaded?

### ISSUE THREAD

**Issue by lxzh** [MobSF/Mobile-Security-Framework-MobSF#1705]
What is the maximum size of an APK file that can be uploaded? Nowadays an APK is often several hundred megabytes. Now I test an APK with more than 20 megabytes, and it always fails to upload

**Comment by ajinabraham** [comment]
By default it's 256 MB. https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/da1dbeb448f78493ad14a23585e0b93ef1747f73/mobsf/MobSF/settings.py#L208
Please use slack for discussion

**Comment by lxzh** [comment]
But this upload function always fails when uploading APK of more than 20 megabytes.
![image](https://user-images.githubusercontent.com/4122619/112572262-c3ceaa00-8e24-11eb-8399-00b3146ffc6f.png)
![image](https://user-images.githubusercontent.com/4122619/112572353-faa4c000-8e24-11eb-9613-a262af4a47dd.png)
