### ISSUE TITLE
Remove .so files from security scan 

### ISSUE THREAD

**Issue by AndyKD** [MobSF/Mobile-Security-Framework-MobSF#1706]
Hi Ajin,

I am looking for your support on my query, this will really save my day from going into deeper.

We are developing our application using ReactNative and we have used some 3rd party libraries. That frameworks are adding default .so files.

When we are doing a security scan over the .apk file generated from react native code that is showing lot of security warning, 

Is there a way we can ignore .so files from security scan? or not include the .so files before static security scan?

Help from your side would be really appreciated.

Thanks in advance..

**Comment by ajinabraham** [comment]
Please use slack channel for support
