### ISSUE TITLE
long time hang at "pip is looking at multiple versions of chardet"

### ISSUE THREAD

**Issue by elig0n** [MobSF/Mobile-Security-Framework-MobSF#1721]
## ENVIRONMENT

```
OS and Version: Linux and Windows
Python Version: 3.9.4
MobSF Version: Git
```

## EXPLANATION OF THE ISSUE
When running setup.bat or setup.sh pip would provide the following message and stop producing output for a long time (hours). I had an instance where after leaving it on for 24 hours I would see it finished.

```
INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
```

I have noticed this "multiple version looking" happen with other packages as well but chardet seems to be the longest. I hope there is a way to shorten all of this.

**Comment by elig0n** [comment]
Also see: https://github.com/pypa/pip/issues/8713

**Comment by ajinabraham** [comment]
Hi @elig0n this is a known issue and our setup scripts are updated to use the legacy resolver for the time being. Please pull the latest master and try running setup again.

**Comment by elig0n** [comment]
@ajinabraham Are both windows and nix setup scripts updated ?
Can you point to the relevant commits ?

This is also happening for the certifi package.

**Comment by ajinabraham** [comment]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/e0f1f7e7b30456988ad90179fc820e80a52874ad/setup.sh#L62

There is similar change for windows as well. We also have automated cross platform tests running against each commit.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions/workflows/mobsf_test.yml
