### ISSUE TITLE
[FEATURE] Split APK support

### ISSUE THREAD

**Issue by ObscenityIB** [MobSF/Mobile-Security-Framework-MobSF#1728]
Suggestion for supporting `.apks` files.

A split apk is a newer application that is broken up into multiple apk files, legacy apk tools cannot install these, specific split apk installers are required, such as the google play store.

Attempting to install only part of the split apk will produce an error in the system package manager.

An `.apks` file is a compressed file containing a list of files as such:

`icon.png` - The application icon
`base.apk` - The main application
`split_config.arm64_v8a.apk` - Contains libraries for the supported arch, may be named differently
`split_config.xxhdpi.apk` - Contains UI elements and resources for the supported graphics options

Currently, trying to use such a file in MobSF, even renamed, is not supported.

**Comment by ajinabraham** [comment]
We support the `.xapk` split APK format. For every thing else, your best bet is to install the split APK to a device using adb or other installers and let MobSF download the APK and do a static analysis from the Dynamic Analysis View. This is supported from V3.4.3

**Comment by ajinabraham** [comment]
Quick update. We will also support `.apks` file from 3.4.4 onwards.

**Comment by epaphrasmakoko** [comment]
Still i don't understand, if it's a feature enhancement, why i dont i see this in the Documentation of mobsf. 
how do we perform dynamic analysis from the split application in mobsf as you stated its already added
