### ISSUE TITLE
Some ipa package stuck in the MACHO analysis phase

### ISSUE THREAD

**Issue by MrLeeSr** [MobSF/Mobile-Security-Framework-MobSF#1734]
some ipa file got this , 
[2021-05-17 05:03:40 PM-macho_analysis.py-INFO:Running MachO Analysis on ***]

To be precise ， it stuck in macho_analysis.py  'self.macho = lief.parse(macho.as_posix())' .

i'm using python3.9 and lief == 0.11.4

**Comment by ajinabraham** [comment]
@MrLeeSr Please share the IPA for troubleshooting this.

**Comment by MrLeeSr** [comment]
I put the file in this repository . [link](https://github.com/MrLeeSr/testIpa)

**Comment by ajinabraham** [comment]
Looks like a really large IPA. I think it's a LIEF issue.
You might want to report to https://github.com/lief-project/LIEF

**Comment by MrLeeSr** [comment]
Got it , thanks

**Comment by ajinabraham** [comment]
Closing this as it affects a third-party component.
