### ISSUE TITLE
Unable to Scan APK using docker at Mac M1

### ISSUE THREAD

**Issue by kaleb-g** [MobSF/Mobile-Security-Framework-MobSF#1735]
## ENVIRONMENT

```
OS and Version: Big Sur 11.3.1 Mac M1
Python Version: 3.8.10
MobSF Version: 3.4.4
```

## EXPLANATION OF THE ISSUE

```
After trying to run the command docker there was a warning "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"  then I tried to scan an APK using the docker on my Mac M1. but an error stating "Error Inappropriate argument type cannot unpack non-iterable NoneType object" .The APK I'm trying to scan is the DIVAv2.  
```
## STEPS TO REPRODUCE THE ISSUE

```
1. docker pull opensecurity/mobile-security-framework-mobsf
2. docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
3. Upload the DIVA Apk.
```

## LOG FILE
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[INFO] 21/May/2021 17:16:16 - Converting AXML to XML
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[ERROR] 21/May/2021 17:16:18 - Getting Manifest file
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 905, in get_manifest_apk
    subprocess.check_output(args)  # lgtm [py/command-line-injection] md5 hash
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/jdk-12/bin/java', '-jar', '/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.5.0.jar', '--match-original', '--frame-path', '/tmp', '-f', '-s', 'd', '/root/.MobSF/uploads/a6d8abdfe911ac24460a4939820ea74d/a6d8abdfe911ac24460a4939820ea74d.apk', '-o', '/root/.MobSF/uploads/a6d8abdfe911ac24460a4939820ea74d/apktool_out']' died with <Signals.SIGSEGV: 11>.
[ERROR] 21/May/2021 17:16:18 - Parsing Manifest file
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/usr/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 21/May/2021 17:16:18 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 158, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 21/May/2021 17:16:18 - cannot unpack non-iterable NoneType object
[ERROR] 21/May/2021 17:16:18 - Internal Server Error: /static_analyzer/

Hoping for your kind answer. Thanks!

**Comment by 7500** [comment]
This issue is reported multiple times, I have the same issue and it seems to be a bug as the same apk can be scanned with x86 processors.

I found similar issues closed without a workaround with search. Also haven‘t found a solution at Slack.

It seems to be related with m1 and docker.

If there is a workaround, can somebody please post a fix?

**Comment by muuuh** [comment]
Same issue here, didn't found a solution at Slack. Seems to work according to Slack without Docker, but I think this is not do great.

**Comment by kaleb-g** [comment]
Hey @muuuh I also tried using the command where it errors, the commands work btw.

**Comment by ajinabraham** [comment]
Docker on M1 has issues running  MobSF.
```
subprocess.CalledProcessError: Command '['/jdk-12/bin/java', '-jar', '/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.5.0.jar', '--match-original', '--frame-path', '/tmp', '-f', '-s', 'd', '/root/.MobSF/uploads/a6d8abdfe911ac24460a4939820ea74d/a6d8abdfe911ac24460a4939820ea74d.apk', '-o', '/root/.MobSF/uploads/a6d8abdfe911ac24460a4939820ea74d/apktool_out']' died with <Signals.SIGSEGV: 11>
```
The exception occurs in 3rd party tool. We won’t  be able to support until Docker can handle this.

Alternatively you could setup MobSF on host or on a VM.

**Comment by ajinabraham** [comment]
@kaleb-g We recently published a arm compatible image
Again, not tested on M1 macs, but worth a try
`docker pull opensecurity/mobile-security-framework-mobsf:arm`

**Comment by kaleb-g** [comment]
Cool!. trying it now.

**Comment by kaleb-g** [comment]
@ajinabraham it's working now! thanks! a great tool as always!
