### ISSUE TITLE
Docker build fails with settings.py no such file or directory.

### ISSUE THREAD

**Issue by cryptax** [MobSF/Mobile-Security-Framework-MobSF#1737]
## ENVIRONMENT

```
OS and Version: Linux Mint Ulyssa
Python Version: 3.8.5
MobSF Version: 3.4.4 beta
```

## EXPLANATION OF THE ISSUE

Building the docker container with `docker-compose build` fails with the following error:

```
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.8.6
sed: can't read ../mobsf/MobSF/settings.py: No such file or directory
ERROR: Service 'mobsf' failed to build: The command '/bin/sh -c ./scripts/postgres_support.sh $POSTGRES' returned a non-zero code: 2
``` 

This is because you run `postgres_support.sh` from `.` in the Dockerfile `RUN ./scripts/postgres_support.sh ` in the Dockerfile, while the scripts assumes it is run from `./scripts`. I will issue a merge request fixing this soon.

**Comment by ajinabraham** [comment]
Fixed
