### ISSUE TITLE
[Enhancement] Add ARM64 Docker Images

### ISSUE THREAD

**Issue by fire1ce** [MobSF/Mobile-Security-Framework-MobSF#1739]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
All the docker images are x86

**Describe the solution you'd like**
Add ARM64 Docker Images for MobSF

**Comment by ajinabraham** [comment]
Hi @fire1ce This is already available with `arm` tag https://mobsf.github.io/docs/#/docker
