### ISSUE TITLE
[FEATURE] IOS - Hardcoded secrets in info.plist

### ISSUE THREAD

**Issue by RangeardL** [MobSF/Mobile-Security-Framework-MobSF#1742]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Add a "Hardcoded secret" field who is a filter on the plist file which is a well known security flaw.
This would add more details to the IOS report and help while automating.

**Describe the solution you'd like**
I have already implemented it for my personal use and am ready to do the PR
You can find it in this branch: https://github.com/Na4aX/Mobile-Security-Framework-MobSF/tree/plist-secrets

**Comment by ajinabraham** [comment]
Hi @RangeardL,

This is great. I made a PR to upstream from your fork.

**Comment by ajinabraham** [comment]
Addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1769
