### ISSUE TITLE
[FEATURE] Why 

### ISSUE THREAD

**Issue by mbiamont** [MobSF/Mobile-Security-Framework-MobSF#1746]
**Is your feature request related to a problem? Please describe.**
Hello 👋 ,

I would like to know why you consider a security issue the usage of functions like `memcpy()` or `strlen()` in an iOS build?
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/StaticAnalyzer/views/ios/rules/ipa_rules.py

According to the Internet, the `_s` functions are "a bad idea to use" and are not suitable for a non-Microsoft project.

![image](https://user-images.githubusercontent.com/4358453/121723922-6d017400-cae7-11eb-89c0-33233daa214e.png)
Source: https://stackoverflow.com/questions/870019/memcpy-in-secure-programming 

![image](https://user-images.githubusercontent.com/4358453/121723944-71c62800-cae7-11eb-9345-0e207e88a560.png)
Source: https://www.reddit.com/r/learnprogramming/comments/5uq1sl/c_language_replace_memcpy_with_memcpy_s_i_cant/

For example, I use `memcpy()` in my project written in C and used in an iOS project. But except by re-writing the function by hand, I didn't found other alternatives.

**Describe the solution you'd like**
Either remove this rule, either provide a concrete solution

**Describe alternatives you've considered**
Re-write those functions by hand (which can result in more bugs than originated).

**Additional context**
N/A

**Comment by ajinabraham** [comment]
In general these rules are sourced from

https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

`memcpy()` is not unsafe if used with proper bound checking and or compiler flags.
similarly for `strlen()`, see:  https://rules.sonarsource.com/objective-c/RSPEC-5813

These are false positives if the said functions are implemented securely. The implementation details is not available from a IPA binary, but only the function name. Hence MobSF will flag the functions are found in the symbols.

**Comment by mbiamont** [comment]
Hi @ajinabraham,

I agree with you (and Apple) that used badly, those functions can be unsafe.

But the problem is that my client disapproves my library because MobSF considered these functions as insecure; which is not really the case, it just depends on the usage we make of them.

Also, avoiding the usage of these functions incites to re-write them manually which can cause more troubles than using the original API. What do you think?

**Comment by mbiamont** [comment]
Hi @ajinabraham ,

Another question related to this issue:
I see in the Apple doc:

> -D_FORTIFY_SOURCE—Adds additional static and dynamic bounds checking to a number of functions that normally provide none (sprintf, vsprintf, snprintf, vsnprintf, memcpy, mempcpy, memmove, memset, strcpy, stpcpy, strncpy, strcat and strncat). If set to level 1 (-D_FORTIFY_SOURCE=1), only compile-time checking is performed. Level 1 is enabled by default when compiling for macOS 10.6 and later. At level 2, additional run-time checking is performed.

So, if used (which is the case by default) shouldn't it cover MobSF issue report?

Thanks in advance for your support 🙏

**Comment by ajinabraham** [comment]
@mbiamont Please use our slack channel for discussions.
