### ISSUE TITLE
[FEATURE]setup.sh run in ubuntu 20.04 will report venv error

### ISSUE THREAD

**Issue by HughLu** [MobSF/Mobile-Security-Framework-MobSF#1758]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
run setup.sh
[error info]
[200~[INSTALL] Using python virtualenv
Error: Command '['Mobile-Security-Framework-MobSF/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
[ERROR] Failed to create virtualenv. Please install MobSF requirements mentioned in Documentation.

** solve ***
I change the setup.sh
# python3 -m venv ./venv
virtualenv -p /usr/bin/python3 --no-site-packages venv

**Comment by ajinabraham** [comment]
Hi @HughLu
We tested on Ubuntu 20.04 our setup script work fine. It might be an issue with your python installation.
