### ISSUE TITLE
Cvss score and CODE ANALYSIS are not analyzed normally in static analyzer screen.

### ISSUE THREAD

**Issue by choonSpring** [MobSF/Mobile-Security-Framework-MobSF#1762]
## ENVIRONMENT

OS and Version: Window 10
Python Version: 3.9.6
MobSF Version: 3.4

## EXPLANATION OF THE ISSUE

Cvss score and CODE ANALYSIS were not analyzed in static analyzer screen.
=> Cvss score is 0 and CODE ANALYSIS result is empty table.
Please refer to below screenshots.

[cvss score is '0']
![image](https://user-images.githubusercontent.com/86935937/124409569-8793d980-dd83-11eb-830a-2e2a6d4a5c35.png)

[code analysis table is always empty]
![image](https://user-images.githubusercontent.com/86935937/124409619-9ed2c700-dd83-11eb-936b-3eb0a50109a5.png)

I think that the cvss score of 0 seems the code analysis is not analyzed normally.
In normal case, cvss score is calculated with each code analyzed.

## STEPS TO REPRODUCE THE ISSUE

1. Executed run.bat in command screen.
2. Upload the apk file in Mobsf main screen.
3. Checked the static analyzer screen.

## LOG FILE

I pasted the debug log content.

[debug log]
[INFO] 05/Jul/2021 10:52:35 - Mobile Security Framework v3.4.4 Beta
[INFO] 05/Jul/2021 10:52:35 - OS: Windows
[INFO] 05/Jul/2021 10:52:35 - Platform: Windows-10-10.0.17763-SP0
[INFO] 05/Jul/2021 10:52:35 - Dist:   
[INFO] 05/Jul/2021 10:52:35 - MobSF Basic Environment Check
[WARNING] 05/Jul/2021 10:52:35 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 05/Jul/2021 10:52:36 - Checking for Update.
[INFO] 05/Jul/2021 10:52:36 - No updates available.
[INFO] 05/Jul/2021 10:53:55 - MIME Type: application/vnd.android.package-archive FILE: ThinQ_3.5.1400_201125_release.apk
[INFO] 05/Jul/2021 10:53:55 - Performing Static Analysis of Android APK
[INFO] 05/Jul/2021 10:53:56 - Starting Analysis on: ThinQ_3.5.1400_201125_release.apk
[INFO] 05/Jul/2021 10:53:56 - Analysis is already Done. Fetching data from the DB...
[INFO] 05/Jul/2021 10:54:31 - MIME Type: application/vnd.android.package-archive FILE: ThinQ_3.5.1043_200915_release.apk
[INFO] 05/Jul/2021 10:54:31 - Performing Static Analysis of Android APK
[INFO] 05/Jul/2021 10:54:31 - Starting Analysis on: ThinQ_3.5.1043_200915_release.apk
[INFO] 05/Jul/2021 10:54:31 - Generating Hashes
[INFO] 05/Jul/2021 10:54:32 - Unzipping
[INFO] 05/Jul/2021 10:54:38 - APK Extracted
[INFO] 05/Jul/2021 10:54:38 - Getting Hardcoded Certificates/Keystores
[INFO] 05/Jul/2021 10:54:39 - Getting AndroidManifest.xml from APK
[INFO] 05/Jul/2021 10:54:39 - Converting AXML to XML
[INFO] 05/Jul/2021 10:55:05 - Parsing AndroidManifest.xml
[INFO] 05/Jul/2021 10:55:13 - Fetching icon path
[INFO] 05/Jul/2021 10:55:20 - Extracting Manifest Data
[INFO] 05/Jul/2021 10:55:20 - Fetching Details from Play Store: com.lgeha.nuts
[INFO] 05/Jul/2021 10:55:21 - Manifest Analysis Started
[INFO] 05/Jul/2021 10:55:21 - Reading Network Security Config
[INFO] 05/Jul/2021 10:55:21 - Parsing Network Security Config
[INFO] 05/Jul/2021 10:55:21 - Binary Analysis Started
[INFO] 05/Jul/2021 10:55:21 - Analyzing lib/arm64-v8a/libAppSuit.so
[INFO] 05/Jul/2021 10:55:21 - Analyzing lib/arm64-v8a/libdecoderJNI.so
[INFO] 05/Jul/2021 10:55:21 - Analyzing lib/arm64-v8a/libdewarping-lib.so
[INFO] 05/Jul/2021 10:55:21 - Analyzing lib/arm64-v8a/libgojni.so
[INFO] 05/Jul/2021 10:55:24 - Analyzing lib/arm64-v8a/liblgupnp2.so
[INFO] 05/Jul/2021 10:55:26 - Analyzing lib/arm64-v8a/libnative-lib.so
[INFO] 05/Jul/2021 10:55:26 - Analyzing lib/arm64-v8a/libsds4JNI.so
[INFO] 05/Jul/2021 10:55:26 - Analyzing lib/arm64-v8a/libSDSPlusCore.so
[INFO] 05/Jul/2021 10:55:26 - Analyzing lib/arm64-v8a/libsecuritychecker-lib.so
[INFO] 05/Jul/2021 10:55:28 - Analyzing lib/arm64-v8a/libviterbi.so
[INFO] 05/Jul/2021 10:55:28 - Analyzing lib/armeabi-v7a/libAppSuit.so
[INFO] 05/Jul/2021 10:55:28 - Analyzing lib/armeabi-v7a/libdecoderJNI.so
[INFO] 05/Jul/2021 10:55:28 - Analyzing lib/armeabi-v7a/libdewarping-lib.so
[INFO] 05/Jul/2021 10:55:29 - Analyzing lib/armeabi-v7a/libgojni.so
[INFO] 05/Jul/2021 10:55:33 - Analyzing lib/armeabi-v7a/liblgupnp2.so
[INFO] 05/Jul/2021 10:55:35 - Analyzing lib/armeabi-v7a/libnative-lib.so
[INFO] 05/Jul/2021 10:55:35 - Analyzing lib/armeabi-v7a/libsds4JNI.so
[INFO] 05/Jul/2021 10:55:35 - Analyzing lib/armeabi-v7a/libSDSPlusCore.so
[INFO] 05/Jul/2021 10:55:35 - Analyzing lib/armeabi-v7a/libsecuritychecker-lib.so
[INFO] 05/Jul/2021 10:55:37 - Analyzing lib/armeabi-v7a/libviterbi.so
[INFO] 05/Jul/2021 10:55:38 - Reading Code Signing Certificate
[INFO] 05/Jul/2021 10:55:38 - Running APKiD 2.1.2
[INFO] 05/Jul/2021 10:55:49 - Trackers Database is up-to-date
[INFO] 05/Jul/2021 10:55:49 - Detecting Trackers
[INFO] 05/Jul/2021 10:55:56 - APK -> JAVA
[INFO] 05/Jul/2021 10:55:56 - Decompiling to Java with jadx
[INFO] 05/Jul/2021 10:55:56 - DEX -> SMALI
[INFO] 05/Jul/2021 10:55:56 - Converting classes.dex to Smali Code
[INFO] 05/Jul/2021 10:55:56 - Converting classes2.dex to Smali Code
[INFO] 05/Jul/2021 10:55:56 - Converting classes3.dex to Smali Code
[INFO] 05/Jul/2021 10:55:56 - Converting classes4.dex to Smali Code
[INFO] 05/Jul/2021 10:55:56 - Code Analysis Started on - java_source
[INFO] 05/Jul/2021 10:55:56 - Running NIAP Analyzer
[INFO] 05/Jul/2021 10:55:56 - Finished Code Analysis, Email and URL Extraction
[INFO] 05/Jul/2021 10:55:56 - Extracting Strings from APK
[INFO] 05/Jul/2021 10:59:44 - Detecting Firebase URL(s)
[INFO] 05/Jul/2021 11:16:42 - Performing Malware Check on extracted Domains
[INFO] 05/Jul/2021 11:16:45 - Maltrail Database is up-to-date
[INFO] 05/Jul/2021 11:16:45 - Connecting to Database
[INFO] 05/Jul/2021 11:16:45 - Saving to Database

Could you please share the solution about this issue?

Thanks.

**Comment by ajinabraham** [comment]
Please use slack channel for support.
This is because code analysis didn't identify any issue in Java code or the analysis failed.
On a side note, we are revamping scoring matrix.
