### ISSUE TITLE
Application security Score shows zero and Application permission status shows unknown

### ISSUE THREAD

**Issue by VinayKrishnaReddy** [MobSF/Mobile-Security-Framework-MobSF#1766]
## ENVIRONMENT

```
OS and Version:
Python Version:
MobSF Version:
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

HI,
when i am checking the static analysis for cricbuzz apk i am getting security score is 0/100 and one application permission shows unknown (com.cricbuzz.android.permission.C2D_MESSAGE) can you please look on this issue.

Thanks,
vinay
[Cricbuzz Live Cricket Scores News_v5.02.02_apkpure.apk.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/6815547/Cricbuzz.Live.Cricket.Scores.News_v5.02.02_apkpure.apk.zip)

**Comment by ajinabraham** [comment]
This is expected. We are also reworking our scoring mechanism. For discussions, please use  MobSF slack channel.
