### ISSUE TITLE
'cp949' codec can't decode byte 0xe2 in position 39020: illegal multibyte sequence

### ISSUE THREAD

**Issue by pypygeek** [MobSF/Mobile-Security-Framework-MobSF#1779]
## ENVIRONMENT

```
OS and Version: Windows 10 21H1 (Build 19043.1151)
Python Version: 3.9.5
MobSF Version: 3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```
1. Upload 546f93d93d47c422b3193864c872a64f87fabd1dab845eecbf68195c41d35207.apk
2. MobSF Show Error Page - Error Unicode decoding error. 'cp949' codec can't decode byte 0xe2 in position 39020: illegal multibyte sequence
![image](https://user-images.githubusercontent.com/19469996/128301806-d6202568-1c53-4e54-a433-760870995248.png)
3. `run.bat` show Error `[ERROR] 05/Aug/2021 15:15:37 - Error Performing Static Analysis` , `UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 39020: illegal multibyte sequence`
![image](https://user-images.githubusercontent.com/19469996/128301748-cb693033-7dcb-4dac-a51d-4db540a3259f.png)

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**No debug.log was created.**

**Comment by ajinabraham** [comment]
This is due to the localization not handled properly. Your system uses a non utf-8 encoding and androguard doesn't handle or enforce it.
You might want to report it to. https://github.com/androguard/androguard/issues

**Comment by pypygeek** [comment]
Here's a solution for those of you who have come across the same problem.

**control panel** 
1. country or region
2. system local changes
3. `Beta: Use Unicode UTF-8` Check
4. apply(A) 
5. computer resart
![image](https://user-images.githubusercontent.com/19469996/128443845-f9f9d744-4256-422b-8989-6a5358fcc729.png)
