### ISSUE TITLE
returned non-zero exit status 1.

### ISSUE THREAD

**Issue by pypygeek** [MobSF/Mobile-Security-Framework-MobSF#1780]
## ENVIRONMENT

```
OS and Version: Windows 10 21H1 (Build 19043.1151)
Python Version: 3.9.5
MobSF Version: 3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

 Only this file `2f820a64e255e540903e2a51482e8144a8408176a3319ed6977c3c7d9e3678d6.apk` causes the following error.

I've done all the setup as per the docs description.
Set JAVA_HOME env variable or set java path in MobSF/settings.py

It is probably an error that occurs because something cannot be extracted from the apk file.

![image](https://user-images.githubusercontent.com/19469996/128447304-c01a004e-8173-4b61-9b2c-5e09c1ce240e.png)

![image](https://user-images.githubusercontent.com/19469996/128447282-14fd985f-af86-4f5d-9c54-9fc3b25c6390.png)

#1204 - There are people who are having a similar problem to me.

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```
1. Upload `2f820a64e255e540903e2a51482e8144a8408176a3319ed6977c3c7d9e3678d6.apk`

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```
**No debug.log was created.**

**Comment by ajinabraham** [comment]
Any configurations should be done on `C:\Users\<user>\.MobSF\config.py` and not settings.py.
In your case, it looks like JAVA_HOME is set. The exception happens in baksmali. This is a third party tool that we use. You might want to report it with backsmali.

**Comment by pypygeek** [comment]
@ajinabraham Thanks for the explanation.
As you said, I edit the`C:\Users\<user>\.MobSF\config.py` and restart mobSF But, same error when I try to. I will report it to baksmali.
