### ISSUE TITLE
[FEATURE]support Android App Bundle format 

### ISSUE THREAD

**Issue by fishso** [MobSF/Mobile-Security-Framework-MobSF#1782]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
From August 2021, new apps are required to publish with the Android App Bundle on Google Play. 
 Android App Bundle is a new format.
refer : [https://developer.android.com/guide/app-bundle](https://developer.android.com/guide/app-bundle)

**Comment by ajinabraham** [comment]
Duplicate.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1517
We support apks, you need to generate signed apks from app bundle using bundletool to be used with MobSF.
