### ISSUE TITLE
[FEATURE] Download AndroidManifest from API

### ISSUE THREAD

**Issue by franco-marino** [MobSF/Mobile-Security-Framework-MobSF#1783]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
currently it is not possible to download the android manifest in any way using the API

**Describe the solution you'd like**
it would be useful to be able to download the android manifest via the API in addition to the source code. I would suggest using the `/view_source` endpoint by entering a new value for the type parameter (e.g. **manifest**) and looking for the result in the `apk_tool` folder

**Comment by ajinabraham** [comment]
Tracked separately
