### ISSUE TITLE
When I installed, the run.sh file showed a connection failure

### ISSUE THREAD

**Issue by 13724460607** [MobSF/Mobile-Security-Framework-MobSF#1786]
1. I successfully executed the./setup.sh file.
2./run.sh 127.0.0.1:8000, can't connect to (127.0.0.1:8000)  
![image](https://user-images.githubusercontent.com/52743072/129011508-2cc4ccbc-a081-4902-a109-a1dcf3a936f5.png)
![image](https://user-images.githubusercontent.com/52743072/129011818-9bbd9341-f3f1-48cf-bde5-3f2da0deaa2f.png)

How should I solve this problem?thank you

**Comment by ajinabraham** [comment]
You already have some process using port 8000. Please use MobSF slack channel for support
