### ISSUE TITLE
Bug: bad regex for domains

### ISSUE THREAD

**Issue by evilcel3ri** [MobSF/Mobile-Security-Framework-MobSF#1797]
## ENVIRONMENT

```
OS and Version:
Python Version: 3.8
MobSF Version: Latest docker version 
also tested with the current Github release of MobSF (basic installation on the Linux 5.10 and Python 3.8)
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

Hi! I'm coming from the project [Pithus](https://beta.pithus.org). We use MobSF in our toolsuite and we noticed that for this [sample](https://beta.pithus.org/report/7f4dda8c5131fe4f43112f696c1733bb93d3a9f6bef9e1aa4c87891b49874970) the regex for domains was going a bit crazy resulting in a lot of noise (see [issue](https://github.com/Pithus/bazaar/issues/48)). 

I [patched](https://github.com/Pithus/bazaar/pull/53) it quickly on our side, but I thought I'd let you know about it. I tried to find a solution but regexes are not that easy to fix (ah ah). 

## STEPS TO REPRODUCE THE ISSUE

```
1. Download a clean version of MobSF
2. Build and run.
3. You can download the sample from Pithus page here: https://beta.pithus.org/report/7f4dda8c5131fe4f43112f696c1733bb93d3a9f6bef9e1aa4c87891b49874970 and upload it to MobSF.
4. Check the domain/urls section.
```
I believe the problem stands here: 

```python
    url_pattern = re.compile(
        r'((?:https?://|s?ftps?://|file://|'
        r'javascript:|data:|www\d{0,3}'
        r'[.])[\w().=/;,#:@?&~*+!$%\'{}-]+)', re.UNICODE)
``` 
in `mobsf/DynamicAnalyzer/views/android/analysis.py`. As the sample creating the bug has packages starting with "www", it seems to throw the regex a bit out of balance. 

I'd be happy to help around, I'm currently testing solutions locally but no success for the moment.

**Comment by ajinabraham** [comment]
This is a tricky one. The regex that MobSF uses is designed to catch maximum URLs from code. This is done intentionally to detect half baked URLs and other hacky ones that are often crafted by malware authors and hence you see the noise.
