### ISSUE TITLE
IPA file not support and Dynamic Analyzer not working 

### ISSUE THREAD

**Issue by johnp2686** [MobSF/Mobile-Security-Framework-MobSF#18]
Hi,

I have trying to upload IPA file with zipped format not working,when i click Dynamic Analyzer VM not able to connect,please help me regarding this issue.

**Comment by bugwrangler** [comment]
IPA doesn't support for this framework right now, i guess only Android package is supported.

**Comment by johnp2686** [comment]
Dynamic Analyzer not running properly do you have idea for that.

**Comment by ajinabraham** [comment]
IPA is not supported for Dynamic Analysis. Zipped iOS Source code will be supported soon. Current commit doesn't support any iOS Apps. I working to fix some bugs and improve the rules.

Dynamic Analyzer doesn't work since there is no VM available. I will uploading the VM once I am done with all the test cases and bug fixes around it.

**Comment by bugwrangler** [comment]
Okay fine Ajin, waiting for release :+1:

**Comment by ajinabraham** [comment]
IPA is Supported now!

**Comment by ajinabraham** [comment]
You need to wait for some more time to see Dynamic Analyser in Action.

**Comment by bugwrangler** [comment]
Super release, Let me quickly verify the same!

**Comment by neilkamulkar** [comment]
Hi ajinabraham, I tried to upload ipa file on mobsf framework but it gives me an error iOS Application Security Analysis requires OSX. Can you please explain me this  and also the solution

**Comment by DominikSchlecht** [comment]
IPA-Analysis relies on OSX-native tools like `otool`, therefore OSX is needed.

**Comment by neilkamulkar** [comment]
How do i configure it can you please explain it to me step wise ... Also i have installed it on Kali Linux

**Comment by ajinabraham** [comment]
@neilkamulkar You need a MAC for IPA analysis.  Thats what MobSF says " iOS Application Security Analysis requires OSX" Configure MobSF in a MacBook.

**Comment by neilkamulkar** [comment]
Thanks Ajinabraham will install it and check ...

**Comment by DebarghyaRoy** [comment]
@ajinabraham , Could you please tell whether dynamic analysis is supported for IPA ? if not any plans for the same ? please help ..

**Comment by ajinabraham** [comment]
Not supported at the moment. It's in the pipeline.

**Comment by hemangdk** [comment]
@ajinabraham : Is IPA dynamic analysis now supported ?

**Comment by ajinabraham** [comment]
Nope

**Comment by SrinivasanZee** [comment]
@ajinabraham Is IPA dynamic analysis now supported ? In Mac pro with XCODE.

**Comment by ajinabraham** [comment]
Not yet. In the meantime, please take a look at https://github.com/chichou/grapefruit
