### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by KDR9666** [MobSF/Mobile-Security-Framework-MobSF#1800]
ERROR: Cannot install -r requirements.txt (line 23), click==7.1.2 and quark-engine==21.6.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested click==7.1.2
    androguard 3.4.0a1 depends on click>=7.0
    quark-engine 21.6.3 depends on click==8.0.1

**Comment by ajinabraham** [comment]
Are you able to run MobSF after running the setup script?

**Comment by mastercho** [comment]
> Are you able to run MobSF after running the setup script?

i got same issue and MobSF works until gets quark-engine analyze  and throws error that quark-engine is missing

**Comment by mastercho** [comment]
I just tried last commit and still getting

```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
quark-engine 21.6.3 requires click==8.0.1, but you'll have click 7.1.2 which is incompatible
```

**Comment by superpoussin22** [comment]
solved in last version
