### ISSUE TITLE
Not work and loop

### ISSUE THREAD

**Issue by yaser1234567890** [MobSF/Mobile-Security-Framework-MobSF#1810]
XML Seems to be packed, operations on the AndroidManifest.xml might fail.
Requested API level 30 is larger than the maximum we have, returning API level 28 instead.
mobsf doesn't work correctly

**Comment by superpoussin22** [comment]
without details and logs impossible to help you

**Comment by superpoussin22** [comment]
use https://mobsf.slack.com/join/shared_invite/enQtNzM2NTAyNzA1MjgxLTdjMzkzNDc3ZjdiMjkwZTZhMmFhNDlkZmMwZDhjNDNmYTAzYWE5NGZlMDIzYzliNTdiMDQ2MTRlYjU1MjkyNGM for support
