### ISSUE TITLE
Can't access http://ip:8000 on the web

### ISSUE THREAD

**Issue by barkosHuang** [MobSF/Mobile-Security-Framework-MobSF#1827]
I can successfully access 127.0.0.1:8000 on ubuntu, but on my computer, I cannot access http://ip:8000. Where can I configure it?

**Comment by superpoussin22** [comment]
use slack channel to ask for help :)
did you take a look on the documentation ?
if your ubuntu is runing mobsf and you want to access mobsf from another computer , then replace 127.0.0.1 with the real ip @ of your ubuntu  ( the lan ip @ of the ubuntu )
