### ISSUE TITLE
[FEATURE]Starting httptools Web UI independently

### ISSUE THREAD

**Issue by mastercho** [MobSF/Mobile-Security-Framework-MobSF#1829]
Often i have to go for some random Dynamic analysis to get httptools web UI started to check some recent scans, would be good on the main page you add httptools web UI next to dynamic analysis for example, so we have to not go every time through-full steps to get there

**Comment by ajinabraham** [comment]
You can start httptools independently within the MobSF venv
```
source venv/bin/activate
httptools -m server -p 1337
```
and choose the project you need. Please use slack for queries. Github issues are strictly for bug reports ONLY.
