### ISSUE TITLE
[FEATURE] Getting Stuck while running Static scan at - Running NIAP Analyzer

### ISSUE THREAD

**Issue by susantaroy2002** [MobSF/Mobile-Security-Framework-MobSF#1831]
**Here is the logs, its not moving further post NIAP Analyzer. Not sure about the NIAP Analyzer.  

[INFO] 21/Oct/2021 06:03:09 - Running NIAP Analyzer

Need suggestion.

[INFO] 21/Oct/2021 05:25:05 - Running APKiD 2.1.2
[INFO] 21/Oct/2021 05:25:21 - Trackers Database is up-to-date
[INFO] 21/Oct/2021 05:25:21 - Detecting Trackers
[INFO] 21/Oct/2021 05:25:32 - APK -> JAVA
[INFO] 21/Oct/2021 05:25:32 - Decompiling to Java with jadx
[INFO] 21/Oct/2021 05:27:50 - DEX -> SMALI
[INFO] 21/Oct/2021 05:27:50 - Converting classes9.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes8.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes11.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes10.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes12.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes3.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes2.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes13.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes6.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes7.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes16.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes14.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes5.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes4.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Converting classes15.dex to Smali Code
[INFO] 21/Oct/2021 05:27:50 - Code Analysis Started on - java_source
[INFO] 21/Oct/2021 06:03:09 - Running NIAP Analyzer

**Comment by mastercho** [comment]
thats related to https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1800 if click dependecie is failed during setup will stuck at NIAP Analyzer

**Comment by ajinabraham** [comment]
Please use slack.
