### ISSUE TITLE
[FEATURE] validate against known vulnerable apps

### ISSUE THREAD

**Issue by blshkv** [MobSF/Mobile-Security-Framework-MobSF#1836]
There are many open vulnerable application published. It would be good to enhance MobSF so that it would detect the all vulnerabilities which could be detected in automated mode.

The recent project is:
https://github.com/oversecured/ovia

There are many more:
https://github.com/rewanthtammana/Damn-Vulnerable-Bank
https://github.com/optiv/InsecureShop
https://github.com/satishpatnayak/AndroGoat
https//github.com/dineshshetty/Android-InsecureBankv2
https://github.com/payatu/diva-android
https://github.com/OWASP/MSTG-Hacking-Playground

**Comment by ajinabraham** [comment]
Tracked separately
