### ISSUE TITLE
Dynamic Analysis Failed for Genymotion Cloud SaaS Device

### ISSUE THREAD

**Issue by oa2013** [MobSF/Mobile-Security-Framework-MobSF#1838]
Hi! I'm connecting to a Genymotion instance successfully but I get the following non-descriptive error when I try to run dynamic analysis on an app - is there anyway to get more information about what's causing the error?

GApps is installed on the device and the device is running Android version 10.

Here are the screenshots:
<img width="1105" alt="Screen Shot 2021-11-05 at 10 38 48 PM" src="https://user-images.githubusercontent.com/5304739/140595275-b628a673-92d3-4fda-8922-fdb30e84af13.png">

<img width="928" alt="Screen Shot 2021-11-05 at 10 39 03 PM" src="https://user-images.githubusercontent.com/5304739/140595279-166d2b98-322b-4236-803d-5ea2255f6ddb.png">

**Comment by superpoussin22** [comment]
please use slack channel for this and provide logs in slack.
did you check if your mobsf can connect to the genymotion SaaS ?
https://mobsf.github.io/docs/#/dynamic_analyzer?id=genymotion-cloud-android

**Comment by david-colombo** [comment]
This should be reopened again.

There definitely is *some* kind of major issue when using Genymotion Cloud SaaS Devices.
And it's either the fault of Genymotion or a bug in MobSF.

Connecting to the device: works fine
Mobsifying the device: works fine
Starting dynamic analysis: adb becomes unresponsive at random points during the start of the dynamic analysis
