### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by 89z** [MobSF/Mobile-Security-Framework-MobSF#1839]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.9.6
MobSF Version: 3.4.3
```

## EXPLANATION OF THE ISSUE

If I try to use this:

~~~
ssl_pinning_bypass.js
~~~

## STEPS TO REPRODUCE THE ISSUE

with this app:

~~~
com.vimeo.android.videoapp
~~~

and I start the app, it prompts for login. Alternatively you can hit SKIP in the top right corner. If I hit SKIP, I get this message:

~~~
Something strange occurred
Sorry about that. Please try again.
~~~

If I try again, same error. If I then disable proxy and try again, it works.

**Comment by Heufiih** [comment]
Kjg

**Comment by superpoussin22** [comment]
please use slack channel for help
