### ISSUE TITLE
Installation Failed!

### ISSUE THREAD

**Issue by AhmadShakerASH** [MobSF/Mobile-Security-Framework-MobSF#1855]
ERROR: Could not find a version that satisfies the requirement yara-python-dex>=1.0.0 (from apkid==2.1.2->-r requirements.txt (line 24)) (from versions: none)
ERROR: No matching distribution found for yara-python-dex>=1.0.0 (from apkid==2.1.2->-r requirements.txt (line 24))

[ERROR] Installation Failed!
Please ensure that all the requirements mentioned in documentation are installed before you run setup script.
Scroll up to see any installtion errors.

The 'decorator==4.4.2' distribution was not found and is required by the application

**Comment by superpoussin22** [comment]
please use slack chanel for help on usage/installation
