### ISSUE TITLE
Bad exception handling in binary analysis

### ISSUE THREAD

**Issue by SynacktivCerv** [MobSF/Mobile-Security-Framework-MobSF#1858]
## ENVIRONMENT

```
OS and Version: Docker opensecurity/mobile-security-framework-mobsf:latest
MobSF Version: 3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

In the Android binary analysis, if a _.so_ file raises an exception, the binary analysis stops and does not analyze the remaining _.so_ files. Furthermore, no error is returned into the report about failing to analyze a shared library.

## STEPS TO REPRODUCE THE ISSUE

The APK cannot be shared. You can recompile an APK with a bad _.so_ file to reproduce. 

## LOG FILE

```
[INFO] 01/Dec/2021 12:37:53 - Analyzing lib/armeabi-v7a/XXXX.so
Unknown format
[ERROR] 01/Dec/2021 12:37:53 - Performing Binary Analysis
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 248, in elf_analysis
    elf_find = chk.checksec()
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 19, in checksec
    is_nx = self.is_nx()
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 174, in is_nx
    return self.elf.has_nx
AttributeError: 'NoneType' object has no attribute 'has_nx'
```
```
$ file lib/armeabi-v7a/XXXX.so
XXXX.so:        data
```

**Comment by ajinabraham** [comment]
Hi there can you share the problematic `.so` file?

**Comment by SynacktivCerv** [comment]
Unfortunately it is not possible. However the file is just a blob of data, lief does not recognize it as an ELF file so it cannot use the _is_nx_ method.

The following code return False:
```
import lief

print(lief.is_elf("lib/armeabi-v7a/XXXX.so"))
```

**Comment by ajinabraham** [comment]
Hotfixed in latest master
