### ISSUE TITLE
[FEATURE] Fridump integration 

### ISSUE THREAD

**Issue by ITmustang** [MobSF/Mobile-Security-Framework-MobSF#1864]
(https://github.com/MobSF/Mobile-Security-Framework-MobSF/discussions/1834) @zerodaysjoker.

Have thought about this for awhile and saw this discussion. havent seen a request feature yet so wanted to go ahead and put in one for fridump integration! thanks!

**Comment by matandobr** [comment]
Hey @ITmustang !
Great idea...
Besides strings, did you think about anything else that we could do with that?

**Comment by ITmustang** [comment]
@matandobr often times when i run fridump, i need to know which .data file contains whatever sensitive information im looking for. so along with strings, i usually do something like, _grep -rw -l CREDENTIALS *_   to search all .data files for credentials. I think it'd be really helpful to maybe have an input box to enter whatever information you're looking for in the heapdump and it'll print out what .data file(s) contain it.

**Comment by ajinabraham** [comment]
Tracked separately
