### ISSUE TITLE
i got it in linux and windows

### ISSUE THREAD

**Issue by hosseinkhojany** [MobSF/Mobile-Security-Framework-MobSF#1867]
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ImportError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">cannot import name 'url' from 'django.conf.urls' (F:\LINUX_BACKUP\SEC\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\conf\urls\__init__.py)</pre>

Request Method: | GET
-- | --
http://127.0.0.1:8000/
4.0
ImportError
cannot import name 'url' from 'django.conf.urls' (F:\LINUX_BACKUP\SEC\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\conf\urls\__init__.py)
F:\LINUX_BACKUP\SEC\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\MobSF\urls.py, line 1, in <module>
F:\LINUX_BACKUP\SEC\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\venv\Scripts\python.exe
3.9.9
['F:\\LINUX_BACKUP\\SEC\\Mobile-Security-Framework-MobSF-master\\Mobile-Security-Framework-MobSF-master\\venv\\Scripts\\waitress-serve.exe',  'C:\\Users\\Khoujani\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',  'C:\\Users\\Khoujani\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',  'C:\\Users\\Khoujani\\AppData\\Local\\Programs\\Python\\Python39\\lib',  'C:\\Users\\Khoujani\\AppData\\Local\\Programs\\Python\\Python39',  'F:\\LINUX_BACKUP\\SEC\\Mobile-Security-Framework-MobSF-master\\Mobile-Security-Framework-MobSF-master\\venv',  'F:\\LINUX_BACKUP\\SEC\\Mobile-Security-Framework-MobSF-master\\Mobile-Security-Framework-MobSF-master\\venv\\lib\\site-packages',  'F:\\LINUX_BACKUP\\SEC\\Mobile-Security-Framework-MobSF-master\\Mobile-Security-Framework-MobSF-master']
Sat, 11 Dec 2021 12:10:14 +0000

</body>
</html>

**Comment by superpoussin22** [comment]
Please update your mobsf to the last version it should solve the issue 
BTW please use slack channel for question
