### ISSUE TITLE
False Positive "No RELRO"

### ISSUE THREAD

**Issue by NewbieGoose** [MobSF/Mobile-Security-Framework-MobSF#1874]
## ENVIRONMENT

```
OS and Version: Docker opensecurity/mobile-security-framework-mobsf:latest
MobSF Version: MobSF v3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

In Android binary analysis, there are cases where some shared libraries are _incorrectly_ reported as having "No RELRO"
protection in place. Using other binary analysis tools, such as [checksec.py](https://github.com/Wenzel/checksec.py) or [checksec.sh](https://github.com/slimm609/checksec.sh), the results under the RELRO category differ.

## STEPS TO REPRODUCE THE ISSUE

1. Scan the apk, which can be fetched from [APKMirror](https://www.apkmirror.com/apk/niantic-inc/pokemon-go-samsung-galaxy-apps-version/pokemon-go-samsung-galaxy-apps-version-0-225-2-release/pokemon-go-samsung-galaxy-store-0-225-2-android-apk-download/) with MobSF (sorry cannot upload, file too lage)
2. Extract the libraries from the attached apk, e.g `unzip "com.nianticlabs.pokemongo.ares_0.225.2-2021120901_minAPI23(arm64-v8a)(nodpi)_apkmirror.com.apk" 'lib/arm64-v8a/*' -d libs`, and use either `checksec.py` or `checksec.sh` tools on the extracted libraries.
3. Notice the difference between the results (results presented below)

```
| Library                                              | MobSF      | checksec.py   | checksec.sh   |
| pokemon/lib/arm64-v8a/libmain.so                     | No RELRO   | Partial RELRO | Partial RELRO |
| pokemon/lib/arm64-v8a/libnative-googlesignin.so      | No RELRO   | Full RELRO    | Full RELRO    |
| pokemon/lib/arm64-v8a/libsqlite3.so                  | No RELRO   | Full RELRO    | Full RELRO    |
| pokemon/lib/arm64-v8a/libtensorflowlite.so           | No RELRO   | Partial RELRO | Partial RELRO |
| pokemon/lib/arm64-v8a/libunity.so                    | No RELRO   | Partial RELRO | Partial RELRO |
```

## ADDITIONAL INFORMATION
In comparison with `checksec.py`, which also uses `lief` to test the protections of the binaries, the differences on the reported results lie on the facts (according to my investigation):
1. MobSF does not make an additional check for `lief.ELF.DYNAMIC_FLAGS_1.NOW` flag in `DT_FLAGS_1` dynamic tags. (More information on the [flag](https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter6-42444.html), as well as checksec.py's [implementation](https://github.com/Wenzel/checksec.py/blob/e8f0671bce330430ca55b4a237570edb6d5e5dbb/checksec/elf.py#L119-L139))
2. MobSF does not handle exceptions raised in line `if bind_now in self.elf.get(flags):` in line 198 when `self.elf.get(flags)` fails 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/d3df61e324b568a38b2614827bfe8229a7b54b20/mobsf/StaticAnalyzer/views/android/binary_analysis.py#L192-L204

Attached you will find two files:
1. A .zip file  ([false_libs.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/7726898/false_libs.zip)), which includes the .so files which differ. (Again, I apologize for not attaching the whole apk, but there's an upload limit).
1. A python script ([test_relro.py.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/7726904/test_relro.py.txt)) which copies the methods used by MobSF and checksec.py for quick comparison between the .so files in the attached .zip

**Comment by ajinabraham** [comment]
Thanks for the detailed bug report. I will take a look.

**Comment by ajinabraham** [comment]
We will be removing RELRO due to false positives.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1978
