### ISSUE TITLE
Emulator crashes soon after clicking on Start Instrumentation

### ISSUE THREAD

**Issue by zerodaysjoker** [MobSF/Mobile-Security-Framework-MobSF#1876]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.8.10
MobSF Version: 3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

In the dynamic analysis page, after we click on the "Start Instrumentation", the emulator starts to reboot. In the console it shows "Timed out while waiting for device to appear". 

## STEPS TO REPRODUCE THE ISSUE

```
1. Start dynamic analysis
2. In the dynamic analysis page Select Enumerate Loaded Classes, Capture Strings and Capture String Comparisons
3. Click Start Instrumentation
```

## LOG FILE

```
[INFO] 09/Dec/2021 21:14:57 - Starting Instrumentation
[INFO] 09/Dec/2021 21:14:57 - Starting Frida Server
[INFO] 09/Dec/2021 21:14:57 - Waiting for 2 seconds...
[ERROR] 09/Dec/2021 21:15:23 - Timed out while waiting for device to appear
```

**Comment by ajinabraham** [comment]
This needs to be reported to the corresponding emulator project. We cannot debug or fix things outside the scope of MobSF.
