### ISSUE TITLE
scan stuck in quark scan

### ISSUE THREAD

**Issue by javixeneize** [MobSF/Mobile-Security-Framework-MobSF#1882]
Hi

I tried the previous mobsf version, and it was reporting a problem with the module quark.objects being missed, although i fully installed the requirements.txt file

I downloaded the newest version and now it is stuck in quark scan until it gives a timeout

[INFO] 09/Jan/2022 18:08:15 - Running Quark 22.1.1

I am running it in a mac m1, if it helps

Thanks

**Comment by ajinabraham** [comment]
Are you on the latest MobSF release? We made some quark related fixes on 3.4.6.
If you are and seeing this issue, you might want to reach out to quark project.

**Comment by javixeneize** [comment]
yeah i downloaded it with the new quark version.

I will try to run quark standalone and see if i have the same problem

Thanks!

**Comment by javixeneize** [comment]
Same problem using quark standalone, i reported to them - https://github.com/quark-engine/quark-engine/issues/299

Is there any way to skip the quark scan in mobsf? Maybe a flag can be added if this is a common problem

Thanks

**Comment by ajinabraham** [comment]
Quark is disabled by default. You might have it set to true in your config.py. Please set `QUARK_ENABLED = False` in `~/.MobSF/config.py`

**Comment by javixeneize** [comment]
Ok, I will modify that file, but I ran it as default and quark was executed

**Comment by ajinabraham** [comment]
The config.py might have it set to True from an older MobSF release. We turned it off by default from a few commits back. Your config.py is never updated on MobSF update so you might have the old configuation.
