### ISSUE TITLE
Wrong permissions for .local directory in /home/mobsf

### ISSUE THREAD

**Issue by frost9i** [MobSF/Mobile-Security-Framework-MobSF#1883]
**Running**: ./scripts/postgres_support.sh True
**Returns**:
```
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Installing collected packages: psycopg2-binary
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/mobsf/.local/lib'
Check the permissions.
```
![image](https://user-images.githubusercontent.com/25299818/148743644-f6a9d7f5-b74d-47ae-9ce1-a002554c13e7.png)

**Comment by ajinabraham** [comment]
Hi @frost9i Permission issues are something you need to fix in your OS environment. This is not a MobSF bug.

**Comment by frost9i** [comment]
Yeah, sorry, I wasn't clear enough.
It is related to docker image.

Got it fixed by running postgress support script as root:
```
FROM opensecurity/mobile-security-framework-mobsf
# Enabling Postgres support
USER root
ARG POSTGRES=True
RUN ./scripts/postgres_support.sh $POSTGRES
USER mobsf
```
