### ISSUE TITLE
add some new android permission

### ISSUE THREAD

**Issue by firmianay** [MobSF/Mobile-Security-Framework-MobSF#1888]
1. 
```
        "com.qualcomm.permission.IZAT": {
            "status": "unknown",
            "info": "Unknown permission",
            "description": "Unknown permission from android reference"
        },
```
https://krispitech.com/qualcomm-izat/

2. 
```
        "android.car.permission.CAR_VENDOR_EXTENSION": {
            "status": "unknown",
            "info": "Unknown permission",
            "description": "Unknown permission from android reference"
        },
```
```
<permission
 android:name=”android.support.car.permission.CAR_VENDOR_EXTENSION”
 android:permissionGroup=”android.support.car.permission.CAR_INFORMATION”
 android:protectionLevel=”signature|privileged” />
```

**Comment by ajinabraham** [comment]
These permissions are not present in https://developer.android.com/reference/android/Manifest.permission
which is our source. Also permissions like `com.qualcomm.permission.IZAT` are vendor created and not official.

**Comment by firmianay** [comment]
Ok, but can you add those new permissions that were added in API 31?

**Comment by ajinabraham** [comment]
We don't manually gather and update permissions. Once in a while, we run this script https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/scripts/update_android_permissions.py to fetch new permission from Android docs.
