### ISSUE TITLE
[FEATURE] Allow using environment variables to set settings

### ISSUE THREAD

**Issue by proletarius101** [MobSF/Mobile-Security-Framework-MobSF#1889]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Containers usually use environment variables to configure for easier injection. That's especially useful in the context of CI/CD, where secrets (e.g. `VT_API_KEY`) should be protected. However, currently mobsf only reads `config.py`

**Describe the solution you'd like**
Maybe `config.py` can read the environment variables and inject them

**Comment by magaofei** [comment]
Hi @ajinabraham , Should we do it? I can implement it.

**Comment by ajinabraham** [comment]
Yes, this is nice to implement
