### ISSUE TITLE
Mapping key not found. - 'good' (macOS 12.0.1)

### ISSUE THREAD

**Issue by alonf1983** [MobSF/Mobile-Security-Framework-MobSF#1892]
open a new one as the last one closed:

I did **fresh** installed (rm -rf and new git clone) and same issue.
I tried also after the new **fresh** install:

git pull origin master
. venv/bin/activate
pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate
deactivate

however, getting the same error:

```
[ERROR] 31/Jan/2022 09:25:11 - Error Performing Static Analysis
Traceback (most recent call last):
File "/Users/alonf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 307, in static_analyzer
context['appsec'] = get_android_dashboard(context, True)
File "/Users/alonf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/common/appsec.py", line 134, in get_android_dashboard
findings[i[0]].append({
KeyError: 'good'
[ERROR] 31/Jan/2022 09:25:11 - 'good'
[ERROR] 31/Jan/2022 09:25:11 - Internal Server Error: /static_analyzer/

```
could you help please?

**Comment by ajinabraham** [comment]
Please use slack for support
