### ISSUE TITLE
Add FileLink for Permissions

### ISSUE THREAD

**Issue by LukasMarckmiller** [MobSF/Mobile-Security-Framework-MobSF#1894]
It would be handy to include links in the Permissions section to files using this permission.

**Is your feature request related to a problem? Please describe.**
Security Researchers are lazy so it would be cool to review the code section that uses the permission within the browser.

**Describe the solution you'd like**
Maby a list of file path links like in the section Android API or Code Analysis

**Comment by ajinabraham** [comment]
Tracked separately.
