### ISSUE TITLE
[FEATURE] Support for GPlayDL

### ISSUE THREAD

**Issue by srikanthlogic** [MobSF/Mobile-Security-Framework-MobSF#1900]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

[GPlayDL](https://github.com/rehmatworks/gplaydl/) is a command line Google Play APK downloader. It extracts APK for an authenticated user.  This can automate the download of current APK in Google Play and analyse the same within MobSF in a single step.

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**

1. For a given a playstore URL in search bar, download the APK using GPlayDL, instead of the current APK mirrors.
2. Pre-requisites for this - email id and app-specific password as configuration variables.

**Describe alternatives you've considered**
Haven't found any other reliable GPlay downloader, but if there is a better lib / tool to download APK from Google Play, that is okay as well.

**Additional context**
NA

**Comment by ajinabraham** [comment]
Tracked separately
