### ISSUE TITLE
MobSF Dynamic Analysis fails when using Genymotion SaaS

### ISSUE THREAD

**Issue by david-colombo** [MobSF/Mobile-Security-Framework-MobSF#1911]
## EXPLANATION OF THE ISSUE

MobSF Dynamic Analysis fails when using a Genymotion SaaS instance due to the adb device going offline.

## STEPS TO REPRODUCE THE ISSUE

1. Install the latest version of MobSF
2. Start a Genymotion SaaS instance, using the gmsaas tool (important! starting the instance using the cloud console will cause a different Genymotion related issue)
3. Initialize the adb connection to the virtual device
4. Verify MobSF detects the device
5. Start Dynamic Analysis / Mobsifying
6. See the device going into an offline state and the Dynamic Analysis failing

## WHAT CAUSES THE ISSUE

If you take a look in mobsf/DynamicAnalyzer/views/android/environment.py
```
def connect_n_mount(self):
        """Test ADB Connection."""
        self.adb_command(['kill-server'])
        self.adb_command(['start-server'])
        logger.info('ADB Restarted')
        self.wait(2)
```

The adb server gets restarted every time when connecting to and mounting a device causing the device to go offline until the server runs again.
But when using a Genymotion SaaS instance restarting the adb server will take a lot longer than the 2 second wait time.
Which will lead to a complete failure because MobSF proceeds to run adb commands after the 2 seconds wait time without verifying the adb device is online again.

I personally fixed this by simply removing the kill/start server commands.
But I think, if the adb server restart is required, the better option would be to just wait longer or verify the device is online again before proceeding.

**Comment by ajinabraham** [comment]
Please use our slack channel for discussions.

**Comment by eslam2010011** [comment]
@david-colombo 
I have the same problem
How did you solve this problem
