### ISSUE TITLE
 Running Quark 22.2.1 time is too long

### ISSUE THREAD

**Issue by GreatAsia** [MobSF/Mobile-Security-Framework-MobSF#1924]
upload apk after,
find  running Quark 22.2.1   Run for 17 minutes

## ENVIRONMENT

```
OS and Version: win10
Python Version:3.9
MobSF Version:v3.5.2beta
```

## LOG FILE
[INFO] 17/Mar/2022 17:15:04 - Running Quark 22.2.1
[INFO] 17/Mar/2022 17:32:41 - Extracting Strings from APK

**Comment by PaulNicolasHunter** [comment]
possibly related to this [issue](https://github.com/quark-engine/quark-engine/issues/130)

**Comment by ajinabraham** [comment]
This is an upstream issue with Quark. You could disable Quark analysis in config.py till an upstream fix is available.
