### ISSUE TITLE
[FEATURE]How to convert PDF report to Chinese

### ISSUE THREAD

**Issue by GreatAsia** [MobSF/Mobile-Security-Framework-MobSF#1925]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
I need Chinese PDF report

**Describe the solution you'd like**
convert PDF report to Chinese

**Describe alternatives you've considered**
Google translate

**Additional context**

The platform can choose to generate reports and PDFS in Chinese

**Comment by ajinabraham** [comment]
You might want to touch base with @magaofei 
At this time, we do not have non-english language support on the tool. If we can get translators, we can take a look at this.

**Comment by magaofei** [comment]
> You might want to touch base with @magaofei At this time, we do not have non-english language support on the tool. If we can get translators, we can take a look at this.

I could implement this feature, but I have a question. how to choose the language for the report?

**Comment by ajinabraham** [comment]
I guess, it can be an environment variable or settings. This should be a locale based implementation in future to support other languages as well.

**Comment by magaofei** [comment]
> I guess, it can be an environment variable or settings. This should be a locale based implementation in future to support other languages as well.

ok, that sounds good.

**Comment by Fe4rl3** [comment]
Eye

**Comment by ajinabraham** [comment]
Tracked separately
