### ISSUE TITLE
[FEATURE] Download IPA files, just like APKs

### ISSUE THREAD

**Issue by andyacer** [MobSF/Mobile-Security-Framework-MobSF#1932]
My team uses a hosted version of MobSF to share information and compare notes.  The "Download APK" button makes it a convenient way to share APK files across the team.  I think iOS apps should get the same treatment, MobSF should have a "Download IPA" button for iOS apps.

**Is your feature request related to a problem? Please describe.**
Not a problem, just feature parity between iOS and Android.  Android already has this feature.

**Describe the solution you'd like**
On the static analyzer page, specific to an iOS app, enable a "Download IPA" button towards the top of the page.  On Android this is shown to the right of the "Scan Options" within a "Decompiled Code" card.

**Describe alternatives you've considered**
A workaround is to SSH onto the mobSF server and SCP the files directly.  Using the webUI would be much nicer.

**Additional context**
![image](https://user-images.githubusercontent.com/25163515/160625029-25ec2fc1-725b-4031-984b-d05ba8afb55f.png)

![image](https://user-images.githubusercontent.com/25163515/160625255-f705723c-6f03-435e-9d2f-68b6fcbe66bc.png)

**Comment by ajinabraham** [comment]
Fixed on https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1977
