### ISSUE TITLE
apktool failed to extract AndroidManifest.xml or parsing failed

### ISSUE THREAD

**Issue by faheemadam** [MobSF/Mobile-Security-Framework-MobSF#1937]
i am using mobsf on docker PWD and after loading apk i got this error, 3.5.2 beta is the version

[INFO] 03/Apr/2022 15:25:53 - Converting AXML to XML
[INFO] 03/Apr/2022 15:25:57 - Parsing AndroidManifest.xml
[ERROR] 03/Apr/2022 15:25:57 - apktool failed to extract AndroidManifest.xml or parsing failed
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 48, in get_manifest
    manifest = minidom.parseString(manifest)
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1969, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
[WARNING] 03/Apr/2022 15:25:57 - Using Fake XML to continue the Analysis
[INFO] 03/Apr/2022 15:25:57 - Extracting Manifest Data
[INFO] 03/Apr/2022 15:25:57 - Fetching Details from Play Store: Failed
[INFO] 03/Apr/2022 15:25:57 - Manifest Analysis Started
[INFO] 03/Apr/2022 15:25:57 - Binary Analysis Started
[INFO] 03/Apr/2022 15:25:57 - Reading Code Signing Certificate
[ERROR] 03/Apr/2022 15:25:57 - Reading Code Signing Certificate

**Comment by ajinabraham** [comment]
Hi @faheemadam The APK probably has a malformed manifest file (`apktool failed to extract AndroidManifest.xml or parsing failed`) . Can you share the file and move this conversation to slack.

Will reopen if this is a MobSF bug.

**Comment by faheemadam** [comment]
i did put it on slack. no one is answering there
