### ISSUE TITLE
Error in Static Analysis (Android) - "Performing Binary Analysis"

### ISSUE THREAD

**Issue by toxicphreAK** [MobSF/Mobile-Security-Framework-MobSF#1943]
While running the static analysis on a non-public APK I am not able to provide you with further runtime details. But I get an error on the following code line, as the code does not check if `self.elf.get(flags)` does not respond any value, so its `None` and then an error occurs, as this case is not handled. Please review or come back and I will try to explain further.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/c4f5130b5c8522f5d2c2cfa579ca02e8c4b5de84/mobsf/StaticAnalyzer/views/android/binary_analysis.py#L198

**Comment by ajinabraham** [comment]
Hi @toxicphreAK We started noticing this with the LIEF project version update. This should be fixed in latest master.
