### ISSUE TITLE
Can't Install MobSf

### ISSUE THREAD

**Issue by ahk52899** [MobSF/Mobile-Security-Framework-MobSF#1952]
So I've been trying to install mobSF on my kali virtual box machine. I get these error messages. I do have python decorator installed.
error couldn't find a version that satisfies the requirement yara-pythondex > 1.0.0 (from apkid=2.1.3->r requirements.txt (line 24)) (from version s: none)
Error: no matching distribution found for yara-python-dex>1.0.0 (from apkid=2.1.3->r requirements.txt (line 24)) 

error installation failed. Plese ensure all the requirements mentioned in documentation are instaled before you run setup script. the 'decorator=4.4.2' distribution was not found and is required by the application.

Anybody get these errors when installing it? I havent anybody getting these errors online.

**Comment by ajinabraham** [comment]
Please use slack for limited support

**Comment by NWcodeart** [comment]
did you find the solution ?

**Comment by mustafairan** [comment]
I tried to manually install requirements. There is a package version confliction as below. I don't know how to solve. (I don't want to get into package manuals etc :) ) So any help will be appreciated. (python version 3.9.0)
The conflict is caused by:
    The user requested click==8.0.1
    androguard 3.4.0a1 depends on click>=7.0
    quark-engine 22.10.1 depends on click
    mitmproxy 6.0.2 depends on click<8 and >=7.0
