### ISSUE TITLE
Default Permissions for Mobsf Integration to Private Repo using Github Actions

### ISSUE THREAD

**Issue by OlugbengaJJ** [MobSF/Mobile-Security-Framework-MobSF#1967]
**The feature request/problem?**
While integrating using Github Action on Private Repository I noticed the 
Error: codeql/upload-sarif action failed: HttpError: Resource not accessible by integration

**Solution**
The issue was because the permission set on the job was not sufficient. This is the most minimal permission that worked and fixed the issue raised.

1. Enable advance security using this [Advance Github Security](https://docs.github.com/en/enterprise-cloud@latest/get-started/learning-about-github/about-github-advanced-security#enabling-advanced-security-features.).
2. Add the following permission to the workflow for private repos.
permissions:
**actions: read
contents: read
security-events: write
statuses: write**

3. Confirm Workflow have read and write permissions in the repository for all scopes.
Using this [Set workflow permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)

**Additional context**
Rerun the workflow and you should have a successful response.
<img width="953" alt="Mobsf " src="https://user-images.githubusercontent.com/30858703/170487260-fee2f97f-a96b-42ba-9565-b6cb9de8bc3d.png">

**Comment by ajinabraham** [comment]
This is not applicable to this repo. Please report it to the MobSF action repo instead.
