### ISSUE TITLE
setup.bat broken for Windows installation

### ISSUE THREAD

**Issue by rmartinez213** [MobSF/Mobile-Security-Framework-MobSF#1979]
setup.bat in master branch yields error based on latest commit: `- was unexpected at this time`

Reverting to old setup.bat from Dec 'fixes' it.
NOTE: This was for windows 11 installation if that makes any difference.

![Screenshot 2022-06-12 203527](https://user-images.githubusercontent.com/25447970/173275292-dd303796-a894-43bb-b61c-8b3a56e7e5ec.png)

**Comment by ajinabraham** [comment]
Thanks for catch. The fix for this is  available in the latest `master` branch
