### ISSUE TITLE
[iOS Permissions]

### ISSUE THREAD

**Issue by KongLynn** [MobSF/Mobile-Security-Framework-MobSF#1981]
There is no Local Network Permission in permission_analysis.py(COCOA_KEYS), which is added after iOS14. https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription. Could you please update the latest permission list of iOS.

**Comment by KongLynn** [comment]
Mes list take from https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources

**Comment by KongLynn** [comment]
List take from https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources

**Comment by ajinabraham** [comment]
Will be fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2000/files
