### ISSUE TITLE
PDF export is dead, find a better option

### ISSUE THREAD

**Issue by blshkv** [MobSF/Mobile-Security-Framework-MobSF#1982]
mobsf uses https://pypi.org/project/pdfkit/ which is a wrapper of Wkhtmltopdf.
Wkhtmltopdf requires QtWebKit which was depreciated, and the migration to QtWebEngine is slow.
See the following links:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3391
https://github.com/NixOS/nixpkgs/issues/53079

On a side note, the current export to PDF  (html -> pdf) is broken and useless as paginated sections are not getting exported. You should re-write it and export from database directly.

**Comment by ajinabraham** [comment]
Tracked separately.
