### ISSUE TITLE
Windows Issue - Mapping Key Not Found "good"

### ISSUE THREAD

**Issue by chinmaydhawale** [MobSF/Mobile-Security-Framework-MobSF#1987]
Running MobSF on 127.0.0.1:8000
[INFO] 01/Jul/2022 06:48:21 -
  __  __       _    ____  _____       _____  ____
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___|
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/
[INFO] 01/Jul/2022 06:48:21 - Mobile Security Framework v3.5.2 Beta
REST API Key: 990ce823cc738ad8a2cd71ef6d6bed7e2e095a75cf24a60cc3a07fdc088f87f2
[INFO] 01/Jul/2022 06:48:21 - OS: Windows
[INFO] 01/Jul/2022 06:48:21 - Platform: Windows-10-10.0.14393-SP0
[INFO] 01/Jul/2022 06:48:21 - MobSF Basic Environment Check
[WARNING] 01/Jul/2022 06:48:21 - Dynamic Analysis related functions will not work.
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[WARNING] 01/Jul/2022 06:48:21 - Internet Not Available. Skipping Update check
[INFO] 01/Jul/2022 06:48:28 - MIME Type: application/vnd.android.package-archive FILE: Brisbane_EIL_v2.1.18(94)_sign.apk
[INFO] 01/Jul/2022 06:48:28 - Performing Static Analysis of Android APK
[INFO] 01/Jul/2022 06:48:28 - Starting Analysis on: Brisbane_EIL_v2.1.18(94)_sign.apk
[INFO] 01/Jul/2022 06:48:28 - Analysis is already Done. Fetching data from the DB...
[ERROR] 01/Jul/2022 06:48:28 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 307, in static_a
nalyzer
    context['appsec'] = get_android_dashboard(context, True)
  File "C:\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\common\appsec.py", line 190, in get_android_dashbo
ard
    findings[i[0]].append({
KeyError: 'good'
[ERROR] 01/Jul/2022 06:48:28 - 'good'
[ERROR] 01/Jul/2022 06:48:29 - Internal Server Error: /static_analyzer/
ERROR:django.request:Internal Server Error: /static_analyzer/
[INFO] 01/Jul/2022 06:48:29 - Starting Analysis on: Brisbane_EIL_v2.1.18(94)_sign.apk
[INFO] 01/Jul/2022 06:48:29 - Analysis is already Done. Fetching data from the DB...
[ERROR] 01/Jul/2022 06:48:29 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 307, in static_a
nalyzer
    context['appsec'] = get_android_dashboard(context, True)
  File "C:\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\common\appsec.py", line 190, in get_android_dashbo
ard
    findings[i[0]].append({
KeyError: 'good'
[ERROR] 01/Jul/2022 06:48:29 - 'good'
[ERROR] 01/Jul/2022 06:48:29 - Internal Server Error: /static_analyzer/
ERROR:django.request:Internal Server Error: /static_analyzer/

**Comment by ajinabraham** [comment]
Please share the APK for troubleshooting.

**Comment by chinmaydhawale** [comment]
[GmsInstaller_V1.1_20201210_SIG (1).zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/9023596/GmsInstaller_V1.1_20201210_SIG.1.zip)

**Comment by chinmaydhawale** [comment]
Thanks Ajin. So what's the recommendation for resolving the install issue? 

I have updated the mobsf.
tried cloning fresh.
removed libsast

**Comment by ajinabraham** [comment]
If you are still seeing issues after reinstall, that suggests that your cleanup was incomplete. Have you deleted files created under .MobSF directory under your home directory? Please use slack channel for support.
