### ISSUE TITLE
[Feature] Add Support for Android App Bundles (.aab) files

### ISSUE THREAD

**Issue by bh4nut3j4** [MobSF/Mobile-Security-Framework-MobSF#1992]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and its importance.

**Is your feature request related to a problem? Please describe.**
Right now MobSF does not support Android App Bundles (.aab files). https://developer.android.com/guide/app-bundle 

**Describe the solution you'd like**
It would be great to support .aab file upload and convert them to .apk files on the fly before the scan.

**Comment by ajinabraham** [comment]
Duplicate https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1643

**Comment by ajinabraham** [comment]
Supported now https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2391
