### ISSUE TITLE
[FEATURE] async support

### ISSUE THREAD

**Issue by BabelQwerty** [MobSF/Mobile-Security-Framework-MobSF#2017]
async support

**Comment by superpoussin22** [comment]
can you elaborate a little bit ?

**Comment by DMyachin** [comment]
Sometimes `api/v1/scan` can takes more than 1 hour on my PC. Can you add `api/v1/scanAsync` what will returns (for example) scan task id and `api/v1/taskState` for checking task state.

In progress: 

```json
{
    "task_state": "IN_PROGRESS"
    "task_ok": false
    "file_hash": ""
}
```

Finished:


```json
{
    "task_state": "DONE"
    "task_ok": true // or false if some error
    "file_hash": "qwerty123456"
}
```

And now I can use `/api/v1/report_json` with hash
