### ISSUE TITLE
unable to find user mobsf in git Hub action Workflow

### ISSUE THREAD

**Issue by utpal-maersk** [MobSF/Mobile-Security-Framework-MobSF#2032]
[logs_14.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/9633488/logs_14.zip)
<img width="1154" alt="Screenshot 2022-09-23 at 5 35 22 PM" src="https://user-images.githubusercontent.com/73114132/191957757-b6835907-b710-4a2c-91c8-64e12491c036.png">

## ENVIRONMENT

```
OS and Version: Ubuntu/20.04.5/LTS
Python Version:
MobSF Version: mobile-security-framework-mobsf:v3.4.3
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Able to create the apk file 
    
2. When it run the MobSF scanning we are getting the error 
```

## LOG FILE

```
please find the attachment of log file and screen shots of error 
```

**Comment by utpal-maersk** [comment]
Github Action yml file full 

name: Mobsfscanning Mobile App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set-up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set-up Flutter
        uses: subosito/flutter-action@v2

      - name: Flutter Install Dependencies
        run: flutter pub get

      # - name: Flutter Test
      #   run: flutter test

      - name: Flutter Build
        run: flutter build apk

      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.2
        env:
          INPUT_FILE_NAME: build/app/outputs/apk/app.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report

      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf

      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json

**Comment by ajinabraham** [comment]
We do not maintain that action. Please work with it’s author to resolve any issues.
