### ISSUE TITLE
[FEATURE] Support static analysis of different binary formats

### ISSUE THREAD

**Issue by gautamar** [MobSF/Mobile-Security-Framework-MobSF#2036]
Hi, 

We would like to request new features to include static analysis of the following binary formats independently and generate a report

Priority 1:   **Android: AAR, dynamic library (.so)**, **IOS: Dynamic framework** (iOS dynamic framework is a bundle (a structured directory) that contains a dynamic shared library along with associated resources, such as nib files, image files, and header files)
Priority 2:   ****Android**: JAR support**
Priority 3:   **Android static library(.a), iOS static framework** ( same as that of dynamic framework except for dynamic library, it packages the static library with the resources such as images, headers etc )

Here are details on what is expected in the report for each of the binary formats

**.aar** - Report shall be similar to that of APK with aar specific sections ( all sections except signing certificate section )
**.jar** - Report shall be similar to that of APK with only the jar specific sections (Android API, Security Analysis(Network security, Code Analysis, NIAP Analysis, File Analysis), Malware Analysis, Reconnaissance, Components )
**.so, .a** - Report shall contain details parsed for Binary analysis section ( This is already done for .so files within an apk  ). Additionally the report shall list the readable strings
**ios dynamic and static framework**  - Report shall be a subset of IPA analysis with applicable sections.

**Comment by aebrahim** [comment]
Any chance AAB (Android App Bundle) can be included as well?

**Comment by ajinabraham** [comment]
Closing this. Tracked separately as a part of the priority enterprise feature request.
