### ISSUE TITLE
Report json format does not work

### ISSUE THREAD

**Issue by saheredelgadom** [MobSF/Mobile-Security-Framework-MobSF#2038]
I am using docker mobsf on linux ubuntu 22.04 when following the documentation instructions for reporting json format in the static vulnerability scan:

<html>
<body>
<h2 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-weight: 500; line-height: 1.2; color: rgb(33, 37, 41); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bolder;">Generate JSON Report API</strong></h2><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">API to generate JSON Report.</p><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">URL:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">/api/v1/report_json</code></p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">Method:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">POST</code></p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">Header:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">Authorization:&lt;api_key&gt;</code><span> </span><strong style="box-sizing: border-box; font-weight: bolder;">Or</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">X-Mobsf-Api-Key:&lt;api_key&gt;</code></p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">Data Params</strong></p></li></ul>

Param Name | Param Value | Required
-- | -- | --
hash | hash of the scan | Yes

<br style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">Success Response:</strong></p><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Code:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">200</code><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Content-Type:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">application/json; charset=utf-8</code><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Content:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">JSON Contents</code></li></ul></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">Error Response:</strong></p><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Code:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">500 Internal Server Error</code><span> </span>or<span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">405 Method Not Allowed</code><span> </span>or<span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">422 Unprocessable Entity</code><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Content-Type:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">application/json; charset=utf-8</code><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Content:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">{"error": &lt;error message&gt; }</code></li></ul><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;">OR</p><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Code:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">401 Unauthorized</code><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Content-Type:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">application/json; charset=utf-8</code><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Content:</strong><span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">{"error": "You are unauthorized to make this request." }</code></li></ul></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;"><strong style="box-sizing: border-box; font-weight: bolder;">Sample Call:</strong></p><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li style="box-sizing: border-box;"><pre style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; margin-top: 0px; margin-bottom: 1rem; overflow: auto; display: block; color: rgb(33, 37, 41); padding: 0.75rem; white-space: pre-wrap; overflow-wrap: break-word;"><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: inherit; color: inherit; word-break: normal;">curl -X POST --url http://localhost:8000/api/v1/report_json --data "hash=82ab8b2193b3cfb1c737e3a786be363a" -H "Authorization:e085cf7084a6a497c275801eba49d1de9464bcf177b3cef0a830181265a5b7e5"
                  </code></pre></li></ul><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;">OR</p><ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li style="box-sizing: border-box;"><pre style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; margin-top: 0px; margin-bottom: 1rem; overflow: auto; display: block; color: rgb(33, 37, 41); padding: 0.75rem; white-space: pre-wrap; overflow-wrap: break-word;"><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: inherit; color: inherit; word-break: normal;">curl -X POST --url http://localhost:8000/api/v1/report_json --data "hash=82ab8b2193b3cfb1c737e3a786be363a" -H "X-Mobsf-Api-Key:e085cf7084a6a497c275801eba49d1de9464bcf177b3cef0a830181265a5b7e5"</code></pre></li></ul></li></ul>
</body>
</html>

when i use the command:

curl -X POST --url http://localhost:8000/api/v1/report_json --data "hash=82ab8b2193b3cfb1c737e3a786be363a" -H "X-Mobsf-Api-Key:e085cf7084a6a497c275801eba49d1de9464bcf177b3cef0a5a5a83018"

the answer is:

{"report": "Report not Found"}

any ideas?

**Comment by ajinabraham** [comment]
Please use slack for support
