### ISSUE TITLE
can not get icon

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/Mobile-Security-Framework-MobSF#2040]
## ENVIRONMENT

```
OS and Version: win10
Python Version: 3.9
MobSF Version: last release
```

## EXPLANATION OF THE ISSUE

```
1. static_analyzer, this app (via) can not get icon
2. via download:https://play.google.com/store/apps/details?id=mark.via.gp
```
![2022-10-01_112659](https://user-images.githubusercontent.com/1449374/193385651-b203d25c-0cf3-446f-81b5-eb8b16b8e103.jpg)

**Comment by ajinabraham** [comment]
Thanks for the fix here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/41dc60773345b4480b5a07b5215b8b15f1ef8a34
