### ISSUE TITLE
Android - Picking wrong network security config file. 

### ISSUE THREAD

**Issue by su-vikas** [MobSF/Mobile-Security-Framework-MobSF#2049]
## ENVIRONMENT

```
OS and Version: MacOS 12.6
Python Version: 3.10.7
MobSF Version: 
```

## EXPLANATION OF THE ISSUE

In APK's where `networksecurityconfig` attribute declares a filename like "another_security_config.xml" and then in _res/xml_ folder both, "network_security_config.xml" and "another_security_config.xml" is present, MobSF will choose "network_security_config.xml" file (basically whichever comes first while iterating over xml files in the folder). 

The reason being, in the code in [network_security.py,](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/StaticAnalyzer/views/android/network_security.py#L25) it is checking for presence of either declare config file name or "network_security_config", and in current case it is always choosing "network_security_config", as co-incidentally "network_security_config.xml" file is also present in the application. 

## STEPS TO REPRODUCE THE ISSUE

Can be reproduced for MyJio v7.0.19 application (https://www.apkmirror.com/apk/jio-platforms-limited/myjio/myjio-7-0-19-release/). 

In the app, the manifest declares:
```
networkSecurityConfig="@xml/network_security"
```

And application contains two network security config files:
- network_security.xml
- network_security_config.xml

MobSF will choose "network_security_config.xml"

**Comment by Gregory5555** [comment]
473b41c31bcb3b2f2ebf015db48561ad855e8b0d

**Comment by Gregory5555** [comment]
> ## ENVIRONMENT
> 
> ```
> OS and Version: MacOS 12.6
> Python Version: 3.10.7
> MobSF Version: 
> ```
> 
> ## EXPLANATION OF THE ISSUE
> 
> In APK's where `networksecurityconfig` attribute declares a filename like "another_security_config.xml" and then in _res/xml_ folder both, "network_security_config.xml" and "another_security_config.xml" is present, MobSF will choose "network_security_config.xml" file (basically whichever comes first while iterating over xml files in the folder). 
> 
> The reason being, in the code in [network_security.py,](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/StaticAnalyzer/views/android/network_security.py#L25) it is checking for presence of either declare config file name or "network_security_config", and in current case it is always choosing "network_security_config", as co-incidentally "network_security_config.xml" file is also present in the application. 
> 
> ## STEPS TO REPRODUCE THE ISSUE
> 
> Can be reproduced for MyJio v7.0.19 application (https://www.apkmirror.com/apk/jio-platforms-limited/myjio/myjio-7-0-19-release/). 
> 
> In the app, the manifest declares:
> ```
> networkSecurityConfig="@xml/network_security"
> ```
> 
> And application contains two network security config files:
> - network_security.xml
> - network_security_config.xml
> 
> MobSF will choose "network_security_config.xml"

**Comment by Gregory5555** [comment]
> 👋 @su-vikas
> Issues is only for reporting a bug/feature request. For limited support, questions, and discussions, please join [MobSF Slack channel](https://join.slack.com/t/mobsf/shared_invite/zt-153nfus2r-hMCGrwzm8Lyy3OxsihnolQ)
> Please include all the requested and relevant information when opening a bug report. Improper reports will be closed without any response.

Don't my account

**Comment by ajinabraham** [comment]
Thanks for the report. I will take a look at this and revert.

**Comment by ajinabraham** [comment]
Took a lot of time, but addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2307
