### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by antonkap** [MobSF/Mobile-Security-Framework-MobSF#2062]
## ENVIRONMENT

```
OS and Version: Ubuntu 20.04.4 LTS
Python Version: 3.8.10
MobSF Version: 3.6.1
```

## EXPLANATION OF THE ISSUE

We deployed MobSF application in kubernetes cluster(use image built from the last code version(commit [075e9c18623a78a30774391d83566e40e664eb1d](https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/075e9c18623a78a30774391d83566e40e664eb1d)) with postgres support). We use m5.2xlarge aws instance as node and EFS storage which is mounted to uploads and downloads folders. Also RDS postgres DB is used.

We set following limits in kubernetes deployment:
```
 limits:
 	cpu: 7500m
            memory: 30Gi
```

But even with this configuration we are facing performance issues and pod is restarting from time to time due to high memory consumption. Even when there isn’t any scan in progress, application can use a lot of RAM(For examle, now it’s about 10Gb).  Also we found that if we are doing some actions on UI side of application(not scanning) RAM usage increases decently.

Previously we used vm setup and faced similar issues but in this case instance stuck and we needed to reboot it.

**Comment by ajinabraham** [comment]
Can you isolate the steps or stages in analysis that causes this memory spike? MobSF uses a lots of 3rd party dependencies as well. So without isolated data, steps to reproduce this locally, we cannot debug this further.

**Comment by ajinabraham** [comment]
Closing after 25 days of no response.
