### ISSUE TITLE
Help on SSL/TLS tester in Dynamic analysis of Android-MobSF

### ISSUE THREAD

**Issue by skothandan** [MobSF/Mobile-Security-Framework-MobSF#2066]
Hi Team,

How to interpret the output of MobSF - SSL/TLS tester report as the output of testing results are showing in green ticks. Is there any way to see the logs of SSL/TLS test output. 

Attached the output screenshot for your reference. 
Note: This output looks similar for both android apps (one with ssl pining vulnerability open and another one with ssl pining vulnerability fixed).

![image](https://user-images.githubusercontent.com/98824645/199257060-efec56a1-6f9f-485f-8e34-2b4a93a258d6.png)
Need your assistance on this. Thanks.

**Comment by ajinabraham** [comment]
Please use MobSF slack channel for discussions/questions.
