### ISSUE TITLE
[FEATURE] I suggest replace IP2Location  library with geoip2 

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/Mobile-Security-Framework-MobSF#2073]
I suggest using geoip2 library instead of IP2Location, because it supports multiple languages

**Describe the solution you'd like**
IP address information display in different languages

pip install geoip2
http://dev.maxmind.com/geoip/geoip2/geolite2

**Comment by superpoussin22** [comment]
Like some other addon it will require to create an account, and provide the info in the MobSF configuration file.
can you make a PR for this new service ? thinking thta we must let the users choose which one they want to use
