### ISSUE TITLE
Add support for Apple silicon

### ISSUE THREAD

**Issue by hinddeep** [MobSF/Mobile-Security-Framework-MobSF#2075]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Android app analysis is too slow on Macs with apple silicon. That is because python 3.9 run under Rosetta. 

**Describe the solution you'd like**
The tool should support python 3.11 which natively supports apple silicon. This should expedite android app analysis. 

**Describe alternatives you've considered**

**Additional context**

**Comment by superpoussin22** [comment]
Python@3.10 already support natively Silicon

**Comment by hinddeep** [comment]
Yes, it does but the virtual environment used by MobSF doesn't. MobSF uses python 3.9 in its venv. It unsets my PATH and replaces it with its own PATH variable that points to venv containing python 3.9. I've also tried to modify run.sh to use python 3.11. However, gunicorn is not compatible with python 3.11 as it throws some errors.

**Comment by ajinabraham** [comment]
We will be able to support newer versions of python only after all our dependencies can support them.

**Comment by hinddeep** [comment]
okay, thank you for the information.
