### ISSUE TITLE
This API Level is not supported for Dynamic Analysis

### ISSUE THREAD

**Issue by Keynotey** [MobSF/Mobile-Security-Framework-MobSF#2091]
I am running mobsf dynamic analyzer and while the static analysis works pretty well the dynamic one is exiting with an error of could not connect to emulator-5554

This is my ENVIRONMENT

```
OS and Version: windows 10
Python Version: 3.8
MobSF Version: latest
```

I am trying to run the dynamic analyzer and I am getting the following error "cannot connect to emulator-5554".
On the command prompt I'm getting the following error
[ERROR] 19/Dec/2022 10:23:45 - This API Level is not supported for Dynamic Analysis.

```


This are the log details I am getting on the cmd

s', 'emulator-5554', 'remount']' returned non-zero exit status 10.
[INFO] 19/Dec/2022 10:23:45 - Performing System check
[INFO] 19/Dec/2022 10:23:45 - Android API Level identified as 33
[ERROR] 19/Dec/2022 10:23:45 - This API Level is not supported for Dynamic Analysis.
[ERROR] 19/Dec/2022 10:23:45 - Cannot Connect to emulator-5554
[ERROR] 19/Dec/2022 10:23:45 - Internal Server Error: /android_dynamic/c25d36b353ae28ccd87ad8aae4c3f717
ERROR:django.request:Internal Server Error: /android_dynamic/c25d36b353ae28ccd87ad8aae4c3f717

**Comment by superpoussin22** [comment]
take a look at documentation
Supports x86, x86_64 architecture Android 4.1 - 10.0, upto API 29

**Comment by Kongwarriors** [comment]
Currently android supports up to 15 and API35. Is there any way to use Mobsf with this device?

**Comment by mzalazar** [comment]
SLACK CHANNEL is only invitation...... I can't get support for this product, what I supposed to do now?????????? be gentile with your answer admins

**Comment by ajinabraham** [comment]
The support channel is not invite only you can join the free support slack channel by signing up for an account 

https://join.slack.com/t/mobsf/shared_invite/zt-2huaz2nj9-ifViLV7g7w1xthx5D6rGhw
