### ISSUE TITLE
[FEATURE] make gunicorn listen on ipv4 + ipv6 sockets

### ISSUE THREAD

**Issue by r3pek** [MobSF/Mobile-Security-Framework-MobSF#2109]
Right now, gunicorn is forced to bind to `0.0.0.0` which makes it only bind to ipv4 address. If docker/k8s is running on dual stack mode (or by any change, ipv6 only) the ipv6 address of the pod won't work because gunicorn doesn't lsten on the ipv6 socket.
Make it bind to `[::]` instead :wink: 

**Is your feature request related to a problem? Please describe.**
Yeah, no IPv6 replies from the service (gunicorn)

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
The alternative is to disable ipv6 for the pod/service in question

**Additional context**
see above.

**Comment by ajinabraham** [comment]
Sure, will look into this.
