### ISSUE TITLE
Information Disclosure Vulnerability in MobSF: Sensitive Information Leak due to Debug Mode Enabled

### ISSUE THREAD

**Issue by paragbagul111** [MobSF/Mobile-Security-Framework-MobSF#2119]
Description:
The issue of Django's built-in debugging features leading to information disclosure in a production environment is considered a security vulnerability.
Affected version: latest

Steps to reproduce the issue of Django's built-in debugging features leading to information disclosure:

Run the shell script using the command "bash run.sh"
Disable the shell script by pressing "Control + c"
Re-run the shell script with the command "bash run.sh"
Open your web browser and visit the URL "http://127.0.0.1:8000/". Note that by default, the MobSF web interface runs on port 8000.
When you visit the URL, you will see a debug error message from Django. This error message contains sensitive information that could be used by an attacker to launch further attacks on the application or its infrastructure.

Impact:
 The impact of this vulnerability is that an attacker may be able to gain access to sensitive information about the application and its environment, such as the version of Django being used, the structure of the database, and the details of any errors that occur. This information can be used to launch further attacks on the application or its infrastructure. 

solution:
The solution to this vulnerability is to disable debugging in production. This can be done by setting the "DEBUG" setting in the Django settings file to "False". Additionally, it's recommended to use other tools, such as logging, to track and diagnose errors in production. Furthermore, it is also important to properly secure the admin interface and any other sensitive parts of the application.

To customize the error messages displayed by Django in the event of an error, you can create a custom error page template and configure Django to use it. Here are the steps to do this:

Create a template for your custom error page in your Django project's templates directory. You can use the built-in "404.html" or "500.html" templates as a starting point.

In your Django settings file, set the "TEMPLATE_DIRS" setting to include the directory where your custom error page template is located.

In the same settings file, set the "DEBUG" setting to "False" to disable the built-in debugging features.

In your views.py, you can use the django.views.defaults.server_error function and pass your custom template to it.

You can also use the django.views.defaults.page_not_found function for 404 error page

To test your custom error page, you can trigger an error in your code or manually visit a non-existent URL on your site.

For more fine-grained control, you can also use the django.core.exceptions.handle function to handle specific exceptions and render custom templates for them.
By following these steps, you will be able to customize the error messages displayed by Django in the event of an error, and prevent the built-in debugging features from displaying sensitive information in a production environment.

About Researcher:
Name: Parag bagul
Linkedin:https://www.linkedin.com/in/parag-bagul-061440199/

![mobsf_poc10](https://user-images.githubusercontent.com/68190427/213375114-231c873a-220e-4bae-b95c-396237f7662a.png)
![mobsf_poc11](https://user-images.githubusercontent.com/68190427/213375130-e2650df7-e856-4f3b-94e4-6459393aeb16.png)
![mobsf_poc12](https://user-images.githubusercontent.com/68190427/213375152-fda4f0df-83ae-4be0-954a-955a0c96d230.png)
![mobsf_poc12](https://user-images.githubusercontent.com/68190427/213375174-62a42189-8f52-4ac0-a310-1183f4c146e8.png)
![mobsf_poc14](https://user-images.githubusercontent.com/68190427/213375196-53588cef-fa81-44b9-ab9d-4c0f60dc131b.png)

![mobbsf_poc12](https://user-images.githubusercontent.com/68190427/213374304-8ecc861f-5a12-49af-ac40-5535bc2c8eb3.png)
![mobsf2](https://user-images.githubusercontent.com/68190427/213374352-854c893a-8eb2-44c6-aa0a-517c0a43bc93.png)
![mobsf7poc](https://user-images.githubusercontent.com/68190427/213374374-c799c318-dc16-44d9-ae10-f45a1b099296.png)
![mobsf_poc1](https://user-images.githubusercontent.com/68190427/213374411-cac14769-ed35-49e1-8067-b241a05b4822.png)
![mobsf_poc5](https://user-images.githubusercontent.com/68190427/213374432-cdc86909-0bf5-4ff6-8c74-eee8e92065f6.png)
![mobsf_poc6](https://user-images.githubusercontent.com/68190427/213374449-db20d6f2-fb2a-44c5-a6a5-06fc34f86c77.png)
![mobsf_poc8](https://user-images.githubusercontent.com/68190427/213374475-3f965d3d-e135-4154-a6a2-93a3c4a95acc.png)
![mobsf_poc9](https://user-images.githubusercontent.com/68190427/213374493-b2812880-31ea-49ff-b344-8569b0da9654.png)

**Comment by superpoussin22** [comment]
if you change the value in settings.py to False , it should solve your issue 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/MobSF/settings.py#L153

**Comment by paragbagul111** [comment]
its bug and security misconfiguration the debug mode should be set as false by default

**Comment by ajinabraham** [comment]
Hi @paragbagul111 MobSF is self hosted application distributed as a web app. We are in Beta and want to collect any or all exceptions from the users for easy troubleshooting and hence using Debug mode.
