### ISSUE TITLE
Android Task Hijacking Check

### ISSUE THREAD

**Issue by ITmustang** [MobSF/Mobile-Security-Framework-MobSF#2124]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
in the android manifest checks, it does mention 'singleTask' but could be expanded. if an android activity is marked with 'singleTask' the activity has the risk of being hijacked. Android allows activities from different apps to co-reside in the same Task and this is the main cause of the vulnerability. a malicious app could be installed on device that hijacks a legitimate app's activities.

**Describe the solution you'd like**
have a finding mentioned about this. and its solution
1. Set the launchMode to singleInstance which will prevent other activities from becoming a part of it's task.
2. An additional boolean attribute can be introduced for each app to decide if it allows the activities from other apps to have the same affinity as the app

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.usenix.org/conference/usenixsecurity15/technical-sessions/presentation/ren-chuangang
https://medium.com/mobis3c/android-task-hijacking-6a3a8848f16e
https://blog.dixitaditya.com/android-task-hijacking

**Comment by ajinabraham** [comment]
Took us a while, but this will be addressed once https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2307 gets merged.
