### ISSUE TITLE
i facing this issue in more then Android version 5 how to solve this issue i  peresently using android version 7

### ISSUE THREAD

**Issue by Naveenrasu** [MobSF/Mobile-Security-Framework-MobSF#2125]
[INFO] 30/Jan/2023 17:22:11 - Mobile Security Framework v3.6.3 Beta
REST API Key: fec17e4993dff450c009737e914708b579a7ee1c8de6cad44b5d9d5dc2afcc93
[INFO] 30/Jan/2023 17:22:11 - OS: Windows
[INFO] 30/Jan/2023 17:22:11 - Platform: Windows-10-10.0.22000-SP0
[INFO] 30/Jan/2023 17:22:11 - MobSF Basic Environment Check
[INFO] 30/Jan/2023 17:22:14 - Checking for Update.
[INFO] 30/Jan/2023 17:22:14 - No updates available.
[INFO] 30/Jan/2023 17:22:46 - Creating Dynamic Analysis Environment for com.amtex.imahila.emathi
[WARNING] 30/Jan/2023 17:22:46 - Failed to get Activities. Static Analysis not completed for the app.
[INFO] 30/Jan/2023 17:22:51 - ADB Restarted
[INFO] 30/Jan/2023 17:22:51 - Waiting for 2 seconds...
[INFO] 30/Jan/2023 17:22:53 - Connecting to Android 127.0.0.1:21523
[INFO] 30/Jan/2023 17:22:53 - Waiting for 2 seconds...
[INFO] 30/Jan/2023 17:22:55 - Restarting ADB Daemon as root
[INFO] 30/Jan/2023 17:22:55 - Waiting for 2 seconds...
[INFO] 30/Jan/2023 17:22:57 - Reconnecting to Android Device
[INFO] 30/Jan/2023 17:22:58 - Waiting for 2 seconds...
[WARNING] 30/Jan/2023 17:23:00 - Unable to identify Dynamic Analysis environment. Official support is available only for Android Emulator, Corellium, and Genymotion
[INFO] 30/Jan/2023 17:23:00 - Remounting
[INFO] 30/Jan/2023 17:23:00 - Performing System check
[INFO] 30/Jan/2023 17:23:00 - Android API Level identified as 25
[INFO] 30/Jan/2023 17:23:01 - Android Version identified as 7.1
[INFO] 30/Jan/2023 17:23:01 - Environment MobSFyed Check
[INFO] 30/Jan/2023 17:23:01 - Installing MobSF RootCA
[INFO] 30/Jan/2023 17:23:02 - Starting HTTPs Proxy on 1337
[INFO] 30/Jan/2023 17:23:10 - Enabling ADB Reverse TCP on 1337
[INFO] 30/Jan/2023 17:23:10 - Setting Global Proxy for Android VM
[INFO] 30/Jan/2023 17:23:11 - Starting Clipboard Monitor
[INFO] 30/Jan/2023 17:23:11 - Getting screen resolution
[INFO] 30/Jan/2023 17:23:11 - Testing Environment is Ready!
[INFO] 30/Jan/2023 17:23:25 - Starting Instrumentation
[INFO] 30/Jan/2023 17:23:25 - Starting Frida Server
[INFO] 30/Jan/2023 17:23:25 - Waiting for 2 seconds...
[ERROR] 30/Jan/2023 17:23:28 - Error Connecting to Frida
Traceback (most recent call last):
  File "C:\Users\Hoote\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\views\android\frida_core.py", line 130, in connect
    pid = device.spawn([self.package])
  File "C:\Users\Hoote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Hoote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\frida\core.py", line 157, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: need Gadget to attach on jailed Android; its default location is: C:\Users\Hoote\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\AC\INetCache\frida\gadget-android-arm64.so

**Comment by Five81** [comment]
Have you solved this problem? I encountered the same problem, how did you solve it?
