### ISSUE TITLE
MobSF APK installation fails "adb install" on genymotion

### ISSUE THREAD

**Issue by manhfutaco** [MobSF/Mobile-Security-Framework-MobSF#2127]
[INFO] 31/Jan/2023 15:55:09 - Creating Dynamic Analysis Environment for com.ftlvn.mts.shs
[INFO] 31/Jan/2023 15:55:14 - ADB Restarted
[INFO] 31/Jan/2023 15:55:14 - Waiting for 2 seconds...
[INFO] 31/Jan/2023 15:55:16 - Connecting to Android 192.168.204.101:5555
[INFO] 31/Jan/2023 15:55:16 - Waiting for 2 seconds...
[INFO] 31/Jan/2023 15:55:18 - Restarting ADB Daemon as root
[INFO] 31/Jan/2023 15:55:18 - Waiting for 2 seconds...
[INFO] 31/Jan/2023 15:55:20 - Reconnecting to Android Device
[INFO] 31/Jan/2023 15:55:20 - Waiting for 2 seconds...
[INFO] 31/Jan/2023 15:55:22 - Found Genymotion x86 Android VM
[INFO] 31/Jan/2023 15:55:22 - Remounting
[INFO] 31/Jan/2023 15:55:22 - Performing System check
[INFO] 31/Jan/2023 15:55:22 - Android API Level identified as 29
[INFO] 31/Jan/2023 15:55:22 - Android Version identified as 10.0
[INFO] 31/Jan/2023 15:55:22 - Environment MobSFyed Check
[INFO] 31/Jan/2023 15:55:22 - Installing MobSF RootCA
[INFO] 31/Jan/2023 15:55:22 - Starting HTTPs Proxy on 1337
[INFO] 31/Jan/2023 15:55:24 - Killing httptools UI
[INFO] 31/Jan/2023 15:55:26 - Enabling ADB Reverse TCP on 1337
[INFO] 31/Jan/2023 15:55:26 - Setting Global Proxy for Android VM
[INFO] 31/Jan/2023 15:55:27 - Starting Clipboard Monitor
[INFO] 31/Jan/2023 15:55:27 - Getting screen resolution
[INFO] 31/Jan/2023 15:55:27 - Installing APK - com.ftlvn.mts.shs
[INFO] 31/Jan/2023 15:55:29 - Removing Global Proxy for Android VM
[ERROR] 31/Jan/2023 15:55:29 - This APK cannot be installed. Is this APK compatible the Android VM/Emulator?
adb install failed
[ERROR] 31/Jan/2023 15:55:29 - Internal Server Error: /android_dynamic/bacccbddc54734c5c46199c12bcb2790
ERROR:django.request:Internal Server Error: /android_dynamic/bacccbddc54734c5c46199c12bcb2790
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 2.5
MobSF Version: 3.6.2 beta
Genymotion: 3.2
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1.  I have replace adb default of Genymotion 3.3.2 but not resolves.
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
please use slack channel
