### ISSUE TITLE
iOS Source bug: needs more info to verify

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#2132]
## ENVIRONMENT

```
OS and Version: Mac NA
Python Version: 2.9
MobSF Version: 3.6.2
```

## EXPLANATION OF THE ISSUE

```
* iOS zip source code with .m objective c files does not show `scan completed` even when it is completed.
* Suppression logic fails
```
```
checksum: 7bfa370a843de307ed8325bf2c85e32d
rule: ios_swift_log
type: code
```
```
{
    "status": "failed",
    "message": "Invalid Parameters"
}
```

## STEPS TO REPRODUCE THE ISSUE

```
Reported by Damien Suggs
Verified internally, package shared in slack DM 
```

## LOG FILE

```
NA
```

**Comment by ajinabraham** [comment]
After further investigation, it looks like the iOS source code ZIP after analysis does not return a package name. A package name is required to mark the scan as complete (which we will be relaxing) and it is crucial for suppression feature. Without package name available from source code, suppression feature cannot work.

**Comment by caesium55ds** [comment]
Ahhh....got it.  Thank you so much for looking into this.  I will supply a package name in GitHub...see where we go from there.

**Comment by caesium55ds** [comment]
Hello Ajin.  It’s been a couple of weeks since we chatted last.  The developer has made the necessary changes in the meta-data for the code, and it is still failing:
![](https://files.slack.com/files-pri/T0QMJH7PA-F04TM4F8J21/image.png)

**Comment by ajinabraham** [comment]
MobSF is unable to identify the package name. It looks at couple of files to guess the identifier.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/6c64d17229164d15458290921216e7834a4719f9/mobsf/StaticAnalyzer/views/ios/plist_analysis.py#L48-L90
You can see an empty identifier in the screenshot above. Where exactly is the identifier information added by the developer?

**Comment by caesium55ds** [comment]
Thank you sir….I will get back to you.

{"Damien Suggs": {
"company": "Caesium55 LLC",
"position": "Sr. Application Security Architect", "cell" : "(404)819-9989"
“office”:”(770)423-1903”}}


From: Ajin Abraham ***@***.***>
Reply-To: MobSF/Mobile-Security-Framework-MobSF ***@***.***>
Date: Wednesday, March 15, 2023 at 9:22 PM
To: MobSF/Mobile-Security-Framework-MobSF ***@***.***>
Cc: Damien Suggs ***@***.***>, Comment ***@***.***>
Subject: Re: [MobSF/Mobile-Security-Framework-MobSF] iOS Source code multiple bugs (Issue #2132)


MobSF is unable to identify the package name. It looks at couple of files to guess the identifier.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/6c64d17229164d15458290921216e7834a4719f9/mobsf/StaticAnalyzer/views/ios/plist_analysis.py#L48-L90
You can see an empty identifier in the screenshot above. Where exactly is the identifier information added by the developer?

**Comment by ajinabraham** [comment]
Closing this due to 25 days of inactivity.
