### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by Ezyhoo** [MobSF/Mobile-Security-Framework-MobSF#2134]
## ENVIRONMENT

```
OS and Version: ubuntu:20.04
Python Version: 3.9
MobSF Version: 3.6 beta
```

unable to do a docker build:
#0 8.742          cwd: /tmp/pip-install-syurx1dd/http-tools/
#0 8.742     Complete output (3 lines):
#0 8.742     error in http-tools setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
#0 8.742         mitmproxy>=6.0.0<=6.0.2

## LOG FILE
https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions/runs/4131201026/jobs/7138625908#step:6:1701

**Comment by ajinabraham** [comment]
Thanks for the report. I will take a look at this.
