### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by edevane** [MobSF/Mobile-Security-Framework-MobSF#2144]
## ENVIRONMENT

```
OS and Version: latest Docker container image - d5cdd4b2ab28
Python Version: Python 3.8
MobSF Version: 3.6.3 beta
Xcode version: 14.2
```

## EXPLANATION OF THE ISSUE
```
Hello, I'm facing error when uploading the Xcode project for static analysis. 
This issue persist for my existing Xcode project as well as brand new Storyboard-based Xcode project. 
PRODUCT_BUNDLE_IDENTIFIER exist for both existing and brand new Xcode project.

I've posted this issue in the Slack channel as well.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Spin up latest docker image (opensecurity/mobile-security-framework-mobsf)
2. Zip Xcode project with the .xcodeproj file in root directory.
3. Upload zip file to static analysis.
```

## LOG FILE

```
[WARNING] 17/Mar/2023 08:37:24 - Error in parsing .pbxproj
[ERROR] 17/Mar/2023 08:37:24 - Reading from Info.plist
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/plist_analysis.py", line 169, in plist_analysis
    plist_info['id'] = get_bundle_id(plist_obj, src)
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/plist_analysis.py", line 91, in get_bundle_id
    return min(possible_ids, key=len)
ValueError: min() arg is an empty sequence
[ERROR] 17/Mar/2023 08:37:24 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/static_analyzer.py", line 222, in static_analyzer_ios
    app_dict['appstore'] = app_search(infoplist_dict.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 17/Mar/2023 08:37:24 - 'NoneType' object has no attribute 'get'
[ERROR] 17/Mar/2023 08:37:24 - Internal Server Error: /static_analyzer_ios/
```

**Comment by ajinabraham** [comment]
Can you share a package that can reproduce this issue? Looks like this is caused at the bundle id extraction logic, so it must be a .xcodeproj/.plist file causing it.

**Comment by edevane** [comment]
> Can you share a package that can reproduce this issue? Looks like this is caused at the bundle id extraction logic, so it must be a .xcodeproj/.plist file causing it.

Yes. Here's an empty project that I used to reproduce the issue: [TestProject.zip - Google Drive](https://drive.google.com/file/d/1j4DfLlYKLM-nzd8VYRZKfrGddUz3AUEa/view?usp=sharing).

**Comment by pddkhanh** [comment]
Hi @ajinabraham , I'm facing the same issue with this. I found your fix in [this commit](https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/bfef7e6285068662f5a24ab4055b5f8fafeca0c4), there is another line that will cause exception when reading the bundleId from pbxproj file at [line 84](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/c7578b8735f7ce91d0668b33b9c04ec73095cd2b/mobsf/StaticAnalyzer/views/ios/plist_analysis.py#LL84C33-L84C43) 

Could you help to check please?
