### ISSUE TITLE
Obfuscation and finding a PKCS5/PKCS7 issue.

### ISSUE THREAD

**Issue by seanleblanc** [MobSF/Mobile-Security-Framework-MobSF#2146]
If we scan an Android APK that has had obfuscation turned on, it finds
the following issue:

"[The App uses the encryption mode CBC with PKCS5/PKCS7 padding. This
configuration is vulnerable to padding oracle
attacks.](https://github.com/MobSF/owasp-mstg/blob/master/Document/0x04g-Testing-Cryptography.md#identifying-insecure-andor-deprecated-cryptographic-algorithms-mstg-crypto-4)"

However, without obfuscation turned on, it does not find this high at all.

`public class s {
     public static BiometricPrompt.c a() {
         try {
             KeyStore keyStore = KeyStore.getInstance("AndroidKeyStore");
             keyStore.load(null);
             KeyGenParameterSpec.Builder a2 = a.a("androidxBiometric", 3);
             a.i(a2);
             a.j(a2);
             KeyGenerator keyGenerator = KeyGenerator.getInstance("AES",
"AndroidKeyStore");
             keyGenerator.init(a2.build());
             keyGenerator.generateKey();
             Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding");
             cipher.init(1, (SecretKey)
keyStore.getKey("androidxBiometric", null));
             return new BiometricPrompt.c(cipher);
         } catch (IOException | InvalidAlgorithmParameterException |
InvalidKeyException | KeyStoreException | NoSuchAlgorithmException |
NoSuchProviderException | UnrecoverableKeyException |
CertificateException | NoSuchPaddingException unused) {
             return null;
         }
     }`

**Comment by ajinabraham** [comment]
This is the pattern that MobSF checks for https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/93432c961a6799673f155974462d972cfc3a6049/mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml#L641-L642

If the exact pattern is not present in the decompiled java/ source code files, it will not detect the finding. Please use MobSF slack channel for discussions and troubleshooting.

**Comment by nguyenvanan18031993** [comment]
Hi @seanleblanc  @ajinabraham 
I have the same issue. Do you know if we have a solution?
