### ISSUE TITLE
Failed to MobSFy Android Instance

### ISSUE THREAD

**Issue by Jane151013** [MobSF/Mobile-Security-Framework-MobSF#2166]
Hi all:
   I've installed MobSF and genymotion，the static analysis is work well，but dynamic analysis have an error.
The environment:
win10
mobsf:3.6.5-beta
genymotion：3.3.3
The error log:
[INFO] 18/Apr/2023 19:24:13 - Performing Static Analysis of Android APK
[INFO] 18/Apr/2023 19:24:13 - Scan Hash: 3761283e531fc1e56abf5294877ea64e
[INFO] 18/Apr/2023 19:24:13 - Starting Analysis on: inocube_1.0.13.apk
[INFO] 18/Apr/2023 19:24:13 - Analysis is already Done. Fetching data from the DB...
[INFO] 18/Apr/2023 19:24:13 - Scan Hash: 3761283e531fc1e56abf5294877ea64e
[INFO] 18/Apr/2023 19:24:13 - Starting Analysis on: inocube_1.0.13.apk
[INFO] 18/Apr/2023 19:24:13 - Analysis is already Done. Fetching data from the DB...
[INFO] 18/Apr/2023 19:26:30 - Creating Dynamic Analysis Environment for com.inovance.inocube
[INFO] 18/Apr/2023 19:26:35 - ADB Restarted
[INFO] 18/Apr/2023 19:26:35 - Waiting for 2 seconds...
[INFO] 18/Apr/2023 19:26:37 - Connecting to Android 192.168.199.102:5555
[INFO] 18/Apr/2023 19:26:37 - Waiting for 2 seconds...
[INFO] 18/Apr/2023 19:26:39 - Restarting ADB Daemon as root
[INFO] 18/Apr/2023 19:26:40 - Waiting for 2 seconds...
[INFO] 18/Apr/2023 19:26:42 - Reconnecting to Android Device
[INFO] 18/Apr/2023 19:26:42 - Waiting for 2 seconds...
[INFO] 18/Apr/2023 19:26:45 - Found Genymotion x86 Android VM
[INFO] 18/Apr/2023 19:26:45 - Remounting
[INFO] 18/Apr/2023 19:26:45 - Performing System check
[INFO] 18/Apr/2023 19:26:45 - Android API Level identified as 29
[INFO] 18/Apr/2023 19:26:45 - Android Version identified as 10.0
[INFO] 18/Apr/2023 19:26:45 - Environment MobSFyed Check
cat: /system/.mobsf-f: No such file or directory
[WARNING] 18/Apr/2023 19:26:46 - This Android instance is not MobSFyed/Outdated.
MobSFying the android runtime environment
[INFO] 18/Apr/2023 19:26:46 - Android Version identified as 10.0
[INFO] 18/Apr/2023 19:26:46 - Android OS architecture identified as x86
[INFO] 18/Apr/2023 19:26:46 - Copying frida server for x86
[ERROR] 18/Apr/2023 19:26:47 - Failed to MobSFy Android Instance
Traceback (most recent call last):
  File "D:\Program Files\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\views\android\environment.py", line 558, in mobsfy_init
    self.mobsf_agents_setup('frida')
  File "D:\Program Files\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\views\android\environment.py", line 568, in mobsf_agents_setup
    self.install_mobsf_ca('install')
  File "D:\Program Files\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\views\android\environment.py", line 188, in install_mobsf_ca
    mobsf_ca = get_ca_file()
  File "D:\Program Files\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\tools\webproxy.py", line 73, in get_ca_file
    create_ca()
  File "D:\Program Files\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\tools\webproxy.py", line 59, in create_ca
    subprocess.Popen(argz,
  File "D:\Program Files\Python\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Program Files\Python\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[ERROR] 18/Apr/2023 19:26:47 - Failed to MobSFy the instance
[ERROR] 18/Apr/2023 19:26:47 - Internal Server Error: /android_dynamic/3761283e531fc1e56abf5294877ea64e
ERROR:django.request:Internal Server Error: /android_dynamic/3761283e531fc1e56abf5294877ea64e

I've tried to set environment variable PATH and add the dir of adb.exe in genymotion.And set 
ADB_BINARY = 'D:\Program Files\Genymobile\Genymotion\tools\adb.exe'
 in .MobSF\config.py.But both on help with this error.

**Comment by Jane151013** [comment]
> 👋 @Jane151013 Issues is only for reporting a bug/feature request. For limited support, questions, and discussions, please join [MobSF Slack channel](https://join.slack.com/t/mobsf/shared_invite/zt-153nfus2r-hMCGrwzm8Lyy3OxsihnolQ) Please include all the requested and relevant information when opening a bug report. Improper reports will be closed without any response.

bug

**Comment by Jane151013** [comment]
I think it's a bug

**Comment by ajinabraham** [comment]
` Failed to MobSFy Android Instance` this happens probably due to a windows file lock. You can just retry dynamic analysis/ MobSFy to fix this.

Please use slack for support. Closing this thread.

**Comment by Jane151013** [comment]
First of all,thank you for your answers.
But I have tried several times to retry dynamic analysis or restart MobSF,neither can solve the problem.Then I tried reinstall mitmproxy/mitmdump with the same version,unfortunately,the problem is still there.
In fact,I am worry about this log:
cat: /system/.mobsf-f: No such file or directory
What's this,and why there is no this file or directory
At last,I'm sorry to ask that:What's the meaning of：
Please use slack for support. Closing this thread

**Comment by Jane151013** [comment]
I'm sorrry for I can't use or join Slack though the Internet of my country.Maybe the github is the only methord to asking for help

**Comment by ajinabraham** [comment]
> But I have tried several times to retry dynamic analysis or restart MobSF,neither can solve the problem.Then I tried reinstall mitmproxy/mitmdump with the same version,unfortunately,the problem is still there.

Have you installed it inside the virtualenv?
You can also manually run the following to create CA cert

`mitmdump -n`

and then do the following to verify that ca certs and pems are created.

`ls ~/.mitmproxy/`
 ```     
mitmproxy-ca-cert.cer mitmproxy-ca-cert.p12 mitmproxy-ca-cert.pem mitmproxy-ca.p12      mitmproxy-ca.pem      mitmproxy-dhparam.pem
```

If the above commands doesn't work then your installation of mitmproxy/mitmdump is incorrect. Otherwise, try running dynamic analysis again.

> In fact,I am worry about this log:
> cat: /system/.mobsf-f: No such file or directory
> What's this,and why there is no this file or directory

This file is created only if mobsfy is successful. In your case ca certs are not available and hence the file is not created and not found.

**Comment by Jane151013** [comment]
Thank you for your answers.
Firstly,I reinstall mitmdump and mitmproxy inside the venv.
Secondly,I have tried to run "mitmdump -p 8008" inside the venv and tried to cd the dir of "~/.mitmproxy/",but the venv return the dir is not exist.
Maybe you are right,installation is incorrect.But reinstall is useless too.
So,should I reinstall Mobsf?Or any thing else I can do to make the installation of mitmdump&mitmproxy right?

**Comment by ajinabraham** [comment]
The correct version of mitmproxy has to be installed and the certs has to be generated for this to work. Reinstalling MobSF might help, but not guaranteed.

**Comment by Jane151013** [comment]
Thank you for your answers.
I know the importance of mitmproxy and certs，but I don't know whic version is correct.
The version of mitmproxy in Mobsf is mitmproxy is 6.0.2,is it right?
By the way,when I installed Mobsf,I saw some errors as below:

> flask 1.1.4 requires click<8.0,>=5.1, but you'll have click 8.0.1 which is incompatible.
> mitmproxy 6.0.2 requires asgiref<3.4,>=3.2.10, but you'll have asgiref 3.6.0 which is incompatible.
> mitmproxy 6.0.2 requires click<8,>=7.0, but you'll have click 8.0.1 which is incompatible.
> ipython 8.12.0 requires prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30, but you'll have prompt-toolkit 3.0.19 which is incompatible.
I'm not sure weather thease errors will lead to the failure of mitmproxy and cert generation.I have tried to install Mobsf in other computer,the error is the same.Cause both Django and mitmproxy depend on asgiref,but not the same version.

**Comment by ajinabraham** [comment]
Yes 6.0.2 is the correct version. You can ignore the incompatibly warnings. This doesn't affect the mitmproxy features that MobSF requires. After a successful install inside the venv, you should be able to run mitmproxy.
```
(venv) ➜  Mobile-Security-Framework-MobSF git:(master) ✗ mitmproxy --version
Mitmproxy: 6.0.2
Python:    3.10.8
OpenSSL:   OpenSSL ***
Platform:  macOS-13.3.1-x86_64-i386-64bit
```

**Comment by Jane151013** [comment]
Thank you for your answers.
It seems like the mitmproxy is successful install inside venv:
(venv) D:\Program Files\Mobile-Security-Framework-MobSF\venv\Scripts>mitmdump --version

> Mitmproxy: 6.0.2
> Python:    3.8.9
> OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
> Platform:  Windows-10-10.0.17763-SP0

Moreover,the default port of mitmproxy is occupied by another procedure.So if it started in MobSF at default port of 8080,I think it will fail.
So,should I modify another port of mitmproxy with some configuration when MobSF started?

**Comment by Jane151013** [comment]
@ajinabraham,I'm happy to tell you that the problem is solved.
The reason of this problem is because the port of 8080 is occupied by another procedure.After I stop the procedure,this error is gone
Thank you for all your help
