### ISSUE TITLE
[FEATURE] iOS Need binary code analysis detail info like android

### ISSUE THREAD

**Issue by Tobey0328** [MobSF/Mobile-Security-Framework-MobSF#2188]
When conducting binary code analysis and encountering an issue, there would be detailed information provided for that issue, such as file paths and specific code details. 

However, now only the description of the issue is available, making it difficult to quickly identify the problem and determine if it is a false positive. 

I hope the next version can include these details. 

Thank you.

**Comment by ajinabraham** [comment]
Android APKs can be decompiled back to source code/equivalent. iOS produces object code and cannot be decompiled back to source code and hence you see limited information.

**Comment by Tobey0328** [comment]
iOS cannot be decompiled back to the source code, so it is impossible to directly access the original code. However, additional information about the inspection process should be provided to ensure a thorough check.

As for MobSF, it detects the usage of "malloc" in a program and identifies it as a high-risk issue. I would like more information about how MobSF checks for this issue and the additional information it provides when detecting such issues.
