### ISSUE TITLE
Timeframe on stable releases?

### ISSUE THREAD

**Issue by theoretick** [MobSF/Mobile-Security-Framework-MobSF#2189]
Hi there! Thanks for maintaining an amazing tool.

Hope this question is okay for the issue tracker but I thought discovery might be a bit better than Slack (and maybe some docs could come out of it). 

Is there a timeframe on mobsf releases?

For `v3.6.0` stable, I noticed [the most recent one](https://github.com/MobSF/Mobile-Security-Framework-MobSF/releases) is from 8 months ago and missing some hotfixes [like this one](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/2144). I couldn't find any Projects, Milestones, or Issues tracking version completion so figured I'd ask if there's a signaling mechanism or way it's documented that I'm missing.

Thanks in advance!

**Comment by ajinabraham** [comment]
There is no fixed timeframe for releases. Usually a new major version is released when there are multiple feature additions and or critical bug fixes. 

The latest changes are pushed to `master` branch which is also versioned (for minor bug fixes) but not released as such. We cut stable releases when we are comfortable with the major changes in master branch over a period of time and after it is functioning in a stable manner.

**Comment by theoretick** [comment]
Got it, thanks for clarifying!
