### ISSUE TITLE
Scan devices in a network via REST API

### ISSUE THREAD

**Issue by EvilWatermelon** [MobSF/Mobile-Security-Framework-MobSF#2190]
Hi,

I'm want to use the REST API to scan devices in a local network. Is it possible to scan them by accessing them via IP address?

**Comment by ohyeah521** [comment]
I didn't understand the problem you described. Do you want to scan the apk file of the mobile phone in the LAN or scan the apk file in the shared folder in the LAN?

**Comment by ajinabraham** [comment]
Please use slack for support.
