### ISSUE TITLE
[FEATURE] Enhancing secret detection with regex rules

### ISSUE THREAD

**Issue by ksg97031** [MobSF/Mobile-Security-Framework-MobSF#2191]
Hello,

I believe that simply searching for keywords like 'api' or 'key' is insufficient when trying to detect a secret. Have you considered using regular expression rules to detect secret patterns?

As you are already know, it's quite simple to find an example demonstrating the implementation of this approach.
https://github.com/dwisiswant0/apkleaks/blob/master/config/regexes.json

**Comment by ohyeah521** [comment]
Regularity is indeed a good strategy, but it will increase system overhead. If the apk file is large and a single smali file exceeds 5m, the matching speed will be extremely slow

**Comment by ajinabraham** [comment]
Tracked separately.
