### ISSUE TITLE
[FEATURE] Optimizing the Storage of Privileges in the Database

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/Mobile-Security-Framework-MobSF#2192]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

The dvm_permissions.py file stores the permission description of the apk. When a large number of apks are stored in the database, the description information will be a large amount of repeated data, resulting in a larger and larger database. Therefore, it is recommended to store the contents of this file in the database, and then reference it with a foreign key
 
**Describe the solution you'd like**

```
 class DVMPermission(models.Model):
    name = models.CharField(max_length=50, primary_key=True) # 权限的名称，如SEND_SMS
    level = models.CharField(max_length=10) # 权限的等级，如危险
    description = models.CharField(max_length=255) # 权限的描述，如发送短信
    explanation = models.CharField(max_length=255) # 权限的解释，如允许应用程序发送短信

class StaticAnalyzerAndroid(models.Model):
     PERMISSIONS = models.ManyToManyField(DVMPermission) # 使用ManyToManyField
     ..............

```

In this way, you can reduce a large amount of repeated text in DVM_PERMISSIONS in the database, and improve the standardization and maintainability of the data.

**Comment by ajinabraham** [comment]
Tracked separately.
