### ISSUE TITLE
[FEATURE] Support non-default XMLNS attribute in androidManifest.xml

### ISSUE THREAD

**Issue by JonasH-polestar** [MobSF/Mobile-Security-Framework-MobSF#2198]
**Is your feature request related to a problem? Please describe.**
Some APKs seemingly has a different naming scheme for things that usually are prefixed with `android:xxxx`, this prevents mobsf from properly listing things such as used permissions etc.  
At present I am unsure whether this comes from the build process of the APK itself, or if it comes from the tooling underneath mobsf to extract the manifest.

**Describe the solution you'd like**
Preferably MobSF would read the XMLNS attached to `http://schemas.android.com/apk/res/android` instead of using the hardcoded `android:` prefix.

**Describe alternatives you've considered**
I took a look at the source code to figure out whether the prefix was hard coded in MobSF, and it does seem to be the case looking at https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/dc0dc273e520d6bf2949e75fcf8dc10e27866b30/mobsf/StaticAnalyzer/views/android/manifest_analysis.py#L97

**Additional context**
I am not sure whether linking APK mirrors here are allowed, but for testing I used Vivaldi Browser 6.1.3035.102 of the x86_64 architecture.

MobSF version: c7578b87 (jun 14)

**Comment by ajinabraham** [comment]
Thanks for reporting will add this to the backlog.

**Comment by ajinabraham** [comment]
@JonasH-polestar  this is addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2248/files
