### ISSUE TITLE
【error】 Internal Server Error: /static_analyzer/

### ISSUE THREAD

**Issue by gitamorning** [MobSF/Mobile-Security-Framework-MobSF#2202]
install on windows 10
could not open file "Mobile-Security-Framework-MobSF-master\venv\Lib\site-packages\apkid\rules\rules.yarc" 

Internal Server Error: /static_analyzer/

 Error Performing Static Analysis

**Comment by Y-LyN-10** [comment]
I can confirm that the issue persists with Arch Linux / Blackarch - on a very fresh & updated installation.

**Comment by baptx** [comment]
Maybe this will help you:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/2294#issuecomment-1912444624

**Comment by dr-r00t3r** [comment]
I have the same problem and won't use docker. 
I upgrade all package in arch not work
