### ISSUE TITLE
Uninstall Steps Needed

### ISSUE THREAD

**Issue by W0lfbane** [MobSF/Mobile-Security-Framework-MobSF#2206]
I have installed MobSF without docker to do a DAST scan. I am trying to figure out how to uninstall at this point now that I no longer need MobSF for the time being, however there are no steps provided for this.

I would like to see some entries in the documentation for remove MobSF installed without docker.

**Comment by ajinabraham** [comment]
This a python web app, to remove you can just delete the source code directory and remove the data directory `~/.MobSF`. Please use slack for support.
