### ISSUE TITLE
Add to recent scan db not working in scanning.py

### ISSUE THREAD

**Issue by flamecopper** [MobSF/Mobile-Security-Framework-MobSF#2208]
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(32)

I am actually using postgresql sql. can advise what could be the problem?

mobsf=# SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'StaticAnalyzer_recentscansdb';
 column_name  |        data_type         
--------------+--------------------------
 ANALYZER     | character varying
 SCAN_TYPE    | character varying
 FILE_NAME    | character varying
 APP_NAME     | character varying
 PACKAGE_NAME | character varying
 VERSION_NAME | character varying
 MD5          | character varying
 TIMESTAMP    | timestamp with time zone
(8 rows)

**Comment by ajinabraham** [comment]
Thanks for reporting. We normally have our developer setup using sqlite and never had this issue before.
Postgres seems to complain about an over 32 character long field. MD5 is the field that has this restriction https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/3c7c9afecd2ba6cd51dd860112331ce352a4b692/mobsf/StaticAnalyzer/models.py#L14

I am not sure why this is a problem with postgresql, MD5 hashes have a max char length of 32.
May be you can increase the char length in the models and try again with postgres.

cc: @superpoussin22  who worked on adding postgres support.

**Comment by superpoussin22** [comment]
can you provide more details ?
does it occur with all apk or only with one ?

**Comment by ajinabraham** [comment]
Passed the response window of 25 days.
