### ISSUE TITLE
Tool being used for inappropiate reasons

### ISSUE THREAD

**Issue by muskanf** [MobSF/Mobile-Security-Framework-MobSF#2212]
Hello. I have noticed the tool being used for child p*rnography apps. Please add a feature of verification thing to prevent this from happening.

**Comment by ajinabraham** [comment]
Thanks for reporting this. Unfortunately `mobsf.live` is a public demo instance and anyone can upload binaries or source code there. We do not have any control on what gets uploaded. However, we remove all the uploads in periodic intervals.
