### ISSUE TITLE
Unable to install Mobsf on Macbook pro

### ISSUE THREAD

**Issue by kpratik9** [MobSF/Mobile-Security-Framework-MobSF#2215]
ERROR: Cannot install -r requirements.txt (line 23), -r requirements.txt (line 25), click==8.0.1 and http-tools because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested click==8.0.1
    androguard 3.4.0a1 depends on click>=7.0
    quark-engine 23.5.1 depends on click
    mitmproxy 6.0.2 depends on click<8 and >=7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: Skipping /usr/local/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/local/lib/python3.11/site-packages/protobuf-4.21.12-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/local/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/local/lib/python3.11/site-packages/protobuf-4.21.12-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/local/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/local/lib/python3.11/site-packages/protobuf-4.21.12-py3.11.egg-info due to invalid metadata entry 'name'

**Comment by ajinabraham** [comment]
Please follow the updated documentation https://mobsf.github.io/docs/#/mobsf_docker

Also please use slack for support
