### ISSUE TITLE
Dynamic Analyser for iOS 

### ISSUE THREAD

**Issue by iTestOS** [MobSF/Mobile-Security-Framework-MobSF#2216]
There is no support for Dynamic Analyser for iOS 

Can you guys please confirm?

**Comment by ajinabraham** [comment]
Please use MobSF slack channel for discussions and questions.

iOS Dynamic Analysis is not supported yet, but will soon land in MobSF
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2194
