### ISSUE TITLE
Update python support for 3.11 version

### ISSUE THREAD

**Issue by Dazmed707** [MobSF/Mobile-Security-Framework-MobSF#2221]
![pp](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/35184132/5ec77f46-627c-401e-9ada-f8dabbef6b4a)

**Comment by ajinabraham** [comment]
We have updated setup instructions. see https://mobsf.github.io/docs/#/mobsf_docker

please use slack for support
