### ISSUE TITLE
It is impossible to learn how to use this tool from the documentation

### ISSUE THREAD

**Issue by djcvijic** [MobSF/Mobile-Security-Framework-MobSF#2223]
Documentation is very lacking, from a usage perspective, especially for first-time users. It is impossible to learn how to use this tool from the documentation.

After approx 1.5 hours of scouring the "usage" and "getting started" and "docker options" sections of documentation, I was unable to find what to do after running the docker image. I kept trying to find out how to pass my .APK file to the docker command, but did not find anything similar.

After I delegated this to a colleague, and he tinkered for a bit, and after some trial and error he realized that this is a WEB TOOL, which after running the tool in the CLI, you must visit a page in the browser, and continue from there. After reading the full documentation, it contained only CLI steps, so I assumed this was a CLI tool.

Issues:
* The documentation makes no mention that this is a web tool, which must be visited in the browser
* The documentation contains no screenshots or usage steps exactly how to analyze your APK files

**Comment by ajinabraham** [comment]
Fair enough!
Addressed in https://github.com/MobSF/docs/pull/21
