### ISSUE TITLE
dashboard not found

### ISSUE THREAD

**Issue by b0fhb0fh** [MobSF/Mobile-Security-Framework-MobSF#2238]
## ENVIRONMENT

```
OS and Version: macOS Ventura 13.5
Python Version: 3.9.6
MobSF Version: 3.7
```

## EXPLANATION OF THE ISSUE

```
Dashboard not found after installation 
I tried 2 different ways 
1. as in Readme.md
docker pull opensecurity/mobile-security-framework-mobsf:latest
docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

2. docker compose up

Results are the same : 

Not Found: /dashboard/

```
[INFO] 16/Aug/2023 13:50:06 - Mobile Security Framework v3.7.3 Beta
[INFO] 16/Aug/2023 13:50:06 - OS: Linux
[INFO] 16/Aug/2023 13:50:06 - Platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.29
[INFO] 16/Aug/2023 13:50:06 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 16/Aug/2023 13:50:06 - MobSF Basic Environment Check
[WARNING] 16/Aug/2023 13:50:06 - Not Found: /dashboard/
[INFO] 16/Aug/2023 13:50:07 - Checking for Update.
[INFO] 16/Aug/2023 13:50:07 - No updates available.
[WARNING] 16/Aug/2023 14:06:49 - Not Found: /dashboard/

**Comment by b0fhb0fh** [comment]
This is bug. Version 3.4.3 worked without problems

**Comment by ajinabraham** [comment]
MobSF doesn’t have a route named /dashboard 

Please see the official docs, use slack for support.
