### ISSUE TITLE
AAR Scan via API Fails

### ISSUE THREAD

**Issue by rmkanda** [MobSF/Mobile-Security-Framework-MobSF#2253]
## ENVIRONMENT

```
MobSF Version: v3.6.9 Beta
```

## EXPLANATION OF THE ISSUE
AAR Scan via UI works fine, when we do the same via API calls it fails.

## Steps

1. Used /upload API to upload the aar
2. After upload used the /scan endpoint with scan_type as 'aar'
3. Recieved a HTML error page in response

Looking at the API docs seems it is not supported.
<img width="1441" alt="image" src="https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/38713281/c1101640-6e34-4001-bad9-cea4644e4a1e">

**Comment by ajinabraham** [comment]
Can you try using the latest mater branch or MobSF v3.7.7. The API docs are outdated. There were some recent changes made to support API scans of AAR/JAR.

**Comment by rmkanda** [comment]
Sure @ajinabraham let me try with new version and update you.

**Comment by ajinabraham** [comment]
This should be supported in latest master.
