### ISSUE TITLE
[FEATURE] when rescan finished,remove rescan=1 argument

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/Mobile-Security-Framework-MobSF#2261]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.
 do a redirect without rescan parameter after the scan is completed.
 
example:
https://mobsf.live/static_analyzer/?checksum=hash&name=minAPI9.apk&type=apk&rescan=1
when rescan finished, redirect to https://mobsf.live/static_analyzer/?checksum=hash&name=minAPI9.apk&type=apk

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2260/commits/196e4503536e2ac24fd19529dc16301088f31b38
