### ISSUE TITLE
"wkhtmltopdf reported an error:\nExit with code 1 due to network error: ContentNotFoundError\r\n"

### ISSUE THREAD

**Issue by rnb2kool** [MobSF/Mobile-Security-Framework-MobSF#2270]
Hello,

I am facing "wkhtmltopdf reported an error:\nExit with code 1 due to network error: ContentNotFoundError\r\n" issue while Generating Report. The screenshot of log has been attached. My OS is Windows 10. 
![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/145319144/1a70f5c0-89ca-418c-a305-1d9ad04cd495)

**Comment by ajinabraham** [comment]
Can you use the docker image instead? That's the recommend way to setup MobSF on Windows.
https://mobsf.github.io/docs/#/mobsf_docker
