### ISSUE TITLE
Dynamic Analyzer > Pull & Static Analysis fails with split apks

### ISSUE THREAD

**Issue by jonathanbheadley** [MobSF/Mobile-Security-Framework-MobSF#2271]
## ENVIRONMENT

```
OS and Version: Kali Linux, 6.5.0-kali1-amd64
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2023.3
Codename:	kali-rolling

Python Version: Python 3.9.16
MobSF Version:  MobSF v3.7.8 Beta
```

## EXPLANATION OF THE ISSUE

The "Pull & Static Analysis" button fails to pull an app with split apks. MobSF seems to be running `adb pm path com.coinhako` and then running `adb pull <result>` which improperly parses out the multiline return value:

![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/65432843/bbb7e00b-3255-4c57-883c-7845ee07fcfa)

![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/65432843/19b24187-9a3d-4868-8621-493509e82491)

## STEPS TO REPRODUCE THE ISSUE

1. Start Mobsf: `sudo docker run --network="host" -it --rm -p 8000:8000 -p 1337:1337 -e MOBSF_ANALYZER_IDENTIFIER="emulator-5554" -e MOBSF_PLATFORM="somethingelse" opensecurity/mobile-security-framework-mobsf:latest`

2. Navigate to Dynamic Analyzer tab
3. Click Pull & Static Analysis button

## LOG FILE

For some reason, both debug files in ~/.MobSF and /root/.MobSF (since i'm using sudo) are empty...

I couldn't upload the apk(s), files were too large: https://play.google.com/store/apps/details?id=com.coinhako&hl=en_US&gl=US

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/2446/commits/14d48df0c3b9c26401488c01a458af1ff0bca62e
