### ISSUE TITLE
Running MobSF against adb daemon on MacOS physical host

### ISSUE THREAD

**Issue by phydroxide** [MobSF/Mobile-Security-Framework-MobSF#2274]
Consider the scenario of Mac Devices

https://twosixtech.com/blog/integrating-docker-and-adb/

When I cannot connect direct to USB from a docker container on OSX I will want to start ADB as a daemon on the host and use the network to list the device. 

I gather your flow requires a bunch of recovery work if it loses the device, so we have to handle it by stopping and starting the adb daemon.

 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/abb47659a19ac772765934f184c65fe16cb3bee7/mobsf/DynamicAnalyzer/views/android/environment.py#L85-L86

However I would like a way to use the host's daemon because I can mount the device that way

```
docker run --rm -it \
  -e ANDROID_ADB_SERVER_ADDRESS=host.docker.internal \
  -e ANDROID_ADB_SERVER_PORT=5037 \
  --add-host=host.docker.internal:host-gateway \
  -e MOBSF_ANALYZER_IDENTIFIER=4c38584d38593398 \
  -e MOBSF_VT_ENABLED="False" \
  -e MOBSF_VT_UPLOAD="False" \
  -p 8000:8000 \
  mobsf
```

https://github.com/twosixtech/demo-integrating-docker-and-adb

```
mobsf@02101d6f08b2:~/Mobile-Security-Framework-MobSF$ adb devices
List of devices attached
4c38584d38593398	device
```

Somehow your logic doesn't see it, and restarts the server and picks that one up instead. Any suggestions to check for this scenario?

**Comment by ajinabraham** [comment]
We do not officially support real devices at this time. See supported options for Dynamic Analysis here:
https://mobsf.github.io/docs/#/dynamic_analyzer
