### ISSUE TITLE
oscrypto / openSSL regex bug when running setup.sh

### ISSUE THREAD

**Issue by SpookyB00k** [MobSF/Mobile-Security-Framework-MobSF#2286]
## ENVIRONMENT

```
OS and Version: Kali Linux Rolling Release 6.5.0-kali3-amd64
Python Version: 3.11.6
MobSF Version: 3.7.9 Beta
```

## EXPLANATION OF THE ISSUE

When trying to install MobSF with the provided setup.sh, you may run into the issue that the install fails because it is unable to detect the version of libcrypto.
![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/37688484/adf1704c-3261-4c27-8be2-bcddf9b02a59)
When working with versions that are higher or equal than 3.0.10 of OpenSSL, the Regex used to detect does not work.
Currently it is 
```
\b(\d\.\d\.\d[a-z]*)\b
```

Personally I monkeypatched /home/Sp00kyB00k/.cache/pypoetry/virtualenvs/mobsf-vfi9xHNf-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_cffi.py to which is far from perfect but good enough to get the install rolling.
```
\b(\d\.\d\.\d+[a-z]*)\b
```
Adding the extra + with the last digit should fix it. 

## STEPS TO REPRODUCE THE ISSUE

Install on Kali Linux by cloning the repository and running the setup.sh

**Comment by danilabs** [comment]
Awesome @SpookyB00k you save me a lot of time :clap: !
Thank you!

**Comment by ajinabraham** [comment]
We are removing oscrypto dependency from MobSFv3.8 onwards. That should address this.

**Comment by baptx** [comment]
Thanks, the solution worked.
For information, I also had an error "externally-managed-environment" that I fixed by modifying setup.sh to add `--break-system-packages` at the end of each pip line.
More details here: https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3/75722775#75722775
