### ISSUE TITLE
When high >= 2 and sec == 1，the secure score is positively correlated with warnings

### ISSUE THREAD

**Issue by johnxguo** [MobSF/Mobile-Security-Framework-MobSF#2293]
![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/10493206/8788c964-62a6-4c4f-863a-4c8e94b6f957)

e.g., if sec == 1, high == 4, the equation is like this: y = 1 - (3.8 + x*0.5) / (5+x)，and it's graph is:
![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/10493206/70a1103e-5b63-4213-9a86-0ad1d3b5bd44)

it means that more warnings lead to higher secure score

can you improve the method of calculation

**Comment by ajinabraham** [comment]
Will track this under https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1940
