### ISSUE TITLE
[FEATURE] use the websocket protocol to display analysis progress related logs in real time on the front end, providing better visual progress information.

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/Mobile-Security-Framework-MobSF#2303]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

After the user submits the apk file, he does not know the current execution step, because I want to use the websocket protocol to display the analysis progress related logs in real time on the front end to provide better visual progress information.

**Comment by ajinabraham** [comment]
Not top priority, tracking this separately.

**Comment by ajinabraham** [comment]
Not using websockets, but realtime logs are now available.
