### ISSUE TITLE
EXECUTION ISSUE IN WINDOW as "no such file or directory' for entrypoint.sh"

### ISSUE THREAD

**Issue by Er-shivam11** [MobSF/Mobile-Security-Framework-MobSF#2321]
Execution Error: 'no such file or directory' for entrypoint.sh in Docker Container

OS : window

Dockerfile:

last line:

CMD ["/home/mobsf/Mobile-Security-Framework-MobSF/scripts/entrypoint.sh"]

**Comment by ajinabraham** [comment]
Please use github for support
