### ISSUE TITLE
iOS Dynamic Analyzer - Generate Report disabled

### ISSUE THREAD

**Issue by HackJJ** [MobSF/Mobile-Security-Framework-MobSF#2330]
## ENVIRONMENT

```
OS and Version: MacBook Pro M2 Sonoma
Python Version: 3.12
MobSF Version:v3.9.3 Beta
```

## EXPLANATION OF THE ISSUE

The 'Generate Button' is always disabled for iOS dynamic analysis no matter what action I perform

## STEPS TO REPRODUCE THE ISSUE

```
1. Go to http://127.0.0.1:8000/ios/dynamic_analysis/
2. Select "Start dynamic analysis" for the app
3. I run the app and perform actions but the'Generate Report' button is always disabled
```

**Comment by HackJJ** [comment]
This is an issue. This functionality does not work. Once you click on "Spawn and Inject" the "Generate Button" appears but the report is never successful and there are no Frida logs.

**Comment by ajinabraham** [comment]
Please use slack for triaging.

**Comment by HackJJ** [comment]
I've tried but getting no response.
