### ISSUE TITLE
Fetching data from DB stucks in an infinite loop after a successful scan

### ISSUE THREAD

**Issue by EvilWatermelon** [MobSF/Mobile-Security-Framework-MobSF#2334]
When an analysis is done and the scan is stored to the DB then it's not possible to load the UI correctly because the query seems to stuck in an infinite loop.

```log
[...]
[INFO] 06/Feb/2024 12:37:34 - Saving to Database
[INFO] 06/Feb/2024 12:37:40 - Scan Hash: Some Hash
[INFO] 06/Feb/2024 12:37:40 - Starting Analysis on: Some APK
[INFO] 06/Feb/2024 12:37:40 - Analysis is already Done. Fetching data from the DB...
``` 

I have to restart the Docker container every time while this happens in order to see the scan results in a fully loaded UI. 

MobSF Version: 3.9
OS Environment: Linux (ubuntu 22.04 Jammy Jellyfish) Linux-6.1.0-17-amd64-x86_64-with-glibc2.35

**Comment by ajinabraham** [comment]
Please use slack for debugging this.
