### ISSUE TITLE
How to show login screen on MobSF

### ISSUE THREAD

**Issue by uthens** [MobSF/Mobile-Security-Framework-MobSF#2338]
Hi team, 

I implement on the server and setup to public domain and it's worked, 
and I have plan to implent with our CI.

But our security team **concern** and we need to know how to show login screen first it's possible and support on this case or not ?

We don't want to show main screen for everybody it's security case and policy issue.
We do not want just anybody accessing it.

And also i tested on this repo on Mac, but it's don't work can't setup : 
https://github.com/MobSF/RP4MobSF

![Screenshot 2567-02-09 at 14 36 24](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/10783170/ae649c8b-6ad2-44fc-a462-07516110691d)

Best,
Uthen

**Comment by uthens** [comment]
Don't work on this link : https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/748

**Comment by ajinabraham** [comment]
We do not support authentication for MobSF.

**Comment by AkutoSai** [comment]
> We do not support authentication for MobSF. Please use slack channel for discussions.

![image](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/36693722/9bdaa323-76b5-453d-a7c4-9acc4b597e38)

How to sign-in/configure this

**Comment by ajinabraham** [comment]
Authentication is now supported. see docs.

**Comment by ahmedtarek0908** [comment]
hi,
i am having an issue with login screen . cant find where to sign in

**Comment by AzhariRamadhan** [comment]
> hi, i am having an issue with login screen . cant find where to sign in

same problem here after pull

**Comment by jfloodnet** [comment]
Now need to add this line







`   -e MOBSF_DISABLE_AUTHENTICATION=1 \`

```
docker run -it --rm \
    -p 8000:8000 \
    -p 1337:1337 \
    -e MOBSF_ANALYZER_IDENTIFIER=<id> \
    -e MOBSF_DISABLE_AUTHENTICATION=1 \
    opensecurity/mobile-security-framework-mobsf:latest
```

**Comment by captping** [comment]
The default credentials for mobsf are: mobsf/mobsf which can be found at https://mobsf.github.io/docs/#/mobsf_docker
