### ISSUE TITLE
Git clone and issue while running application

### ISSUE THREAD

**Issue by hari-id** [MobSF/Mobile-Security-Framework-MobSF#2340]
## ENVIRONMENT

```
OS and Version: MacOS Ventura 13.4 (22F66)
Python Version: python 3.11
MobSF Version: v3.9
```

## EXPLANATION OF THE ISSUE

I have cloned the MobSF, trying to run the application as instructed under readme section throws error  No module named poetry. Poetry of version 1.1.0 is already installed.

## STEPS TO REPRODUCE THE ISSUE

```
1. git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
2. cd Mobile-Security-Framework-MobSF
3. created virtual python environment of version 2.11
4. Running command ./run.sh
5. Throws error No module named poetry. unable to run the application 
```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
what do you mean by 2.11 , only Python 3 is supported 
did you run setup.Sh ?
which os ?
did you read the doc for the requierements ? https://mobsf.github.io/docs/#/develop?id=static-analysis

**Comment by hari-id** [comment]
Able to install. Working now

**Comment by williamwrsa** [comment]
> Able to install. Working now

Hi,

Please, can you tell me how you solved the problem?
