### ISSUE TITLE
Datatables export function, when exporting a file, the Chinese in the file is garbled

### ISSUE THREAD

**Issue by ohyeah521** [MobSF/Mobile-Security-Framework-MobSF#2342]
## ENVIRONMENT

```
OS and Version: win10
Python Version: 3.10
MobSF Version: 3.9.4
```

## STEPS TO REPRODUCE THE ISSUE

```
Datatables export function, when exporting a file, the Chinese in the file is garbled.
```

**Comment by ohyeah521** [comment]
this project may help:  
[](https://github.com/tekintian/vfs_fonts.js-build-tools)

**Comment by ajinabraham** [comment]
I have difficulty understanding the documentation. Do you mind sending a PR?

This [commit](https://reports.exodus-privacy.eu.org/en/trackers/312/) towards the end has the file and code changes for data tables export support

**Comment by ohyeah521** [comment]
@ajinabraham i'll try.

**Comment by ajinabraham** [comment]
Tracked separately.
