### ISSUE TITLE
"ANDROID_8_0_LEVEL" is substituted where "minSdkVersion" should be substituted.

### ISSUE THREAD

**Issue by watanabemk** [MobSF/Mobile-Security-Framework-MobSF#2343]
Target file:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/StaticAnalyzer/views/android/manifest_analysis.py
Applicable line:

```
# Android Task Hijacking or StrandHogg 1.0
try:
    target_sdk = int(man_data_dic['target_sdk'])
except Exception:
    target_sdk = ANDROID_8_0_LEVEL     ←★This line
if (target_sdk < ANDROID_9_0_LEVEL
        and launchmode == 'singleTask'):
    ret_list.append(('task_hijacking', (item,), (target_sdk,)))
```
basis:
[Androiddocument](https://developer.android.com/guide/topics/manifest/uses-sdk-element?hl=en)
android:targetSdkVersion
An integer designating the API level that the application targets. If not set, the default value equals that given to minSdkVersion.
solution:
Based on the above, it is expected that by assigning "ANDROID_LEVEL" that corresponds to "minSdkVersion" to the variable "target_sdk", detection will be made in accordance with the actual situation.

**Comment by ajinabraham** [comment]
More context: 
https://mobsf.slack.com/archives/C0QMLNKMF/p1707273779008299

Related: https://github.com/MobSF/mobsfscan/issues/78
