### ISSUE TITLE
[FEATURE] Android Manifest String resource expansion

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#2345]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Items with @string should be expanded based on string resource.

**Describe the solution you'd like**
For now document items that can make use of string expansion.

**Describe alternatives you've considered**

**Additional context**

**Comment by ajinabraham** [comment]
applinks [ERROR] 24/Feb/2024 01:47:07 - Well Known Assetlinks Check for URL: https://@string/wk_server_address/.well-known/assetlinks.json

**Comment by ayushmanchhabra** [comment]
Am I correct to assume that the `@string/*` is a reference to the values in the `res/values/strings.xml` file?

**Comment by ajinabraham** [comment]
Tracked separately
