### ISSUE TITLE
Tests failing for Binskim and Binscope in StaticAnalysis

### ISSUE THREAD

**Issue by Mardigas** [MobSF/Mobile-Security-Framework-MobSF#2349]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: Python 3.11.4
MobSF Version: v3.9.4
```

## EXPLANATION OF THE ISSUE

Binskim and Binscope arguments are being passed to [subprocess_hook](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f20ee08a68de14fdfc91dc7caf2b166b010558c2/mobsf/MobSF/security.py#L138) from [windows.py binskim function](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f20ee08a68de14fdfc91dc7caf2b166b010558c2/mobsf/StaticAnalyzer/views/windows/windows.py#L301) and [windows.py binscope function](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f20ee08a68de14fdfc91dc7caf2b166b010558c2/mobsf/StaticAnalyzer/views/windows/windows.py#L470) as a tuple with string inside it, instead of a tuple containing list. In result it throws an TypeError when trying to parse executable name from params.
```
Args in subprocess hook currently:  ('\\MobSF\\Tools\\Microsoft.CodeAnalysis.BinSkim.1.7.2\\tools\\netcoreapp3.1\\win-x64\\BinSkim.exe analyze \\.MobSF\\uploads/8179b557433835827a70510584f3143e/AppStudio.exe --verbose -o \\.MobSF\\uploads/8179b557433835827a70510584f3143e/AppStudio.exe_binskim --config default --force',)

Should be: (['\\MobSF\\Tools\\Microsoft.CodeAnalysis.BinSkim.1.7.2\\tools\\netcoreapp3.1\\win-x64\\BinSkim.exe', 'analyze', '\\.MobSF\\uploads/8179b557433835827a70510584f3143e/AppStudio.exe', '--verbose', 
'-o', '\\.MobSF\\uploads/8179b557433835827a70510584f3143e/AppStudio.exe_binskim', '--config', 'default', '--force'],)
```

I think the problem is the use of subprocess.list2cmdline function in mentioned lines [here](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f20ee08a68de14fdfc91dc7caf2b166b010558c2/mobsf/StaticAnalyzer/views/windows/windows.py#L301) and [here](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f20ee08a68de14fdfc91dc7caf2b166b010558c2/mobsf/StaticAnalyzer/views/windows/windows.py#L470), because without it everything seemed to work correctly

**Comment by ajinabraham** [comment]
I will take a look at this when I get some time. Thanks for reporting and sharing the details here.
