### ISSUE TITLE
False positive for compiled Dart code

### ISSUE THREAD

**Issue by Olaw2jr** [MobSF/Mobile-Security-Framework-MobSF#2358]
EXPLANATION OF THE ISSUE
Shared objects should use fortified functions warning for compiled Dart code (e.g., Flutter's libpp.so)

MobSF detects a missing fortified function call in a shared object, but this might be a false positive for compiled Dart code. Dart code doesn't directly interact with libc functions; it uses the Dart standard library.

WHY THIS MIGHT BE A FALSE POSITIVE
MobSF checks for functions with a _chk suffix, fortified functions in glibc. Since Dart code doesn't use these functions, MobSF misinterprets it as non-fortified calls.

STEPS TO REPRODUCE (if applicable)
This step might not be applicable as it's a potential false positive.

Compile Dart code into a shared object (e.g., Flutter app)
Run MobSF analysis on the shared object

**Comment by ajinabraham** [comment]
The newer MobSF versions already warns in the report for Fortify Checks.
" This check is not applicable for Dart/Flutter libraries."
<img width="304" alt="Screenshot 2024-03-18 at 10 58 47 AM" src="https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/4301109/c424a883-4558-4163-94ca-4a5cf804dd9a">
