### ISSUE TITLE
docker install fails

### ISSUE THREAD

**Issue by captainkyd** [MobSF/Mobile-Security-Framework-MobSF#2360]
## ENVIRONMENT
i'm using wsl to call the "docker compose up"
```
OS and Version: win 11 with kali rolling wsl
Python Version: 3.11.8
MobSF Version: whatever one can pull from this git
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```
So runnign "docker compose up" builds the instance ok, however when it comes to running it I get this error

docker compose up
[+] Running 2/2
 ✔ Container mobile-security-framework-mobsf-postgres-1  Recreated                                                                                                                                                                                                       0.7s
 ✔ Container mobile-security-framework-mobsf-mobsf-1     Recreated                                                                                                                                                                                                       0.3s
Attaching to mobsf-1, postgres-1
postgres-1  | 
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  | 
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8000 -> 0.0.0.0:0: listen tcp 0.0.0.0:8000: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

To clarify, I don't have anything running on port 8000 currently. In fact I have even deleted several docker containers to ensure they weren't getting in the way. Not sure what is going on here or why the error occurs, but yeah 

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**Comment by ajinabraham** [comment]
docker compose require configuration before running. The default docker setup instructions are available here:
https://mobsf.github.io/docs/#/mobsf_docker
