### ISSUE TITLE
linux/arm64 image for latest tag missing

### ISSUE THREAD

**Issue by wczarnecki** [MobSF/Mobile-Security-Framework-MobSF#2361]
When trying to run using docker:
docker run -it --rm --name mobsf -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
I get following error:
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

One week ago it was working fine. Any reason for missing linux/arm64 image for latest tag?

**Comment by ajinabraham** [comment]
The latest arm image publishing is broken due to androguard update which depends on pyqt5 which is not available on ARM64 as a binary dist nor they publish an sdist.

```
  • Installing pyqt5-qt5 (5.15.2)
#12 89.04 
#12 89.04   RuntimeError
#12 89.04 
#12 89.04   Unable to find installation candidates for pyqt5-qt5 (5.15.2)
#12 89.04 
#12 89.04   at /usr/local/lib/python3.10/dist-packages/poetry/installation/chooser.py:73 in choose_for
#12 89.15        69│ 
#12 89.15        70│             links.append(link)
#12 89.15        71│ 
#12 89.15        72│         if not links:
#12 89.15     →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
#12 89.15        74│ 
#12 89.16        75│         # Get the best link
#12 89.16        76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
#12 89.16        77│ 
#12 89.16 
```

**Comment by ajinabraham** [comment]
This should be addressed now.

**Comment by wczarnecki** [comment]
Yes, it's working fine, thank you for support :)
