### ISSUE TITLE
dynamic analyse

### ISSUE THREAD

**Issue by Al0ne-collab** [MobSF/Mobile-Security-Framework-MobSF#2371]
when i run dynamic analyze to app i got error:
``[ERROR] 02/Apr/2024 15:16:33 - Executable/Library Tampering Detected``
full output:
```
[INFO] 02/Apr/2024 15:15:59 - Connecting to Android 127.0.0.1:5555
[WARNING] 02/Apr/2024 15:16:00 - Executable [/usr/lib/android-sdk/platform-tools/adb] not found in known hashes, skipping runtime executable tampering detection
[ERROR] 02/Apr/2024 15:16:33 - Executable/Library Tampering Detected
```
emulator: ``Pixel_XL_API_26``

**Comment by Al0ne-collab** [comment]
solved

**Comment by IrvanWijayaSardam** [comment]
i having the same issue, how do you solve this ?

**Comment by ryankwonguy** [comment]
Hello @Al0ne-collab, can you share the resolution you made to solve this issue?
