### ISSUE TITLE
[FEATURE] SHA256 hash after a POST request

### ISSUE THREAD

**Issue by taaaahahaha** [MobSF/Mobile-Security-Framework-MobSF#2375]
After a  POST request has been sent using REST api; a MD5 hash is returned.
Due to this, a rare occur but two apk's have a better chance of getting overlapped using this MD5.
If SHA256 is being retuned, gives a better chance for scanning the uploaded apks

**Comment by ajinabraham** [comment]
We are aware of MD5 hash collision. Do you have an example that caused an issue? Will keep this as an enhancement ticket to migrate from MD5 to sha2 or similar.

**Comment by ajinabraham** [comment]
Tracked separately.

**Comment by ajinabraham** [comment]
Duplicate https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1930

**Comment by taaaahahaha** [comment]
I was using AndroZoo's APK library and this collision caused an inconsistency in my dataset; 
I do not have the APK at the moment.
