### ISSUE TITLE
Unable to start Dynamic Analysis

### ISSUE THREAD

**Issue by osabri009** [MobSF/Mobile-Security-Framework-MobSF#2376]
I run the MobSF via the docker command and use Genymotion as my Android emulator. But I can't get the Dynamic analyzer to work. Every time I run it, I get "Dynamic Analysis Failed.". 

Here is the logs 
[ERROR] 14/Apr/2024 05:27:12 - Dynamic Analysis Failed.
[ERROR] 14/Apr/2024 05:27:12 - Internal Server Error: /android_dynamic/7686782abefaaf8c0db276d93226cc3a
[INFO] 14/Apr/2024 05:27:16 - Connecting to Android adb://192.168.56.101:5555
[INFO] 14/Apr/2024 05:27:16 - Waiting for 2 seconds...
[ERROR] 14/Apr/2024 05:27:18 - Error Running ADB Command
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/views/android/environment.py", line 167, in adb_command
    result = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/adb', '-s', 'adb://192.168.56.101:5555', 'shell', 'getprop', 'ro.build.version.release']' returned non-zero exit status 1.
[INFO] 14/Apr/2024 05:27:23 - Creating Dynamic Analysis Environment for com.shia.Testapp
[INFO] 14/Apr/2024 05:27:26 - ADB Restarted
[INFO] 14/Apr/2024 05:27:26 - Waiting for 2 seconds...
[INFO] 14/Apr/2024 05:27:28 - Connecting to Android adb://192.168.56.101:5555
[INFO] 14/Apr/2024 05:27:28 - Waiting for 2 seconds...
[INFO] 14/Apr/2024 05:27:30 - Restarting ADB Daemon as root
adb: unable to connect for root: device 'adb://192.168.56.101:5555' not found
[ERROR] 14/Apr/2024 05:27:30 - Dynamic Analyzer

**Comment by emilyanncr** [comment]
Do this:
docker pull opensecurity/mobile-security-framework-mobsf:latest
docker run -e MOBSF_ANALYZER_IDENTIFIER='IP:5555' -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

The MOBSF analyzer identifier is the IP of the phone and can be found by going to the emulated phone's settings -> Wifi -> Double click on the Wifi button, expand the 'Advanced' options section -> IP

**Comment by ajinabraham** [comment]
Please use slack for support.

**Comment by osabri009** [comment]
I’m unable to join the slack for support. It says I need to be invited

Thanks,
Omar Sabri
Computer Science Engineering
CND | EHCS | CEH | CIH | CHFI
Master in Cyber Security
419.450.0693
***@***.******@***.***>
***@***.******@***.***>

[University of Toledo Logo]

________________________________

**Comment by ben-tanto** [comment]
What might be useful is ensuring ADB is listening on `tcpip` mode then running docker in `host` mode to ensure TCP comms are simpler. This may help:

1. Start AVD
2. Reconnect to AVD using tcp `adb connect 0.0.0.0:5555`
3. Start mobsf in host mode so we can directly connect to adb
`docker run -it --net=host --rm -e MOBSF_ANALYZER_IDENTIFIER="0.0.0.0:5555" opensecurity/mobile-security-framework-mobsf:latest`
