### ISSUE TITLE
Recent Scan Bug

### ISSUE THREAD

**Issue by flamecopper** [MobSF/Mobile-Security-Framework-MobSF#2379]
## ENVIRONMENT

```
OS and Version: Ubuntu Latest
Python Version: 24.0
MobSF Version: 3.9 Beta
```

This has been happening in all the recent scan code for all the feature:

oReverseMatch at /recent_scans/
Reverse for 'appsec_dashboard' with keyword arguments '{'checksum': '3b4d462b8cce5f377a33417e1be7680717065f280a9f6e2f6af49325dbe89411'}' not found. 1 pattern(s) tried: ['appsec_dashboard/(?P<checksum>[0-9a-f]{32})/$']
Request Method:	GET
Request URL:	http://127.0.0.1:8000/recent_scans/
Django Version:	5.0.4
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'appsec_dashboard' with keyword arguments '{'checksum': '3b4d462b8cce5f377a33417e1be7680717065f280a9f6e2f6af49325dbe89411'}' not found. 1 pattern(s) tried: ['appsec_dashboard/(?P<checksum>[0-9a-f]{32})/$']
Exception Location:	/home/alvoo/.cache/pypoetry/virtualenvs/mobsf-WOMRtHg9-py3.10/lib/python3.10/site-packages/django/urls/resolvers.py, line 851, in _reverse_with_prefix
Raised during:	mobsf.MobSF.views.home.recent_scans
Python Executable:	/home/xxxx/.cache/pypoetry/virtualenvs/mobsf-WOMRtHg9-py3.10/bin/python
Python Version:	3.10.12
Python Path:	
['/home/alvoo/.cache/pypoetry/virtualenvs/mobsf-WOMRtHg9-py3.10/bin',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/home/alvoo/.cache/pypoetry/virtualenvs/mobsf-WOMRtHg9-py3.10/lib/python3.10/site-packages',
 '/home/alvoo/Mobile-Security-Framework-Mob

**Comment by ohyeah521** [comment]
Are you kidding? This is not an md5 value.  3b4d462b8cce5f377a33417e1be7680717065f280a9f6e2f6af49325dbe89411

**Comment by ajinabraham** [comment]
search currently supports only MD5
