### ISSUE TITLE
Our Application always shows  "App Keeps Stopping" error in Android emulator.

### ISSUE THREAD

**Issue by jAmEeN786** [MobSF/Mobile-Security-Framework-MobSF#2382]
Issue 2: Our Application always shows  "App Keeps Stopping" error in Android emulator.

Issue description: I successfully connect with genymotion emulator and our application is installed in android emulator as well as displayed in emulator also.

But when I'm trying to open my application in emulator, That always shows "App keeps stopping" error popup message.SO, To analyse it ,I opened the logs and check the error message. But I cant analyze the root cause for that issue.

I attached the screenshot of error popup message and as well as log checks also.

Error logs:
05-02 06:47:01.149 715 2263 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=xxxxxxxxxxxxxxxxxxxxxxx bnds=[290,914][540,1242]} from uid 10083\n'
 05-02 06:47:01.363 715 746 I ActivityManager: Start proc 9565:cxxxxxxxx/u0a101 for activity {cxxxxxxxx/cxxxxxxxx.MainActivity}\n'
 05-02 06:47:02.129 9565 9605 W GooglePlayServicesUtil: cxxxxxxxx requires the Google Play Store, but it is missing.\n'
 05-02 06:47:02.438 9565 9565 I RenderThread: type=1400 audit(0.0:195): avc: denied { write } for name="property_service" dev="tmpfs" ino=8477 scontext=u:r:untrusted_app:s0:c101,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=1 app=cxxxxxxxx\n'
 05-02 06:47:02.438 9565 9565 I RenderThread: type=1400 audit(0.0:196): avc: denied { connectto } for path="xxxxxxxx" scontext=u:r:untrusted_app:s0:c101,c256,c512,c768 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1 app=cxxxxxxxx\n'
 05-02 06:47:02.484 9565 9619 I FA : adb shell setprop dxxxxxxxx cxxxxxxxx\n'
 05-02 06:47:03.220 9565 9565 E FlutterLoader: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: xxxxxxxxDexPathList[[zip file "/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk"],nativeLibraryDirectories=[/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/lib/x86, /data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk!/lib/x86, /system/lib, /system/product/lib, /system/vendor/lib]]] couldn\'t find "libflutter.so"\n'
 05-02 06:47:03.220 9565 9565 E FlutterLoader: Caused by: java.lang.UnsatisfiedLinkError: xxxxxxxxDexPathList[[zip file "/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk"],nativeLibraryDirectories=[/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/lib/x86, /data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk!/lib/x86, /system/lib, /system/product/lib, /system/vendor/lib]]] couldn\'t find "libflutter.so"\n'
 05-02 06:47:03.221 9565 9565 E AndroidRuntime: Process: cxxxxxxxx, PID: 9565\n'
 05-02 06:47:03.221 9565 9565 E AndroidRuntime: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: xxxxxxxxDexPathList[[zip file "/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk"],nativeLibraryDirectories=[/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/lib/x86, /data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk!/lib/x86, /system/lib, /system/product/lib, /system/vendor/lib]]] couldn\'t find "libflutter.so"\n'
 05-02 06:47:03.221 9565 9565 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: xxxxxxxxDexPathList[[zip file "/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk"],nativeLibraryDirectories=[/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/lib/x86, /data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk!/lib/x86, /system/lib, /system/product/lib, /system/vendor/lib]]] couldn\'t find "libflutter.so"\n'
 05-02 06:47:03.221 9565 9565 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: xxxxxxxxDexPathList[[zip file "/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk"],nativeLibraryDirectories=[/data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/lib/x86, /data/app/cxxxxxxxx-Vp_L7JCfk5SkESplRvrm5g==/base.apk!/lib/x86, /system/lib, /system/product/lib, /system/vendor/lib]]] couldn\'t find "libflutter.so"\n'
 05-02 06:47:03.224 715 2263 W ActivityTaskManager: Force finishing activity xxxxxxxxxxxxxxxxxxxxxxx\n'
 05-02 06:47:03.278 715 2261 I ActivityManager: Process cxxxxxxxx (pid 9565) has died: fore TOP \n'
 05-02 06:47:03.726 715 739 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{dcf3844 u0 xxxxxxxxxxxxxxxxxxxxxxx t-1 f}\n'
 05-02 06:47:03.910 448 448 E Layer : [Surface(name=AppWindowToken{xxxxxxxx token=Token{xxxxxxxx u0 xxxxxxxxxxxxxxxxxxxxxxx t18}}})/@0xd05233f - animation-leash#0] No local sync point found\n'
 05-02 06:47:03.910 448 448 E Layer : [Surface(name=AppWindowToken{xxxxxxxx token=Token{xxxxxxxx u0 xxxxxxxxxxxxxxxxxxxxxxx t18}}})/@0xd05233f - animation-leash#0] No local sync point found\n'

**Comment by ajinabraham** [comment]
Please use slack for support.
