### ISSUE TITLE
[FEATURE] Integrate apkleaks

### ISSUE THREAD

**Issue by security-companion** [MobSF/Mobile-Security-Framework-MobSF#2385]
**Is your feature request related to a problem? Please describe.**
I would like to see API-endpoints integrated in an app I am analyzing.

**Describe the solution you'd like**
My suggestion is to integrate https://github.com/dwisiswant0/apkleaks and show its output in MobSF

**Comment by ajinabraham** [comment]
> API-endpoints integrated 

MobSF already shows this under URLs during both static and dynamic analysis.
