### ISSUE TITLE
Login screen in v4.0 MobSF

### ISSUE THREAD

**Issue by iremclk** [MobSF/Mobile-Security-Framework-MobSF#2388]
MobSF v4.0 installed via docker. when i start MobSF i see login screen in the beginning. how can i create an account? or how can i run static scan for an apk? i can't directly jump to the static analyzer page. 
<img width="1440" alt="Screenshot 2024-05-22 at 16 40 16" src="https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/15799224/09fa8727-570e-4b1b-90b6-0fa848c3d11f">

**Comment by ajinabraham** [comment]
Please read the docs. The default credentials are mentioned in the docs.

**Comment by iremclk** [comment]
okay, thanks. I am leaving default credentials here: mobsf/mobsf
https://mobsf.github.io/docs/#/mobsf_docker

**Comment by ajinabraham** [comment]
Please do not. We want folks to follow the up to date docs. Github issues are strictly for tracking bugs and feature requests.
