### ISSUE TITLE
How do I reuse the same volume after it is created ?

### ISSUE THREAD

**Issue by engkiatkoh** [MobSF/Mobile-Security-Framework-MobSF#2396]
Hello !

I am facing this issue where I am unable to reuse the same volume after the initial creation.

The initial creation of docker container was smooth and I could use MobSF. I even verified that the folders and files were created successfully inside the /opt/MobSF directory

**mkdir /opt/MobSF**

**chown 9901:9901 /opt/MobSF**

**sudo docker run -it --rm --name MobSF -p 8000:8000 -v /opt/MobSF:/home/mobsf/.MobSF opensecurity/mobile-security-framework-mobsf:latest**

After exiting and having the container deleted, I ran the same command again. I was provided with this error message.

![MobSF Error Message](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/171221045/1e62f39c-04e4-4d37-9821-d096357dad12)

Could someone advice me on what went wrong and how I can fix this ? 
I really want to use MobSF with a persistent volume. 

Regards,
Eng Kiat

**Comment by ajinabraham** [comment]
Please use slack for support.
