### ISSUE TITLE
V4.0.3 Login Page

### ISSUE THREAD

**Issue by Tobey0328** [MobSF/Mobile-Security-Framework-MobSF#2398]
Update to V4.0.3 (Not new install)
Has a new login page in V4.0.3 , but what's the default account / password ?

Thanks 

OS and Version:MacOS 12.5
Python Version:3.09
MobSF Version:4.0.3

**Comment by mastercho** [comment]
in FAQ says set MOBSF_DISABLE_AUTHENTICATION=1 which i did but still asking for login and still dont know the password

**Comment by ha6ker-hu** [comment]
> Update to V4.0.3 (Not new install) Has a new login page in V4.0.3 , but what's the default account / password ?
> 
> Thanks
> 
> OS and Version:MacOS 12.5 Python Version:3.09 MobSF Version:4.0.3

mobsf:mobsf
