### ISSUE TITLE
[FEATURE] Add default login credentials to documentation on website

### ISSUE THREAD

**Issue by SpaceBass11** [MobSF/Mobile-Security-Framework-MobSF#2404]
Hey,

Just a thought. Since multiple people are having issues finding the default login credentials, and those tickets keep getting closed, they should probably be added to the documentation website.

Best regards,

SpaceBass

**Comment by ajinabraham** [comment]
They are mentioned both in the documentation website 

https://mobsf.github.io/docs/#/mobsf_docker?id=run-mobsf-with-static-analysis-support

and in the console when you run MobSF.
