### ISSUE TITLE
 OpenSSL executable not found in [C:\\Program Files\\OpenSSL-Win64\\bin\\openssl.exe]

### ISSUE THREAD

**Issue by zhaoxiaoqian666** [MobSF/Mobile-Security-Framework-MobSF#2407]
Problems encountered while executing the 【**setup.bat**】 command.

![problem](https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/38559685/af33cacb-29d3-4129-a84d-28e8ec23aaad)

**Comment by ajinabraham** [comment]
Please use slack for support. You have not installed all the requirements. https://mobsf.github.io/docs/#/develop?id=requirements
