### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by flamecopper** [MobSF/Mobile-Security-Framework-MobSF#2409]
Hi there. I would like to feedback on the internal server error, which MobSF present.
So basically, so basically when I run the code on the browser itself. It only shows internal server. And when I change debug to true, it still shows internal server error without any stack trace.I am currently running on python 3.10 and using mobsf version 3.7.6 and running on ubuntu. I do make some code changes from now and then. It is only "Internal Server Error" without any other error.

**Comment by ohyeah521** [comment]
I also found this problem. This problem occurs because you made a mistake in modifying the code. Just restore the last correct modification.

**Comment by flamecopper** [comment]
No this doesn't work enough for me, I want to know where exactly the code
went wrong you know.

**Comment by ajinabraham** [comment]
Please use slack for support.

**Comment by dr1408** [comment]
Make sure yara-dex-python is installed .. that was my problem now mobsf works in browser
