### ISSUE TITLE
[FEATURE] : The android can be installed on vulnrable devices is not a high security issue. It should be a warnning at most. 

### ISSUE THREAD

**Issue by thegallows-404** [MobSF/Mobile-Security-Framework-MobSF#2419]
I believe that this feature can be misleading especially for bug bounty hunters.  

![Screenshot at 2024-08-05 14-04-23](https://github.com/user-attachments/assets/8d73e5c2-d2c3-46cc-813d-b0d8002d8301)

**Comment by ajinabraham** [comment]
We have two rules here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/cc625fe8430f3437a473e82aa2966d100a4dc883/mobsf/StaticAnalyzer/views/android/kb/android_manifest_desc.py#L65-L87

If the app support really old versions of android it will be a high and for relatively newer but outdated versions, we show a warning severity.
