### ISSUE TITLE
garbled Chinese character

### ISSUE THREAD

**Issue by tuojianSun** [MobSF/Mobile-Security-Framework-MobSF#2423]
Chinese characters are not displayed properly.
<img width="606" alt="截屏2024-09-13 11 20 58" src="https://github.com/user-attachments/assets/ab9712cc-af61-4c75-b6fe-c3eaf2f12ea0">

**Comment by ajinabraham** [comment]
We use wkhtmltopdf to generate the PDF files, you might want to report this to https://wkhtmltopdf.org/
