### ISSUE TITLE
No Internet connection on Android emulator after dynamic analysis

### ISSUE THREAD

**Issue by netoeuler** [MobSF/Mobile-Security-Framework-MobSF#2425]
## ENVIRONMENT

OS and Version: Windows 11
Python Version: (Using latest version of the Docker image)
MobSF Version: (Using latest version of the Docker image)

## EXPLANATION OF THE ISSUE

After use dynamic analysis on Android emulator, the system doesn't has Internet connection and a have to wipe the system to have Internet again. I checked if there's some proxy defined but there's none.
![image](https://github.com/user-attachments/assets/383b9b1e-4049-443b-80b5-cd1551098de2)

## STEPS TO REPRODUCE THE ISSUE

1. Use Dynamic Analysis on an AVD started like mentioned in the documentation, emulator.exe -avd <AVD_NAME> -writable-system -no-snapshot.
2. After that, close the emulator and open it again. There will be no Internet connection.

## LOG FILE

It wasn't possible to get the log file from the Docker container, but I can try to get it if necessary.

**Comment by ajinabraham** [comment]
Please join slack channel for support.
