### ISSUE TITLE
❗CRITICAL❗Windows Defender detects Win32 Trojan Virus from MobSF

### ISSUE THREAD

**Issue by KeiranGamingTV** [MobSF/Mobile-Security-Framework-MobSF#2455]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.12.3 (pip-24.3.1)
MobSF Version: v.4.1.3
```

## EXPLANATION OF THE ISSUE

_**See screenshot below for more details.**_  After installing MobSF through Command Prompt, Windows Defender notified me that file `C:\Users\[USER]\Mobile-Security-Framework-MobSF\mobsf\signatures\maltrail-malware-domains.txt` was infected with a **Severe Alert Level** ``Trojan:Win32/WinLNK.CJ!MTB`` virus. 
After browsing online, I found nothing relating to the CJ!MTB Trojan virus, so I'm filing an issue for the developers to know about. Also, is this a false positive or is it actually dangerous?

![win32detection](https://github.com/user-attachments/assets/843f537c-ec77-40bc-abfd-aa377fe05a3d)

## STEPS TO REPRODUCE THE ISSUE

1.) Open _Command Prompt_ and execute `git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git`
2.) Change directory with `cd Mobile-Security-Framework-MobSF`
3.) Install with `setup.bat`
4.) Run Windows Defender Check if not automatically ran.

## LOG FILE

```
None.
```

**Comment by ajinabraham** [comment]
This is a false positive, `maltrail-malware-domains.txt` contains a text database of known malicious domains. This is probably triggering Windows Defender.

**Comment by KeiranGamingTV** [comment]
> This is a false positive, `maltrail-malware-domains.txt` contains a text database of known malicious domains. This is probably triggering Windows Defender.

Thank you, sir!
