### ISSUE TITLE
[FEATURE] Add test start time to task list API

### ISSUE THREAD

**Issue by dri-mobisec** [MobSF/Mobile-Security-Framework-MobSF#2463]
It would be helpful to have a "started_at" field in the tasks list JSON. 
With this field one could be able to understand if a test has started or not and, once a test is finished, how much time elapsed from start to finish. 
The queued_at field alone is obviously not enough because id doesn't allow to know if a test has started or not, you just know that in a certain point in time a test has been queued

**Comment by ajinabraham** [comment]
This is addressed in 4.2.8

**Comment by ajinabraham** [comment]
This is addressed in 4.2.8
