### ISSUE TITLE
In the tasks list json the status field has different formats

### ISSUE THREAD

**Issue by dri-mobisec** [MobSF/Mobile-Security-Framework-MobSF#2464]
## ENVIRONMENT

```
MobSF Version: 4.2.4
```

## EXPLANATION OF THE ISSUE

when calling the api/v1/tasks endpoint, in the tasks lists the "status" field is either a string or an object depending on the status itself.
This is a problem because the json format is coherent and it makes impossible to create a proper mapper for the object;

**Comment by ajinabraham** [comment]
This is addressed in 4.2.8
