### ISSUE TITLE
I'm having problem wiht my Dynamic Analyzer

### ISSUE THREAD

**Issue by TesterCac** [MobSF/Mobile-Security-Framework-MobSF#2465]
Hi, I hope you guys all doing well.

I did follow the instructions mentioned in the https://mobsf.github.io/docs/#/dynamic_analyzer_docker.
and tried different emulator I got the same error as you can see on the screenshot 

I use the cmd to run mobsf

docker run -it --rm -p 8000:8000 -p 1337:1337 -e MOBSF_ANALYZER_IDENTIFIER=emulator-5554 opensecurity/mobile-security-framework-mobsf:latest

![error mobsf](https://github.com/user-attachments/assets/8881e6cc-6380-41b4-b3be-a5f9f891c483)

**Comment by mostafamdy** [comment]
when starting the emulator use this command `{Android_SDK_Path}/emulator/emulator.exe -avd {AVD Name} -writable-system -no-snapshot -wipe-data -port 5554`

after that use these commands 
1- `adb root`
2- `adb shell avbctl disable-verification`
3- `adb disable-verity`
4- `adb reboot`
5- `adb root`
6- `adb remount`
