### ISSUE TITLE
pyWebProxy doesn't support large files downloading.

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [MobSF/Mobile-Security-Framework-MobSF#296]
Hello!

Due to async request yielded from:

`yield tornado.gen.Task(self.application.async_client.fetch, request)`

which colletcs chunks at:

`def handle_data_chunk(self, data):`

Tornado finally sends headers and all response data when:

`def finish_response(self, response):`

called. So when downloading large file (5,10,15+Mb) via slow connection it works like synchronously.
Hope explained clear :)

Also a @tornado.web.asynchronous decorator is not needed before _def get(self)_ because @tornado.gen.coroutine is already set.

**Comment by ajinabraham** [comment]
As suggested by @tunnelshade Increasing the instance of server should solve this. https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/edc35e087fe1e6d00cda7dc497143b93c8e3205e/DynamicAnalyzer/pyWebProxy/pywebproxy.py#L552

I will send a commit after testing this.

**Comment by MamuEbal** [comment]
I'm not sure it could help to resolve problem, because the problem is that client doesn't receive response headers (Save file dialog in browser) until chunks are not over. Fix me if I'm wrong.

**Comment by tunnelshade** [comment]
@MamuEbal Ah, ok. I assumed the problem to be requests getting queued as single instance is stuck mostly. The correct fix to this will be to write headers as soon as they arrive and keep writing chunks as and when they arrive.

**Comment by MamuEbal** [comment]
Yep, I tried to fix it myself via setting header_callback like:

```
    def header_callback(self, line):
        header = line.strip()
        if header:
            if ':' not in header:
                ver, code, reason = tornado.httputil.parse_response_start_line(header)
                self.set_status(code, reason)
            else:
                key, val = [x.strip() for x in header.split(':', 1)]
```
But when I call add_header routine from this callback I got error line finish() called twice or page content not showed properly.

**Comment by ajinabraham** [comment]
@tunnelshade Do we have a fix for this in OWTF branch?

**Comment by ajinabraham** [comment]
Closing this as the proxy component is third party. We will update this if the issue is fixed in parent repo.
