### ISSUE TITLE
Saving to Database Error

### ISSUE THREAD

**Issue by RootToolKit** [MobSF/Mobile-Security-Framework-MobSF#314]
[ERROR] Saving to DB (/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 236 "static_db.save()"): table StaticAnalyzer_staticanalyzerandroid has no column named BROWSABLE

**Comment by ajinabraham** [comment]
Do migrate database in django

**Comment by RootToolKit** [comment]
python manage.py migrate

[INFO] Checking for Update.

[INFO] No updates available.
Operations to perform:
  Apply all migrations: APITester, MobSF, StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.


No luck. Any other suggestions?

**Comment by ajinabraham** [comment]
Make migrations before migrating. Delete db.sqlite if that didn't solved the issue

**Comment by RootToolKit** [comment]
Got it. Thank you :)
