### ISSUE TITLE
About Code Nature

### ISSUE THREAD

**Issue by 3lackrush** [MobSF/Mobile-Security-Framework-MobSF#318]
Dear Author~
 i'm little confused about the Native flag on Code Nature part.Is that means Native Method in java?

 i would be appreciate that if you reply on  this!

**Comment by ajinabraham** [comment]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/code_analysis.py#L324
