### ISSUE TITLE
IPA analyzer error

### ISSUE THREAD

**Issue by vmsv** [MobSF/Mobile-Security-Framework-MobSF#319]
Hello,

  While analyzing an IPA file I run into this error.

tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios.py, LINE 107 "STATIC_DB.save()"): table StaticAnalyzer_staticanalyzeripa has no column named 

PERMISSIONSHave you seen this before?

**Comment by DominikSchlecht** [comment]
Hey @vmsv ,

yep, this might due to a recent change implementing permissions-analysis.

Could you please try to either run the clean.sh or migrate the databases? Maybe your code is up-to-date but your db-structure isn't :)

Greetings,
Dominik

**Comment by ajinabraham** [comment]
Check: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
