### ISSUE TITLE
IPA file is too big! Max file size 100MB

### ISSUE THREAD

**Issue by RootToolKit** [MobSF/Mobile-Security-Framework-MobSF#323]
Hi,

Trying to load a 145MB IPA via the dropzone and receive "IPA file is too big! Max file size 100MB"...
I tried editing "static/js/dropzone.js" but still receive that error. What's the best way to test an Apple IPA? Can we adjust the max file size somewhere?

**Comment by ajinabraham** [comment]
You need to change it here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/e10871aec2f627fccabc487df5dbf4c6f97865d8/templates/general/index.html#L173

**Comment by TiberiumPY** [comment]
@ajinabraham why there's this client side restriction?

**Comment by itsecforu** [comment]
> Is there a solution if index.html is missing?

The same - version 3.5.0 

@ajinabraham How to solve it?

`mobsf@mobsf-temp-7777cbd8c5-sjkn2:~/Mobile-Security-Framework-MobSF/mobsf/templates/general$ ls
about.html  apidocs.html  error.html  home.html  not_found.html  recent.html  search.html  view.html  zip.html`

log:

`Skipping large file /home/mobsf/.MobSF/uploads/
`
