### ISSUE TITLE
Dynamic API Analysis Error

### ISSUE THREAD

**Issue by RootToolKit** [MobSF/Mobile-Security-Framework-MobSF#329]
Receiving the following errors on Dynamic Analysis -- permission issue?

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device
connected to 10.0.0.19:5555

[INFO] Mounting

[INFO] Starting App for Dynamic Analysis

[INFO] Installing APK
388 KB/s (59911350 bytes in 150.758s)
	pkg: /data/local/tmp/831b665bed7ade759849eb07896e5be7.apk
Success

[INFO] Launching APK Main Activity
Starting: Intent { cmp=XXXXXXXXXXXX.activities.SplashActivity }
[INFO] Testing Environment is Ready!

[INFO] Getting Screen Resolution
[23/Jan/2017 17:33:07] "POST /GetEnv/ HTTP/1.1" 200 66

[INFO] Installing MobSF RootCA

[INFO] Starting Clipboard Dump Service in VM/Device
24 KB/s (1119 bytes in 0.045s)
[23/Jan/2017 17:33:08] "POST /MobSFCA/ HTTP/1.1" 200 19
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=opensecurity.clipdump/.ClipDumper }
Error: Not found; no service started.
[23/Jan/2017 17:33:09] "POST /ClipDump/ HTTP/1.1" 200 21

[INFO] Collecting Data and Cleaning Up

[INFO] Downloading Logcat logs
remote object '/data/data/de.robv.android.xposed.installer/log/error.log' does not exist

[INFO] Downloading Droidmon API Monitor Logcat logs

[INFO] Downloading Dumpsys logs

[INFO] Stopping Application

[INFO] Stopping ScreenCast Service
[23/Jan/2017 17:48:30] "POST /FinalTest/ HTTP/1.1" 200 16

[INFO] Device Data Dump

[INFO] Stopping any running instance of WebProxy

[INFO] Deleting Dump Status File

[INFO] Saving Captured Web Proxy Data

[INFO] Saving URLS

[INFO] Saving WebTraffic

[INFO] Saving Request Objects

[INFO] Stopped WebProxy and Data Saved

[INFO] Creating TAR of Application Files.
Starting service: Intent { act=XXXXXXXXXXXXX/.GetPackageLocation }

[INFO] Waiting for TAR dump to complete...

[INFO] Dumping Application Files from Device/VM
321 KB/s (378880 bytes in 1.150s)

[INFO] Stopping ADB
[23/Jan/2017 17:48:34] "POST /DumpData/ HTTP/1.1" 200 15

[INFO] Dynamic Analysis Report Generation

[INFO] Dynamic API Analysis

[2017-01-23 17:48:34]
[ERROR] Dynamic API Analysis (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android.py, LINE 797 "with open(LOCATION, "r") as f:"): [Errno 2] No such file or directory: u'/opt/Mobile-Security-Framework-MobSF/uploads/831b665bed7ade759849eb07896e5be7/x_logcat.txt'

[INFO] Dynamic File Analysis

[2017-01-23 17:48:34]
[ERROR] Dynamic Analysis Report Generation (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android.py, LINE 597 "APP_DIR, MD5, PKG)"): [Errno 2] No such file or directory: '/opt/Mobile-Security-Framework-MobSF/uploads/831b665bed7ade759849eb07896e5be7/x_logcat.txt'
[23/Jan/2017 17:48:34] "GET /Report/?md5=831b665bed7ade759849eb07896e5be7&pkg=XXXXXXXXXXXX HTTP/1.1" 302 0
[23/Jan/2017 17:48:34] "GET /error/ HTTP/1.1" 200 4603

**Comment by ajinabraham** [comment]
Are you using MobSF supplies VM or something different. You don't have the required apps installed it seems.

**Comment by RootToolKit** [comment]
What apps specifically?

**Comment by ajinabraham** [comment]
These: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsfy.py#L75-L90
