### ISSUE TITLE
Check VM is up to date

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#330]
we need to check if VM is up to date for Dynamic Analysis

**Comment by nmurilo** [comment]
In my macOS running 10.12.3, VirtualBox Version 5.0.32 r112930 and MobSF_VM_0.3.ova
I got this error: 
![screen shot 2017-02-03 at 2 12 50 pm](https://cloud.githubusercontent.com/assets/22617810/22598537/e6969668-ea1a-11e6-97db-4191490a1b00.png)
