### ISSUE TITLE
class-dump for iOS apps written in Swift?

### ISSUE THREAD

**Issue by cobbr** [MobSF/Mobile-Security-Framework-MobSF#332]
Is MobSF currently capable of performing a class-dump of iOS applications written in Swift?

If it does, I am having trouble getting it to work. If this is not implemented yet, would it be possible to add this as a feature request?

From my understanding, there is a few extra steps to get output that looks similar to class-dump-z for applications written in Swift. I'm certainly no expert, but I think this would be possible using something like Apple's swift-demangle script. I found a few details about a tool called "class-dump-s" in a slide presentation [here](http://gsec.hitb.org/materials/sg2016/COMMSEC%20D1%20-%20Michael%20Gianarakis%20-%20Reverse%20Engineering%20Swift%20Applications.pdf). Relevant info starts at page 19.

Let me know if I can help out with this at all.

**Comment by ajinabraham** [comment]
Swift is not supported at the moment

**Comment by cobbr** [comment]
Is this something you plan on supporting in the future? If so, is there any work I could help with to implement it?

**Comment by ajinabraham** [comment]
I don't have the bandwidth to work on it at the moment. I guess it's not a difficult addition. If you are interested, you can take a look into https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/ios.py#L687-L699 and integrate https://github.com/nygard/class-dump similarly. I will add it to enhancements. But there is quite a lot of things in the backlogs now.

**Comment by ajinabraham** [comment]
Enhancements are tracked separately
