### ISSUE TITLE
VM ID not visible in virtualbox. Ip Management field empty. 

### ISSUE THREAD

**Issue by kanikagupta17** [MobSF/Mobile-Security-Framework-MobSF#333]
Hi,

I am trying to configure Dynamic Analyzer with MobSF supplied VM. While booting up the VM, IP management field is empty and I am getting this - eth0 is not configured correctly - hardware opengl is disabled in virtualbox. After this VM starts and I have done everything, but I am not able to get VM ID to store in settings.py.

Also, one more issue, when I change settings.py, after that do I need to compile that again ? I am modifying it in notepad and I am doing this complete setup in Windows 10.

Please suggest How can I get the VM ID. Thanks.

**Comment by ajinabraham** [comment]
Try this : https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/6.-What-to-do-when-MobSF-VM-and-VirtualBox-Host-Only-Adapter-are-not-in-the-same-network-range

This is not a mobsf issue. It's something to do with your VirtualBox and Virtual Network
