### ISSUE TITLE
Don't Play Around. An Error just popped in! on ipa binary 

### ISSUE THREAD

**Issue by nmurilo** [MobSF/Mobile-Security-Framework-MobSF#335]
I got this error when scan apple ipa file, android ipk worked  like a charm. 
Any hints? 

[2017-02-02 13:04:37]
[ERROR] - Reading from Info.plist (/Users/nmor/fnt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views.py, LINE 2103 "p=plistlib.readPlistFromString(XML)"): must be string or buffer, not None
[INFO] iOS Binary : NewRendererXX
[INFO] Running otool against the Binary
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/nmor/fnt/Mobile-Security-Framework-MobSF/uploads/549e90476b84e3efb392aecf68391275/Payload/NewRendererXX.app/NewRendererXX': No such file or directory.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed

**Comment by ajinabraham** [comment]
Can you share the ipa that caused this problem?

**Comment by nmurilo** [comment]
Sure, pls check your email.

**Comment by ajinabraham** [comment]
I saw the issue but two questions.

Why that IPA doesn't have a `Info.plist` and where is `NewRendererBB.app` directory? This error occurs because the IPA you sent doesn't have these two critical files.

**Comment by nmurilo** [comment]
I´m using iMazing to extract ipa pack from iphone. Do you recomend another one?

**Comment by nmurilo** [comment]
In this case iMazing extraction doesn´t work. Now I using a real ipa file and all works fine. 
I´m sorry for disturb .
