### ISSUE TITLE
'ascii' codec can't decode byte issue and patch 

### ISSUE THREAD

**Issue by nmurilo** [MobSF/Mobile-Security-Framework-MobSF#337]
Hi, I got this the error above because a directory name have a non-ascii char (í ). 
To solve it, there is my patch: 

[ios-py.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/751888/ios-py.txt)

**Comment by ajinabraham** [comment]
Thanks the fix is added. https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/b6bd0537e2a4337e159dc82bc878539bf716871f
