### ISSUE TITLE
No module named 'settings'

### ISSUE THREAD

**Issue by mohsin1122** [MobSF/Mobile-Security-Framework-MobSF#338]
hi
while executing this command `python manage.py runserver` i am getting error **"D:\pentest\Mobile-Security-Framework-MobSF-master\MobSF\utils.py", line 20, in <module>
    import settings
ModuleNotFoundError: No module named 'settings'** 
i am using python 3.6

**Comment by ajinabraham** [comment]
Have you read the docs ?
Python 2.7 not 3.6
