### ISSUE TITLE
What is the password of MobSF_VM_0.3.ova

### ISSUE THREAD

**Issue by 3lackrush** [MobSF/Mobile-Security-Framework-MobSF#339]
Dear author,
    I want to perform a dynamic analysis of the android application,but i don't know the password of the virtual machine. I would be appreciated if you can tell me. By the way, the dynamic analysis only support the android 4.03 - 4.4 according the wiki, but there is a huge apps that must install on the higher version of android. Is there any update will support the higher version of android?
   thanks

**Comment by ajinabraham** [comment]
The password of MobSF VM is 1234 it's mentioned in the Wiki. You can use a
rooted device with Xposed Framework that supports Android >5.0 This is not
tested though.

Regards,

*Ajin Abraham  *
Security Researcher
<https://twitter.com/ajinabraham>    <http://in.linkedin.com/in/ajinabraham>
  <https://github.com/ajinabraham>
m +91-9633325997 a Bangalore,India
s opensecurity.in s opsecx.com

**Comment by mharyanjune** [comment]
how to login ??
