### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by TolgaSEZER** [MobSF/Mobile-Security-Framework-MobSF#340]
i was installed all python requirements. but i get this error;

> C:\MobSF>python manage.py runserver
> [INFO] Running first time setup for windows.
> [*] Reading config file..
> [*] Downloading nuget..
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
> 367, in execute_from_command_line
>     utility.execute()
>   File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
> 316, in execute
>     settings.INSTALLED_APPS
>   File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 53, in __ge
> tattr__
>     self._setup(name)
>   File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _set
> up
>     self._wrapped = Settings(settings_module)
>   File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 97, in __in
> it__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
>     __import__(name)
>   File "C:\MobSF\MobSF\settings.py", line 381, in <module>
>     windows_setup.install_locally(MobSF_HOME)
>   File "C:\MobSF\install\windows\setup.py", line 369, in install_locally
>     tools_nuget()
>   File "C:\MobSF\install\windows\setup.py", line 122, in tools_nuget
>     nuget_file = urlrequest.urlopen(nuget_url) # pylint: disable-msg=E1101
>   File "C:\Python27\lib\urllib.py", line 87, in urlopen
>     return opener.open(url)
>   File "C:\Python27\lib\urllib.py", line 213, in open
>     return getattr(self, name)(url)
>   File "C:\Python27\lib\urllib.py", line 443, in open_https
>     h.endheaders(data)
>   File "C:\Python27\lib\httplib.py", line 1038, in endheaders
>     self._send_output(message_body)
>   File "C:\Python27\lib\httplib.py", line 882, in _send_output
>     self.send(msg)
>   File "C:\Python27\lib\httplib.py", line 844, in send
>     self.connect()
>   File "C:\Python27\lib\httplib.py", line 1263, in connect
>     server_hostname=server_hostname)
>   File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
>     _context=self)
>   File "C:\Python27\lib\ssl.py", line 611, in __init__
>     self.do_handshake()
>   File "C:\Python27\lib\ssl.py", line 840, in do_handshake
>     self._sslobj.do_handshake()
> IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
> y failed (_ssl.c:661)
> 
> C:\MobSF>

jdk & python vc compiler etc.. installed.

**Comment by DominikSchlecht** [comment]
Hey @TolgaSEZER ,

this seems to be an SSL error (as statet, `SSL: CERTIFICATE_VERIFY_FAILED`).

Did you retry the installation? If not, could you please verify that you can open [https://dist.nuget.org/win-x86-commandline/latest/nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) in the browser (or better copy the python code and connect)?

Greetings,
Dominik

**Comment by TolgaSEZER** [comment]
fixed with .net framework (this was necessary for nuget)
Thx reply.
