### ISSUE TITLE
Error is appearing on uploading apk/ipa file in the interface.

### ISSUE THREAD

**Issue by BHARATSEHRA** [MobSF/Mobile-Security-Framework-MobSF#341]
![mobsf](https://cloud.githubusercontent.com/assets/20972378/22645944/c6047952-ec8f-11e6-9823-3407e0942771.jpg)

Error: Don't play around. An error just popped in.
no such table : static analyser_staticanalyserandroid/ios (This error is coming after uploading the file)

Could you please help me to resolve the issue at the earliest possible. 

For workaround , i have downloaded android tamer virtual machine to work with apk file.

**Comment by ajinabraham** [comment]
Your database migration is failed: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
