### ISSUE TITLE
Web API Fuzzer Error

### ISSUE THREAD

**Issue by workfast108** [MobSF/Mobile-Security-Framework-MobSF#342]
Dear Admin, 

After completing my Dynamic analysis on an apk file, i try to use  the Web API Fuzzer on some known Parameter that was detected on the API Fuzzer Page, but i got Error pop up." i have tried with 3 different apks , and i follow the screenshot that was explained on the github page regarding the WebFuzzer Analysis.But the Web API Fuzzer keep given Error. Kindly let me know if am doing anything wrong. i have attached screenshot of the usual error that i am encountering below.

Warm Regards
![capture13](https://cloud.githubusercontent.com/assets/24754100/22668884/3e688d16-ec77-11e6-989d-99083e58d07f.PNG)
Dere Sewa

**Comment by ajinabraham** [comment]
This doesn't help us to debug. You need to provide complete information. Read: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/CONTRIBUTING.md#bug-reports
