### ISSUE TITLE
How can we Integration of MobSF with Sonarcube ?

### ISSUE THREAD

**Issue by neeru-thakur** [MobSF/Mobile-Security-Framework-MobSF#343]
Can we Integration of MobSF with Sonarcube? If so please share the links or any detail. 

Thanks

**Comment by ajinabraham** [comment]
Github issues is strictly for bug tracking, All discussions, question: https://mobsf.slack.com/

**Comment by neeru-thakur** [comment]
How would I join  MobSF team on slack as there is no signup for this team. Where could I send request to admin to send me invitation ?

**Comment by ajinabraham** [comment]
Please use this invitation form: https://goo.gl/6cYU5a
