### ISSUE TITLE
Connect to real device instead of VM image...

### ISSUE THREAD

**Issue by dktran65** [MobSF/Mobile-Security-Framework-MobSF#344]
I have three quick questions:

1. Can you connects to real device without have to jailbreak or rooted the device for Dynamic Analysis?

2. If yes, are there instructions how to do that? (I have not found one)...

3. If No, is that possible to do and what is the limitation?

I am trying to use the device on Perfecto Mobile Cloud that is connects to the Real Device (Device is  is not rooted or jailbreak).   They have new feature that call DevTunnel which allows you to connects to a Real Device on their Cloud with your Android Studio IDE (or Xcode IDE) likes you would connects to the Emulator, but this is a real device and you can do single step code debugging, and on the Android Studio,  i can see some of the adb commands being executes in the output pane.
 
Thanks in advance!

**Comment by ajinabraham** [comment]
Please don't use Github issues for question, Join our Slack channel for questions and discussion. (https://goo.gl/6cYU5a)

short answers

1. Can connect but not useful for security analysis
2. None
3. Non rooted devices are limited and doesn't support runtime instrumentations
