### ISSUE TITLE
VM and Server on different machines in the same network?

### ISSUE THREAD

**Issue by mrpinghe** [MobSF/Mobile-Security-Framework-MobSF#345]
This is more of a question on this already fantastic tool...

Is it possible, at least in a theoretical level, to have the MobSF server running on machine A, and the MobSF VM running on machine B, provided both are under the same LAN? Or do they have to be on the same machine like in the tutorial?

Thanks!

**Comment by ajinabraham** [comment]
Please don't use Github issues for question, Join our Slack channel for questions and discussion. (https://goo.gl/6cYU5a)

Now for your question. 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-dynamic-analyzer-with-rooted-android-device

This is nothing but using a rooted android device in the LAN
