### ISSUE TITLE
Can not export PDF

### ISSUE THREAD

**Issue by mryu-org** [MobSF/Mobile-Security-Framework-MobSF#347]
## log:
[INFO] Fetching data from DB for PDF Report Generation (IOS IPA)

WEB page click to export PDF, has been waiting for the state.

* MAC、MobSF0.93、chrome.
python 2.7.10
pip install Django==1.10.b1
pyOpenSSL
tornado==4.1
xhtml2pdf==0.0.6
html5lib==1.0b8
psutil==4.2.0
rsa
configparser
lxml

**Comment by DominikSchlecht** [comment]
Hey,

how many strings does the IPA contain? Sometimes, if there are a lot of strings in the binary, PDF generation can take a lot of time :/

Greetings,
Dominik

**Comment by DominikSchlecht** [comment]
PS: You can check the strings on the analysis screen :) there is a "strings" button.

**Comment by ajinabraham** [comment]
Yeah PDF generation depends on the size of the content to be rendered as PDF.

**Comment by ajinabraham** [comment]
@DominikSchlecht I have added a basic unit test for static analysis that includes upload test, static analysis test and pdf generation test.

You can go to `127.0.0.1:8000/runtest/` for starting the unit test.

During test, I have used http://damnvulnerableiosapp.com/?paiddownloads_id=11 and found that PDF generation is not giving a response back. I am using a Mac 16GB/Core i7/512GB SSD.
Can we optimize something here?

**Comment by DominikSchlecht** [comment]
Hey Ajin,

I will have a look into it this evening/tomorrow morning.

**Comment by DominikSchlecht** [comment]
I debugged the pdf creation to find out what call takes so long, sadly it's the 
```
pdf = pisa.pisaDocument(StringIO("{0}".format(
                html.encode('utf-8'))), result, encoding='utf-8')
```
function itself.

Well, I see 2 easy "solution":
- Remove the strings section from the pdf
- Turn up the strings-method to a min of 5 characters (this would decrease the number of strings here from apprx. 17000 to 7000)

The more clean solution would be to switch to a better pdf rendering engine.


I just tried with pdfkit, looks much nicer and finishes in below 10 seconds:
```
print("[+] Creating PDF")
#pdf = pisa.pisaDocument(StringIO("{0}".format(
#    html.encode('utf-8'))), result, encoding='utf-8')
import pdfkit
pdf = pdfkit.from_string(html, False)
print("[+] Finished creating PDF")
# if not pdf.err:
#     return HttpResponse(result.getvalue(), content_type='application/pdf')
# else:
#     return HttpResponseRedirect('/error/')
return HttpResponse(pdf, content_type='application/pdf')
```

Sadly pdfkit needs a custom installation ([wiki](https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf)) so I don't know if we want to implement pdfkit :/ Especially on Mac you would be forced to use brew or compile it yourself :/ On the other hand xhtml and pisa aren't that great ether.

@ajinabraham, what do you think? 

Greetings,
Dominik

**Comment by ajinabraham** [comment]
@DominikSchlecht Nice Suggestion.

Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/2161cc398348915da907d5b5907eab81255ea673
