### ISSUE TITLE
Config.py error

### ISSUE THREAD

**Issue by anantshri** [MobSF/Mobile-Security-Framework-MobSF#351]
## EXPLANATION OF THE ISSUE

1. Upgrade from mobsf 0.9.2 to 0.9.4. 
2. USE_HOME = True
3. ~/.MobSF/config.py found and hence new options not added.
4. remove ~/.MobSF/config.py and reran the server
5. config.py is created but with error's in it.

Error message as shown below

![mobsf](https://cloud.githubusercontent.com/assets/236843/23321353/25441a7a-fb05-11e6-884d-9d41cb5fc579.jpg)

basically last 3 lines are missing the indentation.

as far as i can see https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/f42b8321507c540b341832e99b93ccee775b49bd/MobSF/utils.py#L81 is the cause of the issue lstrip removes all identation and you need indentiation in that place.

EDIT More
Once this is sorted by manually placing identation to config following additional error's occur
![next_error](https://cloud.githubusercontent.com/assets/236843/23321491/cf4a133a-fb05-11e6-96e9-844fd388ee22.jpg)

**Comment by ajinabraham** [comment]
I am trying to reproduce this issue on Ubuntu VM.
@DominikSchlecht Something to do with `config.py`
Can you take a look?

**Comment by ajinabraham** [comment]
Ok so this `config.py` is your custom file

**Comment by ajinabraham** [comment]
@DominikSchlecht  Sorry this is not Windows config. This is MobSF config when USE_HOME is set to true.

**Comment by ajinabraham** [comment]
@DominikSchlecht The indentation issue is here
```
if (os.path.isfile(PATH_TO_LOCK_FILE) is False) and CURRENT_PLATFROM == 'Windows':
print "[INFO] Running first time setup for windows."
# Setup is to-be-executed
windows_setup.install_locally(MobSF_HOME)
#==============================================
```

**Comment by ajinabraham** [comment]
It seems 
```
import platform
import os
MobSF_HOME
``` 
are not defined in `config.py`

```
#==============================================
#================WINDOWS-Analysis-Settings ====
# Get the OS MobSF is currently running on
CURRENT_PLATFROM = platform.system()
# Private key if rpc server is needed
WINDOWS_VM_SECRET = 'MobSF/windows_vm_priv_key.asc'
# IP and Port of the MobSF Windows VM
# eg: WINDOWS_VM_IP = '127.0.0.1'
WINDOWS_VM_IP = None
WINDOWS_VM_PORT = '8000'
# Configure here if you are on windows
# Path to lock-file (so setup is only run once)
PATH_TO_LOCK_FILE = os.path.join(MobSF_HOME, "setup_done.txt")
if (os.path.isfile(PATH_TO_LOCK_FILE) is False) and CURRENT_PLATFROM == 'Windows':
	print "[INFO] Running first time setup for windows."
	# Setup is to-be-executed
	windows_setup.install_locally(MobSF_HOME)
	#==============================================
```

**Comment by anantshri** [comment]
important question do we need this block in config.py at user level or this should be part of the Overall settings.py at base project.

**Comment by ajinabraham** [comment]
@anantshri This should be fixed in latest master. Make sure you remove everything in `<home>/.MobSF`
Please verify the fix.

Also from now on, you can do a unit test of Static Analyzer from : `http://127.0.0.1:8000/runtest/`
Run that before deploying.

@DominikSchlecht : 
I have moved the logic from settings to `setup.py` in Windows.
Can you review this hotfix: https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/a2ad74683ca8943c923770ab500ba160475257e2

I couldn't test Windows App Static Analysis.

**Comment by anantshri** [comment]
Thanks for the quick work. But i realized another issue, if a user is using USE_HOME the config.py exists and you add some new values in settings.py these new parameters will never get reflected coz config.py already exists. 

Not sure how to solve this but something that needs to be looked at.

**Comment by ajinabraham** [comment]
Valid concern, But we cannot overwrite User's config file as he might have added some modifications already.

**Comment by anantshri** [comment]
Like i said not sure how we can ever solve this ever.

One idea

1. Mostly config.py is filled with variables and we generally will be adding more variables in the config.
2. How about looking for the variables names in config.py if they don't exist append them to the end of the document.

This way we don't tamper with what exists but we add in anything new we introduced.

**Comment by DominikSchlecht** [comment]
You could add values to a config-file via config parser (or for example check if the key is already filled with a value, and only write it if not). I do that alot with the windows-analysis.

Sry, I couldn't really follow the thread and I am a bit short on time right now - ist there anything I can help with?

Greetings,
Dominik
