### ISSUE TITLE
Static Analyzer Rules Android

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#352]
https://github.com/SUPERAndroidAnalyzer/super/blob/master/rules.json
https://github.com/SUPERAndroidAnalyzer/super/tree/master/src/static_analysis
LICENSE: GPL3

**Comment by imran209** [comment]
I am new to mobile security.
I have installed the MobSF, python27 and i have configure mobsf for static analysis.
I have drag the code in zip format to the mobsf and it is showing that for android we required .xml and src.
I didn't get it can you please help me out of this.

**Comment by ajinabraham** [comment]
Most rules are already there.
