### ISSUE TITLE
CFR upgrade

### ISSUE THREAD

**Issue by anantshri** [MobSF/Mobile-Security-Framework-MobSF#353]
cfr_0_119.jar (November 2016) 

http://www.benf.org/other/cfr/

the version build inside seems to be cfr_0_115.jar

**Comment by ajinabraham** [comment]
Upgraded.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/4a14c0d71b53f39fb9d5daa86379fe5e9ece759f
