### ISSUE TITLE
Incorrect example binary marked

### ISSUE THREAD

**Issue by anantshri** [MobSF/Mobile-Security-Framework-MobSF#356]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L274

marks d2j_invoke.sh as DEX2JAR_BINARY however the correct name is d2j-dex2jar.sh 
needed to dig into the actual code to figure out what's required.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/eb099ff49eadca973212cbba9edfe87bfc68494a/StaticAnalyzer/views/android/converter.py#L42

rathe the inv https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/eb099ff49eadca973212cbba9edfe87bfc68494a/StaticAnalyzer/views/android/converter.py#L37 is never used.

**Comment by ajinabraham** [comment]
I have updated the confusing place holder in settings.py
https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/05df9fa4655af5bc8ff1b6909cd7aa166a5f0eff

`d2j-dex2jar.sh` calls `d2j-invoke.sh`internally.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/eb099ff49eadca973212cbba9edfe87bfc68494a/StaticAnalyzer/tools/d2j2/d2j-dex2jar.sh#L36
"We are `chomd` ing it to fix permission issues for some unix users.
