### ISSUE TITLE
Request: use Signed github Commits

### ISSUE THREAD

**Issue by anantshri** [MobSF/Mobile-Security-Framework-MobSF#357]
If you use PGP you can sign your commit's using PGP key and github will show verified sign next to commit's. This is a good idea to prevent commit forgery 

https://help.github.com/articles/signing-commits-using-gpg/

This instils trust in users that the commit are from original author and no one has forged the commit's.

possible good read if you need more egging for this : https://mikegerwitz.com/papers/git-horror-story#trust-ensure

**Comment by ajinabraham** [comment]
Will consider this

**Comment by ajinabraham** [comment]
I commit from multiple devices. Anyways I will add PGP to sign commits from my personal laptop.
