### ISSUE TITLE
SHA-1 Signing Certificate rated as "good"

### ISSUE THREAD

**Issue by whoot** [MobSF/Mobile-Security-Framework-MobSF#361]
## EXPLANATION OF THE ISSUE

If an (android) app uses a signer certificate with SHA-1 as signature algorithm, MobSF rates the certificate as "good".
However SHA-1 is broken and should not be used as signature algorithm. Therefore I recommend to change the rating of the signer certificate to "insecure" or "bad" or something else.

Mor information about SHA-1 collision attack can be found here:
http://shattered.it/

Greetings

**Comment by ajinabraham** [comment]
This is added to latest master. Thanks for pointing out.
