### ISSUE TITLE
MobSF dynamic analyzer

### ISSUE THREAD

**Issue by liskar64** [MobSF/Mobile-Security-Framework-MobSF#362]
Hello.

When I have the Environment created and the apk installed I can`t see the app at the left. If I go to the device of the VM I see the app installed but when I want to use it`s not possible

These are the steps that I do:

1. I push the dynamic analysis button from the static analysis page
2. I have running the server(manage.py) and mobsfy.py with the data of the device
3. The page of dynamic analysis is open
4. I push the button of create environment
5. Device of VM is open
6. VM status seems ok:
VM Snapshot loaded
Trying to setup the environment
Running HTTPS Proxy
Connecting to VM
Mounting
Installing APK
Running APK
Environment is Ready!
Agents are running in the Background
Go Ahead and navigate through all the flows of the Application.
MobSF RootCA Installed Successfully
Clipboard Monitoring Started!

7. If I push the button of show screen the manage.py console begins to write a lot of lines like this:

[01/Mar/2017 15:30:55] "GET /download/screen/screen.png?1488378655448 HTTP/1.1" 200 625
[01/Mar/2017 15:30:55] "GET /download/screen/screen.png?1488378655749 HTTP/1.1" 200 625
[01/Mar/2017 15:30:56] "GET /download/screen/screen.png?1488378656049 HTTP/1.1" 200 625
Got Connection from:  192.168.56.101
[01/Mar/2017 15:30:56] "GET /download/screen/screen.png?1488378656649 HTTP/1.1" 200 625
[01/Mar/2017 15:30:56] "GET /download/screen/screen.png?1488378656949 HTTP/1.1" 200 625
Got Connection from:  192.168.56.101
[01/Mar/2017 15:30:57] "GET /download/screen/screen.png?1488378657249 HTTP/1.1" 200 625
[01/Mar/2017 15:30:57] "GET /download/screen/screen.png?1488378657849 HTTP/1.1" 200 625
Got Connection from:  192.168.56.101
[01/Mar/2017 15:30:58] "GET /download/screen/screen.png?1488378658149 HTTP/1.1" 200 625
[01/Mar/2017 15:30:58] "GET /download/screen/screen.png?1488378658449 HTTP/1.1" 200 625
[01/Mar/2017 15:30:59] "GET /download/screen/screen.png?1488378659067 HTTP/1.1" 200 625
Got Connection from:  192.168.56.101
[01/Mar/2017 15:30:59] "GET /download/screen/screen.png?1488378659349 HTTP/1.1" 200 625
[01/Mar/2017 15:30:59] "GET /download/screen/screen.png?1488378659949 HTTP/1.1" 200 625 

8. The app don´t appears at the device on the left
9. If I go to the device of VM the app appears but If I try to use it I can't do it
10. If I push the button of finish the analysis ends ok and it launches a report but I can't navigate across the app
11.These are my settings.py:

#===============DEVICE SETTINGS=================
    REAL_DEVICE = False
    DEVICE_IP = '192.168.1.18'
    DEVICE_ADB_PORT = 5555
    DEVICE_TIMEOUT = 300
    #===============================================
    #================VM SETTINGS ===================

    # VM UUID
    UUID = '5dd734da-9d9d-4c37-874d-d89397063785'
    # Snapshot UUID
    SUUID = 'ccbbff56-efdb-40d1-9a56-7feac0bb2624'
    # IP of the MobSF VM
    VM_IP = '192.168.56.101'
    VM_ADB_PORT = 5555
    VM_TIMEOUT = 100
    #==============================================
    #================HOST/PROXY SETTINGS ==========

    PROXY_IP = '192.168.56.1'  # Host/Server/Proxy IP
    PORT = 1337  # Proxy Port
    ROOT_CA = '0025aabb.0'
    SCREEN_IP = PROXY_IP  # ScreenCast IP
    SCREEN_PORT = 9339  # ScreenCast Port

    #==============================================

    #========UPSTREAM PROXY SETTINGS ==============
    # If you are behind a Proxy
    UPSTREAM_PROXY_IP = None
    UPSTREAM_PROXY_PORT = None
    UPSTREAM_PROXY_USERNAME = None
    UPSTREAM_PROXY_PASSWORD = None
    #==============================================

Thank you.

**Comment by ajinabraham** [comment]
Can you see if your system blocks port 9339. The VM tries to make a connection to port 9339 to share the screen in the web app. If the port is filtered or blocked, you won't be able to do screen casting.

**Comment by liskar64** [comment]
How can I see this? I have launch a telnet order:OPEN login.icq.com 9339(I have looked it at internet). The answer is that the connection is not possible. After I have gone to windows firewall and I have added a enter rule(I don´t know how it works)TCP for 9339, private, local port and remote port all. This don´t work. I say you that I have no idea about open ports and how it works.

Thank you.

**Comment by ajinabraham** [comment]
Also see if that port is used by some other apps.
`netstat -a -b` or you can use TCPView tool.

**Comment by ajinabraham** [comment]
Other than port issue, I couldn't find any other reasons for this at the moment.

**Comment by liskar64** [comment]
Yes. I have followed the running ports with TCP view and 9339 state is closed_wait. How can I open it?. My windows firewall is disabled because in my PC runs Mcafee antivirus(I suppose that this is the reason). Do I change the ports in windows firewall console?. 

Thank you.

**Comment by ajinabraham** [comment]
The port will be in open state once you start to use it. See if McAfee blocks inbound connections.

**Comment by liskar64** [comment]
Hello.
I think that I have disabled the antivirus for a while and the problem goes on. I have watched the manage.py runserver console and I have seen one exception when I push the screen show button. I send you a attached file with the code
[server.docx](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/816182/server.docx).

Thank you again.

**Comment by ajinabraham** [comment]
I saw the docx. Those exceptions are fine, due to some socket errors. But
there is some issue with TCP connection in your system.  If you can come
over TeamViewer sometime, prolly I can take a look.

**Comment by liskar64** [comment]
I have installed MobSF at my home without firewall and antivirus and happens the same to me. I don´t know if I do something wrong about the installation. The port 9339 status is closed_wait

**Comment by ajinabraham** [comment]
This needs to be better looked into. Can  you come over Teamviewer?

**Comment by liskar64** [comment]
Hello.

I can use the app in the virtual device and the automatic testing and the final report works OK.
What`s Teamviewer?. I have another questions for you. I have read that dynamic analysis is not avalaible for IOS apps. Do you have thinking about a development for this soon?. Are Hybrid apps valid for MobSF analysis?.

Thank you again.

**Comment by ajinabraham** [comment]
I can use the app in the virtual device and the automatic testing and the final report works OK. Yes even if it didn't show up. It is not a problem in doing dynamic analysis.
Teamviewer allows me to access your PC to debug the issues.
https://www.teamviewer.com/en/download/
iOS Dynamic analyzer is under development and yes Hybrid apps will do just fine.

**Comment by ajinabraham** [comment]
Closing this issue as 25 days response period is over.

**Comment by jamespenetration** [comment]
hi,admin 
please show me  how to fix this problem ? i have same quesion. my system is windows 2008 standard。when i use android dynamic anlyazer ,that can't show  screen,but log file record my request and picture size.
i'm confuse . maybe it's happen,because  django 's  problem, i guess.  please help me solve the problem. thanks.

**Comment by ajinabraham** [comment]
Show screen is just an auxiliary feature. It has issues on some Windows  OS versions.

**Comment by jamespenetration** [comment]
but, i still think  django make issue appearance ,  i search django and image  in baidu , a chinese Search [Engine](https://stackoverflow.com/questions/29219162/django-not-show-images) .  django just  allow  pictrue shwon  in   spiceal folder, do you think it's connectd?  just advice. :)  thanks your's response。

**Comment by ajinabraham** [comment]
It works perfectly fine in MAC, Linux and most Windows OS version.

**Comment by luolin2611** [comment]
Hello, my problem is exactly the same as that described by the subject. The port 9339 is not occupied, but the image is not displayed.

**Comment by luolin2611** [comment]
Hello, my problem is exactly the same as the title description of the port 9339 is not occupied, but can not display the image. Can you help me through TeamViewer?
