### ISSUE TITLE
error in cert_analysis (missing argument)

### ISSUE THREAD

**Issue by wintzx** [MobSF/Mobile-Security-Framework-MobSF#363]
Hi 
There is an issue in the file called \StaticAnalyzer\views\android\cert_analysis line 71
the second argument of findall is missing.
It's not really an issue, just something you forgot to commit i think.
Best regards and keep the flag flying in high winds.
Pat

**Comment by ajinabraham** [comment]
It is a bug. Fixed in master.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/e849d234c3004cec5eef12c965df47a50685fa1f
