### ISSUE TITLE
Syntax issue of print.

### ISSUE THREAD

**Issue by t1819** [MobSF/Mobile-Security-Framework-MobSF#366]
At the time of installation of setup.py, it's showing print syntax issue. Please edit the setup.py and add the () after print syntax.

**Comment by DominikSchlecht** [comment]
Could you please provide more information (Error message, how you ran `setup.py` and python-version).

Greetings,
Dominik

**Comment by DominikSchlecht** [comment]
Also please check if the fix fixes it for you :)

Greetings,
Dominik

**Comment by ajinabraham** [comment]
@t1819 Can you confirm if it's fixed?

**Comment by t1819** [comment]
@ajinabraham Yes, it's fixed. Thank you so much.
