### ISSUE TITLE
Syntax highlighting/coloring break on block comments

### ISSUE THREAD

**Issue by perost-l14** [MobSF/Mobile-Security-Framework-MobSF#367]
## EXPLANATION OF THE ISSUE

Version v0.9.4.2 Beta. Android java files.

/ViewSource/ only formats (color codes) source after the last */ in block comments

## STEPS TO REPRODUCE THE ISSUE

View the source of almost any java file. If it has two block comments (/* */), all the text to the end of the second (or the last in file) will be green and not color coded.

suggesting for fix: I looks like the regex (or whatever) searching for */ is too greedy and does not stop on the first occurrence.

## CONSOLE OUTPUT

n/a

## CONTENTS OF LOG FILES

nothing related to this

**Comment by ajinabraham** [comment]
Known issue in thirdparty component. Syntax Highlighter

**Comment by per-l14-test** [comment]
MobSF seems to be using a very old version. Would it be possible to ask for an upgrade to v4 from https://github.com/syntaxhighlighter/syntaxhighlighter?

**Comment by ajinabraham** [comment]
V4 don't have build available in CDN or in Github, I tried building but the CSS is failing. Anyways I have migrated to higlight.js

You can find the fix on latest master.
