### ISSUE TITLE
Detect Vulnerable Javascript Libraries in Hybrid Mobile Apps

### ISSUE THREAD

**Issue by maxchill** [MobSF/Mobile-Security-Framework-MobSF#368]
It seems to me there are lots of opportunities for enhancements for detecting vulnerable hybrid mobile applications.

Such as Retire.js integration for identifying vulnerable Javascript libraries in Hybrid mobile applications

http://retirejs.github.io/retire.js/

**Comment by ajinabraham** [comment]
Tracked separately under enhancements
