### ISSUE TITLE
Static Regex Needed

### ISSUE THREAD

**Issue by unl1k3ly** [MobSF/Mobile-Security-Framework-MobSF#373]
Hi, 

I've been missing lots of IP addresses and URLs when they are hardcoded on APKS. 

I know the MobSF seeks for http/s content and shows as URL, although, could you please considering this functionally to be a regex filter ?

By doing so, MobSF would be much more accurate while doing URL and IP's static analyzes.

Local IP would also be important in this case, it could show a miss configuration that could lead to a vulnerability...

I think you got my idea.

Cheers

**Comment by ajinabraham** [comment]
Tracking this separately

**Comment by ajinabraham** [comment]
Added

**Comment by unl1k3ly** [comment]
thanks ! I'll pull now
