### ISSUE TITLE
Runtime error, static analysis.

### ISSUE THREAD

**Issue by NeuroWinter** [MobSF/Mobile-Security-Framework-MobSF#374]
## EXPLANATION OF THE ISSUE

When I try and upload and analylise com.indeed.android.jobsearch, I get the following error in the server console:

[ERROR] Static Analyzer (/home/neuro/MobSF/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/views/android/static_analyzer.py, LINE 157 "man_an_dic['permissons'],"): 'NoneType' object has no attribute '__getitem__'

## CONSOLE OUTPUT

```
 io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall
Processing io.fabric.sdk.android.services.settings.FeaturesSettingsData
Processing io.fabric.sdk.android.services.settings.IconRequest
Processing io.fabric.sdk.android.services.settings.PromptSettingsData
Processing io.fabric.sdk.android.services.settings.SessionSettingsData
Processing io.fabric.sdk.android.services.settings.Settings
Processing io.fabric.sdk.android.services.settings.SettingsCacheBehavior
Processing io.fabric.sdk.android.services.settings.SettingsData
Processing io.fabric.sdk.android.services.settings.SettingsJsonConstants
Processing io.fabric.sdk.android.services.settings.SettingsRequest
Processing io.fabric.sdk.android.services.settings.UpdateAppSpiCall

[2017-03-19 03:32:22]
[ERROR] Static Analyzer (/home/neuro/MobSF/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/views/android/static_analyzer.py, LINE 157 "man_an_dic['permissons'],"): 'NoneType' object has no attribute '__getitem__'

```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by matandobr** [comment]
This happend to me couple of times, its due to the version of the apktool,
I used older version to fix it

בתאריך 19 במרץ 2017 6:16 AM,‏ "Alex Manson" <notifications@github.com> כתב:

**Comment by NeuroWinter** [comment]
For some reason this only happens with one or two apks..

**Comment by ajinabraham** [comment]
@NeuroWinter Are you using the latest master?
Also can you share an APK that caused this issue?

**Comment by NeuroWinter** [comment]
@ajinabraham Yeah I am and its this apk:

https://apkpure.com/indeed-job-search/com.indeed.android.jobsearch

**Comment by ajinabraham** [comment]
I think you are not on latest master. There was a bug fixed in latest master. The apk just works fine at my end.
[indeed job.pdf](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/867153/indeed.job.pdf)
