### ISSUE TITLE
report generation

### ISSUE THREAD

**Issue by Navya90** [MobSF/Mobile-Security-Framework-MobSF#376]
Cant generate report

Error:
{"pdf_error": "Cannot Generate PDF", "err_details": "No wkhtmltopdf executable found: \"\"\nIf this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf"}

Already downloaded wkhtmlpdf

**Comment by DominikSchlecht** [comment]
Please check if wkhtmltopdf is in the path.

**Comment by ajinabraham** [comment]
Please read: https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf#windows
