### ISSUE TITLE
MAC OS X El Capitan - Static Analysis - class-dump-z error

### ISSUE THREAD

**Issue by georgepetz** [MobSF/Mobile-Security-Framework-MobSF#380]
## EXPLANATION OF THE ISSUE

Hi @ajinabraham ,

I'm using the version 0.9.4,2 of MobSF in MAC OS X El Capitan (v 10.11.6) and when I try to make static analysis under the ipa file, I get the follow error:
[ERROR] - Cannot perform class dump [...] returned non-zero exit status -11

What can I do to avoid this error?

Thanks!

Logs:
```
[INFO] MIME Type: application/octet-stream FILE: MyApp.ipa

[INFO] Performing Static Analysis of iOS IPA
[27/Mar/2017 12:33:01] "POST /upload/ HTTP/1.1" 200 146
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping
[INFO] Get Files, BIN Plist -> XML, and Normalize
[INFO] iOS Info.plist Analysis Started
[INFO] Finding Info.plist in iOS Binary
[INFO] Checking Permissions
[INFO] Checking for Insecure Connections
[INFO] Starting Binary Analysis
[INFO] Starting Otool Analysis
[INFO] Running otool against Binary : MyApp
[INFO] Running class-dump-z against the Binary

[2017-03-27 12:33:15]
[ERROR] - Cannot perform class dump (/Users/compseg/Desktop/ArquivosApp/MobSF_094/StaticAnalyzer/views/ios/binary_analysis.py, LINE 207 "class_dump = subprocess.check_output([class_dump_z_bin, bin_path])"): Command '['/Users/compseg/Desktop/ArquivosApp/MobSF_094/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/compseg/Desktop/ArquivosApp/MobSF_094/uploads/7408aece5baefaf02c35af24a064e62e/Payload/App-B_Sit.app/App-B_Sit']' returned non-zero exit status -11
[INFO] Running strings against the Binary

[2017-03-27 12:33:31]
[ERROR] iOS Binary Analysis (/Users/compseg/Desktop/ArquivosApp/MobSF_094/StaticAnalyzer/views/ios/binary_analysis.py, LINE 262 "binary_analysis_dict["bin_res"] = otool_dict["anal"] + cls_dump"): cannot concatenate 'str' and 'NoneType' objects

[INFO] Connecting to DB

[INFO] Saving to Database

[2017-03-27 12:33:31]
[ERROR] Saving to DB (/Users/compseg/Desktop/ArquivosApp/MobSF_094/StaticAnalyzer/views/ios/db_interaction.py, LINE 125 "BIN_ANAL=bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'

[2017-03-27 12:33:31]
[ERROR] Rendering to Template (/Users/compseg/Desktop/ArquivosApp/MobSF_094/StaticAnalyzer/views/ios/db_interaction.py, LINE 33 "'bin_anal': bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'
[27/Mar/2017 12:33:31] "GET /StaticAnalyzer_iOS/?name=App_Dev_Static.ipa&type=ipa&checksum=7408aece5baefaf02c35af24a064e62e HTTP/1.1" 200 16173
```

**Comment by maxchill** [comment]
Is it a Swift app?

**Comment by georgepetz** [comment]
Yes, it's

**Comment by maxchill** [comment]
That's the problem.  Classdump-z doesn't support Swift apps.  I've been working on this issue myself, and looking at trying 
https://github.com/Maximus-/class-dump-swift 
in the place of class-dump-z. but I imagine there will probably be some other compatibility issues.

**Comment by ajinabraham** [comment]
@georgepetz 
Can you share the IPA or similar IPA that causes the issue. Now I am seeing couple of people raising similar issues.

**Comment by georgepetz** [comment]
@maxchill Thanks for the quick response!

@ajinabraham Sorry, but I can't share the IPA file, after the commend of @maxchill I found one post on this repo about class-dump of Swift language.

**Comment by ajinabraham** [comment]
Ok,
I have to close this as I don't have enough details to debug this issue.

**Comment by kryptoknight13** [comment]
Hi, this app is written in swift.
https://itunes.apple.com/us/app/my-sprint-mobile/id491126018?mt=8

**Comment by afdsghjk** [comment]
Hi guys, are there any solutions about this issue? It is also happened to my IPA file.

**Comment by New2OSx** [comment]
I have same issue and wondering is there any update on it, thank you.

**Comment by ajinabraham** [comment]
Third party app issue. We can't do anything about it currently

**Comment by alokc83** [comment]
@georgepetz : Can you please share what did you find? I am also struggling with the same issue. 
@ajinabraham I don't understand the reference for your comment. All apps are the third party from your/or this toolchain perspective

**Comment by georgepetz** [comment]
Hi @alokc83, actually we didn't use MobSF for this type of analysis. We comment the code that doesn't work to use another results of MobSF.
