### ISSUE TITLE
Yara Required

### ISSUE THREAD

**Issue by forced-request** [MobSF/Mobile-Security-Framework-MobSF#381]
## EXPLANATION OF THE ISSUE

I just installed a35f825 and after installing the packages and trying to run the application I noticed that it throws an error related to Yara. I noticed that the requirements.txt file does not include Yara, so I installed it manually. After doing so things worked fine.

I verified that `APKID_ENABLED = False` in the Settings.py and did not modify the code at all after checkout.

```
  File "/Users/jpoulin/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apkid/apkid.py", line 42, in <module>
    import yara
ImportError: No module named yara
```

**Comment by ajinabraham** [comment]
Nice Catch it is a bug

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/ec1e580b394cbafc5daa5f11dd9e0f559224e29d
