### ISSUE TITLE
Multiple errors on ipa analysis

### ISSUE THREAD

**Issue by bitdaemon** [MobSF/Mobile-Security-Framework-MobSF#382]
Hi All,

I am running MobSF, the latest version, and i am having issues analyzing and ipa file (which i cannot share), and getting problems when trying to analyze it.

As soon the file is uploaded to the framework, it drops me to the result screen, which is apparently does not include any information, and the terminal shows several error messages

## CONTENTS OF LOG FILES
```
[2017-03-30 10:10:11]
[ERROR] - Cannot perform class dump (/Users/ricco/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/binary_analysis.py, LINE 207 "class_dump = subprocess.check_output([class_dump_z_bin, bin_path])"): Command '['/Users/ricco/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/ricco/MobSF/Mobile-Security-Framework-MobSF-master/uploads/ce782e9bbee8383fc73127d09b7fc37a/Payload/SecureNet_iOS.app/SecureNet_iOS']' returned non-zero exit status -11
[2017-03-30 10:10:13]
[ERROR] iOS Binary Analysis (/Users/ricco/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/binary_analysis.py, LINE 262 "binary_analysis_dict["bin_res"] = otool_dict["anal"] + cls_dump"): cannot concatenate 'str' and 'NoneType' objects
[2017-03-30 10:10:13]
[ERROR] Saving to DB (/Users/ricco/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db_interaction.py, LINE 125 "BIN_ANAL=bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'
[2017-03-30 10:10:13]
[ERROR] Rendering to Template (/Users/ricco/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db_interaction.py, LINE 33 "'bin_anal': bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'

```
Trying other ipa files throwing the same errors. Also android apps are being analyzed properly.

Any help would be appreciated.

**Comment by Donegal** [comment]
I am also getting the very same error, I have tried DVIA and iGoat and they work perfectly. I am trying to run it with a new application. Any Ideas?

**Comment by zombietango** [comment]
Same issue here. I can get class_dump_z/MobSF to analyze the last IPA I performed an assessment on but not my current one.

**Comment by ajinabraham** [comment]
Is the IPA coded in Swift. It seems classdumpz can't handle IPA binary coded in Swift.

**Comment by zombietango** [comment]
I don't know for sure, but I have a strong suspicion that you are correct. Damn. Thanks.

**Comment by brajbong** [comment]
Facing same issue here- it's mostly Objective-C but got some swift files as well.

**Comment by ajinabraham** [comment]
Run unit test for MobSF `http://127.0.0.1:8080/runtest/` see if IPA is being analysed. If it's a success, then this is not a MobSF issue. Your system has some issues with classdump or permission issues.

If it's working fine and other IPAs are throwing error. I need a sample IPA to find out the issue. If you can't share a sample IPA that triggers the issue, I can't debug the issue. 

Closing this issue.

**Comment by brajbong** [comment]
An excerpt of the logs I am getting, just showing the error messages. Can you see what's the issue? 

```
[ERROR] - Cannot perform class dump (/Users/some/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/views/ios/binary_analysis.py, LINE 207 "class_dump = subprocess.check_output([class_dump_z_bin, bin_path])"): Command '['/Users/some/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/some/Mobile-Security-Framework-MobSF-0.9.4.2/uploads/7c0da10ea6796cd94ad81224a15452f2/Payload/demoApp.app/demoApp']' returned non-zero exit status -11
[INFO] Running strings against the Binary

[2017-03-31 23:30:22]
[ERROR] iOS Binary Analysis (/Users/some/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/views/ios/binary_analysis.py, LINE 262 "binary_analysis_dict["bin_res"] = otool_dict["anal"] + cls_dump"): cannot concatenate 'str' and 'NoneType' objects

[INFO] Connecting to DB

[INFO] Saving to Database

[2017-03-31 23:30:22]
[ERROR] Saving to DB (/Users/some/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/views/ios/db_interaction.py, LINE 125 "BIN_ANAL=bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'

[2017-03-31 23:30:22]
[ERROR] Rendering to Template (/Users/some/Mobile-Security-Framework-MobSF-0.9.4.2/StaticAnalyzer/views/ios/db_interaction.py, LINE 33 "'bin_anal': bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'
```

**Comment by brajbong** [comment]
@ajinabraham I know this issue is already closed, but any ideas/timelines as to when Swift also would be supported?

**Comment by ajinabraham** [comment]
We are using a thridparty tool for this purpose. We can't do anything unless they do the fixing.
