### ISSUE TITLE
detect and report android app allowed to be loaded as plugin

### ISSUE THREAD

**Issue by anantshri** [MobSF/Mobile-Security-Framework-MobSF#384]
reference : https://www.blackhat.com/docs/asia-17/materials/asia-17-Luo-Anti-Plugin-Don't-Let-Your-App-Play-As-An-Android-Plugin.pdf

**Comment by ajinabraham** [comment]
No public tool available as per my knowledge.This is a library which can be integrated with android application to prevent from being abused. (not available publicly)
