### ISSUE TITLE
Application Transport Security (ATS) check of iOS Apps gives wrong results

### ISSUE THREAD

**Issue by SilentServices** [MobSF/Mobile-Security-Framework-MobSF#385]
## EXPLANATION OF THE ISSUE

MobSF (current code as of 3. April 2017) declares the Application Transport Security settings as secure even if "NSAllowsArbitraryLoads" is defined as True in the info.plist of the targeted iOS app.

## STEPS TO REPRODUCE THE ISSUE

Open an app with ATS set to NSAllowsArbitraryLoads=true. Analyze with MobSF and see the results.

**Comment by ajinabraham** [comment]
@DominikSchlecht Any ideas?

**Comment by DominikSchlecht** [comment]
I will look into this.

**Comment by floyd-fuh** [comment]
Just wanted to add a "me too". I made a screenshot that shows the "secure" result but also the Info.plist shown in MobSF clearly stating that insecure requests are allowed:

![ast_secure_insecure](https://user-images.githubusercontent.com/1428689/30651436-fcbfeea2-9e25-11e7-9d3c-dd1cfaf08b7b.png)

**Comment by superpoussin22** [comment]
I can confirm the solution from @suruchisrivastava1701 works fine and is correct

**Comment by ajinabraham** [comment]
Looking into it.

**Comment by ajinabraham** [comment]
This should be fixed in latest master: https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/e54ceb1d43a60d258e4ba8b47e6830a16409f174

@superpoussin22 @DominikSchlecht  Can you test and verify this?

**Comment by superpoussin22** [comment]
@ajinabraham  that's ok for me :) thanks
