### ISSUE TITLE
What is the principle of dynamic analysis?

### ISSUE THREAD

**Issue by Zhang343750200** [MobSF/Mobile-Security-Framework-MobSF#388]
I wish you could briefly talk something about the principle of dynamic analysis?
I have the following suggestions：
- Can the dynamic analysis be executed automatically just like static analysis? 
- When dynamic analysis is performing, can we capture the network traffic and save in pcap file ?

**Comment by ajinabraham** [comment]
Can the dynamic analysis be executed automatically just like static analysis?
-under implementation.
When dynamic analysis is performing, can we capture the network traffic and save in pcap file ?
- not available at the moment.
Please use slack channel for discussion.

**Comment by asifurrouf** [comment]
Is it possible to run dynamic analysis on a Custom Android VM or in a Simulator?
