### ISSUE TITLE
No AVD support

### ISSUE THREAD

**Issue by coloboslexx** [MobSF/Mobile-Security-Framework-MobSF#391]
There is AVD support [mentioned in wiki](https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/9.-Use-AVD-Emulator) but there is no mobsfy_AVD.py script inside MobSF master and no AVD SETTINGS section in settings.py for manual config.

**Comment by ajinabraham** [comment]
This feature is not available in master branch yet. Currently under testing.
