### ISSUE TITLE
Feature request: Save reports to disk automatically when performing mass analysis

### ISSUE THREAD

**Issue by securisec** [MobSF/Mobile-Security-Framework-MobSF#395]
Feature request: Save reports to disk automatically when performing mass analysis

Due to the nature of mobsf reports (bootstrap and other dependencies), it is not super easy to download the reports once a scan completes. I tried writing a wrapper that would do that while using regex to change the locations, but it doesnt fully work. 

Thanks!

**Comment by ajinabraham** [comment]
No plans for writing reports to Disk as it's already stored in DB. You can directly query the DB or use the PDF generation APIs.

This sample code gives you an idea: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/tests.py#L51-L70
