### ISSUE TITLE
How to run dynamic analysis on rooted android device

### ISSUE THREAD

**Issue by Chrisified** [MobSF/Mobile-Security-Framework-MobSF#396]
## EXPLANATION OF THE ISSUE

Hi. I have installed Mobsf on windows and Kali successfully but the APK file I want tested only gets static analysis results done. When we go to Dynamic analysis the App fails in the emulator saying "Unfortunately the APP XXX has stopped running". I presumed this was a thing with the emulator and decided to root n actual android device running Jellybean that had the app running perfectly. I have done the configuration of the device until the last step but now Im clueless as to how to use the physical android device for dynamic analysis? 

When I run the dynamic analysis it still tries to open the Virtualbox emulator! Also is there anyway to change the emulator? 

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
Did you miss this step?

https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-dynamic-analyzer-with-rooted-android-device

You need to set Real Device to True.

**Comment by kperevoznikova** [comment]
> Did you miss this step?
> 
> https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-dynamic-analyzer-with-rooted-android-device
> 
> You need to set Real Device to True.

There is no such step in a [new wiki](https://mobsf.github.io/docs/#/dynamic_analyzer). Did you remove this feature?

**Comment by ajinabraham** [comment]
While it may work with some hacks, due to the overwhelming amount of support requests, we officially dropped any support on setting up with a real device.
