### ISSUE TITLE
Dynamic Analyser - apps with HTTPS traffic is not working 

### ISSUE THREAD

**Issue by Madapppoe** [MobSF/Mobile-Security-Framework-MobSF#400]
When use the dynamic analysis module and try to analyze APK with https requests inside the app activities not working even when i tried any https website from the browser while the proxy is enabled the websites not working as well.

Steps
======
1- Open Mobsf webapp
2- Upload apk with https traffic
3- after the static analysis finish , press "Start dynamic Analysis"
4- Wait till the VM snapshot is up and running
5- Press "Create Environment"

Actual : 
The app will be started but nothing happened , loading forever

Expected : 
The app will be started and the activity responses will be retrieved and user start navigating the app

* you can try the following app "https://play.google.com/store/apps/details?id=com.olit.xclusivescard"
which is tested after removing the proxy and it opened correctly.

**Comment by Madapppoe** [comment]
Any updates regarding the mentioned issue

**Comment by ajinabraham** [comment]
Could be problems like app not allowing traffic to be send through a proxy. Let me investigate with this app.

**Comment by ajinabraham** [comment]
Works fine for the app for me using MobSF AVD and VM. Might be a port issue or something at your end.
