### ISSUE TITLE
adb root commands errors from host to device 

### ISSUE THREAD

**Issue by androcoverage** [MobSF/Mobile-Security-Framework-MobSF#403]
## EXPLANATION OF THE ISSUE

All adb root commands are failing. MobSF try to send root commands with the "adb shell su -c |command|" argument, which does not works for me (OS/adb/MobSF version are following). The solution is to use "adb shell su root |command|" instead.   

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

$ adb version
Android Debug Bridge version 1.0.32

Mobile Security Framework v0.9.5.2 Beta

## STEPS TO REPRODUCE THE ISSUE

1 - python mobsfy.py
2 - enter |device-serial|
3 - choose 2 (Device)  

## CONSOLE OUTPUT

[...]
[INFO] Executing Command - |adb-path| -s |device-serial| shell su -c mount -o rw,remount,rw /system
unknown option -- o

Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk

[INFO] Executing Command - |adb-path| -s |device-serial| shell su -c cp /data/local/tmp/0025aabb.0 /system/etc/security/cacerts/0025aabb.0
Unknown id: /data/local/tmp/0025aabb.0

[INFO] Executing Command - |adb-path| -s |device-serial| shell su -c chmod 644 /system/etc/security/cacerts/0025aabb.0
Usage: chmod [OPTION] <MODE> <FILE>
  -R, --recursive         change files and directories recursively
  --help                  display this help and exit
[...]

## QUICK WORKAROUND

Replace "-c" with "root" in these files:

./mobsfy.py:67:    ExecuteCMD([adb, "-s", adbconnect, "shell", "su", "-c",
./mobsfy.py:69:    ExecuteCMD([adb, "-s", adbconnect, "shell", "su", "-c", "cp",
./mobsfy.py:71:    ExecuteCMD([adb, "-s", adbconnect, "shell", "su", "-c", "chmod",
./DynamicAnalyzer/views/android/android_dyn_shared.py:25:                             "su", "-c", "mount", "-o", "rw,remount,rw", "/system"])
./DynamicAnalyzer/views/android/android_dyn_shared.py:28:                             "su", "-c", "mount", "-o", "rw,remount,rw", "/system"])
./DynamicAnalyzer/views/android/android_dynamic.py:420:                                     "-c",
./DynamicAnalyzer/views/android/android_dynamic.py:429:                                     "-c",
./DynamicAnalyzer/views/android/android_dynamic.py:455:                                 "-c",

**Comment by ajinabraham** [comment]
This is device specific issue i guess. Is your device rooted and has Super Su installed?
Alternative rooting solutions and binaries are not supported at the moment.

**Comment by androcoverage** [comment]
No, I made a custom AOSP 6.0 build with userdebug enabled. So the su is natively embeded in Android.

**Comment by ajinabraham** [comment]
Ok We support only till v4.4.
You might need to change a lot of things including Xposed Framework to support 6.0.
This is out of scope for current version of MobSF.
