### ISSUE TITLE
adding option for dynamic analysis with wired adb instead of wifi adb

### ISSUE THREAD

**Issue by paul-irolla** [MobSF/Mobile-Security-Framework-MobSF#404]
It would be convenient to use dynamic analysis with a device identified with a serial number. 
It requires only a quick fix: 

`MobSF/settings.py`, add under `ANDROID REAL DEVICE SETTINGS`:

    DEVICE_SERIAL = "your-device-serial-here"

`MobSF/android_dyn_shared.py`, in `get_identifier()`, replace:

     if settings.ANDROID_DYNAMIC_ANALYZER == "MobSF_REAL_DEVICE":
         return settings.DEVICE_IP + ":" + str(settings.DEVICE_ADB_PORT)

with

    if settings.ANDROID_DYNAMIC_ANALYZER == "MobSF_REAL_DEVICE":
        if settings.DEVICE_SERIAL:
            return settings.DEVICE_SERIAL
        else:
            return settings.DEVICE_IP + ":" + str(settings.DEVICE_ADB_PORT)

**Comment by ajinabraham** [comment]
Would be neat if you can sent a PR. 
Else will take this up for next release or milestone.

**Comment by ajinabraham** [comment]
Tracked Separately

**Comment by ajinabraham** [comment]
Out of scope with new dynamic analyzer
