### ISSUE TITLE
APKid not getting installed on Windows10

### ISSUE THREAD

**Issue by KotamRamana** [MobSF/Mobile-Security-Framework-MobSF#407]
I have downloaded latest 0.9.5 Beta version from GIThub. I am planning to enable APKiD feature.
I have this installed on my laptop:
    1)Python 2.7.11
    2)VCForPython27

## STEPS TO REPRODUCE THE ISSUE
git clone https://github.com/rednaga/APKiD
cd APKiD
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install

## CONSOLE OUTPUT
C:\Users\********\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -Iyara/windows/include -IC:\Python27\include -IC:\Python27\PC /Tcyara\libyara\lexer.c /Fobuild\temp.win32-2.7\Release\yara\libyara\lexer.obj
lexer.c
lexer.l(794) : warning C4090: 'function' : different 'const' qualifiers
lexer.l(846) : error C2143: syntax error : missing ';' before 'type'
lexer.l(853) : error C2065: 'buf' : undeclared identifier
lexer.l(853) : warning C4022: 'ReadFile' : pointer mismatch for actual parameter 2
lexer.l(853) : error C2065: 'buf' : undeclared identifier
lexer.l(867) : error C2065: 'buf' : undeclared identifier
lexer.l(867) : warning C4047: 'function' : 'char *' differs in levels of indirection from 'int'
lexer.l(867) : warning C4024: 'yara_yy_scan_bytes' : different types for formal and actual parameter 1
error: command 'C:\\Users\\*********\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

## CONTENTS OF LOG FILES
NA

**Comment by ajinabraham** [comment]
You might need to post it on APKid repository

**Comment by KotamRamana** [comment]
Hi Ajin,
Please look at issue 277 as I reopen it. Regards and Thanks, 
K.V.Ramanamurthy, 
B210,Pariwar Pendant Apartment, 1st A Cross, 3 main road,Doctors Layout, Kodichikkanahalli,Bengaluru - 560076, +91-7028082804(Mobile) 

    On Tuesday, May 9, 2017 2:53 PM, Ajin Abraham <notifications@github.com> wrote:
 

 You might need to post it on APKid repository—
