### ISSUE TITLE
VBOXMANAGE_BINARY input from Setting.py  is not pickeup and VM is not started

### ISSUE THREAD

**Issue by KotamRamana** [MobSF/Mobile-Security-Framework-MobSF#409]
## EXPLANATION OF THE ISSUE
I have configure setting.py for the parameter as VBOXMANAGE_BINARY = "D:/Oracle/Virtualbox/VBoxManage.exe". But the mobsf_vm is not launched and get error during dynamic analysis.

## STEPS TO REPRODUCE THE ISSUE
Please input location of VBoxManage.exe location other than standard define in C:. like VBOXMANAGE_BINARY = "D:/Oracle/Virtualbox/VBoxManage.exe" in setting.py config file.

## CONSOLE OUTPUT
Error: Unable to connect 192.168.56.5:5555.

I have debugged issue and found that utils.py does not pickup correct value. Hence quick fix was done by me  as given below:
        if platform.system() == "Windows":
                # Path to VBoxManage.exe
                vbox_path = ["D:\Oracle\VirtualBox\VBoxManage.exe",
                             "C:\Program Files (x86)\Oracle\VirtualBox\VBoxManage.exe"]
                for path in vbox_path:
                    if os.path.isfile(path):
                        return path

**Comment by ajinabraham** [comment]
If you set the path correct. in `VBOXMANAGE_BINARY` It should not throw an error.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/6cd9c2eadf54faffe42d0eccd9683c1f866c6e67/MobSF/utils.py#L161-L162

**Comment by KotamRamana** [comment]
HI Ajin,
Thanks. Regards and Thanks, 
K.V.Ramanamurthy, 
B210,Pariwar Pendant Apartment, 1st A Cross, 3 main road,Doctors Layout, Kodichikkanahalli,Bengaluru - 560076, +91-7028082804(Mobile) 

    On Thursday, May 11, 2017 1:42 PM, Ajin Abraham <notifications@github.com> wrote:
 

 Closed #409.—
