### ISSUE TITLE
File "setup.py" line 445 in <module> _install_remote()

### ISSUE THREAD

**Issue by noahfranklin** [MobSF/Mobile-Security-Framework-MobSF#410]
When I run MobSF on my Windows Laptop. I am getting following error kindly help me resolve this issue.
Note: I am using Vmware for another testing    and Vbox for MobSF.

File "setup.py", line 445 in <module>
_install_remote()
File "stepup.py", line 340, in _install_remote
autostart()
File "steup.py", line 340, in autostart
autostart_file.write (bytes(text, 'utf8'))
TypeError: str() takes at most 1 arguments (2give)

**Comment by DominikSchlecht** [comment]
Hey,
this seems strange - could you please remove the current install from the file-system and re-install mobsf?

Greetings,
Dominik

**Comment by ajinabraham** [comment]
Closing as there is no response.
