### ISSUE TITLE
Error Message MobSF Setup.py start server 

### ISSUE THREAD

**Issue by noahfranklin** [MobSF/Mobile-Security-Framework-MobSF#411]
Please press any key when done...
[*] Creating autostart binary...
[*] Done. Start the server.
Listening on port 8000...

127.0.0.1 - - [17/May/2017 07:32:19] code 501, message Unsupported method ('GET'
)
127.0.0.1 - - [17/May/2017 07:32:19] "GET / HTTP/1.1" 501 -

**Comment by ajinabraham** [comment]
Not enough information. Closing the bug. This is only for enabling Windows App analysis support if you are running on non windows OS
