### ISSUE TITLE
Static Analysis - Malware Check - False Positive

### ISSUE THREAD

**Issue by SatanicDrNull** [MobSF/Mobile-Security-Framework-MobSF#415]
## EXPLANATION OF THE ISSUE

On version 0.92 as well 0.95 I detected the framework incorrectly matches the IP 127.0.0.1 with a string inside the Malware-DB
This was verified on android component. Inspecting the code, I am almost sure the same occurs on iOS and Windows

The problem seems to be on line 132 of the views.py file inside the MalwareAnalyzer folder:

`if (domain in details_dict["domain_or_url"]) or (domain in details_dict["ip"]):`

This part of the code tells to seek the  "domain" content  inside the "details_dict['ip']

As the string "127.0.0.1" is part of the registry on MalwareDb file: 
`193.107.19.80/inter/gate.php?hwid=4281525696&pc=COMPUTERNAME&localip=127.0.0.1&winver=x32`

It returns as a false positive.
```

 
## STEPS TO REPRODUCE THE ISSUE

```
1. Upload an Apk where inside the code is referred the url "http:\\127.0.0.1"
2. Execute the static analysis
3. The Malware Check section will show a malware is found.
```

## CONSOLE OUTPUT

![bug_mobsf](https://cloud.githubusercontent.com/assets/28790490/26220208/1dc03c60-3be8-11e7-84d3-9e04b9b0da77.JPG)

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
```
No MobSF.log was generated.
```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```
<!--
BEFORE POSTING YOUR ISSUE/BUG
- These comments won't show up when you submit the issue.
- GitHub issues ARE NOT FOR SUPPORT, DISCUSSIONS AND QUESTIONS! 
- If you have questions, use our slack channel. Request invitation here https://goo.gl/6cYU5a.
- Installation problems with regards to requirements.txt or VirtualBox in not considered as a MobSF issue.
- Reproduce issue in the latest master and try to add as much detail as possible.
- If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.
- Once you open a bug, you should also provide additional information if requested. 
- Failure to do so in 25 days will result in closure of the bug without further communication.
-->

**Comment by ajinabraham** [comment]
Will look into this for next release

**Comment by PaulAnton** [comment]
Can I solve this bug? If i can, can you please provide me a sample of the DB file from where the line is read?

**Comment by ajinabraham** [comment]
sure go ahead, here is the logic related to malware analysis: https://github.com/MobSF/Mobile-Security-Framework-MobSF/tree/master/MalwareAnalyzer

**Comment by PaulAnton** [comment]
hi Anjin, 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/431

**Comment by PaulAnton** [comment]
Hi Anjin- #431 is the changes done-
**The Logic:**
taking the part of the IP before the forward slash ('/')- this way it will avoid the part that might contain 127.0.0.1. 

 assuming the urllist will have just the part before the forward slash- I think my logic is correct- please have a look at it and merge it with the main code if you agree

**Comment by ajinabraham** [comment]
I will do a review and update my comments against the PR.
