### ISSUE TITLE
PDF-Report scales with screen resolution

### ISSUE THREAD

**Issue by DominikSchlecht** [MobSF/Mobile-Security-Framework-MobSF#420]
## EXPLANATION OF THE ISSUE

Doing an app analysis on an iMac with an an large screen renders the text in the pdf utterly small. (Sadly I can't post the pdf...)

## STEPS TO REPRODUCE THE ISSUE

```
1. Analyse an app
2. Create am PDF-Report
```

## CONSOLE OUTPUT

```
None
```

## CONTENTS OF LOG FILES

```
None
```

## TODO
```
Try to fix the pdf-text size readable for a normal A4 page.
```

**Comment by ajinabraham** [comment]
Tweaking this should fix it.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/7734de07e33ffb2814f69b718bbae08f437a43d5/StaticAnalyzer/views/shared_func.py#L174-L187

**Comment by ajinabraham** [comment]
Tracked separately.
