### ISSUE TITLE
Integrating with MobSF with Appium

### ISSUE THREAD

**Issue by pavanbachu0604** [MobSF/Mobile-Security-Framework-MobSF#423]
Hello , I am new to Mobile Security. I want to know if there is possibility to implement the MobileSecurity with existing framework where i use Appium (Selenium) to perform the testing on iOS Devices.

Appium : 1.6.4
iOS Version expected 10+

**Comment by ajinabraham** [comment]
We do not support out of the box, how ever, you can integrate as the project is open source.
