### ISSUE TITLE
Implementing MobSF with existing framework

### ISSUE THREAD

**Issue by pavanbachu0604** [MobSF/Mobile-Security-Framework-MobSF#424]
I am completely new to Mobile Security, I was curious if its possible to implement the MobSF to our existing framework that uses Appium (Selenium) for functional testing.

**Comment by ajinabraham** [comment]
Follow static analysis unit tests here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/tests.py#L16
This should help you to integrate it.
