### ISSUE TITLE
iOS Scanning Error

### ISSUE THREAD

**Issue by aaronthomas1406** [MobSF/Mobile-Security-Framework-MobSF#425]
## EXPLANATION OF THE ISSUE
When I ran an iOS scan I received an error output outlined in the console output and log section of this issue. In terms of expected results, I was expecting to see app scan results once the scan was completed, but when the scan completed the MobSF UI returned a screen with no results. 
I am using the most current master MobSF download. 

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT
[2017-06-01 03:06:39]
[ERROR] - Reading from Info.plist (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/plist_analysis.py, LINE 213 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/uploads/88698177140f3ae24b326500fb7c9d81/Payload/'
[INFO] Starting Binary Analysis

[2017-06-01 03:06:39]
[ERROR] iOS Binary Analysis (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/binary_analysis.py, LINE 241 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/uploads/88698177140f3ae24b326500fb7c9d81/Payload/'
[INFO] Connecting to DB
[INFO] Saving to Database
[2017-06-01 03:06:39]
[ERROR] Saving to DB (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db_interaction.py, LINE 118 "INFOPLIST=info_dict["plist_xml"],"): 'NoneType' object has no attribute '__getitem__'
[2017-06-01 03:06:39]
[ERROR] Rendering to Template (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db_interaction.py, LINE 26 "'plist': info_dict["plist_xml"],"): 'NoneType' object has no attribute '__getitem__'
[01/Jun/2017 03:06:39] "GET /StaticAnalyzer_iOS/?name=Ethicon.ipa&type=ipa&checksum=88698177140f3ae24b326500fb7c9d81 HTTP/1.1" 200 16173

## CONTENTS OF LOG FILES
[2017-06-01 03:06:39]
[ERROR] Unzipping Error (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/shared_func.py, LINE 69 "with zipfile.ZipFile(APP_PATH, "r") as z:"): File is not a zip file
[2017-06-01 03:06:39]
[ERROR] Unzipping Error (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/shared_func.py, LINE 86 "dat = subprocess.check_output(['unzip', '-qq', '-l', APP_PATH])"): Command '['unzip', '-qq', '-l', u'/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/uploads/88698177140f3ae24b326500fb7c9d81/88698177140f3ae24b326500fb7c9d81.ipa']' returned non-zero exit status 9
[2017-06-01 03:06:39]
[ERROR] - Reading from Info.plist (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/plist_analysis.py, LINE 213 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/uploads/88698177140f3ae24b326500fb7c9d81/Payload/'
[2017-06-01 03:06:39]
[ERROR] iOS Binary Analysis (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/binary_analysis.py, LINE 241 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/uploads/88698177140f3ae24b326500fb7c9d81/Payload/'
[2017-06-01 03:06:39]
[ERROR] Saving to DB (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db_interaction.py, LINE 118 "INFOPLIST=info_dict["plist_xml"],"): 'NoneType' object has no attribute '__getitem__'
[2017-06-01 03:06:39]
[ERROR] Rendering to Template (/Users/Tizzle/MobSF/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db_interaction.py, LINE 26 "'plist': info_dict["plist_xml"],"): 'N
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)

**Comment by ajinabraham** [comment]
Can you share the IPA?

**Comment by aaronthomas1406** [comment]
Unfortunately, I cannot share the IPA due to company policies.

**Comment by ajinabraham** [comment]
Can't help much in that case. Closing the bug.
