### ISSUE TITLE
Does MobSF supports REST API ?

### ISSUE THREAD

**Issue by vahidd** [MobSF/Mobile-Security-Framework-MobSF#426]
I was wondering Is there a REST API so I can submit my APK or IPA files and get a JSON response?

**Comment by ajinabraham** [comment]
At the moment there is no REST API. But can follow the unit test to script one that will give you a PDF report after uploading a file.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/tests.py#L16

**Comment by ajinabraham** [comment]
Yes we do. 
See API Docs: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/9.-REST-API-Documentation
