### ISSUE TITLE
Not able to install xposed

### ISSUE THREAD

**Issue by priyacshekar** [MobSF/Mobile-Security-Framework-MobSF#428]
Hi,
for dynamic analysis , i ran the command run mobsf.py. but after that i am not able to install/update the xposed , it says "xposed in not compatible with Android sdk version 21 or your processor architecture(armeavi v7a)
cannot link executable : couldnt load  library "libdvm.so" needed by /data/data/de.robv.android.xposed.installer"  kindly suggest what needs to be done here

**Comment by ajinabraham** [comment]
It's clearly mentioned we don't support Android 5
