### ISSUE TITLE
Restructure the entire repo for extensibility / Create documentation for contributing

### ISSUE THREAD

**Issue by xandfury** [MobSF/Mobile-Security-Framework-MobSF#430]
Hi! 
Thanks for your contribution to the community. I feel however, that the repository lacks somewhat structure.
For example, I needed to study how the static analysis is done with MobSF, I would require a tremendous effort just to locate all related files. There is also no documentation for extensibility or how MobSF works under the hood. 
Overall this is a wonderful tool but I think should be documentation/structure to the code provided as I mentioned above.

**Comment by ajinabraham** [comment]
All the static analysis related modules are found under https://github.com/MobSF/Mobile-Security-Framework-MobSF/tree/master/StaticAnalyzer/views

Can share an example of the project structure that you are expecting?

**Comment by ajinabraham** [comment]
Closing as 25 days grace period is over
