### ISSUE TITLE
Settings - SKIP_CLASSES not working on Windows

### ISSUE THREAD

**Issue by egerod** [MobSF/Mobile-Security-Framework-MobSF#432]
## EXPLANATION OF THE ISSUE

After scanning an app on a Windows and a Linux machine, the Windows report included many entries from com.google.\*, compared to the Linux report with included nothing. 
com/google is set in the SKIP_CLASSES list on both machines, so it appears the setting isn't working on Windows machine.
Removing com/google from the Linux SKIP_CLASSES settings, results in identical reports from the two machines (both including com.google.\*), reinforcing the setting not working as intended on Windows. 

I suspect the issue may be in the comparison of the SKIP_CLASSES file paths and the Windows file paths.

Windows: Windows 10, version 1607
MobSF: 0.9.5.2 beta

## STEPS TO REPRODUCE THE ISSUE

```
1. Scan app including com.google code
```

## CONSOLE OUTPUT

```
None
```

## CONTENTS OF LOG FILES

```
NONE
```

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/339e8e6c1f6e7c5cd6cfc15194b1c688c4acfe51
