### ISSUE TITLE
Google account pre-configured in OVA

### ISSUE THREAD

**Issue by mattoufoutu** [MobSF/Mobile-Security-Framework-MobSF#436]
## EXPLANATION OF THE ISSUE

The OVA image you provide comes with a pre-configured Google account (yodleebanglore[at]gmail.com), which is configured to sync application data online. This means that if people assess applications without noticing this, some information about the application that's being assessed could leak and be synchronized on this account.

In my opinion, the OVA should NOT come with a preconfigured account, moreover one that will synchronize applications data without the user being aware of it... If an account is required for any task, it should be up to the user to create one he owns himself.

## STEPS TO REPRODUCE THE ISSUE

```
1. Import and start the OVA
2. Go to Android's account settings
3. Notice that a 3rd-party Google account is already configured
```

**Comment by ajinabraham** [comment]
The ova is preconfigured with a dummy account to facilitate the automated analysis of some apps that requires a google account or play services. If you are concerned, you should use alternate options for dynamic analysis like Rooted Device, Another VM or Android ARM emulator etc...

**Comment by mattoufoutu** [comment]
I understand the point, but it would still be nice to put a disclaimer
somewhere so that users are aware of it...

Le mer. 5 juil. 2017 à 08:46, Ajin Abraham <notifications@github.com> a
écrit :
