### ISSUE TITLE
Android apps are unable to connect to server while performing dynamic analysis

### ISSUE THREAD

**Issue by khanfiroj12345** [MobSF/Mobile-Security-Framework-MobSF#437]
## EXPLANATION OF THE ISSUE

Version: 0.9.5
Environment: Android VM
Everything is configured as explained. While performing dynamic analysis Apk is installed, launched properly. While exploring the app, it never connects server.

## STEPS TO REPRODUCE THE ISSUE

```
1. Launch Dynamic analysis
2. Create environment
3. Navigate through the Android app launched on Android
4. App never connects to the Server (Although I am able to access the internet on VM if I use Play store)
5 Settings as follows:
   VM IP:192.168.57.101
   Proxy configured: 192.168.51.1:1337
```

## CONSOLE OUTPUT

No error on Console

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
 there is no error in MobSF.log
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```
[E 170704 14:20:48 iostream:554] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\iostream.py", line 515, in _handle_events
        self._handle_connect()
      File "C:\Python27\lib\site-packages\tornado\iostream.py", line 1427, in _handle_connect
        do_handshake_on_connect=False)
      File "C:\Python27\lib\site-packages\tornado\netutil.py", line 526, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
        _context=self)
      File "C:\Python27\lib\ssl.py", line 582, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

**Comment by ajinabraham** [comment]
```
VM IP:192.168.57.101
   Proxy configured: 192.168.51.1:1337
```
This won't work.

The Network range should be same. 192.168.51.1 won't be able to reach 192.168.57.101
The host IP should be something like 192.168.57.x
