### ISSUE TITLE
Xposed is not compatible with android SDK version 23 (Libdvm not found) 

### ISSUE THREAD

**Issue by ariefibis** [MobSF/Mobile-Security-Framework-MobSF#439]
## EXPLANATION OF THE ISSUE

Hello, Gm 　 just one concern while setting up a dynamic environment ...I tried setting up a VM using genymotion but our apk is compatible only with version 5 or above ...wherein dynamic mobsf it should be 4.0.3 to 4.4 I guess if I am not wrong ...Is there a chance it can be updated to compatible versions or any other alternative which could help.

## STEPS TO REPRODUCE THE ISSUE

```
commands python mobfsf.py 
*select vm
*ip address and port number

## CONSOLE OUTPUT

![mobsf](https://user-images.githubusercontent.com/22467094/28103335-d644db3a-66f2-11e7-9173-f22cd9d3497c.PNG)
![mobsf2](https://user-images.githubusercontent.com/22467094/28103337-d7b9ec94-66f2-11e7-992d-dd9938b21b89.PNG)


Please do the needful

Thanks and Regards,
Mohammed arief.A

**Comment by ajinabraham** [comment]
Higher versions of Android is not supported by MobSF.
