### ISSUE TITLE
How to update? THX! 

### ISSUE THREAD

**Issue by laughing-gor** [MobSF/Mobile-Security-Framework-MobSF#441]
I am a new user to MobSF and ubuntu.
currently I am using v9.0.2 beta ,If I want to update to v9.0.5 beta, 
Is the following the right way to update ? THX!

1.copy and unzip source code(https://github.com/MobSF/Mobile-Security-Framework-MobSF/archive/v0.9.5.2.zip)
, and then paste to original MobSF folder. 
2. update the dependencies according to the requirements.txt (pip install -r /path/to/requirements.txt)

Am I right?
Anything else should I avoid or do ?
THX!

**Comment by ajinabraham** [comment]
The easiest is
``` 
git clone repo
git pull
```
also check: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf

Please use this for bug reports only. For discussions and questions use slack channel/

**Comment by SubZe12o** [comment]
git clone repo
git pull
Is not working for me

also check: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
explains how to perform a database migrations but not how to update.  Currently have Mobile-Security-Framework-MobSF-0.9.2 installed and every time I run git clone repo

fatal: repository 'repo' does not exist\

any ideas

**Comment by ajinabraham** [comment]
Because you didn't cloned the initial repo. You need to initialise a git repository inside your current MobSF directory

**Comment by SubZe12o** [comment]
I must be noob then, because I am trying that its not working.  Is it possible to give me steps :( sorry noob I am.

**Comment by SubZe12o** [comment]
I followed this:

Linux

sudo apt install build-essential libssl-dev libffi-dev python-dev
pip install -r requirements.txt --user

**Comment by ajinabraham** [comment]
for support use our slack channels. github is strictly for bugs

**Comment by mkaraoz** [comment]
If anybody ends up in here, check this documentation page: https://mobsf.github.io/docs/#/updating 

cd Mobile-Security-Framework-MobSF/
git pull origin master
. venv/bin/activate
pip install --no-cache-dir -r requirements.txt
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate
deactivate
