### ISSUE TITLE
download report

### ISSUE THREAD

**Issue by shystartree** [MobSF/Mobile-Security-Framework-MobSF#462]
I can not download report ,the error is: 
Inappropriate argument type.
__init__() got an unexpected keyword argument 'status_code'

Thank you for your time

**Comment by ajinabraham** [comment]
Share the complete console log.

**Comment by shystartree** [comment]
Are you refer to the MobSF.log?  here is the contents of the log:
[ERROR] Malware DB Update (XX\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views.py, LINE 91 "if sha256(tmp_dwd.name) != sha256(mal_db):"): [Errno 13] Permission denied: 'c:\\users\\qingyu\\appdata\\local\\temp\\tmphrckrb'
[2017-08-04 17:27:42]
[ERROR] __init__() got an unexpected keyword argument 'status_code'

**Comment by shystartree** [comment]
Are you refer to the MobSF.log? here is the contents of the log:
[ERROR] Malware DB Update (XX\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views.py, LINE 91 "if sha256(tmp_dwd.name) != sha256(mal_db):"): [Errno 13] Permission denied: 'xx\appdata\local\temp\tmphrckrb'
[2017-08-04 17:27:42]
[ERROR] init() got an unexpected keyword argument 'status_code'

**Comment by ajinabraham** [comment]
You have have proper permissions to run MobSF. Permission denied is due to that. Run MobSF with standard privileges.
