### ISSUE TITLE
MobSF_VM NO Internet Connection

### ISSUE THREAD

**Issue by phspade** [MobSF/Mobile-Security-Framework-MobSF#465]
I cannot test the apk files without internet.

**Comment by ajinabraham** [comment]
This is not a bug. If you feel so feel free to give detailed description after following the guidelines to report a bug. Please use the slack channel otherwise.

**Comment by phspade** [comment]
im just asking a question.. on how to configure it with Internet

**Comment by ajinabraham** [comment]
I am telling you as per this project guidelines, GitHub issues are ONLY for reporting bugs or feature requests. Use slack channel for questions and discussions.
