### ISSUE TITLE
Android Static Analysis test request

### ISSUE THREAD

**Issue by MrVaughan** [MobSF/Mobile-Security-Framework-MobSF#468]
Internal username and path disclosure:
I believe this also applies to iOS but apple strips this data out before it goes to iTunes.

If you run `strings *|grep "/Users/"` on any of the compiled library .so files you get the username of the developer who compiled the binary. You also get the folder structure/layout of the developers local machine. That is if they are running on a mac. Similar strings could be searched for windows/nix based.

Love the tool, thanks!

**Comment by ajinabraham** [comment]
Good suggestion. Would be great if you can sent a PR, else we will track it as an enhancement.

**Comment by ajinabraham** [comment]
tracked separately
