### ISSUE TITLE
PDF download not working

### ISSUE THREAD

**Issue by ottucsakj** [MobSF/Mobile-Security-Framework-MobSF#469]
## EXPLANATION OF BUG
PDF download not working under 0.9.5.4 beta. I get {"report": "Report not Found"} error and 500 HTTP error code in the console log. I have wkhtmltopdf installed and added to the Windows path, but I cannot see any error related to pdf generation.

## STEPS TO REPRODUCE

1. Upload apk
2. Click on download pdf button

![image](https://user-images.githubusercontent.com/5910566/29525035-baa69724-8691-11e7-856c-f54381fda3d4.png)

**Comment by ajinabraham** [comment]
Migrate your DB. Thats the issue.
