### ISSUE TITLE
Req Python 3.6 Support

### ISSUE THREAD

**Issue by Murthysagi** [MobSF/Mobile-Security-Framework-MobSF#473]
Hi

This project is not supported on Python 3.6 version, If possible could you please support in feature?

Thanks 
Murthysagi.

**Comment by ajinabraham** [comment]
No plans to move to Python 3.6 in the near feature as most tools that MobSF uses are in Python2.7, and that it's a major change.

**Comment by franklinyu** [comment]
Mind elaborating what tools are in Python 2.7? So that we can push them instead.

**Comment by ajinabraham** [comment]
The next release is python 3 compaticble as python 2 is expiring in 27 months. The code is available in python3 branch.

**Comment by Murthysagi** [comment]
Awesome :+1:
