### ISSUE TITLE
"invalid continuation byte" is returned when tried to upload .apk file

### ISSUE THREAD

**Issue by kcchaitanya** [MobSF/Mobile-Security-Framework-MobSF#474]
"Don't Play Around. An Error just popped in!" is returned in the local Host and "'utf8' codec can't decode byte 0xd4 in position 30: invalid continuation byte." is displayed in the console.

STR:
1. Run the Mob SF File
2. Goto "http://127.0.0.1:8000/" on your browser
3. Upload the .apk file
4. Wait for the analysis to complete
5. Notice that the error is displayed on the Dashboard.

CONSOLE OUTPUT:
 [ERROR] Static Analyzer (/Users/krishnachaitanya/Downloads/Mobile-Security-Framework-MobSF-0.9.5.2/StaticAnalyzer/views/android/static_analyzer.py, LINE 212 "return render(request, template, context)"): 'utf8' codec can't decode byte 0xd4 in position 30: invalid continuation byte. You passed in '      644  08-25-17 02:14   ^L\xd4\xc7\xae\xd4\xc7\xe8.xml' (<type 'str'>)
[05/Sep/2017 11:30:00] "GET /StaticAnalyzer/?name=apk_packagename&type=apk&checksum=63a65b459af7fbfea146e6168a09ccc8 HTTP/1.1" 200 4607
[05/Sep/2017 11:37:26] "GET / HTTP/1.1" 200 7692
[INFO] MIME Type: application/octet-stream FILE: package_name.apk

<img width="1280" alt="screen shot 2017-09-05 at 5 15 51 pm" src="https://user-images.githubusercontent.com/16398128/30059791-32daf690-925e-11e7-95dc-a5a7fc83dd2c.png">
<img width="572" alt="screen shot 2017-09-05 at 5 15 59 pm" src="https://user-images.githubusercontent.com/16398128/30059790-32dac36e-925e-11e7-9ab3-7c670d67cc93.png">

**Comment by matandobr** [comment]
Can you upload the file so we can examine him?

**Comment by kcchaitanya** [comment]
Unable to attach the .apk file. You can download the same from
https://apkpure.com/workruit-job-search/com.workruit

**Comment by ajinabraham** [comment]
Are you using latest MobSF? I am able to run a scan, although some features are not available due to  obfuscation.

**Comment by kcchaitanya** [comment]
I've updated my mobSF to the latest version and its working Fine. Thanks for the quick response.
