### ISSUE TITLE
[ Possible BUG or enhancement needed in MOBSF] Certificate and Signing

### ISSUE THREAD

**Issue by superpoussin22** [MobSF/Mobile-Security-Framework-MobSF#476]
Hi,

Just a little question regarding MobSF and apk signature.

you can use an SHA1 certificate to sign the apk but use sha256 for signing the apk .

Mobsf will see that the certificate use SHA1 ans report a bad state which is good regarding the certificate  but don't reflect how files are hashed.

I think mobsf should inspect the MANIFEST.MF file or better ht .SF to have apksigner information

What do you think ?

PS: What will define the signature algorithm used by apksigner is mostly the MinSDK version

**Comment by ramimac** [comment]
@ajinabraham I've run into this false positive as well, and would be interested in putting together a pull request that checks for the conflict, and adds a line to the report recommending manual confirmation. 

Would you be willing to field a pull request if I put on together? Should be relatively straightforward

**Comment by ajinabraham** [comment]
@ramimac PRs are always welcome. The correct fix is to inspect manifest file and extract correct signing information.
