### ISSUE TITLE
Getting error while executing ADB commands

### ISSUE THREAD

**Issue by sanju70** [MobSF/Mobile-Security-Framework-MobSF#479]
I got following error while executing the adb commands, I'm using MobSF Android 4.4.2 x86 VirtualBox VM. Can you please help me with this?

[ERROR] Casting Screen (/root/Mobile-Security-Framework-MobSF-0.9.1/Mobile-Secur                                                                                        ity-Framework-MobSF-0.9.1/DynamicAnalyzer/views.py, LINE 150 "subprocess.call(ar                                                                                        gs)"): [Errno 2] No such file or directory
[19/Sep/2017 14:39:04]"POST /ScreenCast/ HTTP/1.1" 200 19

[INFO] Executing ADB Commands

[INFO] Getting ADB Location

[2017-09-19 14:39:12]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF-0.9.1/Mobi                                                                                        le-Security-Framework-MobSF-0.9.1/DynamicAnalyzer/views.py, LINE 208 "resp=subpr                                                                                        ocess.check_output(args)"): [Errno 2] No such file or directory
[19/Sep/2017 14:39:12]"POST /ExecuteADB/ HTTP/1.1" 200 31

**Comment by ajinabraham** [comment]
Enable 32 bit execution support and give execute permissions to MobSF tools subdirectory

**Comment by sanju70** [comment]
I"ve enabled 32 bit execution support and gave full permission to MobSF but still  getting the same error

**Comment by ajinabraham** [comment]
Also it seems you are using `-0.9.1` Use the latest from the master.
