### ISSUE TITLE
0.9.5.4 os-x dex2jar error classes.jar not exists

### ISSUE THREAD

**Issue by zhao-guo** [MobSF/Mobile-Security-Framework-MobSF#482]
When I use the laterest version on a mac,it appear below:

[ERROR] Converting Dex to JAR (/Users/syswin1/Mobile-Security-Framework-MobSF-0.9.5.4/StaticAnalyzer/views/android/converter.py, LINE 84 "subprocess.call(args)"): [Errno 2] No such file or directory

and it's no problem when it works on a windows,!

And when I see the converter.py ,the file  classes.jar after analysis not exist 。
When and where classes.jar generate？

Thanks！

**Comment by ajinabraham** [comment]
Insufficient Log, hence closing the issue. Follow the reporting guidelines. 
Most prolly Oracle JDK is not installed or it's not set to default.
