### ISSUE TITLE
Signer Certificate - Incorrect Status

### ISSUE THREAD

**Issue by narayan8291** [MobSF/Mobile-Security-Framework-MobSF#484]
## EXPLANATION OF THE ISSUE

I scanned an iOS binary where the signer certificate is signed using MD5RSA algorithm. The certificate status is good whereas when I scanned a different binary which used SHA1RSA algorithm it complained about collision issues. 

MD5 is also vulnerable to hash collisions and needs to be reported.

**Comment by ajinabraham** [comment]
@narayan8291 Can you share the binary for replicating the issue.

**Comment by ajinabraham** [comment]
Closing as 25 days response period is over.
