### ISSUE TITLE
to support Android version 7.0 above

### ISSUE THREAD

**Issue by nanshihui** [MobSF/Mobile-Security-Framework-MobSF#487]
Since more and more Apps can only be installed on Android 7.0 above, do you have a plan to make Mobsf to support rooted Android 7.0?

Thank you very much for your help.

**Comment by ajinabraham** [comment]
It is supported, but you will have to manually configure with xposed and other tools that works with version 7.

**Comment by ajinabraham** [comment]
tracked separately
