### ISSUE TITLE
API and web interface

### ISSUE THREAD

**Issue by superpoussin22** [MobSF/Mobile-Security-Framework-MobSF#490]
Using API is ok , you can upload a file, analyze it, generate a pdf, and delete it

If you don't delete it you can see the scan in the interface but you can't acces the report cause the url is not correct  : url associated to the report will be http//server:port  instead of http//server:port/StaticAnalyzer/?name=app_name&type=app_type&checksum=app_checksum 

@ajinabraham

**Comment by ajinabraham** [comment]
Yeah, Good spot!

**Comment by ajinabraham** [comment]
Fixed in latest master.
