### ISSUE TITLE
The problem of icon and coding

### ISSUE THREAD

**Issue by Raul1718** [MobSF/Mobile-Security-Framework-MobSF#491]
## Brief introduction
Just beginning to study Mobsf，hava two problems can't solove.So I ask for help.

## 1.The app's icon can't display properly
```
When i finish an app scan，the app's icon can't display properly.
There is this icon in the root directory.
When I use Chrome open a new tab to open the icon,has been unable to load out.
```

## 2. Coding Error
```
I want to translate Mobsf into Chinese,I modify android_rules.py'desc to Chinese.
When scanning again,There was an error:

Don't Play Around. An Error just popped in!
None
'utf8' codec can't decode byte 0xb6 in position 0: invalid start byte. 
You passed in '\xb6\xc1\xc8\xa1/\xd0\xde\xb8\xc4/\xc9\xbe\xb3\xfdSD\xbf\xa8\xc4\xda\xc8\xdd' (<type 'str'>)
```

**Comment by ajinabraham** [comment]
1. Please share more info like console log, errors etc.
2. Unicode errors, you need to deal with unicode in Python2 safely.

**Comment by matandobr** [comment]
Could you upload the apk?

**Comment by Raul1718** [comment]
@matandobr yes,can uoload the apk.

**Comment by Raul1718** [comment]
@ajinabraham 
1.for app's icon can't display properly:
don't have any error info.
There was the console log :

[12/Oct/2017 10:46:21] "GET /download/cccbb07b75c7feec89deb4b686b4817b-icon.pn
HTTP/1.1" 200 5

And then don't hava any respond,The browser is always loading,can't load out.so app's icon can't display properly.

**Comment by ajinabraham** [comment]
@Raul1718 In that case can you share the APK?

**Comment by Raul1718** [comment]
@ajinabraham It seems not apk's problem.I had tried a lot of apks,all hava this problem.

**Comment by ajinabraham** [comment]
If you don't see any errors + the same behaviour for all apks, then something is wrong at your end. Please share an apk for which you see the issue so that we can verify this.

**Comment by superpoussin22** [comment]
if it can help: 
 trying to analyze an apk on mac 
the icon is not diplayed 

erros is :  [2017-10-17 19:41:57]
[ERROR] Get icon function (/Users/super22/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/icon_analysis.py, LINE 90 "aapt_output = subprocess.check_output(args)"): Command '['/Users/super22/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/aapt/mac/aapt', 'd', 'badging', u'/Users/super22/Mobile-Security-Framework-MobSF/uploads/d5f7259176f99c8a2fe9e044deb5f047/d5f7259176f99c8a2fe9e044deb5f047.apk']' returned non-zero exit status -6

same issue trying to use last aapt from Android SDK

**Comment by ajinabraham** [comment]
Can you try giving a `chmod -R a+x /Users/super22/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/`

**Comment by Raul1718** [comment]
@ajinabraham 
My problem still exists.
Cut two pictures:
![image](http://wx4.sinaimg.cn/large/006fVPCvly1fkovjs4080j30td09wmxg.jpg)
![image](http://wx2.sinaimg.cn/large/006fVPCvly1fkovk7iv78j30no0dqjrv.jpg)

**Comment by ajinabraham** [comment]
This is actually fetching existing results. Do a Rescan of the APK or try with an APK that is not scanned before.

**Comment by Raul1718** [comment]
@ajinabraham I had tried many apps,Icons can not be displayed as well.I built Mobsf in Windows.

**Comment by matandobr** [comment]
@Raul1718 , Please share the apk so I could investigate it

**Comment by ajinabraham** [comment]
@Raul1718 You can share any APK that caused this problem, we will try to replicate in our environments. So far, all the APKs are working at our end. It looks like the aapt binary has some issues at your end.

**Comment by ajinabraham** [comment]
This should be fixed with recent bug fix related to icon analysis.
