### ISSUE TITLE
icon extration for apk on Mac

### ISSUE THREAD

**Issue by superpoussin22** [MobSF/Mobile-Security-Framework-MobSF#493]
I open a separeted thread 

trying to analyse an apk on mac I get 

aapt(1180,0x7fff9565a340) malloc: *** error for object 0x5000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[ERROR] Get icon function (/Users/super22/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/icon_analysis.py, LINE 90 "aapt_output = subprocess.check_output(args)"): Command '['/Users/super22/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/aapt/mac/aapt', 'd', 'badging', u'/Users/super22/Mobile-Security-Framework-MobSF/uploads/d5f7259176f99c8a2fe9e044deb5f047/d5f7259176f99c8a2fe9e044deb5f047.apk']' returned non-zero exit status -6

I have done the requested : chmod -R a+x /Users/super22/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/

@ajinabraham

**Comment by ajinabraham** [comment]
@superpoussin22 Can you try with a different aapt binary. Everything works fine at my end.
@matandobr Any ideas?

**Comment by matandobr** [comment]
Could you share the apk?

**Comment by ajinabraham** [comment]
Looks like a memory corruption with  aapt.
Anyways closing as 25 days response time is over.
