### ISSUE TITLE
[Enhancement] Integrate Koodous

### ISSUE THREAD

**Issue by superpoussin22** [MobSF/Mobile-Security-Framework-MobSF#494]
Hi,

I think it coudl be fine to integrate koodous using api in Mobsf .

there's a python script for requesting koodous : https://github.com/Koodous/Scripts/blob/master/pykoodous.py

It coudl be done in two ways :  

1st way : mobsf request Koudoos report and integrate it in mobsf report (if apk is knowned from Koudoos) (using sha256 signature of apk or com.xxxx.yyy + other info to fidn the right apk )

2d way : mobsf send apk to koudoos and ask for analysys and report 

Those two ways could be defined in mobsf settings file  (and also the API key :) )

what do you think Ajin ?  : @ajinabraham

**Comment by ajinabraham** [comment]
@superpoussin22  Koodous report looks very similar to MobSF. What do you think will be the advantage of getting Koodous report with MobSF. Do you have in mind, some features or advantages of koodous that will help MobSF users if it's integrated?

**Comment by ajinabraham** [comment]
Closing this as it passed 25 days response time.
