### ISSUE TITLE
iOS Application Security Analysis requires OSX

### ISSUE THREAD

**Issue by sridharjonnalagadda** [MobSF/Mobile-Security-Framework-MobSF#495]
I am running on mini  MAC 10.12.6 using docker but , i am getting this error "iOS Application Security Analysis requires OSX"

**Comment by superpoussin22** [comment]
Do you install  the required softwares on your mac ?

Mac OSX Users must install Command-line tools for MAC OS X   (See documentation )

**Comment by sridharjonnalagadda** [comment]
Yes i have installed Command-line tools for MAC OS X

**Comment by superpoussin22** [comment]
think you can't use docker to analyze ipa : install Mobsf directly on mac , this is what I have done

**Comment by sridharjonnalagadda** [comment]
Thank you you are right !
