### ISSUE TITLE
WebAPI Fuzzing

### ISSUE THREAD

**Issue by saravanapriya1991** [MobSF/Mobile-Security-Framework-MobSF#498]
Hi,

When am trying to access the url Localhost:8000/api/v1/upload , am getting an error as follows.

{"error": "You are unauthorized to make this request."}

Kindly suggest how to proceed with API fuzzing ,  also the steps we have to follow to implement api fuzzing.

**Comment by ajinabraham** [comment]
This is the MobSF REST API: api/v1/upload

To use WebAPI Fuzzer, you need to perform dynamic analysis of an android app that talks to internet. Do not use github issues for queries and questions, use our slack channel. This is strictly for bug reports and feature requests.
