### ISSUE TITLE
no report generating

### ISSUE THREAD

**Issue by maddy45** [MobSF/Mobile-Security-Framework-MobSF#501]
Mobile Security Framework v0.9.5.4 Beta

REST API Key: fd4500b311e3447ab5b62a1bec73be6e754be21472f2e77d8743b28c7b01244d
OS: Linux
Platform: Linux-4.4.0-96-generic-i686-with-Ubuntu-14.04-trusty
Dist: ('Ubuntu', '14.04', 'trusty')

[INFO] Finding JDK Location in Linux/MAC....

[INFO] JDK 1.7 or above is available

****[WARNING] You don't have 32 bit execution support enabled or MobSF shipped ADB binary is not compatible with your OS.
Please set the 'ADB_BINARY' path in settings.py****

[INFO] Checking for Update.

[INFO] No updates available.
System check identified no issues (0 silenced).
November 07, 2017 - 09:43:27
Django version 1.11.5, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

**Comment by maddy45** [comment]
can anyone help me out?

**Comment by maddy45** [comment]
[ERROR] Saving to DB (/home/maddy/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 232 "static_db.save()"): table StaticAnalyzer_staticanalyzerandroid has no column named ICON_HIDDEN

This error shows after scanning the apk file, i have solved the above problem just by adding path to adb_binary line in settings.py to '/usr/bin/X11/adb'.

**Comment by ajinabraham** [comment]
You need to migrate database: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
and for report generation: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#pdf-report-generation

PS: READ THE DOCUMENTATION WIKI CLEARLY BEFORE OPENING BUGS!

**Comment by maddy45** [comment]
pdf_error | "Cannot Generate PDF"
-- | --
err_details | "wkhtmltopdf exited with non-zero code 1. error:\nUnknown long argument --no-outline\n\nName:\n  wkhtmltopdf 0.9.9\n\nSynopsis:\n  wkhtmltopdf [OPTIONS]... <input file> [More input files] <output file>\n  \nDescription:\n  Converts one or more HTML pages into a PDF document, *not* using wkhtmltopdf\n  patched qt.\n\nGeneral Options:\n      --collate                       Collate when printing multiple copies\n      --copies <number>               Number of copies to print into the pdf                                      file (default 1)\n      --extended-help                 Display more extensive help, detailing                                      less common command switches\n  -h, --help                          Display help\n  -O, --orientation <orientation>     Set orientation to Landscape or Portrait\n  -s, --page-size <size>              Set paper size to: A4, Letter, etc.\n      --password <password>           HTTP Authentication password\n  -p, --proxy <proxy>                 Use a proxy\n  -q, --quiet                         Be less verbose\n      --username <username>           HTTP Authentication username\n  -V, --version                       Output version information an exit\nReduced Functionality:\n  This version of wkhtmltopdf has been compiled against a version of QT without\n  the wkhtmltopdf patches. Therefore some features are missing, if you need\n  these features please use the static version.\n\n  Currently the list of features only supported with patch QT includes:\n\n * Printing more then one HTML document into a PDF file.\n * Running without an X11 server.\n * Adding a document outline to the PDF file.\n * Adding headers and footers to the PDF file.\n * Generating a table of contents.\n * Adding links in the generated PDF file.\n * Printing using the screen media-type.\n * Disabling the smart shrink feature of webkit.\n\nContact:\n  If you experience bugs or want to request new features please visit \n  <http://code.google.com/p/wkhtmltopdf/issues/list>, if you have any problems\n  or comments please feel free to contact me: see \n  <http://www.madalgo.au.dk/~jakobt/#about>\n\n"


This is error when i tried to generate report. I have followed steps, can you please help me with this.

**Comment by ajinabraham** [comment]
This can be an issue with wkhtmltopdf in the OS you are using. What OS are you using? You should file a bug here instead: http://code.google.com/p/wkhtmltopdf/issues/list

**Comment by maddy45** [comment]
ubuntu 14.04 lts trusty tahr

**Comment by maddy45** [comment]
wkhtmltopdf has been moved from above link

**Comment by ajinabraham** [comment]
This is their new repo: https://github.com/wkhtmltopdf/wkhtmltopdf/issues
