### ISSUE TITLE
RestApi Pdf download issue

### ISSUE THREAD

**Issue by saravanapriya1991** [MobSF/Mobile-Security-Framework-MobSF#502]
Hi,
Whena am trying to download pdf file of the scan report using curl am getting error as follows.

{"err_details": "global name 'pdfkit' is not defined", "error": "Cannot Generate PDF"}

Kindly suggest the solution for this issue

**Comment by ajinabraham** [comment]
Not enough details. Read the instruction on how to file a bug. Also read documentation on how to enable pdf report generation.

**Comment by saravanapriya1991** [comment]
Hi,
I am working on Rest Api apk file scanning  using MobSF. I am done with scanning an apk file but when am trying to download the scan report in pdf format using  the following curl command

curl -X POST --url http://localhost:8000/api/v1/download_pdf --data "hash=82ab8b2193b3cfb1c737e3a786be363a&scan_type=apk" -H "Authorization:563d64fc5054d3b239ac0419f1d6b2378465f5c80e1778c283eb1e3265bdd7ae"

am getting error as follows.

{"err_details": "global name 'pdfkit' is not defined", "error": "Cannot Generate PDF"}

Kindly suggest the solution for this issue

**Comment by ajinabraham** [comment]
Don't post your Authorization header in public. It's a sensitive information.
Have you installed PDFKit as per the documentation? If not install and make sure PDF generation is working with the web app before testing with REST API Call.


Follow the instruction below on how to report a bug.

```
<!-- ## IMPORTANT -->
<!-- Issues are ONLY for reporting bugs and feature requests. For support, questions, queries and discussions use our slack channel. Slack Channel: https://mobsf.slack.com/ , Get Invitation: https://goo.gl/6cYU5a
-->
## EXPLANATION OF THE ISSUE

<!-- What happens, under which versions, under what conditions, when, and what were you expecting instead. -->

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```
<!--
BEFORE POSTING YOUR ISSUE/BUG
- These comments won't show up when you submit the issue.
- GitHub issues ARE NOT FOR SUPPORT, DISCUSSIONS AND QUESTIONS! 
- If you have questions, use our slack channel. Request invitation here https://goo.gl/6cYU5a.
- Installation problems with regards to requirements.txt or VirtualBox in not considered as a MobSF issue.
- Reproduce issue in the latest master and try to add as much detail as possible.
- If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.
- Once you open a bug, you should also provide additional information if requested. 
- Failure to do so in 25 days will result in closure of the bug without further communication.
-->
```

**Comment by saravanapriya1991** [comment]
Yes , i have installed pdfkit . but still getting the same error

**Comment by ajinabraham** [comment]
Like I said there is not much information here. Share the log file and console logs.

**Comment by ajinabraham** [comment]
Also this is the hash from the example API call `82ab8b2193b3cfb1c737e3a786be363a` You need to give the hash and type of your apk. Not the example one. 

The steps are like
1. Upload the File API call
2. Start scan API call
3. Generate PDFAPI call

**Comment by saravanapriya1991** [comment]
yes, i have used the hash value from my apk file only. But still am getting the same error only.  i have attached the error file with this.
 kindly suggest
![err](https://user-images.githubusercontent.com/24264989/32536920-68b7d7ec-c486-11e7-89aa-c4414bd3069f.png)

**Comment by ajinabraham** [comment]
You are still posting the same thing.
please share the CONSOLE LOG and Log file.
