### ISSUE TITLE
incomplete apk analysis - AndroidManifest.xml issue?

### ISSUE THREAD

**Issue by ThomasHeinrich** [MobSF/Mobile-Security-Framework-MobSF#504]
After analyzing an apk file the AndroidManifest.xml shows only the first line:
   `<?xml version="1.0" encoding="utf-8"?>`
Also the App Information field shows:

>    App Information
>    Package Name **Failed**
>    Main Activity
>    Target SDK Min SDK Max SDK
>    Android Version Name **Failed**
>    Android Version Code **Failed**
> 

By checking the manifest file manually I found following attribute:
      `android:largeHeap="true"`
This attribute I've never seen before and is not really often used. Maybe MobSF cannot handle it.
The other "Failed" attributes are not included in the manifest file.
Here is the complete 2nd line of the manifest file:
   `<manifest android:versionCode="49" android:versionName="3.1 DE" android:largeHeap="true" package="de.xxxxxxx.yyyyyyyy.zzzzzzzzzzzz"
  xmlns:android="http://schemas.android.com/apk/res/android">`

Btw, I'm a fan of your tool - great job!

**Comment by matandobr** [comment]
Thank you for sharing!
Could you share the complete manifest / upload the apk so we could investigate it properly?

**Comment by ThomasHeinrich** [comment]
@matandobr : Thanks for your quick answer. Can I send you the manifest or the apk directly. I dont wanna share it to the public.

**Comment by matandobr** [comment]
Sure.
matandobr@gmail.com

**Comment by matandobr** [comment]
@ThomasHeinrich , I've been waiting for your reply (20.11 - Thomas sent me a decoded manifest which I didn't see any problem in), Waiting for the encoded manifest / the whole apk so we could fix the issue

**Comment by ajinabraham** [comment]
Hey @matandobr @ThomasHeinrich I just added support for manifest extraction with apktool if AXML2 fails. AXMLPrinter2 fails with some manifest files due to some bugs with it. So please do fetch the latest master and do a rescan.
