### ISSUE TITLE
application/binary FILE Isssue

### ISSUE THREAD

**Issue by ABCD35** [MobSF/Mobile-Security-Framework-MobSF#505]
[21/Nov/2017 19:11:13] "GET / HTTP/1.1" 200 7727
[INFO] MIME Type: application/binary FILE: app-nee.apk

[ERROR] File format not Supported!
[21/Nov/2017 19:11:25] "POST /upload/ HTTP/1.1" 500 75

Please check this issue i am facing while uploading the .apk file.

**Comment by ABCD35** [comment]
![error_screenshot_1](https://user-images.githubusercontent.com/12570891/33111642-29b98582-cf75-11e7-9301-7d7367bfe087.jpg)

**Comment by ajinabraham** [comment]
Can you share the APK @ABCD35 
Ideally we don't support the MIME Type:  `application/binary` for Android APK. You can see the supported MIME types here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L106-L110

**Comment by ABCD35** [comment]
It was not working for any apk file i check multiple files. Giving the same error.
[ERROR] File format not Supported!

i have installed this in kali box.

**Comment by ABCD35** [comment]
Also, to check the issue, i have used Android Tammer VM Box and found that it is working fine. I was able to analyze the same file.

**Comment by ajinabraham** [comment]
Probably due to your browser setting APK's mime type as `application/binary`. You can try a different browser in Kali to verify this.

**Comment by ABCD35** [comment]
Thanks!! i will check and update you.

**Comment by ABCD35** [comment]
I have checked this issue with other browser now it is working fine. Thanks for Help.
![error_screenshot_1](https://user-images.githubusercontent.com/12570891/33144358-c40d8bc0-cfe2-11e7-9353-21363916a4d1.jpg)
