### ISSUE TITLE
 Requires OSX: iOS Application Security Analysis requires OSX.

### ISSUE THREAD

**Issue by ABCD35** [MobSF/Mobile-Security-Framework-MobSF#508]
Can we analyze .ipa file with this tool. i have both installation windows and kali linux. Or we must have Mac to run the .ipa file. Please suggest if there are any solution.
![os_screenshot_1](https://user-images.githubusercontent.com/12570891/33144494-4b348540-cfe3-11e7-8f01-b0c0dbed19e5.jpg)

**Comment by ajinabraham** [comment]
As the error says. You need a Mac for ipa

**Comment by ajinabraham** [comment]
For questions and discussions use slack channel. GitHub is strictly for bugs

**Comment by ABCD35** [comment]
Thanks!!
