### ISSUE TITLE
Can not run IOS Ipa file analysis with docker version.

### ISSUE THREAD

**Issue by liujian1983** [MobSF/Mobile-Security-Framework-MobSF#510]
## EXPLANATION OF THE ISSUE
Can not run IOS Ipa file analysis with docker version.

## STEPS TO REPRODUCE THE ISSUE

install Docker and Kitematic on Mac pro with macOS Serria 10.12.6
1. download the docker image and start the image. (can run static analysis with APK file.) 
2. drag the Ipa file to the file area, system show:Requires OSX.iOS Application Security Analysis requires OSX.

Question: I just review the docker image info, it is Ubuntu os. So, mobSF docker version can not run IOS IPA file analysis?(can run IPA file analysis by manually install with command with older version)
```

## CONSOLE OUTPUT

![image](https://user-images.githubusercontent.com/28887241/33364546-e60c46c0-d51f-11e7-9ee4-7fb508c6897a.png)

**Comment by ajinabraham** [comment]
You should be running in Mac as host for IPA analysis. Docker image uses a Linux based environment.

**Comment by liujian1983** [comment]
1. you mean docker image only support APK analysis?
2. if I want to do iPA analysis, Only to setup mobSF on Mac?....OK.


Another question,just want to report: Can not run dymatic analysis, why?

* daemon not running. starting it now at tcp:5037 *
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
[INFO] ADB Started
[INFO] Waiting for 5 seconds...
error: device '192.168.56.101:5555' not found
error: device '192.168.56.101:5555' not found
[INFO] Starting App for Dynamic Analysis
[INFO] Installing APK
error: device '192.168.56.101:5555' not found
adb: error: failed to get feature set: device '192.168.56.101:5555' not found
- waiting for device -

no virtual image installed on Docker image? NEED to config env to run dynamic analysis?

**Comment by ajinabraham** [comment]
Currently for Dynamic Analysis and IPA or APPX analysis, you need to run in Host than the Docker image.

**Comment by liujian1983** [comment]
Thank you. 
if possible, pls provide new Mac docker image for IPA analysis :)
Config on Host have some problems with env setup....:(
