### ISSUE TITLE
ERROR 'NoneType' object does not support item assignment while performing Static Analysis on iOS App

### ISSUE THREAD

**Issue by ygoncalves1999** [MobSF/Mobile-Security-Framework-MobSF#516]
Hi there,

I am Facing an issue while running the MobSF for static analysis of iOS App.

Resources i am using:
MAC OS X version 10.8
VM running in Windows 10 Professional

Here is the log for the error:

[2017-12-05 14:46:50]
[ERROR] Saving to DB (/Users/mac/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db.interaction.py, LINE 125 "BIN_ANAL=bin_dict["bin_res"],"): 'NoneType' object has no atribute '__getitem__'

[2017-12-05 14:46:50]
[ERROR] Rendering to Template (/Users/mac/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/db.interaction.py, LINE 33 " ' bin_anal': bin_dict["bin_red"],"): 'NoneType' object has no atribute '__getitem__'

[ERROR] 'NoneType' object does not support item assignment

Seems to be some issue with python, idk.

Kindly provide a solution for this.
Thank you,
Yolanda, xoxo.

**Comment by ajinabraham** [comment]
@ygoncalves1999  can you share the IPA that caused this issue?

**Comment by ygoncalves1999** [comment]
Actually, I can't. 

Do you think it is a problem related to the app compilation? Is there anything else a can provide?

**Comment by ajinabraham** [comment]
MobSF works with Objective C apps. If it's  written in Swift, it won't  work. We can'testigate further as binary is not available, hence closing the issue.

**Comment by ygoncalves1999** [comment]
How can I check if its written in C or Swift?

**Comment by ajinabraham** [comment]
Try running classdumpz on it and it will fail for a swift binary.

**Comment by ygoncalves1999** [comment]
I installed MobSF in a Macbook and it worked perfectly!!! Thank you!!!

**Comment by ygoncalves1999** [comment]
I think the problem was related with the OS version installed on the Virtual Machine
