### ISSUE TITLE
Icon Analysis / Get icon function  attempting to use adb linux?

### ISSUE THREAD

**Issue by PermaNulled** [MobSF/Mobile-Security-Framework-MobSF#517]
I'm not sure if this is intended but it seems that the when executing the GetIcon function MobSF attempts to call adb instead of aapt which has no "d" or "badging"

[INFO] appt_binary /home/droiduser/Android/Sdk/platform-tools/adb
adb: usage: unknown command d

[2017-12-08 00:51:54]
[ERROR] Get icon function (/home/droiduser/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/icon_analysis.py, LINE 91 "aapt_output = subprocess.check_output(args, env=env)"): Command '['/home/droiduser/Android/Sdk/platform-tools/adb', 'd', 'badging', u'/home/droiduser/Mobile-Security-Framework-MobSF/uploads/90b81cd1c73485bc954cfda4ef169a47/90b81cd1c73485bc954cfda4ef169a47.apk']' returned non-zero exit status 1

This seems to occur due to this line returning the adb binary:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/icon_analysis.py#L47

Instead of the aapt binary:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/icon_analysis.py#L83

I would've made a pull request but I'm not sure if this is a bug or something is wrong with my specific configuration.

**Comment by matandobr** [comment]
It does seems like an issue, thank you for noticing.
We will fix it shortly!

**Comment by ajinabraham** [comment]
Fixed!
