### ISSUE TITLE
Yara is Not incompatible

### ISSUE THREAD

**Issue by nice9uy** [MobSF/Mobile-Security-Framework-MobSF#522]
[ERROR] rules file "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apkid/rules/rules.yarc" is incompatible with this version of YARA
in my case apkid i made become True
what should I do?

Thanks

**Comment by ajinabraham** [comment]
This won't work with normal YARA. You should use rednaga's fork of yara
