### ISSUE TITLE
Don't Play Around. An Error just popped in! Sequence index out of range.

### ISSUE THREAD

**Issue by x0rzer0** [MobSF/Mobile-Security-Framework-MobSF#523]
i got this error when send [this](https://ufile.io/nc80n) apk file.
--

> Don't Play Around. An Error just popped in!
> Sequence index out of range.
> 
> list index out of range

--
Commandline output
--

> [24/Dec/2017 18:14:58] "GET / HTTP/1.1" 200 7727
> [INFO] MIME Type: application/vnd.android.package-archive FILE: 16b280b277ecf84b71052b32cba488c8eb03e659f1b0ce38a46d22ddbdeb96ab.apk
> 
> [INFO] Performing Static Analysis of Android APK
> [24/Dec/2017 18:15:43] "POST /upload/ HTTP/1.1" 200 191
> [INFO] Starting Analysis on : 16b280b277ecf84b71052b32cba488c8eb03e659f1b0ce38a46d22ddbdeb96ab.apk
> [INFO] Generating Hashes
> [INFO] Unzipping
> [INFO] Getting Hardcoded Certificates/Keystores
> [INFO] APK Extracted
> [INFO] Getting Manifest from Binary
> [INFO] AXML -> XML
> [INFO] Parsing AndroidManifest.xml
> [INFO] Fetching icon path
> [INFO] Extracting Manifest Data
> [INFO] Manifest Analysis Started
> [INFO] Static Android Binary Analysis Started
> [INFO] Static Android Resourse Analysis Started
> [INFO] Reading Code Signing Certificate
> [INFO] APKiD Analysis on Dex file
> [ERROR] list index out of range

--

**Comment by matandobr** [comment]
This issue occurred because of the absence of classes.dex file in the apk.
@x0rzer0 - Where did you get this app from?

**Comment by x0rzer0** [comment]
thx to fix.i got this app from [koodous.com](https://koodous.com/apks/16b280b277ecf84b71052b32cba488c8eb03e659f1b0ce38a46d22ddbdeb96ab)

**Comment by ThunderSon** [comment]
Hello. Kindly note that this is not fixed on Static Analysis for APKs which are missing `classes.dex` 
![broken_dex](https://user-images.githubusercontent.com/32433575/49450038-dc929c00-f7e4-11e8-923a-559a486065cb.png)

**Comment by ajinabraham** [comment]
Can you share the APK @ThunderSon ?

**Comment by ThunderSon** [comment]
It's more of a private APK, not able to share it. I'll be working on the classes.dex file and see what I'll discover. Whenever I find the irregularity, I'll let you know.
