### ISSUE TITLE
Static analyzing doesnt complete.

### ISSUE THREAD

**Issue by x0rzer0** [MobSF/Mobile-Security-Framework-MobSF#525]
I sent [this](https://ufile.io/wiohr) apk and mobsf is working stopped.
the analyzing doesnt complete.
--Commandline Output--

> [INFO] MIME Type: application/vnd.android.package-archive FILE: ff2f8d87fe869850cbb9b2ee11c8a0a14bdf835315f08febe18411e327138a92.apk
> 
> [INFO] Performing Static Analysis of Android APK
> [26/Dec/2017 18:47:15] "POST /upload/ HTTP/1.1" 200 191
> [INFO] Starting Analysis on : ff2f8d87fe869850cbb9b2ee11c8a0a14bdf835315f08febe18411e327138a92.apk
> [INFO] Generating Hashes
> [INFO] Unzipping
> [INFO] Getting Hardcoded Certificates/Keystores
> [INFO] APK Extracted
> [INFO] Getting Manifest from Binary
> [INFO] AXML -> XML
> [INFO] Parsing AndroidManifest.xml
> [INFO] Fetching icon path
> [INFO] Extracting Manifest Data
> [INFO] Manifest Analysis Started
> [INFO] Static Android Binary Analysis Started
> [INFO] Static Android Resourse Analysis Started
> [INFO] Reading Code Signing Certificate
> [INFO] APKiD Analysis on Dex file
> [INFO] DEX -> JAR
> [INFO] Using JAR converter - dex2jar
> dex2jar /home/toor/Mobile-Security-Framework-MobSF/uploads/38164afc932a07879a48f7d78cf8ef1e/classes.dex -> /home/toor/Mobile-Security-Framework-MobSF/uploads/38164afc932a07879a48f7d78cf8ef1e/classes.jar
> [INFO] DEX -> SMALI
> [INFO] JAR -> JAVA
> Processing /home/toor/Mobile-Security-Framework-MobSF/uploads/38164afc932a07879a48f7d78cf8ef1e/classes.jar (use silent to silence)
> Processing a.a.a.a.b
> Processing a.a.a.a.c
> Processing a.a.a.a.d
> Processing a.a.a.a.e
> Processing a.a.a.a.g
> Processing a.a.a.a
> Processing a.a.a.b.j
> Processing a.a.a.b.f
> Processing a.a.a.b.a
> Processing a.a.a.b.b
> //And then working stop...Anayzing doesnt complete.

**Comment by ajinabraham** [comment]
MobSF supports multiple JAR to JAVA decompilers. Use a different one in settings.py and do a scan.

**Comment by x0rzer0** [comment]
It's worked perfectly for me.Thx too much!!
