### ISSUE TITLE
Getting error while generating the Dynamic Analysis Report 

### ISSUE THREAD

**Issue by rohitanga** [MobSF/Mobile-Security-Framework-MobSF#528]
Hi ,
I am getting below error while generating Dynamic analysis report:
Don't Play Around. An Error just popped in!

[INFO] Downloading Logcat logs
adb: error: remote object '/data/data/de.robv.android.xposed.installer/log/error.log' does not exist

[INFO] Downloading Droidmon API Monitor Logcat logs

[INFO] Downloading Dumpsys logs

[INFO] Stopping Application

[INFO] Stopping ScreenCast Service
[09/Jan/2018 14:18:06] "POST /FinalTest/ HTTP/1.1" 200 16

[INFO] Downloading Application Data from Device

[INFO] Stopping any running instance of WebProxy

[INFO] Deleting Dump Status File

[INFO] Saving Captured Web Proxy Data

[INFO] Saving URLS
rm failed for /sdcard/mobsec_status, No such file or directory

[INFO] Creating TAR of Application Files.
/system/bin/sh: /data/local/tmp/tar.sh: not found

[INFO] Waiting for TAR dump to complete...

[INFO] Saving WebTraffic

[INFO] Saving Request Objects

[INFO] Stopped WebProxy and Data Saved

[ERROR] TAR Generation Failed. Process timed out.

[INFO] Dumping Application Files from Device/VM
adb: error: remote object '/data/local/com.androwarn.sampleapplication.tar' does not exist

[INFO] Stopping MobSF Emulator

[INFO] Stopping ADB
[09/Jan/2018 14:19:47] "POST /DumpData/ HTTP/1.1" 200 15

[INFO] Dynamic Analysis Report Generation

[INFO] Dynamic API Analysis

[2018-01-09 14:19:47]
[ERROR] Dynamic API Analysis (D:\Tools\Mobile-Security-Framework-MobSF-master\Dy
namicAnalyzer\views\android\android_dynamic.py, LINE 964 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: u'D:\Tools\Mobile-Security-Framework-MobSF-master\uploads/bebecf3d5f13f41affb5ab9da8f7e391/x_logcat.txt'

[INFO] Dynamic File Analysis

[2018-01-09 14:19:47]
[ERROR] Dynamic Analysis Report Generation (D:\Tools\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\android_dynamic.py, LINE 830 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file ordirectory: u'D:\Tools\Mobile-Security-Framework-MobSF-master\uploads/bebecf3d5f13f41affb5ab9da8f7e391/x_logcat.txt'
[09/Jan/2018 14:19:47] "GET /Report/?md5=bebecf3d5f13f41affb5ab9da8f7e391&pkg=co
m.androwarn.sampleapplication HTTP/1.1" 302 0
[09/Jan/2018 14:19:47] "GET /error/ HTTP/1.1" 200 4661

I see that x_logcat file isn't getting created in uploads folder , I tried with other apks too but no luck . I am using Mobsf Emulator.

**Comment by ajinabraham** [comment]
@rohitanga x86 VM or emulator?

**Comment by rohitanga** [comment]
I am using android emulator.

**Comment by ajinabraham** [comment]
@matandobr ^

**Comment by matandobr** [comment]
@rohitanga 
Which version of android studio are you using?
Was it your first try using the avd emulator (was it ever working properly for you)?

**Comment by rohitanga** [comment]
I am using using android studio 2.3.2.
Yes  avd emulator was my first try , sadly it never worked properly for me .

**Comment by HILALUDEEN** [comment]
Hi,
i am getting this error when running dynamic analyzer,
using ubuntu OS

[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF Emulator

[INFO] Stopping MobSF Emulator

[INFO] Deleting emulator files

[INFO] Duplicating MobSF Emulator

[2018-04-11 11:27:17]
[ERROR] Duplicating MobSF Emulator (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/avd.py, LINE 56 "shutil.copyfile(reference_ini, dup_ini)"): [Errno 2] No such file or directory: '/home/hilaal/.android/avd/Nexus5API16.ini'

[INFO] Starting MobSF Emulator

[2018-04-11 11:27:17]
[ERROR] Starting MobSF Emulator (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/avd.py, LINE 96 "subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)"): [Errno 2] No such file or directory: '/home/hilaal/Android/Sdk/emulator/emulator': '/home/hilaal/Android/Sdk/emulator/emulator'

**Comment by ajinabraham** [comment]
We have some issue with Emulator on some android sdk and studio versions. So use x86 VM or Real Device at the moment.

**Comment by HILALUDEEN** [comment]
Thanks...!!

**Comment by HILALUDEEN** [comment]
Real device will it work above 5 Android Version

**Comment by ajinabraham** [comment]
It should. You can use MobSFy script to configure the environment.

**Comment by abhigyan17** [comment]
[ERROR] 29/Jul/2019 04:19:02 - Dynamic Analysis Report Generation
Traceback (most recent call last):
  File "/root/Downloads/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/dynamic.py", line 713, in report
    analysis_result = run_analysis(app_dir, md5_hash, package)
  File "/root/Downloads/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/analysis.py", line 170, in run_analysis
    with io.open(xlogcat, mode='r', encoding='utf8', errors='ignore') as flip:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Downloads/Mobile-Security-Framework-MobSF-master/uploads/74d618926473fcf2c74f1212c8cc2720/x_logcat.txt'
[ERROR] 29/Jul/2019 04:19:02 - Error Geneating Dynamic Analysis Report
[ERROR] 29/Jul/2019 04:19:02 - Internal Server Error: /Report/

Using NOX player virtual device

**Comment by RanushMithila** [comment]
Can I use NOX player for Dynamic Scan in MOBSF

**Comment by KuHarry** [comment]
Can I use NOX player for Dynamic Scan in MOBSF

**Comment by abhigyan17** [comment]
Yes, you can, but need to config nox player with mobsf...
