### ISSUE TITLE
UPSTREAM_PROXY variable not used 

### ISSUE THREAD

**Issue by superpoussin22** [MobSF/Mobile-Security-Framework-MobSF#532]
Sounds like  UPSTREAM_PROXY variables are not used for : 

- check update

- malware db update

- virus total analysis

is this intentional ?

cheers

Vince

**Comment by ajinabraham** [comment]
This is not intentional, `UPSTREAM_PROXY` is currently used only with pyWebProxy, which we are going to replace in next major release of MobSF where we are moving to Python3. Do you mind sending PR to include proxy settings for update, malware db and VT?

**Comment by superpoussin22** [comment]
will try :)

**Comment by superpoussin22** [comment]
PR submited
