### ISSUE TITLE
incomplete apk analysis

### ISSUE THREAD

**Issue by mschuermeyer** [MobSF/Mobile-Security-Framework-MobSF#534]
## EXPLANATION OF THE ISSUE

MobSF v0.9.5.4 shows 0 activities, 0 services, 0 receiver and 0 providers. Additionally, PackageName, AndroidVersionName and AndroidVersionCode failed.

## STEPS TO REPRODUCE THE ISSUE

```
1. Download the app (please, search 'Telekom Message+ (RCS)) from GooglePlayStore
2. Start MobSF and look at the results.
```

## CONSOLE OUTPUT

```
During uploading the app file, there is popping up an error like this (an extract from the console, look at the row starting with [ERROR]). 
...
[INFO] AXML -> XML
java.lang.ArrayIndexOutOfBoundsException: 4120
	at android.content.res.StringBlock.getShort(StringBlock.java:231)
	at android.content.res.StringBlock.getString(StringBlock.java:91)
	at android.content.res.AXmlResourceParser.getName(AXmlResourceParser.java:140)
	at test.AXMLPrinter.main(AXMLPrinter.java:56)
[INFO] Parsing AndroidManifest.xml

[2018-01-16 14:11:40]
[ERROR] Pasrsing AndroidManifest.xml (/Users/martin/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 27 "manifest = minidom.parseString(dat)"): no element found: line 1, column 38
[WARNING] Using Fake XML to continue the Analysis
[INFO] Fetching icon path
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
...
```

**Comment by ajinabraham** [comment]
use the latest release. We added apktool as a fallback if AXMLPrinter2 failed!
https://github.com/MobSF/Mobile-Security-Framework-MobSF/releases/tag/v0.9.5.5

**Comment by mschuermeyer** [comment]
Hi,

 

thank you very much for your rappid answer. I can confirm, this issues is fixed, great!
 

Kind regards,
Martin

 
 

Gesendet: Dienstag, 16. Januar 2018 um 18:44 Uhr
Von: "Ajin Abraham" <notifications@github.com>
An: MobSF/Mobile-Security-Framework-MobSF <Mobile-Security-Framework-MobSF@noreply.github.com>
Cc: mschuermeyer <mschuermeyer@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [MobSF/Mobile-Security-Framework-MobSF] incomplete apk analysis (#534)


use the latest release. We added apktool as a fallback if AXMLPrinter2 failed!
https://github.com/MobSF/Mobile-Security-Framework-MobSF/releases/tag/v0.9.5.5
