### ISSUE TITLE
MacOS- "Oracle JDK 1.7 or above is not found!" after installation of JAVA

### ISSUE THREAD

**Issue by alonf1983** [MobSF/Mobile-Security-Framework-MobSF#539]
Hi
i have install to my mac both jdk 9.0.4 and jre 8u161, however when i run mobsf i get:
[INFO] Finding JDK Location in Linux/MAC....
[ERROR] Oracle JDK 1.7 or above is not found!

the result of java -version: Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
please help
thanks

**Comment by ajinabraham** [comment]
If Java is not detected, provide the java path in `settings.py`

**Comment by alonf1983** [comment]
Hi
I updated the settings.py to the lines: # COMMON
    JAVA_DIRECTORY = "/usr/bin/"
    VBOXMANAGE_BINARY = ""

however, I can't run it now:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/alonf/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 1
    \"""
       ^
SyntaxError: unexpected character after line continuation character

**Comment by ajinabraham** [comment]
You caused some syntax error.

**Comment by pkrahul87** [comment]
Hi I faced the same issue in windows and I updated the path as, in place of "C:\Program Files\Java\jdk1.7.0_79\bin" as ""C:/Program Files/Java/jdk1.7.0_79/bin/" and the same worked fine.

I know this thread is for MacOS but this issue lead me to this thread and I got this idea from the last comment from Ajin.

**Comment by eaneatfruit** [comment]
Hello, I am encountering this issue as well. I have added JAVA_DIRECTORY in settings.py, it is still throwing that error. Please advise.

**Comment by ajinabraham** [comment]
Install Oracle JDK 1.7 or above, make it the default one.
And provide path to that installation in `JAVA_DIRECTORY`

**Comment by eaneatfruit** [comment]
I realize I had two installations of the Oracle JDK - is there a way to make one default? When you mean the path do you mean /usr/bin/java or where the JDK files are actually located in /Library/Java/JavaVirtualMachines?

**Comment by eaneatfruit** [comment]
FINALLY.

Setting Java default:
export JAVA_HOME=`/usr/libexec/java_home -v 10`

My error was here:
JAVA_DIRECTORY - I kept setting it to /usr/bin/java instead of what it said in the examples: /usr/bin.

Sorry, ID10T error.
