### ISSUE TITLE
error when scan iPad with Mac 10.12 (Sierra)

### ISSUE THREAD

**Issue by alonf1983** [MobSF/Mobile-Security-Framework-MobSF#540]
Hi
when I try to scan an IPA with my Mac , I have received the below error:

[2018-02-02 11:34:27]
[ERROR] - Cannot perform class dump (/Users/AAA/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py, LINE 208 "class_dump = subprocess.check_output([class_dump_z_bin, bin_path])"): Command '['/Users/AAA/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/AAA/Mobile-Security-Framework-MobSF/uploads/9f05c2632377ea8b0d8f9d8a53755c8a/Payload/BBB.app/BBB']' returned non-zero exit status -11

could you help me how to solve it?

I have tried to install class-dump.dmg but it's not fixed it

Thanks for your help

**Comment by ajinabraham** [comment]
Is that IPA a swift binary? It's not supported at the moment as class dumpz can't handle it

**Comment by alonf1983** [comment]
Hi
Any news regards a version for swift?
