### ISSUE TITLE
Permission 'com.google.android.c2dm.permission.RECEIVE ' Unknown

### ISSUE THREAD

**Issue by whoot** [MobSF/Mobile-Security-Framework-MobSF#552]
## EXPLANATION OF THE ISSUE

The permission 'com.google.android.c2dm.permission.RECEIVE' is unknown to MobSF.
When analyzing an android app which includes the named permission, the following text is shown:

<img width="501" alt="unknown" src="https://user-images.githubusercontent.com/8066322/36412787-f708699e-161b-11e8-8fe7-72debde7c137.png">

This permission is needed for setting up a Google Cloud Messaging (GCM) Client App on Android (see https://developers.google.com/cloud-messaging/android/client).

Please add the missing permission(s).

**Comment by ajinabraham** [comment]
Tracked Separately

**Comment by alangonzalez** [comment]
This one tripped me up today... Didn't know it was for this.  Thanks.  It would be nice for the app to be updated to show that.
