### ISSUE TITLE
Error when specific file doesn't exist in upload folder

### ISSUE THREAD

**Issue by Arash-sj** [MobSF/Mobile-Security-Framework-MobSF#553]
mobsf keep checking a file that isn't in upload folder, i want to know how can i prevent checking that file is exist or not?

I know there isn't a fileName.apk in my upload folder, i just want to skip checking this file.
I even run clean.sh to clean all database but when run server there is always this error.

Mobsf version:  v0.9.5.4 Beta

## CONSOLE OUTPUT

[INFO] Starting Analysis on : fileName.apk
[ERROR] [Errno 2] No such file or directory: '/uploads/de60b0f5e9534c692d3cbcb3b2166065/de60b0f5e9534c692d3cbcb3b2166065.apk'
[22/Feb/2018 09:55:15] "GET /StaticAnalyzer/?name=fileName.apk&type=apk&checksum=de60b0f5e9534c692d3cbcb3b2166065 HTTP/1.1" 500 4833

**Comment by ajinabraham** [comment]
This is expected behaviour. If file is not in the uploads directory it cannot proceed with the next steps.

**Comment by Arash-sj** [comment]
so i can never stop this behavior you mean?
is it normal what can i do for it?

**Comment by ajinabraham** [comment]
How are you getting this exception?

**Comment by Arash-sj** [comment]
The problem started when a file extension is changed to something else for example IPA to APK, and there was exception for that so the mobsf has stopped, i deleted the file and the error that has been mentioned above showed in console everytime.

**Comment by ajinabraham** [comment]
The error won't come until unless you tamper a file during the uploading process. You can delete everything from `uploads` and the database file `db.sqlite3` and try again.

**Comment by Arash-sj** [comment]
i even run `clean.sh` but yet this error is killing me!
What should i do?
Thanks for your time.

**Comment by ajinabraham** [comment]
That's what I told. Manually delete the contents of `uploads` and remove the file `db.sqlite3`

**Comment by Arash-sj** [comment]
Unfortunately it didn't help the error is keep showing, i don't know how can it detects that deleted file.
I deleted contents of `uploads` and delete `db.sqlite3` file.

**Comment by ajinabraham** [comment]
Are you using a different config file, did you set `USE_HOME = True` ?

**Comment by Arash-sj** [comment]
no it's `False`, i double checked now.

**Comment by ajinabraham** [comment]
Also Firefox sometimes sent cached request to fill it's Last recent tabs. That can be the issue as well. 
This time try running it on a fresh port.
If that doesn't work, clone a fresh repo and try again.

**Comment by Arash-sj** [comment]
Thx @ajinabraham, you're a life savor.
when changed the port, it didn't show the error anymore.  

Thank you for your time and great support.
