### ISSUE TITLE
False positive in iOS's ATS checker 

### ISSUE THREAD

**Issue by pich4ya** [MobSF/Mobile-Security-Framework-MobSF#560]
Given the following NSAppTransportSecurity configuration,

```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>example.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

According to the Apple document,

```
NSAllowsArbitraryLoads 
If set to YES , disables all ATS restrictions for all network connections, apart from the connections to domains that you configure individually in the optional NSExceptionDomains dictionary. Default value is NO.
```

When the NSAllowsArbitraryLoads configures to YES (True), ATS feature will disable for all domain except for the domain in NSExceptionDomains (in this case example.com) that ATS will be enabled.

[](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33)

However, MobSF reports a totally different thing by saying that the ATS feature is disabled only on example.com.

```
App Transport Security (ATS) is disabled on the domain 'example.com'. Disabling ATS can allow insecure communication with particular servers or allow insecure loads for web views or for media, while maintaining ATS protections elsewhere in your app.
```

**Comment by ajinabraham** [comment]
@DominikSchlecht, Can you look into this?

**Comment by aleenadavy90** [comment]
I am seeing similar issue for App Transport Security, all the subdomains should have ATS enabled by the below config, but MobSF reports error.

```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>somedomain.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
			<key>someotherdomain.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by superpoussin22** [comment]
@magaofei can you take a look ? Thanks

**Comment by magaofei** [comment]
NSAllowsArbitraryLoads can make a uniform setting, but does not affect NSExceptionDomains, NSExceptionDomains has a higher priority. NSAllowsArbitraryLoads defaults to NO and all connections must be HTTPS. If set to YES, the limit can be removed. If NSExceptionDomains is not set, it will be affected by NSAllowsArbitraryLoads. If NSExceptionDomains is set separately, it will not be affected by NSAllowsArbitraryLoads.

**Comment by ajinabraham** [comment]
fixed with new ats analyzer
