### ISSUE TITLE
Some analyses missing when switching to min SDK 21

### ISSUE THREAD

**Issue by iordanis** [MobSF/Mobile-Security-Framework-MobSF#566]
We are using MobSF on an Android app that is quite large (method count >65K). We have multidex switched on and generate more than 1 dex file. (https://developer.android.com/studio/build/multidex.html#about)

Recently we moved to min SDK 21. That adds native support for multi-dex and makes the final APK have a lot more `classN.dex` files. At the same time, our reports started missing details in sections like: Android API, Code Analysis. That points to the fact that perhaps MobSF doesn't scan for all `classN.dex` files. It could also mean that even the previous analyses were missing part of our code.

Switching back to min SDK 19 makes the missing reports re-appear.

To reproduce:
1. Analyse an apk with minSdk<21
2. Confirm Code Analysis exists and points to some issues
3. Raise minSdk to >= 21
4. Notice Code Analysis is missing parts of the step 2. (for our case it doesn't show anything)

Happy to provide more info.

Note: Could be linked to #551

**Comment by ajinabraham** [comment]
Do you mind sharing two APKs one in SDK 19 and SDK <21 with multidex that exhibits this issue. That will help in speeding up things.

**Comment by iordanis** [comment]
I appreciate that, but can't post the Shazam APK :) 

I will try to find a project that does so.

Thanks for your quick response.

**Comment by ajinabraham** [comment]
Never mind, I got what I am looking for :)

**Comment by iordanis** [comment]
In the meantime I've discovered something relevant in case it's ever needed: https://github.com/gradle/perf-android-large

**Comment by ajinabraham** [comment]
@iordanis One quick fix is to use enjarify as the dex to jar converter as mentioned in #551. It will automatically translate multiple dex files.

**Comment by iordanis** [comment]
@ajinabraham Many thanks, I'll try that.

**Comment by ajinabraham** [comment]
Should be fixed in `python3` branch in https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/24a8eab72cceb0a89c344cf769c2fe67e87c2440

**Comment by iordanis** [comment]
Thanks for this and congrats on your project! It's really helpful.
