### ISSUE TITLE
recent_scans - Page not found

### ISSUE THREAD

**Issue by alonf1983** [MobSF/Mobile-Security-Framework-MobSF#568]
Hi
after I upgraded to the new version, I have the following error when I try to access the 'recent scans'

Request Method: | GET
-- | --
http://127.0.0.1:8000/recent_scans/

Using the URLconf defined in MobSF.urls, Django tried these URL patterns, in this order:
^$
^upload/$
^download/
^about$
^api_docs$
^recent_scans$
^delete_scan/$
^search$
^error/$
^not_found/$
^zip_format/$
^mac_only/$
^StaticAnalyzer/$
^StaticAnalyzer_iOS/$
^StaticAnalyzer_Windows/$
^ViewFile/$
^ViewSource/$
^PDF/$
^Smali/$
^Java/$
^Find/$
^ManifestView/$
^DynamicAnalyzer/$
^GetEnv/$
^GetRes/$
^MobSFCA/$
^TakeScreenShot/$
^ClipDump/$
^ExportedActivityTester/$
^ActivityTester/$
^FinalTest/$
^DumpData/$
^ExecuteADB/$
^Report/$
^View/$
^ScreenCast/$
^Touch/$
^capfuzz$
^api/v1/upload$
^api/v1/scan$
^api/v1/delete_scan$
^api/v1/download_pdf$
^api/v1/report_json$
^runtest/$
^runapitest/$
The current path, recent_scans/, didn't match any of these.

**Comment by matandobr** [comment]
Did you upgrade properly?
try to run these commands:
python3 manage.py makemigrations
python3 manage.py migrate

**Comment by ajinabraham** [comment]
It should be http://127.0.0.1:8000/recent_scans not http://127.0.0.1:8000/recent_scans/
