### ISSUE TITLE
Unicode encoding error. UTF-8 issues in Windows (10)

### ISSUE THREAD

**Issue by MartinRJ** [MobSF/Mobile-Security-Framework-MobSF#572]
After installing the latest build today, and upgrading to Python 3 (3.6.4), I get the following message on Windows:

```
Don't Play Around. An Error just popped in!
Unicode encoding error.

'charmap' codec can't encode character '\u0393' in position 234: character maps to <undefined>

```
As a solution I added `, encoding="utf-8"` to the following open() - calls:

**analysis.py**
line 42
line 183

**cert_analysis.py**
line 78

**rpc_client.py**
line 24
line 122
line 172

**settings.py**
line 141

**utils.py**
line 61

**win_fixes.py**
line 19
line 45

**windows.py**
line 239
line 369
line 476

Also for this to work (to not throw above error), in

shared_func.py
line 82: `zipptr.extract(`

I also had to change the following:
C:\Python36\Lib\zipfile.py line 1484:
        `return self._extract_member(member, str(path, encoding="utf-8"), pwd)`
[was: `return self._extract_member(member, path, pwd)` ]

But I still get the error:
[2018-03-26 05:14:57]
[ERROR] Unzipping Error (c:\MobSF\StaticAnalyzer\views\shared_func.py, LINE 82 "zipptr.extract(fileinfo, str(ext_path))"): decoding str is not supported

But with that above change I at least get most results (static analysis) in the browser.

-----

Complete log:

Performing system checks...

  __  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/

Mobile Security Framework v1.0 Beta

REST API Key: *****
OS: Windows
Platform: Windows-10-10.0.16299-SP0

[INFO] Finding JDK Location in Windows....

[INFO] Oracle Java JDK is installed!

[INFO] Checking for Update.

[INFO] No updates available.
System check identified no issues (0 silenced).
March 26, 2018 - 05:11:11
Django version 2.0.3, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] MIME Type: application/vnd.android.package-archive FILE: *****build.apk

[INFO] Performing Static Analysis of Android APK
[26/Mar/2018 05:14:57] "POST /upload/ HTTP/1.1" 200 148
[INFO] Starting Analysis on : *****build.apk
[INFO] Generating Hashes
[INFO] Unzipping

[2018-03-26 05:14:57]
[ERROR] Unzipping Error (c:\MobSF\StaticAnalyzer\views\shared_func.py, LINE 82 "zipptr.extract(fileinfo, str(ext_path))"): decoding str is not supported

[INFO] Not yet Implemented.
[INFO] Getting Hardcoded Certificates/Keystores

[2018-03-26 05:14:57]
[ERROR] Getting Hardcoded Certificates/Keystores (c:\MobSF\StaticAnalyzer\views\android\cert_analysis.py, LINE 23 "for file_name in files:"): 'NoneType' object is not iterable
[INFO] APK Extracted
[INFO] Reading Android Manifest
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - c:\MobSF\uploads/******/java_source/
[INFO] Performing Malware Check on extracted Domains
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Styles Offset given, but styleCount is zero.
Styles Offset given, but styleCount is zero.
Styles Offset given, but styleCount is zero.
Styles Offset given, but styleCount is zero.

[INFO] Connecting to Database

[INFO] Saving to Database

[2018-03-26 05:14:58]
[ERROR] Saving to DB (c:\MobSF\StaticAnalyzer\views\android\db_interaction.py, LINE 236 "static_db.save()"): NOT NULL constraint failed: StaticAnalyzer_staticanalyzerandroid.FILES
[26/Mar/2018 05:14:58] "GET /StaticAnalyzer/?name=*****build.apk&type=apk&checksum=***** HTTP/1.1" 200 185190

**Comment by ajinabraham** [comment]
Will look into this.

**Comment by ajinabraham** [comment]
Fixed in latest Master
