### ISSUE TITLE
Can not export PDF

### ISSUE THREAD

**Issue by bitian** [MobSF/Mobile-Security-Framework-MobSF#573]
when I start mobsf,it shows warining:
[WARNING] wkhtmltopdf is not installed/configured properly. PDF Report Generation is disabled
and when I export PDF,it appears this error:
{"pdf_error": "Cannot Generate PDF", "err_details": "global name 'pdfkit' is not defined"}

can you help me?

**Comment by ajinabraham** [comment]
Read Documentation: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#pdf-report-generation
