### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Teicu** [MobSF/Mobile-Security-Framework-MobSF#574]
Hi, I'm runing Kali Linux 

_pip install -r requirements.txt --user
Collecting git+https://github.com/MobSF/CapFuzz.git (from -r requirements.txt (line 7))
  Cloning https://github.com/MobSF/CapFuzz.git to /tmp/pip-req-build-YsIdr2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-YsIdr2/setup.py", line 16, in <module>
        "capfuzz", "capfuzz.*", "capfuzz.core", "capfuzz.fuzzer", "capfuzz.web",
    TypeError: find_packages() got an unexpected keyword argument 'include'_

**Comment by ajinabraham** [comment]
Update pip, use python 3.5 and above

**Comment by Teicu** [comment]
Hi Ajin 

already installed python 3.5 and I updated the pip, but I got still the same error :(

**Comment by ajinabraham** [comment]
This happens when you are using pip from python 2.
Try 
`python3 -m pip -r requirements.txt`
or 
`pip3 install -r requirements.txt`
