### ISSUE TITLE
Unable to connect to the VM Virtual box with Dynamic Analyse option 

### ISSUE THREAD

**Issue by Aznariy** [MobSF/Mobile-Security-Framework-MobSF#575]
Python version - 3.6.4
Python installation path - C:\Users\john.doe\AppData\Local\Programs\Python\Python36
Java version - 10 (2018-03-20)
Java installation path - C:\Program Files\Java\jdk-10
Virtual Box version - 5.2.8 r 121009 (Qt5,6,2)
Virtual Box installation folder - C:\Program Files\Oracle\VirtualBox
wkhtmltopdf installation folder - C:\Program Files\wkhtmltopdf
   
## EXPLANATION OF THE ISSUE

I'm trying to run a dynamic analysis for the .apk file on my local drive C:\john.doe\InstalledSoftware\MobSF\SampleProjects\MySampleProject.apk. I've gone through the entire documentation tutorial over here _https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation_ and successfully set up **Configuring Dynamic Analyzer with MobSF Android 4.4.2 x86 VirtualBox VM** without any problems. Once I havigated to the 127.0.0.1:8000 and uploaded my .apk file, I was able to see static analysis results. Clicking on the **Start Dynamic Analysis** button rerouted me to the _http://127.0.0.1:8000/DynamicAnalyzer/_ where I clicked on **Create Environment** button. After that I can see that the emulator boots successfully and home page of it becomes visible. While waiting for the next stage of the page, red error message appears at the top right corner of the entire wep page with contents: **Cannot Connect to the VM/Device. ('ERROR Connecting to VM/Device. ', 'unable to connect to 192.168.56.101:1337: cannot connect to 192.168.56.101:1337: No connection could be made because the target machine actively refused it. (10061)\r')**. While looking at the console I noticed another interesting sentences: 
_____________________________________________________________________________________________

Traceback (most recent call last):                                                                                      
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 659, in _build_master                                                                                              
    ws.require(__requires__)                                                                                            
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 967, in require                                                                                                    
    needed = self.resolve(parse_requirements(requirements))                                                             
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 858, in resolve                                                                                                    
    raise VersionConflict(dist, req).with_context(dependent_req)                                                        
pkg_resources.ContextualVersionConflict: (cryptography 2.2.1 (c:\users\john.doe\appdata\local\programs\python\p
ython36\lib\site-packages), Requirement.parse('cryptography<2.2,>=2.1.4'), {'mitmproxy'})                               
                                                                                                                        
During handling of the above exception, another exception occurred:                                                     
                                                                                                                        
Traceback (most recent call last):                                                                                      
  File "C:\Users\john.doe\AppData\Local\Programs\Python\Python36\Scripts\capfuzz-script.py", line 6, in <module
>                                                                                                                       
    from pkg_resources import load_entry_point                                                                          
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 3017, in <module>                                                                                                  
    @_call_aside                                                                                                        
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 3003, in _call_aside                                                                                               
    f(*args, **kwargs)                                                                                                  
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 3030, in _initialize_master_working_set                                                                            
    working_set = WorkingSet._build_master()                                                                            
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 661, in _build_master                                                                                              
    return cls._build_from_requirements(__requires__)                                                                   
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 674, in _build_from_requirements                                                                                   
    dists = ws.resolve(reqs, Environment())                                                                             
  File "c:\users\john.doe\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", 
line 853, in resolve                                                                                                    
    raise DistributionNotFound(req, requirers)                                                                          
pkg_resources.DistributionNotFound: The 'cryptography<2.2,>=2.1.4' distribution was not found and is required by mitmpro
xy      

______________________________________________________________________________________________________                                                                                                                   

## STEPS TO REPRODUCE THE ISSUE

Steps are provided above

## CONSOLE OUTPUT

Console Output is provided above

## CONTENTS OF LOG FILES

[2018-03-27 15:27:26]
[ERROR] Unzipping Error (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\shared_func.py, LINE 82 "zipptr.extract(fileinfo, str(ext_path))"): [Errno 2] No such file or directory: 'C:\\john.doe\\InstalledSoftware\\MobSF\\MobSF_Git\\Mobile-Security-Framework-MobSF\\uploads\\52c50ae824e329ba8b5b7a0f523efffe\\app\\build\\intermediates\\exploded-aar\\com.android.support\\appcompat-v7\\21.0.3\\res\\color\\abc_background_cache_hint_selector_material_dark.xml'
[2018-03-27 15:27:27]
[ERROR] Getting Hardcoded Certificates/Keystores (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\cert_analysis.py, LINE 23 "for file_name in files:"): 'NoneType' object is not iterable
[2018-03-27 15:27:27]
[ERROR] This ZIP Format is not supported
[2018-03-27 15:28:32]
[ERROR] Malware DB Update (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views.py, LINE 102 "if sha256(tmp_dwd.name) != sha256(mal_db):"): [Errno 13] Permission denied: 'C:\\Users\\john~1.RAM\\AppData\\Local\\Temp\\1\\tmp1lbcqqwr'
[2018-03-27 15:28:34]
[ERROR] [WinError 2] The system cannot find the file specified
[2018-03-27 15:28:37]
[ERROR] local variable 'context' referenced before assignment
[2018-03-27 15:30:38]
[ERROR] Unzipping Error (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\shared_func.py, LINE 82 "zipptr.extract(fileinfo, str(ext_path))"): [Errno 2] No such file or directory: 'C:\\john.doe\\InstalledSoftware\\MobSF\\MobSF_Git\\Mobile-Security-Framework-MobSF\\uploads\\52c50ae824e329ba8b5b7a0f523efffe\\app\\build\\intermediates\\exploded-aar\\com.android.support\\appcompat-v7\\21.0.3\\res\\color\\abc_background_cache_hint_selector_material_dark.xml'
[2018-03-27 15:30:38]
[ERROR] Getting Hardcoded Certificates/Keystores (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\cert_analysis.py, LINE 23 "for file_name in files:"): 'NoneType' object is not iterable
[2018-03-27 15:30:38]
[ERROR] This ZIP Format is not supported
[2018-03-27 15:31:40]
[ERROR] Malware DB Update (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views.py, LINE 102 "if sha256(tmp_dwd.name) != sha256(mal_db):"): [Errno 13] Permission denied: 'C:\\Users\\john~1.RAM\\AppData\\Local\\Temp\\1\\tmpuspzmn7f'
[2018-03-27 15:31:42]
[ERROR] [WinError 2] The system cannot find the file specified
[2018-03-27 15:31:44]
[ERROR] local variable 'context' referenced before assignment
[2018-03-27 15:38:58]
[ERROR] Unzipping Error (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\shared_func.py, LINE 82 "zipptr.extract(fileinfo, str(ext_path))"): [Errno 2] No such file or directory: 'C:\\john.doe\\InstalledSoftware\\MobSF\\MobSF_Git\\Mobile-Security-Framework-MobSF\\uploads\\52c50ae824e329ba8b5b7a0f523efffe\\app\\build\\intermediates\\exploded-aar\\com.android.support\\appcompat-v7\\21.0.3\\res\\color\\abc_background_cache_hint_selector_material_dark.xml'
[2018-03-27 15:38:58]
[ERROR] Getting Hardcoded Certificates/Keystores (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\cert_analysis.py, LINE 23 "for file_name in files:"): 'NoneType' object is not iterable
[2018-03-27 15:38:58]
[ERROR] This ZIP Format is not supported
[2018-03-27 15:40:01]
[ERROR] Malware DB Update (C:\john.doe\InstalledSoftware\MobSF\MobSF_Git\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views.py, LINE 102 "if sha256(tmp_dwd.name) != sha256(mal_db):"): [Errno 13] Permission denied: 'C:\\Users\\john~1.RAM\\AppData\\Local\\Temp\\1\\tmpkby245as'
[2018-03-27 15:40:03]
[ERROR] [WinError 2] The system cannot find the file specified
[2018-03-27 15:40:05]
[ERROR] local variable 'context' referenced before assignment

Please advise once the issue gets resolved.

**Comment by ajinabraham** [comment]
I can see couple of issues here.

Your system doesn't allow mobsf to create temp files. Either give the permission or Run cmd.exe as administrator and then run MobSF from there. 

You need to install cryptography module, which is missing .
Try
```
python3 -m pip install cryptography
python3 -m pip install mitmproxy==3.0.2
```

See on what IP your VM is running. Make sure it's correct. Looks like you modified ADB port in settings.py *unable to connect to 192.168.56.101:1337* It shouldn't be port 1337 but 5000. Revert any unnecessary modifications. https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/4a2c06a739ffa49424c2b518a246057174acbc30/MobSF/settings.py#L368

**Comment by Aznariy** [comment]
Sure thing, thanks for the response. Couple questions here:

1.  Where MobSF is supposed to create those temp files? If I would know the folder, I might be seeking for a solution to allow MobSF to create temp files there.

2. Where should I install the cryptography module? In Python installation folder or MobSF installation folder? (Sorry, I'm from .NET shop, never had experience with Python language)

Thanks for the support.

**Comment by ajinabraham** [comment]
1. There is couple of place like these. see the error log: `Permission denied: 'C:\Users\john1.RAM\AppData\Local\Temp\`
2. It's a python library that needs to be installed as MobSF depends on that. From the logs you have provided, it looks like python3 is your default python and available as `python`.
3. In your case python3 is available as `python`
4. `python -m pip install -r requirements.txt` should solve your problems.
