### ISSUE TITLE
Unable to connect to proxy from OVA

### ISSUE THREAD

**Issue by t3hbb** [MobSF/Mobile-Security-Framework-MobSF#584]
## EXPLANATION OF THE ISSUE

During dynamic analysis using MobSF_VM_0.3.ova, the proxy starts on the host computer on port 1337 but I still get an net::ERR_PROXY_CONNECTION_FAILED

Host to VM ping works fine, VM to host ping works fine, VM to internet ping works fine. Port 1337 is shown to be listening on 0.0.0.0:1337 on host

Disabling the proxy in the wireless network settings allows internet connectivity.

## STEPS TO REPRODUCE THE ISSUE

1. Start dynamic analysis
2. Attempt to reach a website

My Configuration : 

Windows 10
VirtualBox Host-Only IP : 192.168.56.1
VM IP : 192.168.56.101
proxy in VM: 192.168.56.1, port 1337

settings.py:
VM/Device IP

VM_IP='192.168.56.101'
PROXY SETTINGS

PROXY_IP='192.168.56.1' #Host/Server/Proxy IP
PORT='1337' #Proxy Port

## CONSOLE OUTPUT

Performing system checks...

  __  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/

Mobile Security Framework v1.0 Beta

REST API Key: 772d518ab94ed4ae6b460e93289123373271f1e18359e3bc3b2bb4d12caf1573
OS: Windows
Platform: Windows-10-10.0.16299-SP0

[INFO] Finding JDK Location in Windows....

[INFO] Oracle Java JDK is installed!

[INFO] Checking for Update.

[INFO] No updates available.
System check identified no issues (0 silenced).
April 06, 2018 - 13:12:46
Django version 2.0.3, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[06/Apr/2018 13:12:56] "GET /recent_scans HTTP/1.1" 200 8052
[INFO] Starting Analysis on : test-aligned-debugSigned.apk

[INFO] Analysis is already Done. Fetching data from the DB...
[06/Apr/2018 13:12:59] "GET /StaticAnalyzer/?name=test-aligned-debugSigned.apk&type=apk&checksum=04c53a4480ada4710c7e951bd810b540 HTTP/1.1" 200 403964
[06/Apr/2018 13:12:59] "GET /download/04c53a4480ada4710c7e951bd810b540-icon.png HTTP/1.1" 200 11381

[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF VM
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Closed
Restoring snapshot 'SAVEDSTATE' (db317bef-cbde-42f6-a964-c38847f97228)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
Waiting for VM "7e4506b0-c97b-4789-8e3b-824192d2e0a5" to power on...
VM "7e4506b0-c97b-4789-8e3b-824192d2e0a5" has been successfully started.

[INFO] VM Starting
[06/Apr/2018 13:13:17] "POST /DynamicAnalyzer/ HTTP/1.1" 200 32467
[06/Apr/2018 13:13:17] "GET /download/screen/screen.png HTTP/1.1" 302 0
[06/Apr/2018 13:13:17] "GET /error/ HTTP/1.1" 200 4749

[INFO] Setting up Dynamic Analysis Environment

[INFO] Connecting to VM/Device
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Capture Module Loaded
Proxy server listening at http://*:1337

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device

[INFO] Mounting

[INFO] Starting App for Dynamic Analysis

## CONTENTS OF LOG FILES

The only error in the logs currently is 
[2018-04-06 12:58:28]
[ERROR] Malware DB Update (C:\Users\xxx\MobSF\MalwareAnalyzer\views.py, LINE 102 "if sha256(tmp_dwd.name) != sha256(mal_db):"): [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpqe31bzv7'

**Comment by ajinabraham** [comment]
Can you try configuring 192.168.56.1 and 1337 as your browser proxy and try visiting an HTTP website just to confirm that the proxy is working.

**Comment by t3hbb** [comment]
Proxy does work when configuring Firefox to connect through it.

Many thanks

**Comment by ajinabraham** [comment]
I just checked in Windows 10 and it works fine.
Have you tried navigating to some site using the browser in the android VM?
Is the error you saw is with an Android App? (It can happen that the app is cert pinned and it won't connect through the MiTM Proxy)

**Comment by t3hbb** [comment]
The actual error "net::ERR_PROXY_CONNECTION_FAILED" happens from the virtualised browser when attempting to reach any site (http or https).

I'm going to try and use the same setup on a different machine so I can eliminate some weird installation/ova importation glitch. 

If there are any other logs or anything that may help in the meantime, please let me know and I'll get them back to you as soon as possible.

**Comment by t3hbb** [comment]
Installed on 3 different machines - no issues.

I still have the non-working set-up if there is something that you would like to trouble shoot - otherwise please feel free to close this issue.

**Comment by ajinabraham** [comment]
It is a straightforward process, setting an HTTPs proxy to the x86 VM. I am guessing the issue is because their might be issues with VirtualBox Network settings. That is pretty much out of the project scope. So I am closing this.
