### ISSUE TITLE
MobSF not finding Directory Traversal and Hard Coded credentials issues in Intentionally Vulnerable Mobile Application 

### ISSUE THREAD

**Issue by Simon-Davies** [MobSF/Mobile-Security-Framework-MobSF#587]
## EXPLANATION OF THE ISSUE

Under the latest development build git cloned today on 09/04/2018 MobSF is not finding Directory Traversal and Hard Coded credentials issues in an intentionally vulnerable Mobile Application when performing Static Analysis.

I was expecting MobSF to find the issues.

**Comment by ajinabraham** [comment]
We can't cover things that cannot be detected using generic regex or string match.
