### ISSUE TITLE
apktool "--match-original" missing

### ISSUE THREAD

**Issue by trgava** [MobSF/Mobile-Security-Framework-MobSF#588]
Without this option the created manifest xml won't show Android Version Name, Version code and so on.

Setting "--match-original" (manifest_analysis.py) fixed the problem: 

`args = [settings.JAVA_PATH + 'java', '-jar', apktool_path, "--match-original", "-f", "-s", "d", app_path, "-o", output_dir]`

**Comment by superpoussin22** [comment]
good catch will do the PR

**Comment by superpoussin22** [comment]
PR done so closing  - Thanks again
