### ISSUE TITLE
Dynamic analysis stuck with ARM Emulator showing "Proxy server listening at http://*:1337"

### ISSUE THREAD

**Issue by tomamuns** [MobSF/Mobile-Security-Framework-MobSF#594]
Hi, 
This is really awesome tool so far i have used. hats off to you guyz.
I have successfully tested with VM. :) Though i have some issue with ARM emulator as it gets stuck with "Proxy server listening at http://*:1337".

![dynamic analysis stuck with arm emulator bat](https://user-images.githubusercontent.com/5146806/38735612-0d5e280c-3f4b-11e8-973e-d6d89930d44c.png)

**Comment by ajinabraham** [comment]
From V1 onwards we are reimplementing the ARM emulator support. It may not work well as the proxy root CA is not installed to the emulator. I am afraid it's not possible to install as well as /system is readonly. Correct me if I am wrong @matandobr.
Alternatively you can wait for some time when we update the instructions and support for ARM emulator for Android 5+ versions.

**Comment by tomamuns** [comment]
Thank you very much. Definitely will wait for that... :)

**Comment by matandobr** [comment]
Hey @tomamuns,
As Ajin said, you may install the new ca on your own, 
although I highly recommend you wait a little longer for the new and stable version of the AVD emulator...
