### ISSUE TITLE
Could not set IP and Port at mobsfy.py

### ISSUE THREAD

**Issue by TrickyMystique** [MobSF/Mobile-Security-Framework-MobSF#597]
Hi I got and error when try to set ip and port on script mobsfy.py that I would like to use my device to do dynamic scan. The error is "[ERROR] Error occured - invalid syntax (<string>, line 1)"
By the way my device is Samsung note4 with Android 6.0.1. Not sure the compatible with environment or not?

**Comment by ajinabraham** [comment]
I don't see any issue as such. Make sure your file is not edited. Use the latest from master and also use python3.

`python mobsfy.py -i 192.168.0.1:5555 -t 1 -v 2` worked fine for me.
