### ISSUE TITLE
import module

### ISSUE THREAD

**Issue by z3r0dung** [MobSF/Mobile-Security-Framework-MobSF#598]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.4/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.4/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 13, in <module>
    from MobSF import utils
  File "/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 20, in <module>
    from . import settings
ImportError: cannot import name 'settings'

why this error happen?

**Comment by superpoussin22** [comment]
how did you launch mobsf ?

**Comment by ajinabraham** [comment]
Run MobSF from its root directory.

**Comment by z3r0dung** [comment]
@ajinabraham yups its from root directory
@superpoussin22 python3 manage.py runserver

**Comment by ajinabraham** [comment]
bytecode caching might be the issue. remove the repo. Do a fresh clone from master repo.
and run from MobSF root directory.

**Comment by nanoymaster** [comment]
same issue, re-downloaded to new directory and error:
cannot import name 'settings'

**Comment by ajinabraham** [comment]
Share the output for 
`pwd`
`which python`

Also install virtualenv
And try

`virtualenv -p python3 venv`
`source venv/bin/activate`
`pip install -r requirements.txt`
`python manage.py runserver` 
And see if it's working fine. You python env have some issues I think.

**Comment by nanoymaster** [comment]
$pwd 
/opt/MobSF_Redownloaded
$which python
/usr/bin/python
$which python3
/usr/bin/python3

$virtualenv -p python3 venv
-bash: virtualenv: command not found

never needed it before... o.O

**Comment by ajinabraham** [comment]
Install virtualenv and try. Your python environment in host have some issues.

**Comment by nanoymaster** [comment]
nope didn't work.

**Comment by ajinabraham** [comment]
Can you share a screenshot of running from venv?

**Comment by nanoymaster** [comment]
ahh sorry, just killed the VM, gonna re-install on a new OS hopefully not need virtualenv.
was just a load of errors running pip install (also tried pip3 install)

there were no errors pip3 installing outside of virtualenv previously

**Comment by aminmaghsodi** [comment]
I have the same issue with MobSF
I use virtualenv and python 3.4.3

**Comment by aminmaghsodi** [comment]
I have the same issue
I use virtualenv and python 3.4.3

**Comment by ajinabraham** [comment]
@aminmaghsodi  Can you share a screenshot of running from venv?

**Comment by aminmaghsodi** [comment]
@ajinabraham I don't know what was the problem, but I founded the problem. The problem was Ubuntu 14.04 . I had changed my OS to Ubuntu 16.04 and my problem solved. Also it works on Ubuntu 18 .  I test it on 2 other systems with Ubuntu 14.04 and it has this problem.

**Comment by tryharder0323** [comment]
Don't Play Around. An Error just popped in!
None

no such table: StaticAnalyzer_staticanalyzeripa

I am on MacOS, this MOBSF kinda crap

**Comment by ajinabraham** [comment]
Follow documentation!
Your DB is not migrated properly

**Comment by aadityao1** [comment]
mine worked when i used python3 manage.py runserver

**Comment by YingYeNaiAi** [comment]
> 伙计们，一切都为我解决了，分析中唯一带有下拉列表的东西给出了这个错误。
> 
> [错误] 2021 年 10 月 25 日 19：38：51 - 执行静态分析回溯时出错（最近一次调用）：文件“C：\Users\ACER\OneDrive\Рабочий стол\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\android\static_analyzer.py”，第 211 行，static_analyzer apkid_results = apkid_analysis（app_dic[ 文件“C：\Users\ACER\OneDrive\Рабочий стол\Mobile-Security-Framework-MobSF\mobsf\MalwareAnalyzer\views\apkid.py”，第 41 行，apkid_分析规则 = options.rules_manager.load（） 文件“C：\Users\ACER\OneDrive\Рабочий стол\Mobile-Security-Framework-MobSF\venv\lib\site-packages\apkid\rules.py”，第 46 行，加载 self.rules = yara.load（self.rules_path） yara。错误：无法打开文件“C：\Users\ACER\OneDrive\Рабочий стол\Mobile-Security-Framework-MobSF\venv\Lib\site-packages\apkid\rules\rules.yarc” [错误] 25/Oct/2021 19：38：51 - 无法打开文件“C：\Users\ACER\OneDrive\Рабочий стол\Mobile-Security-Framework-MobSF\venv\Lib\site-packages\apkid\rules\rules.yarc” [错误] 25/Oct/2021 19：38：51 - 内部服务器错误：/static_analyzer/ 错误：django.request：内部服务器错误：/static_analyzer/

Did you solve it?
