### ISSUE TITLE
Typo in /scripts/mobsfy_AVD.py

### ISSUE THREAD

**Issue by Simon-Davies** [MobSF/Mobile-Security-Framework-MobSF#599]
## EXPLANATION OF THE ISSUE

Executing mobsfy_AVD.py prints output to the terminal. There is a minor spelling mistake in the line:

"[INFO] Make sure to run this script ONLY after you successfully installed leatest Android Studio..."

It should read: " [INFO] Make sure to run this script ONLY after you have successfully installed the latest Android Studio..."

**Comment by superpoussin22** [comment]
good catch , just made a PR to correct this
