### ISSUE TITLE
Add customized android vm for dynamic analysis

### ISSUE THREAD

**Issue by tomamuns** [MobSF/Mobile-Security-Framework-MobSF#603]
Hi, hope your are doing well.
Would appreciate for some suggestions to add customized android vm instead of using existing for dynamic analysis. Is there additional configuration required. Or just replacing the vm will work?

Also, it would be helpful for some reference to build customized test script for dynamic analysis.

Rgds, mamun

**Comment by ajinabraham** [comment]
Read the documentation for Dynamic Analysis. It explains how to add custom VM.
Also @matandobr is working on Android >= 5.0 ARM Emulator support. it will be released soon.
