### ISSUE TITLE
Mobsf/settings.py

### ISSUE THREAD

**Issue by Gam-7** [MobSF/Mobile-Security-Framework-MobSF#605]
please somebody tell me where this is settings.py is I am using 
"Go to **MobSF/settings.py** and set the appropriate values as"

 MobSF Android x86 4.4.2 VM (v0.3) ova file

please update the documentation to explain exactly where this is

**Comment by ajinabraham** [comment]
The documentation is correct. 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py
