### ISSUE TITLE
issue getting this program to work on windows

### ISSUE THREAD

**Issue by Gam-7** [MobSF/Mobile-Security-Framework-MobSF#608]
dude

python3 doesnt work so I have to use py which open python 3 
![py](https://user-images.githubusercontent.com/38298059/39260538-bc74a39c-48b1-11e8-9760-e2d2d063b226.png)
then I got this error when running py manage.py runserver
![2](https://user-images.githubusercontent.com/38298059/39260605-e8261ac0-48b1-11e8-857e-ae85deab250e.png)

**Comment by ajinabraham** [comment]
Django is not installed for python3. Github issues are strictly for bug reports. For discussions and support use our Slack channel.
