### ISSUE TITLE
MobSF dynamic assessment error

### ISSUE THREAD

**Issue by Sathishkumarsubramani1** [MobSF/Mobile-Security-Framework-MobSF#611]
## EXPLANATION OF THE ISSUE

I have followed all the steps and finally i am gettign below errror kindly let me know what could be the reason

## STEPS TO REPRODUCE THE ISSUE
![mobsf error](https://user-images.githubusercontent.com/37904007/39312312-ea2ed236-498c-11e8-9c34-5bc9fcfe50ca.png)

**Comment by ajinabraham** [comment]
Is your MobSF android VM running on 192.168.56.101? If so can you ping it from host OS while it is running?

**Comment by Sathishkumarsubramani1** [comment]
MobSF VM should be in closed mode right. Once i click create environment Mobsf VM should open automatically and it has to install APK right. But my case its not happening. One laptop its working fine and we tried with another laptop but its thows this error. We followed the same steps. Its pining but once click create environment VM is automatically getting closed my guess. what could be the reason.

**Comment by ajinabraham** [comment]
This is a configuration issue or your VirtualBox has issues, not a bug.

**Comment by Sathishkumarsubramani1** [comment]
what is the virtual box version is recommended

**Comment by ajinabraham** [comment]
We test on the latest ones.

**Comment by Sathishkumarsubramani1** [comment]
we are also using the latest one https://download.virtualbox.org/virtualbox/5.2.8/VirtualBox-5.2.8-121009-Win.exe

But in my laptop, we are using 5.1.26 which is working. May i try with same version in not working laptop as well? please suggest

**Comment by ajinabraham** [comment]
5.2.8 works fine for us. So we can't really suggest a particular version. Infact anything above 4.8 worked fine. The issues may be with the host system configuration. Once you add MobSF Android VM. Try running it from VirtualBox itself. If it's not running. It might be compatibility issues with VirtualBox in your system. For discussions use Slack channel. GitHub issues us strictly for bug reports
