### ISSUE TITLE
Don't Play Around. An Error just popped in! Inappropriate argument type.  'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by Gam-7** [MobSF/Mobile-Security-Framework-MobSF#612]
So I eventually get this software running only run into yet another error ! this time I got 

![error2](https://user-images.githubusercontent.com/38298059/39334166-7c2fc8b2-49a5-11e8-8d2a-49a56d1c69b6.png)
 so I checked the closed issues I then modified settings.py to point to the jdk directory 
![jdk](https://user-images.githubusercontent.com/38298059/39334189-944d870e-49a5-11e8-970b-92a25abf6ab5.png)
I then reset the server ran the scan again, no luck same error persisted.

![error1](https://user-images.githubusercontent.com/38298059/39334350-2ac9a79e-49a6-11e8-8060-d42cff8ceaf1.png)

Does this thing even work on a windows machine, not a VM an actual windows machine

**Comment by ajinabraham** [comment]
This is not a bug. You have configuration issues. Use slack channel for troubleshooting and support.
