### ISSUE TITLE
ModuleNotFoundError : No module named rsa 

### ISSUE THREAD

**Issue by Dilshandila** [MobSF/Mobile-Security-Framework-MobSF#613]
## EXPLANATION OF THE ISSUE
when running Mobsf, getting ModuleNotFoundError : No module named rsa 

## STEPS TO REPRODUCE THE ISSUE

```
1. Cloned the Mobsf from github
2. Installed requirements.txt (python3 -m pip install -r requirements.txt --user) 
3. Fpython3 manage.py runserver
4. After runninf requirements.txt i got following:

Requirement already satisfied: rsa==3.4.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
```

## CONSOLE OUTPUT

```

ModuleNotFoundError : No module named rsa 

```
Pls. help
![mobsf](https://user-images.githubusercontent.com/38777354/39347538-e7ecd3a4-4a10-11e8-97fc-fca8b3575584.PNG)

**Comment by ajinabraham** [comment]
Install missing modules. Don't post these issues in bug tracker.

**Comment by ajinabraham** [comment]
You have installed RSA to python2 not python3
