### ISSUE TITLE
Android Library Binary Analysis - Found elf built without Stack Protection [False Negative] [bug]

### ISSUE THREAD

**Issue by Simon-Davies** [MobSF/Mobile-Security-Framework-MobSF#621]
## EXPLANATION OF THE ISSUE

MobSF is flagging an Android Library binary as having been built without the -fstack-protector compiler option but when manually verifying this it look like MobSF is giving a False Negative

![image](https://user-images.githubusercontent.com/713455/39536518-bb2088da-4e2e-11e8-94d5-6416d423d45b.png)

See Link: https://security.stackexchange.com/questions/158609/how-is-the-stack-protection-enforced-in-a-binary

See Below Manual Verification:

root@android:/home/si# hardening-check liblastpass.soliblastpass.so:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: no, only unprotected functions found!
 Read-only relocations: yes
 Immediate binding: yes
root@android:/home/si# strings liblastpass.so | grep stack_chk__stack_chk_fail

Duplicate: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/646

**Comment by shuxin** [comment]
#412

**Comment by shuxin** [comment]
@Simon-Davies  Is it a x86 version?

**Comment by vineetj** [comment]
@Simon-Davies  : Is there similar command for mac to check manually the binary (similar to 'hardening-check'). I have tried checksec tool but running file command using it always gives an error 'Not an ELF file'

**Comment by vineetj** [comment]
Yes have done it through binutils only.

**Comment by Simon-Davies** [comment]
There must be a problem with either checksec.sh or binutils on OSX.

**Comment by ajinabraham** [comment]
I guess this is a related issue: @shuxin ?
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/646

**Comment by ajinabraham** [comment]
It's not reliable to do this check. Hence removing it from MobSF

**Comment by idrisbohra** [comment]
Hi, @ajinabraham I am also encountering the same elf error. is this feature removed or still in under removing process?

**Comment by ajinabraham** [comment]
Looks like a regression may be. Reopening this. 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1354 is a possible way to fix this.

**Comment by ajinabraham** [comment]
Rewrite binary analysis with

https://github.com/Wenzel/checksec.py
or https://github.com/lief-project/LIEF

**Comment by ajinabraham** [comment]
Replaced the entire logic with lief. Addressed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1558
