### ISSUE TITLE
MobSF Show Screen problem

### ISSUE THREAD

**Issue by luolin2611** [MobSF/Mobile-Security-Framework-MobSF#627]
Hello, I encountered problems in using MobSF as well as the problems encountered here.
[https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/362](url)
Port 9339 is not occupied, but the image cannot be displayed. Can you help me through TeamViewer?

**Comment by ajinabraham** [comment]
Are you on windows?

**Comment by luolin2611** [comment]
No, I'm using a Mac computer.

**Comment by luolin2611** [comment]
Is it convenient for you to solve it? Thank you!

**Comment by ajinabraham** [comment]
The screencast doesn't work on some systems. It's just an auxiliary feature. You can interact directly with VM.
