### ISSUE TITLE
Problem booting the ova on x86 virtualbox

### ISSUE THREAD

**Issue by mahmoodn** [MobSF/Mobile-Security-Framework-MobSF#629]
I followed the guide on [1] after importing the ova file on a virtualbox x86 windows host. Right after clicking on start, I get

```
Could not start the machine MobSF_VM_0.2 because the following physical network interfaces were not found:

vboxnet0 (adapter 1)

You can either change the machine's network settings or stop the machine.


```

What should I do?

[1] https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation

**Comment by ajinabraham** [comment]
Add VirtualBox network adaptors. This is for bug reports of things under the scope of MobSF.

**Comment by mahmoodn** [comment]
What do you mean? As I check the Preferences->Network->Host-only Networks, I see 
VirtualBox Host-Only Ethernet Adapter # 2 (192.168.56.1)
VirtualBox Host-Only Ethernet Adapter # 3 (192.168.65.1)


For the guest machine, when I open settings->netwrok, the first adapter is set to Host-only Adapter and the name is VirtualBox Host-Only Ethernet Adapter # 2
