### ISSUE TITLE
i got the following error during uploading apk

### ISSUE THREAD

**Issue by dipsubho** [MobSF/Mobile-Security-Framework-MobSF#630]
Don't Play Around. An Error just popped in!

Inappropriate argument type.
'NoneType' object does not support item assignment

In terminal i got this-

[INFO] Performing Static Analysis of Android APK
[08/May/2018 23:24:36] "POST /upload/ HTTP/1.1" 200 136
[INFO] Starting Analysis on : diva-beta.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Converting AXML to XML

[2018-05-08 23:24:39]
[ERROR]Getting Manifest file (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\manifest_analysis.py, LINE 1304 "subprocess.check_output(args)"): [WinError 2] The system cannot find the file specified

[2018-05-08 23:24:39]
[ERROR] Reading Manifest file (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\manifest_analysis.py, LINE 1259 "if isFileExists(manifest):"): stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] Parsing AndroidManifest.xml

[2018-05-08 23:24:39]
[ERROR] apktool failed to extract AndroidManifest.xml or parsing failed (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\manifest_analysis.py, LINE 28 "manifest = minidom.parseString(dat)"): a bytes-like object is required, not 'NoneType'
[WARNING] Using Fake XML to continue the Analysis
[INFO] Fetching icon path
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate

[2018-05-08 23:24:39]
[ERROR] Reading Code Signing Certificate (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\cert_analysis.py, LINE 65 "dat = subprocess.check_output(args)"): [WinError 2] The system cannot find the file specified
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
[INFO] Converting C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\uploads/82ab8b2193b3cfb1c737e3a786be363a\classes.dex to JAR
[INFO] Running JAVA path fix in Windows
'"javajava"' is not recognized as an internal or external command,
operable program or batch file.
[INFO] DEX -> SMALI
[INFO] Converting C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\uploads/82ab8b2193b3cfb1c737e3a786be363a\classes.dex to Smali Code

[2018-05-08 23:24:39]
[ERROR] Converting DEX to SMALI (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\converter.py, LINE 112 "subprocess.call(args)"): [WinError 2] The system cannot find the file specified
[INFO] JAR -> JAVA
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\uploads/82ab8b2193b3cfb1c737e3a786be363a/java_source/
[INFO] Performing Malware Check on extracted Domains
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK

[INFO] Connecting to Database

[INFO] Saving to Database

[2018-05-08 23:24:40]
[ERROR] Saving to DB (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable

[2018-05-08 23:24:40]
[ERROR] Rendering to Template (C:\Users\dipjy\Desktop\APT\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[ERROR] 'NoneType' object does not support item assignment
[08/May/2018 23:24:40] "GET /StaticAnalyzer/?name=diva-beta.apk&type=apk&checksum=82ab8b2193b3cfb1c737e3a786be363a HTTP/1.1" 500 4835

**Comment by ajinabraham** [comment]
Set Java path correctly
`Running JAVA path fix in Windows
'"javajava"' is not recognized as an internal or external command,`

**Comment by dipsubho** [comment]
how to do it?

**Comment by anilksree** [comment]
I am also getting similar kind of error. I setup the Java path correctly. Anyone please help?

Thanks in advance
