### ISSUE TITLE
MobSF stuck while analysing the apk and there is no log file in logs folder.

### ISSUE THREAD

**Issue by babitaadhikari17** [MobSF/Mobile-Security-Framework-MobSF#631]
Environment: macOS High Sierra

Small Sample apps are working fine but if i test the actual apk (size: 37MB) the tool got stuck after  analyzing this package "Processing com.nokia.maps.PlacesReference".
And there is no log file generated in the logs folder.

Can you please help in resolving this issue?

Mobile Security Framework v1.0 Beta

REST API Key: ae57472af3c45a79c5d8305f5e99dac7f4a37afaa8131fa929d3c10402b9f12b
OS: Darwin
Platform: Darwin-17.5.0-x86_64-i386-64bit

[INFO] Finding JDK Location in Linux/MAC....

[INFO] JDK 1.7 or above is available

[INFO] Checking for Update.

[INFO] No updates available.
System check identified no issues (0 silenced).
May 09, 2018 - 07:36:16
Django version 2.0.5, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[09/May/2018 07:36:24] "GET / HTTP/1.1" 200 7723
[INFO] MIME Type: application/vnd.android.package-archive FILE: CobitApp_Maxwell_20180409.apk

[INFO] Performing Static Analysis of Android APK
[09/May/2018 07:36:35] "POST /upload/ HTTP/1.1" 200 152
[INFO] Starting Analysis on : CobitApp_Maxwell_20180409.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Reading Android Manifest
[INFO] Parsing AndroidManifest.xml
[INFO] Fetching icon path
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
[INFO] Converting /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes.dex to JAR
dex2jar /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes.dex -> /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes0.jar
[INFO] Converting /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes2.dex to JAR
dex2jar /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes2.dex -> /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes1.jar
[INFO] Converting /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes3.dex to JAR
dex2jar /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes3.dex -> /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes2.jar
[INFO] DEX -> SMALI
[INFO] Converting /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes.dex to Smali Code
[INFO] Converting /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes2.dex to Smali Code
[INFO] Converting /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes3.dex to Smali Code
[INFO] JAR -> JAVA
[INFO] Decompiling /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes0.jar to Java Code
Processing /Users/babitaadhikari/Mobile-Security-Framework-MobSF/uploads/8052a3c9808ec239f7e4b5f70f9f19b4/classes0.jar (use silent to silence)
Processing android.support.compat.R
Processing android.support.constraint.R
Processing android.support.coreui.R
Processing android.support.coreutils.R
Processing android.support.design.R
Processing android.support.fragment.R
Processing android.support.graphics.drawable.R
Processing android.support.graphics.drawable.animated.R
Processing android.support.mediacompat.R
Processing android.support.transition.R
Processing android.support.v13.R
Processing android.support.v4.R
.
.
.
.
Processing com.nokia.maps.PlacesMediaCollectionPage
Processing com.nokia.maps.PlacesMediaContent
Processing com.nokia.maps.PlacesNavigationPosition
Processing com.nokia.maps.PlacesPlace
Processing com.nokia.maps.PlacesRatings
Processing com.nokia.maps.PlacesReference

**Comment by superpoussin22** [comment]
can you share the apk ?

**Comment by ajinabraham** [comment]
@babitaadhikari17 If the APK is large, the analysis also takes considerable amount of time. You can try  changing the `JAR -> JAVA` decompiler in `settings.py`
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L254

**Comment by babitaadhikari17** [comment]
@superpoussin22 Sorry i cannot share the apk

@ajinabraham ok i'll try this JAR -> JAVA decompiler in settings.py
Yesterday i put the apk for analyzing but it doesn't complete the analyses even after 13hrs.

**Comment by ajinabraham** [comment]
Such issues can happen. That's why we keep multiple decompilers. Try using a different one.

**Comment by babitaadhikari17** [comment]
Thankyou its working now i try with different compiler.
