### ISSUE TITLE
Dynamic Analysis is not working correctly.

### ISSUE THREAD

**Issue by babitaadhikari17** [MobSF/Mobile-Security-Framework-MobSF#632]
Environment: MacOS
Logs: No log file in the logs folder

Start dynamic analysis-> Create environment
Below are the logs display in terminal.

INFO] Setting up Dynamic Analysis Environment
[INFO] Wait for emulator to load
[INFO] Wait for dev.boot_complete loop
Capture Module Loaded
Proxy server listening at http://*:1337

App is not installing in the emulator.
Kindly help with this issue.

**Comment by ajinabraham** [comment]
The emulator is not supported at the moment. We are releasing a new emulator soon.

**Comment by babitaadhikari17** [comment]
When the new emulator will release? @ajinabraham

**Comment by ajinabraham** [comment]
It is being tested across multiple host OS. If everything goes right, it will be out in 2 months.
