### ISSUE TITLE
[Errno 2] No such file or directory: 'capfuzz': 'capfuzz'

### ISSUE THREAD

**Issue by aflima** [MobSF/Mobile-Security-Framework-MobSF#634]
## EXPLANATION OF THE ISSUE

I have a Android Device rooted and alread configured with the mobsfy.py script all ok, and changed the settings.py already.

When I try to start Dynamic Analyzer it gives me the following error:
`[ERROR] Setting up Dynamic Analysis Environment (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 158 "start_proxy(settings.PORT, package)"): [Errno 2] No such file or directory: 'capfuzz': 'capfuzz'`

I have the capfuzz installed in python3 correctly, and I can import it without problems, however when I run the Popen function of the subprocess I get the following error:

```
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> import capfuzz
>>> subprocess.Popen(["capfuzz", "-m", "capture", "-p", "1337", "-n", "foo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'capfuzz': 'capfuzz'
```

I'm using Kali Linux. Do you have any idea what might be causing the error in execution?

Thanks in advance.

## STEPS TO REPRODUCE THE ISSUE

```
1. Run manage.py runserver
2. Try to create environment in Dynamic Analyzer
```

**Comment by ajinabraham** [comment]
Works fine for me 
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.Popen(["capfuzz", "-m", "capture", "-p", "1337", "-n", "foo"])
<subprocess.Popen object at 0x1047b60f0>
>>> Capture Module Loaded
Proxy server listening at http://*:1337
```

**Comment by ajinabraham** [comment]
I suggest you to install capfuzz like
`python3 -m pip install git+https://github.com/MobSF/CapFuzz.git`

**Comment by aflima** [comment]
I don't know if i need to set de $capfuzz with something, but i execute like you show up

 ✘ ⚡ root@kali  /opt/Mobile-Security-Framework-MobSF   master ●  echo $capfuzz

 ⚡ root@kali  /opt/Mobile-Security-Framework-MobSF   master ●  /opt/Mobile-Security-Framework-MobSF/$capfuzz
 ⚡ root@kali  /opt/Mobile-Security-Framework-MobSF   master ●  python3
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> import capfuzz
>>> subprocess.Popen(["capfuzz", "-m", "capture", "-p", "1337", "-n", "foo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'capfuzz': 'capfuzz'
>>> 

Still with error =(

**Comment by ajinabraham** [comment]
Nop, you don't have to add `$`
Just try to run `capfuzz` from MobSF directory just like you run `python3`. If it's installed correctly, you will see the help text.

**Comment by aflima** [comment]
I don't know if it is what you mean, but...
⚡ root@kali  /opt/Mobile-Security-Framework-MobSF   master ●  capfuzz
zsh: command not found: capfuzz
 ✘ ⚡ root@kali  /opt/Mobile-Security-Framework-MobSF   master ●  /opt/Mobile-Security-Framework-MobSF/capfuzz
zsh: no such file or directory: /opt/Mobile-Security-Framework-MobSF/capfuzz
 ✘ ⚡ root@kali  /opt/Mobile-Security-Framework-MobSF   master ●  python3 -m pip install -r requirements.txt --user
Collecting git+https://github.com/MobSF/CapFuzz.git (from -r requirements.txt (line 7))
  Cloning https://github.com/MobSF/CapFuzz.git to /tmp/pip-req-build-2cz2r2h6
Requirement already satisfied (use --upgrade to upgrade): capfuzz==0.0.1 from git+https://github.com/MobSF/CapFuzz.git in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: Django==2.0.5 in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.0.5)
Requirement already satisfied: pdfkit==0.6.1 in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: configparser==3.5.0 in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (3.5.0)
Requirement already satisfied: androguard==3.2.0 in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (3.2.0)
Requirement already satisfied: lxml==4.2.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (4.2.1)
Requirement already satisfied: rsa==3.4.2 in /root/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (3.4.2)
Requirement already satisfied: mitmproxy==3.0.2 in /root/.local/lib/python3.6/site-packages (from capfuzz==0.0.1->-r requirements.txt (line 7)) (3.0.2)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from Django==2.0.5->-r requirements.txt (line 1)) (2018.4)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (0.3.7)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (2.2.2)
Requirement already satisfied: future in /root/.local/lib/python3.6/site-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (0.16.0)
Requirement already satisfied: pygments in /root/.local/lib/python3.6/site-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: networkx>=1.11 in /root/.local/lib/python3.6/site-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (2.1)
Requirement already satisfied: ipython>=5.0.0 in /root/.local/lib/python3.6/site-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (6.3.1)
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from androguard==3.2.0->-r requirements.txt (line 4)) (0.24.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa==3.4.2->-r requirements.txt (line 6)) (0.4.2)
Requirement already satisfied: certifi>=2015.11.20.1 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2018.1.18)
Requirement already satisfied: pyperclip<1.7,>=1.5.22 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: cryptography<2.2,>=2.1.4 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2.1.4)
Requirement already satisfied: ldap3<2.5,>=2.4 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2.4.1)
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (0.8)
Requirement already satisfied: wsproto<0.12.0,>=0.11.0 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: requests<3,>=2.9.1 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2.18.4)
Requirement already satisfied: pyparsing<2.3,>=2.1.3 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2.2.0)
Requirement already satisfied: brotlipy<0.8,>=0.7.0 in /root/.local/lib/python3.6/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (0.7.0)
Requirement already satisfied: click<7,>=6.2 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (6.7)
Requirement already satisfied: hyperframe<6,>=5.1.0 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (5.1.0)
Requirement already satisfied: pyOpenSSL<17.6,>=17.5 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (17.5.0)
Requirement already satisfied: blinker<1.5,>=1.4 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (1.4)
Requirement already satisfied: urwid<2.1,>=2.0.1 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2.0.1)
Requirement already satisfied: h11<0.8,>=0.7.0 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (0.7.0)
Requirement already satisfied: ruamel.yaml<0.16,>=0.13.2 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (0.15.34)
Requirement already satisfied: tornado<4.6,>=4.3 in /root/.local/lib/python3.6/site-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (4.5.3)
Requirement already satisfied: h2<4,>=3.0.1 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (3.0.1)
Requirement already satisfied: sortedcontainers<1.6,>=1.5.4 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (1.5.9)
Requirement already satisfied: passlib<1.8,>=1.6.5 in /usr/lib/python3/dist-packages (from mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (1.7.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from matplotlib->androguard==3.2.0->-r requirements.txt (line 4)) (2.6.1)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib->androguard==3.2.0->-r requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: numpy>=1.7.1 in /usr/lib/python3/dist-packages (from matplotlib->androguard==3.2.0->-r requirements.txt (line 4)) (1.13.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->androguard==3.2.0->-r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from matplotlib->androguard==3.2.0->-r requirements.txt (line 4)) (1.11.0)
Requirement already satisfied: decorator>=4.1.0 in /usr/lib/python3/dist-packages (from networkx>=1.11->androguard==3.2.0->-r requirements.txt (line 4)) (4.1.2)
Requirement already satisfied: jedi>=0.10 in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.15 in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (1.0.15)
Requirement already satisfied: pickleshare in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.7.4)
Requirement already satisfied: setuptools>=18.5 in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (39.1.0)
Requirement already satisfied: simplegeneric>0.8 in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.8.1)
Requirement already satisfied: traitlets>=4.2 in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (4.3.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (4.5.0)
Requirement already satisfied: backcall in /root/.local/lib/python3.6/site-packages (from ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.1.0)
Requirement already satisfied: cffi>=1.0.0 in /root/.local/lib/python3.6/site-packages (from brotlipy<0.8,>=0.7.0->mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (1.11.5)
Requirement already satisfied: parso>=0.2.0 in /root/.local/lib/python3.6/site-packages (from jedi>=0.10->ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: wcwidth in /root/.local/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.1.7)
Requirement already satisfied: ipython-genutils in /root/.local/lib/python3.6/site-packages (from traitlets>=4.2->ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /root/.local/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.0.0->androguard==3.2.0->-r requirements.txt (line 4)) (0.5.2)
Requirement already satisfied: pycparser in /root/.local/lib/python3.6/site-packages (from cffi>=1.0.0->brotlipy<0.8,>=0.7.0->mitmproxy==3.0.2->capfuzz==0.0.1->-r requirements.txt (line 7)) (2.18)
Building wheels for collected packages: capfuzz
  Running setup.py bdist_wheel for capfuzz ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-ygn7gu9x/wheels/b3/28/db/381f394ea2298b954714256e06d524a7bf5f104d8780f8945e
Successfully built capfuzz

**Comment by ajinabraham** [comment]
Have reproduced this issue. I will update the install instruction in Documentation.

Install virtualenv

```
pip3 install virtualenv
virtualenv -p python3 venv
source venv/bin/activate
pip3 install -r requirements.txt
python3 manage.py runserver
```

**Comment by aflima** [comment]
INFO] Setting up Dynamic Analysis Environment

[INFO] Connecting to VM/Device
* server not running *
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Capture Module Loaded
Proxy server listening at http://*:1337

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device

[INFO] Mounting

[INFO] Starting App for Dynamic Analysis

[INFO] Installing APK
[ 79%] /data/local/tmp/9fabd700386259c11d24b5fc0d92d08c.apk


Mannnn that's what i'm talking about :) , tks 👍
