### ISSUE TITLE
i am getting error when i run setup.py

### ISSUE THREAD

**Issue by dipsubho** [MobSF/Mobile-Security-Framework-MobSF#635]
when i run setup.py it showing me 

"found more than 2 exes for binskim, panic"

what to do? how can i install mobsf??? please help me as soon as possible

**Comment by ajinabraham** [comment]
@DominikSchlecht, Could you please look into this?

**Comment by JustKay** [comment]
I'm actually having the same problem.
![binskim-error](https://user-images.githubusercontent.com/1184746/40216497-e63ebfca-5a1b-11e8-9b78-13da1ab208ae.JPG)

**Comment by ajinabraham** [comment]
Can you uninstall all the binskim present on your OS once?

**Comment by JustKay** [comment]
I never had binskim installed on my computer, the first instance I've used is with running the setup.py. I think maybe in the setup.py or in the bundle maybe extra files were left in the build?
![no-binskim](https://user-images.githubusercontent.com/1184746/40265312-e0ce73a8-5aea-11e8-8924-f5b2b5c090aa.JPG)

**Comment by JustKay** [comment]
I'm not saying its a python module, I'm saying it seems like something needed for the MobSF like rsa and nuget.exe. So maybe somewhere in the bundle for MobSF or the setup.py it was duplicated?

**Comment by ajinabraham** [comment]
@JustKay, @DominikSchlecht works on the windows part. The question was for you.

**Comment by kawaxi** [comment]
Im having the same problem....
