### ISSUE TITLE
Dynamic API Analysis fail

### ISSUE THREAD

**Issue by mehrant95** [MobSF/Mobile-Security-Framework-MobSF#636]
## EXPLANATION OF THE ISSUE
After static analysis of the APK, i tried dynamic analysis using MobSF Android 4.4.2 x86 VirtualBox. Everything worked well but when i try to finish the dynamic analysis, it shows the error below:
```
[INFO] Dynamic API Analysis

[2018-05-10 12:40:51]
[ERROR] Parsing JSON Failed for: {"timestamp":1525954568306,"class":"java.lang.reflect.Method","method":"invoke","hooked_method":"findLoadedClass","hooked_class":"dalvik.system.PathClassLoader","type":"reflection","args":["net.iGap.proto.ProtoChannelRemoveUsernaDroidmon-apimonitor-net.iGap:{"timestamp":1525954568320,"class":"java.lang.reflect.Method","method":"invoke","hooked_method":"findLoadedClass","hooked_class":"dalvik.system.PathClassLoader","type":"reflection","args":["net.iGap.fragments.t$12"]}
 (/home/ubuntu/mobsf_test/DynamicAnalyzer/views/android/analysis.py, LINE 52 "apis = json.loads(value, strict=False)"): Expecting ',' delimiter: line 1 column 261 (char 260)

```
I'm using MobSF 1.0 beta, Ubuntu 17.10 and Java Oracle 1.8. 
**Edit:** 
APK can be downloaded from [here](https://apkdl.in/app/details?id=net.iGap)

**Comment by ajinabraham** [comment]
I am yet to check this due to other works. Will check and let you know soon.

**Comment by A-AFTAHI** [comment]
@mehrant95 the link to the machine you provided returns 404 error

**Comment by ajinabraham** [comment]
@mehrant95 I lost the APK, can you re upload it?

**Comment by ajinabraham** [comment]
Closing as reporter is inactive.

**Comment by mehrant95** [comment]
sorry, i updated the download link (basically it's a direct link for downloading [iGap](https://play.google.com/store/apps/details?id=net.iGap) from google play).

**Comment by ajinabraham** [comment]
Thanks for the APK, I will look into this.

**Comment by ajinabraham** [comment]
Couldn't reproduce this issue. Also we are doing a Dynamic Analyzer revamp to support Genymotion.
