### ISSUE TITLE
Static analysis using MobSF giving error

### ISSUE THREAD

**Issue by khushbukothari** [MobSF/Mobile-Security-Framework-MobSF#637]
## EXPLANATION OF THE ISSUE
Hello,
    I'm using the MobSF for static analysis. I have installed the MObSF requirements on Windows 7 machine. I have followed the documentation on link "https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation" for installation.
While running the MobSF and uploading the apk file, I'm getting the error
" 'NoneType' object does not support item assignment"     

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

D:\Python36>python.exe d:\Mobile-Security-Framework-MobSF\manage.py runserver
Performing system checks...

  __  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/

Mobile Security Framework v1.0 Beta

REST API Key: a79edbcec9aa119f30d2d2bc07e525bae83f9cd259e8bb5df91c6fdb87789a81
OS: Windows
Platform: Windows-7-6.1.7601-SP1

[WARNING] Could not find VirtualBox path.

[INFO] Checking for Update.

[INFO] No updates available.
System check identified no issues (0 silenced).
May 11, 2018 - 11:14:38
Django version 2.0.5, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[11/May/2018 11:15:19] "GET / HTTP/1.1" 200 7723
[INFO] MIME Type: application/vnd.android.package-archive FILE: Testapp.apk

[INFO] Performing Static Analysis of Android APK
[11/May/2018 11:15:31] "POST /upload/ HTTP/1.1" 200 134
[INFO] Starting Analysis on : Testapp.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Converting AXML to XML

[2018-05-11 11:15:42]
[ERROR]Getting Manifest file (d:\Mobile-Security-Framework-MobSF\StaticAnalyzer\
views\android\manifest_analysis.py, LINE 1304 "subprocess.check_output(args)"):
[WinError 2] The system cannot find the file specified

[2018-05-11 11:15:42]
[ERROR] Reading Manifest file (d:\Mobile-Security-Framework-MobSF\StaticAnalyzer
\views\android\manifest_analysis.py, LINE 1259 "if isFileExists(manifest):"): st
at: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] Parsing AndroidManifest.xml

[2018-05-11 11:15:42]
[ERROR] apktool failed to extract AndroidManifest.xml or parsing failed (d:\Mobi
le-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py, L
INE 28 "manifest = minidom.parseString(dat)"): a bytes-like object is required,
not 'NoneType'
[WARNING] Using Fake XML to continue the Analysis
[INFO] Fetching icon path
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate

[2018-05-11 11:15:44]
[ERROR] Reading Code Signing Certificate (d:\Mobile-Security-Framework-MobSF\Sta
ticAnalyzer\views\android\cert_analysis.py, LINE 65 "dat = subprocess.check_outp
ut(args)"): [WinError 2] The system cannot find the file specified
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
[INFO] Converting d:\Mobile-Security-Framework-MobSF\uploads/56e9273f71f06d29ea6
e98c45b77e890\classes.dex to JAR
[INFO] Running JAVA path fix in Windows
'"D:/Program Files/Java/jdk-10.0.1/binjava"' is not recognized as an internal or
 external command,
operable program or batch file.
[INFO] Converting d:\Mobile-Security-Framework-MobSF\uploads/56e9273f71f06d29ea6
e98c45b77e890\classes2.dex to JAR
[INFO] Running JAVA path fix in Windows
'"D:/Program Files/Java/jdk-10.0.1/binjava"' is not recognized as an internal or
 external command,
operable program or batch file.
[INFO] DEX -> SMALI
[INFO] Converting d:\Mobile-Security-Framework-MobSF\uploads/56e9273f71f06d29ea6
e98c45b77e890\classes.dex to Smali Code

[2018-05-11 11:15:44]
[ERROR] Converting DEX to SMALI (d:\Mobile-Security-Framework-MobSF\StaticAnalyz
er\views\android\converter.py, LINE 112 "subprocess.call(args)"): [WinError 2] T
he system cannot find the file specified
[INFO] JAR -> JAVA
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - d:\Mobile-Security-Framework-MobSF\uploads/56e
9273f71f06d29ea6e98c45b77e890/java_source/
[INFO] Performing Malware Check on extracted Domains
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK

[INFO] Connecting to Database

[INFO] Saving to Database

[2018-05-11 11:15:45]
[ERROR] Saving to DB (d:\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\an
droid\db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType
' object is not subscriptable

[2018-05-11 11:15:45]
[ERROR] Rendering to Template (d:\Mobile-Security-Framework-MobSF\StaticAnalyzer
\views\android\db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],")
: 'NoneType' object is not subscriptable
←[1m←[91m[ERROR] 'NoneType' object does not support item assignment←[0m
[11/May/2018 11:15:45] "GET /StaticAnalyzer/?name=Testapp.apk&type=apk&checksum=
56e9273f71f06d29ea6e98c45b77e890 HTTP/1.1" 500 4835

Error message showing on the browser:

Don't Play Around. An Error just popped in!
Inappropriate argument type.

'NoneType' object does not support item assignment

## CONTENTS OF LOG FILES
[MobSF.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/1994079/MobSF.log)

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by khushbukothari** [comment]
Thanks in advance.

**Comment by ajinabraham** [comment]
Java path is wrong. Clone the latest master and Don't run MobSF from python dir. Add python3 to path and run it from MobSF dir.

**Comment by khushbukothari** [comment]
Hi Abraham,
           The java path was correct as I had installed java in "D" drive. I cloned the latest MobSF and then as you said, I run it from MobSF directory and it worked.
Thanks

**Comment by ajinabraham** [comment]
It is not. Read that path in the error message once again

**Comment by ajinabraham** [comment]
The latest MobSF try to gracefuly cover up human errors to some extent. The path should end with a / and your Java path was missing that.

**Comment by Anucode** [comment]
Successfully configured static Analyzer.
Got the 
![image](https://user-images.githubusercontent.com/11830512/57771621-d5c36a00-7730-11e9-87f5-f31a5bc5fd21.png)
But while running got the below error:
Error: Specify one application only got this

**Comment by ajinabraham** [comment]
The latest version is 1.0.3.

**Comment by Anucode** [comment]
I have installed the latest one v1.0.8  Beta. I haven't got the system check identified messages , I am guessing that's why I am not able to  start it.

When I tried running manage.py runserver got below mentioned error:
from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

When I tried running python -c "import django; print(django.get_version())" to know the version
it prints 2.2.1

Could you please help me figure out this?

Thanks in anticipation

**Comment by ajinabraham** [comment]
The installation is not successful. How did you install? Which OS?

**Comment by ajinabraham** [comment]
You should read latest MobSF documentation. The setup instructions has changed.

**Comment by Anucode** [comment]
I followed https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation
I followed Configuring Static Analyzer  On my local windows system
Failed building wheel for cryptography.

**Comment by ajinabraham** [comment]
The setup script ask you to install openssl to meet crypto dependencies. If you are trying in windows, you need to wait till a bug is fixed. We have some issues with windows at the moment

**Comment by Anucode** [comment]
I have installed Open SSL from https://slproweb.com/products/Win32OpenSSL.html.
Okay. One more question I have if I want to do this setup in Azure VM, what document should I follow, or what are the steps to do so?

**Comment by ajinabraham** [comment]
Depending on the OS. We currently support Windows, Linux and Mac. The setup instructions are the same. If something fails that means one or other dependencies are not installed properly. You need to find that and fix them. MobSF as shipped is tested on Windows 10, Ubuntu 16.04+, OSX+.
But currently broken in Windows env.

**Comment by yztale** [comment]
Hello, I used mobsf to test apk and found many apk errors.
`
Don't Play Around. An Error just popped in!
Inappropriate argument type.
'NoneType' object does not support item assignment
`
The following APK is full of errors，I tested 100 apk, 20 of which reported errors, and the other 80 were normal
![image](https://user-images.githubusercontent.com/45749015/58547015-29f24200-8239-11e9-8e98-70ec47de6cd9.png)

![image](https://user-images.githubusercontent.com/45749015/58546926-fe6f5780-8238-11e9-9272-84e137db8d16.png)

**Comment by ajinabraham** [comment]
Please share the ones that caused issues for troubleshooting.

**Comment by yztale** [comment]
Am I here to ask how to solve this problem so that I can successfully scan

**Comment by ajinabraham** [comment]
How do I solve the problem without knowing what caused it? I need the files to reproduce/troubleshoot issues and fix them if applicable.

**Comment by yztale** [comment]
Ok, I will send you the email tomorrow

**Comment by yztale** [comment]
I will send the questions to your email (ajin25@gmail.com)
I look forward to your help  ,think you

**Comment by zjsjayce** [comment]
I also have this problem ：[INFO] 05/Jul/2019 02:31:35 - JDK 1.7 or above is available
[WARNING] 05/Jul/2019 02:31:35 - Could not find VirtualBox path.
[INFO] 05/Jul/2019 02:31:35 - MobSF Basic Environment Check

mac os /python/ latest

**Comment by Anucode** [comment]
Use the docker image it works perfectly.

Regards
Anuradha

________________________________

**Comment by zjsjayce** [comment]
After I use the docker, I also have another problem:
 [ERROR] 08/Jul/2019 03:17:28 - You're using the staticfiles app without
having set the STATIC_ROOT setting to a filesystem path.
[ERROR] 08/Jul/2019 03:17:28 - Internal Server Error: /StaticAnalyzer/

How do I fix it~
Thx


Anucode <notifications@github.com> 于2019年7月5日周五 下午5:42写道：

**Comment by imaduddin85** [comment]
Hi Team, 
I'm getting an error: Don't play around and error just popped in
Internal error 34


RROR] 09/Sep/2019 11:28:44 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Documents/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 186, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/root/Documents/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/usr/local/lib/python3.7/dist-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 09/Sep/2019 11:28:44 - internal error: 34
[ERROR] 09/Sep/2019 11:28:44 - Internal Server Error: /StaticAnalyzer/
[ERROR] 09/Sep/2019 11:28:44 - "GET /StaticAnalyzer/?name=Sample%20Android%20App%20Test_v1.0_apkpure.com.apk&type=apk&checksum=5b8a7fe0055b3a68f8369658789304f0 HTTP/1.1" 500 4796

**Comment by bugview** [comment]
Error
Inappropriate argument type.

__init__() got an unexpected keyword argument 'include_types'  what is problem？Has anyone met?Please reply to me！my email bugview@126.com  thank!
