### ISSUE TITLE
vm screen size

### ISSUE THREAD

**Issue by mahmoodn** [MobSF/Mobile-Security-Framework-MobSF#638]
After MobSF_VM_0.2 boots up, I can login with 1234 password. However, the vm screen size is larger than my screen. Therefore, virtualbox will add scrollbars. 
That happens when the vm guest additions are not installed. Is that the same issue here? What should I do?

**Comment by ajinabraham** [comment]
Scale the display in Virtual Box. This is not a bug. For discussion use slack channel
