### ISSUE TITLE
Don't play arround a error just stopped in! in mob security framework

### ISSUE THREAD

**Issue by dk201996** [MobSF/Mobile-Security-Framework-MobSF#639]
[2018-05-25 23:17:14]
[ERROR] ScreenCast Server (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 1032 "screen_socket.bind(addr)"): [Errno 99] Cannot assign requested address
[2018-05-25 23:21:03]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 376 "resp = subprocess.check_output(args)"): Command '['/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.7:5555', '']' returned non-zero exit status 1.
[2018-05-25 23:21:03]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 379 "data = {'cmd': 'yes', 'resp': resp.decode("utf8", "ignore")}"): 'str' object has no attribute 'decode'
[2018-05-25 23:27:03]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 376 "resp = subprocess.check_output(args)"): Command '['/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.7:5555', '']' returned non-zero exit status 1.
[2018-05-25 23:27:03]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 379 "data = {'cmd': 'yes', 'resp': resp.decode("utf8", "ignore")}"): 'str' object has no attribute 'decode'
[2018-05-25 23:27:56]
[ERROR] ScreenCast Server (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 1032 "screen_socket.bind(addr)"): [Errno 99] Cannot assign requested address
[2018-05-25 23:30:02]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:30:02]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:30:28]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:30:28]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:35:18]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:35:18]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:39:19]
[ERROR] ScreenCast Server (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 1032 "screen_socket.bind(addr)"): [Errno 99] Cannot assign requested address
[2018-05-25 23:56:36]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:56:36]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:58:54]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-25 23:58:54]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-26 00:03:23]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-26 00:03:23]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-26 00:03:31]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-26 00:03:31]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 13:05:11]
[ERROR] Getting Screen Resolution (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/shared.py, LINE 74 "[adb, "-s", get_identifier(), "shell", "dumpsys", "window"])"): Command '['/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.13:5555', 'shell', 'dumpsys', 'window']' returned non-zero exit status 1.
[2018-05-27 13:12:28]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 376 "resp = subprocess.check_output(args)"): Command '['/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.13:5555', 'adb', 'devices']' returned non-zero exit status 1.
[2018-05-27 13:12:28]
[ERROR] Executing ADB Commands (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 379 "data = {'cmd': 'yes', 'resp': resp.decode("utf8", "ignore")}"): 'str' object has no attribute 'decode'
[2018-05-27 13:20:36]
[ERROR] ScreenCast Server (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 1032 "screen_socket.bind(addr)"): [Errno 99] Cannot assign requested address
[2018-05-27 13:43:00]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 13:43:00]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 13:44:44]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 13:44:44]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 14:08:58]
[ERROR] ScreenCast Server (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 1032 "screen_socket.bind(addr)"): [Errno 99] Cannot assign requested address
[2018-05-27 14:14:53]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 14:14:53]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 14:17:16]
[ERROR] ScreenCast Server (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 1032 "screen_socket.bind(addr)"): [Errno 99] Cannot assign requested address
[2018-05-27 14:32:50]
[ERROR] Dynamic API Analysis (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_logcat.txt'
[2018-05-27 14:32:50]
[ERROR] Dynamic Analysis Report Generation (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 845 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/uploads/21835ce25d271b43d76d04d75c5527a8/x_log**

This error is occuring again and again plz help me out.I am using Rooted Android 6.0 massmellow  Device with adb to connect to kali in which the mobsf is installed.

**Comment by ajinabraham** [comment]
Do you have 32 bit execution support enabled?
Try running this individually
`/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb`

Make sure you run this https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/kali_fix.sh and it's a success.

**Comment by pgargey** [comment]
Same problem observed -- while doing static analysis

Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable

[2018-05-30 18:51:47]
[ERROR] Reading Code Signing Certificate 
Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 49 "cert) if os.path.isfile(os.path.join(cert, f))]"): [Errno 2] No such file or directory: 
Mobile-Security-Framework-MobSF/uploads/bf97bd0eaf4e1424b742cb155a98e245/META-INF/'

**Comment by pgargey** [comment]
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - Mobile-Security-Framework-MobSF/uploads/bf97bd0eaf4e1424b742cb155a98e245/java_source/
[INFO] Performing Malware Check on extracted Domains

[INFO] Malware Database is up-to-date.
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK

[INFO] Connecting to Database

[INFO] Saving to Database

[2018-05-30 18:52:16]
[ERROR] Saving to DB (Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable

[2018-05-30 18:52:16]
[ERROR] Rendering to Template (Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[ERROR] 'NoneType' object does not support item assignment

**Comment by pgargey** [comment]
Also, I have tried
python3 manage.py migrate 
python3 manage.py makemigrations

still no use

**Comment by dk201996** [comment]
Actually i am using real Android device with version 6.0.Is it okay or the problem which is shown is occuring because of my Android version?

**Comment by ajinabraham** [comment]
Currently we don't support Android 6.0
