### ISSUE TITLE
How can I set the api key?

### ISSUE THREAD

**Issue by omerlh** [MobSF/Mobile-Security-Framework-MobSF#642]
## EXPLANATION OF THE ISSUE

I want to run MobSF in the CI (using docker), and to interact with it I want to use the API.
The only problem is the authentication - I need to either get the API key programmatically or be able to set it prior to launch. 
Is that possible? What is required?

Edit:

I've tried to set `/root/.MobSF/secret`, but looks like it is overridden during startup.

Thanks!
Omer

**Comment by superpoussin22** [comment]
This is how we generate the API Key. It is unique per secret key which is generated at first run

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/utils.py#L57 

You can prolly programatically open the file and calculate the hash to generate the API key

**Comment by ajinabraham** [comment]
@omerlh Alternatively if it's a closed environment, You can hard code a sha256 hash here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/utils.py#L63 and use it as API key.

**Comment by omerlh** [comment]
@ajinabraham  why closing the issue? I still not following what should I do.

What you suggesting is changing the code? is this the only solution?

**Comment by ajinabraham** [comment]
Like @superpoussin22 mentioned. The REST API key is generated at first run. You will have to pull it out from the docker container programatically or like I suggested, hard code the API Key before building the Docker image by changing the code or scripting in Dockerfile.

**Comment by omerlh** [comment]
What about adding an option to override the api key? I can open a PR...

**Comment by ajinabraham** [comment]
Could you please elaborate?

**Comment by omerlh** [comment]
This is why I asked why you closed the issue - I might have more to say about the issue before closing it.

One option - adding an environment variable, and if set read the api key from it. Another option - add an env var that disables api key authentication. Both are great solutions for CI when you run mobsf locally and you don't care about authentication.

**Comment by ajinabraham** [comment]
GitHub issues are for Bugs and Feature requests. For discussions use our slack channel. Read: https://github.com/MobSF/Mobile-Security-Framework-MobSF#contribution-feature-requests--bugs

Option one looks fine to me. We don't want to disable Auth. PRs are always welcome.

**Comment by omerlh** [comment]
Fair enough, your point is clear. Sorry for opening an issue and not reading the issue template, where this is exactly specified.

I'll start working on a PR.

**Comment by fuzboxz** [comment]
Thanks for creating the PR @omerlh, this is exactly what I needed.
