### ISSUE TITLE
fstack protector flag applied but only visible for MIPS architecture

### ISSUE THREAD

**Issue by vineetj** [MobSF/Mobile-Security-Framework-MobSF#646]
## EXPLANATION OF THE ISSUE

A security issue was raised where the Android apk containing native libs does not have stack protection enabled. The stack protector flag was then put as compiler option and again apk was uploaded on MobSF tool but only for MIPS architecture the library issue got resolved while for other architectures like arm64-v8, armeabi-v7a it still complains about missing stack protector flag.

Attached are the screens after putting compiler flag(Screen1) & before putting compiler flag(Screen2):

![screen1](https://user-images.githubusercontent.com/5718108/41234123-f4adea2c-6da8-11e8-98bd-c45ebb938873.png)

![screen2](https://user-images.githubusercontent.com/5718108/41234124-f5044d4a-6da8-11e8-9cab-feb3dc2b8463.png)

**Comment by ajinabraham** [comment]
I think it's related to a previous issue reported.

**Comment by vineetj** [comment]
@ajinabraham  :  That may be the case but i want to be very sure about what i did to remove that security issue (i.e. setting of compiler flags). Not sure if this can verified here, but still here's the code which has been put up in CMakeList.txt :  `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -fstack-protector-strong")`. So depending if this is correct and no other compiler flag needs to be mentioned then there might be an issue with tool.

**Comment by vineetj** [comment]
Any updates on the same

**Comment by ajinabraham** [comment]
This feature was contributed to MobSF by an external contributor. This will take some time to get resolved.

**Comment by ajinabraham** [comment]
Closing this here and tracking with original issue
