### ISSUE TITLE
Recent Scans Page Returning 404 

### ISSUE THREAD

**Issue by bit-twidd1er** [MobSF/Mobile-Security-Framework-MobSF#651]
## EXPLANATION OF THE ISSUE

Using the docker image and most recent master branch from Github, the Recent Scans page returns a 404 (Page not found) error. This results in a user not being able to revisit previous analysis and having to reanalyze binaries constantly.

## STEPS TO REPRODUCE THE ISSUE

```
1. Pull down latest docker image: `docker pull opensecurity/mobile-security-framework-mobsf`
2. Run the docker container: `docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest`
3. Navigate to localhost:8000
4. Click on the "Recent Scans" link and observe the error message
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Not Found: /recent_scans/
2018-06-18 14:18:35 WARNING  Not Found: /recent_scans/
[18/Jun/2018 14:18:35] "GET /recent_scans/ HTTP/1.1" 404 6929
```

**Comment by ajinabraham** [comment]
It's `/recent_scans` not `/recent_scans/`

**Comment by bit-twidd1er** [comment]
My apologies, but that is a typo in my writeup, and the issue remains. Check to console output to see that is the case.

**Comment by ajinabraham** [comment]
I just tested the latest docker image and it just works fine.

**Comment by bit-twidd1er** [comment]
My apologies, I will wipe my docker image and try to pull a fresh image to see if it resolves it.
