### ISSUE TITLE
Dynamic Analysis

### ISSUE THREAD

**Issue by abhishekankur** [MobSF/Mobile-Security-Framework-MobSF#655]
SIR ,
kindly help
while running Mobsf_avd.py
i found this error
![screenshot from 2018-06-26 18-09-04](https://user-images.githubusercontent.com/39509913/41912305-edf25de2-796c-11e8-9ee7-d49c7d10abda.png)

root@kaliJi:~/Desktop/Mobile-Security-Framework-MobSF-master/scripts# sudo python mobsfy_AVD.py 

MobSFy_AVD Script

[INFO] Starting MobSF - AVD interactive configuration script

[INFO] Make sure to run this script ONLY after you successfuly installed latest AndroidStudio & downloaded MobSF_ARM_Emulator.zip

[INFO] Please specify the path to MobSF_ARM_Emulator extracted folder

MobSF_ARM_Emulator folder: /root/Desktop/MobSF_ARM_Emulator
Traceback (most recent call last):
  File "mobsfy_AVD.py", line 317, in <module>
    sys.exit(main())
  File "mobsfy_AVD.py", line 214, in main
    mobsf_arm_folder = verify_path('MobSF_ARM_Emulator folder')
  File "mobsfy_AVD.py", line 39, in verify_path
    path = input(help_msg + ': ')
  File "<string>", line 1
    /root/Desktop/MobSF_ARM_Emulator
    ^
SyntaxError: invalid syntax

**Comment by ajinabraham** [comment]
It needs python3, not python2. Also MobSF AVD is currently not working.

**Comment by abhishekankur** [comment]
![screenshot from 2018-06-27 12-02-03](https://user-images.githubusercontent.com/39509913/41956648-fba58e38-7a01-11e8-97d6-e7d63896fb03.png)

**Comment by abhishekankur** [comment]
sir now showing this error 
sorry for disturbing you
I am a PG student doing m.tech from rgpv bhopal with cyber forensic branch.

**Comment by princenaman** [comment]
Is it still not working?

```
nexus 5 skin path: 
Traceback (most recent call last):
  File "mobsfy_AVD.py", line 318, in <module>
    sys.exit(main())
  File "mobsfy_AVD.py", line 256, in main
    skin_path = verify_path('nexus 5 skin path')
  File "mobsfy_AVD.py", line 40, in verify_path
    path = input(help_msg + ': ')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by ajinabraham** [comment]
AVD support is currently discontinued.

**Comment by princenaman** [comment]
😢 okay

**Comment by joekendal** [comment]
@ajinabraham Really??? The documentation is out of date then

**Comment by ajinabraham** [comment]
@joekendal The doc's are latest. This was an early implementation of AVD that went unsupported.

**Comment by joekendal** [comment]
@ajinabraham then why do I get this error:
```
[ERROR] 12/Jun/2020 06:13:18 - Is the Android VM running?
MobSF cannot identify device id.
Please set ANALYZER_IDENTIFIER in MobSF/settings.py
```

settings.py
```
    # =======ANDROID DYNAMIC ANALYSIS SETTINGS===========
    ANALYZER_IDENTIFIER = 'emulator-5554'
    FRIDA_TIMEOUT = 4
    # ==============================================
```

```
➜  ~ ./Library/Android/sdk/platform-tools/adb devices     
List of devices attached
emulator-5554	device

```

What is it meant to be

**Comment by joekendal** [comment]
and there's still no avd script is there?

**Comment by ajinabraham** [comment]
There is no script to use here. please follow the official docs.

**Comment by ajinabraham** [comment]
For support use slack channel

**Comment by joekendal** [comment]
@ajinabraham I followed the docs. the docs are outdated clearly
