### ISSUE TITLE
Possibilty of Dynamic Analysis in Android 7 or 6(VM or Rooted Device)???

### ISSUE THREAD

**Issue by rohandora** [MobSF/Mobile-Security-Framework-MobSF#656]
Hello team,
Thanks for the nice product,i am new to this tool and was doing dynamic analysis when i ran into problems.

I used Android VM provided by you,for dynamic analysis.Everything works fine,report is also generated but unfortunately my app crashes multiple times while running Activity Tester possibly due to Android Jelly Bean and lower API version.

Also,I donot have a rooted device,however i could manage to get approval to root a device, but with Android 7 or 6.

So,Currently,is it possible to run dynamic analysis in VM,with higher version of Android
or can we do dynamic analysis in a rooted device with android 7 or atleast android 6 ?.

**Comment by ajinabraham** [comment]
@rohandora This script `MobSFy.py` https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/scripts/mobsfy.py unofficially support android devices above version 5. You can try that, but we haven't tested it well. We are working on MobSF AVD to support newer version. But that takes time.

Follow docs here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/2.-Configure-MobSF-Dynamic-Analysis-Environment-in-your-Android-Device-or-VM

**Comment by rohandora** [comment]
Hello @ajinabraham thanks for the help.I used Android 6 Virtual Machine for the setup and i end up in the same issue as pointed out at #428.
Thanks
