### ISSUE TITLE
Enhancement - Support for both "armeabi-v7a and armeabi-v7a x86"

### ISSUE THREAD

**Issue by madhuCNKony** [MobSF/Mobile-Security-Framework-MobSF#661]
When we run few real time apps on MobSF Emulator (for dynamic analysis), we face issue

"adb: failed to install luavmandroid.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]"

To run all apps, please support armeabi-v7a and armeabi-v7a x86 compatible emulator.

Ref: 

https://androidlad.blogspot.com/2016/10/installfailednomatchingabis-when.html 

http://translate.google.com/translate?depth=1&nv=1&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=http://m.blog.csdn.net/article/details%3Fid%3D49735601

**Comment by ajinabraham** [comment]
Tracked Sepearately
