### ISSUE TITLE
regression after move from pyWebProxy to CapFuzz

### ISSUE THREAD

**Issue by rriemann** [MobSF/Mobile-Security-Framework-MobSF#662]
## EXPLANATION OF THE ISSUE

`script/mobsfy.py` to setup real devices for MobSF is still assuming the existence of some root CA files from pyWebProxy and fails now, because pyWebProxy has been removed.

Furthermore, the script also assumes that MobSF was already running and certificates were generated. This should be better documented.

## STEPS TO REPRODUCE THE ISSUE

- checkout this repo
- run `python3 scripts/mobsfy.py`

**Comment by ajinabraham** [comment]
Good Catch!
