### ISSUE TITLE
Capfuz proxy very verbose logging

### ISSUE THREAD

**Issue by rriemann** [MobSF/Mobile-Security-Framework-MobSF#663]
## EXPLANATION OF THE ISSUE

I start the dynamic analysis and configured on a real android device the MobSF proxy Capfuz. When I start downloading data using some app, the output of `python3 manage.py runserver` contains hundreds of lines:

````
some-ip:port: clientconnect
some-ip:port clientdisconnect
```

I fear to miss out important messages because of that.

**Comment by ajinabraham** [comment]
You should file this at capfuzz repo.
