### ISSUE TITLE
CODE ANALYSIS Issue related to Android APK Static Analysis

### ISSUE THREAD

**Issue by R-PSingh** [MobSF/Mobile-Security-Framework-MobSF#666]
On runnng the MobSF I have got these below issue.

- This App uses Java Hash Code. It's a weak hash function and should never be used in Secure Crypto 
- App can read/write to External Storage. Any App can read data written to External Storage.
- The App logs information. Sensitive information should never be logged.
- The App uses an insecure Random Number Generator.
- Files may contain hardcoded sensitive informations like usernames, passwords, keys etc.

Please find the attached screen shot from the report.
![code analysis](https://user-images.githubusercontent.com/33144225/42815742-ea6c9b68-89e5-11e8-8384-c9ab68943c7d.PNG)

To develop our mobile app we have used react js language. 
I am facing the above issues when I run  the MobSF static analysis on Android APK .. Do you have any suggestion/pointers to resolve this issue?

**Comment by ajinabraham** [comment]
Use slack channel for discussions. This issue tracker is strictly for MobSF bugs.
The above is not bug.

**Comment by FidelAHM** [comment]
I am facing the same problem. Is there any solution?
