### ISSUE TITLE
Not ale to perform MobSF Dynamic Analysis on MobSF ARM Emulator

### ISSUE THREAD

**Issue by vikashbkj** [MobSF/Mobile-Security-Framework-MobSF#667]
## EXPLANATION OF THE ISSUE

All setup done.
While clicking on **Start Dynamic Analysis** button Emulator starts successfully but apk is not installing hence app is not running.

Please find terminal log
[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF Emulator

[INFO] Stopping MobSF Emulator

[INFO] Deleting emulator files

[INFO] Duplicating MobSF Emulator

[INFO] Starting MobSF Emulator
[18/Jul/2018 11:17:35] "POST /DynamicAnalyzer/ HTTP/1.1" 200 31318
[18/Jul/2018 11:17:35] "GET /download/screen/screen.png HTTP/1.1" 302 0
[18/Jul/2018 11:17:35] "GET /error/ HTTP/1.1" 200 4749

[INFO] Setting up Dynamic Analysis Environment
[INFO] Wait for emulator to load
[INFO] Wait for dev.boot_complete loop
Capture Module Loaded
Proxy server listening at http://*:1337

**Emulator stuck at Proxy server listening at http://*:1337**

App does not run on Emulator for Dynamic Analysis
App is not launched on Emulator.

## CONSOLE OUTPUT
[INFO] Starting MobSF Emulator
[18/Jul/2018 11:17:35] "POST /DynamicAnalyzer/ HTTP/1.1" 200 31318
[18/Jul/2018 11:17:35] "GET /download/screen/screen.png HTTP/1.1" 302 0
[18/Jul/2018 11:17:35] "GET /error/ HTTP/1.1" 200 4749

[INFO] Setting up Dynamic Analysis Environment
[INFO] Wait for emulator to load
[INFO] Wait for dev.boot_complete loop
Capture Module Loaded
Proxy server listening at http://*:1337

```

## CONTENTS OF LOG FILES
```

[ERROR] Duplicating MobSF Emulator (/home/bluepi/Vikash/GitHub/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/avd.py, LINE 56 "shutil.copyfile(reference_ini, dup_ini)"): [Errno 2] No such file or directory: '/home/bluepi/.android/avd/Nexus5API16.ini'
[2018-07-18 10:02:40]
[ERROR] Starting MobSF Emulator (/home/bluepi/Vikash/GitHub/Mobile-Security-Framework-MobSF-master/DynamicAnalyzer/views/android/avd.py, LINE 96 "subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)"): [Errno 13] Permission denied
[2018-07-18 11:11:10]
[ERROR] Performing Malware Check (/home/bluepi/Vikash/GitHub/Mobile-Security-Framework-MobSF-master/MalwareAnalyzer/views.py, LINE 162 "if isInternetAvailable():"): HTTPSConnectionPool(host='www.google.com', port=443): Read timed out.
[2018-07-18 11:17:12]
[ERROR] Cannot Check for updates. (/home/bluepi/Vikash/GitHub/Mobile-Security-Framework-MobSF-master/MobSF/utils.py, LINE 103 "proxies=proxies, verify=verify)"): HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5)

```

```

**Comment by vikashbkj** [comment]
@ajinabraham Please guide.

**Comment by ajinabraham** [comment]
MobSF Arm emulator is broken at the moment. It's mentioned in the docs.

**Comment by vikashbkj** [comment]
![screenshot from 2018-07-19 12-40-40](https://user-images.githubusercontent.com/22520808/42927163-3a2ff3ae-8b51-11e8-829d-8cc469616b32.png)


@ajinabraham 
Please find attached screen shot. Please guide what is the way to perform dynamic analysis.
Thanks

**Comment by ajinabraham** [comment]
I repeat ARM emulator doesn't work at the moment. Use VirtualBox VM or Real device.
