### ISSUE TITLE
Real Device - Dynamic Analysis ERROR "Unfortunately, <app name> has stopped".

### ISSUE THREAD

**Issue by f00bar10** [MobSF/Mobile-Security-Framework-MobSF#670]
Hi,

First of all, this framework is really awesome, nice work!

I am trying to do a dynamic analysis for apk, and when the project installs the app on my real device (configured as you recommend), I get a crash immediately saying "Unfortunately, <APP> has stopped".

I have guessed why, and I think it is because of **Xposed Droidmon module**, because when it is activated, the apps (more than one is being tested, for instance Whatsapp, Google Play Services...) do not work and you can see the "<APP> has stopped". If I stop this module, all apps work nicely.

How can I solve it? I get the same error on your MobSF Android x86 4.4.2 VM (v0.3) ova.

Thanks in advance,
Best regards.

PD: my Android version on real device is 5.1.1 with Kali Nethunter installed.

**Comment by ajinabraham** [comment]
Which version of Xposed are you using with Android 5.1.1?
Also what kind of root are you using. Currently the recommended way is to use system less root like Magisk with Xposed. Also if your apk has code to detect Xposed, you should patch that before hand. You can also check adb logs to see what is causing the crash.

**Comment by f00bar10** [comment]
I am using **Xposed v3.1.5 (Framework v89 for SDK 22)**, it is ok, isn't it?
How can I know what kind of root I am using? I have already installed Magisk for testing, but still the error. As I said before, when I active **Droidmon module** on Xposed Framework and reboot the phone, YouTube app, Google Play Services, Mozilla Focus, my app, etc, always crash immediately saying "Unfortunately, <APP> has stopped". By contrast, if I stop this module, all apps work nicely.
I think (99% sure) that my app is not detecting Xposed, how can I check it?
Related to **adb logs,** here is the output:
`....SNIP....
I/Xposed  ( 9588): Droidmon-apimonitor-com.iphonedroid.apptest.newapp:{"class":"libcore.io.IoBridge","method":"open","timestamp":1532187389455,"type":"file","args":["\/data\/data\/com.iphonedroid.apptest.newapp\/files\/.Fabric\/com.crashlytics.sdk.android.crashlytics-core\/5G2852FD019D-0212-2574-E34570353824SessionDevice.json","577"],"result":{"descriptor":29}}
W/CrashlyticsCore( 9588): Cannot send reports. Settings are unavailable.
E/AndroidRuntime( 9588): FATAL EXCEPTION: main
E/AndroidRuntime( 9588): Process: com.iphonedroid.apptest.newapp, PID: 9588
E/AndroidRuntime( 9588): io.reactivex.exceptions.OnErrorNotImplementedException: Already connected
E/AndroidRuntime( 9588): 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
E/AndroidRuntime( 9588): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
E/AndroidRuntime( 9588): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 9588): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9588): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 9588): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 9588): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9588): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9588): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 9588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 9588): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
E/AndroidRuntime( 9588): Caused by: java.lang.IllegalStateException: Already connected
E/AndroidRuntime( 9588): 	at java.net.URLConnection.checkNotConnected(URLConnection.java:463)
E/AndroidRuntime( 9588): 	at java.net.URLConnection.setUseCaches(URLConnection.java:945)
E/AndroidRuntime( 9588): 	at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.createHttpUrlConnection(WalledGardenInternetObservingStrategy.java:107)
E/AndroidRuntime( 9588): 	at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.isConnected(WalledGardenInternetObservingStrategy.java:87)
E/AndroidRuntime( 9588): 	at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:59)
E/AndroidRuntime( 9588): 	at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:57)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:83)
E/AndroidRuntime( 9588): 	at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:422)
E/AndroidRuntime( 9588): 	at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:372)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
E/AndroidRuntime( 9588): 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
E/AndroidRuntime( 9588): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 9588): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
E/AndroidRuntime( 9588): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
E/AndroidRuntime( 9588): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 9588): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 9588): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  652):   Force finishing activity 1 com.iphonedroid.apptest.newapp/com.iphonedroid.apptest.screen.main.MainActivity
....SNIP....`

**Comment by ajinabraham** [comment]
The versions looks fine. I am not sure what exactly is the issue here. You might want to check with Xposed project https://github.com/rovo89/XposedInstaller or Droidmon https://github.com/idanr1986/droidmon to troubleshoot this.

**Comment by realramkumar** [comment]
Issue seems to be in the [droidmon](https://github.com/idanr1986/droidmon). I went through my logs and found that **zygote** process fails forking the app.
```
12-02 15:00:20.567  2355  3736 I ActivityManager: Start proc 5490:com.getmimo/u0a107 for activity com.getmimo/.ui.SplashActivity
```
ActivityManager tries to start the launcher activity. PID: 5490
```
12-02 15:00:20.611  5490  5490 W zygote64: ClassLoaderContext size mismatch. expected=1, actual=2 (PCL[] | PCL[];PCL[/data/dalvik-cache/xposed_XResourcesSuperClass.dex*2802528989:/data/dalvik-cache/xposed_XTypedArraySuperClass.dex*708326108])
```
In the context of 5490, the zygote fails with ClassLoaderContext size mismatch. Then the 5490 dies receiving segmentation fault.
```
12-02 15:00:20.995  5490  5490 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7a87d85a9c in tid 5490 (re-initialized>), pid 5490 (re-initialized>)
```
The above happens for every app that crashes due to droidmon.
