### ISSUE TITLE
Download Report  and not Found!

### ISSUE THREAD

**Issue by walterliang** [MobSF/Mobile-Security-Framework-MobSF#672]
## EXPLANATION OF THE ISSUE

![image](https://user-images.githubusercontent.com/26303684/43073299-a0b7cb1c-8eab-11e8-8ab6-c475e9fde86c.png)

## STEPS TO REPRODUCE THE ISSUE

```
1. click the button: Download Report
2. and you can see the json tell u report not found!

```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
Need more details. Do you followed: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#pdf-report-generation

Also Can you see the Scan in the Recent Scans View. What's the console error when this occur

**Comment by walterliang** [comment]
my django version is not 2.0 and my python is 2.7. so i git pull and update new python and django. no issue now! thanks!

**Comment by okenwakc** [comment]
I am unable to download report from MobSF
