### ISSUE TITLE
Cannot Check for updates

### ISSUE THREAD

**Issue by safebaseline** [MobSF/Mobile-Security-Framework-MobSF#676]
(/root/Mobile-Security-Framework-MobSF/MobSF/utils.py, LINE 98 "proxies=proxies, verify=verify)"): HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=5)

**Comment by ajinabraham** [comment]
Works for me. Probably a network issue at your end.

```
[INFO] Checking for Update.
[INFO] No updates available.
```

**Comment by safebaseline** [comment]
my network is stable。another question：when i create  a vm,it warn me what can't Connect 192.168.56.101：5555.




------------------ 原始邮件 ------------------
发件人: "Ajin Abraham"<notifications@github.com>;
发送时间: 2018年8月9日(星期四) 凌晨1:45
收件人: "MobSF/Mobile-Security-Framework-MobSF"<Mobile-Security-Framework-MobSF@noreply.github.com>;
抄送: "风的影子"<798942836@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MobSF/Mobile-Security-Framework-MobSF] Cannot Check for updates(#676)




Works for me. Probably a network issue at your end.
 [INFO] Checking for Update. [INFO] No updates available.

**Comment by ajinabraham** [comment]
@safebaseline Make sure the VM is running at `192.168.56.101` and your host IP is in `192.168.56.XXX` range.

**Comment by safebaseline** [comment]
when will you update capfuzz? when i install mitmproxy3.0.2,the cryptography can't install!



------------------ 原始邮件 ------------------
发件人: "Ajin Abraham"<notifications@github.com>;
发送时间: 2018年8月9日(星期四) 凌晨1:45
收件人: "MobSF/Mobile-Security-Framework-MobSF"<Mobile-Security-Framework-MobSF@noreply.github.com>;
抄送: "风的影子"<798942836@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MobSF/Mobile-Security-Framework-MobSF] Cannot Check for updates(#676)




Works for me. Probably a network issue at your end.
 [INFO] Checking for Update. [INFO] No updates available.
