### ISSUE TITLE
VirtualBox with the .ova stopped

### ISSUE THREAD

**Issue by Kallo1994** [MobSF/Mobile-Security-Framework-MobSF#689]
## STEPS TO REPRODUCE THE ISSUE

I started VirtualBox with the .ova File as described in the documentation, but after a few seconds nothing happens anymore and I never get to see the VM IP. (I have Windows 10)

## CONSOLE OUTPUT

![unbenannt](https://user-images.githubusercontent.com/36983700/44277951-b0aad500-a24c-11e8-9603-c6b9b70a20e3.PNG)

**Comment by ajinabraham** [comment]
Sould be an issue with your system configuration or virtualbox.
