### ISSUE TITLE
Do we have plans to translate into other languages, or how to translate?

### ISSUE THREAD

**Issue by magaofei** [MobSF/Mobile-Security-Framework-MobSF#694]
My colleague wants to be a Chinese page.

**Comment by ajinabraham** [comment]
@magaofei It's not in the priority as there are tons of missing features to implement or refactor. However PRs are always welcome. Like @superpoussin22 mentioned we need english as default and allows user to change to other language.

This is a PR to support arabic: https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/664
but this cannot be merged to master. 
This are possible ways to achieve that in Django: 
https://coderwall.com/p/5lqyqg/multilanguage-in-django-1-9
https://fueled.com/blog/supporting-multiple-languages-in-django/
https://devdoodles.wordpress.com/2009/02/14/multi-language-support-in-a-django-project/

**Comment by magaofei** [comment]
OK
