### ISSUE TITLE
Don't Play Around. An Error just popped in! Attribute not found.  module 'yara' has no attribute 'load'

### ISSUE THREAD

**Issue by safebaseline** [MobSF/Mobile-Security-Framework-MobSF#701]
Don't Play Around. An Error just popped in!
Attribute not found.

module 'yara' has no attribute 'load'

**Comment by magaofei** [comment]
@safebaseline Thank you, Please provide more information

**Comment by safebaseline** [comment]
![default](https://user-images.githubusercontent.com/38883009/44695759-54934c80-aaa7-11e8-83cd-2e71c6e0ca79.png)
this is my screenshot！
![default](https://user-images.githubusercontent.com/38883009/44695796-7987bf80-aaa7-11e8-9245-2f223f03c101.png)
this is my log！

**Comment by magaofei** [comment]
@safebaseline Is it convenient to give me a download address?

**Comment by safebaseline** [comment]
what are you want to download？The picture what i upload！

**Comment by magaofei** [comment]
@safebaseline the apk file

**Comment by magaofei** [comment]
@safebaseline How did you run it?  Do you use Python3.6+ ?

**Comment by safebaseline** [comment]
yeah！my python version is 3.6.3！ i am sorry ！the apk file can't share with you！

**Comment by magaofei** [comment]
@safebaseline No problem, have you closed DEBUG ?

**Comment by safebaseline** [comment]
how to colse the debug？

**Comment by magaofei** [comment]
In file `MobSF/settings.py`, the default value is `DEBUG = True` , If it is True, no change is required.

**Comment by magaofei** [comment]
@safebaseline Can you install and run using a virtual environment?

**Comment by safebaseline** [comment]
ok! i will try!

**Comment by ajinabraham** [comment]
@safebaseline Yara is required by MobSF if you enable APKiD. It's not enabled by default. Read documentation
