### ISSUE TITLE
The some field name in api of report response is wrong 

### ISSUE THREAD

**Issue by magaofei** [MobSF/Mobile-Security-Framework-MobSF#708]
The api of report json response, the field of name`bro_count` is not browsable_activities count, should be is receivers count, so the name can't be `bro_count`, it should be `receiver_count` or `rec_count`.
and field `bro_count`

Please check

**Comment by ajinabraham** [comment]
`bro_count` is short for `Broadcast receivers count`

**Comment by magaofei** [comment]
The name is too short and there is a big ambiguity

**Comment by ajinabraham** [comment]
This is an enhancement and can be tracked separately
