### ISSUE TITLE
API CORS issue.

### ISSUE THREAD

**Issue by surya-bb** [MobSF/Mobile-Security-Framework-MobSF#709]
## EXPLANATION OF THE ISSUE

While Trying to make an api call, I am getting **401 error**, to which I found out that it could possibly be a CORS issue.  (Source: [https://stackoverflow.com/questions/39408413/http-post-how-to-send-authorization-header?answertab=votes#tab-top](url))

My front-end is running on different host, So while making POST request, because of CORS, it is being changed into OPTION. 

## STEPS TO REPRODUCE THE ISSUE

```
1. Make a small test app running on different port.
2. Make an API call from there.
3. Don't Use Postman kind of tools to test.
```

## CONSOLE OUTPUT

```
Unauthorized: /api/v1/upload
[30/Aug/2018 07:24:00] "OPTIONS /api/v1/upload HTTP/1.1" 401 61
```

## CONTENTS OF BROWSER API CALL ERROR

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
Failed to load http://127.0.0.1:8000/api/v1/upload: Response for preflight does not have HTTP ok status.

```

**Comment by superpoussin22** [comment]
dir you try this ?
curl -s -F "file=@./696943d5bf15d1a3fac6c19cc34300d1.apk" http://127.0.0.1:8000/api/v1/upload -H "Authorization:$API_KEY"   
(where API_KEY is you MobSF API KEY")

**Comment by ajinabraham** [comment]
@surya-bb Are you trying to make the API call as AJAX request?
Can you share the code you are using to make the API Call?

**Comment by surya-bb** [comment]
Okay!
So when can I expect the new changes?

**Comment by magaofei** [comment]
@surya-bb Are you running locally? Your front end can open the proxy. 
for example, the webpack have proxy and changeOrigin of devServer

**Comment by ajinabraham** [comment]
@surya-bb Sorry there is a bug that is preventing it. I am working on a fix. Will keep you posted

**Comment by surya-bb** [comment]
@magaofei I tried the proxy.-config way, I didn't work

`
{
	"/api/*":{
		"target": "http://127.0.0.1:8000/",
		"secure": false,
		"loglevel": "debug"

	}
}
`
this is what I tried doing.



@ajinabraham Thank you. By the way I tried to change the source code by installing django-cors-headers and setting up corsheaders middleware but it didn't work.

**Comment by surya-bb** [comment]
@magaofei I tried the proxy.-config way, I didn't work
```
{
	"/api/*":{
		"target": "http://127.0.0.1:8000/",
		"secure": false,
		"loglevel": "debug"

	}
}
```
this is what I tried doing.



@ajinabraham Thank you. By the way I tried to change the source code by installing django-cors-headers and setting up corsheaders middleware but it didn't work.

**Comment by magaofei** [comment]
@surya-bb Are you using webpack?
this is my settings.
```
devServer: {
    host: '127.0.0.1',
    port: 8011,
    proxy: {
      '/api/': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    },
  },
```

**Comment by surya-bb** [comment]
@magaofei Thanks! for the quick fix. `"changeOrigin": true` worked for me, but still I am getting 500 which I need to debug.

Still looking for a fix, because I don't want to put proxy-config in Production. :stuck_out_tongue_winking_eye:

**Comment by ajinabraham** [comment]
@surya-bb This will be fixed once #709 is merged to master.
Please use this as a baseline: https://gist.github.com/ajinabraham/bf2945741346c2fcdcd1b2e3df8baab0 while doing AJAX from Angular

**Comment by magaofei** [comment]
@surya-bb The local front end is the nodeJS service, which opens a different port, so there are cross-domain issues. On the line, it is usually static file access, and there is no proxy setting.

**Comment by magaofei** [comment]
@surya-bb I just test is, it worked for me.
![image](https://user-images.githubusercontent.com/3363787/44918695-3743d400-ad6e-11e8-90bb-2a98ca00eabe.png)
