### ISSUE TITLE
Error during static analysis using mobsf 

### ISSUE THREAD

**Issue by Payam-Almasian** [MobSF/Mobile-Security-Framework-MobSF#715]
after uploading an apk , an error page is shown 
take look at the log of the console 

[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - C:\Users\Sam\Desktop\Mobile-Security-Framework
-MobSF-master_3\Mobile-Security-Framework-MobSF-master\uploads/3b3801c01c8c08dd3
1727de8ff0ea0b0/java_source/

[2018-09-01 16:53:43]
[ERROR] Performing Code Analysis (C:\Users\Sam\Desktop\Mobile-Security-Framework
-MobSF-master_3\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\andr
oid\code_analysis.py, LINE 70 "errors="ignore""): [Errno 2] No such file or dire
ctory: 'C:\\Users\\Sam\\Desktop\\Mobile-Security-Framework-MobSF-master_3\\Mobil
e-Security-Framework-MobSF-master\\uploads/3b3801c01c8c08dd31727de8ff0ea0b0/java
_source/newapp\\com\\taxiyaab\\taxiyaab\\screenFragments\\dialogFragments\\snapp
Jek\\snappJekOnBoarding\\SnappJekChildFragment$$ViewInjector.java'

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping

[2018-09-01 16:53:44]
[ERROR] Zipping (C:\Users\Sam\Desktop\Mobile-Security-Framework-MobSF-master_3\M
obile-Security-Framework-MobSF-master\MobSF\utils.py, LINE 546 "zip_file.write(o
s.path.join(root, file_name))"): [WinError 3] The system cannot find the path sp
ecified: 'C:\\Users\\Sam\\Desktop\\Mobile-Security-Framework-MobSF-master_3\\Mob
ile-Security-Framework-MobSF-master\\uploads/3b3801c01c8c08dd31727de8ff0ea0b0/ja
va_source/newapp\\com\\taxiyaab\\taxiyaab\\screenFragments\\dialogFragments\\sna
ppJek\\snappJekOnBoarding\\SnappJekChildFragment$$ViewInjector.java'
[INFO] Zipping

[2018-09-01 16:53:45]
[ERROR] Zipping (C:\Users\Sam\Desktop\Mobile-Security-Framework-MobSF-master_3\M
obile-Security-Framework-MobSF-master\MobSF\utils.py, LINE 546 "zip_file.write(o
s.path.join(root, file_name))"): [WinError 3] The system cannot find the path sp
ecified: 'C:\\Users\\Sam\\Desktop\\Mobile-Security-Framework-MobSF-master_3\\Mob
ile-Security-Framework-MobSF-master\\uploads/3b3801c01c8c08dd31727de8ff0ea0b0/sm
ali_source/android\\support\\v4\\media\\session\\MediaControllerCompat$MediaCont
rollerImplApi21$ExtraBinderRequestResultReceiver.smali'
[INFO] Extracting Strings from APK

[INFO] Connecting to Database

[INFO] Saving to Database

[2018-09-01 16:53:46]
[ERROR] Saving to DB (C:\Users\Sam\Desktop\Mobile-Security-Framework-MobSF-maste
r_3\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\db_inter
action.py, LINE 221 "API=code_an_dic['api'],"): 'NoneType' object is not subscri
ptable

[2018-09-01 16:53:46]
[ERROR] Rendering to Template (C:\Users\Sam\Desktop\Mobile-Security-Framework-Mo
bSF-master_3\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android
\db_interaction.py, LINE 108 "'api': code_an_dic['api'],"): 'NoneType' object is
 not subscriptable
←[1m←[91m[ERROR] 'NoneType' object does not support item assignment←[0m
[01/Sep/2018 16:53:46] "GET /StaticAnalyzer/?name=cab.snapp.passenger.fl.apk&typ
e=apk&checksum=3b3801c01c8c08dd31727de8ff0ea0b0 HTTP/1.1" 500 4836

**Comment by superpoussin22** [comment]
checksum indicate this is cab.snapp.passenger , right ?

If yes I'm able to analyze it using mobsf

**Comment by Payam-Almasian** [comment]
whats wrong with my MOBSF  ?

**Comment by ajinabraham** [comment]
Can you share the APK @Payam-Almasian ?

**Comment by Polibus** [comment]
Hi i have the same issue with onother android  app the strange is that the other day MOBSF worked and analized the app well 
I attached the log file and the link of the APK 
(if i need to creat another Thread i'll do)
[APK](https://play.google.com/store/apps/details?id=be.delen.digital&hl=en) 
[log.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/2408144/log.log)

**Comment by ajinabraham** [comment]
Closing as 25 days of response period is over
