### ISSUE TITLE
plist_analysis.py, LINE 16

### ISSUE THREAD

**Issue by paradiseduo** [MobSF/Mobile-Security-Framework-MobSF#716]
[ERROR] Converting Binary XML to Readable XML (/Users/youssef/Documents/MSF/StaticAnalyzer/views/ios/plist_analysis.py, LINE 16 "plist_obj = plistlib.readPlist(bin_xml_file)"): Invalid file

how to do with it?

**Comment by ajinabraham** [comment]
@youshaoduo Are you on latest master? 
We don't support SWIFT binaries.
Can you share the IPA?

**Comment by youshaoduo** [comment]
@ajinabraham yes, I am on master, last submit 93606646d5339bb3eae729ce49121fa9726cecd0.

I am afraid I can't provide IPA.  We signed a confidentiality agreement.

I analysis the IPA in IDA64,  Objective-C and Swift both used.

**Comment by youshaoduo** [comment]
@magaofei 
<img width="201" alt="1" src="https://user-images.githubusercontent.com/14846965/45083819-4ee4d900-b12f-11e8-8a5b-58cae4fcf79c.png">

**Comment by youshaoduo** [comment]
<img width="200" alt="1" src="https://user-images.githubusercontent.com/14846965/45084054-e4806880-b12f-11e8-91f5-c793eacd10f5.png">
![2](https://user-images.githubusercontent.com/14846965/45084056-e5b19580-b12f-11e8-95f8-8a5de7c4b699.png)
@magaofei

**Comment by magaofei** [comment]
@ajinabraham I think this is a problem with plistlib. Third-party library biplist will solve this problem
