### ISSUE TITLE
Html Report Enhancement and reducing Detection Noise level

### ISSUE THREAD

**Issue by shivasurya** [MobSF/Mobile-Security-Framework-MobSF#717]
## Third-party services similar to Firebase, Push SDK, Analytics service and Broadcast Receiver blacklist

Feature Request

1.  Can we blacklist/ or have the separate section in reports/HTML page for the third party services class Google Analytics, Push SDK, firebase sdk service and receivers? This can reduce much **noise** in the actual application components report

2. Can we identify exported activities or it's the base activity ( as a link in the HTML report ) that uses getIntent() method to accept values that can cause vulnerability 

3. Can we check the Components custom permission classified as Signature level or normal mode?

4. Can we mark the Content Provider component vulnerable if the exported attribute isn't present? for API level <=16, it's really mandatory one.

These are more such suggestions after analyzing around 100+ apps. Please let me know if you have any questions. We can have constructive comments to make the analysis to bring more relevant results

Regards,
Shivasurya S,
hackerone.com/shivasurya

**Comment by ajinabraham** [comment]
1. You can blacklist out of scope items: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L256
2. There is multiple ways to export an activity, not all exported activities are bad. So it's up to the analyst to use the search function and discover more info from code base.
3. What do you mean? please briefly explain
4. Any documented references for this?
