### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by zseha** [MobSF/Mobile-Security-Framework-MobSF#726]
I have asked in slack but got no answer. 
I would like to perform static analysis on xamarin apps same way its done to java classes in android.
Do you know if anyone has done anything in this direction already, as i would like not to duplicate the code.

**Comment by ajinabraham** [comment]
Currently we don't do anything form xaramin perspective.

**Comment by Techbrunch** [comment]
FYI:

.dll files can be decompiled using [ILSpy](https://github.com/icsharpcode/ILSpy)

You might need to decompress them before: [Decompressing Xamarin DLLs](https://www.x41-dsec.de/security/news/working/research/2020/09/22/xamarin-dll-decompression/)

Another cool project for Xamarin apps: https://github.com/NorthwaveSecurity/fridax
