### ISSUE TITLE
Virtual Machine Connection Problem

### ISSUE THREAD

**Issue by asharif1990** [MobSF/Mobile-Security-Framework-MobSF#728]
Hi, 

I have a problem during dynamic analysis. I follow the instructions in the wiki page and when I start the dynamic analysis it connected to my virtual machine and try to do the tests. I attached the log as well that prove the fact that it starts the analysis. 

[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF VM
[ERROR] VirtualBox not found, Manually set VBOXMANAGE_BINARY in settings.py

[2018-09-14 09:31:13]
[ERROR] Refreshing MobSF VM (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/virtualbox_vm.py, LINE 14 "subprocess.call(args)"): expected str, bytes or os.PathLike object, not NoneType
[14/Sep/2018 09:31:13] "POST /DynamicAnalyzer/ HTTP/1.1" 200 32588
[14/Sep/2018 09:31:13] "GET /download/screen/screen.png HTTP/1.1" 302 0
[14/Sep/2018 09:31:13] "GET /error/ HTTP/1.1" 200 4750

[INFO] Setting up Dynamic Analysis Environment

[INFO] Connecting to VM/Device
* server not running *
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Capture Module Loaded
Proxy server listening at http://*:1337

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device

[INFO] Mounting

[INFO] Starting App for Dynamic Analysis

[INFO] Installing APK

[INFO] Launching APK Main Activity
[INFO] Testing Environment is Ready!

[INFO] Getting Screen Resolution
[14/Sep/2018 09:31:26] "POST /GetEnv/ HTTP/1.1" 200 66

[INFO] Starting Clipboard Dump Service in VM/Device

[INFO] Installing MobSF RootCA
[14/Sep/2018 09:31:27] "POST /MobSFCA/ HTTP/1.1" 200 19
[14/Sep/2018 09:31:27] "POST /ClipDump/ HTTP/1.1" 200 21

[INFO] Activity Tester

[INFO] Fetching Activity List from DB

the issue is that, that the VM didn't connect to the internet anymore after I set the proxy inside it, therefore it can not do the test in correct way. I would like to ask, How can I solve this issue?

**Comment by ajinabraham** [comment]
Read the errors carefully!

`[ERROR] VirtualBox not found, Manually set VBOXMANAGE_BINARY in settings.py`
