### ISSUE TITLE
ERROR Oracle JDK 1.7 or above is not found

### ISSUE THREAD

**Issue by Andrian13** [MobSF/Mobile-Security-Framework-MobSF#729]
Hi,

I have a problem during starting MobSF,since i've upgraded my linux to 2018.3 i can't running MobSF. It said "[Error] Oracle JDK 1.7 or above is not found" but when i checked my jdk version it's said is already the newest version (openjdk version "10.0.2" 2018-07-17) 
the issue is that, I would like to ask, How can I solve this issue?

**Comment by ajinabraham** [comment]
Set Java Path in settings.py if MobSF is unable to find Java path.
