### ISSUE TITLE
how to auto update project？

### ISSUE THREAD

**Issue by safebaseline** [MobSF/Mobile-Security-Framework-MobSF#730]
how to auto update project？

**Comment by magaofei** [comment]
please take more information.
what the platform ?

**Comment by safebaseline** [comment]
windows


798942836@qq.com
 
发件人： magaofei
发送时间： 2018-09-17 11:46
收件人： MobSF/Mobile-Security-Framework-MobSF
抄送： safebaseline; Author
主题： Re: [MobSF/Mobile-Security-Framework-MobSF] how to auto update project？ (#730)
please take more information.
what the platform ?

**Comment by magaofei** [comment]
@safebaseline 
try to this
```
git pull origin master
pip install -r requirements.txt	

```

**Comment by safebaseline** [comment]
ok i will try
