### ISSUE TITLE
get better report in mobsf

### ISSUE THREAD

**Issue by Und3rCover96** [MobSF/Mobile-Security-Framework-MobSF#734]
hi its pretty cool tools for android penetration testing but the weakness is the report export is very bad and it's not have a good style and its lazy please fix it

**Comment by superpoussin22** [comment]
Would you have an idea to improve it ?

**Comment by ajinabraham** [comment]
This is something we can get help from the community to improve

**Comment by ajinabraham** [comment]
Closing this as we have an enhancement already to track this
