### ISSUE TITLE
About Headless mode in Android x86 (OVA)

### ISSUE THREAD

**Issue by anhkhoa14592** [MobSF/Mobile-Security-Framework-MobSF#739]
Hi 

At the moment Mobsf does not support Headless mode in virtualbox. I think this is a important feature in Virtualbox helping who needs run Mobsf as a services. I hope Mobsf develope team will consider and add this option in settings configuration file next time.

I've searched and found out we can run as Headless mode by adding **--type headless** in `Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/virtualbox_vm.py`
** Original - Run as GUI **
`        args = [vbox_exe, 'startvm', uuid] `
** Edited - Run as Headless **
`        args = [vbox_exe, 'startvm', uuid, '--type', 'headless'] `

**Comment by ajinabraham** [comment]
Added to master
