### ISSUE TITLE
enhancement - Diff between static results

### ISSUE THREAD

**Issue by matandobr** [MobSF/Mobile-Security-Framework-MobSF#742]
This is how I see it, @ajinabraham feel free to comment :

- add a "diff" button to the recent_scans page which will open some kind of way to mark 2 scans (like checkbox or some cool bootstrap things)
- make a diff analysis and save the result
- make a new view that compares 2 apps, with the result from the analysis
- make a toggle or something like that for the diff results inside the recent_scans page 

things I'm afraid of - only the code comparison, different decompiler, and how difficult it will be to show the changes of modified source files...

wish me luck ;)

**Comment by ajinabraham** [comment]
Probably permission diff and finding diff is easier. File diff, let's not do that.

**Comment by matandobr** [comment]
Lets start with the basics and we'll keep going frpm there
