### ISSUE TITLE
Do you have authentication for MobSF?

### ISSUE THREAD

**Issue by harman-sunnysun** [MobSF/Mobile-Security-Framework-MobSF#748]
## EXPLANATION OF THE ISSUE
I'd like the end user to login the system first, then do some uploads. Do you have this feature now? if yes, how to config it? thanks a lot.

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by magaofei** [comment]
Not support this.
should we add this feature to take advantage of Django ADMIN? @ajinabraham

**Comment by harman-sunnysun** [comment]
@magaofei  thanks for your feedback, I'm using Nginx basic auth as a workaround.

**Comment by secureITmania** [comment]
Refer to the below link for the tutorial to setup Basic Authentication
https://secureitmania.medium.com/secure-docker-instance-with-basic-authentication-d81fc39fec37

**Comment by ajinabraham** [comment]
We do now from MobSF v4.0 onwards
