### ISSUE TITLE
The API code coupling between pdf and report_json is too high

### ISSUE THREAD

**Issue by magaofei** [MobSF/Mobile-Security-Framework-MobSF#753]
The API code coupling between pdf and report_json is too high. For example, report_json does not require wkhtmltopdf, but it must be installed. In the source code, these two APIs point to the same method.

**Comment by ajinabraham** [comment]
Can be easily done by moving the `wkhtmltopdf` import I guess.

**Comment by ajinabraham** [comment]
This is fixed. Reopen if not.
