### ISSUE TITLE
Don't Play Around. An Error just popped in! -Inappropriate argument type.

### ISSUE THREAD

**Issue by jeancsm1** [MobSF/Mobile-Security-Framework-MobSF#758]
I'm new with this Project, and I'm using MobSf to analyze an IOS application, this is the error:

- Inappropriate argument type.
- 'NoneType'
- object is not iterable

## CONSOLE OUTPUT

```
Mobile Security Framework v1.0.2 Beta

REST API Key: 
OS: Linux
Platform: Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Dist: ('Kali', 'kali-rolling', 'kali-rolling')
[INFO] Finding JDK Location in Linux/MAC....
[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
System check identified some issues:

WARNINGS:
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.

System check identified 1 issue (0 silenced).
October 29, 2018 - 22:38:21
Django version 1.11.7, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[29/Oct/2018 22:38:27] "GET / HTTP/1.1" 200 7727
[INFO] MIME Type: application/octet-stream FILE: krelease.ipa

[INFO] Performing Static Analysis of iOS IPA
[29/Oct/2018 22:38:32] "POST /upload/ HTTP/1.1" 200 213
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping
[INFO] Get Files, BIN Plist -> XML, and Normalize

[2018-10-29 22:38:32]
[ERROR] iOS List Files (/root/Desktop/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios/static_analyzer.py, LINE 92 "convert_bin_xml(file_path)"): Invalid file
[ERROR] 'NoneType' object is not iterable
[29/Oct/2018 22:38:32] "GET /StaticAnalyzer_iOS/?name=KRelease.ipa&type=ipa&checksum=78f972431299cc75a6a1707b174c3956 HTTP/1.1" 500 4819

```Can you help me, I appreciate your help please, thanks.

**Comment by magaofei** [comment]
Can you copy the latest code and execute it?

**Comment by ajinabraham** [comment]
Also please upgrade your requirements to latest. We are using `Django 2.1.2`

**Comment by ajinabraham** [comment]
If you still see issue, please share the IPA

**Comment by jeancsm1** [comment]
> Thank you for your question, Can you copy the latest code and execute it?

# -*- coding: utf_8 -*-
"""
iOS Static Code Analysis
"""
import re
import os
import io
import shutil


from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.conf import settings
from django.utils.html import escape



from StaticAnalyzer.views.ios.db_interaction import (

    get_context_from_analysis_ipa,

    get_context_from_db_entry_ipa,

    update_db_entry_ipa,

    create_db_entry_ipa,



    get_context_from_analysis_ios,

    get_context_from_db_entry_ios,

    update_db_entry_ios,

    create_db_entry_ios,

)





from StaticAnalyzer.views.ios.binary_analysis import (

    binary_analysis,

)

from StaticAnalyzer.views.ios.code_analysis import (

    ios_source_analysis,

)



from StaticAnalyzer.views.ios.plist_analysis import (

    plist_analysis,

    convert_bin_xml

)





from StaticAnalyzer.views.shared_func import (

    file_size,

    hash_gen,

    unzip

)

from StaticAnalyzer.models import StaticAnalyzerIPA, StaticAnalyzerIOSZIP



from MobSF.utils import (

    print_n_send_error_response,

    PrintException,

    isFileExists

)



import StaticAnalyzer.views.android.VirusTotal as VirusTotal



##############################################################

# Code to support iOS Static Code Analysis

##############################################################





def ios_list_files(src, md5_hash, binary_form, mode):

    """List iOS files"""

    try:

        print("[INFO] Get Files, BIN Plist -> XML, and Normalize")

        # Multi function, Get Files, BIN Plist -> XML, normalize + to x

        filez = []

        certz = []

        sfiles = []

        database = []

        plist = []

        for dirname, _, files in os.walk(src):

            for jfile in files:

                if not jfile.endswith(".DS_Store"):

                    file_path = os.path.join(src, dirname, jfile)

                    if "+" in jfile:

                        plus2x = os.path.join(

                            src, dirname, jfile.replace("+", "x"))

                        shutil.move(file_path, plus2x)

                        file_path = plus2x

                    fileparam = file_path.replace(src, '')

                    filez.append(fileparam)

                    ext = jfile.split('.')[-1]

                    if re.search("cer|pem|cert|crt|pub|key|pfx|p12", ext):

                        certz.append(escape(file_path.replace(src, '')))

                    if re.search("db|sqlitedb|sqlite", ext):

                        database.append("<a href='../ViewFile/?file=" + \

                            escape(fileparam) + "&type=" + mode + "&md5=" + \

                            md5_hash + "''> " + \

                            escape(fileparam) + " </a>")

                    if jfile.endswith(".plist"):

                        if binary_form:

                            convert_bin_xml(file_path)

                        plist.append("<a href='../ViewFile/?file=" + \

                            escape(fileparam) + "&type=" + mode + "&md5=" + \

                            md5_hash + "''> " + \

                            escape(fileparam) + " </a>")

        if len(database) > 0:

            sfiles.append({ "issue": "SQLite Files", "files": database })

        if len(plist) > 0:

            sfiles.append({ "issue": "Plist Files", "files": plist })

        if len(certz) > 0:

            sfiles.append({ "issue": "Certificate/Key Files Hardcoded inside the App.", "files": certz })

        return filez, sfiles

    except:

        PrintException("[ERROR] iOS List Files")





def static_analyzer_ios(request, api=False):

    """Module that performs iOS IPA/ZIP Static Analysis"""

    try:

        print("[INFO] iOS Static Analysis Started")

        if api:

            file_type = request.POST['scan_type']

            checksum = request.POST['hash']

            rescan = str(request.POST.get('re_scan', 0))

            filename = request.POST['file_name']

        else:

            file_type = request.GET['type']

            checksum = request.GET['checksum']

            rescan = str(request.GET.get('rescan', 0))

            filename = request.GET['name']



        md5_match = re.match('^[0-9a-f]{32}$', checksum)

        if ((md5_match) and

                    (filename.lower().endswith('.ipa') or

                     filename.lower().endswith('.zip')

                     ) and

                    (file_type in ['ipa', 'ios'])

                ):

            app_dict = {}

            app_dict["directory"] = settings.BASE_DIR  # BASE DIR

            app_dict["file_name"] = filename  # APP ORGINAL NAME

            app_dict["md5_hash"] = checksum  # MD5

            app_dict["app_dir"] = os.path.join(

                settings.UPLD_DIR, app_dict["md5_hash"] + '/')  # APP DIRECTORY

            tools_dir = os.path.join(

                app_dict["directory"], 'StaticAnalyzer/tools/mac/')  # TOOLS DIR

            if file_type == 'ipa':

                # DB

                ipa_db = StaticAnalyzerIPA.objects.filter(

                    MD5=app_dict["md5_hash"])

                if ipa_db.exists() and rescan == '0':

                    context = get_context_from_db_entry_ipa(ipa_db)

                else:

                    print("[INFO] iOS Binary (IPA) Analysis Started")

                    app_dict["app_file"] = app_dict[

                        "md5_hash"] + '.ipa'  # NEW FILENAME

                    app_dict["app_path"] = app_dict["app_dir"] + \

                        app_dict["app_file"]  # APP PATH

                    app_dict["bin_dir"] = os.path.join(

                        app_dict["app_dir"], "Payload/")

                    app_dict["size"] = str(

                        file_size(app_dict["app_path"])) + 'MB'  # FILE SIZE

                    app_dict["sha1"], app_dict["sha256"] = hash_gen(

                        app_dict["app_path"])  # SHA1 & SHA256 HASHES

                    print("[INFO] Extracting IPA")

                    # EXTRACT IPA

                    unzip(app_dict["app_path"], app_dict["app_dir"])

                    # Get Files, normalize + to x,

                    # and convert binary plist -> xml

                    files, sfiles = ios_list_files(

                        app_dict["bin_dir"], app_dict["md5_hash"], True, 'ipa')

                    infoplist_dict = plist_analysis(app_dict["bin_dir"], False)

                    bin_analysis_dict = binary_analysis(

                        app_dict["bin_dir"], tools_dir, app_dict["app_dir"], infoplist_dict.get("bin"))

                    # Saving to DB

                    print("\n[INFO] Connecting to DB")

                    if rescan == '1':

                        print("\n[INFO] Updating Database...")

                        update_db_entry_ipa(

                            app_dict, infoplist_dict, bin_analysis_dict, files, sfiles)

                    elif rescan == '0':

                        print("\n[INFO] Saving to Database")

                        create_db_entry_ipa(

                            app_dict, infoplist_dict, bin_analysis_dict, files, sfiles)

                    context = get_context_from_analysis_ipa(

                        app_dict, infoplist_dict, bin_analysis_dict, files, sfiles)



                context['VT_RESULT'] = None

                if settings.VT_ENABLED:

                    vt = VirusTotal.VirusTotal()

                    context['VT_RESULT'] = vt.get_result(

                        os.path.join(app_dict['app_dir'], app_dict[

                                     'md5_hash']) + '.ipa',

                        app_dict['md5_hash']

                    )



                template = "static_analysis/ios_binary_analysis.html"

                if api:

                    return context

                else:

                    return render(request, template, context)

            elif file_type == 'ios':

                ios_zip_db = StaticAnalyzerIOSZIP.objects.filter(

                    MD5=app_dict["md5_hash"])

                if ios_zip_db.exists() and rescan == '0':

                    context = get_context_from_db_entry_ios(ios_zip_db)

                else:

                    print("[INFO] iOS Source Code Analysis Started")

                    app_dict["app_file"] = app_dict[

                        "md5_hash"] + '.zip'  # NEW FILENAME

                    app_dict["app_path"] = app_dict["app_dir"] + \

                        app_dict["app_file"]  # APP PATH

                    # ANALYSIS BEGINS - Already Unzipped

                    print("[INFO] ZIP Already Extracted")

                    app_dict["size"] = str(

                        file_size(app_dict["app_path"])) + 'MB'  # FILE SIZE

                    app_dict["sha1"], app_dict["sha256"] = hash_gen(

                        app_dict["app_path"])  # SHA1 & SHA256 HASHES

                    files, sfiles = ios_list_files(

                        app_dict["app_dir"], app_dict["md5_hash"], False, 'ios')

                    infoplist_dict = plist_analysis(app_dict["app_dir"], True)

                    code_analysis_dic = ios_source_analysis(

                        app_dict["app_dir"])

                    # Saving to DB

                    print("\n[INFO] Connecting to DB")

                    if rescan == '1':

                        print("\n[INFO] Updating Database...")

                        update_db_entry_ios(

                            app_dict, infoplist_dict, code_analysis_dic, files, sfiles)

                    elif rescan == '0':

                        print("\n[INFO] Saving to Database")

                        create_db_entry_ios(

                            app_dict, infoplist_dict, code_analysis_dic, files, sfiles)

                    context = get_context_from_analysis_ios(

                        app_dict, infoplist_dict, code_analysis_dic, files, sfiles)

                template = "static_analysis/ios_source_analysis.html"

                if api:

                    return context

                else:

                    return render(request, template, context)

            else:

                msg = "File Type not supported!"

                if api:

                    return print_n_send_error_response(request, msg, True)

                else:

                    return print_n_send_error_response(request, msg, False)

        else:

            msg = "Hash match failed or Invalid file extension or file type"

            if api:

                return print_n_send_error_response(request, msg, True)

            else:

                return print_n_send_error_response(request, msg, False)

    except Exception as exp:

        msg = str(exp)

        exp_doc = exp.__doc__

        if api:

            return print_n_send_error_response(request, msg, True, exp_doc)

        else:

            return print_n_send_error_response(request, msg, False, exp_doc)

**Comment by jeancsm1** [comment]
> If you still see issue, please share the IPA

Thanks for your support "ajinabraham"  I'm going to update to Django 2.1.2

**Comment by ajinabraham** [comment]
@jeancsm1 not to copy paste the code here. But update your code to the latest.
`git pull origin master`
Also go to scripts and run. /clean.sh once.
Warning this will remove your previous scan results.

**Comment by jeancsm1** [comment]
Hi ajinabraham, I did it, but the error continue: 

[ERROR] ios List Files (/root/Escritorio/Mobiles-Security-Framework-MobSf master/StaticAnalyzer/views/ios/static_analyzer.py, LINE 92 "Cconver_bin_xml(file_path)"): Invalid file
[ERROR] ´NoneType´ object is not interable.

Please, I need your support, Thanks.

**Comment by magaofei** [comment]
@jeancsm1 Could you share your ipa file ?

**Comment by jeancsm1** [comment]
This issue is was resolved, I modified a line in the static_analyzer .py file and it runs, I modified the path: convert_bin_xml(file_path), thanks

**Comment by magaofei** [comment]
@jeancsm1 Can you submit the modified code to a pull request?

**Comment by jeancsm1** [comment]
Line 91 or 92 of the "static_analyzer.py" file, you must to modifie the path depending of the location of you ios List file.
