### ISSUE TITLE
PDF Report Size

### ISSUE THREAD

**Issue by ali0818** [MobSF/Mobile-Security-Framework-MobSF#759]
While generating the PDF report, there is some issue with the size. 

![image](https://user-images.githubusercontent.com/17707955/47712239-2f64bb00-dc5d-11e8-8380-17670bbf923f.png)
I am using OS X

**Comment by magaofei** [comment]
I don't know what means
There are still pictures that are not clear, too blurred.

**Comment by ajinabraham** [comment]
This is a limitation of the pdf generation we use at the moment. We have an enhancement to track migration to a different library
