### ISSUE TITLE
Don't Play Around. An Error just popped in!

### ISSUE THREAD

**Issue by solidmonster** [MobSF/Mobile-Security-Framework-MobSF#763]
I received the following error: Don't Play Around. An Error just popped in! 'NoneType' object is not iterable. This occurs when I am trying to analyze an IPA file. 

PS: I'm using docker instance.

See error log below:

[INFO] Performing Static Analysis of iOS IPA
[02/Nov/2018 09:12:22] "POST /upload/ HTTP/1.1" 200 188
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping
[INFO] Get Files, BIN Plist -> XML, and Normalize

[2018-11-02 09:12:23]
[ERROR] iOS List Files (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py, LINE 193 "convert_bin_xml(file_path)"): Invalid file
[ERROR] 'NoneType' object is not iterable
Internal Server Error: /StaticAnalyzer_iOS/
2018-11-02 09:12:23 ERROR    Internal Server Error: /StaticAnalyzer_iOS/

**Comment by solidmonster** [comment]
App is still not public, will check and get back to you.

**Comment by magaofei** [comment]
Can you take a picture of the project directory?

**Comment by ajinabraham** [comment]
We have tested multiple IPAs in Dockerized MobSF and it works fine. We can't work on this issue until we get an IPA to reproduce this. Hence closing. Feel free to comment with update or useful info that can help us to reproduce this issue.
