### ISSUE TITLE
Wrong page rendering during running MobSF windows server

### ISSUE THREAD

**Issue by mariusz1987** [MobSF/Mobile-Security-Framework-MobSF#765]
Hi,

During running server the web page not properly rendering (almost white without any pictures). Probably it is caused by something like this(log from server console) :: **django.core.exceptions.SuspiciousFileOperation: The joined path (D:\s\d\ay\G\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\static\img\MobSF_Logo_small.png) is located outside of the base path component (D:\s\d\a\G\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\static\)**

What should I do?

**Comment by ajinabraham** [comment]
See: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/752

**Comment by sundaramRNT** [comment]
Downloaded from https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
After installation, executed setup.bat . Then executed run.bat in windows 10 environment.
when tried in the browser using "http://localhost:8000
throwing error message "The content of the page cannot be displayed"

Please help to resolve.
