### ISSUE TITLE
"Don't Play Around. An Error just popped in!" if one of the many plist files is in JSON format.

### ISSUE THREAD

**Issue by patcheng** [MobSF/Mobile-Security-Framework-MobSF#770]
I am using the docker image.

I received the following error: `Don't Play Around. An Error just popped in! 'NoneType' object is not iterable`. This occurs when I am trying to analyze an IPA file.

In the console log it shows:
```
[ERROR] iOS List Files (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py, LINE 193 "convert_bin_xml(file_path)"): Invalid file
[ERROR] 'NoneType' object is not iterable
```

I was able to modify the MobSF code to get more detail.

In our IPA, we have a file: `Payload/XXXX.app/XXX/XXX.xxx/XXXX.plist`

The plist file is actually in the less-known JSON format. 

biplist.readPlist will throw exception because it's throwing `biplist.InvalidPlistException`.

If I modified `Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/plist_analysis.py` to catch and ignore the exception like:
```
def convert_bin_xml(bin_xml_file):
    """Convert Binary XML to Readable XML"""
    try:
      plist_obj = readPlist(bin_xml_file)
      data = writePlistToString(plist_obj)
      return data
    except biplist.InvalidPlistException:
      PrintException("[ERROR] - Failed to convert")
```

The rest of the analyze would continue.

I tried to create a sample IPA, but I was not able to reproduce the issue.

**Comment by ajinabraham** [comment]
Hi, We need a sample to replicate this issue.

**Comment by patcheng** [comment]
I was able to create a sample project: https://github.com/patcheng/MobSFTest

This is the file format that is causing issue: 
https://github.com/patcheng/MobSFTest/blob/master/Test/Test.pack/Test.plist

**Comment by patcheng** [comment]
For those needing a workaround until the issue is resolved:

I ran docker with '-name' option, so I can use the name later
```
docker rm mobsf
docker run --name mobsf -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
```

in a different window,
```
docker exec -i -t mobsf /bin/bash
apt-get update
apt-get install -y nano

nano /root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/plist_analysis.py
```

look for the function `convert_bin_xml(bin_xml_file)`
and replace the function with: 

```
def convert_bin_xml(bin_xml_file):
    """Convert Binary XML to Readable XML"""
    try:
      plist_obj = readPlist(bin_xml_file)
      data = writePlistToString(plist_obj)
      return data
    except biplist.InvalidPlistException:
      PrintException("[ERROR] - Failed to convert")
```

Save the file. Now the scan will continue.

**Comment by ajinabraham** [comment]
Is this from an IPA? It would be great if you can provide the IPA with Plist in this format

**Comment by patcheng** [comment]
[Archive.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/2567385/Archive.zip)

Here is a "IPA" file I generated manually by zipping a Payload folder with the offending folder structure and content.

It's not a valid file, so after fixing the error, you will see some other error.

**Comment by ajinabraham** [comment]
@patcheng The Archive doesn't contain a valid IPA. MobSF needs a valid IPA.
I was able to reproduce it with the github src.

**Comment by ajinabraham** [comment]
@magaofei This is a sample that cause issue in reading plist of json format.
To reproduce, do analysis the below zip -> Go to file analysis and try to view the plist files. 

I remember raising a concern about using bplist before. This sample will cause an error
`Raised when the plist is incorrectly formatted.`
We need a fallback to read such files if bplist fails, like a normal file read. 
[bplist_issue.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/2692200/bplist_issue.zip)

**Comment by patcheng** [comment]
Actually, it's not a real JSON format.

I found this repo has some other plist samples:

https://github.com/3breadt/dd-plist/tree/master/test-files

**Comment by sanjayrk** [comment]
Thank you so much @patcheng for posting the solution 👍

**Comment by kj0317** [comment]
@patcheng solution also worked for me and allowed me to analyze an ipa that wasn't cooperating.

**Comment by superpoussin22** [comment]
@kj0317 can you share the ipa ?

**Comment by stonedauwg** [comment]
This issue went away for me by getting the latest from beta 1.0.6 to beta 1.0.7

**Comment by superpoussin22** [comment]
Thanks. closed
