### ISSUE TITLE
Dynamic Analysis on Real device android version 7

### ISSUE THREAD

**Issue by sali123** [MobSF/Mobile-Security-Framework-MobSF#771]
Can I run dynamic analysis on real device Samsung S6 with Android 7. I am asking this because my device is not rooted. I don't want to root it then discover that it is not working.

**Comment by ajinabraham** [comment]
Dynamic analysis can work on rooted android device that support Xposed Framework

**Comment by ajinabraham** [comment]
This is for bug reports only use slack channel for questions and discussions
