### ISSUE TITLE
I can not use Dynamic Analyzer ?

### ISSUE THREAD

**Issue by Andrian13** [MobSF/Mobile-Security-Framework-MobSF#777]
## EXPLANATION OF THE ISSUE

i have some problems while trying Dynamic Analysis, i've tried just like what it's stated on "how to Configuring Dynamic Analyzer with MobSF Android 4.4.2 x86 VirtualBox VM" page. i've already got the UUID, SUUID, VMIP, PROXY IP. But i got some error when i clicked "create environment" it's said i have some error in "mobsf/DynamicAnlyzer/tools/adb/linux/adb" and the error in terminal just like :
192.168.56.1:33560 clientconnected
192.168.56.1:33560 clientdisconnected
192.168.56.1:33562 clientconnected
192.168.56.1:33562 clientdisconnected
192.168.56.1:33564 clientconnected
192.168.56.1:33564 clientdisconnected
and so on. i've tried to ping the PROXY IP, and the IP is fine it's still replying.
Can you help me what i have to do to fix the problems ?
Thanks

**Comment by ajinabraham** [comment]
Use slack channel for support
