### ISSUE TITLE
Integrate virustotal API to get Hash report

### ISSUE THREAD

**Issue by javixeneize** [MobSF/Mobile-Security-Framework-MobSF#779]
Hi

I think it would be a good idea to integrate virustotal API with MobSF to scan the hash of the application and display the results in the main dashboard

Do you think it would be useful? If so, i can do a merge request with this addition

Thanks

**Comment by ajinabraham** [comment]
Have you read the documentation?

VirtusTotal API is already integrated in MobSF
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#virustotal

**Comment by javixeneize** [comment]
Hi Ajin

Yes, but it will need an user to add its key. What i mean is to automatically display the virustotal result in the dashboard

**Comment by ajinabraham** [comment]
VirusTotal free API key has limitations on the no of requests and other thresholds. Hence we cannot ship MobSF with one. The user has to generate one and configure MobSF to use that.
