### ISSUE TITLE
[Error]Uploading apk file

### ISSUE THREAD

**Issue by mariusz1987** [MobSF/Mobile-Security-Framework-MobSF#784]
Hi,

After uploading .apk file I got error `LINE19 "if not db_obj.exists():"): no such table:StaticAnalyzer_recentscansdb` How to improve this?

**Comment by magaofei** [comment]
`python manage.py migrate StaticAnalysis`

**Comment by mariusz1987** [comment]
Unfortunately, it still does not work. @magaofei Run this comand finally I got: CommandError: App 'StaticAnalysis' does not have mgration. @ajinabraham After tun command python manage.py migrate error still exists.

**Comment by ajinabraham** [comment]
Please follow MobSF documentation.
```
cd scripts
./clean.sh
cd ..
./setup.sh
./run.sh
```
