### ISSUE TITLE
Report generation error

### ISSUE THREAD

**Issue by mohsin2928** [MobSF/Mobile-Security-Framework-MobSF#785]
hi, while generating the report I get the following error, need your support on this, appreciate  your response
![screenshot from 2018-11-22 11-13-00](https://user-images.githubusercontent.com/44868349/48890027-b1a16300-ee48-11e8-9122-84dbfd5a0455.png)
![bool](https://user-images.githubusercontent.com/44868349/48890033-b49c5380-ee48-11e8-91e2-5f47d52d90a6.JPG)

**Comment by ajinabraham** [comment]
Do bug reports properly with enough details

**Comment by mohsin2928** [comment]
what more details do you require, i am just uploading an simple application and trying to generate a report

**Comment by ajinabraham** [comment]
Read the gudline to report bugs
