### ISSUE TITLE
Not processing ADB error properly

### ISSUE THREAD

**Issue by Redict** [MobSF/Mobile-Security-Framework-MobSF#787]
You can take any file that have additional lib with ARM aarch64, try to do a dynamic analysis it on VM and nothing will happen, but when you  try to run it through adb manually:
`adb install -r apk`
It shows up:
`Failure [INSTALL_FAILED_CPU_ABI_INCOMPATIBLE]`

**Comment by ajinabraham** [comment]
VM is x86. Doesn't support ARM apks at the first place
