### ISSUE TITLE
Cert Parser Fails inside Docker

### ISSUE THREAD

**Issue by MartinRJ** [MobSF/Mobile-Security-Framework-MobSF#789]
## EXPLANATION OF THE ISSUE

I just downloaded the latest Docker version (2018-11-27) to reproduce the error I found.

I get this message when I try to analyze a specific apk. The ipa- version of the same app works fine.
> Don't Play Around. An Error just popped in!
> Inappropriate argument type.
> 
> 'NoneType' object does not support item assignment

`[2018-11-27 09:52:42]
[ERROR] Reading Code Signing Certificate (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 65 "dat = subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/Users/martinfurholz/MobSF/StaticAnalyzer/tools/CertPrint.jar', '/Users/martinfurholz/MobSF/uploads/1cede86d5ee2833204448a5d6831fed8/META-INF/1.RSA']' returned non-zero exit status 1.`

## CONTENTS OF LOG FILES

`[2018-11-27 09:49:28]
[ERROR] Reading Code Signing Certificate (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 65 "dat = subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/Users/martinfurholz/MobSF/StaticAnalyzer/tools/CertPrint.jar', '/Users/martinfurholz/MobSF/uploads/1cede86d5ee2833204448a5d6831fed8/META-INF/1.RSA']' returned non-zero exit status 1.
[2018-11-27 09:50:37]
[ERROR] Saving to DB (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[2018-11-27 09:50:37]
[ERROR] Rendering to Template (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[2018-11-27 09:50:37]
[ERROR] 'NoneType' object does not support item assignment
[2018-11-27 09:52:42]
[ERROR] Reading Code Signing Certificate (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 65 "dat = subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/Users/martinfurholz/MobSF/StaticAnalyzer/tools/CertPrint.jar', '/Users/martinfurholz/MobSF/uploads/1cede86d5ee2833204448a5d6831fed8/META-INF/1.RSA']' returned non-zero exit status 1.
[2018-11-27 09:53:50]
[ERROR] Saving to DB (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[2018-11-27 09:53:50]
[ERROR] Rendering to Template (/Users/martinfurholz/MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[2018-11-27 09:53:50]
[ERROR] 'NoneType' object does not support item assignment`

**Comment by ajinabraham** [comment]
APK is provided  in PM. Looking into this

**Comment by ajinabraham** [comment]
The APK works fine locally, but fails inside Docker. Probably something to do with Java.

**Comment by ajinabraham** [comment]
@superpoussin22  The APK is confidential. I will share the problematic certificate file in Slack. 

Strangely it works fine on my Mac with an older version of Java. But fails on my Ubuntu 18 box with latest Java. Even Java's on keytool fails. 

```
keytool -printcert -file uploads/.../META-INF/1.RSA
```
Works on Mac but fails on Ubuntu with latest Oracle JDK

**Comment by ajinabraham** [comment]
The exception I am getting on Windows 10 and Ubuntu
```
[INFO] Reading Code Signing Certificate
Exception in thread "main" java.security.cert.CertificateException: Unable to initialize, java.io.IOException: Short read of DER length
       at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:198)
       at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:471)
       at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
       at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:478)
       at Cert.main(Cert.java:16)
Caused by: java.io.IOException: Short read of DER length
       at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:588)
       at java.base/sun.security.util.DerValue.<init>(DerValue.java:257)
       at java.base/sun.security.util.DerInputStream.getDerValue(DerInputStream.java:457)
       at java.base/sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1834)
       at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
       ... 4 more

[2018-11-29 09:26:42]
```

Win 10 (Fails)
```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
OS Mojave (Works)
```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by ajinabraham** [comment]
@superpoussin22  Can we use Androguard for certificate extraction. This is still failing in Ubuntu 18, Java 11 Docker container.

**Comment by superpoussin22** [comment]
will check

**Comment by MartinRJ** [comment]
openssl works fine:
`openssl pkcs7 -inform DER -in 1.RSA -noout -print_certs -text`

**Comment by ajinabraham** [comment]
It's an issue with Java, not the cert file.

**Comment by superpoussin22** [comment]
@ajinabraham  yep 
someting like that : 
`from androguard.core.bytecodes.apk import APK
a = APK('examples/signing/apksig/golden-aligned-v1v2-out.apk')
# first check if this APK is signed
print("APK is signed: {}".format(a.is_signed()))
if a.is_signed():
# Test if signed v1 or v2 or both
print("APK is signed with: {}".format("both" if a.is_signed_v1() and
a.is_signed_v2() else "v1" if a.is_signed_v1() else "v2"))
# Iterate over all certificates
for cert in a.get_certificates():
# Each cert is now a asn1crypt.x509.Certificate object
# From the Certificate object, we can query stuff like:
cert.sha1 # the sha1 fingerprint
cert.sha256 # the sha256 fingerprint
cert.issuer.human_friendly # issuer
cert.subject.human_friendly # subject, usually the same
cert.hash_algo # hash algorithm
cert.signature_algo # Signature algorithm
cert.serial_number # Serial number
cert.contents # The DER coded bytes of the certificate itself`

**Comment by MartinRJ** [comment]
> It's an issue with Java, not the cert file.
I know. I suggested to use openssl instead of what was previously used to check the certificate.
Call with:
`openssl pkcs7 -inform DER -in [/path/filename.RSA] -noout -print_certs -text`
