### ISSUE TITLE
Update OpenSSL Setup download links in Setup.bat and Setup.sh

### ISSUE THREAD

**Issue by AnimeshShaw** [MobSF/Mobile-Security-Framework-MobSF#790]
In  the current version of the setup the OpenSSL setup link mentioned gives HTTP 404. Kindly update the links in both setup.sh and setup.bat to the following:

https://slproweb.com/download/Win64OpenSSL-1_1_1a.exe

I have tested the above and it works on windows properly.

**Comment by superpoussin22** [comment]
good catch , will update
