### ISSUE TITLE
Documentation: IPA analysis not supported on linux

### ISSUE THREAD

**Issue by noraj** [MobSF/Mobile-Security-Framework-MobSF#798]
## EXPLANATION OF THE ISSUE

This is a documentation error (or maybe a code one), the documentation ([wiki](https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation)) says:

> iOS IPA Analysis works only on Mac and Linux.

But it doesn't work on Linux, just on Mac.

MobSF 1.11.16 from Linux:

![](https://i.imgur.com/2mvfE8D.png)

## STEPS TO REPRODUCE THE ISSUE

1.  Install mobSF on Linux
2. Upload an IPA

## CONSOLE OUTPUT

```
[ERROR] Static Analysis of iOS IPA requires OSX
```

## CONTENTS OF LOG FILES

No error on ` logs/MobSF.log`.

**Comment by ajinabraham** [comment]
What's your MobSF version? The support for IPA analysis in Linux is added in recent MobSF version. Please use the latest version from master branch which is `1.0.3 Beta`. I never know of a version `1.11.16` !

**Comment by anantshri** [comment]
Folks why was i tagged. If its AndroidTamer related can i ask to please
send in the details to anant <@> anantshri <dot> info
-Anant

**Comment by noraj** [comment]
@anantshri I'm sorry, it was me, I wanted to tag @ajinabraham but the poor github auto-completion tricked me.

**Comment by noraj** [comment]
@ajinabraham To have the precise commit version I'm using:

```bash
pkgver() {
  cd Mobile-Security-Framework-MobSF

  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
}
```

Version: `489.712e800-1`

**Comment by ajinabraham** [comment]
@noraj
This is pretty old and the version you are printing is Django I guess not MobSF. 
We moved from Python 2 to 3 long time back. You are using an outdated version of MobSF.

**Comment by noraj** [comment]
@ajinabraham I see you are now at commit `775.8fcebdf`, but please don't forget to update your issue template to explain to people opening issue how to check the MobSF version installed !

**Comment by ajinabraham** [comment]
MobSF version is printed on the console when you run the server and the WebUI footer section on pretty much all recent releases.

**Comment by noraj** [comment]
@ajinabraham Yeah but write that here https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/.github/ISSUE_TEMPLATE.md in a comment so future people opening an issue will know that when filling the template.

**Comment by ajinabraham** [comment]
Also Github issues are strictly for bugs or feature requests. Anything that is not in scope will be closed immediately. For discussions you should use our slack channel as described in the issue template.

**Comment by ajinabraham** [comment]
It's already mentioned
Paste the output generated at your console/terminal (This output will have version and distro details)

**Comment by noraj** [comment]
@ajinabraham This is not a discussion, I thought either there was a bug (IPA not supported) or a documentation issue but that was just me with a too old version.

**Comment by ajinabraham** [comment]
It's not a big either, hence the issue was closed promptly

**Comment by noraj** [comment]
@ajinabraham I only pasted `[ERROR] Static Analysis of iOS IPA requires OSX`, this is not self explanatory, an the CLI tool should show the version too.

**Comment by noraj** [comment]
Anyway, I'll try to update the blackarch package of mobsf https://raw.githubusercontent.com/BlackArch/blackarch/master/packages/mobsf/PKGBUILD, I'll made a PR there.
