### ISSUE TITLE
[Feature request] updating archlinux package for mobsf

### ISSUE THREAD

**Issue by noraj** [MobSF/Mobile-Security-Framework-MobSF#800]
## EXPLANATION OF THE ISSUE

I started the work here https://github.com/BlackArch/blackarch/pull/2143, but updating mobSF from a very old version the the actual master (changing version of python and of a lot of dependencies) is a lot of work and i need help for that.

**Comment by ajinabraham** [comment]
@noraj We are pretty much busy with the enhancements for MobSF. You should touch base with the original author of that for BlackArch in packaging. I can help if there is anything specific with MobSF is required.

**Comment by ajinabraham** [comment]
I am closing this thread. But feel free to comment for any MobSF related support.
