### ISSUE TITLE
How to fix when i run “run.bat” file?some promblem is hanppen!

### ISSUE THREAD

**Issue by safebaseline** [MobSF/Mobile-Security-Framework-MobSF#811]
Fatal Python error: Py_Initialize: unable to load the file system codec
  File "E:\MobFS\Mobile-Security-Framework-MobSF\venv\lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

Current thread 0x000028ec (most recent call first):

**Comment by ajinabraham** [comment]
This is issue with your environment. Not MobSF issue. Make sure you have virtualenv and python 3.
For support use slack channel and not github issues

**Comment by MouyNgim** [comment]
When I run cmd run.bat on Windows, there is a problem like shown below:
**The system cannot find the path specified.**

How to resolve this issue?
