### ISSUE TITLE
uplaod apk file

### ISSUE THREAD

**Issue by safebaseline** [MobSF/Mobile-Security-Framework-MobSF#813]
[ERROR] Saving to DB (E:\MobFS\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable

[2018-12-16 13:13:04]
[ERROR] Rendering to Template (E:\MobFS\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[1m[91m[ERROR] 'NoneType' object does not support item assignment[0m

**Comment by ajinabraham** [comment]
Closing due to lack of response.
