### ISSUE TITLE
Make releases more constantly

### ISSUE THREAD

**Issue by Edu4rdSHL** [MobSF/Mobile-Security-Framework-MobSF#817]
Please, make releases more constantly, the BlackArch team are going to package it tool in the distro but the latest release are more than 300 commits down compared with the master branch.

**Comment by Edu4rdSHL** [comment]
See https://github.com/BlackArch/blackarch/pull/2143

**Comment by ajinabraham** [comment]
I will create a release soon. We normally create a version when there is a major improvement or change.

**Comment by ajinabraham** [comment]
New Release: https://github.com/MobSF/Mobile-Security-Framework-MobSF/releases/tag/v1.0.3Beta

**Comment by Edu4rdSHL** [comment]
@ajinabraham thank you.
