### ISSUE TITLE
setting doesn't take effect

### ISSUE THREAD

**Issue by Ryaninf** [MobSF/Mobile-Security-Framework-MobSF#821]
## EXPLANATION OF THE ISSUE

MOBSF_VER = "v1.0.2 Beta"
I run MobSF on docker, and want to config Dynamic Analyzer, but when I change setting on  MobSF/settings.py, it doesn't take effect.

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```
1.start docker container
`docker start fc6cdc6415d8`
`docker exec -it fc6cdc6415d8 /bin/bash`
2.change settting.py as below
![image](https://user-images.githubusercontent.com/19621374/50430929-e4d08980-0901-11e9-8d04-adbfb4b7e85d.png)
3.restart docker container
`docker restart fc6cdc6415d8`
4.open Dynamic Analyzer on browser, and click "Create Environment", and console log as below
![image](https://user-images.githubusercontent.com/19621374/50430938-f7e35980-0901-11e9-8823-796767c348d5.png)
5.so I guess setting is doesn't work

## CONSOLE OUTPUT
console log:
![image](https://user-images.githubusercontent.com/19621374/50430938-f7e35980-0901-11e9-8823-796767c348d5.png)

**Comment by ajinabraham** [comment]
You cannot do VirtualBox based dynamic analysis with dockerized MobSF. See Documentation https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation

Also in docker containers settings are loaded from `~/.MobSF/config.py`
If you like to use `settings.py`, set USE_HOME to False in `settings.py`
