### ISSUE TITLE
Download linkerror

### ISSUE THREAD

**Issue by A-AFTAHI** [MobSF/Mobile-Security-Framework-MobSF#822]
hi please make sure that there is no error in the VM download link https://drive.google.com/uc?export=download&confirm=sxIY&id=0B_Ci-1YbMqshY0xrYl9IWHVTVFU for dynamic analysis

**Comment by superpoussin22** [comment]
https://drive.google.com/uc?id=0B_Ci-1YbMqshY0xrYl9IWHVTVFU&export=download if working fine for me
