### ISSUE TITLE
Mapping key not found.  'rules'

### ISSUE THREAD

**Issue by vinothkumar19** [MobSF/Mobile-Security-Framework-MobSF#824]
![screenshot 14](https://user-images.githubusercontent.com/45356663/50625686-afeeb300-0f4f-11e9-9d57-96aa1c418e89.png)

Hints : Mobsf Successfully installed in windows machine.

Apk static analysis working properly but APPX static analysis not working properly.

**Comment by ajinabraham** [comment]
Please share the appx over slack channel to reproduce this issue

**Comment by vinothkumar19** [comment]
please find the attchment of APPX file

[Windows-App-Studio-Sample-App-1.8.0.0-Appx4Fun.com.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/2729272/Windows-App-Studio-Sample-App-1.8.0.0-Appx4Fun.com.zip)

**Comment by ajinabraham** [comment]
Reproduced this on Windows 10.

**Comment by ajinabraham** [comment]
Fixed by: https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/845

**Comment by techman-github** [comment]
I am getting a similar error.

![Capture](https://user-images.githubusercontent.com/54284670/71654224-a06a9b80-2d56-11ea-9e90-f67dd98a6428.PNG)

How can I solve it???

**Comment by ajinabraham** [comment]
Update MobSF to latest version

**Comment by Sulikta123** [comment]
I m using Mobsf version 3.2.I am getting a similar error while testing a windows application. Android testing works fine.
![Mobsf issue](https://user-images.githubusercontent.com/68074608/104702457-09dc0300-573c-11eb-99a5-c72f7a8ac8d0.PNG)
