### ISSUE TITLE
Dynamic Analysis reconfiguration

### ISSUE THREAD

**Issue by A-AFTAHI** [MobSF/Mobile-Security-Framework-MobSF#826]
Hi, i wondering if i have to reconfigure the VM fo dynamic analysis each time i reboot the VM.
Thanks

**Comment by 0x00xx** [comment]
You  can simply create a snapshot with your configuration and tell MobSF to boot that Snapshot where you have configured everything? Does that solve your problem?

**Comment by ajinabraham** [comment]
Snapshots will do it for x86 VM
