### ISSUE TITLE
[Feature Request] Updating Android version of VM

### ISSUE THREAD

**Issue by 0x00xx** [MobSF/Mobile-Security-Framework-MobSF#830]
Since I wanted to try the framework with an application, which has min SDK 23, which is Android 6.0, I was wondering if it is possible to update the provided Android VM to a newer version.
The current VM runs Android 4.2 iirc.

Thanks in advance.

**Comment by ajinabraham** [comment]
We are going to do away with VMs real soon for Dynamic Analysis. I am afraid we won't be supporting anymore x86 VMs and instead support real ARM devices where most APKs work.

**Comment by iamjack22** [comment]
Hi, 
full disclosure: I understand ARM emulator is not supported as stated in the documentation for the current MobSF version. Nevertheless, I had been attempting to run ARM emulator on an version 0.9.5.2. I have also specified the path with MobSF_AVD.py and it runs perfectly. But when I check AVD manager on Android studio, It fails to download or grab the Nexus5API16 packages from Mobsf ARM emulator and spits out an error messages saying packages-xposed-16 missing, I tried giving it an android 4.1 image manually, but the emulator doesn't boot up. 

I pretty sure 0.9.5.2 works fine with ARM Emulator as portrait on a youtube video posted by you. Hence, I humbly seek your assistance on this matter that I've been stuck on for weeks. 

Looking forward to hear from you.  Cheers!

**Comment by ajinabraham** [comment]
@iamjack22 We stopped supporting emulator since android studio updates make it difficult for us to maintain the ARM images.

We are working on making a huge revamp to our Dynamic Analysis suite at the moment to use Geneymotion VMs. It will be merged to master soon.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1067
