### ISSUE TITLE
support for proguard deobfuscation

### ISSUE THREAD

**Issue by xandfury** [MobSF/Mobile-Security-Framework-MobSF#839]
Android apps when published are often obfuscated using tools such as proguard. This makes reverse engineered java source harder to understand and find bugs with.

[deguard](http://apk-deguard.com/) claims to de-obfuscate apks with nearly 80% accuracy. [Link to paper](https://files.sri.inf.ethz.ch/website/papers/deguard.pdf)

**Comment by ajinabraham** [comment]
This is an online tool. We can only integrate open source tools available in binaries or packages. We will  watchout this space but will close this request as there is no immediate action possible.
