### ISSUE TITLE
UnicodeEncodeError during APK upload

### ISSUE THREAD

**Issue by TheAxZim** [MobSF/Mobile-Security-Framework-MobSF#844]
## EXPLANATION OF THE ISSUE

Very minor issue... but APKs with weird names (not ascii characters) fail to be uploaded to MobSF's static analyzer. We were testing some Japanese applications with katakana in the APK filename and it triggered the below issue.

e.g. モニタリング_2019.apk

## CONSOLE OUTPUT

```
2019-01-16 05:52:12 ERROR    Internal Server Error: /upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/home.py", line 72, in as_view
    return upload.upload_html()
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/home.py", line 117, in upload_html
    response_data = self.upload()
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/home.py", line 150, in upload
    file_type, file_name_lower))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 64-68: ordinal not in range(128)
[16/Jan/2019 05:52:12] "POST /upload/ HTTP/1.0" 500 78428
```

## Workaround

Rename the files

## Fix

Capture the exception correctly? The frontend just shows stuck at 'uploading 100%'.

**Comment by ajinabraham** [comment]
The filename works fine in latest MobSF.
```
Mobile Security Framework v1.0.3 Beta

REST API Key: ****
OS: Darwin
Platform: Darwin-18.2.0-x86_64-i386-64bit
[INFO] Finding JDK Location in Linux/MAC....
[INFO] JDK 1.7 or above is available
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
System check identified no issues (0 silenced).
January 17, 2019 - 11:05:35
Django version 2.1.4, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[17/Jan/2019 11:06:20] "GET / HTTP/1.1" 200 7723
[17/Jan/2019 11:06:20] "GET /static/css/cover.css HTTP/1.1" 200 2879
[17/Jan/2019 11:06:20] "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 200 2132
[17/Jan/2019 11:06:20] "GET /static/css/dropzone.css HTTP/1.1" 200 12587
[17/Jan/2019 11:06:20] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 109518
[17/Jan/2019 11:06:20] "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 200 32351
[17/Jan/2019 11:06:20] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[17/Jan/2019 11:06:20] "GET /static/js/jquery.min.js HTTP/1.1" 200 95786
[17/Jan/2019 11:06:20] "GET /static/js/dropzone.js HTTP/1.1" 200 64400
[17/Jan/2019 11:06:20] "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 304 0
[17/Jan/2019 11:06:20] "GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 200 23320
[INFO] MIME Type: application/vnd.android.package-archive FILE: モニタリング_2019.apk

[INFO] Performing Static Analysis of Android APK
[17/Jan/2019 11:07:16] "POST /upload/ HTTP/1.1" 200 287
[INFO] Starting Analysis on : モニタリング_2019.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Converting AXML to XML
[INFO] Reading Android Manifest
[INFO] Parsing AndroidManifest.xml
[INFO] Fetching icon path
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
...
```

Could you please share an APK that causes this issue.

**Comment by ajinabraham** [comment]
Closing as there is no response

**Comment by kalsankkiran** [comment]
Hi ajinabraham,

Can you please help in getting this resolve,

The log mentioned below,

[INFO] 30/May/2019 10:44:10 - Mobile Security Framework v1.1.1 Beta
REST API Key: 8ce1f82eaec7b41390cd0dccaf26e6eb3e40824fc0b053c1de87751f6fc23354
[INFO] 30/May/2019 10:44:10 - OS: Windows
[INFO] 30/May/2019 10:44:10 - Platform: Windows-10-10.0.17763-SP0
[INFO] 30/May/2019 10:44:10 - Finding JDK Location in Windows....
[INFO] 30/May/2019 10:44:10 - Oracle Java JDK is installed!
[WARNING] 30/May/2019 10:44:10 - Could not find VirtualBox path.
[INFO] 30/May/2019 10:44:10 - MobSF Basic Environment Check
[INFO] 30/May/2019 10:44:10 - Checking for Update.
[INFO] 30/May/2019 10:44:10 - No updates available.
May 30, 2019 - 10:44:11
Django version 2.2.1, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] 30/May/2019 10:44:42 - "GET / HTTP/1.1" 200 7723
[INFO] 30/May/2019 10:44:42 - "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/css/cover.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/js/jquery.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/js/dropzone.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/css/dropzone.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:42 - "GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:45 - MIME Type: application/vnd.android.package-archive FILE: cdhsandroid build.apk
[INFO] 30/May/2019 10:44:45 - Performing Static Analysis of Android APK
[INFO] 30/May/2019 10:44:45 - "POST /upload/ HTTP/1.1" 200 227
[INFO] 30/May/2019 10:44:45 - Starting Analysis on :ANDROID BUILD.apk
[INFO] 30/May/2019 10:44:45 - Generating Hashes
[INFO] 30/May/2019 10:44:46 - Unzipping
[INFO] 30/May/2019 10:44:48 - Getting Hardcoded Certificates/Keystores
[INFO] 30/May/2019 10:44:48 - APK Extracted
[INFO] 30/May/2019 10:44:48 - Reading Android Manifest
[INFO] 30/May/2019 10:44:48 - Parsing AndroidManifest.xml
[INFO] 30/May/2019 10:44:48 - Fetching icon path
[INFO] 30/May/2019 10:44:48 - Extracting Manifest Data
[INFO] 30/May/2019 10:44:48 - Fetching Details from Play Store: com.colorado.mycobenefits
[INFO] 30/May/2019 10:44:50 - Manifest Analysis Started
[INFO] 30/May/2019 10:44:50 - Static Android Binary Analysis Started
[INFO] 30/May/2019 10:44:50 - Static Android Resource Analysis Started
[INFO] 30/May/2019 10:44:50 - Reading Code Signing Certificate
[INFO] 30/May/2019 10:44:50 - Running APKiD 2.0.2
[ERROR] 30/May/2019 10:44:51 - internal error: 34
[ERROR] 30/May/2019 10:44:51 - Internal Server Error: /StaticAnalyzer/
[ERROR] 30/May/2019 10:44:51 - "GET /StaticAnalyzer/?name=ANDROID%20BUILD.apk&type=apk&checksum=9897d95d4a0ea361b7b3a941b03d72e0 HTTP/1.1" 500 4796
[INFO] 30/May/2019 10:44:51 - "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/css/ionicons.min.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/dash/css/skins/_all-skins.min.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/dash/css/AdminLTE.min.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/css/style.css HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/plugins/slimScroll/jquery.slimscroll.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/js/jquery.bootstrap-growl.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/plugins/fastclick/fastclick.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/plugins/jQuery/jQuery-2.1.4.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/dash/js/app.min.js HTTP/1.1" 304 0
[INFO] 30/May/2019 10:44:51 - "GET /static/js/docs.js HTTP/1.1" 304 0
