### ISSUE TITLE
not find /sdcard/mobsec_status

### ISSUE THREAD

**Issue by safebaseline** [MobSF/Mobile-Security-Framework-MobSF#848]
[2019-01-24 08:53:11]
[ERROR] adb_command (/home/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/shared.py, LINE 67 "result = subprocess.check_output(args)"): Command '['/home/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.57.101:5555', 'shell', 'cat', '/sdcard/mobsec_status']' returned non-zero exit status 1.

**Comment by ajinabraham** [comment]
What is your environment? 
Are you using VirtualBox VM?
Is this occurring for every app?

**Comment by ajinabraham** [comment]
Closing as there is no response
