### ISSUE TITLE
Apkid Incomplete results

### ISSUE THREAD

**Issue by bajobongo** [MobSF/Mobile-Security-Framework-MobSF#853]
apkid is quite old now. Current version is 1.2.1 but MobSF uses 1.0.0. Is it possible to update it, as I notice that it sometimes generates incorrect results for different versions of applications. The same applications have correct results on newer apkid version. Thanks in advance

**Comment by superpoussin22** [comment]
the version 1.0.0  is the version of the python script for apkid , but last version is in MobSF  yara is up to date and also the dictionnary from apkid is up to date too

**Comment by bajobongo** [comment]
Are you sure? I see many differences between StaticAnalyzer/tools/apkid/apkid.py and StaticAnalyzer/tools/apkid/rules/rules.yarc included in current MobSF and current apkid built from https://github.com/rednaga/APKiD. Could you re-check?

**Comment by superpoussin22** [comment]
rules.yarc is not updated each time they do a change in Master Branch, as soon as a new stable rules.yarc is ready I will compile it and put it in MobSF.  I'm waiting for the merge of pending PR's regarding dictionnary rules before compiling a new version.
you can compile a new dictionnary for test and see if it solve your issue.

**Comment by superpoussin22** [comment]
you can test branch apkid_rulesupdate , I just create it with updated rules

**Comment by bajobongo** [comment]
Thank you. I've checked and unfortunately problem is still observed. I did scan on version A of my app, then did scan on version B of my APP (change between version is negligible and not related to APKiD findings). Results of both scans in APKiD section are different:

ANTI-VM | COMPILER | OBFUSCATOR | PACKER | DROPPER | MANIPULATOR | ANTI-ASSEMBLY | ANTI-DEBUG | ABNORMAL PATTERN
-- | -- | -- | -- | -- | -- | -- | -- | --
packet.name 3e63f9e693cfc685d1a61917d7a95300 v2.v2.v2 | Build.TAGS checkpossible ro.secure check | Jack 4.xdx |   |   |   |   |   |   |  
packet.name 7982f5ffd9b25e29d4f7385e3e60c391 v1.v1.v1 | Build.FINGERPRINT checkBuild.MODEL checkBuild.MANUFACTURER checkBuild.PRODUCT checkBuild.BOARD checkpossible Build.SERIAL checkBuild.TAGS checknetwork operator name checkpossible vm check | Jack 4.xdx |   |   |   |   |   | Debug.isDebuggerConnected() check

However more tests show that problem isn't related to APKiD nor rules versions.
I did the test calling manually scan using apkid.py integrated with the MobSF on both applications and on both I've got correct results:

```
import importlib.util
spec = importlib.util.spec_from_file_location("module.name",  '/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apkid/apkid.py')
foo = importlib.util.module_from_spec(spec)
spec.loader.exec_module(foo)
foo.scan('/root/Mobile-Security-Framework-MobSF/uploads/3e63f9e693cfc685d1a61917d7a95300/3e63f9e693cfc685d1a61917d7a95300.apk', 1000, False)
```

results in:

> [*] /root/Mobile-Security-Framework-MobSF/uploads/3e63f9e693cfc685d1a61917d7a95300/3e63f9e693cfc685d1a61917d7a95300.apk!classes.dex
> |-> anti_debug : Debug.isDebuggerConnected() check
> |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, network operator name check, possible Build.SERIAL check, possible vm check
> |-> compiler : Jack 4.x, dx
> [*] /root/Mobile-Security-Framework-MobSF/uploads/3e63f9e693cfc685d1a61917d7a95300/3e63f9e693cfc685d1a61917d7a95300.apk!classes2.dex
> |-> anti_vm : Build.TAGS check, possible ro.secure check
> |-> compiler : Jack 4.x, dx

`foo.scan('/root/Mobile-Security-Framework-MobSF/uploads/7982f5ffd9b25e29d4f7385e3e60c391/7982f5ffd9b25e29d4f7385e3e60c391.apk', 1000, False)`

results in:
> [*] /root/Mobile-Security-Framework-MobSF/uploads/7982f5ffd9b25e29d4f7385e3e60c391/7982f5ffd9b25e29d4f7385e3e60c391.apk!classes.dex
>  |-> anti_debug : Debug.isDebuggerConnected() check
>  |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, network operator name check, possible Build.SERIAL check, possible vm check
> |-> compiler : Jack 4.x, dx
> [*] /root/Mobile-Security-Framework-MobSF/uploads/7982f5ffd9b25e29d4f7385e3e60c391/7982f5ffd9b25e29d4f7385e3e60c391.apk!classes2.dex
> |-> anti_vm : Build.TAGS check, possible ro.secure check
> |-> compiler : Jack 4.x, dx


Do you have any idea what could be wrong? Unfortunately I cannot share the app.

**Comment by superpoussin22** [comment]
ok found why , need to find a way to solve this

**Comment by superpoussin22** [comment]
@bajobongo can you try branch apkid_better_result ?

**Comment by ajinabraham** [comment]
This should be fixed in latest master

**Comment by bajobongo** [comment]
Confirmed and fixed. Thank you.
