### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ITmustang** [MobSF/Mobile-Security-Framework-MobSF#854]
I've noticed with analyzing an apk, if you click on 'start dynamic analysis'. it automatically installs the app on the device/emulator, regardless of if you already have app installed. i propose adding a simple check to see if the app is already installed on phone before continuing. thanks!

**Comment by ajinabraham** [comment]
The dynamic analyzer flow tries to install the app after static analysis is done. It's too much work to fetch info from the phone regarding an already installed app.
