### ISSUE TITLE
DynamicAnalyzer Installing apk fails (Failure [INSTALL_FAILED_OLDER_SDK])

### ISSUE THREAD

**Issue by AdmiralGaust** [MobSF/Mobile-Security-Framework-MobSF#865]
I know the virtual machine you provided runs an older version of android because of Xposed Framework . But what should I do when the application I am trying to install does not support older versions. 

DynamicAnalyzer shows nothing in logs but when I tried to install it with adb I get this error

```
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
	pkg: /data/local/tmp/SEEK Job Search_v6.5.0_apkpure.com.apk
Failure [INSTALL_FAILED_OLDER_SDK]
```

VM is running absolutely fine and I am able to intercept the pre-installed apps data with burp proxy without any ssl pinning issues.

**Comment by ajinabraham** [comment]
Github Issues are for bugs / feature requests only. Use slack for discussions and queries
