### ISSUE TITLE
[ERROR] No module named 'yara'

### ISSUE THREAD

**Issue by f00bar10** [MobSF/Mobile-Security-Framework-MobSF#867]
## EXPLANATION OF THE ISSUE
Hi MobSF guys! Thanks for this amazing tool.

First of all:
1. MobSF version installed --> Mobile Security Framework v1.0.3 Beta
2. MobSF installed as Doc says
3. APKiD installed as Doc says at https://github.com/rednaga/APKiD#installing

Having "APKID_ENABLED = True" I get the following error when analyzing an APK:
**[ERROR] No module named 'yara'**

Note1: without this module ON, I do not get any error during the analysis...
Note2: "import yara" works perfectly

## STEPS TO REPRODUCE THE ISSUE

```
1. Install MobSF as Doc says
2. Install APKiD as Doc says
3. Launch an APK analysis
```

## CONSOLE OUTPUT

```
...
[INFO] Reading Code Signing Certificate
[ERROR] No module named 'yara'
Internal Server Error: /StaticAnalyzer/
[14/Feb/2019 23:04:14] "GET /StaticAnalyzer/?name=test.apk&type=apk&checksum=X HTTP/1.1" 500 4821

```

## CONTENTS OF LOG FILES

```
[2019-02-14 23:04:14]
[ERROR] No module named 'yara'
```

**Comment by superpoussin22** [comment]
git clone --recursive https://github.com/rednaga/yara-python-1 yara-python && \
    cd yara-python && \
    python3 setup.py build --enable-dex install && \
    pip3 install apkid && \
    sed -i 's/APKID_ENABLED.*/APKID_ENABLED = True/' /root/Mobile-Security-Framework-MobSF/MobSF/settings.py

**Comment by ajinabraham** [comment]
You have to install it inside MobSF virtual environment.
