### ISSUE TITLE
Link to VirusTotal on the web UI

### ISSUE THREAD

**Issue by JoelPagliuca** [MobSF/Mobile-Security-Framework-MobSF#869]
For malware purposes we could try adding a link to VT for further investigation.

Would anyone else be interested in this?

**Comment by superpoussin22** [comment]
Virus Total report is included in the interface, what do you want to add ?

**Comment by ajinabraham** [comment]
<img width="575" alt="screenshot 2019-02-15 at 3 19 42 pm" src="https://user-images.githubusercontent.com/4301109/52848596-27aa2300-3135-11e9-8c38-0617db6f8dc2.png">
Link to VirusTotal already exists.
