### ISSUE TITLE
feature request::nsfileprotection iOS

### ISSUE THREAD

**Issue by ITmustang** [MobSF/Mobile-Security-Framework-MobSF#872]
one of the checks i usually do for iOS apps is check the executable and other important files for nsfileprotection.. https://developer.apple.com/documentation/foundation/nsfileprotectioncomplete 

i usually use FileDP for this.(http://www.securitylearn.net/2012/10/18/extracting-data-protection-class-from-files-on-ios/) 

would like to see this integrated into MobSF!! thanks!

**Comment by ajinabraham** [comment]
Added a static analysis rule.
