### ISSUE TITLE
SSLError(SSLCertVerificationError)

### ISSUE THREAD

**Issue by vedeshkm** [MobSF/Mobile-Security-Framework-MobSF#875]
Hi,

Facing below issue. Please guide

Cannot Check for updates. (D:\Security Testing\Mobile-Security-Framework-MobSF\MobSF\utils.py, LINE 100 "proxies=proxies, verify=verify)"): HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /MobSF/Mobile-Security-Framework-MobSF/master/MobSF/settings.py (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

**Comment by superpoussin22** [comment]
is your mobsf behind a proxy ?
does it have access to internet ?

BTW it shouldn't prevent from using MobSF

**Comment by vedeshkm** [comment]
@superpoussin22 ,

mobsf is not behind a proxy and yes it has access to internet.

Not sure why i'm getting the error

**Comment by ajinabraham** [comment]
This happens when certificate validation is failing. https://docs.python.org/3/library/ssl.html#ssl.SSLError

Either you are running MobSF behind a proxy or your OpenSSL is older. This is not a MobSF issue.
