### ISSUE TITLE
no such table: StaticAnalyzer_staticanalyzerandroid issue

### ISSUE THREAD

**Issue by madevaprasad** [MobSF/Mobile-Security-Framework-MobSF#876]
Hi , Please help on below issue:

[INFO] 27/Feb/2019 18:38:03 - Mobile Security Framework v1.0.5 Beta
REST API Key: 4cbe319a66e3cd8e74946b70286f1fd25971c6469a2b54fd13f63061e12e55c2
[INFO] 27/Feb/2019 18:38:03 - OS: Windows
[INFO] 27/Feb/2019 18:38:03 - Platform: Windows-10-10.0.16299-SP0
[INFO] 27/Feb/2019 18:38:03 - Finding JDK Location in Windows....
[INFO] 27/Feb/2019 18:38:03 - Oracle Java JDK is installed!
[INFO] 27/Feb/2019 18:38:03 - MobSF Basic Environment Check
[INFO] 27/Feb/2019 18:38:03 - Checking for Update.
[ERROR] 27/Feb/2019 18:38:04 -
Cannot Check for updates. (D:\Security Testing\Mobile-Security-Framework-MobSF\MobSF\utils.py, LINE 100 "proxies=proxies, verify=verify)"): HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /MobSF/Mobile-Security-Framework-MobSF/master/MobSF/settings.py (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
System check identified no issues (0 silenced).
February 27, 2019 - 18:38:04
Django version 2.1.7, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] 27/Feb/2019 18:38:19 - "GET / HTTP/1.1" 200 7723
[INFO] 27/Feb/2019 18:38:19 - "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/css/cover.css HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/jquery.min.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/dropzone.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/css/dropzone.css HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:36 - MIME Type: application/vnd.android.package-archive FILE: myapp-dev-debug.apk
[ERROR] 27/Feb/2019 18:38:36 -
Adding Scan URL to Database (D:\Security Testing\Mobile-Security-Framework-MobSF\MobSF\views\scanning.py, LINE 20 "if not db_obj.exists():"): no such table: StaticAnalyzer_recentscansdb
[INFO] 27/Feb/2019 18:38:36 - Performing Static Analysis of Android APK
[INFO] 27/Feb/2019 18:38:36 - "POST /upload/ HTTP/1.1" 200 231
[INFO] 27/Feb/2019 18:38:36 - Starting Analysis on : MYPP-DEV-debug.apk
[ERROR] 27/Feb/2019 18:38:36 - no such table: StaticAnalyzer_staticanalyzerandroid
[ERROR] 27/Feb/2019 18:38:36 - Internal Server Error: /StaticAnalyzer/
[ERROR] 27/Feb/2019 18:38:36 - "GET /StaticAnalyzer/?name=IQToolBox-DEV-debug.apk&type=apk&checksum=69ce81c350e180541280e442acfa3995 HTTP/1.1" 500 4829

**Comment by superpoussin22** [comment]
duplicate

**Comment by ajinabraham** [comment]
Migrate DB please: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
