### ISSUE TITLE
Don't Play Around. An Error just popped in!

### ISSUE THREAD

**Issue by warloccarlos** [MobSF/Mobile-Security-Framework-MobSF#880]
Hi Ajin.

I appreciate the work you have done. Thanks for it.

I installed the Mobsf today on Linux Mint. I was testing ipa and it gives me same error on MacOS as well.

'NoneType' object has no attribute 'get'
I wouldn't be able to share the ipa.

Console Logs
[ERROR] 03/Mar/2019 06:47:10 - 
Reading from Info.plist (/home/nazgul/Downloads/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/plist_analysis.py, LINE 184 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/home/nazgul/Downloads/Mobile-Security-Framework-MobSF/uploads/9bf52e9cf55a02de6a22ac7f0ee160d6/Payload/'
[ERROR] 03/Mar/2019 06:47:10 - 'NoneType' object has no attribute 'get'
[ERROR] 03/Mar/2019 06:47:10 - Internal Server Error: /StaticAnalyzer_iOS/
[ERROR] 03/Mar/2019 06:47:10 - "GET /StaticAnalyzer_iOS/?name=***************.ipa&type=ipa&checksum=9bf52e9cf55a02de6a22ac7f0ee160d6 HTTP/1.1" 500 4850

Kindly help me fix this one.

Thanks.
Regards,
Carlos

**Comment by ajinabraham** [comment]
Please share the IPA over our slack channel for further debugging.

**Comment by superpoussin22** [comment]
can you try with last MobSF version ?

**Comment by ajinabraham** [comment]
I missed the part where he mentioned IPA cannot be shared. Hence closing this issue as we cannot debug further.
