### ISSUE TITLE
Support detection of hardcoded sensitive information oAuth client_secret

### ISSUE THREAD

**Issue by alangonzalez** [MobSF/Mobile-Security-Framework-MobSF#887]
## EXPLANATION OF THE ISSUE

Mobile Applications which use the OAuth 2.0 Authorization Grant could be storing client_secret in the app.  There are best practices in how to use those.  It would be great if the scanner could pickup where they are potentially being used in plain text hardcodes, such as:

client_secret="1955279925675241571"
oauth_secret="1955279925675241571"

This is just an example, with a secret example used.

regex would be something like this, but case insensitive.  I am just putting a quick regex strawman.  This isn't entirely accurate but you should get the idea.

.\*client_secret.\*\"[a-zA-Z0-9\+/]*={0,3}$\"
.\*SECRET.\*\"[a-zA-Z0-9\+/]*={0,3}$\"
.\*OAUTH.\*\"[a-zA-Z0-9\+/]*={0,3}$\"

The last one may get the oauth client_id which may not be ideal.  

I pulled the base64 detect regex from some code I found online... see below

public static bool IsBase64String(this string s)
{
    s = s.Trim();
    return (s.Length % 4 == 0) && Regex.IsMatch(s, @"^[a-zA-Z0-9\+/]*={0,3}$", RegexOptions.None);

}

**Comment by ajinabraham** [comment]
MobSF already has a rule to detect `secret` from code.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/android_rules.py#L44

**Comment by alangonzalez** [comment]
I see, what happened in my case is the code had the code put into a hashmap.  so the 'secret =' detection code in android_rules.py didn't match.  I guess I should have been more clear in my description code example
