### ISSUE TITLE
feature request: API call to return list of scans

### ISSUE THREAD

**Issue by jbaginski** [MobSF/Mobile-Security-Framework-MobSF#888]
MobSF API has an endpoint that allows us to remotely remove a scan, but there's no way to get the list of all available scans. That feature would be useful to allow users to dynamically manage scans or build a custom scan rotation mechanism.

**Comment by superpoussin22** [comment]
@magaofei what do you think on this idea ?

**Comment by magaofei** [comment]
@superpoussin22 we are able to implements this feature.

**Comment by superpoussin22** [comment]
thanks @magaofei  I assigned it to you :)
