### ISSUE TITLE
can't setup  django.contrib.auth

### ISSUE THREAD

**Issue by p4d4ck** [MobSF/Mobile-Security-Framework-MobSF#899]
Hi, i can't setup django.contrib.auth or  admin features,  i mean .. i'm trying to setup a login page because i gonna put the MobSF  in a production server for my company but i just can't figure out how to do it  or i don't know if is just impossible to do it ...

```
> ERRORS:
?: (admin.E402) 'django.contrib.auth.context_processors.auth' must be in TEMPLATES in order to use the admin application.

System check identified 1 issue (0 silenced).
```

any hint or help about it ?

thnx

**Comment by superpoussin22** [comment]
I have published a RP for MobSF 
hope it help
https://github.com/MobSF/RP4MobSF

**Comment by ajinabraham** [comment]
We don't enable auth for MobSF by default. You can look into alternate auth systems like the one @superpoussin22 shared above.

**Comment by p4d4ck** [comment]
thank yall so much for reply  :D
