### ISSUE TITLE
feature request::ios static analysis runtime manipulation checks

### ISSUE THREAD

**Issue by ITmustang** [MobSF/Mobile-Security-Framework-MobSF#900]
in iOS applications, during pentest i always check to see if the app has run time integrity checks / anti-debuggers implemented to prevent run time manipulation using frida or objection. i see frida is on the road map. would love to see these runtime checks added! thanks! 

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md

**Comment by ajinabraham** [comment]
We already have a rule to detect jailbreak/debugger detection code. Will improve that.
