### ISSUE TITLE
No page rendering during running MobSF in Kali Linux

### ISSUE THREAD

**Issue by pra007shant** [MobSF/Mobile-Security-Framework-MobSF#901]
Hi,

During running server the web page not properly rendering (almost white page without any pictures only upload function available ). 
(log from server console) ::

|  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        

[INFO] 22/Mar/2019 12:24:10 - Mobile Security Framework v1.0.6 Beta
REST API Key: be5ea16b79ec31e51bf3f3e5002b5894fe733feddf04157270e34b8a03fd2dfa
[INFO] 22/Mar/2019 12:24:10 - OS: Linux
[INFO] 22/Mar/2019 12:24:10 - Platform: Linux-4.19.0-kali4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[INFO] 22/Mar/2019 12:24:10 - Dist: ('Kali', 'kali-rolling', 'kali-rolling')
[INFO] 22/Mar/2019 12:24:10 - Finding JDK Location in Linux/MAC....
[INFO] 22/Mar/2019 12:24:10 - JDK 1.7 or above is available
[WARNING] 22/Mar/2019 12:24:10 - Could not find VirtualBox path.
[INFO] 22/Mar/2019 12:24:10 - MobSF Basic Environment Check
[INFO] 22/Mar/2019 12:24:11 - Checking for Update.
[INFO] 22/Mar/2019 12:24:12 - No updates available.
System check identified no issues (0 silenced).
March 22, 2019 - 12:24:13
Django version 2.1.7, using settings 'MobSF.settings'
Starting development server at http://192.168.x.xxx:3425/
Quit the server with CONTROL-C.
[INFO] 22/Mar/2019 12:24:16 - "GET / HTTP/1.1" 200 7723
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1691
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/css/cover.css HTTP/1.1" 404 1667
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1724
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/js/dropzone.js HTTP/1.1" 404 1670
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1685
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1676
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1730
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/css/dropzone.css HTTP/1.1" 404 1676
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/js/dropzone.js HTTP/1.1" 404 1670
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1700
[WARNING] 22/Mar/2019 12:24:16 - "GET /static/css/dropzone.css HTTP/1.1" 404 1676
[WARNING] 22/Mar/2019 12:24:17 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1685
[WARNING] 22/Mar/2019 12:24:17 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1730
[WARNING] 22/Mar/2019 12:24:17 - Not Found: /favicon.ico
[WARNING] 22/Mar/2019 12:24:17 - "GET /favicon.ico HTTP/1.1" 404 7301

Please give the solution ASAP.

Thanks..

**Comment by ajinabraham** [comment]
How are you running it. See Documentation for latest instructions

**Comment by ajinabraham** [comment]
OK I can see that you might be running it like `python manage.py runserver` . from `Starting development server at http://192.168.x.xxx:3425/`
We have moved from dev server to gunicorn. use `./run.sh` or `run.bat`

**Comment by aliluyala** [comment]
its work!
just change it:
MobSF>settings.py

#STATIC_ROOT = (
#os.path.join(BASE_DIR, 'static/')
#)
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static") ]
THANK YOU!!!
