### ISSUE TITLE
Don't Play Around. An Error just popped in!

### ISSUE THREAD

**Issue by lmy-0** [MobSF/Mobile-Security-Framework-MobSF#904]
![QQ截图20190325103946](https://user-images.githubusercontent.com/48897617/54891958-7c864980-4eea-11e9-9755-682a81d581eb.png)

log:
[debug.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3001290/debug.log)

**Comment by ajinabraham** [comment]
Read FAQ. migrate your database

**Comment by ajinabraham** [comment]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
