### ISSUE TITLE
 In Dynamic Analysis Unable to capture the MobSF_VM to MobSF in Kali Linux

### ISSUE THREAD

**Issue by Lakshmi4** [MobSF/Mobile-Security-Framework-MobSF#908]
[INFO] 26/Mar/2019 12:41:12 - Downloading Application Data from Device
[INFO] 26/Mar/2019 12:41:12 - Deleting Dump Status File
[INFO] 26/Mar/2019 12:41:12 - Creating TAR of Application Files.
[INFO] 26/Mar/2019 12:41:12 - Waiting for TAR dump to complete...
[INFO] 26/Mar/2019 12:41:13 - Dumping Application Files from Device/VM
[INFO] 26/Mar/2019 12:41:13 - Stopping ADB
[INFO] 26/Mar/2019 12:41:13 - Dynamic Analysis Report Generation
[INFO] 26/Mar/2019 12:41:13 - Dynamic API Analysis
[INFO] 26/Mar/2019 12:41:13 - Dynamic File Analysis
[INFO] 26/Mar/2019 12:41:13 - Performing Malware Check on extracted Domains
[INFO] 26/Mar/2019 12:41:16 - Malware Database is up-to-date.
[INFO] 26/Mar/2019 12:41:17 - Generating Downloads
[INFO] 26/Mar/2019 12:41:17 - 
Fetching Exported Activity & Activity List from DB
[INFO] 26/Mar/2019 12:41:21 - Starting CapFuzz Web UI
Running Web GUI at *:1337
[INFO] 26/Mar/2019 12:41:27 - CapFuzz UI Started
Loading Requests

**Comment by ajinabraham** [comment]
In complete log. Closing the issue. Please read guidelines before opening bugs.

**Comment by Lakshmi4** [comment]
Hi,

From one month to till now i am suffering this issue.
