### ISSUE TITLE
Snapshot restoring problem with Virtualbox 6

### ISSUE THREAD

**Issue by rleroi** [MobSF/Mobile-Security-Framework-MobSF#909]
Hi, I'm trying to setup Dynamic analysis using Virtualbox 6 and the MobSF VM 0.2.
After making a snapshot i cant restore it, does it have to do with Virtualbox 6 compatibility? (Maybe there are guest additions for Virtualbox 5 installed inside the MobSF VM?)

Virtualbox gives me the following error when manually or via Dynamic analysis trying to restore the snapshot:
NS_ERROR_FAILURE (0x80004005)
Component: SessionMachine

**Comment by shellux** [comment]
Same error here with virtualbox 6 on Ubuntu 18.04

**Comment by ajinabraham** [comment]
You might need to use VirtualBox 5 till we have a fix for this
