### ISSUE TITLE
Can I use this MobSF framework offline?

### ISSUE THREAD

**Issue by Joyoe** [MobSF/Mobile-Security-Framework-MobSF#912]
Just a quick question:

Can I use the MobSF offline?

Cause I found that the MobSF working in a B/S mode, and the network is only needed when launching and checking the update by running the script `./run.sh`

Can I just disable the update check and deploy the service in internal network?

**Comment by superpoussin22** [comment]
without internet access, you will not be able to check for new version, check url for "bad" domain , and get antivirus report but it will work without problem 

So yes:  you can use it on internal network and without modifying anything

**Comment by ajinabraham** [comment]
For questions please use slack channel. GitHub issues is strictly for bug reports or feature requests.
