### ISSUE TITLE
Getting GET error when loading bootstrap based homepag

### ISSUE THREAD

**Issue by akholicz** [MobSF/Mobile-Security-Framework-MobSF#918]
I installed mobsf and after opening the link i am getting the warnings like this
![Screenshot from 2019-04-09 15-12-56](https://user-images.githubusercontent.com/46276318/55838970-1c42fa80-5adb-11e9-8a33-bf671a8d17a3.png)
![Screenshot from 2019-04-09 15-13-03](https://user-images.githubusercontent.com/46276318/55838984-249b3580-5adb-11e9-8976-7d54c3c88e50.png)

[INFO] 09/Apr/2019 22:06:44 - "GET / HTTP/1.1" 200 7723
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 09/Apr/2019 22:06:44 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726

and after opening the link i am not getting the images and the apk is not scanning

**Comment by ajinabraham** [comment]
MobSF moved from development server. Dev server is not supported. Read updated documentation before opening issues.

**Comment by youshaoduo** [comment]
I have the same issue. And where is the updated documentation???
`[INFO] 20/Apr/2019 15:07:07 - Mobile Security Framework v1.0.7 Beta
REST API Key: 101ba16a7dd7ead40441fc01397a0bb017b74b82fd3c1bc1e5b698bf7bc1ef6e
[INFO] 20/Apr/2019 15:07:07 - OS: Darwin
[INFO] 20/Apr/2019 15:07:07 - Platform: Darwin-18.2.0-x86_64-i386-64bit
[INFO] 20/Apr/2019 15:07:07 - Finding JDK Location in Linux/MAC....
[INFO] 20/Apr/2019 15:07:07 - JDK 1.7 or above is available
[WARNING] 20/Apr/2019 15:07:07 - Could not find VirtualBox path.
[INFO] 20/Apr/2019 15:07:07 - MobSF Basic Environment Check
[INFO] 20/Apr/2019 15:07:07 - Checking for Update.
[INFO] 20/Apr/2019 15:07:08 - No updates available.
[DEBUG] 20/Apr/2019 15:07:08 - Apps ready_event triggered. Sending autoreload_started signal.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/venv/lib/python3.7/site-packages/django/contrib/auth/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/venv/lib/python3.7/site-packages/django/contrib/contenttypes/locale with glob **/*.mo.
System check identified no issues (0 silenced).
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/venv/lib/python3.7/site-packages/django/contrib/sessions/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/venv/lib/python3.7/site-packages/django/contrib/messages/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/venv/lib/python3.7/site-packages/django/contrib/staticfiles/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/StaticAnalyzer/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/DynamicAnalyzer/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/MobSF/locale with glob **/*.mo.
[DEBUG] 20/Apr/2019 15:07:08 - Watching dir /Users/youshaoduo/Desktop/MobSF/MalwareAnalyzer/locale with glob **/*.mo.
April 20, 2019 - 15:07:08
Django version 2.2, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[INFO] 20/Apr/2019 15:07:11 - "GET / HTTP/1.1" 200 7723
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 20/Apr/2019 15:07:11 - "GET /static/favicon.ico HTTP/1.1" 404 1657`

> MobSF moved from development server. Dev server is not supported. Read updated documentation before opening issues.

**Comment by dineshkumarinxs** [comment]
Me too facing the issue, not clear on what you were referring as DEV server. Also please share the link of the updated documentation

**Comment by aliluyala** [comment]
its work!
just change it:
MobSF>settings.py

#STATIC_ROOT = (
#os.path.join(BASE_DIR, 'static/')
#)
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static") ]
THANK YOU!!!
