### ISSUE TITLE
Unable to find package 'Microsoft.CodeAnalysis.BinSkim'

### ISSUE THREAD

**Issue by mohsin1122** [MobSF/Mobile-Security-Framework-MobSF#919]
Hi,
when i try to run setup.py
following error occurs

`Unable to find package 'Microsoft.CodeAnalysis.BinSkim'
Traceback (most recent call last):
  File "setup.py", line 443, in <module>
    _install_remote()
  File "setup.py", line 435, in _install_remote
    tools_binskim()
  File "setup.py", line 168, in tools_binskim
    '-o', mobsf_subdir_tools
  File "C:\Program Files\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\mohsin.mustafa1\\MobSF\\\\Tools\\nuget.exe', 'install', 'Microsoft.CodeAnalysis.BinSkim', '-Pre', '-o', 'C:\\Users\\mohsin.mustafa1\\MobSF\\\\Tools\\']' returned non-zero exit status 1.`

plz help me in this regard

**Comment by ajinabraham** [comment]
Do you have the required tools installed?
There are requirements for Windows installation.
See: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/install/windows/readme.md

**Comment by mohsin1122** [comment]
yes i have installed all the pre recs for windows environment

**Comment by mohsin1122** [comment]
@ajinabraham  waiting for reply.

**Comment by ajinabraham** [comment]
We will try to reproduce this

**Comment by mohsin1122** [comment]
@ajinabraham  any update??

**Comment by ajinabraham** [comment]
You need to install `Microsoft.CodeAnalysis.BinSkim` tool if the automated install fails
