### ISSUE TITLE
Getting corrupted pdf report from MobSF rest api in case of zip souce code file

### ISSUE THREAD

**Issue by arjunpalex** [MobSF/Mobile-Security-Framework-MobSF#920]
My name is Arjun. I used MobSF rest apis in my python application. All the formats are working fine except the zip source code. I am able to upload the zip source file and init the scan, able to get the scan results in json format. Finally before deleting the scan i am retrieving the results as PDF, the file is getting created and its a corrupted file. I changed the pdf extension to json then i got the below json,
{"scan_type": "Type is not Allowed"}
I tried the same file with MobSF WebApplication and i am able to download the report as pdf file.

Including the screen shots below,

![Screenshot from 2019-04-11 12-29-13](https://user-images.githubusercontent.com/49511440/55936989-7667cb00-5c55-11e9-8c77-556ae274c50c.png)
above screen shot is when we tried to open the corrupted pdf file which we got from the MobSF rest api.

![Screenshot from 2019-04-11 12-31-47](https://user-images.githubusercontent.com/49511440/55937124-d199bd80-5c55-11e9-9fa1-4e153d59f629.png)
above screen shot is the json results after scanning.

Including the code which i used below,

    print("MobSF scan initiated")
    scanner = MobSFScanner()
    scan_result_path = "/home/arjun/Downloads/"
    data = scanner.upload("/home/arjun/Project/Misc Files/Archive.zip")
    print("upload response: " + data)
    result = scanner.scan(data)
    write_to_file("mobsf_result.json", result, scan_result_path)
    scanner.pdf(data, scan_result_path)
    scanner.delete(data)
    print("MobSF scan completed")

[Note: The file "Archive.zip" is shared by you in the below link,
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/725]

The pdf function is below,
    
        print("Generate PDF report")
        response = requests.post(self.server + '/api/v1/download_pdf', data=data, headers=headers, stream=True)
        with open(file_path + "mobsf_pdf_result.pdf", 'wb') as flip:
            for chunk in response.iter_content(chunk_size=1024):
                if chunk:
                    flip.write(chunk)
        print("Report saved as report.pdf")

![zip_source_code_pdf_report _issue](https://user-images.githubusercontent.com/49511440/55938354-d318b500-5c58-11e9-8f18-8a3e4b392ba6.png)
Above screen shot is the response object that we are getting.

Please help asap. Thanks in advance.

**Comment by ajinabraham** [comment]
Thanks for the neat bug report. I had reproduced this issue. Working on a fix.

**Comment by arjunpalex** [comment]
Thanks for the confirmation.

Thanks & Regards
Arjun

________________________________

**Comment by ajinabraham** [comment]
Works fine for me in latest master 
```

import json
import requests

SERVER = "http://127.0.0.1:8000"
APIKEY = '**'
HASH = '0c9ec74b0f46a88279d25e49804c7b20'


def pdf():
    """Generate PDF Report"""
    print("Generate PDF report")
    headers = {'Authorization': APIKEY}
    data = {"hash": HASH , "scan_type": "ioszip"}
    response = requests.post(SERVER + '/api/v1/download_pdf',  data=data, headers=headers, stream=True)
    with open("report.pdf", 'wb') as flip:
        for chunk in response.iter_content(chunk_size=1024):
            if chunk:
                flip.write(chunk)
    print("Report saved as report.pdf")


def json_resp():
    """Generate JSON Report"""
    print("Generate JSON report")
    headers = {'Authorization': APIKEY}
    data = {"hash": HASH, "scan_type": "ioszip"}
    response = requests.post(SERVER + '/api/v1/report_json', data=data, headers=headers)
    print(response.text)


pdf()
json_resp()
```

**Comment by ajinabraham** [comment]
<img width="1144" alt="Screenshot 2019-05-17 at 2 29 26 PM" src="https://user-images.githubusercontent.com/4301109/57948645-32995e80-78b0-11e9-9ce4-3f080da17000.png">

**Comment by arjunpalex** [comment]
We are getting the upload response as below,
{"scan_type": "zip", "hash": "0c9ec74b0f46a88279d25e49804c7b20", "file_name": "Archive.zip"}
And i found in your code that you used "scan_type" as "ioszip". I am getting this object after upload file function call. Hope manipulating this object is not a good solution. 

Also what about the JAVA, IOS source code scanning? Pasting the object screen shot below,

![upload_response](https://user-images.githubusercontent.com/49511440/57980889-b0936c00-7a4e-11e9-9cdb-6347d2a53d8f.png)

Kindly help on this

**Comment by ajinabraham** [comment]
If you see the REST API documentation, https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/3.-REST-API-Documentation
For PDF and JSON APIs the supported scan_types are different. For ZIP files, you need to explicitly mention what kind of zip it is. But yes it might be confusing comparerd to other APIs. I will see if anything can be done here as an enhancement.
