### ISSUE TITLE
Update VM configuration documentation with host network setup instructions

### ISSUE THREAD

**Issue by benbadio** [MobSF/Mobile-Security-Framework-MobSF#921]
## EXPLANATION OF THE ISSUE
While trying to set up the MobSF VirtualBox VM using the instructions in the docs I kept running into an issue where my VM IP address wasn't shown during boot-up of the VM. The "IP Management" line didn't show the IP address. After searching through issues here I found that other people had the same problem (#267 and #837 for example) but that the common response was that this was a due to an improperly configured host network. While this answer is correct, it's not very informative and it doesn't help users solve the issue they're running into.

After trying different things suggested in the issues I looked through and finding that none of them worked, I discovered on my own the real problem: The host network used for adapter 1 **must have DHCP enabled**. This requirement isn't mentioned anywhere in the documentation, and based on the amount of confused users posting about this issue, it seems like it's not safe to assume users will know that they need to do this.

## SUGGESTION
Please add the following to the VM configuration docs (**before** the current first step):
1. In VirtualBox, open the Host Network Manager (File > Host Network Manager)
2. If a host network is not already present, create a new host network.
3. In the host network's DHCP settings tab (viewable by clicking "Properties") make sure the "DHCP Enabled" box is checked.

**Comment by ajinabraham** [comment]
Will take a look soon.

**Comment by ajinabraham** [comment]
Thanks for that. Docs updated.
