### ISSUE TITLE
Unable to install MobSF on Windows 10

### ISSUE THREAD

**Issue by catchdebanjan** [MobSF/Mobile-Security-Framework-MobSF#923]
## STEPS TO REPRODUCE THE ISSUE

```
1. Run setup.bat
2. It fails while installing cryptography. Manually installing cryptography by using pip install doesn't help either. 
.
```

## CONSOLE OUTPUT
![image](https://user-images.githubusercontent.com/41503360/56603204-87beb900-65ff-11e9-93ff-57137eaf7982.png)
![image](https://user-images.githubusercontent.com/41503360/56603448-0e739600-6600-11e9-9d69-fae4cd09f0b1.png)
![image](https://user-images.githubusercontent.com/41503360/56603512-277c4700-6600-11e9-93c6-8e5e27c8078b.png)
![image](https://user-images.githubusercontent.com/41503360/56603560-38c55380-6600-11e9-8f8e-e911f084f3b8.png)
![image](https://user-images.githubusercontent.com/41503360/56603585-424ebb80-6600-11e9-805c-4336d7c065a1.png)

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
Not a MobSF issue/bug. You need to install cryptography module that is compatible with your OS for MobSF to run.

**Comment by catchdebanjan** [comment]
Isnt the installer able to determine the compatible version ? Given that installer is pushing it. It isn't a pre-req, Otherwise installation steps should be updated to reflect that.

**Comment by ajinabraham** [comment]
Installer doesn't install further dependencies need for MobSF's dependencies. You need an environment where` pip install -r requirements.txt` works without any issues.

**Comment by catchdebanjan** [comment]
can you help me understand if the issue is with cryptography installation or openSSL library itself ? I am trying to understand what fails. Both cryptography(when installed independently) and OpenSSL without any issues
