### ISSUE TITLE
Portal loads incorrectly

### ISSUE THREAD

**Issue by catchdebanjan** [MobSF/Mobile-Security-Framework-MobSF#925]
## EXPLANATION OF THE ISSUE
The MOBSF portal doesn't load correctly

## STEPS TO REPRODUCE THE ISSUE

```
1. Upon loading the MobSF portal on 127.0.0.1:8000 
2. There are lots of errors (HTTP 404) on the console
3. Also the portal on the browser looks broken.



## CONSOLE OUTPUT
![image](https://user-images.githubusercontent.com/41503360/56683188-544a6000-66cd-11e9-8c09-70a02bf669b2.png)



## CONTENTS OF LOG FILE
```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

<!--
BEFORE POSTING YOUR ISSUE/BUG
- These comments won't show up when you submit the issue.
- GitHub issues ARE NOT FOR SUPPORT, DISCUSSIONS AND QUESTIONS! 
- If you have questions, use our slack channel. Request invitation here https://goo.gl/6cYU5a.
- Installation problems with regards to requirements.txt or VirtualBox in not considered as a MobSF issue.
- Reproduce issue in the latest master and try to add as much detail as possible.
- If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.
- Once you open a bug, you should also provide additional information if requested. 
- Failure to do so in 25 days will result in closure of the bug without further communication.
-->

**Comment by ajinabraham** [comment]
How did you start MobSF? Looks like you are trying to run it using development server. Log file is missing in this report. Read the latest documentation. We use gunicorn for running MobSF.

**Comment by catchdebanjan** [comment]
I had manually update the static_url variable

**Comment by ajinabraham** [comment]
I can't help with code modification. You should run it as per the documentation. We have some known issues with Windows like fcntl module is not available that is being investigated. See https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/916

I don't recommend using it on Windows at the moment till that bug is fixed

**Comment by catchdebanjan** [comment]
With the modification it started working
