### ISSUE TITLE
VM for dybamic analyzer doesnt work 

### ISSUE THREAD

**Issue by catchdebanjan** [MobSF/Mobile-Security-Framework-MobSF#926]
## EXPLANATION OF THE ISSUE
The provided VM image doesn't boot on Oracle Virtual Box 

## STEPS TO REPRODUCE THE ISSUE

```
1. Following instructions at https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/11.-Configuring-Dynamic-Analyzer-with-MobSF-Android-4.4.2-x86-VirtualBox-VM

2. At the step, Save the settings and Start MobSF VM. While the VM is Booting up. Note down the VM IP. The VM refuses to boot up. 
3. An error msg can be seen on Oracle Virtual Box logs
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```
00:00:02.439301 VMSetError: F:\tinderbox\win-6.0\src\VBox\VMM\VMMR3\NEMR3Native-win.cpp(1463) int __cdecl nemR3NativeInitAfterCPUM(struct VM *); rc=VERR_NEM_VM_CREATE_FAILED
00:00:02.439334 VMSetError: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87)
00:00:02.439372 NEM: Destroying partition 0000000001cb9230 with its 0 VCpus...
00:00:02.443394 ERROR [COM]: aRC=E_FAIL (0x80004005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)}, preserve=false aResultDetail=-6805
00:00:02.443600 Console: Machine state changed to 'PoweredOff'
00:00:02.455102 Power up failed (vrc=VERR_NEM_VM_CREATE_FAILED, rc=E_FAIL (0X80004005))
00:00:02.955439 GUI: UIMachineViewScale::resendSizeHint: Restoring guest size-hint for screen 0 to 800x1280
00:00:02.955477 ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={ab4164db-c13e-4dab-842d-61ee3f0c1e87} aComponent={DisplayWrap} aText={The console is not powered up}, preserve=false aResultDetail=0
00:00:02.955694 GUI: Aborting startup due to power up progress issue detected...
## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
Which version not Virtual Box are you using?
We have reports that Virtual Box 6 has issues. Please use version 5. Also make sure that virtualization is supported by VirtualBox.

**Comment by catchdebanjan** [comment]
I am on virtual box 6, will downgrade and retry

**Comment by ajinabraham** [comment]
Closing as it's a duplicate
