### ISSUE TITLE
Static folder files are not loaded in MobSF v1.0.7 Beta

### ISSUE THREAD

**Issue by SecureByte** [MobSF/Mobile-Security-Framework-MobSF#927]
I installed version 1.0.7 Beta with git command and after all installation process, I can not see the site correctly.

Windows 10-x64
MobSF 1.0.7 Beta

Static root in settings.py
STATIC_ROOT = (
    os.path.join(BASE_DIR, 'static')
)

#Static files (CSS, JavaScript, Images)
#https://docs.djangoproject.com/en/dev/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#256MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 268435456

Log file :
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 26/Apr/2019 23:35:03 - "GET /static/favicon.ico HTTP/1.1" 404 1657
[ERROR] 26/Apr/2019 23:35:03 - "GET /static/favicon.ico HTTP/1.1" 500 59

I try C:\MobSF and C:\MobSF\Mobile-Security-Framework-MobSF but doesn't work.

Thank you.

**Comment by ajinabraham** [comment]
How did you start the framework?

**Comment by SecureByte** [comment]
python manage.py runserver in command prompt

**Comment by ajinabraham** [comment]
We don't use the Dev server anymore. Read documentation. Also there is a bug with Windows that we are tracking.

**Comment by kec0a** [comment]
me too, all static folder not found.

ex: 
[WARNING] 04/May/2019 23:39:16 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 04/May/2019 23:39:16 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 04/May/2019 23:39:16 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:39:16 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 04/May/2019 23:39:16 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 04/May/2019 23:39:16 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 04/May/2019 23:39:16 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 04/May/2019 23:39:16 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 04/May/2019 23:39:16 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[INFO] 04/May/2019 23:39:28 - "GET / HTTP/1.1" 200 7723
[WARNING] 04/May/2019 23:39:28 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 04/May/2019 23:39:28 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 04/May/2019 23:39:28 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 04/May/2019 23:39:28 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:39:28 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 04/May/2019 23:39:28 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:39:28 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 04/May/2019 23:39:28 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 04/May/2019 23:39:28 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[INFO] 04/May/2019 23:39:47 - "GET / HTTP/1.1" 200 7723
[WARNING] 04/May/2019 23:39:47 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 04/May/2019 23:39:47 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 04/May/2019 23:39:47 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 04/May/2019 23:39:47 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:39:47 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:39:47 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 04/May/2019 23:39:47 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 04/May/2019 23:39:47 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 04/May/2019 23:39:47 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[INFO] 04/May/2019 23:40:02 - "GET / HTTP/1.1" 200 7723
[WARNING] 04/May/2019 23:40:02 - "GET /static/css/bootstrap.min.css HTTP/1.1" 404 1687
[WARNING] 04/May/2019 23:40:02 - "GET /static/css/cover.css HTTP/1.1" 404 1663
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 404 1720
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 04/May/2019 23:40:02 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 04/May/2019 23:40:02 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/jquery.min.js HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/dropzone.js HTTP/1.1" 404 1666
[WARNING] 04/May/2019 23:40:02 - "GET /static/css/dropzone.css HTTP/1.1" 404 1672
[WARNING] 04/May/2019 23:40:02 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 404 1696
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/bootstrap.min.js HTTP/1.1" 404 1681
[WARNING] 04/May/2019 23:40:02 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 404 1726
[WARNING] 04/May/2019 23:40:02 - "GET /static/favicon.ico HTTP/1.1" 404 1657

**Comment by aliluyala** [comment]
here is the solution:

#STATIC_ROOT = (
#    os.path.join(BASE_DIR, 'static/')
#)
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static") ]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# 256MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 268435456

**Comment by aliluyala** [comment]
its work!
just change it:
MobSF>settings.py

#STATIC_ROOT = (
#os.path.join(BASE_DIR, 'static/')
#)
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static") ]
THANK YOU!!!

**Comment by 123Pro123Pro** [comment]
Edit file MobSF/settings.py

#STATIC_ROOT = (
#os.path.join(BASE_DIR, 'static/')
#)
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static") ]

THANK EVERYONE !
