### ISSUE TITLE
It would be very good if mobsf analyse socket traffic and sniff data like http traffic

### ISSUE THREAD

**Issue by smms1985black** [MobSF/Mobile-Security-Framework-MobSF#928]

**Comment by superpoussin22** [comment]
can you explain a little bit more what you would like to see in MobSF ?

**Comment by smms1985black** [comment]
1- I want see socket traffic (client/server) like http/https traffic
2- I want see analysis report of every crypto library like BouncyCastle along with crypto library android api

thnx

**Comment by ajinabraham** [comment]
MobSF currently collects all the http/https traffic. If you are interested in other traffic and uses MobSF virtualbox VM. You can use packet capture feature to collect all traffic.
https://www.virtualbox.org/wiki/Network_tips
