### ISSUE TITLE
PDF Report Generation Error(Don't Play Around. An Error just popped in!)

### ISSUE THREAD

**Issue by aliluyala** [MobSF/Mobile-Security-Framework-MobSF#933]
Mobile Security Framework v1.0.7 Beta
windows 10
python 3.6.6

Don't Play Around. An Error just popped in!
Attribute not found.

'bool' object has no attribute 'dumps'
![image](https://user-images.githubusercontent.com/24489214/57349138-8b1f7c00-718b-11e9-8b7c-f9eb11b1d2cc.png)

[INFO] 08/May/2019 12:05:01 - "GET /recent_scans/ HTTP/1.1" 200 11237
[INFO] 08/May/2019 12:05:03 - Starting Analysis on : testme.apk
[INFO] 08/May/2019 12:05:03 - Analysis is already Done. Fetching data from the DB...
[INFO] 08/May/2019 12:05:03 - "GET /StaticAnalyzer/?name=testme.apk&type=apk&checksum=858429cc9299f568002dd3553440f5c9 HTTP/1.1" 200 688277
[INFO] 08/May/2019 12:05:03 - "GET /download/858429cc9299f568002dd3553440f5c9-icon.png HTTP/1.1" 200 2663
[INFO] 08/May/2019 12:06:32 - Fetching data from DB for PDF Report Generation (Android)
[INFO] 08/May/2019 12:06:32 - Analysis is already Done. Fetching data from the DB...
信息: 用提供的模式无法找到文件。
[ERROR] 08/May/2019 12:06:32 - 'bool' object has no attribute 'dumps'
[ERROR] 08/May/2019 12:06:32 - Internal Server Error: /PDF/
[ERROR] 08/May/2019 12:06:32 - "GET /PDF/?md5=858429cc9299f568002dd3553440f5c9&type=APK HTTP/1.1" 500 4848
![image](https://user-images.githubusercontent.com/24489214/57348985-e1d88600-718a-11e9-9f5a-961c89f7ad8e.png)

**Comment by ajinabraham** [comment]
Can you share the APK that's causing the issue?

**Comment by ajinabraham** [comment]
Should be fixed in latest master. Feel free to comment with APK if issue still exist.
