### ISSUE TITLE
Error on docker image local build

### ISSUE THREAD

**Issue by deadpyxel** [MobSF/Mobile-Security-Framework-MobSF#934]
## EXPLANATION OF THE ISSUE

After trying to build the docker image locally, in the step 23/30, the build fails due to apparently a `yara` syntax error.

## STEPS TO REPRODUCE THE ISSUE

```
1. clone repo
2. Edit the `MobSF/settings.py` for Dynamic analysis (only change made in the cloned project)
3. build the docker image with `docker build -t mobsf .`
4. At step 23/30 get the error message
```

## CONSOLE OUTPUT

```
Step 23/30 : RUN git clone https://github.com/rednaga/APKiD.git &&     cd APKiD &&     python3 prep-release.py &&     cp apkid/rules/rules.yarc /root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/ &&     sed -i 's#RULES_DIR =.*#RULES_DIR =  "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer"#' /usr/local/lib/python3.6/dist-packages/apkid/rules.py &&     cd .. &&     rm -fr APKiD
 ---> Running in f749949ae078
Cloning into 'APKiD'...
[*] Compiling Yara files
Traceback (most recent call last):
  File "prep-release.py", line 49, in <module>
    rules = rules_manager.compile()
  File "/root/Mobile-Security-Framework-MobSF/APKiD/apkid/rules.py", line 58, in compile
    self.rules = yara.compile(filepaths=yara_files)
yara.SyntaxError: /root/Mobile-Security-Framework-MobSF/APKiD/apkid/rules/dex/obfuscators.yara(66): invalid field name "header"
The command '/bin/sh -c git clone https://github.com/rednaga/APKiD.git &&     cd APKiD &&     python3 prep-release.py &&     cp apkid/rules/rules.yarc /root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/ &&     sed -i 's#RULES_DIR =.*#RULES_DIR =  "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer"#' /usr/local/lib/python3.6/dist-packages/apkid/rules.py &&     cd .. &&     rm -fr APKiD' returned a non-zero code: 1
```

## CONTENTS OF LOG FILES

```
No logs generated
```

Notes:
- Using the prebuilt docker image works fine, but I need the dinamic analysis part, that's why I am building it locally;
- I am running this on a Ubuntu 18.04.2 LTS x64, using zsh as terminal;

**Comment by ajinabraham** [comment]
Out of the box dynamic analysis doesn't work with dockerized MobSF

**Comment by deadpyxel** [comment]
My problem is in the docker build, is that related?

**Comment by superpoussin22** [comment]
there's an issue with apkid we are on it

**Comment by deadpyxel** [comment]
Thanks @superpoussin22 , let me know if there's any additional info you need

**Comment by superpoussin22** [comment]
for the moment you can remove this block:

> #update apkid rules
RUN git clone https://github.com/rednaga/APKiD.git && \
    cd APKiD && \
    python3 prep-release.py && \
    cp apkid/rules/rules.yarc /root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/ && \
    sed -i 's#RULES_DIR =.*#RULES_DIR =  "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer"#' /usr/local/lib/python3.6/dist-packages/apkid/rules.py && \
    cd .. && \
    rm -fr APKiD

and modify the pip install apkid line with 
pip install apkid==1.2.1

**Comment by deadpyxel** [comment]
Ok, that gave me a build success. I'll update you if I can execute Dynamic analysis.

**Comment by deadpyxel** [comment]
I am getting error messages on startup about virtualbox, but I guess that is not Docker related, so I'll discuss it on slack.

**Comment by ajinabraham** [comment]
From docker subsystem you cannot access Virtual Box. For Dynamic Analysis with MobSF Android VM. You need to install MobSF in host. It's mentioned in the documentation that dockerized MobSF only supports static analysis.

**Comment by ajinabraham** [comment]
Fixed in latest master
