### ISSUE TITLE
Feature request - give you the source code

### ISSUE THREAD

**Issue by digininja** [MobSF/Mobile-Security-Framework-MobSF#935]
I've got an app where I have the APK and the Java source as a Gradle project, would it help if there was a way for me to upload the source as well as the APK so you didn't have to do as much decompiling and could get around code obfuscation?

**Comment by ajinabraham** [comment]
MobSF already support both APK and zipped source code. We handle both of them separately. When you are zipping the source code, zip the root project directory. Refer the sample test files. Github issues are strictly for bug reports. For questions and discussions use our slack channel.

**Comment by digininja** [comment]
I'll check that out.

You need to update your issue template, it currently says:

```
<!-- ## IMPORTANT -->
<!-- Issues are ONLY for reporting bugs and feature requests. 
```
