### ISSUE TITLE
apkid error

### ISSUE THREAD

**Issue by 0xa-saline** [MobSF/Mobile-Security-Framework-MobSF#937]
Cloning into 'APKiD'...
[*] Compiling Yara files
Traceback (most recent call last):
  File "prep-release.py", line 49, in <module>
    rules = rules_manager.compile()
  File "/root/Mobile-Security-Framework-MobSF/APKiD/apkid/rules.py", line 58, in compile
    self.rules = yara.compile(filepaths=yara_files)
yara.SyntaxError: /root/Mobile-Security-Framework-MobSF/APKiD/apkid/rules/dex/abnormal.yara(82): invalid field name "header"
The command '/bin/sh -c git clone https://github.com/rednaga/APKiD.git &&     cd APKiD &&     python3 prep-release.py &&     cp apkid/rules/rules.yarc /root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/ &&     sed -i 's#RULES_DIR =.*#RULES_DIR =  "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer"#' /usr/local/lib/python3.6/dist-packages/apkid/rules.py &&     cd .. &&     rm -fr APKiD' returned a non-zero code: 1

**Comment by superpoussin22** [comment]
we are aware of this error and working on it

**Comment by superpoussin22** [comment]
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/934#issuecomment-490878579

**Comment by 0xa-saline** [comment]
> [#934 (comment)](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/934#issuecomment-490878579)

thks
