### ISSUE TITLE
Debug errors after I ran the command ' python manage.py runserver'

### ISSUE THREAD

**Issue by ambu05** [MobSF/Mobile-Security-Framework-MobSF#938]
@ajinabraham I have completed all the requirements setup in windows 10 for configuring MobSF. After I ran setup.py file, I ran 'python manage.py runserver' command to start the server, but it appeared like attached.
![Screenshot1](https://user-images.githubusercontent.com/50578931/57616383-8f88d200-759b-11e9-8d11-b202c896eaab.PNG)
![Screenshot2](https://user-images.githubusercontent.com/50578931/57616385-8f88d200-759b-11e9-8438-ea68d46917ad.PNG)
![Snapshot3](https://user-images.githubusercontent.com/50578931/57616569-1b9af980-759c-11e9-9656-032087bbf77a.PNG)

Please help me resolve this issue. Thanks!

**Comment by superpoussin22** [comment]
if you use run.bat it shoudl work , we have change a loto of things 

> .\venv\Scripts\activate && gunicorn -b 0.0.0.0:8000 MobSF.wsgi:application --workers=1 --timeout=1800

**Comment by ambu05** [comment]
@superpoussin22 When I run run.bat, I get this error as attached.
![Error](https://user-images.githubusercontent.com/50578931/57626651-f3b79000-75b3-11e9-9cd8-4a25268dddc0.PNG)

I am not able to resolve this error.

**Comment by ajinabraham** [comment]
There is an issue with Windows support. We will fix this in the next release.

**Comment by ajinabraham** [comment]
duplicate of https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/940
