### ISSUE TITLE
[Windows] Waitress syntax incorrect, won't launch

### ISSUE THREAD

**Issue by aph3rson** [MobSF/Mobile-Security-Framework-MobSF#940]
## EXPLANATION OF THE ISSUE

When running using `run.bat`, Waitress shows an error regarding syntax, prints a usage message, and exits.

Note that this can be fixed by moving the arguments to `waitress-serve` to the beginning of the command - Waitress is procedurally-sensitive, in that the order of the arguments matter. I can submit a PR if you'd like.

## STEPS TO REPRODUCE THE ISSUE

1. Clone the repository on a Windows host.
2. Run using `run.bat`, and observe the response.

## CONSOLE OUTPUT

```text
(venv) C:\Tools\mobsf>run.bat
Error: Specify one application only

Usage:

    waitress-serve [OPTS] MODULE:OBJECT

Standard options:

[...]
```
Waitress continues its standard usage message here.

## CONTENTS OF LOG FILES

Application doesn't launch.

**Comment by ajinabraham** [comment]
Thanks for reporting. We have couple of issues in Windows OS. This is due to an untested patch that was merged to master accidentally. We will be fixing this soon.
