### ISSUE TITLE
Error when using MobSF

### ISSUE THREAD

**Issue by Oleg9669** [MobSF/Mobile-Security-Framework-MobSF#941]
When I run MobSF, I get a lot of DEBUGs, a part is shown below. 
`[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/bs/LC_MESSAGES/django.mo first seen with mtime 1557831957.9723744
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/ast/LC_MESSAGES/django.mo first seen with mtime 1557831957.968374
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/ro/LC_MESSAGES/django.mo first seen with mtime 1557831958.0163789
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/nn/LC_MESSAGES/django.mo first seen with mtime 1557831958.0123787
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/lv/LC_MESSAGES/django.mo first seen with mtime 1557831958.0083783
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/sw/LC_MESSAGES/django.mo first seen with mtime 1557831958.0243797
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/id/LC_MESSAGES/django.mo first seen with mtime 1557831957.996377
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/sr/LC_MESSAGES/django.mo first seen with mtime 1557831958.0203793
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/km/LC_MESSAGES/django.mo first seen with mtime 1557831958.0043778
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/io/LC_MESSAGES/django.mo first seen with mtime 1557831957.996377
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/sl/LC_MESSAGES/django.mo first seen with mtime 1557831958.0203793
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/pa/LC_MESSAGES/django.mo first seen with mtime 1557831958.0163789
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/zh_Hant/LC_MESSAGES/django.mo first seen with mtime 1557831958.0323806
[DEBUG] 15/May/2019 10:56:21 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/locale/ka/LC_MESSAGES/django.mo first seen with mtime 1557831958.0003774
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/whitenoise/string_utils.py first seen with mtime 1557831975.374189
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0007_alter_validators_add_error_messages.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/contenttypes/migrations/__init__.py first seen with mtime 1557831957.5243278
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0005_alter_user_last_login_null.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/whitenoise/responders.py first seen with mtime 1557831975.374189
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0006_require_contenttypes_0002.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0003_alter_user_email_max_length.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0011_update_proxy_permissions.py first seen with mtime 1557831957.4563205
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/migrations/0001_initial.py first seen with mtime 1557831958.0323806
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/db/migrations/graph.py first seen with mtime 1557831958.208399
[DEBUG] 15/May/2019 10:56:22 - File /home/olegratnikov/Mobile-Security-Framework-MobSF/StaticAnalyzer/migrations/0001_initial.py first seen with mtime 1557916964.1032872
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py first seen with mtime 1557831958.208399
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0010_alter_group_name_max_length.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/__init__.py first seen with mtime 1557831957.4563205
[DEBUG] 15/May/2019 10:56:22 - File /home/olegratnikov/Mobile-Security-Framework-MobSF/StaticAnalyzer/migrations/__init__.py first seen with mtime 1557916964.0912838
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0004_alter_user_username_opts.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/contenttypes/migrations/0002_remove_content_type_name.py first seen with mtime 1557831957.5243278
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/sessions/migrations/__init__.py first seen with mtime 1557831958.0323806
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/contenttypes/migrations/0001_initial.py first seen with mtime 1557831957.5203273
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/whitenoise/base.py first seen with mtime 1557831975.3701885
[DEBUG] 15/May/2019 10:56:22 - File /home/olegratnikov/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api_middleware.py first seen with mtime 1557916201.121476
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0001_initial.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/whitenoise/__init__.py first seen with mtime 1557831975.3701885
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/whitenoise/scantree.py first seen with mtime 1557831975.374189
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0002_alter_permission_name_max_length.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0009_alter_user_last_name_max_length.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py first seen with mtime 1557831958.208399
[DEBUG] 15/May/2019 10:56:22 - File /home/olegratnikov/Mobile-Security-Framework-MobSF/MobSF/wsgi.py first seen with mtime 1557916201.121476
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/whitenoise/media_types.py first seen with mtime 1557831975.3701885
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/contrib/auth/migrations/0008_alter_user_username_max_length.py first seen with mtime 1557831957.45232
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py first seen with mtime 1557831958.2324016
[DEBUG] 15/May/2019 10:56:22 - File /usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py first seen with mtime 1557831958.2123995
`
I tried to run both with the indication of the port (8000), and without specifying. I will be grateful for the help.

**Comment by ajinabraham** [comment]
How are you running MobSF

**Comment by Oleg9669** [comment]
Launched as shown in this link: https://qualibrate.com/blog/quality-assurance/implement-mobsf-on-kali-linux/
OS Linux

**Comment by ajinabraham** [comment]
Please follow the official MobSF documentation. The setup has changed.
