### ISSUE TITLE
Debug errors and Don't play around. An error just popped in

### ISSUE THREAD

**Issue by G0T-R00T** [MobSF/Mobile-Security-Framework-MobSF#943]
Hi mate, 

So I installed all of the requirements on my Kali VM and all other dependencies required to run this tool. After running **python manage.py runserver** command, I see the debug errors in the console but my web interface opens up alright.

Now when I go to the Web interface, upload the APK and click on upload/Analyze. I get this error message in the Web interface:
**An error just popped in!
None
Internal error:34**

And when I look at the console I see this error along with all other debug errors.

![Capture](https://user-images.githubusercontent.com/17994770/57832925-e517e580-780c-11e9-8750-4768f27c334c.PNG)

Any help will be much appreciated.

**Comment by G0T-R00T** [comment]
Just FYI, I also tried other APK files with same issue.

**Comment by ajinabraham** [comment]
`python manage.py runserver` is not the way you run MobSF. Read latest and official documentation.

**Comment by G0T-R00T** [comment]
Thanks for the reply. In the latest documentation it asks to run
**run.sh** which I did and got the following error:

**./run.sh: line 5: venv/bin/activate: No such file or directory**

Any help will be much appreciated. Thanks

**Comment by ajinabraham** [comment]
Did you run setup?

**Comment by G0T-R00T** [comment]
Yes I did and I ran it again. I get the following error while running setup.sh 
![Capture1](https://user-images.githubusercontent.com/17994770/57895667-f90d2700-78a0-11e9-8b77-fef84ce6774a.PNG)
![Capture2](https://user-images.githubusercontent.com/17994770/57895670-f9a5bd80-78a0-11e9-8833-c365d0e0e1da.PNG)

**Comment by ajinabraham** [comment]
Do you have python3 installed? Have you done any modifications to installation script?

Please share the full logs of setup.sh script. This looks like you are running with python2

**Comment by G0T-R00T** [comment]
I definitely have Python3 installed and no modification to the installation script. Please find attached allthe logs from setup.sh script.
[logs.txt.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3189676/logs.txt.txt)

**Comment by ajinabraham** [comment]
Seems like your setup has some issues
```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
```

Try updating python3 to the latest 3.7 version. Either ways this issue is specific to your local python and not related to MobSF. If you need further support, join our slack channel. Github issues is strictly for MobSF bugs.
