### ISSUE TITLE
While uploading apk file getting an error i.e "Don't Play Around. An Error just popped in! None  relation "StaticAnalyzer_staticanalyzerandroid" does not exist LINE 1: SELECT (1) AS "a" FROM "StaticAnalyzer_staticanalyzerandroid... " 

### ISSUE THREAD

**Issue by usshah** [MobSF/Mobile-Security-Framework-MobSF#944]
Hi @ajinabraham, 
First time i'm getting an error "no such table: StaticAnalyzer_staticanalyzerandroid"
then I have deleted db.sqlite3 file and entered command python manage.py makemigrations
python manage.py migrate

then I'm getting an error "Don't Play Around. An Error just popped in!
None
relation "StaticAnalyzer_staticanalyzerandroid" does not exist LINE 1: SELECT (1) AS "a" FROM "StaticAnalyzer_staticanalyzerandroid... ^"

I have also commented out in setting.py script as per mentioned in docx (https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/8.-Use-Postgres-Database-Instead-of-Sqlite3) 
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR,
    }
}
'''
 End Sqlite3 support
 Postgres DB - Install psycopg2
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mobsf',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

----------Log file -------
[ERROR] 16/May/2019 12:22:56 - 
Adding Scan URL to Database (C:\Users\test\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\MobSF\views\scanning.py, LINE 20 "if not db_obj.exists():"): relation "StaticAnalyzer_recentscansdb" does not exist
LINE 1: SELECT (1) AS "a" FROM "StaticAnalyzer_recentscansdb" WHERE ...
                               ^

[INFO] 16/May/2019 12:22:56 - Performing Static Analysis of Android APK
[INFO] 16/May/2019 12:22:56 - "POST /upload/ HTTP/1.1" 200 225
[INFO] 16/May/2019 12:22:56 - Starting Analysis on : test.apk
[ERROR] 16/May/2019 12:22:56 - relation "StaticAnalyzer_staticanalyzerandroid" does not exist
LINE 1: SELECT (1) AS "a" FROM "StaticAnalyzer_staticanalyzerandroid...
                               ^
[ERROR] 16/May/2019 12:22:56 - Internal Server Error: /StaticAnalyzer/

I'm using
OS : Window
Database: pgAdmin |||

Can you please look into this?

**Comment by ajinabraham** [comment]
This look like your DB is not migrated properly. We have a bug in windows that will be fixed in the next release.

**Comment by usshah** [comment]
Ok will wait for the next release. Please update once you resolved the issue.
@ajinabraham  Thanks!

**Comment by ajinabraham** [comment]
Windows supported is restored in latest master
