### ISSUE TITLE
Requirement installation error in Ubuntu 18.04 

### ISSUE THREAD

**Issue by rahulkadavil** [MobSF/Mobile-Security-Framework-MobSF#946]
Whenever I'm trying to install in Linux kernel 4.18 and above I get following error:
   ERROR: Complete output from command /home/rahul/Pentest/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-r44fz4_g/yara-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-la51f1bn/install-record.txt --single-version-externally-managed --compile --install-headers /home/Mobile-Security-Framework-MobSF/venv/include/site/python3.6/yara-python:
    ERROR: running install
    running build
    running build_ext
    building 'yara' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/yara
    creating build/temp.linux-x86_64-3.6/yara/libyara
    creating build/temp.linux-x86_64-3.6/yara/libyara/modules
    creating build/temp.linux-x86_64-3.6/yara/libyara/proc
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_LINUX_PROC=1 -DHAVE_MEMMEM=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python3.6m -I/home/rahul/Pentest/Mobile-Security-Framework-MobSF/venv/include/python3.6m -c yara-python.c -o build/temp.linux-x86_64-3.6/yara-python.o
    yara-python.c:20:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-r44fz4_g/yara-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-la51f1bn/install-record.txt --single-version-externally-managed --compile --install-headers /home/rahul/Pentest/Mobile-Security-Framework-MobSF/venv/include/site/python3.6/yara-python" failed with error code 1 in /tmp/pip-install-r44fz4_g/yara-python/

**Comment by ajinabraham** [comment]
Do a google search with the exact error before posting dependency installation as bug
`sudo apt-get install python3-dev`
