### ISSUE TITLE
path length too long during performing static analysis

### ISSUE THREAD

**Issue by kracher86** [MobSF/Mobile-Security-Framework-MobSF#953]
Hi,
when i performed static analysis of attached apk I got the error:

link: [https://digifors-my.sharepoint.de/:u:/p/martin_schoeniger/EaRIShoiyVFFhjTr2owE0GcBWvzwAzCUA1w_RAf1W_A9kw?e=UQIzLD](url)

[…]
[INFO] Running JAVA path fix in Windows
dex2jar C:\Users\masc\Desktop\Mobile-Security-Framework-MobSF-Fork\uploads/d0a4fbb376fba3e5e6991ab7b8bd8fb5\classes2.dex -> C:\Users\masc\Desktop\Mobile-Security-Framework-MobSF-Fork\uploads\d0a4fbb376fba3e5e6991ab7b8bd8fb5\classes1.jar
Detail Error Information in File .\classes2-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
[….]
[ERROR] Performing Code Analysis (C:\Users\masc\Desktop\Mobile-Security-Framework-MobSF-Fork\StaticAnalyzer\views\android\code_analysis.py, LINE 70 "errors="ignore""): [Errno 2] No such file or directory: 'C:\\Users\\masc\\Desktop\\Mobile-Security-Framework-MobSF-Fork\\uploads/d0a4fbb376fba3e5e6991ab7b8bd8fb5/java_source/ch\\financefox\\app\\blocks\\contracts\\upload_content_list\\adapter\\-$$Lambda$UploadContentListAdapter$UploadContentListViewHolder$8CUla1zkMsSBr5fy-ibnbnpst3g.java'
[…]

Reason: path is to long. Windows cant process the path.

What I did:
•	The file exists in the stated path. When I manually change file name via Windows explorer I get an error that path is too long. 
•	I manually performed dex2jar conversion with latest dex2jar version with same result: „Detail Error Information in File .\wefox-error.zip. Please report this file to one of following link if possible (any one).“ I reported it to the stated link.
•	Tried enjarify in settings.py with same error.
•	I shortened the path to a minimum where MobSF is installed in. Then it worked. But what shall I do when the automatically generated path is longer?

My question: Is there any possibility to influence the automatically generated path?

Thanks for your reply.

Regards, Martin

**Comment by ajinabraham** [comment]
Windows has long path restrictions by default. You need to setup MobSF under a root drive like C:/MobSF

Dex2jar or other converters can fail with some APKs thats normal
