### ISSUE TITLE
Mapping key not found-'binskim'

### ISSUE THREAD

**Issue by Kiruthiga11246408** [MobSF/Mobile-Security-Framework-MobSF#954]
![image](https://user-images.githubusercontent.com/41776681/58422990-ace89080-80b1-11e9-8ea4-c8786816720d.png)

Hints : Mobsf Successfully installed in windows machine.

Apk static analysis working properly but APPX static analysis not working properly.

Attached the appx file:

[Core-Music-Player.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3223940/Core-Music-Player.zip)

Log file:
[INFO] 29/May/2019 12:03:53 -

  __  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/

[INFO] 29/May/2019 12:03:53 - Mobile Security Framework v1.1.1 Beta
REST API Key: a5c47c5425274e42613706109f7ab55f633b4a292b1f5583d563a3d3889b8ea8
[INFO] 29/May/2019 12:03:53 - OS: Windows
[INFO] 29/May/2019 12:03:53 - Platform: Windows-10-10.0.17763-SP0
[INFO] 29/May/2019 12:03:53 - Finding JDK Location in Windows....
[INFO] 29/May/2019 12:03:54 - Oracle Java JDK is installed!
[WARNING] 29/May/2019 12:03:54 - Could not find VirtualBox path.
[INFO] 29/May/2019 12:03:54 - MobSF Basic Environment Check
[INFO] 29/May/2019 12:03:55 - Checking for Update.
[INFO] 29/May/2019 12:03:56 - No updates available.
[INFO] 29/May/2019 12:04:12 - MIME Type: application/octet-stream FILE: core-music-player.appx
[INFO] 29/May/2019 12:04:12 - Performing Static Analysis of Windows APP
[INFO] 29/May/2019 12:04:12 - Windows Static Analysis Started
[INFO] 29/May/2019 12:04:12 - Windows Binary Analysis Started
[INFO] 29/May/2019 12:04:12 - Generating Hashes
[INFO] 29/May/2019 12:04:12 - Extracting APPX
[INFO] 29/May/2019 12:04:12 - Unzipping
[INFO] 29/May/2019 12:04:13 - Starting Binary Analysis - XML
[INFO] 29/May/2019 12:04:13 - Reading AppxManifest
[INFO] 29/May/2019 12:04:13 - Starting Binary Analysis
[INFO] 29/May/2019 12:04:14 - Running lokal analysis.
[INFO] 29/May/2019 12:04:14 - Running binskim.
[ERROR] 29/May/2019 12:04:14 - 'binskim'
[ERROR] 29/May/2019 12:04:14 - Internal Server Error: /StaticAnalyzer_Windows/
ERROR:django.request:Internal Server Error: /StaticAnalyzer_Windows/

**Comment by rezamnejad** [comment]
I see this issue is fixed in the docker container, however I still see it only when analyzing the appx of my local instance of MobSF I installed today using git clone. Has the fix not been merged to the git repo?

**Comment by rezamnejad** [comment]
Disregard, I missed moving my VM's windows_vm_priv_key.asc to the MobSF instance.

**Comment by ajinabraham** [comment]
Windows Static Analysis doesn't work on docker out of the box. You need to pull latest mobsf and re run setup.bat

**Comment by rezamnejad** [comment]
Disregard, I have it installed locally, but I missed moving the windows_vm_priv_key.asc key to Mobile-Security-Framework-MobSF/MobSF.

**Comment by Sulikta123** [comment]
I m using mobsf version 3.2.5 in windows 10.I m able to scan APK file but not able to scan APPX file.
Please help me .
![Mobsf issue](https://user-images.githubusercontent.com/68074608/104989417-6b53e880-5a40-11eb-82af-bcf8b27e3ace.PNG)

**Comment by ajinabraham** [comment]
This should be fixed in the latest master (3.2.8 or above)
