### ISSUE TITLE
adb server version (41) doesn't match this client (39); killing...

### ISSUE THREAD

**Issue by ambu05** [MobSF/Mobile-Security-Framework-MobSF#958]
While setting up MobSF Dynamic Analyser with Genymotion 4.4 custom phone, I am getting the below attached error, when I click on the 'Create Environment' inside Dynamic analyser.
![Error](https://user-images.githubusercontent.com/50578931/58631219-7d2ec800-82ff-11e9-976c-b81795ac5d13.PNG)

**Comment by ajinabraham** [comment]
You might have Android studio or other ADB server running. Kill everything before doing dynamic analysis. This is not a bug.
