### ISSUE TITLE
upgrading version of SQLite in linux 

### ISSUE THREAD

**Issue by Kiruthiga11246408** [MobSF/Mobile-Security-Framework-MobSF#960]
raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version) 

 - getting this error while running setup.sh in linux. How to configure the upgraded  version of sqlite.

**Comment by superpoussin22** [comment]
can you provide more details on your linux setup ?

**Comment by Kiruthiga11246408** [comment]
Following pre-requisites are installed:
1.Python 3.6
2.JDK 7
3.CPU is 32-bit supported

We try to run /.setup.sh that time above error came.

**Comment by superpoussin22** [comment]
Ubuntu ? Debian ?

**Comment by Kiruthiga11246408** [comment]
Amazon Linux

**Comment by superpoussin22** [comment]
can you try

> $ python
Python 3.7.3 (default, Apr 12 2019, 16:23:13) 
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.27.2'

**Comment by Kiruthiga11246408** [comment]
import sqlite3
sqlite3.sqlite_version

this displays version 3.7.17
But setup.sh is looking for 3.8.3

**Comment by superpoussin22** [comment]
yes Django 2.2.* requires 3.8.3 or greater 
I think you must downgrade Django to 2.1.*

> pip install Django==2.1.*
or change in requirements.txt (which would be better

**Comment by Kiruthiga11246408** [comment]
Now it is working. Thank you for the help.

**Comment by ajinabraham** [comment]
@superpoussin22 Why downgrade? Why not upgrade sqlite ?

**Comment by superpoussin22** [comment]
@ajinabraham : info I found on internet regarding this isuue says you must downgrade Django , not sure aws linux provide an uodate for sqlite , but agree that this is always better to upgrade when possible 
I have no aws linux to test
