### ISSUE TITLE
No HTTP Requests are being captured on mac OS VM and Genymotion 4.4 device

### ISSUE THREAD

**Issue by ambu05** [MobSF/Mobile-Security-Framework-MobSF#963]
Hi Ajin, I am performing dynamic analysis on MacOS VM installed on Virtual box on windows and using genymotion 4.4 device on windows. I'm unable to capture HTTP(s) requests.

**Comment by ajinabraham** [comment]
Is MobSF and the Genymotion device on the same network? Are they able to communicate? There is not enough information. hence closing this.
