### ISSUE TITLE
Connection timeout in Linux for Windows VM

### ISSUE THREAD

**Issue by Kiruthiga11246408** [MobSF/Mobile-Security-Framework-MobSF#965]
I have followed the steps given to config Windows VM.
When I upload .appx file following error is shown:

[INFO] 06/Jun/2019 07:05:04 - Windows VM configured.
[INFO] 06/Jun/2019 07:05:04 - Uploading sample. 
[ERROR] 06/Jun/2019 07:07:13 - [Errno 110] Connection timed out
[ERROR] 06/Jun/2019 07:07:13 - Internal Server Error: /StaticAnalyzer_Windows/

I am not able to find any folder with "StaticAnalyzer_Windows" name.
Please help me to sort this out.
Thanks in advance.

**Comment by ajinabraham** [comment]
` Connection timed out` is due to some network connectivity issues. There is no folder named `StaticAnalyzer_Windows` It's a route. Please take an effort when posting bugs. Don't post incomplete reports like this.

**Comment by srivga** [comment]
Hi I am getting the following error:

The applications aborts abruptly, please help

OSError at /recent_scans/
[Errno 5] Input/output error
Request Method: GET
Request URL: http://34.234.211.107/recent_scans/
Django Version: 2.1.7
Exception Type: OSError
Exception Value: [Errno 5] Input/output error
Exception Location: /root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/site-packages/colorama/ansitowin32.py in write_plain_text, line 196
Python Executable: /root/mobsf/Mobile-Security-Framework-MobSF/venv/bin/python3
Python Version: 3.6.8
Python Path: ['/root/mobsf/Mobile-Security-Framework-MobSF',
'/root/mobsf/Mobile-Security-Framework-MobSF/venv/bin',
'/root/mobsf/Mobile-Security-Framework-MobSF/venv/lib64/python3.6',
'/root/mobsf/Mobile-Security-Framework-MobSF/venv/lib64/python3.6/lib-dynload',
'/usr/lib64/python3.6',
'/usr/lib/python3.6',
'/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/site-packages',
'/root/mobsf/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages',
'/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages',
'/root/mobsf/Mobile-Security-Framework-MobSF']
Server time: Wed, 12 Jun 2019 04:14:57 +0000
Traceback Switch to copy-and-paste view
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/core/handlers/exception.py in inner
34. response = get_response(request)
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/core/handlers/base.py in _get_response
111. resolver_match = resolver.resolve(request.path_info)
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/urls/resolvers.py in resolve
491. for pattern in self.url_patterns:
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/utils/functional.py in __get__
37. res = instance.__dict__[self.name] = self.func(instance)
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/urls/resolvers.py in url_patterns
533. patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/utils/functional.py in __get__
37. res = instance.__dict__[self.name] = self.func(instance)
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/urls/resolvers.py in urlconf_module
526. return import_module(self.urlconf_name)
▶ Local vars
/root/mobsf/Mobile-Security-Framework-MobSF/venv/lib64/python3.6/importlib/__init__.py in import_module
126. return _bootstrap._gcd_import(name[level:], package, level)
▶ Local vars
<frozen importlib._bootstrap> in _gcd_import
994. <source code not available>
▶ Local vars
<frozen importlib._bootstrap> in _find_and_load
971. <source code not available>
▶ Local vars
<frozen importlib._bootstrap> in _find_and_load_unlocked
955. <source code not available>
▶ Local vars
...
...
...
...
...
...
...
...
...
...
...
