### ISSUE TITLE
Don't Play Around. An Error just popped in!

### ISSUE THREAD

**Issue by hackgod512** [MobSF/Mobile-Security-Framework-MobSF#975]
Plaese give solution for this .  
Below is the log from terminal :

[INFO] 11/Jun/2019 06:30:55 - "GET / HTTP/1.1" 200 7723
[INFO] 11/Jun/2019 06:30:55 - "GET /static/favicon.ico HTTP/1.1" 200 370070
[INFO] 11/Jun/2019 06:31:06 - MIME Type: application/vnd.android.package-archive FILE: diva-beta.apk
[INFO] 11/Jun/2019 06:31:06 - Performing Static Analysis of Android APK
[INFO] 11/Jun/2019 06:31:06 - "POST /upload/ HTTP/1.1" 200 211
[INFO] 11/Jun/2019 06:31:06 - Starting Analysis on : diva-beta.apk
[INFO] 11/Jun/2019 06:31:06 - Generating Hashes
[INFO] 11/Jun/2019 06:31:06 - Unzipping
[ERROR] 11/Jun/2019 06:31:06 - 
Unzipping Error (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/shared_func.py, LINE 86 "with zipfile.ZipFile(app_path, "r") as zipptr:"): File is not a zip file
[INFO] 11/Jun/2019 06:31:06 - Using the Default OS Unzip Utility.
error:  -fn or any combination of -c, -l, -p, -t, -u and -v options invalid
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer
[/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/9f7023fc25b3ce7ec1af34822e765d8b.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/9f7023fc25b3ce7ec1af34822e765d8b.apk or
        /Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/9f7023fc25b3ce7ec1af34822e765d8b.apk.zip, and cannot find /Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/9f7023fc25b3ce7ec1af34822e765d8b.apk.ZIP, period.
[ERROR] 11/Jun/2019 06:31:06 - 
Unzipping Error (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/shared_func.py, LINE 104 "dat = subprocess.check_output(['unzip', '-qq', '-l', app_path])"): Command '['unzip', '-qq', '-l', '/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/9f7023fc25b3ce7ec1af34822e765d8b.apk']' returned non-zero exit status 9.
[INFO] 11/Jun/2019 06:31:06 - Getting Hardcoded Certificates/Keystores
[ERROR] 11/Jun/2019 06:31:06 - 
Getting Hardcoded Certificates/Keystores (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/android/cert_analysis.py, LINE 31 "for file_name in files:"): 'NoneType' object is not iterable
[INFO] 11/Jun/2019 06:31:06 - APK Extracted
[INFO] 11/Jun/2019 06:31:06 - Converting AXML to XML
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
	... 3 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:183)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
[ERROR] 11/Jun/2019 06:31:06 - 
Getting Manifest file (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/android/manifest_analysis.py, LINE 897 "subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/tools/apktool_2.4.0.jar', '--match-original', '--frame-path', '/var/folders/rp/gh130drx2sz5c329y0k085th0000gn/T', '-f', '-s', 'd', '/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/9f7023fc25b3ce7ec1af34822e765d8b.apk', '-o', '/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/apktool_out']' returned non-zero exit status 1.
[ERROR] 11/Jun/2019 06:31:06 - 
Reading Manifest file (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/android/manifest_analysis.py, LINE 844 "if isFileExists(manifest):"): stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] 11/Jun/2019 06:31:06 - Parsing AndroidManifest.xml
[ERROR] 11/Jun/2019 06:31:06 - 
apktool failed to extract AndroidManifest.xml or parsing failed (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/android/manifest_analysis.py, LINE 35 "manifest = minidom.parseString(dat)"): a bytes-like object is required, not 'NoneType'
[WARNING] 11/Jun/2019 06:31:06 - Using Fake XML to continue the Analysis
[INFO] 11/Jun/2019 06:31:06 - Extracting Manifest Data
[INFO] 11/Jun/2019 06:31:06 - Fetching Details from Play Store: Failed
[WARNING] 11/Jun/2019 06:31:06 - Unable to get app details. Invalid application ID: Failed. 404 Client Error: Not Found for url: https://play.google.com/store/apps/details?id=Failed&hl=en&gl=us
[INFO] 11/Jun/2019 06:31:06 - Manifest Analysis Started
[INFO] 11/Jun/2019 06:31:06 - Static Android Binary Analysis Started
[INFO] 11/Jun/2019 06:31:06 - Static Android Resource Analysis Started
[INFO] 11/Jun/2019 06:31:06 - Reading Code Signing Certificate
[ERROR] 11/Jun/2019 06:31:06 - 
Reading Code Signing Certificate (/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/android/cert_analysis.py, LINE 57 "cert) if os.path.isfile(os.path.join(cert, f))]"): [Errno 2] No such file or directory: '/Users/ravinathsingh/Downloads/Mobile-Security-Framework-MobSF-master/uploads/9f7023fc25b3ce7ec1af34822e765d8b/META-INF/'
[INFO] 11/Jun/2019 06:31:06 - Running APKiD 2.0.3
[INFO] 11/Jun/2019 06:31:10 - Tracker Database is up-to-date.
[INFO] 11/Jun/2019 06:31:10 - Detecting Trackers
[ERROR] 11/Jun/2019 06:31:10 - 'NoneType' object is not iterable
[ERROR] 11/Jun/2019 06:31:10 - Internal Server Error: /StaticAnalyzer/
[ERROR] 11/Jun/2019 06:31:10 - "GET /StaticAnalyzer/?name=diva-beta.apk&type=apk&checksum=9f7023fc25b3ce7ec1af34822e765d8b HTTP/1.1" 500 4843

**Comment by superpoussin22** [comment]
are you sure your file is a zip and is not corrupt ? can you share it ?

> File is not a zip file

**Comment by hackgod512** [comment]
my file is not zip but it is an apk file. 
And i have checked many apks.
I have also checked by making zip file of the same but result is the same .

**Comment by ajinabraham** [comment]
The apk looks corrupted. 
`ZipException: zip END header not found`
Please share the apk file.

**Comment by hackgod512** [comment]
Issue resolved !!

**Comment by nikulsanal** [comment]
Please let us know how you solved the issue

**Comment by azhar-999** [comment]
How to resolve this issue?
