### ISSUE TITLE
[Bug] Malware Analysis is always good with suspicious URL's apk

### ISSUE THREAD

**Issue by Kirthikmr** [MobSF/Mobile-Security-Framework-MobSF#978]
Hi, I'm testing the apk which is loading the malware suspicious URL and creating the malware activities at main screen itself but still malware analysis is always good. I'm attaching the apk also for reference. Please check the issue and let me know if it's really bug of MobSF or not.
Thanks.
[suspicious_url_test.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3284450/suspicious_url_test.zip)

**Comment by superpoussin22** [comment]
hello 
your suspicious url did not respect the RFC so urlib will return an empty loc  ( an url must start with at minimum // to be parsed correctly by urlib )

**Comment by superpoussin22** [comment]
I just write a patch to handle this , it could be merged today

**Comment by superpoussin22** [comment]
see #981

**Comment by superpoussin22** [comment]
solved with last version
