### ISSUE TITLE
apkid.py error

### ISSUE THREAD

**Issue by adibikar** [MobSF/Mobile-Security-Framework-MobSF#983]
## ENVIRONMENT

```
OS and Version: Linux Bunsenlabs Helium 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
Python Version: Python3.5
MobSF Version: v1.1 beta
```

## EXPLANATION OF THE ISSUE

```
Error page shows after dragging apk file with message: 
Don't Play Around. An Error just popped in!
Invalid syntax.
invalid syntax (apkid.py, line 38).

And in the terminal says: 
[ERROR] 17/Jun/2019 23:28:29 - invalid syntax (apkid.py, line 38)
[ERROR] 17/Jun/2019 23:28:29 - Internal Server Error: /StaticAnalyzer/
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Run from terminal sudo ./run.sh
2. Go to Http://localhost:8000
3. Drag the apk file
4. Error page shown.
5. Same message on terminal ((apkid.py, line 38)).
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```
[INFO] 17/Jun/2019 23:27:47 - Mobile Security Framework v1.1.2 Beta
[INFO] 17/Jun/2019 23:27:47 - OS: Linux
[INFO] 17/Jun/2019 23:27:47 - Platform: Linux-4.9.0-9-amd64-x86_64-with-BunsenLabs-9.8-helium
[INFO] 17/Jun/2019 23:27:47 - Dist: ('"BunsenLabs"', '"9.8"', '"helium"')
[INFO] 17/Jun/2019 23:27:47 - Finding JDK Location in Linux/MAC....
[INFO] 17/Jun/2019 23:27:47 - JDK 1.7 or above is available
[WARNING] 17/Jun/2019 23:27:47 - Could not find VirtualBox path.
[INFO] 17/Jun/2019 23:27:47 - MobSF Basic Environment Check
[INFO] 17/Jun/2019 23:27:47 - Checking for Update.
[INFO] 17/Jun/2019 23:27:48 - No updates available.
[INFO] 17/Jun/2019 23:28:01 - MIME Type: application/vnd.android.package-archive FILE: myAPK.com.apk
[INFO] 17/Jun/2019 23:28:02 - Performing Static Analysis of Android APK
[INFO] 17/Jun/2019 23:28:02 - Starting Analysis on : myAPK.com.apk
[INFO] 17/Jun/2019 23:28:02 - Generating Hashes
[INFO] 17/Jun/2019 23:28:03 - Unzipping
[INFO] 17/Jun/2019 23:28:08 - Getting Hardcoded Certificates/Keystores
[INFO] 17/Jun/2019 23:28:08 - APK Extracted
[INFO] 17/Jun/2019 23:28:08 - Converting AXML to XML
[INFO] 17/Jun/2019 23:28:24 - Reading Android Manifest
[INFO] 17/Jun/2019 23:28:24 - Parsing AndroidManifest.xml
[INFO] 17/Jun/2019 23:28:24 - Fetching icon path
[INFO] 17/Jun/2019 23:28:25 - Extracting Manifest Data
[INFO] 17/Jun/2019 23:28:25 - Fetching Details from Play Store: com.myAPK_url
[INFO] 17/Jun/2019 23:28:28 - Manifest Analysis Started
[INFO] 17/Jun/2019 23:28:28 - Static Android Binary Analysis Started
[INFO] 17/Jun/2019 23:28:28 - Static Android Resource Analysis Started
[INFO] 17/Jun/2019 23:28:28 - Reading Code Signing Certificate
[ERROR] 17/Jun/2019 23:28:29 - invalid syntax (apkid.py, line 38)
[ERROR] 17/Jun/2019 23:28:29 - Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
MobSF needs python 3.6 or above

**Comment by adibikar** [comment]
I have updated to Python3.7, and update-alternatif the python3 to use python3.7. But the error still there `apkid.py, line 38`

**Comment by ajinabraham** [comment]
Can you share MalwareAnalyzer/views/apkid.py

**Comment by adibikar** [comment]
`# -*- coding: utf_8 -*-
import os
import logging
from django.conf import settings
from MobSF.utils import filename_from_path

logger = logging.getLogger(__name__)


def apkid_analysis(app_dir, apk_file, apk_name):
    """APKiD Analysis of DEX files"""
    if not settings.APKID_ENABLED:
        return {}
    try:
        import apkid
    except ImportError:
        logger.error("APKiD - Could not import APKiD")
        return {}
    if not os.path.exists(apk_file):
        logger.error("APKiD - APK not found")
        return {}

    apkid_ver = apkid.__version__
    from apkid.apkid import Scanner, Options
    from apkid.output import OutputFormatter
    from apkid.rules import RulesManager

    logger.info("Running APKiD %s", apkid_ver)
    options = Options(
        timeout=30,
        verbose=False,
        entry_max_scan_size=100 * 1024 * 1024,
        recursive=True
    )
    output = OutputFormatter(
        json_output=True,
        output_dir=None,
        rules_manager=RulesManager()
    )
    rules = options.rules_manager.load()
    scanner = Scanner(rules, options)
    res = scanner.scan_file(apk_file)
    try:
        findings = output._build_json_output(res)['files']
    except AttributeError:
        # apkid >= 2.0.3
        findings = output.build_json_output(res)['files']
    sanitized = {}
    for item in findings:
        filename = item['filename']
        sanitized[filename] = item['matches']
    return sanitized`

**Comment by adibikar** [comment]
```
# -*- coding: utf_8 -*-
import os
import logging
from django.conf import settings
from MobSF.utils import filename_from_path

logger = logging.getLogger(__name__)


def apkid_analysis(app_dir, apk_file, apk_name):
    """APKiD Analysis of DEX files"""
    if not settings.APKID_ENABLED:
        return {}
    try:
        import apkid
    except ImportError:
        logger.error("APKiD - Could not import APKiD")
        return {}
    if not os.path.exists(apk_file):
        logger.error("APKiD - APK not found")
        return {}

    apkid_ver = apkid.__version__
    from apkid.apkid import Scanner, Options
    from apkid.output import OutputFormatter
    from apkid.rules import RulesManager

    logger.info("Running APKiD %s", apkid_ver)
    options = Options(
        timeout=30,
        verbose=False,
        entry_max_scan_size=100 * 1024 * 1024,
        recursive=True
    )
    output = OutputFormatter(
        json_output=True,
        output_dir=None,
        rules_manager=RulesManager()
    )
    rules = options.rules_manager.load()
    scanner = Scanner(rules, options)
    res = scanner.scan_file(apk_file)
    try:
        findings = output._build_json_output(res)['files']
    except AttributeError:
        # apkid >= 2.0.3
        findings = output.build_json_output(res)['files']
    sanitized = {}
    for item in findings:
        filename = item['filename']
        sanitized[filename] = item['matches']
    return sanitized

**Comment by ajinabraham** [comment]
The code looks fine. I don't see any issues with latest code in test environments. 
Can you share me the output of the following
```
. venv/bin/activate
python --version
python -m py_compile MalwareAnalyzer/views/apkid.py
```

**Comment by adibikar** [comment]
what is .venv/bin/activate?
`python --version: Python 2.7.13` 
`python3 --version: Python 3.7.3`
`python -m py_compile MalwareAnalyzer/views/apkid.py: There is no output`
Shoud do I remove python2.7.13?

**Comment by ajinabraham** [comment]
MobSF uses venv.
There is a space after the `.`
You need to run it from within MobSF directory
```
cd Mobile-Security-Framework
./setup.sh
. venv/bin/activate
python --version
python -m py_compile MalwareAnalyzer/views/apkid.py
```

**Comment by adibikar** [comment]
```
$. venv/bin/activate
(venv) $ python --version
Python 3.5.3
(venv) $ python -m py_compile MalwareAnalyzer/views/apkid.py
(venv) $ 

I think the cause is Python version 3.5 even though in update-alternatives the python3 shows Python 3.7

**Comment by ajinabraham** [comment]
You should either remove Python 3.5 or change this line in your setup script
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/setup.sh#L23
```
python3 -m virtualenv venv -p python3.7
```

**Comment by ajinabraham** [comment]
@adibikar Did you made any progress.

**Comment by adibikar** [comment]
Hi, I am sorry for too long cz my internet down in the morning and I must wait again till 00.01 AM to reinstall python3.7 (get stuck for hours in these step cz error on `checkinstall`). I did `python3 -m virtualenv venv -p python3.7` on `setup.sh` -> `./setup.sh`. Until successfully `[INSTALL] Installation complete` with one error (same error for the 1st time install mobsf):
`ERROR: mitmproxy 3.0.2 has requirement cryptography<2.2,>=2.1.4, but you'll have cryptography 2.6.1 which is incompatible.`
Then, I run `./run.sh`, go to `localhost:8000` updload the apk-file and it run properly. Terminal:
```
...
[INFO] 20/Jun/2019 22:13:29 - Manifest Analysis Started
[INFO] 20/Jun/2019 22:13:29 - Static Android Binary Analysis Started
[INFO] 20/Jun/2019 22:13:29 - Static Android Resource Analysis Started
[INFO] 20/Jun/2019 22:13:29 - Reading Code Signing Certificate
[INFO] 20/Jun/2019 22:13:30 - Running APKiD 2.0.3
[INFO] 20/Jun/2019 22:13:42 - Updating Tracker Database....
[INFO] 20/Jun/2019 22:13:42 - Detecting Trackers
[INFO] 20/Jun/2019 22:13:44 - DEX -> JAR
[INFO] 20/Jun/2019 22:13:44 - Using JAR converter - dex2jar
[INFO] 20/Jun/2019 22:13:44 - Converting classes.dex to JAR
dex2jar /home/myUser/Downloads/Mobile-Tools/Mobile-Security-Framework-MobSF/uploads/2b12135166c0ceaef7045a167d1dcf0f/classes.dex -> /home/hunter/Downloads/Mobile-Tools/Mobile-Security-Framework-MobSF/uploads/2b12135166c0ceaef7045a167d1dcf0f/classes0.jar
[INFO] 20/Jun/2019 22:14:52 - DEX -> SMALI
[INFO] 20/Jun/2019 22:14:52 - Converting classes.dex to Smali Code
[2019-06-20 18:15:01 -0400] [21809] [INFO] Handling signal: winch
[2019-06-20 18:15:06 -0400] [21809] [INFO] Handling signal: winch
[INFO] 20/Jun/2019 22:15:07 - JAR -> JAVA
[INFO] 20/Jun/2019 22:15:07 - Decompiling classes0.jar to Java Code
[INFO] 20/Jun/2019 22:20:55 - Static Android Code Analysis Started
[INFO] 20/Jun/2019 22:20:55 - Code Analysis Started on - java_source
[INFO] 20/Jun/2019 22:20:56 - Finished Code Analysis, Email and URL Extraction
[INFO] 20/Jun/2019 22:20:56 - Extracting Strings from APK
[INFO] 20/Jun/2019 22:20:59 - Detecting Firebase URL(s)
[INFO] 20/Jun/2019 22:21:01 - Performing Malware Check on extracted Domains
[INFO] 20/Jun/2019 22:21:03 - Malware Database is up-to-date.
[INFO] 20/Jun/2019 22:21:03 - Generating Java and Smali Downloads
[INFO] 20/Jun/2019 22:21:03 - Generating Downloads
[INFO] 20/Jun/2019 22:21:03 - Zipping
[INFO] 20/Jun/2019 22:21:05 - Zipping
[INFO] 20/Jun/2019 22:21:08 - Connecting to Database
[INFO] 20/Jun/2019 22:21:08 - Saving to Database
```
```bash
$. venv/bin/activate
(venv) $ python --version
Python 3.7.3
```
And it works :D

**Comment by ajinabraham** [comment]
:+1:

**Comment by itsecforu** [comment]
hey! what to do if bash: `venv/bin/activate: No such file or directory`

**Comment by itsecforu** [comment]
how can i get . venv/bin/activate ?
my output:
```
 . venv/bin/activate
bash: venv/bin/activate: No such file or directory
```

**Comment by ajinabraham** [comment]
You should have that directory if you run setup.sh before. 
I would suggest you run setup.sh from latest master.
