### ISSUE TITLE
Internat Error: 34

### ISSUE THREAD

**Issue by adriansavarese** [MobSF/Mobile-Security-Framework-MobSF#984]
## ENVIRONMENT

```
OS and Version: Kali 2019.2 running on virtualbox oracle
Python Version: 2.7.16
MobSF Version: the last one
```

## EXPLANATION OF THE ISSUE
After upload a SDK I get Internat Error: 34; Internal Server Error: /StaticAnalyzer/
```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step: ./run.sh
2. This is the second step: Open web browser
3. Upload the file
4. I got the error 34
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
did you run setup.sh first ?

**Comment by adriansavarese** [comment]
Yes, here you have all the logs when I run it. I had a error but I don´t know what is about.
[Setup.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3306096/Setup.txt)

**Comment by superpoussin22** [comment]
just see you are using python 2.7 , mobsf is using pytnon3

**Comment by adriansavarese** [comment]
I already update to last version...same issue.

**Comment by superpoussin22** [comment]
can you install libfreetype6-dev and re-run setup.sh

**Comment by adriansavarese** [comment]
Great. It works! Thanks!
