### ISSUE TITLE
Unable to create Dynamic Analysis Report 

### ISSUE THREAD

**Issue by vinay11223** [MobSF/Mobile-Security-Framework-MobSF#985]
## ENVIRONMENT

```
OS and Version: linux 2019
Python Version: 3.6+
MobSF Version:  1.0 

## EXPLANATION OF THE ISSUE

```
after performing dynamic analysis, im unable to generate the dynamic analysis report please help me with this.

a error is appearing at CLI:
 "[ERROR] Malware DB Update (/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/domain_check.py, LINE 34 "response = requests.get(url, timeout=3, proxies=proxies, verify=verify)"): HTTPConnectionPool(host='www.malwaredomainlist.com', port=80): Read timed out."
```


## STEPS TO REPRODUCE THE ISSUE

``
1- go to dynamic analysis 
2 -start dynamic analysis & create environment 
3 -finish test
4 - on dashboard of mobsf when creating dynamic analysis report, following log is created in CLI and failed to generate report



```

## LOG FILE

`""[ERROR] Malware DB Update (/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/domain_check.py, LINE 34 "response = requests.get(url, timeout=3, proxies=proxies, verify=verify)"): HTTPConnectionPool(host='www.malwaredomainlist.com', port=80): Read timed out.""``
.
```

<!--
BEFORE POSTING YOUR ISSUE/BUG
- These comments won't show up when you submit the issue.
- GitHub issues ARE NOT FOR FEATURE REQUESTS, SUPPORT, DISCUSSIONS AND QUESTIONS! 
- If you have questions, use our slack channel. Request invitation here https://goo.gl/6cYU5a.
- Reproduce issue in the latest master and try to add as much detail as possible.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.
- Once you open a bug, you should also provide additional information if requested. 
- Failure to do so in 25 days will result in closure of the bug without further communication.
-->

**Comment by vinay11223** [comment]
![Screenshot from 2019-06-21 07-57-07](https://user-images.githubusercontent.com/48856695/59921020-d80e9780-9445-11e9-8ea7-ef4317ab7251.png)

**Comment by superpoussin22** [comment]
the error shoudl not stop  the process.
Can you upgrade your MobSf sounds like you have a very old version ?

**Comment by vinay11223** [comment]
sure

**Comment by ajinabraham** [comment]
Incomplete logs
