### ISSUE TITLE
[FEATURE] Show time according to system timezone setting

### ISSUE THREAD

**Issue by FranklinYu** [MobSF/Mobile-Security-Framework-MobSF#988]
**Is your feature request related to a problem? Please describe.**
Currently scanning time are displayed as UTC time. It takes some time to relate to local time.

**Describe the solution you'd like**
Display local time if specified by user.

**Describe alternatives you've considered**
Maybe we can let user to choose timezone, but Python already provided [`time.localtime(secs)`](https://docs.python.org/3.7/library/time.html#time.localtime) which is mostly what we want anyway.

**Additional context**
N/A

**Comment by ajinabraham** [comment]
Are you hosting the server and accessing the Web UI in same system or two systems at multiple timezone?

**Comment by FranklinYu** [comment]
Two system, same timezone. We don't have any user in other timezone so I'm not sure what's appropriate when browser and server are in different timezone.

**Comment by ajinabraham** [comment]
I am trying to understand the senario in which you are seeing this issue. So you have two systems on same timezone, server is hosted in one system and you are using the UI from a different system and the time showed is not the same as the local time showed in the system. Is that your problem?

**Comment by FranklinYu** [comment]
Is it expected to have local time? I though the current design is UTC. I don't think it matters whether they are the same system or not; it’s not picking up the local timezone setting anyway.

**Comment by superpoussin22** [comment]
UTC is something which is independant from any TZ , so the best thing will perhaps be to display UTC in the column title :) ?

**Comment by FranklinYu** [comment]
@superpoussin22 I understand that UTC would be easy to implement, but local time is more useful. If you still prefers UTC, we can make this an opt-in feature (actually I meant it by saying “if specified by user”).

**Comment by superpoussin22** [comment]
@FranklinYu : what I mean is that the scanning time must be stored as utc or timestamp in database, and the local time conversion should be done on web interface, it will allow usage from different location :)  We don't have currently user management in MobSF so what will happen if 2 differents user set a different localtime ? ( we should ensure database constistency )

**Comment by ajinabraham** [comment]
I guess we show as per timezone provided by browser.

**Comment by FranklinYu** [comment]
Ok then that can be done by JavaScript

**Comment by ajinabraham** [comment]
@FranklinYu  Upon further investigating. We won't be doing timezone detection. Instead user can set their timezone in `MobSF/settings.py`
Find your timezone identifier
```
>>> import pytz # $ pip install pytz
>>> pytz.all_timezones_set
```
And set it here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L183

**Comment by FranklinYu** [comment]
Would you also consider allowing user to set this variable via environment variable? Like

```python
TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')
```

**Comment by ajinabraham** [comment]
That's fine. Feel free to send a PR.
