### ISSUE TITLE
internal error: 34 [GET /StaticAnalyzer/ 500]

### ISSUE THREAD

**Issue by Anna61** [MobSF/Mobile-Security-Framework-MobSF#994]
When I upload and apk file in Mobsf Internal error:34 is seen.
Results are not coming. Can you please help in fix this issue.

Steps to reproduce:
1.In command prompt run "python3 manage.py runserver"
2.Go the localhost url and upload the apk file
3.Internal error:34 and in log files Internal Server Error: /StaticAnalyzer/
[ERROR] 05/Jul/2019 02:05:14 - "GET /StaticAnalyzer/?name=app-release_100_jiagu_sign.apk&type=apk&checksum=ce3fcb55d3dceb413040f066300bc78c HTTP/1.1" 500 4796will be seen.

logs:
[INFO] 05/Jul/2019 02:02:12 - MIME Type: application/vnd.android.package-archive FILE: app-release_100_jiagu_sign.apk
[INFO] 05/Jul/2019 02:02:12 - Performing Static Analysis of Android APK
[INFO] 05/Jul/2019 02:02:12 - "POST /upload/ HTTP/1.1" 200 245
[INFO] 05/Jul/2019 02:02:12 - Starting Analysis on : app-release_100_jiagu_sign.apk
[INFO] 05/Jul/2019 02:02:12 - Generating Hashes
[INFO] 05/Jul/2019 02:02:12 - Unzipping
[DEBUG] 05/Jul/2019 02:02:12 - File /usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/cp437.py first seen with mtime 1545622915.0
[INFO] 05/Jul/2019 02:02:13 - Getting Hardcoded Certificates/Keystores
[INFO] 05/Jul/2019 02:02:13 - APK Extracted
[INFO] 05/Jul/2019 02:02:13 - Reading Android Manifest
[INFO] 05/Jul/2019 02:02:13 - Parsing AndroidManifest.xml
[INFO] 05/Jul/2019 02:02:13 - Fetching icon path
[INFO] 05/Jul/2019 02:02:13 - Extracting Manifest Data
[INFO] 05/Jul/2019 02:02:13 - Fetching Details from Play Store: com.cnoocwebmobile
[WARNING] 05/Jul/2019 02:05:14 - Unable to get app details. HTTPSConnectionPool(host='play.google.com', port=443): Max retries exceeded with url: /store/apps/details?id=com.cnoocwebmobile&hl=en&gl=us (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10973e860>, 'Connection to play.google.com timed out. (connect timeout=30)'))
[INFO] 05/Jul/2019 02:05:14 - Manifest Analysis Started
[INFO] 05/Jul/2019 02:05:14 - Static Android Binary Analysis Started
[INFO] 05/Jul/2019 02:05:14 - Static Android Resource Analysis Started
[INFO] 05/Jul/2019 02:05:14 - Reading Code Signing Certificate
[INFO] 05/Jul/2019 02:05:14 - Running APKiD 2.0.3
[ERROR] 05/Jul/2019 02:05:14 - internal error: 34
[ERROR] 05/Jul/2019 02:05:14 - Internal Server Error: /StaticAnalyzer/
[ERROR] 05/Jul/2019 02:05:14 - "GET /StaticAnalyzer/?name=app-release_100_jiagu_sign.apk&type=apk&checksum=ce3fcb55d3dceb413040f066300bc78c HTTP/1.1" 500 4796

**Comment by Anna61** [comment]
Mobile-Security-Framework-MobSF v1.1

**Comment by superpoussin22** [comment]
did you run setip.sh ?
which linux distro are you using ?

**Comment by superpoussin22** [comment]
if you are using a mac: Mojave then install headers : 
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

and run `setup.sh` again

**Comment by Anna61** [comment]
> did you run setup.sh ?
> which linux distro are you using ?

yes, I have run setup.sh, no error occured.
and I'm using a mac.

**Comment by Anna61** [comment]
> if you are using a mac: Mojave then install headers :
> `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
> 
> and run `setup.sh` again

OK~I'll try again.

**Comment by Anna61** [comment]
> if you are using a mac: Mojave then install headers :
> `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
> 
> and run `setup.sh` again



> did you run setup.sh ?
> which linux distro are you using ?


I met some warning and error with running setup.sh,  hard to solve.
at last i used Docker Image, everything  runs ok. thank you very much all the same~
