### ISSUE TITLE
Wrong function names getting flagged by iOS static analyzer

### ISSUE THREAD

**Issue by peja** [MobSF/Mobile-Security-Framework-MobSF#995]
## EXPLANATION OF THE ISSUE

When scanning an iOS Swift app I get these issues:

```
 Binary make use of banned API(s)	Insecure	6	CWE-676	The binary may contain the following banned API(s) _alloca, _memcpy.
 Binary make use of malloc Function	Insecure	2	CWE-789	The binary may use malloc function instead of calloc.
```

But when running the otool manually, I get:

```
$ otool -Iv SwiftApp | grep malloc
0x00080d2c 18174 _malloc_size
0x00098a28 18174 _malloc_size
0x00000001000866f0 17907 _malloc_size
0x00000001000a0ba8 17907 _malloc_size

$ otool -Iv SwiftApp | grep _alloca
0x000805fc 17850 _$sSa28_allocateBufferUninitialized15minimumCapacitys06_ArrayB0VyxGSi_tFZ
0x0009885c 17850 _$sSa28_allocateBufferUninitialized15minimumCapacitys06_ArrayB0VyxGSi_tFZ
0x0000000100086204 17593 _$sSa28_allocateBufferUninitialized15minimumCapacitys06_ArrayB0VyxGSi_tFZ
0x00000001000a0860 17593 _$sSa28_allocateBufferUninitialized15minimumCapacitys06_ArrayB0VyxGSi_tFZ
```

Which leads me to believe that static analyzer matches only a part of the function name:

Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py

I think the correct way to perform this analysis is to report suspicious functions only if they fully match the blacklisted name.

**Comment by ajinabraham** [comment]
Will see what can be done to reduce false positives

**Comment by ajinabraham** [comment]
After investigation, we use otool and jtool for this. And the results are non standard. Hence we won't be doing anything on the results. In this particular case it is a false positive.

**Comment by peja** [comment]
> After investigation, we use otool and jtool for this. And the results are non standard. Hence we won't be doing anything on the results. In this particular case it is a false positive.

Here are the steps to reproduce this problem easily:

1. Create an empty Swift or Objective C iOS application.
2. Put a call to **objc_allocateProtocol** function in **viewDidLoad**.
3. Archive the application and create IPA file for ad hoc distribution.
4. Check the binary with **otool** manually.
5. Check IPA file with MobSF.

This is a full example:

```swift
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        _ = objc_allocateProtocol("DummyProtocol")
    }
}
```

When running otool manually we get:

```
$ otool -Iv EmptySwift | grep alloca
0x00000001000067f4    28 _objc_allocateProtocol
0x0000000100008058    28 _objc_allocateProtocol
```

However, MobSF reports:

```
Binary make use of banned API(s) | Insecure | 6 | CWE-676 | The binary may contain the following banned API(s) _alloca.
```

Which means that it flagged **objc_allocateProtocol** because it contains **alloca** string in its name.

That is absolutely wrong as those two functions are completely unrelated.

I can also provide an IPA file if requested.

**Comment by peja** [comment]
@ajinabraham Please reopen this issue.

**Comment by ajinabraham** [comment]
@peja This is a limitation with otool/jtool. These tools list out the functions in non standard form. We don't have a reliable way to get the exact function names. Hence we have to match it with a fuzzy regex. This is a pure case of false positive and can be ignored. Report generated by MobSF or any static analysis tools needs to be verified.

**Comment by peja** [comment]
> @peja This is a limitation with otool/jtool. These tools list out the functions in non standard form. We don't have a reliable way to get the exact function names. Hence we have to match it with a fuzzy regex/string match. This is a pure case of false positive and can be ignored. Report generated by MobSF or any static analysis tools needs to be verified.

Sorry @ajinabraham, but I disagree.

MobSF generates scary messages such as "Binary make use of banned API(s)" even when it's not true. I know it's impossible not to have false positives, but I think we can easily avoid them in this case.

I looked in more detail what kind of output is generated by otool and jtool, and I think it's not too difficult to parse. Here are some examples using awk one-liners, I assume it is equally simple to do in python:

```bash
$ otool -Iv EmptySwift | awk '$1 ~ /^0x/{if ($3) print $3}'
```

```bash
$ jtool -arch arm -bind -v EmptySwift | awk '$3 ~ /^0x/{if ($7) print $7}'
```

```bash
$ jtool -arch arm -lazy_bind -v EmptySwift | awk '$3 ~ /^0x/{if ($6) print $6}'
```

That would list function names one per line, and that list could be checked if it contains blacklisted function names.

Regards,
Peja

**Comment by ajinabraham** [comment]
If you feel that it could be improved and it's a great value add, feel free to send a PR.
