### ISSUE TITLE
Internal Server Error: /StaticAnalyzer/

### ISSUE THREAD

**Issue by 19oos** [MobSF/Mobile-Security-Framework-MobSF#998]
## ENVIRONMENT

```
OS and Version: ubuntu 1804
Python Version: 3.6
MobSF Version: 
```

I upload a apk and analyzer,  this happened
Error from browser:
Don't Play Around. An Error just popped in!
None
internal error: 34

Error from console:
[WARNING] 11/Jul/2019 09:20:53 - Unable to get app details. Invalid application ID: com.android.xxxxx.xxxx. 404 Client Error: Not Found for url: https://play.google.com/store/apps/details?id=com.android.xxxxx.xxxx&hl=en&gl=us
[INFO] 11/Jul/2019 09:20:53 - Manifest Analysis Started
[INFO] 11/Jul/2019 09:20:53 - Static Android Binary Analysis Started
[INFO] 11/Jul/2019 09:20:53 - Static Android Resource Analysis Started
[INFO] 11/Jul/2019 09:20:53 - Reading Code Signing Certificate
[INFO] 11/Jul/2019 09:20:53 - Running APKiD 2.0.3
[ERROR] 11/Jul/2019 09:20:53 - internal error: 34
[ERROR] 11/Jul/2019 09:20:53 - Internal Server Error: /StaticAnalyzer/
[ERROR] 11/Jul/2019 09:20:53 - "GET /StaticAnalyzer/?name=xxx.apk&type=apk&checksum=d93f1a5a0a84eaaa07efb5b947deed22 HTTP/1.1" 500 4796

**Comment by ajinabraham** [comment]
See.https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=internal+error%3A+34&type=Issues
